### ISSUE TITLE
Feature: Toggle

### ISSUE THREAD

**Issue by markfaine** [vscode-neovim/vscode-neovim#101]
I didn't see any way to toggle Neovim mode on and off.  That's important to me since some operations don't translate easily to Windows, like clipboard copy and paste, select all, etc.

**Comment by asvetliakov** [comment]
In meantime you can use insert mode, all neovim keybindings are disabled except ```<C-r>``` and ```<C-a>``` while in insert mode.

I'm assuming you're using wsl option, yeah? Clipboard is actually easy fixable for wsl interop, i'll look sometime soon into it.

**Comment by pomdtr** [comment]
This feature could be useful to be able to use the version control view

**Comment by KuenstlicheIntelligenz** [comment]
Hey, does ctrl-c work to copy in insert mode for you? In my case it exits insert mode and does not copy. Tried to turn of "Use Ctrl Keys For Insert Mode" but it wouldnt help.
Im on windows to and not using wsl.

Any suggestions?

**Comment by asvetliakov** [comment]
@KuenstlicheIntelligenz 
add to your keybindings.json
```json
			{
				"command": "-vscode-neovim.escape",
				"key": "ctrl+c",
			}
```
this will unbind ctrl+c from the escape key

Also `ctrl+insert / shift+insert` are working for copy & paste

**Comment by Callendor** [comment]
I would like to see this too

**Comment by Mills-2** [comment]
Why close this? This is a useful feature to be able to toggle between vim keybinds and standard vsCode keybinds.

**Comment by RidanDev** [comment]
Is there any new? I think this is a very useful feature to be implemented. In the Vim extension it's possible to do that by typing _ctrl+shift+p_ followed by _toggle vim mode_.

**Comment by markfaine** [comment]
I find I myself mostly using actual vim more because switching key modes back and forth all the time is cumbersome and I'm too old to learn vscode key bindings or to not constantly try to use vim bindings whenever I type in an editor. I hope this does happen though, any improvements that reduce the number of times that I have to switch keybindings is a good thing.

**Comment by gitHabbe** [comment]
I'd like this feature as well. As a vim beginner, it's comforting to quickly go back to VSCode mode for a few actions you are uncomfortable with or haven't learned yet.

**Comment by kylepollina** [comment]
I'll comment to add my support for this feature

**Comment by theol0403** [comment]
https://github.com/vscode-neovim/vscode-neovim/pull/1033
