### ISSUE TITLE
Plugin vim-expand-region doesn't work in vscode-neovim

### ISSUE THREAD

**Issue by jonasdiemer** [vscode-neovim/vscode-neovim#1011]
Hi,

looking for a way to get a selection expand feature running with vscode-neovim. As I understood, the VSCode built-in `Expand Selection` command doesn't work, so I was hoping to get https://github.com/terryma/vim-expand-region to work, but it doesn't.

Any idea why or how to fix it?

Regards

**Comment by justinmk** [comment]
visual mode has some known issues currently: https://github.com/vscode-neovim/vscode-neovim/issues?q=is%3Aissue+is%3Aopen+visual

**Comment by theol0403** [comment]
I feel like [terryma/vim-expand-region](https://github.com/terryma/vim-expand-region) should work just fine though.
