### ISSUE TITLE
<C-f> in Visual mode does not select correclty

### ISSUE THREAD

**Issue by f-squirrel** [vscode-neovim/vscode-neovim#1022]
Hey folks,
First of all, I'd like to thank you for the fantastic job you've done!

In Vim/Neovim I can select code by doing `<C-v>` or just `V` (line selection) and then scroll with `C-f>` which will add to the selection everything between the starting point until the last position of the cursor.

In VSCode/Neovim the following happens:
- `V` selects a line
- `<C-f>` jumps but there is not selection
- do `j` or `k` and the cursor jumps back to the original position.

Note: I've tested the behavior in Neovim in both configurations (with my init.vim) and as `nim -u NONE`.

Best,
DD

**Comment by theol0403** [comment]
This is fixed by pending PRs. There is one already in master, but it will be superseeded by #993
