### ISSUE TITLE
Visual Selection out of sync

### ISSUE THREAD

**Issue by BIKA-C** [vscode-neovim/vscode-neovim#1025]
The issue arises when using the command `:m '>+1<CR>gv=gv` to move lines down and `:m '<-2<CR>gv=gv` to move lines up. Apparently, it is just vscode side does not produce the proper selection highlights, but if I do it fast enough or selecting multiple lines, the text will sometimes out of sync too. Adding a cmd call `VSCodeNotifyVisual('noop', 1)` at the end does not help. I have tried to use vscode native movelines command with `VSCodeNotifyVisual`, but then neovim side is out of sync in terms of the text.

**Comment by justinmk** [comment]
search existing issues
