### ISSUE TITLE
EasyMotion draws labels on top of text characters

### ISSUE THREAD

**Issue by sudoandros** [vscode-neovim/vscode-neovim#1026]
Hi! I have a problem when EeasyMotion labels cover text characters without concealing them. It leads to hard to read result with some labels almost impossible to recognize:
![image](https://user-images.githubusercontent.com/27918948/187160670-c593109d-c67e-4a67-a4f1-ad8873c4de77.png)

Is it a known a behaviour and how can I change it? I've been trying to search for solution in docs and issues but never found this problem anywhere. Looks like characters should be concealed by default but don't for some reason.

I use Windows if it's important. My `init.vim':

```
call plug#begin(stdpath('data') . '/plugged')

Plug 'asvetliakov/vim-easymotion'
Plug 'tpope/vim-surround'
Plug 'michaeljsmith/vim-indent-object'
Plug 'bkad/CamelCaseMotion'
Plug 'terryma/vim-expand-region'
Plug 'nelstrom/vim-visual-star-search'
Plug 'tpope/vim-repeat'
Plug 'coderifous/textobj-word-column.vim'

call plug#end()

let mapleader = "\<Space>"

xmap gc  <Plug>VSCodeCommentary
nmap gc  <Plug>VSCodeCommentary
omap gc  <Plug>VSCodeCommentary
nmap gcc <Plug>VSCodeCommentaryLine

let g:camelcasemotion_key = '<leader>'

```

Great extension by the way!

**Comment by nkgm** [comment]
This is a known issue. Please see:
https://github.com/vscode-neovim/vscode-neovim/wiki/Plugins#vim-easymotion
https://github.com/asvetliakov/vim-easymotion

**Comment by sudoandros** [comment]
@nkgm As you can see from my `init.vim` I am using this fork already. Is there any information about why broken decorations may still be an issue?

**Comment by sudoandros** [comment]
Ran `PlugClean` just in case. There were no original easymotion installataion

**Comment by 7vq** [comment]
Just to clarify, like @sudoandros says, this is indeed an issue with the vscode-specific easymotion. This is different from that known issue.

Anyone know how to fix this? I'm guessing the opacity of the background color used for the hints is all that needs to change. Does anyone know what that color variable is called or how to find the variable name?
