### ISSUE TITLE
[Bug] v0.0.90 breaks `workbench.action.compareEditor.nextChange` and `workbench.action.compareEditor.previousChange`

### ISSUE THREAD

**Issue by wenfangdu** [vscode-neovim/vscode-neovim#1027]
v0.0.90 is causing `workbench.action.compareEditor.nextChange` and `workbench.action.compareEditor.previousChange` not working properly (instead of jumping to the change, the viewport twitches), v0.0.89 does not, the code causing this issue is from #919.

I use these two shortcuts all the time when comparing diffs, so it was easy for me to spot:

![image](https://user-images.githubusercontent.com/28700378/186840519-620f9634-37e7-4bfd-a541-be2fe23d698a.png)

**Comment by theol0403** [comment]
Please try with https://github.com/vscode-neovim/vscode-neovim/pull/993
If that doesn't work, try an earlier version with [`11d0d77` (#993)](https://github.com/vscode-neovim/vscode-neovim/pull/993/commits/11d0d77ac8e126d61e2db45f5f43b38e05640d12)

**Comment by wenfangdu** [comment]
@theol0403 #993 is working fine, is it a replacement for #919?

**Comment by theol0403** [comment]
It is a continuation/upgrade/redo, no need for revert.

**Comment by theol0403** [comment]
I will close this as master isn't released and won't be until that PR

**Comment by wenfangdu** [comment]
Reproducible in 0.0.92+, not in 0.0.91, seems like a regression bug, please reopen this and take a look @theol0403

**Comment by theol0403** [comment]
Yeah #919 was released as I felt the pros outweighed the cons (proper lightspeed support). Originally I was not going to release as I also changed c-u/c-d bindings but I was able to separate the changes. 

This will be fixed by #993. Until then use an older version of the extension, I made many incremental releases so it’s easy to pick.

**Comment by wenfangdu** [comment]
@theol0403 I've been stuck with v0.0.91 for nearly half a year now 😭, and can't use fixes/improvements in the newer versions, is there any way to patch this issue in the latest version?

**Comment by xiyaowong** [comment]
Same as #1365

**Comment by wenfangdu** [comment]
@xiyaowong It's not the same issue, and this issue was raised way earlier than #1375, how come this issue got closed?

**Comment by wenfangdu** [comment]
@xiyaowong It's not the same issue, and this issue was raised way earlier than #1365, how come this issue got closed?

**Comment by wenfangdu** [comment]
@xiyaowong It's not the same issue, and this issue was raised one year earlier than #1365, how come this issue got closed?
