### ISSUE TITLE
Allow setting stdpath's to avoid collision with terminal neovim

### ISSUE THREAD

**Issue by distek** [vscode-neovim/vscode-neovim#1030]
Hello!

It seems a lot of neovim plugins expect the UI to be a dedicated UI for neovim itself, and not an integration into another editor platform. Because of this, there seems to be some collisions of functionality with things such as session management, for example.

I've attempted doing a bit of a hacky work around in my `init.lua` that I found from this [post](https://www.reddit.com/r/neovim/comments/s2t0ph/overwrite_vimfnstdpathdata_without_xdg_env_var/). It's a fine idea, but doesn't seem to be working completely in practice?
When I 
`echo stdpath("data")`
it returns the original path, however, doing
`lua print(vim.fn.stdpath("data"))`
works as desired.

I can see this is not functioning on the level I need it to as I still get messages from plugins like `vim-go`, thus it appears it's still using `~/.local/share/nvim` for the data directory.

Is this within the scope of this plugin? I'm not sure how else to go about doing this, but I'd like to maintain separation between the two instances.

Thanks for the plugin!

**Comment by distek** [comment]
A weird little work around that seems to be doing alright:
- `mkdir ~/.local/share/vsc-nvim/config`
- `cp -r ~/.config/vsc-nvim ~/.local/share/vsc-nvim/config/nvim`
- `mkdir ~/.local/share/vsc-nvim/data`

And then run this from the terminal:
```
XDG_DATA_HOME=~/.local/share/vsc-nvim/data XDG_CONFIG_HOME=~/.local/share/vsc-nvim/config code
```

This could be added to a .desktop file on linux, but from the terminal is fine for now.
Unfortunately I loose things like gtk/qt theming (not sure which one vscode/electron uses), but it works.

Could also probably just link those directories instead of copying the dirs, but meh!

**Comment by justinmk** [comment]
`exists('g:vscode')` ? https://github.com/vscode-neovim/vscode-neovim#neovim-configuration

**Comment by distek** [comment]
Hi @justinmk
That doesn't really solve the issue.

As far as I'm able to find, you can't set the values returned by stdpath through any non-hacky means. Is there something else I'm not seeing in any of the docs? That page doesn't mention stdpath at all.

**Comment by theol0403** [comment]
Or use the `cond` helper for plugged.vim or `cond` parameter for packer.nvim, that should enable/disable your plugins properly.

**Comment by distek** [comment]
Looks like I'd have to do that for every plugin. That's alright, I'll just use my workaround whenever I use vs code then.

Thank you for the response.

**Comment by theol0403** [comment]
My dotfiles might help. 
You should generally think about which vim plugins to use with vscode.

https://github.com/theol0403/dotfiles/blob/master/.config/nvim/vimrc/moon/common.moon
https://github.com/theol0403/dotfiles/blob/master/.config/nvim/vimrc/moon/plugins.moon

**Comment by distek** [comment]
My idea was to mostly just avoid (neo)vim plugins in general as VScode has a pretty extensive plugin ecosystem. I could see how some plugins might make the experience a bit better without needing an expensive TS plugin for something that can be solved in a few lines of lua, though.

VScode for me, currently, is useful for stuff like debugging and whatnot. But it might end up _being_ my editor if I can figure out a pretty solid workflow.

I created this issue mainly to see if we can separate the two so I don't have to really screw with my nvim config, but also be able to use VScode while I'm getting used to it.

I also thought it might be worth creating this issue in the event someone wants to do something similar, but want's to keep their TUI neovim config completely separate, but permanently.

**Comment by justinmk** [comment]
> I created this issue mainly to see if we can separate the two so I don't have to really screw with my nvim config

That makes no sense. To solve this issue you need to screw with some config, either in vscode or Nvim. You can set 'runtimepath' in a `exists('g:vscode')` condition, and that's that. There is no reason for vscode-neovim to add another mechanism to do this.

**Comment by distek** [comment]
Here's what I ended up doing to solve this:
- In packer's config, changed the following:
```diff
    config = {
        max_jobs = 5,
        profile = {
            enable = true,
            threshold = 1
        },
+       compile_path = vim.fn.stdpath("data").."/packer/packer_compiled.lua"
    },
```
- Next, I needed to remove the old one from `~/.config/nvim/plugin/packer_compiled.lua` and then run `:PackerCompile` again from within TUI neovim

- Then in my init.lua:
```lua
if vim.g.vscode then
    local function remove(input, path)
        local retTable = {}
        local ret = ""

        for s in string.gmatch(input, "([^,]+)") do
            if string.match(s, path) == nil then
                table.insert(retTable, s)
            end
        end

        for _, v in pairs(retTable) do
            ret = ret..v..","
        end

        return ret
    end

    local newPackPath = remove(vim.o.packpath, ".local/share/nvim/site")
    local newRuntimePath = remove(vim.o.runtimepath, ".local/share/nvim/site/pack(.*)")

    vim.o.packpath = newPackPath
    vim.o.runtimepath = newRuntimePath

    -- other vscode specific neovim config goes here
else
    -- normal TUI neovim config stuffs
end
```

And this seems to have resolved the issue.

I'd like to apologize, @justinmk. It seems like I ticked a nerve with you. I promise I was not trying to be a pain in the ass, I was just hoping for the lease friction to use neovim in vscode without having to faff about with my normal configuration. I wasn't able to avoid such, but at least the extension is working as desired now.

Thanks

**Comment by justinmk** [comment]
> ```lua
>     require('vscode') -- lua/vscode.lua - has stuff to remove some of the packpaths and runtimepaths to prevent loading of TUI plugins
> ```

You could also wrap the TUI plugins in a `if vim.g.vscode` check. The point is that adding some new feature to vscode-neovim to do this kind of thing doesn't save anything. The configuration has to be done somewhere--and since the purpose of vscode-neovim is to use Nvim, why wouldn't you want your config to be in one place (the nvim config) if possible?

I also confirmed that unsetting 'packpath' is an easy way to skip all installed plugins in vscode-neovim:

```
if exists('g:vscode')
  set packpath=
  " set vscode mappings...
  nnoremap <silent> foo bar
  ...
  finish
endif
```
