### ISSUE TITLE
Work with neovim installed in docker container

### ISSUE THREAD

**Issue by meicale** [vscode-neovim/vscode-neovim#1031]
I just wonder that since this plugin can work with neovim installed in wls, it may be ok to work with other docker container which has Linux and neovim installed. Have any guys try that?

**Comment by justinmk** [comment]
https://github.com/vscode-neovim/vscode-neovim/issues/262

**Comment by theol0403** [comment]
You seem to be asking for two different things.

Neovim on local machine while working with remote vscode: current behaviour
Neovim on remote machine while working with remote vscode: #262/#1000

Either way you should be able to configure it how you like with https://github.com/vscode-neovim/vscode-neovim/issues/262#issuecomment-1208062772

**Comment by meicale** [comment]
> At this moment, I use windows 10 as my local host os and I can just use this vscode plugin in local vscode and with remote nvim (which is actually installed in wsl2 of my windows 10 laptop). I also installed my nvim and related plugins in a docker image to make it more portable. I just wonder can I achieve that and how? I walked through [#262](https://github.com/vscode-neovim/vscode-neovim/issues/262#issuecomment-1208062772)  and I have not figured out the solution yet. Can you make it more clear?

**Comment by meicale** [comment]
BTW, I do think that install all my nvim and its plugin in the same container of codespace can solve the problem. because in the container vscode and nvim are actually "local" so they can find each other and can be set up just as usually linux os. I want seperate my nvim because it is always changing and I can use the seperate docker to do editing with a relatively smaller image. It maybe not matter or I may try that solution.
