### ISSUE TITLE
Navigation in Search menu

### ISSUE THREAD

**Issue by Jendker** [vscode-neovim/vscode-neovim#1032]
Thank you for your wonderful work on the extension!

I have a question: I've seen it is possible to use the keybindings for the Explorer navigation. Is it also possible to jump to the sidebar elements e.g. to the search results without using my mouse (or repeatedly pressing TAB)?

An example: I would like to select one of the results after searching in all files. I need to press TAB multiple times to get to the results selection. This significantly brakes the workflow.
![Screenshot from 2022-09-09 10-37-59](https://user-images.githubusercontent.com/14967831/189309737-e805dc82-b851-4b52-9b31-8c3b350fb915.png)
If such navigation is impossible because of VSCode limitations, what is the common solution for the users to search in all files with VSCode & vscode-neovim?

**Comment by theol0403** [comment]
Haven't found a workflow for me personally. 

This is a vscode problem, you *might* be able to find vscode bindings that let you do that (if so make a PR), but generally VSCode does not provide a command or when context to navigate search fields.

**Comment by Jendker** [comment]
Here is a binding I am using.
```
    {
        "key": "alt+m",
        "command": "search.action.focusSearchList"
    }
```
I'm not sure if it fits to make a PR because it is specific only to Search List but if I will find something more generic I'll make a PR.

**Comment by xell** [comment]
In macOS you can use cmd+down arrow to jump to the first item of result list from the search input box, and then you can use up or down arrow keys to select.

**Comment by JohnEricson** [comment]
> In macOS you can use cmd+down arrow to jump to the first item of result list from the search input box, and then you can use up or down arrow keys to select.

Ctrl + down works on Windows too.
