### ISSUE TITLE
No code actions available when selecting text in visual mode

### ISSUE THREAD

**Issue by vvvctr** [vscode-neovim/vscode-neovim#1034]
Code actions are not working when selecting code in visual mode.
If you make the same selection with the mouse, code actions become available:

![Kapture 2022-09-10 at 18 35 33](https://user-images.githubusercontent.com/1019862/189492971-ed025600-f355-4ab1-bff9-1d65641bd75c.gif)

**Comment by theol0403** [comment]
This is because visual selection isn't sent to vscode. There are issues tracking this.

Workarounds off the top of my head:
- open code actions from F1/C-p command picker
- route code actions keybinding (ctrl+.) through neovim
	- send ctrl+. to neovim from vscode in keybindings.json
	- invoke code actions picker from neovim using VSCodeNotifyVisual
