### ISSUE TITLE
Extension breaks VS Code replace feature

### ISSUE THREAD

**Issue by Jendker** [vscode-neovim/vscode-neovim#1036]
If I start vscode's search function with C-S-p and C-f the replace button does not do anything. Only "replace all" works. Is there an easy way to fix it?

**Comment by Jendker** [comment]
For your reference: replacing works fine up to extension version v0.0.87. Seems that it got broken with v0.0.88.

**Comment by Jendker** [comment]
I have poked around and it looks like this commit brakes the replace feature: https://github.com/vscode-neovim/vscode-neovim/commit/f783274b4207d66047139113ad790b6ac25e0fd3. Reverting this commit fixed it for me on v0.0.89 tag.
I am not sure what exactly was the issue though.

**Comment by david-crespo** [comment]
It seems to be working again. macOS Venture 13.2.1, VS Code 1.76.0, plugin version v0.0.97.

**Comment by Jendker** [comment]
You are right, thanks!
