### ISSUE TITLE
settings `editor.cursorSurroundingLines` to have scrolloff ends up in weird behaviour.

### ISSUE THREAD

**Issue by zarghamkhandev** [vscode-neovim/vscode-neovim#1038]
https://user-images.githubusercontent.com/61333365/190913176-dd2e97a7-edcf-4cb4-a967-f23cc65fd972.mov

**Comment by theol0403** [comment]
Please describe the issue

**Comment by snacksncode** [comment]
I also experienced same issue. If you set `scrolloff` in VSCode high enough to have cursor always centered if you click somewhere above or below the cursor it'll jump to accommodate set `scrolloff` value. So it looks very weird and you can't really select anything with mouse. I just disabled `scrolloff` altogether.

**Comment by Axlefublr** [comment]
I know what's the issue. You're using your mouse.
