### ISSUE TITLE
Possible to get NerdTree like shortcuts on file browser?

### ISSUE THREAD

**Issue by ZeChArtiahSaher** [vscode-neovim/vscode-neovim#1040]
I was thinkin if it's possible to get NerdTree like shortcuts in the plugin.

I see that some work, but I was thinking of navigation shortcuts, like zz to go to the middle of the list, or jump 5 lines up/down with 5 j/k.

Any ideas?

**Comment by theol0403** [comment]
zz should work I think. It must all be implemented using vscode shortcuts and command in keybindings.json/package.json
