### ISSUE TITLE
Duplicated text after switching to normal mode

### ISSUE THREAD

**Issue by albertocerrone** [vscode-neovim/vscode-neovim#1041]
Hello everyone!

I have an issue when I type some text in insert mode.
What is happening is that after that I've typed, I press `Esc` to go back to Normal mode and Neovim adds the same thing that I've typed again.

Example:
```python
#  The typed text
hello world
#  The result after Esc
hello worldhello world
```

This behavior isn't happening in nvim in the terminal.

As well I'm new to this extension than is possible that I misconfigure something🫠

Thank you so much for your help

**Comment by albertocerrone** [comment]
I solved this by deleting everything from nvim and reinstalling again.

**Comment by pieterdd** [comment]
I have this too. Can you clarify what you deleted before reinstalling? The VSCode extension, the Neovim application, your Neovim config folder, your VSCode Neovim config, all of the above?

**Comment by albertocerrone** [comment]
Hey @pieterdd Yes I believe that I have done a fresh installation from 0!
