### ISSUE TITLE
remap of init.lua does not work well

### ISSUE THREAD

**Issue by yamatsum** [vscode-neovim/vscode-neovim#1044]
The following settings are made in init.lua.
```
vim.keymap.set("n", "<Tab>", "gt")
```
However, even if I enter <Tab> on vscode, the tab does not switch.
Everything works fine except for that setting in init.lua.
As a workaround, the following is set in keyboard.json, but I would like to set it in init.lua.
```
  {
    "key": "tab",
    "command": "workbench.action.nextEditor",
    "when": "editorTextFocus && neovim.mode != 'insert'"
  },

```

**Comment by justinmk** [comment]
This is because vscode-neovim isn't listening for a "tab change" event, it is remapping `gt` to something like "nextEditor" as in your workaround. 

It is not really possible to "fix" this because vscode's tabs don't really map to Nvim tabs.

**Comment by yamatsum** [comment]
```
local map = vim.keymap.set

if vim.g.vscode then
  map("n", "<Tab>", "<Cmd>call VSCodeNotify('workbench.action.nextEditor')<CR>")
  map("n", "<S-Tab>", "<Cmd>call VSCodeNotify('workbench.action.previousEditor')<CR>")
end
```
I was able to realize it above

**Comment by theol0403** [comment]
I think all you needed was to set `remap = true` so it uses the vscode command.
