### ISSUE TITLE
Cursor freezes on any higher cpu/disk usage

### ISSUE THREAD

**Issue by xxSkyy** [vscode-neovim/vscode-neovim#1048]
Hey
I've got problem that it's very often with some projects with tons of files when VSCode starts searching through it etc the nvim cursor freezes - stops being responsive on any input and I have to wait till processing ends or reload VSCode to make cursor work again.

To reproduce just open any big project and run search for `a` letter in whole project then try to move a cursor.

My specs:
OS: `Manjaro 22`
CPU: I9-10900K
RAM: 32GB
DISK: SATA SSD&M.2 SSD
GPU: RX 6800 XT

Overall It's not like my PC lags while those operations. VSCode is responsive without any issue, I just hear my cooling that my PC do something. And CPU usage is at most of 20%. Only `VSCode Neovim` becomes unresponsive.

**Comment by theol0403** [comment]
Add to settings:

```
  "extensions.experimental.affinity": {
    "vscodevim.vim": 1,
    "asvetliakov.vscode-neovim": 1
  },
```

The problem is that the extension host is single-threaded and your other plugins (lsp, etc) are blocking vscode-neovim.

**Comment by xxSkyy** [comment]
Thanks! Maybe add this tip to `Performance problems` in `Troubleshooting` section
