### ISSUE TITLE
PSA: Use `extensions.experimental.affinity` to speed up extension

### ISSUE THREAD

**Issue by theol0403** [vscode-neovim/vscode-neovim#1051]
VSCode allows extensions to run in their own thread. This improves productivity, and also is more important as of recent PRs. 

Add to settings.json:

```json
"extensions.experimental.affinity": {
    "asvetliakov.vscode-neovim": 1
},
```

**Comment by theol0403** [comment]
Next on my PR list is to make the extension automatically detect if this is set, and prompt if not.

**Comment by the-mighty-mo** [comment]
I'm pretty sure that the "vscodevim.vim" field is for setting the affinity for the [VSCodeVim](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim) extension, so if a prompt is added to this extension, it should only add the "asvetliakov.vscode-neovim" field.

The affinity setting can be verified by running "Developer: Show Running Extensions" in the Command Palette ("local process #"):
![image](https://user-images.githubusercontent.com/24577492/195976502-5308cb9e-e1fb-49f3-8d46-f10cc77ac9f0.png)

**Comment by theol0403** [comment]
You are correct, I did know that but didn't think it was an issue. I didn't think it would hurt to include both as they both benefit from this setting and then you don't have duplicates in settings.json.

However, I can see how this can be confusing, and will delete that line when I have the chance.

**Comment by tauin** [comment]
in the window render log for vscode there are these lines:
`2022-11-07 21:02:03.310 [info] Ignoring configured affinity for 'asvetliakov.vscode-neovim' because the extension is unknown or cannot execute for extension host kind: LocalWebWorker.
`
does anyone else have this?

**Comment by snacksncode** [comment]
I've found one issue when enabled this option. `Ctrl+Backspace` which usually removes the whole word in insert mode now removes only 1 character. Another thing is that "keyboard spam" is creating a noticeable cursor lag (might be just my laptop). Not sure if the cursor issue is solvable but word removal could be

**Comment by theol0403** [comment]
> I've found one issue when enabled this option. `Ctrl+Backspace` which usually removes the whole word in insert mode now removes only 1 character. Another thing is that "keyboard spam" is creating a noticeable cursor lag (might be just my laptop). Not sure if the cursor issue is solvable but word removal could be

Strange, I have no idea how the setting would cause these issues. Are you sure it’s not caused by the recent plugin updates? That is more likely

**Comment by snacksncode** [comment]
Small update, I've updated extension and both issues are fixed. Had couple system reboots since then, it was probably something on my part. Keyboard spam is not noticable anymore and `ctrl+Backspace` works as expected with extension running as a separate process.

**Comment by MostHated** [comment]
I am having this issue (Ignoring configured affinity for 'asvetliakov.vscode-neovim' because the extension is unknown or cannot execute for extension host kind: LocalWebWorker.) and a very noticeable lag that seemingly starts when I alt-tab to another window, then back to VSCode, and it feels like it just gets worse over time after that. I end up having to ctrl palette -> Restart Extension Host / Reload Window every few minutes.

<details>
<summary>Details</summary>

VSCode 

```zsh
Version: 1.75.0-insider
Commit: 6ed4d436a9b6ae131732f4e2a723868231f4473a
Date: 2022-12-23T05:28:27.642Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.0.12-76060006-generic
Sandboxed: Yes
```

VSCode Neovim  v0.0.95

</details>

**Comment by justinmk** [comment]
@laoshaw the plugin id is `asvetliakov.vscode-neovim` , not `vscodevim.vim` .

**Comment by nate-lumalabs** [comment]
Every time I open vscode (cursor actually) I get a popup telling me this setting is not enabled, but it is in my settings.json:

```
  "extensions.experimental.affinity": {
    "asvetliakov.vscode-neovim": 1,
  }
```

Anyone else have that? I wonder why its not being picked up.

**Comment by turtlebasket** [comment]
Same issue here - Cursor 2.3.41

**Comment by ankitpal1029** [comment]
found this thread from cursor, 

[experimental settings wiped](https://forum.cursor.com/t/cursor-deleting-experimental-settings/148143)

seems like a patch is coming soon
