### ISSUE TITLE
Can't select text by mouse in version v0.0.92

### ISSUE THREAD

**Issue by johntaiko** [vscode-neovim/vscode-neovim#1052]
## Neovim: 
```
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.0/share/nvim"

Run :checkhealth for more info
```
## Settings
```
"extensions.experimental.affinity": {
    "vscodevim.vim": 1,
    "asvetliakov.vscode-neovim": 1,
  },
```

## Screen record:

https://user-images.githubusercontent.com/25055590/195489035-a2cea4fb-e6b0-4022-9af9-a736cd38e46e.mov

**Comment by johntaiko** [comment]
The version of vscode:
```
Version: 1.72.1
Commit: 129500ee4c8ab7263461ffe327268ba56b9f210d
Date: 2022-10-10T17:23:16.506Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No
```

**Comment by echaya** [comment]
i can repro on windows. 

```
Version: 1.72.1 (user setup)
Commit: 129500ee4c8ab7263461ffe327268ba56b9f210d
Date: 2022-10-10T17:22:48.346Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19042
Sandboxed: No
```

**Comment by kaiywen** [comment]
same problem on mac

**Comment by theol0403** [comment]
This is caused by https://github.com/vscode-neovim/vscode-neovim/pull/1045. On one hand, if `vscode-neovim.mouseSelectionStartVisualMode` is enabled it works well. But I didn't test if it was disabled.

**Comment by Jendker** [comment]
Maybe it would be easier for a user to understand what's happening if the `vscode-neovim.mouseSelectionStartVisualMode` option would be enabled by default?

**Comment by SubaruArai** [comment]
@theol0403  May I reopen this?
While `vscode-neovim.mouseSelectionStartVisualMode` might be a temporary fix, the behavior is slightly different (needs to press `esc` to end visual mode) and it has its own bug, too.
e.g. when selecting a large chunk of text (more than 1 screen), only the last selected chunk is shown as selected. This is just a visual effect: I can confirm that the start cursor didn't move by yanking or moving the end cursor.

Anyways, I really appreciate your hard work on this project, thank you!

**Comment by theol0403** [comment]
I did actually fix the real issue in the latest commit, just not released yet.

**Comment by SubaruArai** [comment]
Sorry, I didn't notice #1055 !
And I accidentally deleted my post since I thought you didn't read it yet, my bad!

**Comment by jpalawaga** [comment]
Can we hotfix for this? incredibly frustrating to have main editor functionality broken.

**Comment by theol0403** [comment]
Just been busy. You can always install an older version of the ext…
Or build it yourself. I will try to release today.

**Comment by jpalawaga** [comment]
I did switch to an older version--I was just vocalizing that this bug sitting around does have impact to users.

thanks for all of the effort you've put into this plugin. the only reason I complain is because I can't live without the plugin :)
