### ISSUE TITLE
c6d227b breaks visual-multi plugin

### ISSUE THREAD

**Issue by Sduby22** [vscode-neovim/vscode-neovim#1056]
## expected behavior(9fa7f31)

after hitting `Ctrl-N` 3 times I created 3 cursors, and after hit `a` and `bbb` I entered insert mode and appended `bbb` 

https://user-images.githubusercontent.com/29040696/195978316-ad5f9e12-4479-4c28-848d-1ed4c0c49c83.mp4

## result behavior(c6d227b)
after hitting `bbb`, the letters immediately disappeared 

https://user-images.githubusercontent.com/29040696/195978220-a0a10e23-03c1-42cd-b2d1-8d95029fd856.mp4

## bad commit
c6d227b: feat(document_change_manager): replay insert-mode edits in realtime using `nvim_buf_set_text` (#992) …

## vscode version

```
Version: 1.72.1
Commit: 129500ee4c8ab7263461ffe327268ba56b9f210d
Date: 2022-10-10T17:23:16.506Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.4.0
Sandboxed: No
```

**Comment by theol0403** [comment]
Thanks for the report!

I think this has something to do with the fact that edits are now sent using nvim_buf_set_text, and maybe vim-visual-multi is incompatible with this.

It's possible there is a less significant bug going on here as well. 

In the case of the first potential cause, I think the solution would be to redirect incoming edits being sent by `nvim_buf_set_text` and convert them to `nvim_input` in certain cases. This is already mentioned in https://github.com/vscode-neovim/vscode-neovim/pull/992#issuecomment-1228734888 as an option to remove dot-repeat hack. Essentially, an algorithm must be made that converts a sequence of `nvim_buf_set_text` into a sequence of `nvim_input(<Left>/<Right> <BS>/<Del> text)`. 

This is something I was hoping to try, but unfortunately I won't have time to work on this in the short term. I have many midterms approaching and many things to do. I'll try to fix this when I get the chance though.

For now, stick with the older plugin version.

**Comment by Sduby22** [comment]
Thank you!

To whom it may concern, sticking to `v0.90.0` should work now.

**Comment by ynotzort** [comment]
Can confirm that version `v0.0.90` works but all later versions show this faulty behavior.

I would like to contribute here, any pointers on how to get started on this issue? Or maybe some more details on the requirements for the algorithm you mentioned above?

> Essentially, an algorithm must be made that converts a sequence of `nvim_buf_set_text` into a sequence of `nvim_input(<Left>/<Right> <BS>/<Del> text)`.

**Comment by LawrenceLiu023** [comment]
Thank you! I have the same problem and the version `v0.0.90` also works for me. But the behaviour is still different from native Neovim. In native Neovim, the appending letters should appear immediately in visual-multi mode, but in vscode-neovim they only appear when I return to normal mode. I hope future versions will fix this problem.

**Comment by LawrenceLiu023** [comment]
你好，我看到了你建立的vscode-multi-cursor.nvim仓库。


请问这是一个全新的多光标功能实现的插件吗？独立于visual-multi等插件，而且在使用时需要禁用visual-multi？


在下一个发行版中，它将会被官方版本正式收录吗？


我之前一直喜欢使用visual-multi的一个原因是，其可以与GitHub - kevinhwang91/nvim-hlslens: Hlsearch Lens for Neovim联动，实现显示当前光标所在词在所有匹配中的序号，在使用中带来了很大的方便。


我十分敬佩你所做的工作，希望未来能看到更多好用的功能。





&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "vscode-neovim/vscode-neovim"                                                                                    ***@***.***&gt;;
Date:&nbsp;Fri, Oct 20, 2023 01:12 AM
***@***.***&gt;;
Cc:&nbsp;" ***@***.******@***.***&gt;;
Subject:&nbsp;Re: [vscode-neovim/vscode-neovim] c6d227b breaks visual-multi plugin (Issue #1056)





 
After the next release, plugin vscode-neovim/vscode-multi-cursor.nvim will be ready for use. But it's not about making visual-multi work again, rather it's about using multi-cursor editing in a more "vscode" way.

**Comment by rozbo** [comment]
any update? 
This is issue will not fix?
