### ISSUE TITLE
E484: Can't open file /share/nvim/syntax/syntax.vim

### ISSUE THREAD

**Issue by echaya** [vscode-neovim/vscode-neovim#1057]
Similar to https://github.com/vscode-neovim/vscode-neovim/issues/597, I experiences the same error msg when I launch vscode. An empty init.vim results the same error. 

![image](https://user-images.githubusercontent.com/34254408/196180735-893e2917-18af-4796-bb1c-fcaf82de4fe8.png)

**Comment by echaya** [comment]
Seems to me the problem is caused by `syntax on` setting from the file from the `vscode-options.vim` file. 
0 idea why it try to look up `syntax.vim` from the `c:/program files/nvim......` directory as this is not the nvim installation folder

**Comment by justinmk** [comment]
> why it try to look up `syntax.vim` from the `c:/program files/nvim......` directory as this is not the nvim installation folder

you need to fix your Nvim installation. The error message is telling you that.

**Comment by echaya** [comment]
> > why it try to look up `syntax.vim` from the `c:/program files/nvim......` directory as this is not the nvim installation folder
> 
> you need to fix your Nvim installation. The error message is telling you that.

not sure how your answer could be of any help and why you close it. I wished to get answers on why it is searching in this directory instead of a very abrupt "close".
