### ISSUE TITLE
undo with `u` does not work anymore as of version v0.0.91

### ISSUE THREAD

**Issue by rafmsou** [vscode-neovim/vscode-neovim#1058]
Version which identified the issue: v0.0.92

### How to reproduce:

1. Open a file, enter insert mode with `i`
2. Perform an edit
3. Exit insert mode with `esc`
4. Hit `u` to undo

Status bar says "Already at oldest change"

Version v0.0.90 is the last one which seems to function properly.

**Comment by theol0403** [comment]
Please try to reproduce with empty init.vim.

**Comment by rafmsou** [comment]
> Please try to reproduce with empty init.vim.

Yes, did it and the result is the same.

**Comment by theol0403** [comment]
Strange. There is code that has changed in this area, but all my experimental tests (and the cross-platform CI unit tests) have not raised any problems with undo.

Try, in a single line, to perform an edit in insert mode. Then do `:print`. Let me know if the output (shown in the statusbar/output panel) reflects the edit you just made.

**Comment by rafmsou** [comment]
> Try, in a single line, to perform an edit in insert mode. Then do `:print`. Let me know if the output (shown in the statusbar/output panel) reflects the edit you just made.

So it prints the line without the change I've made...

**Comment by theol0403** [comment]
To the issue is not with `undo`, it is with the new vscode->neovim sync.

Make sure you are using a fairly recent build of nvim (in the last month). 

Try with not only empty `init.vim`/`init.lua` but with empty `~/.local/share/nvim/site/pack`. I believe nvim will load plugins installed with `packer.nvim` even with an empty init.vim because they are in the nvim install directory.

Otherwise give more information about nvim/os versions.

**Comment by rafmsou** [comment]
nvim --version

```
NVIM v0.5.0-675-gaa4557920
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode-10.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/travis/build/neovim/bot-ci/build/neovim/build/config -I/Users/travis/build/neovim/bot-ci/build/neovim/src -I/Users/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/usr/local/opt/gettext/include -I/Users/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/Users/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@Traviss-Mac-6.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

**Comment by theol0403** [comment]
You are running an ancient version of nvim.

**Comment by rafmsou** [comment]
> You are running an ancient version of nvim.

Should the readme be updated to inform that?

**Comment by theol0403** [comment]
Yeah
