### ISSUE TITLE
Using shortcut keys for visual selection  does not take effect

### ISSUE THREAD

**Issue by suyby** [vscode-neovim/vscode-neovim#1060]
When I use the shortcut key to comment the selection, the comment does not have a package selection area.
![fail](https://user-images.githubusercontent.com/61300279/197534573-ffbb9270-d798-40e4-bda1-a61ae08ac8f9.gif)

When I use the command panel, it works.
![success](https://user-images.githubusercontent.com/61300279/197534843-ec44e7a4-59e4-4673-ba67-aa9de57a5a12.gif)

```
Version information:
  macOS    v12.6
  VS Code  v1.72.2
  vscode-neovim  v0.0.93
```

**Comment by justinmk** [comment]
might be the same root cause as other "visual selection sync" issues

**Comment by suyby** [comment]
#700 Solved this problem.
