### ISSUE TITLE
VSCode's Find stopped working on v0.0.92

### ISSUE THREAD

**Issue by louiscavalcante** [vscode-neovim/vscode-neovim#1061]
```
{
    "key": "ctrl+f",
    "command": "-vscode-neovim.ctrl-f",
    "when": "editorTextFocus && neovim.ctrlKeysNormal && neovim.init && neovim.mode != 'insert'"
},
```

**Comment by Jendker** [comment]
You need to change it now to:
```
    {
        "key": "ctrl+f",
        "command": "-vscode-neovim.send",
        "when": "editorTextFocus && neovim.ctrlKeysNormal && neovim.init && neovim.mode != 'insert'"
    }
```
If you go to Keyboard Shortcuts in VS Code you can check the existing keybidings by keys and delete them after right clicking. That's at least how I fixed it for me.
![Screenshot from 2022-10-25 10-45-02](https://user-images.githubusercontent.com/14967831/197727683-3707cb45-d1cb-4e2b-be27-e80f535e636d.png)
