### ISSUE TITLE
Got error Unable to init vscode-neovim: The argument 'file' cannot be empty. Received ''

### ISSUE THREAD

**Issue by coderj001** [vscode-neovim/vscode-neovim#1062]
![image](https://user-images.githubusercontent.com/39460245/197690621-75215e58-c79a-4989-8c98-6fd8d258237b.png)

**Comment by coderj001** [comment]
![image](https://user-images.githubusercontent.com/39460245/197698934-6a13e9d6-d047-4935-9d4a-322e8af1bab2.png)

**Comment by Jendker** [comment]
Are you running neovim >=0.8.0?

**Comment by coderj001** [comment]
![image](https://user-images.githubusercontent.com/39460245/197729836-73e0ff8c-9b53-4a08-9812-29245a589533.png)

**Comment by Jendker** [comment]
Have a look into README. Version 0.8.0 is the minimum now.

**Comment by theol0403** [comment]
You didn't provide the path to neovim in the settings, as indicated by the error.

**Comment by coderj001** [comment]
@theol0403 i have provided correct path

**Comment by theol0403** [comment]
What if you run `/usr/bin/nvim` from terminal?
