### ISSUE TITLE
Line navigation not working consistently

### ISSUE THREAD

**Issue by lesiki** [vscode-neovim/vscode-neovim#1063]
This morning I updated to VSCode Version: 1.72.0 and extension v0.0.93

`o` and `O` for inserting new lines is working inconsistently. This video shows repeated attempts at entering insert mode with a new line, where some work and others don't. I've tried it in various language files and seen the same behavior.

https://user-images.githubusercontent.com/1673588/197718214-bb5e9427-1007-440b-afd0-60f1b15d4ee5.mp4

I've also seen other strange behavior - lines being randomly wiped when I exit insert mode, word navigation not working at all.

These two errors pop up intermittently:

```
2022-10-25T07:58:27.756Z BufferManager: Unable to determine neovim windows id for editor viewColumn: 1, docUri: untitled:Untitled-1
```

```
2022-10-25T07:58:27.754Z BufferManager: nvim_win_set_cursor: Cursor position outside buffer
```

Please let me know if there's any further useful context I can share?

**Comment by lesiki** [comment]
FWIW downgrading to `v0.0.89` worked around the issue.

I tried other `0.0.9x` versions but they all have the same behavior.

**Comment by theol0403** [comment]
Are you on nvim version >0.8?

**Comment by lesiki** [comment]
Sorry for delay, I've been afk for a few days. No looks like I'm on an ancient nvim (v0.5.0-715-gc5ceefca7), will update it.

Thanks, closing this issue & will reopen if nvim version wasn't the problem.
