### ISSUE TITLE
Smooth scrolling like astrovim possible?

### ISSUE THREAD

**Issue by Andrew-Pynch** [vscode-neovim/vscode-neovim#1067]
Greetings, Is it possible to do smooth scrolling as depicted in this gif from astrovim?

If so, what settings do I need to toggle to enable this?
![ezgif-3-134e5dd02a](https://user-images.githubusercontent.com/43330642/198036843-069c0635-2153-4688-8a06-1be32b475742.gif)

Otherwise, would you accept a PR implementing this feature into vscode-neovim, or is that not in your vision for this extension? 

~Cheers, love this project <3

**Comment by justinmk** [comment]
vscode already has smooth scrolling. Hard to see from your gif, but I assume you are asking about "accelerated" scrolling. No idea why that would need to be built into this plugin.

**Comment by Andrew-Pynch** [comment]
Thank you for sharing @theol0403 :bow: :heart:

**Comment by adueck** [comment]
@theol0403 Thanks, can you elaborate on how to get the [german-scroll vscode plugin](https://open-vsx.org/extension/Turiiya/german-scroll) with the neovim extension?? To actually make the smooth scrolling happen? It's not working for me 🤔
