### ISSUE TITLE
Error occurs when shifting (<) nested blocks (overlapping ranges)

### ISSUE THREAD

**Issue by linw789** [vscode-neovim/vscode-neovim#1068]
Running command: `<` + `11` + `j` gives error: _DocumentChangeManager: Error applying neovim edits, error: Overlapping ranges are not allowed!_

`>` + `11` + `j` works however.

```c
    if (foo == bar)
    {
        foo += 1;
        if (baz == bar)
        {
            baz += 1;
        }
    }
    else if (foo == 0)
    {
        bar == 0;
    }
```

**Comment by theol0403** [comment]
Thanks for this! I've occasionally seen that issue, but haven't been able to find a reliable reproduction. I can reproduce this though!

This will likely be fixed if/when I find time to rewrite the nvim -> vscode sync code.

**Comment by FangLin2001** [comment]
I encounter this problem too. Just short nested codes can cause this.

**Comment by spmacdonald** [comment]
Just encountered this myself.  Any suggested work around?

**Comment by MateuszSadowski** [comment]
I'm encountering the same issue.
