### ISSUE TITLE
Pasting clipboard contents with <C-r> adds unnecessary newlines.

### ISSUE THREAD

**Issue by parkgang** [vscode-neovim/vscode-neovim#1069]
```
VSCode@1.72.2
nvim@0.8.0
macOS@Ventura 13.0
```

<img width="817" alt="image" src="https://user-images.githubusercontent.com/63892989/198823613-7e1b995e-78d1-4553-a0fa-6b46f721bd83.png">

As above, if you use `<C-r>` to paste the clipboard contents, unnecessary line breaks are added.

To solve this, I enabled the `set paste` option, but in most cases it again adds an unnecessary newline.

When I pasted with `<C-r><C-o>` , no newlines were added.

So I defined it as `inoremap <C-r> <C-r><C-o>` , but even this didn't work.

The current workaround is to explicitly call `<C-r><C-o>+` whenever pasting.

It only happens in `VSCode` + `Neovim` environment, so I suspect it's a bug.

**Comment by theol0403** [comment]
This behaviour is because originally, vscode-neovim would manually access the register and paste from it. Now, vscode-neovim just sends the command to nvim.

This is expected behaviour with nvim - if you were to paste the same thing in nvim, it would also add those newlines. This is not an issue with the extension. 

`set paste` works for me, what is wrong with it? Does it differ from nvim behaviour? 

`inoremap <C-r> <C-r><C-o>` also works for me.

**Comment by parkgang** [comment]
> This behaviour is because originally, vscode-neovim would manually access the register and paste from it. Now, vscode-neovim just sends the command to nvim.
> 
> This is expected behaviour with nvim - if you were to paste the same thing in nvim, it would also add those newlines. This is not an issue with the extension.
> 
> `set paste` works for me, what is wrong with it? Does it differ from nvim behaviour?
> 
> `inoremap <C-r> <C-r><C-o>` also works for me.

I tried mapping with `set paste` option and `inoremap <C-r> <C-r><C-o>`, but pasting proceeded as shown in the picture above in `VSCode` + `nvim` environment.

> The setting was, of course, done in `init.vim`.

If the setting is set correctly, you would expect that the contents copied to the clipboard will be pasted into `VSCode` + `nvim` without a newline.

But it wasn't.

Trying to explicitly `<C-r><C-o>+` per paste didn't result in a newline.

On the other hand, `nvim` worked as expected, so I thought it was a problem with `VSCode + nvim`.

Also, what is questionable is that when only the `set paste` setting is specified, even if the clipboard content is `<C-r>+` in `VSCode` + `nvim`, sometimes a newline is pasted without a newline.

I don't know the condition that sometimes `<C-r>+` is also attached without a newline.

I can't find a solution, so I keep trying to paste using the `<C-r><C-o>+` method. This is a cumbersome way and I'd like to find out if there is another way.

**Comment by theol0403** [comment]
I am fairly certain `set paste` and `inoremap <C-r> <C-r><C-o>` both work. How are you trying to set them?

**Comment by parkgang** [comment]
As a result of checking, it was confirmed that the problem does not occur.
