### ISSUE TITLE
ToggleComment comments/uncomments previously commented/uncommented lines

### ISSUE THREAD

**Issue by nairobi02** [vscode-neovim/vscode-neovim#1070]
```
function! g:ToggleComment()
	normal! gv
	let startline = line("v")
	let endline = line(".")
	call VSCodeNotifyRange('editor.action.commentLine', startline, endline, 1)
endfunction
```
```
vnoremap <silent> <C-/> :call g:ToggleComment()<CR>
nnoremap <silent> <C-/> :call g:ToggleComment()<CR>

```
In normal mode, when i comment something out, it works perfectly, just as expected, i can comment out a line, and then uncomment it the same way.
But, when i enter visual line mode, or visual block mode, and select some lines ABC and the comment, it does work as expected. But then when i go to another line XYZ and try to comment that new line out, the lines ABC get commented/uncommented again, the cursor jumps to ABC.

Why is this happening?

**Comment by theol0403** [comment]
`<C-/>` is already mapped to toggling the comment, why do you need this code?

Try to use `VSCodeNotifyVisual`
