### ISSUE TITLE
Unable to remove ajacent parentheses when deleting with <c-h>

### ISSUE THREAD

**Issue by huibosa** [vscode-neovim/vscode-neovim#1074]
With the vscode setting:

```
"editor.autoClosingDelete":  "always"
```

Paired parentheses or quotes could be removed by pressing `<backspace>`.
But with `<c-h>`, only one quote or parenthese will be removed.

**Comment by theol0403** [comment]
I don't think there is a solution to this, c-h is handled by neovim and it cannot know that vscode "autocompleted" the parenthesis.
