### ISSUE TITLE
VSCode merge editor cursor position issues

### ISSUE THREAD

**Issue by snacksncode** [vscode-neovim/vscode-neovim#1077]
I don't have any code conflicts on the hand so I'll try to describe the issue. If needed I'll provide a recording of said issue.
When using VSCode's "merge editor" we have 3 "splits", two on the top, left and right and combined output on the bottom (let's call it "main"). If scroll the "main" one and click with your mouse to put a cursor somewhere and the use a navigation key like `j` you'll see that cursor was actually placed at the top of the file in neovim and not in the expected position in as it shows in VSCode. Not a big issue but really irritating as you scroll around place a cursor `dd` the line and boom you've actually removed the top most line of the "main" split.

Extension version: v0.0.93
VSCode version: 1.73.1 (Linux x64)
Neovim version: v0.8.0

**Comment by trkoch** [comment]
May be related to https://github.com/vscode-neovim/vscode-neovim/issues/1577?

**Comment by ian-h-chamberlain** [comment]
> There seems to be no solution to this problem

I think this is still an issue, should it stay open even if there is no resolution? Maybe at minimum the extension could disable itself if it can detect it's open in a merge editor, or something like that? 

Obviously ideal would be to Just Work but it sounds like that would be difficult for technical reasons so perhaps either a warning or automatically disabling would be a decent workaround in the extension for now.
