### ISSUE TITLE
Issues with binding C-Space

### ISSUE THREAD

**Issue by kshenoy** [vscode-neovim/vscode-neovim#1079]
Hello, I'm having difficulty creating a binding using `<C-Space>`. I added this to my `~/.config/nvim/init.vim` file. 
````
nnoremap <C-Space><C-B> <Cmd>call VSCodeNotify('workbench.action.toggleSidebarVisibility')<CR>
````

I can confirm that this file is picked up by VSCode as I've been able to toggle the sidebar using this
````
nnoremap z= <Cmd>call VSCodeNotify('workbench.action.toggleSidebarVisibility')<CR>
````

However, if I use `<C-Space>` in the binding, it doesn't work. 
I've tried deleting all the shortcuts that use `Ctrl+Space` and added a shortcut to explicitly pass it to Neovim by adding these to VSCode User keyboard shortcuts (~/.config/Code/User/keybindings.json):
```json
[
  {
    "key": "ctrl+space",
    "command": "-toggleSuggestionDetails",
    "when": "suggestWidgetVisible && textInputFocus"
  },
  {
    "key": "ctrl+space",
    "command": "-editor.action.triggerSuggest",
    "when": "editorHasCompletionItemProvider && textInputFocus && !editorReadonly"
  },
  {
    "key": "ctrl+space",
    "command": "vscode-neovim.send",
    "args": "<C-Space>"
  },
]
```

However, nothing seems to work. What am I missing here?

**Comment by kshenoy** [comment]
Sorry for the late response. I've been a bit busy due to holidays. 

That worked! I used "ctrl+space" to trigger the command on the VSCode side and changed the binding to send "z=" as the args.

**Comment by theol0403** [comment]
I don’t think there is anything we can do to fix neovim not correctly reading C-Space if that is the issue.
