### ISSUE TITLE
[Bug] Change inside quotes, cursor jumps to the end of line

### ISSUE THREAD

**Issue by wenfangdu** [vscode-neovim/vscode-neovim#1080]
OS: macOS 13
nvim: 0.8.0
vsc-nvim: 0.0.94

vscode-neovim behavior (cursor jumps to the end of the line):

https://user-images.githubusercontent.com/28700378/203487927-70fc7320-fb2a-469e-b118-1756ba99947e.mp4

Neovim behavior (cursor stays inside the quotes):

https://user-images.githubusercontent.com/28700378/203488180-ca60d96a-bdb0-4d8d-bcae-4b1949d77b4f.mp4

Code:

```json
{
  "en": {
    "error": "Something went wrong, please try it later, sorry"
  }
}
```

**Comment by theol0403** [comment]
@wenfangdu does this still happen with the latest commit of my visual selection PR?

**Comment by wenfangdu** [comment]
@theol0403 The old repro didn't reproduce.

**Comment by wenfangdu** [comment]
@theol0403 It's reproducible in v0.9.1, please reopen this.

**Comment by xiyaowong** [comment]
@wenfangdu  Works fine for me. And there are no related changes in v0.9.1
![cursor](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/2804c5f8-fad5-4808-b2c3-a8ea10c73422)

**Comment by wenfangdu** [comment]
See https://github.com/vscode-neovim/vscode-neovim/issues/1752#issuecomment-1905341009.
