### ISSUE TITLE
Trying workarounds for weird ctrl+D scrolling, unsuccessfully

### ISSUE THREAD

**Issue by pgsandstrom** [vscode-neovim/vscode-neovim#1082]
So it is a known problem that scrolling is a bit weird. I thought that a decent workaround would be to simply add the M command after each ctrl+D to get a better experience until a fix for the original problem is solved. So I added the following to my config:

nnoremap <C-d> <C-d>M

But it does not seem to work. It seems to work okay in neovim (but there ctrl+D obviously already works). Is there a good way to get this to work?

**Comment by justinmk** [comment]
ctrl-d works for me, not nearly enough info here
