### ISSUE TITLE
ctrl-d, ctrl-u set jumps in the jumplist

### ISSUE THREAD

**Issue by Jendker** [vscode-neovim/vscode-neovim#1084]
Currently using ctrl-d and ctrl-u set jumps in the jumplist with the plugin while it's not the case in neovim. It would be great if that could be avoided.

**Comment by theol0403** [comment]
Not avoidable as vscode jumplist is being used. This may be revisited in the future, but was chosen because on the other hand, navigating via outline view was not updating the neovim jumplist.

**Comment by Jendker** [comment]
Thank you for the confirmation.
