### ISSUE TITLE
custom cursor style or vscode theme between insert,visual and normal mode

### ISSUE THREAD

**Issue by cStralpt** [vscode-neovim/vscode-neovim#1085]
i think it's possible to do that,, i have found it change my cursor style when i navigate between those modes.
if it has a configuration settings please let me know 😊

**Comment by theol0403** [comment]
https://github.com/vscode-neovim/vscode-neovim/discussions/1021

you need to expose some vscode command to change the theme (aka write the theme setting). This can be done using some vscode extension. 

Then you can use the `ModeChange` autocommand and trigger the vscode command from there.
