### ISSUE TITLE
[Feature] Warn when starting extension if the installed version of neovim is under the required version.

### ISSUE THREAD

**Issue by fiveNinePlusR** [vscode-neovim/vscode-neovim#1086]
the interaction between neovim and the extension was causing errors because of an outdated version of neovim 0.5 and now the requirements are 0.8.0. It would be nice to have a warning that the neovim installed is too old to be compatible.

**Comment by theol0403** [comment]
Fixed by https://github.com/vscode-neovim/vscode-neovim/pull/1115
