### ISSUE TITLE
init.vim not being loaded

### ISSUE THREAD

**Issue by igoracmelo** [vscode-neovim/vscode-neovim#1089]
I don't know why, but it seems that my init.vim is being completely ignored...

VSCode settings.json:
```json
{
  "vscode-neovim.neovimExecutablePaths.linux": "/usr/bin/nvim",
  "vscode-neovim.neovimInitVimPaths.linux": "/home/igor/.config/nvim/init.vim", 
}
```

/home/igor/.config/nvim/init.vim
```vim
set number    
set relativenumber    
     
nnoremap <C-d> <C-d>zz    
nnoremap <C-u> <C-u>zz    
```

## Expected behavior:
- relative line numbers
- ctrl D and ctrl U centered

https://user-images.githubusercontent.com/85039990/205973336-c55df905-a35a-415a-909f-3454dffe5bdb.mp4

## Actual behavior:
- default line numbers
- crazy ctrl D and ctrl U

https://user-images.githubusercontent.com/85039990/205973386-37abb5d4-d439-4e7b-8913-e8655d97e92b.mp4

**nvim version:** 0.8.1 (snap)
**VSCode version:** 1.73.1

**Comment by MNThomson** [comment]
Ah, another cultured @ThePrimeagen viewer I see... I spent  ~6hrs last weekend trying to solve this exact problem and think I've figured out as to why (don't take my word for fact).

### Relative Line Numbers

https://github.com/vscode-neovim/vscode-neovim/blob/994b969eab1bb8f280d2763768c31e0f501dee75/README.md?plain=1#L174

So you'll need to change the VSCode `File -> Preferences -> Settings` and change the setting `Line Numbers` to `relative`

### Navigation

Now this one is a bit more scuffed and what I lost most of my time to. As far as I can tell, `<C-u>` & `<C-d>` are not being sent through to NeoVim and are instead overridden by VSCode

https://github.com/vscode-neovim/vscode-neovim/blob/994b969eab1bb8f280d2763768c31e0f501dee75/src/commands_controller.ts#L13-L30

https://github.com/vscode-neovim/vscode-neovim/blob/994b969eab1bb8f280d2763768c31e0f501dee75/src/commands_controller.ts#L72-L75

I don't believe with the extension you can really remap most of the `<C-*>`  keys right now unfortunately. To check if your `init.vim` is actually being run, try remapping keys instead like the below:

```vim
nnoremap gk zz
```

Thus if you can type `gk` in normal mode and have it center to screen, you know in fact your `init.vim` is actually being read.

_Disclaimer: I only started using this extension last week and have absolutely no clue what I'm talking about. If someone who's worked on the extension knows more, please correct me_

**Comment by theol0403** [comment]
This is correct. Your `init.vim` works, but you've managed to test two (somewhat unique) cases where the effect does not apply to vscode.

1. Neovim UI settings are not sent over to vscode, the UI (line numbers, etc) is all handled by vscode. It is on my roadmap to support some settings https://github.com/vscode-neovim/vscode-neovim/pull/656#discussion_r912836951
2. Scrolling is currently a mess. I plan to write about this in an annoucement when I have the chance. Basically, currently scrolling is handled by vscode (using behavior that does not match nvim's). There are a bunch of PRs that work to fix this, but they are currently in a semi-working state. Ref: https://github.com/vscode-neovim/vscode-neovim/pull/885#issuecomment-1315637788

**Comment by theol0403** [comment]
To clarify: there is currently no neovim scroll position -> vscode sync, which means that C-u commands that just move the nvim viewport don't work without intervention.

**Comment by MNThomson** [comment]
Whoops, didn't mean to actually ping Prime. He mentioned the `<C-u>zz` remap in a recent video @theol0403 : [Vim As Your Editor - Vertical Movements](https://m.youtube.com/watch?v=KfENDDEpCsI&t=3m10s)

**Comment by ThePrimeagen** [comment]
i have been summoned and i am happy to see such wonder remaps in play!  May the coconut oil flow as if its 85 degrees in your room.

**Comment by Andrew-Pynch** [comment]
@MNThomson @theol0403 

So just to confirm.

It is not currently possible to reproduce the ctrl + d nnoremap to center when ctrl + d is pressed within this extension currently?

I just got it working in vanilla vim and was hoping to reproduce this effect in nvim/vscode.

**Comment by KatlehoJordan** [comment]
Any place I can "upvote" this as a feature request for the plugin? Would love to rapidly re-center my VS-code editor panes by appending `zz` after various different keystroke-combinations, :heart:.

Thanks for this great extension! Terrific way to start learning nvim in the comfort of VS Code!

**Comment by theol0403** [comment]
Being worked on in https://github.com/vscode-neovim/vscode-neovim/pull/993
