### ISSUE TITLE
The jump list in vscode-neovim is messy up.

### ISSUE THREAD

**Issue by meicale** [vscode-neovim/vscode-neovim#1091]
When using neovim is vscode with this plugin. I find that the jumplist is not useful at all. In neovim I use plugin such as hop and lead and * to jump to anther position, and use ctrl+o and ctrl+i to jump back and forward. But I can not use this at all in vscode. 
If you have any idea,  please let me know! Thx!

**Comment by meicale** [comment]
Neovim on the terminal, I use s or j (plugin lead or hop) to jump to new position one after another, I can just jump back using C-o one by one. But, in vscode, I can not do that, It may just miss some jump. The same thing happens when using "*" builded method to jump. But markers with specified label works ok! 
Thx!

**Comment by Drakota** [comment]
@theol0403 Is there any particular reason why the plugin isn't using the Neovim's native jumplist? It's annoying how CTRL-U/D modifies VSCode's jumplist which makes CTRL-O/I to jump to every scroll.

**Comment by meicale** [comment]
> @theol0403 Is there any particular reason why the plugin isn't using Neovim's native jumplist? It's annoying how CTRL-U/D modifies VSCode's jumplist which makes CTRL-O/I to jump to every scroll.

Can we have any walk around? Thx! @theol0403

**Comment by theol0403** [comment]
Vscode jumplist was used to solve https://github.com/vscode-neovim/vscode-neovim/issues/392. 

Nvim jumplist only works within current file. You could bind `nnoremap <C-o> <C-o>` which reverts to nvim jumplist, but then you can't jump across buffers.

**Comment by zhaoxuyll** [comment]
I've found that using the cursor to redo (cursorUndo) is more accurate than using the workspace navigation(workbench.action.navigateBack) to jump.

**Comment by tobias-klemp** [comment]
Hey i might be a bit late to the party, but i just wanted to share my solution to this in case anyone else does not like the vscode jumplist. 
I'm also a heavy user of `<c-u>` and `<c-d>` so my vscode jumplist is polluted with a lot of entries i dont really want.

I found this plugin: https://marketplace.visualstudio.com/items?itemName=spacian.jumplist
and use it in combination with some autocmds and keymaps to mimic the nvim jumplist but let vscode and the plugin handle the list and jumping.

This is the code i'm using:

```lua
if vim.g.vscode then
  local vscode = require("vscode-neovim")
  local previous_jumplist = vim.fn.getjumplist()[1]

  local function jump_back()
    vscode.call("jumplist.jumpBack")
  end

  local function jump_forw()
    vscode.call("jumplist.jumpForward")
  end

-- this is not nice, but does the job for now
  local function goToDef()
    vscode.call("jumplist.registerJump")
    vscode.call("editor.action.revealDefinition")
  end

  vim.keymap.set({ "n" }, "<c-o>", jump_back, { noremap = true })
  vim.keymap.set({ "n" }, "<c-i>", jump_forw, { noremap = true })
  vim.keymap.set({ "n" }, "gd", goToDef, { noremap = true })

  local function check_jumplist()
    local current_jumplist = vim.fn.getjumplist()[1]
    if #current_jumplist > #previous_jumplist then
      vscode.call("jumplist.registerJump")
    end
    previous_jumplist = current_jumplist
  end

  vim.api.nvim_create_autocmd({ "CursorMoved", "CursorMovedI" }, {
    callback = check_jumplist,
  })
end
```

I know it is pretty messy right now (at work rn), but it works good enough for the moment. Maybe this approach could be refined and added to the plugin? I might do a pr if anyone is intereseted.

**Comment by LonJonn** [comment]
> Hey i might be a bit late to the party, but i just wanted to share my solution to this in case anyone else does not like the vscode jumplist. I'm also a heavy user of `<c-u>` and `<c-d>` so my vscode jumplist is polluted with a lot of entries i dont really want.
> 
> I found this plugin: https://marketplace.visualstudio.com/items?itemName=spacian.jumplist and use it in combination with some autocmds and keymaps to mimic the nvim jumplist but let vscode and the plugin handle the list and jumping.
> 
> This is the code i'm using:
> 
> ```lua
> if vim.g.vscode then
>   local vscode = require("vscode-neovim")
>   local previous_jumplist = vim.fn.getjumplist()[1]
> 
>   local function jump_back()
>     vscode.call("jumplist.jumpBack")
>   end
> 
>   local function jump_forw()
>     vscode.call("jumplist.jumpForward")
>   end
> 
> -- this is not nice, but does the job for now
>   local function goToDef()
>     vscode.call("jumplist.registerJump")
>     vscode.call("editor.action.revealDefinition")
>   end
> 
>   vim.keymap.set({ "n" }, "<c-o>", jump_back, { noremap = true })
>   vim.keymap.set({ "n" }, "<c-i>", jump_forw, { noremap = true })
>   vim.keymap.set({ "n" }, "gd", goToDef, { noremap = true })
> 
>   local function check_jumplist()
>     local current_jumplist = vim.fn.getjumplist()[1]
>     if #current_jumplist > #previous_jumplist then
>       vscode.call("jumplist.registerJump")
>     end
>     previous_jumplist = current_jumplist
>   end
> 
>   vim.api.nvim_create_autocmd({ "CursorMoved", "CursorMovedI" }, {
>     callback = check_jumplist,
>   })
> end
> ```
> 
> I know it is pretty messy right now (at work rn), but it works good enough for the moment. Maybe this approach could be refined and added to the plugin? I might do a pr if anyone is intereseted.

Using an autocmd for this is really smart and it works pretty solid. I was afraid I would have to setup jump registers with every plugin I had, but this implementation is super easy. Good find!
