### ISSUE TITLE
"Almost fully feature-complete VIM integration". Why is that?

### ISSUE THREAD

**Issue by Adam-Antios** [vscode-neovim/vscode-neovim#1092]
This is not an issue, just a general question born out of ignorance regarding Neovim's and VS Code Neovim's inner workings, and out of curiosity regarding the features that may be missing.

In the README, it is stated:

> Almost fully feature-complete VIM integration by utilizing Neovim as a backend.

If there is a fully embedded Neovim instance, why there is an "almost" fully feature-complete integration? What features are not present and why?

**Comment by justinmk** [comment]
vscode-neovim lets vscode take over during insert-mode. This avoids tons of issues and allows all vscode features to work (autocomplete, snippets, etc.).

This is mentioned at the top of the readme but the connection to the sentence you mention isn't explicitly called out. Probably should be made clearer.
