### ISSUE TITLE
Search highlight is broken on lines starting with tab (\t)

### ISSUE THREAD

**Issue by guyguy2001** [vscode-neovim/vscode-neovim#1097]
**Reproduction**
Paste the following code into a file:
```cpp
						Variant::construct(base.type.builtin_type, base_val, nullptr, 0, err);
```
(The first 6 characters are tabs, you might need to use convert indentation to tabs)
and search for `base` via `/`.
![image](https://user-images.githubusercontent.com/6932278/207110500-c706f9f4-6c9e-49d5-bedd-22a781dffd86.png)
(The image is after also performing a visual select)
There are 2 problems:
* The highlights are too much to the right
* The correct highlight (on the first `base`) was created when I did a visual select, and now it's still there even after I exited it

I started debugging this, so I wanna continue working on this until I yield or finish.
One question that I have - is there any documentation on how either vscode-neovim or neovim itself handles columns? I see a lot of stuff like `useBytes`, and it feels to me like I need to understand it to work with the relevant code, even if I'm not using multibyte characters in my code

**Comment by guyguy2001** [comment]
Oh it's a regression caused by 9a06918 - this explains why I haven't found any issue about it.
I'll try to see why it wasn't obvious to the author that they were creating a bug, and make that code clearer

**Comment by guyguy2001** [comment]
I found this piece of code:
https://github.com/vscode-neovim/vscode-neovim/blob/9d1288eea92c547d2b6259208164b81e325d5889/src/viewport_manager.ts#L42-L52
What does `isByteCol` mean? Is it "are we counting the columns as bytes"? If so, what is the alternative? (because `isByteCol` is used for `calculateEditorColFromVimScreenCol`, which also accepts `false` there in other places.

@theol0403 @zbw8388 - I saw that the two of you co-authored this code (according to git at least), could you give me input on this?
(Sorry if I shouldn't have pinged here - I figured that this situation is what it's for, and I couldn't find any info on when it's okay/not okay to ping)

**Comment by theol0403** [comment]
Sorry don't have time to address this rn. I should be able to in a week. 
A lot of this code is written by the original author of the ext.
