### ISSUE TITLE
Overwrite vscode-neovim specific bindings

### ISSUE THREAD

**Issue by GustafXTT** [vscode-neovim/vscode-neovim#1101]
I found that a key combination `gf` has been bonded to `editor.action.revealDeclaration` because it is one of the specific bindings for vscode.
But my habit was to set `gf` as `editor.action.goToReferences`. Hence I tried to set it up in init.vim like:
`nnoremap <C-w>gf <Cmd>call VSCodeNotify('editor.action.editor.action.goToReferences')<CR>`, and it didn't work. Normally it will show that a plugin has bounded the key if users check vscode's keyboard shortcuts page but it shows the default value. I can't overwrite it in the vscode's keyboard shortcuts neither.

I am wondering how can I overwrite vscode-neovim specific bindings.

**Comment by GustafXTT** [comment]
Got it, looks like just need to write a `if exists('g:vscode')` in init.vim

**Comment by theol0403** [comment]
Not sure why it wasn't working at first, and that should not have made a difference, but glad it works.
