### ISSUE TITLE
Rendering wierd characters

### ISSUE THREAD

**Issue by raulbethencourt** [vscode-neovim/vscode-neovim#1102]
First of all, thank for work. It's great plugin, 
Hi I've check the issues and I see that this one it's existed already and it was close, but I'm having troubles in visual mode.
![Capture d’écran de 2022-12-16 14-36-33](https://user-images.githubusercontent.com/58934440/208110385-d6bac592-5003-4e3e-b662-438d3be964a3.png)
I use nvim 8.1 and vscode 1.74.1
I'm using leap
and nvim-yank

Thank in advance

**Comment by raulbethencourt** [comment]
Hi I just discover that is related to error highlights
The problem is when y pass over words with error highlights

**Comment by merlindru** [comment]
For me this happens when using visual selections. I sometimes get the misplaced characters that #1075 attempted to fix as well 😕

**Comment by merlindru** [comment]
To add, visual selections are usually off by a couple characters. This does not happen with 0.90, and is probably related

**Comment by raulbethencourt** [comment]
Ok. Thanks, I'l give it a try 👍🏽

**Comment by raulbethencourt** [comment]
Hi, I've installed prerelease nvim 0.9 but it's still the same.

**Comment by theol0403** [comment]
Fixed by https://github.com/vscode-neovim/vscode-neovim/pull/1099
