### ISSUE TITLE
VSCode selections that don't include a newline are lost when scrolling

### ISSUE THREAD

**Issue by rben01** [vscode-neovim/vscode-neovim#1103]
Settings:
- Mouse Selection Start Visual Mode: `false`
- Reveal Cursor Scroll Line: `false`

To reproduce:
1. Use the mouse to select some text in the editor, but don't include any newlines/line breaks in the selection
1. Use the mouse to scroll (trackpad scrolling, mouse wheel, drag the scroll bar, etc)

Bug:
- The selection is lost the instant the viewport scrolls.

Other notes:
- If the selection wraps across multiple lines, this does not occur (which is the desired behavior; the selection should not be lost when scrolling).
- This doesn't affect or involve vim’s visual mode selections at all; vim’s visual selections are never lost when scrolling. But they don't do some of the VSCode niceties such as highlight all occurrences of the current word, so they're not a suitable workaround.

**Comment by rben01** [comment]
Also this appears to only affect VSCode selections made in normal mode, not in insert mode.

**Comment by theol0403** [comment]
Could be related https://github.com/vscode-neovim/vscode-neovim/pull/959
