### ISSUE TITLE
Pasting makes plugin hang

### ISSUE THREAD

**Issue by merlindru** [vscode-neovim/vscode-neovim#1104]
Hi! I'm on WSL2/Windows 11, running VSCode and nvim in WSL

Sometimes, when I paste, the plugin completely hangs. Especially often (>90% of the time) when the copied text is NOT from vscode but another application. I have to reload the vscode window to get it to work.

This is usually remedied by going into insert mode, so vscode takes over, then pressing CTRL+V.

I have the windows clipboard history enabled, but don't know if that makes any difference.

In my init.vim I have

```
set clipboard=unnamedplus
set ignorecase
set smartcase
```

And one plugin registered with **vim-plug**, which doesn't affect the problem (the problem still exists without the plugin. I haven't tried disabling vim-plug itself however)

Thanks for building vscode-neovim! Keep up the great work :)

**Comment by theol0403** [comment]
I don't think this is a problem with the plugin. The hang comes from nvim trying to access the windows clipboard from inside wsl. This isn't necessarily bad, but probably would still occur in regular nvim inside WSL.

Either way, I don't think there is anything I can do about this.

**Comment by merlindru** [comment]
Hm, I do not have this problem when I run `nvim`. I even made sure it uses the same config as vscode-neovim by using `nvim -u ...` and trying again.

When I copy something in my host OS (e.g. windows), I can paste in nvim just fine. Unless I copied an image, for example, in which case nvim reports

```
E353: Nothing in register "
```

Whereas vscode-neovim crashes. Sometimes vscode crashes as a whole, even, but it's rare. I only have this problem when using vscode-neovim

**Comment by theol0403** [comment]
Very strange. I don't think vscode neovim really does anything differently. It delegates pasting to nvim.

**Comment by merlindru** [comment]
Hm, on second thought, Windows Terminal (which I was using to test nvim) might be doing something to make this work. I'll try a couple of things and let you know

**Comment by meicale** [comment]
> Hm, on second thought, Windows Terminal (which I was using to test nvim) might be doing something to make this work. I'll try a couple of things and let you know

Just like you said. I can work with nvim inside wsl2 and Window 11 appsquite well. But when useing this plugin, it hang when I copy in vscode using the plugin opened with means I get change the register of nvim and clipboard of host system. But I can not find the change of "+" register. It just disappears. But if I ctrl+c, which can change the "+" register correctly.

**Comment by meicale** [comment]
I find out that when I use vscode neovim plugin and nvim in wsl together. The register of plugin used nvim update a little later with 1~2 seconds delay. I wonder this may cause the problem of the hanging. Maybe you guys can repeat it to check that out. I hope this may provide some help.

**Comment by codematsing** [comment]
I've been having this same issue too. Only difference is that I'm running it WSL2/Windows 10. Hoping to get a resolution from this as I've been checking for similar situations with other people. I know that the plugin hangs when doing the "p" command in normal mode since my vscode status bar hangs with "p" as last command

**Comment by meicale** [comment]
Windows terminal, occasionally has the same problem. I guess this may caused by wsl2. It is just my blind guess and These may have different reason.

**Comment by merlindru** [comment]
I think that's down to a different reason. In VSCode, it crashes 95% of the time for me now. With Windows Terminal I've never had the issue, although I don't use it much for nvim

**Comment by meicale** [comment]
I just feel that if I copy and paste too fast, or I paste an empty string, or I try to access the registers before I copy anything in the current session, it hangs.

**Comment by codematsing** [comment]
For now I had to go back to vscode-vim plugin to avoid the issue. It's not having issues with vscode-vim. As a temporary solution

**Comment by meicale** [comment]
> For now I had to go back to vscode-vim plugin to avoid the issue. It's not having issues with vscode-vim. As a temporary solution

I just want to use nvim motion plugin such as leap, hop and so on. I cannot find the motion in the other vscode plugin. But this problem is really annoying. I just find more hang case with Windows terminal, maybe there is some reason behind this.

**Comment by codematsing** [comment]
you probably try https://marketplace.visualstudio.com/items?itemName=shadowndacorner.vscode-easymotion for now to avoid the frequent hangs.

I wish I can give more than bandaid solutions but I don't exactly know why it's happening. Lol

> > For now I had to go back to vscode-vim plugin to avoid the issue. It's not having issues with vscode-vim. As a temporary solution
> 
> I just want to use nvim motion plugin such as leap, hop and so on. I cannot find the motion in the other vscode plugin. But this problem is really annoying. I just find more hang case with Windows terminal, maybe there is some reason behind this.

**Comment by meicale** [comment]
> EDITED RESPONSE:
> 
> It seems that vim easymotion is built in to the vscode-vim now. just use w :)
> 
> > > For now I had to go back to vscode-vim plugin to avoid the issue. It's not having issues with vscode-vim. As a temporary solution
> > 
> > 
> > I just want to use nvim motion plugin such as leap, hop and so on. I cannot find the motion in the other vscode plugin. But this problem is really annoying. I just find more hang case with Windows terminal, maybe there is some reason behind this.

vscode-vim simulated easymotion, it is cool. Thank you! I think I will like it. I will use that for a while.

**Comment by tusharsnn** [comment]
To me it seems xclip is behind it, I would suggest to uninstall xclip entirely (since neovim prefers xclip always) and install xsel instead.

Similar issues: https://github.com/microsoft/terminal/issues/11945#issuecomment-1236376011

**Comment by theol0403** [comment]
Upstream issue. Try xsel.
