### ISSUE TITLE
Jumping to the Next Change does not work when Neovim plugin is turned on

### ISSUE THREAD

**Issue by f-squirrel** [vscode-neovim/vscode-neovim#1106]
How to reproduce:
- Install/Enable `vscode-neovim`
- Change a file in several places in a git repository
- "Open Changes"
- Click "Next Change"

*Result*: the cursor either jumps to the first change but never jumps to the next or simply does not jump at all.

**Comment by alanxmay** [comment]
I found that it works fine only in *insert* mode.

**Comment by f-squirrel** [comment]
@alanxmay, nice workaround.
Thank you!

**Comment by Kiuchi** [comment]
I have faced a similar problem.
I believe this problem started around 0.0.92. I'm now using 0.0.91 and do not have this problem.

**Comment by theol0403** [comment]
This might be fixed by https://github.com/vscode-neovim/vscode-neovim/pull/1258

**Comment by k4nar** [comment]
I'm still reproducing the issue in normal mode with the latest releases of VSCode & VSCode Neovim. It does work as expect in insert mode (but this isn't very convenient for code reviews).
