### ISSUE TITLE
Blue text and indentation markers

### ISSUE THREAD

**Issue by zlee-personal** [vscode-neovim/vscode-neovim#1109]
Example:
![image](https://user-images.githubusercontent.com/10042016/209005200-108bc839-4285-4c6b-b233-5a28d80b3049.png)

Empty init.vim

nvim 0.8.1

Bug appears in versions 0.0.85 onward.

plugin 0.0.95

Arch Linux

**Comment by theol0403** [comment]
See if it is fixed by https://github.com/vscode-neovim/vscode-neovim/pull/1100

**Comment by theol0403** [comment]
Also, are you sure you have empty init.vim? If you use packer, plugins will still be loaded.
