### ISSUE TITLE
want to use ctrl-w to move between the explorer and the code part

### ISSUE THREAD

**Issue by yamatsum** [vscode-neovim/vscode-neovim#1112]
Use neovim's standard ctrl-w to move between neovim file explorers such as nvim-tree and neo-tree.

I want to move between explorers with ctrl-w in vscode-neovim, is there a way?
Or do you plan to support it?

**Comment by theol0403** [comment]
From gitter: 
> I forget the command off the top of my head but there exists one in vscode that lets you navigate left/right views or panels, maybe workbench.action.navigateDown. You have two options. You can either bind something like c-hjkl to those commands, or you can copy the C-w vim bindings in the extension vscode-window-commands.vim and replace the command that it uses. Currently they just use focusBelowGroup.

Basically, you need to use vscode keybindings to support c-w *from* the explorer, and modify (using vscode or nvim keybindings) the c-w from nvim to move across views, not just windows.

**Comment by bigzhu** [comment]
add this to `~/.config/nvim/init.vim`:

```vim
nnoremap <C-w>h <Cmd>call VSCodeNotify('workbench.action.navigateLeft')<CR>
xnoremap <C-w>h <Cmd>call VSCodeNotify('workbench.action.navigateLeft')<CR>
```
