### ISSUE TITLE
tilde added at end of file when using "dd" command

### ISSUE THREAD

**Issue by OkDubs** [vscode-neovim/vscode-neovim#1114]
On certain characters such as (>, }, empty space), when the delete line command is done, a tilde (~) will replace or toggle between the last character of a file.

**Comment by theol0403** [comment]
- make sure you are on nvim > 0.8
- try with empty init.vim and no plugins

I'm fairly confident that is the problem, have never seen this issue before and no related code changes. Please update if not.
