### ISSUE TITLE
Esc on the suggestion will be swallowed by somehow for 0.5 seconds

### ISSUE THREAD

**Issue by GustafXTT** [vscode-neovim/vscode-neovim#1117]
![ezgif-4-a242f16b0b](https://user-images.githubusercontent.com/62175622/210126926-62be6634-ab94-4b0b-93e1-0b3b54bda183.gif)
While turning to normal mode from insert mode, the last Esc will be frozen for 0.5 seconds, then jump to the previous letter.
Any input during this 0.5 seconds takes no effect.

**Comment by GustafXTT** [comment]
By commenting init.vim, I found that this problem will be caused by `set showmatch` command.
Will be fine after removing this command, just don't know why it will cause this problem in vscode-neovim plugin.

**Comment by justinmk** [comment]
what does `:set matchtime?` say?

**Comment by GustafXTT** [comment]
`set matchtime?`says 5, when I set it to 1 there will be a quick flick. Quite annoying might just delete this line.
