### ISSUE TITLE
Linewise visual mode glitch

### ISSUE THREAD

**Issue by atulmirajkar** [vscode-neovim/vscode-neovim#1118]
![nh2](https://user-images.githubusercontent.com/7481548/210127284-32a37b4f-966e-4ccf-a7e5-0101c8c4f31b.gif)

As you can see, when I start linewise visual mode and start selecting more lines, letters get duplicated.
Happens with extension v0.0.95. This does not happen with previous version v0.0.94.

To Reproduce:
Neovim installed on M1 mac.
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-005.local

Tested with a clean init.vim without any plugins.
Also I saw it happen with Go files in my testing. Was not seeing the issue with other files (tested csharp / text files).

**Comment by 0-x-f** [comment]
I guess #1099 fix this problem.
Update extension to 0.0.96 version for checking.

**Comment by miguelski** [comment]
0.0.96 is not listed to download on marketplace https://marketplace.visualstudio.com/items?itemName=asvetliakov.vscode-neovim
where can i get the fix?
