### ISSUE TITLE
Cannot copy from output panel

### ISSUE THREAD

**Issue by ldorigo** [vscode-neovim/vscode-neovim#1123]
Type: <b>Bug</b>

With this extension active, it's impossible to copy output from the "output" pane. Ctrl-c does nothing. It appears as though nvim is enabled (the cursor changes), but copying using nvim (`yy`) doesn't work either.

Extension version: 0.0.95
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:27:19.253Z)
OS version: Linux x64 6.1.1-zen1-1-zen
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics (16 x 4136)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 3, 2|
|Memory (System)|30.77GB (17.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by justinmk** [comment]
search existing issues

**Comment by ldorigo** [comment]
Hello, 

I understand it's a lot of work to maintain oss projects but:

1. It doesn't hurt to be polite to people who take time to report bugs
2. The only related issue I can find is https://github.com/vscode-neovim/vscode-neovim/issues/931 which is both not the same, and marked as resolved without any comment

I am still experiencing this issue.
