### ISSUE TITLE
Dependency version need updating?

### ISSUE THREAD

**Issue by ctstacey** [vscode-neovim/vscode-neovim#1126]
Haven't worked out the dependencies yet.
Raising in case the latter needs updating.

https://github.com/vscode-neovim/vscode-neovim/blob/0bf104748990c35c680df5051718f63f7f5914ad/README.md?plain=1#L59

https://github.com/vscode-neovim/vscode-neovim/blob/0bf104748990c35c680df5051718f63f7f5914ad/package-lock.json#L14

Thanks

**Comment by justinmk** [comment]
readme should be updated, but the package-lock looks ok i guess? it's referring to node-client: https://github.com/neovim/node-client/tags
