### ISSUE TITLE
Toggle block comment works through command palette but not with shortcut (Shift + Alt + A)

### ISSUE THREAD

**Issue by vlrevolution** [vscode-neovim/vscode-neovim#1129]
When using shortcut in visual selection mode to toggle block comment (VSCode own command) it adds an empty block.

Using the command palette works tho.

What's the reason for this and is there a way to fix this?
Would be nice to be able to bind the VSCode's own comment commands and use them with vscode-neovim's visual selections.

Thanks a lot for your time and for this amazing plugin. Keep deving!

**Comment by justinmk** [comment]
> Would be nice to be able to bind the VSCode's own comment commands

documented in the readme and the wiki

**Comment by vlrevolution** [comment]
Thanks, this is completed. I think it would be wise to also put what is said on wiki on the readme actually.

The readme is a bit hard to understand right now. I did not understand it properly and never got the inclination to go look in the wiki. But it does work amazingly now. The nvim plugin solutions don't really work in different contextes.

Those who are struggling to find the info, this is what you should put in init.vim to have commenting with gcc:
```
xmap gc  <Plug>VSCodeCommentary
nmap gc  <Plug>VSCodeCommentary
omap gc  <Plug>VSCodeCommentary
nmap gcc <Plug>VSCodeCommentaryLine
```

**Comment by bassamsdata** [comment]
> Those who are struggling to find the info, this is what you should put in init.vim to have commenting with gcc:

Thank you for these. I really find it hard sometimes with this plugin to get things right. Even though it's an amazing plugin.
But we didn't under stand how it really works with some stuff especially sometimes there's conflicts between old posts, readme, wiki, old video 😔.

I think the maintainers mastered the plugin very well to the point that they can't see it in the eyes of someone new to this world. 🥲

I'm ready to write full documentation (step by step and probably a video) once I understand how it works and how to get things done bc I've been using it for the past 2 weeks and still twerking around myself search for simple thing to do 🙃.
