### ISSUE TITLE
Seems like viewport sync is still bad (leap does weird behavior)

### ISSUE THREAD

**Issue by trueegorletov** [vscode-neovim/vscode-neovim#1131]
Sometimes with this plugin in use, there is a really weird bug that gives a thought about lack of viewport/scroll synchronization, when some changes and updates have been already performed to fix the problem.

For example, when I have a layout like this with the bottom panel opened and cursor on line 22, I am trying to go to line 1 using [leap.nvim](https://github.com/ggandor/leap.nvim), so I type `Sbe`, but plugin responds with no behavior, Looks like it just thinks that this line is out of the viewport, because I am still able to move by the plugin to any line down to 8 (or -14 relatively).

![image](https://user-images.githubusercontent.com/105159089/212487776-83160145-7245-48e5-906d-a1959c166889.png)

 But this offset is not stable: for example, I can't move to any `be*` occurrence when the cursor line is more than 12, but at line 12 and higher all `be*` matches are available.

![image](https://user-images.githubusercontent.com/105159089/212488200-be26ce36-28bd-48c7-a208-bf3a15a55522.png)

When writing this, I've found, that actual behaviour is even more unpredictable: sometimes (after some complex cursor moves by mouse) this occurrences are being approachable even below line 12!

Howbeit, vim mode is used primarly for faster move by keyboard, and it looks like so far this beautiful plugin is not ready to provide it well.

**Comment by nokia-git** [comment]
i did not have this issue, leap.nvim works well for me.
i have about 70 lines on screen, leap.nvim can jump to any line, any word without any abnormal behavior.

**Comment by archilkarchava** [comment]
I also have this problem.
A simple way to simple way to reproduce it:
1. Open a file that's larger than the viewport
2. Move the cursor from the first line to the middle of the screen
3. Close the file, and open some other file
4. Open back the original file, the cursor should be in the position you've previously left it in as long as you have the `workbench.editor.restoreViewState` setting enabled (it should be enabled by default, it will be more difficult to reproduce the issue with this setting disabled, but still possible).
5. Try to use leap or a similar plugin (e.g. hop, lightspeed, easymotion)

I've recorded a short video where I reproduce the problem:
https://user-images.githubusercontent.com/16840190/219684592-ffc0bddf-eaf7-435b-aeb9-18115583c0a1.mp4

I believe the issue appeared in this commit https://github.com/vscode-neovim/vscode-neovim/commit/3036a5a8674afb26372e9f5872365bcc336ab313.

For now, I'm setting `"vscode-neovim.neovimViewportHeightExtend": 70` in my settings.json to work around the issue.

**Comment by theol0403** [comment]
This is simply pending https://github.com/vscode-neovim/vscode-neovim/pull/993
