### ISSUE TITLE
Text bug and highlight in the visual mode only on java

### ISSUE THREAD

**Issue by Smiffeed** [vscode-neovim/vscode-neovim#1132]
![image](https://user-images.githubusercontent.com/97792035/212499003-809d8ca8-4c93-410b-8511-4ecc6f6dbab4.png)
There is no issue in python but not for java I don't know why.
![image](https://user-images.githubusercontent.com/97792035/212498996-f2652b29-fd37-424b-838a-d2165d6d95c8.png)

**Comment by justinmk** [comment]
close to zero info in this bug report. search existing issues, visual mode has some known quirks.

**Comment by vlrevolution** [comment]
Same happening to me.
