### ISSUE TITLE
Save triggers multiple file saves

### ISSUE THREAD

**Issue by Djursing** [vscode-neovim/vscode-neovim#1134]
I've recently run into an issue in VSCode with Neovim.
Every time I save a file in any way it saves it multiple times (2), forcing multiple rebuilds of the binary which triggers the container and causes it to fail most times.

I tried saving in Neovim outside VSCode and found out that it saved it four times instead of once as expected, after a bit of research I added these settings to my `init.lua` file.

```
vim.opt.backup = false
vim.opt.swapfile = false
vim.opt.writebackup = false
```

The above settings forced Neovim to only trigger one save at a time, but the issue of two saves in VSCode still remains.
My `init.lua` has close to no configuration as I'm using VSCode for all I need featurewise but for some reason, I am thinking the save is both triggered for VSCode and the embedded Neovim at the same time instead of just Neovim, but I have no basis for this hypothesis.

Neovim extension `version 0.0.94`, the issue exists on the newest and older versions too.

Has anyone experienced similar issues?

<img width="883" alt="picture of terminal" src="https://user-images.githubusercontent.com/25141019/213655308-8e4395b8-e0bc-4c24-85bf-1ef3b5eacf9c.png">

<img width="718" alt="billede" src="https://user-images.githubusercontent.com/25141019/213659568-6a3fa6fc-9ba2-4e6a-86a2-5f36652eff69.png">

**Comment by theol0403** [comment]
How do you trigger the save? Neovim is not aware of the file path, it only contains a scratch buffer. File management and saving is only done by vscode.

You sure this is not a problem without the extension? Saving just tells vscode to save, and also vscode won't save twice if contents have not changed.

**Comment by Djursing** [comment]
I have tried all methods of saving that I know of in and outside of vscode, whenever Neovim is involved multiple saves are initiated. Everything works as intended if it's just vscode without any neovim.
