### ISSUE TITLE
Intenllisense for init.lua

### ISSUE THREAD

**Issue by jaydamani** [vscode-neovim/vscode-neovim#1136]
I am shifting from neovim to vscode and in my neovim config I configured sumneko and used [hrsh7th/cmp-nvim-lua](https://github.com/hrsh7th/cmp-nvim-lua) to get autocomplete when editing my nvim dot files but vscode-neovim is getting completions from vscode.
I managed to kinda replicate sumneko's behaviour  but I can't get complete for vim.* which came from cmp-nvim-lua plugin, is there a way to get something similar to that plugin's behaviour or better yet something that combines completion from both lsp and neovim?

**Comment by theol0403** [comment]
- install https://marketplace.visualstudio.com/items?itemName=sumneko.lua
- run `lua=vim.api.nvim_get_runtime_file("", true)` to get runtime path
- Add runtime path to settings.json, ex:
```
  "Lua.workspace.library": ["/usr/share/nvim/runtime/"],
  "Lua.diagnostics.globals": ["vim"]
```
- profit
