### ISSUE TITLE
`<Leader><Leader>` not working when `vim.g.mapleader = ' '`

### ISSUE THREAD

**Issue by craigmac** [vscode-neovim/vscode-neovim#1137]
Repro, in init.vim

```vim
let mapleader="\<Space>"
nnoremap <Leader><Leader> <Cmd>call VSCodeNotify("workbench.action.quickOpen")<CR>
nnoremap <Leader>w <Cmd>call VSCodeCall("workbench.action.files.save")<CR>
```

You'll get 'Space, Space' is not a command message at the bottom for the `<Leader>w` works. If you change mapleader to `U` and press it twice, it works as expected.  I think there's something about finding space twice in the LHS of the map. I tried this theory out with this mapping:

```vim
nnoremap <Leader>w<Leader> <Cmd>call VSCodeCall("workbench.action.files.save")<CR>
```

And it doesn't work (space character appearing twice) in the mapping.

**Comment by craigmac** [comment]
Also tried these variations:

```lua
  vim.keymap.set('n', '<Leader> ', '<Cmd>call VSCodeNotify("workbench.action.quickOpen")<CR>')
  vim.keymap.set('n', '<Leader><Leader>', '<Cmd>call VSCodeNotify("workbench.action.quickOpen")<CR>', { noremap = false })
```

This one works fine though:

```lua
  vim.keymap.set('n', '<Leader>w', '<Cmd>call VSCodeCall("workbench.action.files.save")<CR>')
```

**Comment by nubilfi** [comment]
I'm using `lua` file, I've tried using `mapleader` & `maplocalleader`, and still not working:

```
vim.g.mapleader = "," -- leader key
vim.g.maplocalleader = "," -- leader key
```

**Comment by NerDante** [comment]
> I'm using `lua` file, I've tried using `mapleader` & `maplocalleader`, and still not working:
> 
> ```
> vim.g.mapleader = "," -- leader key
> vim.g.maplocalleader = "," -- leader key
> ```

i have same situation, did you find the way?

**Comment by craigmac** [comment]
@NerDante this issue is about a situation when using space as leader,  I'm not sure how @nubilfi comment relates to that, they are using a different leader key. They should open a new issue about whatever it is that is failing with that mapping.

**Comment by feedoom** [comment]
is you bind other keys in keybindings.json about space ? try again after clean that

**Comment by tieniu1** [comment]
![carbon](https://github.com/vscode-neovim/vscode-neovim/assets/49060203/81a8b936-bd10-4497-a445-230eadbb67c9)
My configuration takes effect, note that modifying leader to space must precede the other leader shortcuts.
Hope this helps!

**Comment by craigmac** [comment]
Is there a workaround?

**Comment by theol0403** [comment]
Sorry, this simply cannot be a bug with vscode-neovim. There is a problem with your vim config. 

Try setting mapleader = " ".

**Comment by craigmac** [comment]
@theol0403 do you mean that you can't repro this? just want to rule that out before digging into my setup

**Comment by theol0403** [comment]
Yeah, I can't reproduce. Your reproduction steps work fine for me.

**Comment by theol0403** [comment]
@craigmac I just have no idea how this would be different in vscode-neovim, we don't touch leader or anything

**Comment by Deuscx** [comment]
@justinmk hello, how to resolve this issue.

**Comment by craigmac** [comment]
@Deuscx see my comment above, if it's a double-leader issue, space space, then map it like `<leader><space>` instead of `<leader><leader>`, that's what this issue was originally about and my solution is posted here as well.

**Comment by Deuscx** [comment]
@craigmac  I found that setting this to disable the original space action resolves this question.  thanks anyway.
```
    map("", "<Space>", "<Nop>", opts)
```

**Comment by ListenLove** [comment]
Could someone extracted the answer from this issue?

**Comment by ListenLove** [comment]
Could someone extract the answer from this issue?

**Comment by Syakhisk** [comment]
For anyone looking for the answer:

Put this at the top of your `init.lua`
```lua
vim.keymap.set("", "<Space>", "<Nop>")
vim.g.mapleader = " "
```

The default mapping for `<Space>` need to be deleted for this to work.
Since `vim.keymap.del` is not working so mapping it to `<Nop>` should do the trick.

cc: @ListenLove

**Comment by ListenLove** [comment]
> For anyone looking for the answer:
> 
> Put this at the top of your `init.lua`
> 
> ```lua
> vim.keymap.set("", "<Space>", "<Nop>")
> vim.g.mapleader = " "
> ```
> 
> The default mapping for `<Space>` need to be deleted for this to work. Since `vim.keymap.del` is not working so mapping it to `<Nop>` should do the trick.
> 
> cc: @ListenLove

Thank Very Much！It Works！
@Syakhisk
