### ISSUE TITLE
visual selection issue with gd script file

### ISSUE THREAD

**Issue by doongjohn** [vscode-neovim/vscode-neovim#1138]
![Recording 2023-01-26 at 18 33 30](https://user-images.githubusercontent.com/40219740/214802865-7fe0f16e-7ace-4488-9aca-d6c89c80a66d.gif)

Windows 11
NVIM v0.8.2
vscode-neovim v0.0.95

tested without any plugins

other file format seems to work fine

**Comment by justinmk** [comment]
search issue tracker for "visual"
