### ISSUE TITLE
Allow startup with `-i NONE`

### ISSUE THREAD

**Issue by karmaral** [vscode-neovim/vscode-neovim#1141]
Hello!
I'm running on Windows 10 and this ShaDa file getting corrupted seems to be a common occurence. 

From what I've gathered, the recommended solution is to simply disable shada. I can circumvent this with `set shada="NONE"` but I thought, since there's a `--clear` option, perhaps it'd be handy to have an `-i NONE` as well?

Is it too specific to be worth it? What do you think? 
I could make a PR if this was welcome.

**Comment by justinmk** [comment]
> I can circumvent this with `set shada="NONE"`

yes

> but I thought, since there's a `--clear` option, perhaps it'd be handy to have an `-i NONE` as well?

why?
