### ISSUE TITLE
Issues with rendering blank highlight in VSCode | Leap.nvim

### ISSUE THREAD

**Issue by snacksncode** [vscode-neovim/vscode-neovim#1143]
Hi, I'm noticing issues with "empty" highlight in VSCode which should block the character underneath. I'm using `leap.nvim`. It has some options for highlight colors via `:h leap-highlight`, but there's no option to set colors for this "empty" highlight cell

## Showcase

| Neovim  | VSCode |
| ------------- | ------------- |
| ![nvim](https://user-images.githubusercontent.com/50829382/215358222-7ad43f6e-a173-42ef-b5b0-9237482c115f.png) | ![vscode](https://user-images.githubusercontent.com/50829382/215358234-91212c1c-0d74-4410-8a11-25915e288dfe.png) |

VSCode renders the highlight but you can see the character that is actually in the word, so every highlight pair ends with `l` as I'm looking for the `className`.

## Reproduction
1. Install `leap.nvim`...
2. Search for something, in my case `scl`
3. Put the cursor back where you started
4. Search for `s<Enter>`, this will repeat your last search and will render those empty cells to indicate that you need to press just the first character

If this issue is not with this extension and I need to ask guys from `leap.nvim`, please let me know

**Comment by snacksncode** [comment]
Also when a keyword has it's opacity lowered, same happens to the overlay, not sure if this is fixable / intended.

![image](https://user-images.githubusercontent.com/50829382/215507792-03d42b51-1e10-40dc-bbdb-fef4b5570a8b.png)

**Comment by justinmk** [comment]
highlighting is best-effort

**Comment by theol0403** [comment]
I think I'd like to keep this issue open, as it tracks a real disconnect in the highlight parsing code.

**Comment by snacksncode** [comment]
Thank you so much for looking into this @theol0403 :sparkles:
