### ISSUE TITLE
Bug: Visual mode for files makes letters appear in the line that is selected

### ISSUE THREAD

**Issue by eleijonmarck** [vscode-neovim/vscode-neovim#1144]
Have disabled all other plugins expect the colorscheme.

https://user-images.githubusercontent.com/7727602/215477372-ce102f74-c17e-4ac6-8b82-3ab926d48320.mov

**Comment by ian-h-chamberlain** [comment]
I've been seeing this for a while too, possibly since the last update?

Perhaps worth noting is this seems to be cosmetic — the selection will look garbled, but as far as I can tell the backing buffer has the right selection, since e.g. `vi(y` still works as expected and yank the selection.

**Comment by b4ljk** [comment]
same issue, but looks like this
<img width="475" alt="image" src="https://user-images.githubusercontent.com/84488223/216487955-29852665-2ded-4651-b95f-b13fdccdbcae.png">

**Comment by oleynikandrey** [comment]
I have the same issue, but only with `.go` files.

**Comment by eleijonmarck** [comment]
@oleynikandrey it is actually true for me. I did not notice it but this is for `.go` files for me

**Comment by ian-h-chamberlain** [comment]
Hmm, the example @b4ljk posted doesn't look like Go, but I think it's true for me as well that most of the times I've seen it has been Go — I wonder if certain text decorations used by the Go extension make it more likely to occur? Offhand, the only ones I can think of:

- inlay type/parameter hints
- semantic token highlighting
- code lenses (e.g. `Run Test`, `Debug Test`)

Of those, none of them are unique to the Go extension but perhaps some combination of all of them causes it. It doesn't seem to be trivially reproducible in my case (reloading window seems to clear the messed up state). 

In most other languages, I use spaces for indentation, whereas Go uses tabs — perhaps that could be related too?

**Comment by eleijonmarck** [comment]
il keep it at all files again and see we can get to the bottom of this. I have no clue as I have to restart and reinstall all plugins but it appears as soon as I do it

**Comment by eleijonmarck** [comment]
I tried the nightly builds for copilot and vscode and now it seems to work. but it might appear again. like arnold says "I will be back"

**Comment by brnt** [comment]
I may be running into the same issue. On first insert the only suggestion is the letter 'i' (consistently):
<img width="1316" alt="Screenshot 2023-06-01 at 1 27 49 PM" src="https://github.com/vscode-neovim/vscode-neovim/assets/1072638/f570ab87-a61a-43b5-a3c1-22aa74339542">

Hitting <tab> inserts an actual tab the first time, but if I backspace back to the first of the line, it gets the suggestion nearly right, but with weird extra characters:
<img width="1316" alt="Screenshot 2023-06-01 at 1 27 57 PM" src="https://github.com/vscode-neovim/vscode-neovim/assets/1072638/9d38a943-1cf7-471d-9a82-6ba244a4e1a2">

And sometimes the chars are at the end of the suggestion (conspicuously the same char combination):
<img width="1316" alt="Screenshot 2023-06-01 at 1 28 18 PM" src="https://github.com/vscode-neovim/vscode-neovim/assets/1072638/b555bf5d-8679-415d-b397-623cb32b2d67">

Interestingly, if I start typing the suggestion, the weird trailing chars in one case stop being displayed:

<img width="899" alt="Screenshot 2023-06-01 at 1 47 43 PM" src="https://github.com/vscode-neovim/vscode-neovim/assets/1072638/289991c9-8180-4d54-b22c-34b13b71b0f1">
<img width="882" alt="Screenshot 2023-06-01 at 1 47 59 PM" src="https://github.com/vscode-neovim/vscode-neovim/assets/1072638/648eb411-d299-48e0-bbfa-eb056c13604f">

Note that for these screenshots, I was using my standard `.vimrc`, as evidenced by the nvim customizations in the vscode built-in terminal. I also tried with an empty `.vimrc` and no `~/.vim/` folder to make sure there was nothing in my n/vim settings that were introducing weird characters or anything. I also disabled every extension (all of 'em) except Copilot and Neovim.

**Comment by theol0403** [comment]
Fwiw this is caused by bugs in the highlighting/extmark code. It is cosmetic only, but obviously annoying.

**Comment by ian-h-chamberlain** [comment]
I'm not sure if this is related, but I'm also seeing a similar issue when the vscode-neovim cursor is shown in a comment that has a wrapping line (Using `vscode-pull-request-github` in this case).

https://github.com/vscode-neovim/vscode-neovim/assets/11131775/dfcd385b-1f1a-47cc-9e27-282e5623647f

Is this the same, or should I file a separate issue for this cursor misalignment?

**Comment by theol0403** [comment]
@ian-h-chamberlain honestly I feel like this is an issue with vscode, we don't touch typing or cursor in insert mode

**Comment by annopkomol** [comment]
@ian-h-chamberlain @eleijonmarck  The problem is back again in 0.4.0 (was working fine in 0.3.2). It seems that the problem does not only exist in Go but in the other languages where the indent is set to tab as well
<img width="483" alt="image" src="https://github.com/vscode-neovim/vscode-neovim/assets/27771872/146e698c-fe76-4d72-b669-4e134101711c">
From the image above, I tried to change the indent on line no.3, from space to tab, inside a js file and select the whole function. It turned out that the letters only appear on line no.3.

I also tried to select the whole .go file, and only the lines without the indent(tab) have no letters appearing in the line.

**Comment by theol0403** [comment]
I've narrowed down one source of the visual bug.

Apparently, when a custom hl group (visual fake cursor) is placed on top of a visual selection, the `listchars` disappear for that cell. Because of our listchars hack, the tab isn't being counted properly. Not sure if this is upstream or not yet.

**Comment by andodet** [comment]
Can confirm that I'm having the sampe problem. It seems that the issue arises only when the selection starts before tab characters.
If I enter the visual selection from the middle of the first line everything seems to be rendered well.

![tabs_behaviour](https://github.com/vscode-neovim/vscode-neovim/assets/29178712/5bb79fb1-e76e-4ce5-aa01-0fdbd965a1d0)

**Comment by eleijonmarck** [comment]
I have now switched to the vim integration of vscode. This works fine

**Comment by TiLopes** [comment]
Is there any fix yet?
