### ISSUE TITLE
cmd+d to do multiselect / multicursor and then apply neovim commands to each occurrence does not work

### ISSUE THREAD

**Issue by 55Cancri** [vscode-neovim/vscode-neovim#1145]
When I press `viw` to select a word, then press `cmd+d` to select the other instances, it first activates Match Case and Match Whole Word settings, then starts highlighting the other occurrences.

However, when I then press something like `ciw` to change the words while all the occurrences are highlighted, only the first one changes.
1. How do I begin selecting occurrences immediately, without first activating those settings?
2. How do I apply the neovim keys to each currently selected occurrence instead of just the first one?

**Comment by theol0403** [comment]
Multi cursor not supported in visual mode

**Comment by 55Cancri** [comment]
> Multi cursor not supported in visual mode

Normal vscode vim with jumpy2 plugins works wonders

**Comment by xiyaowong** [comment]
Can provide a function that encapsulates editor.action.addSelectionToNextFindMatch to support this feature
<img src="https://github.com/vscode-neovim/vscode-neovim/assets/47070852/65366365-07f6-4f7a-9949-9dbeed7076b0" width="400px" />

**Comment by theol0403** [comment]
That would be nice, if we wrapped all the muticursor commands in normal mode like "select all word under cursor" and all the other ones, that would nicely transition you into insert mode.

**Comment by ghry5** [comment]
It's a little janky but seems to work. This is what I came up with:
```
  vim.keymap.set("v", "<D-d>", function()
    local sel_start = vim.fn.getpos("v")
    local sel_end = vim.fn.getpos(".")
    vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<esc>", true, false, true), "v", false)
    vim.defer_fn(function()
      vim.cmd.startinsert()
      vscode.notify_range_pos("editor.action.addSelectionToNextFindMatch", sel_start[2], sel_end[2], sel_start[3],
        sel_end[3], true)
    end, 20)
  end, opts)
```

To work it needs to forward the cmd+d keystroke from vscode:
```
  {
    "command": "vscode-neovim.send",
    "key": "cmd+d",
    "when": "editorTextFocus && neovim.mode != insert",
    "args": "<D-d>"
  },
  {
    "key": "cmd+d",
    "command": "editor.action.addSelectionToNextFindMatch",
    "when": "editorFocus && neovim.mode != 'visual'"
  },
  {
    "key": "cmd+d",
    "command": "-editor.action.addSelectionToNextFindMatch",
    "when": "editorFocus"
  }
```

First keybinding sends cmd+d to vscode-neovim if in visual mode. second keybinding allows normal vscodes cmd+d behaviour once in insert mode. The thrid disables the default vscode keybinding.

It seems to work very well for me. Only undo functionality is a little wierd. If I select and edit using this method and then hit undo it will undo only one typed character at a time.
If however i go into insert mode normally select the word/phrase using shift+arrow keys (vscode selection) and then start hitting cmd+d to get my selection, Undo will undo everything i typed at once (what I would expect)

**Comment by xiyaowong** [comment]
After the next release, plugin [vscode-neovim/vscode-multi-cursor.nvim](https://github.com/vscode-neovim/vscode-multi-cursor.nvim) will be ready for use. Not sure if it meets everyone’s needs, but it should make multi-cursor easier to use.
