### ISSUE TITLE
how to use remote installed neovim binary

### ISSUE THREAD

**Issue by vync** [vscode-neovim/vscode-neovim#1146]
Hi,

I've tried with versions 0.0.95, 0.0.85 and 0.0.80 but when I set 
"remote.extensionKind": {
        "asvetliakov.vscode-neovim": ["workspace"]
}
on the local settings.json I cannot get the extension to use the remotely installed nvim executable.

I thought this would now be possible because of https://github.com/vscode-neovim/vscode-neovim/pull/668.

Any suggestions on what I may be doing wrong please?

**Comment by trahman1318** [comment]
I was having trouble with this, but what you have should work. In VSCode, hit `cmd+shift+p` and search "Running Extensions". If it is working properly it should look like this
<img width="247" alt="image" src="https://user-images.githubusercontent.com/62212154/216770456-acb6bd9d-bb2e-49b1-b020-e89f4749ee9c.png">
If not, make sure that the extension is installed on the remote & make sure nvim is installed on the remote.

**Comment by theol0403** [comment]
https://github.com/vscode-neovim/vscode-neovim/issues/262
