### ISSUE TITLE
Search replace with confirmation :%s/foo/bar/gc does not scroll automatically

### ISSUE THREAD

**Issue by trahman1318** [vscode-neovim/vscode-neovim#1149]
Having the same issue as https://github.com/vscode-neovim/vscode-neovim/issues/999

MacBook Pro (non-M1)
MacOS Monterey 12.6.3
empty init.vim
empty settings.json
no vscode extensions
NVIM v0.8.3
vscode v1.75.0
extension version v0.0.95

Tried running `%s/get_option/get_option_new/gc` on this [file](https://github.com/mongodb/mongo/blob/450ffbb63d5b265d2e17c6ec4556f030099b9f60/SConstruct) with my cursor at the top. I'm able to confirm replacements, but there is no scrolling which makes it difficult to use. Does anyone else have this issue? Or is there a workaround?

**Comment by ctstacey** [comment]
Sorry, I don't have answers or workarounds at this time (others might?), but here are some clues to help trouble shoot this issue...

I can replicate with a minimal file.

Windows_NT x64 10.0.19044
VSCode 1.75.0
NVIM 0.8.1
VSCode-Neovim 0.0.97

To replicate:
1. open new file (in VSCode with VSCode-Neovim extension enabled)
2. add the letter `a` on line 2
3. add the letter `a` on line 92
4. move to line 1
5. use `%s/a/b/gc` to substitute globally (with scroll and confirm) and notice it will not scroll to the second `a` (after replacing, or not, the first `a`)

If you are successful, try varying the number of lines between the two `a`s until it fails to scroll to the second `a` (after replacing, or not, the first `a`).

It did not make any difference how much text was in the lines between the two `a`s.

I also found that moving to around line 65 meant when I performed the substitute, the extension would not scroll to the first `a` (to make the first substitution on confirmation).

**Comment by LawrenceLiu023** [comment]
I have the same problem. The cursor does not follow the matches and the match waiting to be confirmed is highlighted in the same colour as the other matches, making it difficult to find the right one. Even with an empty init.vim, the problem remains unsolved.

VSCode 1.75.1
Neovim 0.8.2
VSCode-Neovim 0.0.97
Windows11 10.0.22000.1516

**Comment by xiyaowong** [comment]
Similar to https://github.com/vscode-neovim/vscode-neovim/issues/1555#issuecomment-1773966732

**Comment by jpmorris** [comment]
I'm confused with all the all the highlight/search related bugs and which were fixed (if any).  I see $1575 is supposed to fix this scroll bug.  I see #1888 is still open.  I still have issue scrolling with confirmation (no nvim config files, `neovimClean` selected, all plugins disabled. Was this actually fixed?

**Comment by xiyaowong** [comment]
Welcome contributions.

**Comment by jpmorris** [comment]
Happy to help how I can. Though don't know vim/vscode/go enough to actually commit any code.

**Comment by jpmorris** [comment]
By installing nvim-hlslens plugin, it seems to fix this issue (the scroll not the extra highlights).
