### ISSUE TITLE
Any ideas for making go-interface-annotations to work with vscode-neovim?

### ISSUE THREAD

**Issue by moqsien** [vscode-neovim/vscode-neovim#1153]
[go-interface-annotations](https://marketplace.visualstudio.com/items?itemName=galkowskit.go-interface-annotations)

Since go-interface-annotations uses vscode's editors, it does not work with vscode-neovim at present.

**Comment by theol0403** [comment]
I think it should work out of the box?

**Comment by moqsien** [comment]
> I think it should work out of the box?

yeah, the builtin command "codelens.showLensesInCurrentLine" fits my need.
thx anyway.
