### ISSUE TITLE
vscode.lua: No such file or directory

### ISSUE THREAD

**Issue by mattia72** [vscode-neovim/vscode-neovim#1154]
If I start vscode I get the following error:

```
Error detected while processing pre-vimrc command line..script c:\\Users\\Ákos\\.vscode\\extensions\\asvetliakov.vscode-neovim-0.0.97\vim\vscode-neovim.vim:
line  154:
E5108: Error executing lua vim/_init_packages.lua:24: cannot open c:\\Users\Ákos\.vscode\extensions\asvetliakov.vscode-neovim-0.0.97\runtime/lua/vscode.lua: No such file or directory
stack traceback:
	[C]: in function 'error'
	vim/_init_packages.lua:24: in function <vim/_init_packages.lua:18>
	[C]: in function 'require'
	[string ":lua"]:1: in main chunk
```
The cause may be the character 'Á' in my username. 
On other PC with other username, the same configuration works well.

After this error, the extension seems to work fine. It is only a bothering issue.

**Comment by justinmk** [comment]
Looks like https://github.com/neovim/neovim/issues/18122

**Comment by mattia72** [comment]
Indeed. And the utf8 settings mentioned in [this comment](https://github.com/neovim/neovim/issues/18122#issuecomment-1428055012) solves the issue.

**Comment by VoidPaul** [comment]
> Indeed. And the utf8 settings mentioned in [this comment](https://github.com/neovim/neovim/issues/18122#issuecomment-1428055012) solves the issue.

The page no longer exists and I'm facing the same problem. Mind to share?

**Comment by justinmk** [comment]
That's weird...
