### ISSUE TITLE
Editing/deleting lines in C++ file is full of bugs

### ISSUE THREAD

**Issue by yosuanicolaus** [vscode-neovim/vscode-neovim#1157]
Whenever I use "o" or "d" operator (to make/delete lines), the editor always behave unexpectedly.
It will show random character that doesn't actually exist at some part of the file. They returns to normal after changing tab to another file and coming back.

In this video, I used "o", "Enter" a few times in insert mode, delete using "dd", and "d3j"

[Screencast from 18-02-23 11:35:44.webm](https://user-images.githubusercontent.com/87525599/219821656-c89a0db0-bc19-417a-8573-edbe36a887bf.webm)

**Comment by theol0403** [comment]
Please reproduce with empty init.vim.

**Comment by yosuanicolaus** [comment]
sorry, yeah this was a half-assed issue. I didn't know back then that the init.vim has to be empty
