### ISSUE TITLE
Clicking through the VSCode search dialog selects a chunk of text

### ISSUE THREAD

**Issue by awilkins** [vscode-neovim/vscode-neovim#1158]
Double-clicking a search result in the VSCode search dialog causes a chunk of the document you have entered to be selected, and the mode to start as VISUAL.

It seems to be one page-height worth of lines, ie, if you resize the window to accommodate N lines, N lines will be the selection size.

![chunk-of-select](https://user-images.githubusercontent.com/368399/219943323-1d5fb1e1-565c-40eb-9aba-78f7622a50c7.gif)

Expected :

- Document opens with cursor on selected line in NORMAL mode

---

Using the keyboard by e.g. navigating the search results with j/k and using <kbd>g d</kbd> to go to the search hit works fine.

**Comment by cnut1648** [comment]
I have the same issue, did you figure out how to tackle this?

**Comment by justinmk** [comment]
https://github.com/vscode-neovim/vscode-neovim/issues?q=is%3Aissue+is%3Aopen+visual
