### ISSUE TITLE
Characters break code highlighting randomly.

### ISSUE THREAD

**Issue by Adam-Antios** [vscode-neovim/vscode-neovim#1164]
Characters are highlighted with different colors or even become transparent randomly.

**Comment by lamhungypl** [comment]
disable tree-sitter in your neovim config.

**Comment by Adam-Antios** [comment]
I just have vanilla Neovim installed. No plugins are installed. I don't even have a custom config.

**Comment by justinmk** [comment]
There are existing issues covering display quirks.

The highlighting support is currently best-effort.
