### ISSUE TITLE
Azure Data Studio

### ISSUE THREAD

**Issue by titouancreach** [vscode-neovim/vscode-neovim#1165]
Hello,

Azure Data Studio is an SQL Editor based on VSCode (basically the same thing but with a different extension store). A lot of extensions are cross compatible. If it takes no time, can we make vscode-neovim available for that product ? 

I naively tried to compile the vsix and drag and drop but with no luck and this message:
```
Unable to install extension 'asvetliakov.vscode-neovim' as it is not compatible with the current VS Code engine version '1.67.0'.  
```

**Comment by justinmk** [comment]
vscode-neovim requires vscode 1.71 : https://github.com/vscode-neovim/vscode-neovim/blob/fd152cf8d539e3ae28a566d9aad6bca05208755f/package.json#L21

once azure data studio updates to that, it should work
