### ISSUE TITLE
win32 path not found allthough seems to be set correctly

### ISSUE THREAD

**Issue by dboeckenhoff** [vscode-neovim/vscode-neovim#1168]
Hi, My nvim path is not found under windows with the error "Neovim spawn error: spawn %userprofile%/.local/bin/nvim.exe".
My settings.json says:

`"vscode-neovim.neovimExecutablePaths.win32": "C:\\Users\\danie\\.local\\bin\\nvim.exe",`

I checked thousand times that the path given above is actually correct and nvim is working fine. Astonishingly the same configuration works on my laptop.

I turned set logging level to verbose but it is not revealing much unexpected behaviour to my understanding:
```
[Extension Host] 2023-03-06T17:46:24.431Z MainController: Spawning nvim, path: %userprofile%/.local/bin/nvim.exe, useWsl: false, args: ["-N","--embed","-c","source c:\\\\Users\\\\danie\\\\.vscode\\\\extensions\\\\asvetliakov.vscode-neovim-0.0.97/vim/vscode-options.vim","--cmd","source c:\\\\Users\\\\danie\\\\.vscode\\\\extensions\\\\asvetliakov.vscode-neovim-0.0.97/vim/vscode-neovim.vim"]
```

I run on Windows 10. vscode 1.74.1

Thanks for this awesome project!!!

**Comment by theol0403** [comment]
It probably doesn't understand %userprofile%. Something in main manager is trying to be too smart. Just move it for now.

**Comment by WillEhrendreich** [comment]
@dboeckenhoff you may be running into what i was. if I happened to have neovim open already, like in the terminal, and then open vscode, it gives an access error like it's locked. what i did was to copy my neovim installation dir, give it a new name like "c:/NeovimVSCodeExecutable/bin/nvim.exe" then point vscode at that. why does this even error? who knows! doesn't seem to bother any other thing that wants to use neovim, you can have multiple instances of any number of front ends open, and I haven't seen any of them complain about sharing the same exe. but this? HOW 
DARE YOU SIR! lol. anyway, I hope that helps.

**Comment by xiyaowong** [comment]
II use Windows and frequently open multiple VS Code windows without encountering such issues. Please confirm if the problem exists
