### ISSUE TITLE
Problem with commenting multiple line code with "control + /" under macOS environment

### ISSUE THREAD

**Issue by GustafXTT** [vscode-neovim/vscode-neovim#1169]
"control + /" will comment all code selected by visual mode but a system beep will occur.

**Comment by GustafXTT** [comment]
Just tried cmd + / will only comment the line of code where my cursor is while selecting by visual mode, not the whole visual block

**Comment by Jendker** [comment]
Apologies. I forgot that I had to create a VS Code keybinding for this. Here it goes:
```
    {
        "key": "cmd+/",
        "command": "vscode-neovim.send",
        "when": "editorTextFocus && neovim.ctrlKeysNormal && neovim.init && neovim.mode != 'insert'",
        "args": "<C-/>"
    },
```

**Comment by GustafXTT** [comment]
Lovely, thank you

**Comment by LaurensUP** [comment]
@Jendker Thank you, this works!
However, the documentation says it should work out of the box. 

> Visual modes don't produce VSCode selections, so any VSCode commands expecting selection won't work. To round the corners, invoking the VSCode command picker from visual mode through the default hotkeys (f1/ctrl/cmd+shift+p) converts VIM selection to real VSCode selection. This conversion is also done automatically for some commands like commenting and formatting. 

Any clue why we need the custom keymap?
