### ISSUE TITLE
`o` opens new line with different indentation

### ISSUE THREAD

**Issue by still-dreaming-1** [vscode-neovim/vscode-neovim#1172]
I'm trying to get `o` from normal mode to open a new line below and start with whatever indentation VSCode would normally give it if I was not using Neovim. I tried setting autoindent and/or smartindent. I tried leaving all that unchanged. I tried setting both to be off. I tried some different custom mappings for `o`, such as `A<CR>`. That one is strange because if I press `A` and then "enter", it does start the next line indented properly, but if I use a mapping to do it, it does not. I tried using the clean option with no config, and I tried that in combination with setting those indent options without doing it in a config file. I even tried calling out to `VSCodeNotify('editor.action.reindentselectedlines')` at the end of the custom mapping to force it to indent the line the way VSCode would, and it always just ends up indenting the line where I started from instead of the new line it is at...

**Comment by still-dreaming-1** [comment]
Is there some way to send the enter to key to VS Code? Perhaps I could have a map that does `A<CR>` except the CR part is sent to VS Code instead of Neovim? This works if I am just pressing the keys.

**Comment by still-dreaming-1** [comment]
I figured it out. Here is the mapping written in lua:
```
vim.keymap.set( -- change o in normal mode to also auto indent using VS Code
   'n',
   'o',
   "A<CR><esc><Cmd>call VSCodeNotifyRange('editor.action.reindentselectedlines', line('.'), line('.'), 1)<CR>a"
)
```

The calls to `line('.')` get the current line. The `1` toward the end cursor from jumping back to the line where it started after it is all done. `a` is needed at the end to leave you in insert mode.

**Comment by maxrzaw** [comment]
> I figured it out. Here is the mapping written in lua:
> 
> ```
> vim.keymap.set( -- change o in normal mode to also auto indent using VSCode
>    'n',
>    'o',
>    "o<Cmd>call VSCodeNotifyRange('editor.action.reindentselectedlines', line('.'), line('.'), 1)<CR>"
> )
> ```
> 
> The calls to `line('.')` get the current line number. The `1` towards the end prevents the cursor from jumping back to the line where it started after it is all done.

Adding to this, in order to get `O` to function as expected I used a modified version swapping each instance of `line('.')` with `line('.')-1`.

**Comment by still-dreaming-1** [comment]
I keep having more and more issues with different mappings that need something like this in it. There really just needs to be a setting for this extension where insert mode behaves how it normally would in VSCode without Neovim even if it were from a mapping. So what I mean is, normally when you use insert mode, VSCode behaves as normal, but for some reason if a mapping takes it into insert mode and then does other things, that is not the case.

**Comment by still-dreaming-1** [comment]
I've been working on this one for many hours. Was really tricky, so I have to share it:

```
vim.keymap.set(
   'n',
   '<leader><CR>',
   'i<CR><Esc><Cmd>call VSCodeCallRange("editor.action.reindentselectedlines", line("."), line("."), 0)<CR><Esc>^'
)
```

This is one of my most used mappings. While in normal mode, It moves everything after the cursor to the next line, leaving the cursor on that next line at the same character it started out on. In this mapping, I had to use the blocking version, VSCodeCallRange(), in order for the ^ at the end to actually work. Otherwise the cursor is at a different part of the line.

**Comment by justinmk** [comment]
> There really just needs to be a setting for this extension where insert mode behaves how it normally would in VSCode without Neovim even if it were from a mapping. So ... if a mapping takes it into insert mode and then does other things

That is not really possible. vscode-neovim has no way to intercept the internals of nvim mappings.

**Comment by theol0403** [comment]
Dup of https://github.com/vscode-neovim/vscode-neovim/issues/799
