### ISSUE TITLE
asvetliakov/vim-easymotion will open vscode output panel when triggered

### ISSUE THREAD

**Issue by Napoleon-Jm** [vscode-neovim/vscode-neovim#1173]
When I use easymotion, like easymotion-s2, will auto open vscode's output panel.

```

let g:EasyMotion_do_mapping = 0 " Disable default mappings
let g:EasyMotion_smartcase = 1
nmap s <Plug>(easymotion-s2)

```

When I press ```s-<letter>-<letter>```, this panel will open that before is closed.

![image](https://user-images.githubusercontent.com/16489162/224461220-9aca6381-b294-406e-b1fc-aa565e0e365a.png)

When I toggle this, can not stop the output panel auto open nether.
![image](https://user-images.githubusercontent.com/16489162/224462225-de823bb2-e336-419a-8cfa-ce43ab5e4933.png)

**Comment by Napoleon-Jm** [comment]
repeated.

**Comment by gulliver-madrid** [comment]
Duplicate of https://github.com/vscode-neovim/vscode-neovim/issues/910
