### ISSUE TITLE
How to access VSCode* functions within lua without cmd

### ISSUE THREAD

**Issue by Visual-Dawg** [vscode-neovim/vscode-neovim#1174]
I want to execute `workbench.action.quickOpen` with `tab` so that I do not have to hold `cmd+tab`.

However when I use this binding, the cursor jumps to the bottom of the file (this seems to happen with all `<Cmd>` commands, even with a blank config.), making jumping between files a bit uneasy.

```lua
vim.keymap.set('n', '<tab>', '[[<Cmd>call VSCodeCall("workbench.action.quickOpen")<CR>]]')
```

However if a function is executed instead, no jumps happen.
```lua
vim.keymap.set('n', '<tab>', function()
    print("Open quickOpen")
end)
```

So my question is how can I access `VSCodeCall` from the `.lua` config?

**Comment by justinmk** [comment]
vim.fn['VSCodeCall']


    :help vim.fn
