### ISSUE TITLE
"Stage Selected Ranges" only stages one line

### ISSUE THREAD

**Issue by adamjhawley** [vscode-neovim/vscode-neovim#1181]
The "Stage Selected Ranges" button can be found in the context menu when in viewing the 'Working Tree' diff.

When I have the 'vscode-neovim' extension **disabled**, this button stages **ALL** of the lines selected.

When I have the 'vscode-neovim' extension **enabled**, this button stages a **SINGLE** line where the cursor is placed.

Note: using a keybinding or the command-palette to "Stage Selected Ranges" does work as expected.

**Comment by JakobGM** [comment]
I also have this exact same problem, unfortunately, trying to emulate the behavior of [`gitsign.nvim`](https://github.com/lewis6991/gitsigns.nvim)'s `require("gitsigns").stage_hunk`.

**Comment by jackblk** [comment]
Is there anyway to disable this extension in only Working Tree mode?
