### ISSUE TITLE
Issues on startup

### ISSUE THREAD

**Issue by dglav** [vscode-neovim/vscode-neovim#1184]
* When starting vscode, swap files seem to be created and cause conflicts. They open in my vscode window even though I have nothing to do with them. (screen recording)
* When I close the windows and try to edit a file, errors occur in the OUTPUT tab (example error -> screenshot 1)
* After a little while, the errors go away and I can use Neovim. 
* While using Neovim, I get continuous errors (screenshot 2)

Things I have tried:
* Deleting the swap files manually does not fix the issue.
* Reinstalling neovim itself, the extension, and vscode does not fix the issue.

https://user-images.githubusercontent.com/34477242/227435861-026bf24d-ef98-456c-813a-56da3906a09a.mov

<img width="469" alt="image" src="https://user-images.githubusercontent.com/34477242/227435818-7d7e02ed-6654-4e3b-89cf-c3efb282eb13.png">

<img width="461" alt="image" src="https://user-images.githubusercontent.com/34477242/227436266-7b5d8826-e389-4207-8302-69ec86d6d8a0.png">

**Comment by justinmk** [comment]
Always mention exact `nvim` version.

Try without your nvim config, and narrow down the issue. `:help bisect`

**Comment by dglav** [comment]
The problem was that init.vim was not created automatically, so I had to create it and set the path in vscode.
Just in case someone else has the same problem...
