### ISSUE TITLE
Unable to load other files from init.lua

### ISSUE THREAD

**Issue by regisverdin** [vscode-neovim/vscode-neovim#1188]
I had previously gotten this plugin working well, and was using packer to load hop.nvim successfully. 
It stopped working a few weeks ago, and I'm not sure why. I am almost positive I didn't touch any config, it just happened overnight. I'm on mac.

I dug into it a bit today and it seems that my init.lua is no longer able to load other lua files. I've tried placing them in the same directory as init.lua, and in a `lua` dir right next to init.lua.

Any advice for solving this would be great, thanks!

```
Error detected while processing /Users/<user>/.config/nvim-conf/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/<user>/.config/nvim-conf/nvim/init.lua:1: module 'plugins' not found:
	no field package.preload['plugins']
	no file './plugins.lua'
	no file '/opt/homebrew/share/luajit-2.1.0-beta3/plugins.lua'
	no file '/usr/local/share/lua/5.1/plugins.lua'
	no file '/usr/local/share/lua/5.1/plugins/init.lua'
	no file '/opt/homebrew/share/lua/5.1/plugins.lua'
	no file '/opt/homebrew/share/lua/5.1/plugins/init.lua'
	no file './plugins.so'
	no file '/usr/local/lib/lua/5.1/plugins.so'
	no file '/opt/homebrew/lib/lua/5.1/plugins.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
```

**Comment by Jendker** [comment]
What is the output of `brew info neovim`? Does your neovim work fine in terminal?

**Comment by justinmk** [comment]
Try `:checkhealth` in `nvim` (in a terminal).

This has nothing to do with vscode-neovim except that possibly your config is setting 'runtimepath'.

**Comment by regisverdin** [comment]
Running nvim in the terminal works perfectly, it finds my config and loads the required lua files (in ./lua). brew info neovim is healthy. nvim :checkhealth is all ok. What I don't understand is why my runtimepath is different for vscode versus running nvim in the terminal, given that I have set both vscode-neovim and nvim to use the same config.

**Comment by regisverdin** [comment]
Ah. I figured out part of it. I had "Neovim clean" setting selected, which excludes user dirs from the runtimepath.

**Comment by twschum** [comment]
For anyone else ending up here I had the same bug for a different reason, which was not specifying NVIM_APPNAME in the config
