### ISSUE TITLE
Jupyter Notebook (ipynb) filetypes are wrong.

### ISSUE THREAD

**Issue by kiyoon** [vscode-neovim/vscode-neovim#1189]
If I run `:echo &filetype`, in code cells it shows "conf" (should be python) and in markdown cells it doesn't even print anything.

I think this is why most of the bindings are incorrectly set. For example, none of the `nvim-treesitter-textobjects` bindings are not working.

**Comment by milanglacier** [comment]
I have the following code snippet to make it works as python filetype.

Jupyter notebook is internally json... So it is as expected that the cells are json filetype, because it is what it is.

```lua
vim.filetype.add {
    pattern = {
        ['.*%.ipynb.*'] = 'python',
        -- uses lua pattern matching
        -- rathen than naive matching
    },
}

```

**Comment by kiyoon** [comment]
@milanglacier Thank you. It works well and it's very useful! The only problem is that it will recognise markdown section as python as well, but probably it's not a big deal.
