### ISSUE TITLE
Turn off option for Additional Key Bindings 

### ISSUE THREAD

**Issue by pcwa-ahendricks** [vscode-neovim/vscode-neovim#1190]
_Feature Request_

It would be nice if there was a way to easily opt out via a setting(s) of the additional key bindings found in https://github.com/vscode-neovim/vscode-neovim#%EF%B8%8F-bindings. Some folks don't use the default Vim keybindings which conflict with these additions.

**Comment by martin-braun** [comment]
@theol0403 Do you know why `noremap` was picked over `map`? Could simply converting all bindings to `map` be sufficient enough as it would allow anybody to unbind those to `<nop>`?

**Comment by theol0403** [comment]
@martin-braun I'm not sure what you mean, you should already be able to unbind those manually. I think OP was asking if it could be disabled at the source.

**Comment by xiyaowong** [comment]
I guess your purpose is to disable the keybindings in vscode, not the mappings in vim.
