### ISSUE TITLE
Selecting inside tag, `vit` in TSX file selects the wrong parts

### ISSUE THREAD

**Issue by martisj** [vscode-neovim/vscode-neovim#1191]
I have tried `mini.surround`, `tpope's vim-surround`, `vim-matchup`, `targets.vim` to get the "right" `tag` text object. To no avail unfortunately.

VscodeVim does this correctly out of the box. However I can't stand the laggy experience of it. Sooo I would love to understand how to get this set up with vscode-neovim.

Given this code 
```tsx
<button
  onClick={() => {
    console.log('this is quite disheartening');
  }}
>
  <button>My button</button>
  <span>A longer text</span>
</butt|on>
```
where `|` is my cursor position. If I press `vit`
### I expect the selection to be on
```tsx
  <button>My button</button>
  <span>A longer text</span>
```

### However the actual result is this selection
```tsx
 {
    console.log('this is quite disheartening');
  }}
>
  <button>My button</button>
  <span>A longer text</span>
```

### Screenshots:

<img width="434" alt="image" src="https://user-images.githubusercontent.com/661994/228476651-cc598dc9-9acc-42ab-a4e8-ccd4d040cccc.png">

##### `vit`

<img width="423" alt="image" src="https://user-images.githubusercontent.com/661994/228476767-ee9d491d-8aa9-4829-a16c-51e2a07502b9.png">

##### `vat` works fine! 🙌

<img width="426" alt="image" src="https://user-images.githubusercontent.com/661994/228476910-cf6819c1-4a1a-4822-be0a-08d1d8233031.png">

**Screen recording showing the issue with vit and vscode commands.**
https://user-images.githubusercontent.com/661994/228477987-fdc8eb3c-b09d-45b5-af41-0111e19fb436.mov

I know that vscode has selection commands like: `editor.action.smartSelect.expand`, `editor.emmet.action.balanceIn` and `editor.emmet.action.balanceOut` which kind of do what I want to do here. But those commands don't work with `vscode-neovim` selections it seems?🤷‍♂️

My question is: "How can I map these commands to `vit` and `vat` in vscode-neovim? Or is there another way to get these text objects with vscode-neovim?"

PS: I am unsure if this is the right place to post this question/issue, if it is please point me in the right direction/repo and I will happily close this issue.

**Comment by justinmk** [comment]
Depends on the Nvim runtime files. has nothing to do with vscode-neovim

**Comment by lfire** [comment]
@martisj I found the config.
```vim
nnoremap <silent> vit <Cmd>call VSCodeNotify('editor.emmet.action.balanceIn')<CR>
nnoremap <silent> vat <Cmd>call VSCodeNotify('editor.emmet.action.balanceOut')<CR>
```
