### ISSUE TITLE
'u' after long document format yields an error "Overlapping ranges are not allowed!"

### ISSUE THREAD

**Issue by Jendker** [vscode-neovim/vscode-neovim#1192]
Tested with empty vimrc and is reproducable on long python files, such as https://raw.githubusercontent.com/hhatto/autopep8/main/test/inspect_example.py. If I format such python code with black by calling 'Format Document' (ctrl+shift+I in Linux) and then i try to undo with 'u', the changes are not undone and i get following error:

```
2023-03-30T09:39:29.228Z DocumentChangeManager: Error applying neovim edits, error: Overlapping ranges are not allowed!
```
The buffer gets desynced. Calling 'Undo' command from VSCode instead of 'u' works just fine though, no errors emitted. To mitigate this I have created this mapping:
```
vim.keymap.set('n', 'u', ":call VSCodeNotify('undo')<CR>")
vim.keymap.set('n', '<C-r>', ":call VSCodeNotify('redo')<CR>")
```
But now e.g. 'o' in normal mode has to be undone by pressing 'u' twice.

It would be great if the issue could be fixed. Thank you!

**Comment by theol0403** [comment]
Dup https://github.com/vscode-neovim/vscode-neovim/issues/1068
