### ISSUE TITLE
Using "global" search with Leap disconnects neovim and vs code cursors?

### ISSUE THREAD

**Issue by neighthan** [vscode-neovim/vscode-neovim#1194]
When I have leap set up to search globally

```lua
vim.keymap.set('n', 's', function ()
  local focusable_windows_on_tabpage = vim.tbl_filter(
    function (win) return vim.api.nvim_win_get_config(win).focusable end,
    vim.api.nvim_tabpage_list_wins(0)
  )
  require('leap').leap { target_windows = focusable_windows_on_tabpage }
end)
```

I get labels from both open panes in VS Code

![Screenshot 2023-04-05 114030](https://user-images.githubusercontent.com/12573501/230133138-cd2522f1-b967-419a-a0a4-1ca24d177301.png)

But if I type a label from the left pane (while my cursor is in the right one), I get some odd behavior. The line I intended to jump to is highlighted (see the `def parse_args` line on the left, the second function)

![Screenshot 2023-04-05 115041](https://user-images.githubusercontent.com/12573501/230135172-07c02458-4ada-4245-9cf5-44dc935852d9.png)

but the cursor remains on the right pane. While I'm in normal mode, all commands act as if my cursor is now in the left pane (e.g. I can move that highlighted line up or down, `dd` the line, etc). But if I enter insert mode, I'll be back where the red cursor is in the right pane.

Has anybody been able to get leap (or similar) to work for searching multiple windows? Or is an error here expected and this isn't supported?

(note for reproducibility: I can usually but not always get this behavior. The other outcome is that jumping to the other pane just fails. Also, if I jump back to the pane where the red cursor is, things are normal again)

**Comment by justinmk** [comment]
> for searching multiple windows?

Surprised that works at all, lol. Visual plugins are a best-effort thing for now.

**Comment by theol0403** [comment]
Yeah, vscode-neovim does not support any multi-window actions.
