### ISSUE TITLE
Use <C-c> to copy visually selected text to clipboard

### ISSUE THREAD

**Issue by still-dreaming-1** [vscode-neovim/vscode-neovim#1196]
I have tried _many_ different approaches to get this working, and I just can't seem to figure it out. Is this possible?

What I'm trying to do is, visually select some text, via the keyboard via Neovim's visual mode, and then press Ctrl+c to copy what is selected to the clipboard. I don't wan to have to use the mouse to select something just to be able to copy it. I also don't want yank to yank to the clipboard, I like to keep them separate.

I even went as far as to try to completely disable Ctrl+C within VSCode keyboard shortcuts, turning on the "Use Ctrl Keys For Normal Mode" setting (which includes visual mode), and no matter what, it just copies the entire bottom line portion of the visual selection.

So many things about this seem to not be working at all. My attempts to disable the Ctrl+C mapping in VSCode seem to have failed. No matter how I do or do not have Neovim configure, whether I am copying from the text area or somewher else, Ctrl+C always will copy what is selected with the mouse. Additionally, trying to create a custom mapping for Ctrl+C in my ini.lua seems to not be having any effect. I even tried mapping it to something strange like `p`, and that is not working or having any effect. I also tried more potentially logical things like mapping it to call `VSCodeNotifyVisual('editor.action.clipboardCopyAction', 0)`.

One scenario where this would be useful is, to jump to the top of the file with `gg`, switch to visual linewise mode with `V`, jump to the bottom of the file with `G`, and then copy the entire file content with Ctrl+C.

**Comment by nokia-git** [comment]
init.vim
vnoremap <C-C> "+y
nnoremap <C-C> V"+y

keybindings.json
1. disable all ctrl+c binding
2. add this binding
    {
        "key": "ctrl+c",
        "command": "vscode-neovim.send",
        "when": "editorTextFocus && neovim.mode == 'visual'",
        "args": "<C-c>"
    },

this works very well for me

**Comment by still-dreaming-1** [comment]
> vnoremap "+y
> nnoremap V"+y

I'm confused by these. Isn't a mapping supposed to include the mode, the left side (what is being mapped) and the right side (what it is being mapped to)?

**Comment by theol0403** [comment]
The problem is that you need to set up:
* send C-c to neovim (you did this)
* in neovim, bind C-c to VSCodeSendVisual("copy"), where "copy" is the vscode copy command
