### ISSUE TITLE
Remap Sneak back  keymap?

### ISSUE THREAD

**Issue by seriiserii825** [vscode-neovim/vscode-neovim#1197]
Hi. 
In init.vim i am using 
```
nnoremap b S

```

But is not working. 

I can't find a solutions in your issues, also in documentation. 
Also in vscode -> keyboard shortcuts 
search for sneak and nothing. 

Thanks in advance

**Comment by justinmk** [comment]
you need a recursive map if you want to do that.

unrelated to this repo , though
