### ISSUE TITLE
Allow refactoring actions from line selections

### ISSUE THREAD

**Issue by ldorigo** [vscode-neovim/vscode-neovim#1198]
Type: <b>Bug</b>

I can't trigger refactoring actions when I select multiple lines in edit mode (`Shift+v, motion`). If I select the same lines in insert mode (with the mouse), I'm then able to view and trigger available refactorings. This is annoying as it takes a lot of time :-)

Extension version: 0.0.97
VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:57:21.103Z)
OS version: Linux x64 6.2.9-zen1-1-zen
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.0-1035-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics (16 x 4291)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|30.77GB (14.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: sudcal_vm|
|OS|Linux x64 5.15.0-1035-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (2 x 2294)|
|Memory (System)|7.72GB (3.68GB free)|
|VM|0%|
</details>

**Comment by justinmk** [comment]
Works for me, I tried:

1. select text with `V`
2. ctrl-shift-p, run command `Refactor...`
3. choose `Extract to method`
4. the selected text was extracted to a method

Just a guess: try enabling the `vscode-neovim.mouseSelectionStartVisualMode` option?

**Comment by ldorigo** [comment]
Sorry, I wasn't clear/precise enough. 

Indeed triggering the refactors from the global action menu (ctrl-shift-p) works. It's triggering it from the "quick fixes" tooltip (which I get with `ctrl+.` , not sure if that's the default) that does not work (in fact, the tooltip does not show at all).  If I select with mouse (in insert mode), the tooltip appears with refactor suggestions.

**Comment by ldorigo** [comment]
There seem to be a few other selection-related behaviours that do not work as expected with visual-mode selections. For instance, the command `Debug: Evaluate in Debug Console` (need to assign it to a shortcut), does not work for selections selected with `v` + movements.

**Comment by Aneeqasif** [comment]
> Sorry, I wasn't clear/precise enough.
> 
> Indeed triggering the refactors from the global action menu (ctrl-shift-p) works. It's triggering it from the "quick fixes" tooltip (which I get with `ctrl+.` , not sure if that's the default) that does not work (in fact, the tooltip does not show at all). If I select with mouse (in insert mode), the tooltip appears with refactor suggestions.

did you find the solution for this issue?
