### ISSUE TITLE
Auto-indentation when opening new line

### ISSUE THREAD

**Issue by theorlangur** [vscode-neovim/vscode-neovim#1199]
The problem I'm having is best show in the following video:
[vscode-neovim-braces.webm](https://user-images.githubusercontent.com/19556862/232224011-a8c73c38-d0d3-4a26-b8ed-5ce579cfa257.webm)

vs

what happens in actual neovim:
[neovim-braces.webm](https://user-images.githubusercontent.com/19556862/232224031-2b3a6ba5-5852-4a5a-a0a4-5bb5e7e7dc82.webm)

So to put it in text: 
having the following code snippet:
```
if (test)
    <cursor>
```
when opening a new line right after `if (test)` it first puts the cursor somewhere under the `test`, indent which is ok.
But then in neovim, as soon as I start typing opening curly brace it automatically de-indent it (which puts newly added `{` right under `if`), which is what I expect and want.
```
if (test)
{<cursor>
```
In vscode however this is not the case for some reason, it stays indented.
```
if (test)
    {<cursor>}
```

I tried turning off vscode's automatic for indentation or auto-closing brackets but with no luck.
Is this intentional, can this be changed?

**Comment by unlsycn** [comment]
In the insert mode you are indeed typing in VSCode so this issue may be difficult to tackle.

**Comment by justinmk** [comment]
> In the insert mode you are indeed typing in VSCode so this issue may be difficult to tackle.

Yes, vscode is in control of insert-mode. This is an intentional constraint of vscode-neovim. You need to configure vscode to do what you want.
