### ISSUE TITLE
How to change the color of this part in visual section

### ISSUE THREAD

**Issue by vlrevolution** [vscode-neovim/vscode-neovim#1201]
Anybody know what is the styling needed in the configuration to affect this part of the visual select mode:
![2023-04-22 16_35_02-Window](https://user-images.githubusercontent.com/67480746/233788243-bff7908b-5de3-4e6b-845a-f37cfc593d93.png)
Many thanks!

**Comment by justinmk** [comment]
This is an issue tracker.

**Comment by Jendker** [comment]
@vlrevolution you can post your question here: https://github.com/vscode-neovim/vscode-neovim/discussions
