### ISSUE TITLE
Can't get easymotion to work

### ISSUE THREAD

**Issue by lakshits11** [vscode-neovim/vscode-neovim#1202]
I am using windows 10 and have installed my neovim config in a different directory than the usual Appdata/Local/nvim. I am using [dein.vim](https://github.com/Shougo/dein.vim) as plugin manager. I have installed the easymotion extension : https://github.com/asvetliakov/vim-easymotion . but i cannot get easy motion to work inside my vscode. whenever i press my leader 2 times, it just moves cursor one step forward. Below is my init.vim

```vim
"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=C:\Users\Lakshit\.config\nvim-data\dein\repos\github.com\Shougo\dein.vim

" Required:
call dein#begin('C:\Users\Lakshit\.config\nvim-data\dein')

" Let dein manage dein
" Required:
call dein#add('C:\Users\Lakshit\.config\nvim-data\dein\repos\github.com\Shougo\dein.vim')

" Add or remove your plugins here like this:
call dein#add('Shougo/neosnippet.vim')
"call dein#add('Shougo/neosnippet-snippets')
call dein#add('wsdjeg/dein-ui.vim')
call dein#add('asvetliakov/vim-easymotion')

call dein#end()

" Required:
filetype plugin indent on
syntax enable

" If you want to install not installed plugins on startup.
"if dein#check_install()
"  call dein#install()
"endif

"End dein Scripts-------------------------


" Set the clipboard option to "unnamedplus"
set clipboard=unnamedplus
let mapleader=" "
" map <Leader><Leader> <Plug>(easymotion-prefix)
nnoremap <Leader>r <C-r>
nnoremap ? <Cmd>call VSCodeNotify('workbench.action.findInFiles', { 'query': expand('<cword>')})<CR>
nnoremap ? <Cmd>call VSCodeNotify('workbench.action.findInFiles', { 'query': expand('<cword>')})<CR>


```

I have spent hours trying to debug but cannot seem to make it work in vscode. Help please.

**Comment by infinitewhileloop** [comment]
> Easymotion is no longer supported. Use hop or lightspeed. [Source](https://github.com/vscode-neovim/vscode-neovim/issues/910#issuecomment-1170609212)

I use this in my `.vimrc`, just adapt it to your plugin manager:

```
if has('nvim')
  Plug 'phaazon/hop.nvim', {'commit': 'caaccee'}
endif
```

**Comment by lakshits11** [comment]
Okay, thanks! Btw just asking for your personal opinion, which is better suited for beginners hop or lightspeed?

**Comment by infinitewhileloop** [comment]
I can't answer that question, as I have only tried hop. It works pretty good in VS Code, I had to use the specific commit mentioned in my previous reply though because of a bug. It sometimes struggles with folded code in VS Code, but in general it works alright.

**Comment by justinmk** [comment]
support for "visual" plugins like EM is best-effort. and covered in more general "display" issues.

**Comment by theol0403** [comment]
Since there seems to be some links on the internet pointing to this issue: support for easymotion (the vimscript version) is removed, but any nvim (lua based) motion plugins (hop, leap, lightspeed, flash, etc) will work.
