### ISSUE TITLE
VimTex plugin doesn't work properly.

### ISSUE THREAD

**Issue by gaoqiangks** [vscode-neovim/vscode-neovim#1205]
I installed VimTex plugin to write latex in neovim("https://github.com/lervag/vimtex").   One of the function this plugin realize is that: when the cursor is on a dollar sign and neovim is in normal mode, if I pressed %, the sign will jump between between paired dollars.  However, when I use it in vscode-neovim,  the cursor always jump to the previous dollar sign.

**Comment by justinmk** [comment]
sounds like the plugin isn't loaded.

**Comment by theol0403** [comment]
The issue is probably because of `syntax off`

**Comment by gaoqiangks** [comment]
> The issue is probably because of `syntax off`

It works!  Since all things work well with neovim in WSL,  I never thought I should set `syntax on` manually.   Thank you very much!

**Comment by theol0403** [comment]
Unfortunately `syntax off` is forced by the extension, because we don't want the syntax highlighting. I hope to investigate a better solution.
