### ISSUE TITLE
How to highlight words like TODO?

### ISSUE THREAD

**Issue by infinitewhileloop** [vscode-neovim/vscode-neovim#1207]
I use this snippet in my `.vimrc` to highlight these words:

```
augroup HiglightTODO
    autocmd!
    autocmd WinEnter,VimEnter * :silent! call matchadd('Error', 'TODO\|STARTED\|DONE\|FIXME\|FIXED', -1)
augroup END
```

At first, I assumed this didn't work in VS Code. By accident, I found out that it does work if you enable spell check `:set spell`. But because spell check is enabled, every word not in the dictionary gets an ugly squiggly underline. Strangely enough, this underline is only visible in Visual mode.

![image](https://user-images.githubusercontent.com/84473512/235297579-cc81cb39-4fe8-4cbd-9a22-41da23818e48.png)

How can I highlight words like TODO, without enabling spell check?

**Comment by Jendker** [comment]
That may be sufficient for you: https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments

**Comment by theol0403** [comment]
You would have needed to look up what highlight groups TODO uses and set them manually (I assume they were linked to nonexistent spell hl groups).
