### ISSUE TITLE
Warn on empty vscode-neovim.send args

### ISSUE THREAD

**Issue by otherjason** [vscode-neovim/vscode-neovim#1209]
In my vim configuration, I have `Ctrl+V` mapped to paste from the clipboard, so I use `Ctrl+Q` as an alternate keymapping to enter visual block mode. I attempted to configure my VSCode keybindings to remap `Ctrl+Q` from its normal (quit) function and send it to neovim instead by adding the following to my `keybindings.json`:

```json
    {
        "key": "ctrl+q",
        "command": "-workbench.action.quit"
    },
    {
        "key": "ctrl+q",
        "command": "vscode-neovim.send",
        "when": "editorTextFocus && neovim.mode == 'normal'"
    }
```

After doing so, I would get strange behavior in the editor after pressing `Ctrl+Q`, certainly not entering visual block mode. Using neovim's macro record feature, I was able to see that upon pressing `Ctrl+Q`, the key sequence that was actually getting passed to neovim was `undefined`. It makes sense that this would turn into a mess of successive commands and give strange behavior!

After enabling logging in neovim, I confirmed that the `key` argument to the `onSendCommand()` handler in `typing_manager.ts` is `undefined` instead of the key that was pressed. I therefore was able to work around the problem by explicitly specifying the key as the argument to the send command in my key bindings configuration:

```json
    {
        "key": "ctrl+q",
        "args": "<C-q>",
        "command": "vscode-neovim.send",
        "when": "editorTextFocus && neovim.mode == 'normal'"
    }
```

But it seems like this should work even without the `args` field.

**Comment by justinmk** [comment]
Nice debugging! I agree this should work without the explicit `args`, and we should probably give a clear error instead of passing undefined. Care to send a PR?

**Comment by otherjason** [comment]
I would be open to making a PR, but VSCode plugins and TypeScript in general is not my area of competence. I'm guessing it's a simple fix, but I wouldn't even know where to start.

**Comment by justinmk** [comment]
no worries, you did the hard part. fwiw, where to start is:

1. https://github.com/vscode-neovim/vscode-neovim/blob/5b5421201701be67fc92d42b39fb049708b4d0f1/src/typing_manager.ts#L174
2. https://github.com/vscode-neovim/vscode-neovim#-build

**Comment by theol0403** [comment]
If you didn't have args, you would need a different send command for every key. The only improvement is to warn.
