### ISSUE TITLE
Cursor moves improperly when VSCode writes text

### ISSUE THREAD

**Issue by artoonie** [vscode-neovim/vscode-neovim#1210]
This is a new issue, I believe when I upgraded to VSCode 1.77.3 on OSX (M1/ARM).

When VSCode writes text while I'm in insert mode, the cursor doesn't follow.

To reproduce:
1. Type some text
2. Hit Cmd+Space to autocomplete
3. Hit enter to accept changes
4. Continue typing, and notice the cursor doesn't move to the end of the autocompleted text

https://user-images.githubusercontent.com/537316/235738573-e6a9eebe-a7ed-4a01-ae59-b8d6ba7f5340.mov

**Comment by theol0403** [comment]
Please reply if you can repro with empty init.vim.
