### ISSUE TITLE
Unintuitive behaviour when using mouse to make a visual-mode selection

### ISSUE THREAD

**Issue by yogeshdhamija** [vscode-neovim/vscode-neovim#1212]
Context:
- This issue assumes that the `mouseSelectionStartVisualMode` setting enabled, meaning that I expect VSCode selections made via the mouse to also become visual-mode selections in the embedded Neovim.

Given:
- If I'm already in visual mode (that is, something is selected via Neovim),
- and then I use my mouse to select something elsewhere (this would be a VSCode selection),

Intuitive expectation:
- what I previously had selected becomes unselected,
- and what I selected with my mouse becomes selected. 
     (that is, both Neovim and VScode show a selection that begins where my mouse clicked, and ends where I released the mouse button)

Actual behaviour: 
- my previous cursor position becomes the beginning of a new selection,
- and where I dragged my mouse to becomes the end of the new selection.
    (that is, both Neovim shows a selection that begins where my cursor was previously, and ends where I released the mouse button)
    
Motivation:  
- I believe this is one of the things preventing me from creating a function in my `~/.vimrc` which allows me to use the "Expand/Shrink Selection" functionality of VSCode to make NeoVim selections. (I want that, in visual mode, each time I press `v`, it expands my selection, and each time I press `V`, it shrinks it.)

***

Naively, I think this can be fixed by playing with this if condition here:  
https://github.com/vscode-neovim/vscode-neovim/blob/f9bcd2555c01ad238d9eca06f1c051c43ee71b15/src/cursor_manager.ts#LL353C37-L353C37.  
My reading of that code is that, when a VSCode selection change occurs, *_only if it is not in visual mode_*, will the VSCode selection entirely replace the Neovim selection. However, my intuition says that the VSCode selection should always replace the Neovim selection.

**Comment by yogeshdhamija** [comment]
Playing around with the local version a bit, I've realized that fixing this would not resolve the "Expand/Shrink Selection" issue, so the "motivation" portion of the issue is not relevant. 

I've also learned that this is significant effort, as there is a good reason why that `if` condition which I mentioned earlier exists. This is because, while your mouse is dragging a selection, you don't want it to replace your selection, but rather extend it.

I think this should be able to be resolved by checking if the new selection is beginning from outside the current neovim selection. If it is, then start a new selection, otherwise extend your current one. 

However, I'm not experienced with the neovim API, and don't know how to get this information. I'll leave this issue open and might take another crack at it in the future, but not working on it currently.

**Comment by theol0403** [comment]
Fwiw, this can be solved by changing the code you mentioned. Essentially, whenever the vscode selection is updated, you have to re-send that full selection to nvim. Currently, nvim replies by deleting the vscode selection and showing the fake visual selection.

If you want me to explain in more detail I can. I hope to refactor this code at some point.
