### ISSUE TITLE
Wrong cursor position when entering insert mode with a large cursor jump after binding autocmd on `InsertEnter`

### ISSUE THREAD

**Issue by CalaW** [vscode-neovim/vscode-neovim#1213]
Hi, I am using `im-select` with this awesome project to change input method when leaving/entering insert mode. However, the cursor's position after entering insert mode is wrong when there's a "large jump" of cursor position.

Let | denotes cursor position, here's a example
```
(foobar"foobarfoobarfoobarfoobar|foobar"foobar)
↓ ci"
(foobar""foobar)|
```

However small jump works fine ~~(when the jump is less than 8 characters)~~
```
(foobar"foobarfo|obarfoobarfoobarfoobar"foobar)
↓ ci"
(foobar"|"foobar)
```

Here's a screen record:

![record](https://github.com/vscode-neovim/vscode-neovim/assets/41041381/4e51ce64-e29a-43e0-83aa-b3af99c0693a)

MWE is:
```lua
-- init.lua
vim.api.nvim_create_autocmd("InsertEnter", {
    callback = function ()
        vim.fn.system({"im-select"})
    end,
})
```

**Comment by CalaW** [comment]
Maybe time delay of the function call is the reason. I managed to reproduce this issue by calling `sleep` command to delay 0.1 second.

```lua
-- init.lua
vim.api.nvim_create_autocmd("InsertEnter", {
    callback = function ()
        vim.fn.system({"sleep", "0.1"})
    end,
})
```

**Comment by CalaW** [comment]
The problem is invoked when the cursor before the motion is on the right of the last character of current line after the motion. Or in another word, cursor before the motion is in a invalid position after the motion.

Works as intended:
```
(foobar"foobarfo|obarfoobarfoobarfoobar"foobar)
↓ ci"
(foobar""foobar)  # for position reference
(foobar"|"foobar)
```

Wrong behavior:
```
(foobar"foobarfoo|barfoobarfoobarfoobar"foobar)
↓ ci"
(foobar""foobar)|
```

**Comment by theol0403** [comment]
Not sure if the autocommand is the culprit. In that case, dup of https://github.com/vscode-neovim/vscode-neovim/issues/1080
