### ISSUE TITLE
keymap <C-j> may cause content loss

### ISSUE THREAD

**Issue by defpis** [vscode-neovim/vscode-neovim#1214]
My lua config for vscode-neovim:
```
local keymap = vim.api.nvim_set_keymap
local opts = { silent = true, noremap = true }

keymap('i', '<C-l>', '<Right>', opts)
keymap('i', '<C-h>', '<Left>', opts)
keymap('i', '<C-j>', '<Cmd>call VSCodeNotify("deleteWordLeft")<Cr>', opts) 
keymap('i', '<C-k>', '<Cmd>call VSCodeNotify("deleteWordRight")<Cr>', opts)
```
When I type in insert mode and ESC exits, the content is lost, only occurs at the first insertion after the up and down movement, the error is as follows:
![屏幕录制2023-05-12 13 11 15](https://github.com/vscode-neovim/vscode-neovim/assets/48018016/c22a2a89-ad88-491b-ab3d-e406e0815927)

**Comment by justinmk** [comment]
does setting `affinity` help? https://github.com/vscode-neovim/vscode-neovim/issues/1051

> and ESC

if it's after ESC I would guess it's related to vscode-neovim's attempt to track insert-mode "redo".

https://github.com/vscode-neovim/vscode-neovim/issues/1139
