### ISSUE TITLE
Enhancement suggestion: Improved testing of plugin compatibilities with a few common neovim setups

### ISSUE THREAD

**Issue by janderssonse** [vscode-neovim/vscode-neovim#1215]
Currently, we as devs and (neo)vim users have the luxury of using quite a few managed and updated neovim setups of good quality, with regulary tagged release. 

Examples and common are 

- LunarVim https://www.lunarvim.org/
- Lazy Vim https://www.lazyvim.org/

 and a few more. 

With this plugin for VSCode, the pain points of switching between neovim/VSCode give us the best of them both. Almost.
Currently, using any one of these with the default setups will lead to a few nuances due to incompatible plugins or feature.

Suggestion:
To further make life in neovim and VSCode easier to merge, before new release of the plugin, do a test run of  a few of the commonly used pre setups (like the above suggestions) in their latests tagged releases with this neovim plugin and VSCode, to show major incompatibilties and missing features. 

Result:
The outcome would be either more input of features and bugs to adjust in this plugin for the next version to improve neovim usage when having opted for one the common pre setups, or at least a doc section on issues with pre configured neovim setups and what to disable to avoid major incompatibilities.

If there would be interest in the above suggestions I'm sure the community (including me) would help out in finding a few of the major ones. So before doing anything, what are the thoughts about this?

**Comment by justinmk** [comment]
Resources are limited, this is not anywhere near the top priority of things this project should spend time on.
