### ISSUE TITLE
Visual mode selections are not independent between tabs

### ISSUE THREAD

**Issue by OldStarchy** [vscode-neovim/vscode-neovim#1217]
### Steps

1. Open two editors with content
2. Select some text in one editor with visual mode (or click-drag when `vscode-neovim.mouseSelectionStartVisualMode` is enabled)
3. Focus on the other editor/tab

### Expected

No existing selection

### Actual

The same range of text (offset) is selected in the other editor

### Workaround

Use vscode's native selections while in insert mode;

* This only works so long as you don't leave insert mode in any other tab, since the current mode is also shared between tabs

### Thoughts

I guess this is to do with reusing the same neovim buffer in the backend between different tabs, so it likely affects other things that I have yet to notice. It also means its probably not an easy fix, especially for the impact this "bug" has.

**Comment by theol0403** [comment]
Once that PR is merged, please ask to reopen if the issue still exists.
