### ISSUE TITLE
Visual mode only copies the last line

### ISSUE THREAD

**Issue by tieniu1** [vscode-neovim/vscode-neovim#1218]
I really enjoy using neovim plugins, but I've encountered some tricky issues. In vscode, when using visual line mode to select multiple lines and then using command+c, it only copies the last line. Similarly, when using visual line mode to select multiple lines and then using command+/, it only comments out the last line. These problems don't exist in the vim plugin, but only in the neovim plugin. Do you know of any way to solve this issue?

**Comment by Jendker** [comment]
You can only copy with cmd+c if you select with mouse in vscode. Otherwise if you use the visual selection with vim you need to copy also in vim - e.g with `y` or `"*y` if you don't have `set clipboard=unnamedplus`.

**Comment by cnut1648** [comment]
I have `Mouse Selection Start Visual Mode` enabled, and I do can enter visual mode, select multiple lines and do `d` to delete everything I selected. But I found that I cannot use `ctrl+/` to uncomment/comment every line I selected. I do not why it happens. My config is very simple as it only has `set clipboard=unnamedplus`

**Comment by Jendker** [comment]
Maybe [vim-commentary](https://github.com/tpope/vim-commentary) and commenting using `gc` with vim would help?
With lazy.vim you could install it as:
```
  {
    'tpope/vim-commentary',
    config = function ()
      -- Comment c, cpp, cs, java with //
      vim.api.nvim_command([[autocmd FileType c,cpp,cs,java setlocal commentstring=//\ %s]])
    end
  },
```
You can see there that I have added an autocommand to comment some filetypes with `//`.
You could even map it to `ctrl+/` if `ctrl+/` is natural to you. https://github.com/tpope/vim-commentary/issues/161

**Comment by cnut1648** [comment]
I do not use vim-commentary but I figured that this keybinding works for me
```
      {
        "key": "ctrl+/",
        "command": "vscode-neovim.send",
        "when": "editorTextFocus && neovim.init",
        "args": "<C-/>"
      },

```

**Comment by tieniu1** [comment]
> @Jendker thanks, but unfortunately I do not use vim-commentary. However I figured that this keybinding works for me!
> 
> ```
>       {
>         "key": "ctrl+/",
>         "command": "vscode-neovim.send",
>         "when": "editorTextFocus && neovim.init",
>         "args": "<C-/>"
>       },
> ```
I solved the problem。😄
```
" init.vim
if exists('g:vscode')
 vnoremap <D-/> <cmd>call VSCodeNotifyVisual('noop', 1)<CR><Esc><cmd>call VSCodeNotify('editor.action.commentLine')<CR>
else
    " Neovim 
endif
```
```json
 // keybindings.json
 { // Delete key binding
    "key": "cmd+/",
    "command": "-editor.action.commentLine",
    "when": "editorTextFocus && !editorReadonly"
  },
  {  // Give cmd+/ to neovim
    "key": "cmd+/",
    "command": "vscode-neovim.send",
    "when": "editorFocus && neovim.mode == 'visual'",
    "args": "<D-/>"
  },
 ```

**Comment by tieniu1** [comment]
> [commentary](https://github.com/tpope/vim-commentary)

Thank you, I converted neovim's Visual Mode to vscode's select and called vscode's commentary
