### ISSUE TITLE
Command completion not working

### ISSUE THREAD

**Issue by mizagog** [vscode-neovim/vscode-neovim#1221]
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

vscode-neovim v0.0.97

VSCode Version: 1.79.0-insider (Universal)

Steps to reproduce:

Add a command to .init file

Start typing the command name

Press enter when the command is highlighted

Nothing happens

Only when typing in the full command name it is called

command! -nargs=0 HelloWorld :echo 'hello'

<img width="638" alt="image" src="https://github.com/vscode-neovim/vscode-neovim/assets/131956540/266e2be0-df17-46c1-a305-1f6947af471a">

<img width="252" alt="image" src="https://github.com/vscode-neovim/vscode-neovim/assets/131956540/eae9a086-ad92-4ce6-a7c7-293d53f19951">

**Comment by justinmk** [comment]
works for me. you need to figure out why your init isn't getting called, or perhaps a plugin is interfering.

**Comment by mizagog** [comment]
@justinmk, i've narrowed it down:
I'm working with Lowercase keys.
If I'll type 'Hell' then enter, I'll get the auto-command,  but in NVIM the command mode is case sensitive, meaning if I'll user 'hell' I will see it as a completion option, but NVIM won't register.
1. Why is the plugin command mode CASE INSENSITIVE
2. it used to work, do you have any clue if something changed in the last few months regarding Command mode?
