### ISSUE TITLE
change status bar color based on nvim mode?

### ISSUE THREAD

**Issue by devindang** [vscode-neovim/vscode-neovim#1224]
Something... like this: https://github.com/VSCodeVim/Vim/pull/1529#issue-222600744
It looks a bit like vim-airline

**Comment by justinmk** [comment]
You can handle the `ModeChange` event in nvim and call into a custom vscode extension to change the vscode statusline.

**Comment by tieniu1** [comment]
I guess you are looking for it, note that it is not compatible with Peacock, please uninstall [Peacock](https://github.com/johnpapa/vscode-peacock/issues/527) first before using [Neovim Ui Modifier](https://marketplace.visualstudio.com/items?itemName=JulianIaquinandi.nvim-ui-modifier), please check the [issues](https://github.com/kensleDev/vscode-nvim-ui/issues/5) of Neovim Ui Modifier when using it.
![image](https://github.com/vscode-neovim/vscode-neovim/assets/49060203/97dff5fd-ae1b-4b80-a84a-f558b5945746)

**Comment by martin-braun** [comment]
@tieniu1 Not available on VSCodium..

**Comment by martin-braun** [comment]
The Neovim Ui Modifier works like charm, I use it to update `statusBar.background`. I think this can be closed, unless we strive for this behavior in `vscode-neovim`.
