### ISSUE TITLE
move nvim into OBsidian

### ISSUE THREAD

**Issue by lbgws2** [vscode-neovim/vscode-neovim#1226]
May I ask if there are any plans to move NVIM into OBSIDIAN?

**Comment by justinmk** [comment]
There is almost zero information here, please ask questions with more effort if you expect effort in the answer.

I assume you mean this: https://obsidian.md/

The answer is, sure, if obsidian has a plugin model that allows that, and someone develops it. No idea why you're asking this on a vscode project.
