### ISSUE TITLE
Extension stops working when trying open URL

### ISSUE THREAD

**Issue by 1netanel** [vscode-neovim/vscode-neovim#1227]
When I'm pressing  'gx' to open up a URL the extension stops working for a few seconds.

Extension output: 
```
Error detected while processing function <SNR>6_vscodeGoToDefinition:
line    5:
E433: No tags file
E426: tag not found: shell
```

**Comment by justinmk** [comment]
Works for me. You didn't provide any sample text. Did you try disabling your config, for troubleshooting at least?

**Comment by 1netanel** [comment]
I can't recreate this problem, thank you for you help anyway.
