### ISSUE TITLE
How can I config  'vscode triggerd' selection right?

### ISSUE THREAD

**Issue by kmrk** [vscode-neovim/vscode-neovim#1228]
In my case,In 'normal mode' I use vscode's expand/shrink (editor.action.smartSelect.expand, editor.action.smartSelect.shrink) feature to select some code block. Call  expand/shrink by using their original shortcuts.

And then I found the yy or x command did not work properly with these selections.

![image](https://github.com/vscode-neovim/vscode-neovim/assets/50069773/72925b85-2b2d-4c99-b9df-865203151876)

when press x , editor only cut the last char

![image](https://github.com/vscode-neovim/vscode-neovim/assets/50069773/89f9cdf8-cadc-4446-85df-6dfd9ae90586)

Is it possible config neovim working with these selections?

**Comment by justinmk** [comment]
Can't answer configuration questions here. You might check the existing "visual" issues: https://github.com/vscode-neovim/vscode-neovim/labels/visual
