### ISSUE TITLE
Bottom lines slowly disappear while working on documents

### ISSUE THREAD

**Issue by 80sVectorz** [vscode-neovim/vscode-neovim#1235]
I have had issues for quite a while now where, as I work on a document, it seems to chip away at code in the bottom.
I'm the kind of person who basically spams :w it may have to do with that, but I really don't know.
It could not have been any extension that I am aware of because, 
I have tried to be turned off anything that may change the contents of a file, but I keep finding code missing.

Could it have something to do with copy and pasting snippets and operations like that?

**Comment by justinmk** [comment]
You are saying that vscode-neovim is removing code from the file (not merely the display, but the file contents)? Haven't ever seen this, it's likely your config. Did you try after setting the "clean" option? https://github.com/vscode-neovim/vscode-neovim/blob/5b5421201701be67fc92d42b39fb049708b4d0f1/package.json#L91

**Comment by 80sVectorz** [comment]
> You are saying that vscode-neovim is removing code from the file (not merely the display, but the file contents)? Haven't ever seen this, it's likely your config. Did you try after setting the "clean" option?
> 
> https://github.com/vscode-neovim/vscode-neovim/blob/5b5421201701be67fc92d42b39fb049708b4d0f1/package.json#L91

I'll give this a try, if I come across any more issues I'll post more details. One thing I did forget to mention in my first post is that the lines often also were replaced by null characters. It may be a visual thing, you're probably right.

**Comment by 80sVectorz** [comment]
I'm still experiencing the issue:
![image](https://github.com/vscode-neovim/vscode-neovim/assets/66908776/bd52d1dd-4b77-4be3-b88b-d3773fa80933)

**Comment by 80sVectorz** [comment]
I decided to record another case this time with a completion being the cause I think:

https://github.com/vscode-neovim/vscode-neovim/assets/66908776/d76bbad2-c5c8-4383-9a60-c4fb0844c1ad
