### ISSUE TITLE
Support Lazy.nvim

### ISSUE THREAD

**Issue by martin-braun** [vscode-neovim/vscode-neovim#1238]
`<CMD>Lazy<CR>` mapping will freeze the window.

**Comment by justinmk** [comment]
need a minimal repro, not a plugin to debug.

if it's creating new tabs or buffers, that doesn't work well with vscode-neovim atm.

**Comment by martin-braun** [comment]
@justinmk Yes, it creates a new buffer in a floating window where it shows the installed plugins and its pretty important to access this, because the point of lazy is to lazy-load plugins and you have to configure it properly so it works.

Lazy's background functions work, but the buffer can't be opened. However, this would be helpful to see what plugins are already load. Is there any plan on supporting buffers in the future?

**Comment by theol0403** [comment]
Floating windows/interactive buffers are not supported

**Comment by theol0403** [comment]
Though I will say, they used to be, and then the latest refactor broke it. Investigating external buffers is on my list.
