### ISSUE TITLE
Bottom lines slowly disappear while working on documents

### ISSUE THREAD

**Issue by 80sVectorz** [vscode-neovim/vscode-neovim#1242]
I'm reposting this issue since the last one https://github.com/vscode-neovim/vscode-neovim/issues/1235 was closed (in my opinion) prematurely.
# Previous text:
I have had issues for quite a while now where, as I work on a document, it seems to chip away at code in the bottom.
I'm the kind of person who basically spams :w it may have to do with that, but I really don't know.
It could not have been any extension that I am aware of because,
I have tried to be turned off anything that may change the contents of a file, but I keep finding code missing.

# New info:
Could it have something to do with copy and pasting snippets and operations like that?
My findings show it's related to things like code completions and pasting code. I have a few gives and videos with more info.

![image](https://github.com/vscode-neovim/vscode-neovim/assets/66908776/bd52d1dd-4b77-4be3-b88b-d3773fa80933)

![Code_7fQkzKrfpm](https://github.com/vscode-neovim/vscode-neovim/assets/66908776/aeadc436-dfa2-4638-bca8-dd4de9dd080e)

https://github.com/vscode-neovim/vscode-neovim/assets/66908776/d76bbad2-c5c8-4383-9a60-c4fb0844c1ad

**Comment by theol0403** [comment]
Please reproduce with an empty init.vim file.

**Comment by 80sVectorz** [comment]
> Please reproduce with an empty init.vim file.

I have never changed my init.vim or init.lua

**Comment by theol0403** [comment]
Latest nvim version?

**Comment by 80sVectorz** [comment]
> Latest nvim version?

It's v0.9.0

**Comment by theol0403** [comment]
Let me know if you isolate it to vscode-neovim, and can reproduce with empty init.vim.

**Comment by 80sVectorz** [comment]
> Let me know if you isolate it to vscode-neovim, and can reproduce with empty init.vim.

I have decided to switch over to doom emacs. The .init's were always empty for me.
