### ISSUE TITLE
bug: Combine status line items

### ISSUE THREAD

**Issue by martin-braun** [vscode-neovim/vscode-neovim#1251]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

`q` recording is fully supported, but you can't see if you are recording or not.

### Describe the solution you'd like

It would be nice if you could see that you are recording a register in the output window of VSCode, as close as possible to the original behavior:

<img width="138" alt="Screenshot 2023-07-02 at 11 55 50" src="https://github.com/vscode-neovim/vscode-neovim/assets/24259245/666d0daf-f74c-427f-a82c-5daa170c152f">

### Describe alternatives you've considered

If you press `q` without seeing the prefix in the status bar, it means you were recording. I'm pressing `q` so I see the prefix in the status bar. I'm pressing `q` once more and now I know I'm recording to `@q`.

Everything seem to work, which is nice, but it still would be nice to see if I'm recording right now or not and to which register I'm recording.

**Comment by justinmk** [comment]
Could handle the RecordingEnter/RecordingLeave events, but hopefully this is already reflected in the `:help ui` UI events.

**Comment by theol0403** [comment]
This already exists for me... do you have a vim setting that possibly turns this off? 

![image](https://github.com/vscode-neovim/vscode-neovim/assets/16546293/9476b2a1-187c-408b-b3a2-e1d7f6e6fca2)

**Comment by martin-braun** [comment]
@theol0403 Ha! Got it. Sometimes it likes to find itself on the far right, sometimes it does not: 

<img width="2048" alt="Screenshot 2023-07-03 at 06 06 04" src="https://github.com/vscode-neovim/vscode-neovim/assets/24259245/3b299938-5783-40a2-a568-dfff6a41cf82">

Still an issue, I expect it to be at the position where "Type :qa and press <Enter> to exit Nvim".

Both status bar widgets share the name "VSCode Neovim (Extension)". Unselecting it in the context menu will only hide the left one: 

<img width="242" alt="Screenshot 2023-07-03 at 06 11 35" src="https://github.com/vscode-neovim/vscode-neovim/assets/24259245/b6c7cf32-5416-4d82-a535-06c6bbed89b2">

But right clicking the right one will allow me to hide it as well: 

<img width="284" alt="Screenshot 2023-07-03 at 06 12 37" src="https://github.com/vscode-neovim/vscode-neovim/assets/24259245/a17e6971-fcd2-47bd-861a-3b98112edb33">

Having both hidden now, it shows up twice, this can't be right: 

<img width="211" alt="Screenshot 2023-07-03 at 06 12 56" src="https://github.com/vscode-neovim/vscode-neovim/assets/24259245/16d2c9e9-466d-4cc3-9b82-542657c03038">

**Comment by theol0403** [comment]
Not sure what's going on...
- I only have the one panel item (visible, and in the menu)
- I've never seen it on the right
- I've never seen "type :qa and press enter"

**Comment by martin-braun** [comment]
"type :qa and press enter" appears for me when I press `<C-c>` in normal mode. I don't know how the status bar works, but could it be that you don't expect it and thus aren't cleaning the previous text so that VSCode adds a new element in the status bar?

I think my configuration causes this text to appear, but I haven't re-mapped `<C-c>` on `vim.g.vscode`, hmm.

**Comment by justinmk** [comment]
vscode extension statusbar placement depends on the "priority" of statusbar items provided by whatever extensions you have installed.

If vscode-neovim gives itself a high priority, AFAIR it should be on the right. Lower-priority gets placed to the left.

**Comment by martin-braun** [comment]
@justinmk I shouldn't have two of the same, though. And it should not swap with another extension. It looks like it uses the wrong index when recording, overriding my Codeium spot.

**Comment by theol0403** [comment]
It looks like there can be up to three status items https://github.com/vscode-neovim/vscode-neovim/blob/master/src/status_line.ts

However, I think the overwriting/moving is a vscode bug.

**Comment by justinmk** [comment]
It could be randomization because of the 3 different priorities: https://github.com/vscode-neovim/vscode-neovim/blob/c7eabe506d455a3712b9ab7620160c3a70db5931/src/status_line.ts#L9-L11

Why not have 1 status item that shows all 3? I would expect that to improve behavior in general, because it prevents the 3 items from being separated by status items from other extensions.

**Comment by martin-braun** [comment]
@justinmk Thanks for tracking it down, this is definitely the issue and I think it would make sense to combine all into one item. I think VSCode gets confused, because of the name collision with itself or because it expects an extension to have only one status bar item.

In regards of the separator, is `|` really a good pick? How likely there is a `|` in the command or message item? Could an unicode character, such as `⸱` be a better choice?

**Comment by justinmk** [comment]
> is `|` really a good pick?

It's a 2-way door, can pick anything and improve it later. Whoever implements this gets to pick :)
