### ISSUE TITLE
How to copy/paste text from VSCode selection ? 

### ISSUE THREAD

**Issue by Linuxiness** [vscode-neovim/vscode-neovim#1269]
How to copy/paste text from VSCode selection ? 
Like, when with mouse in VSCode I select text, neovim doesn't detect that text, so yanking or pasting doesn't work. 
Only when I right click and copy/paste , VSCode can copy/paste. 

But, can this be made, to copy/paste on ctrl+c / ctrl+v  when there is mouse selection on text, neovim to register it as copy/paste ?

**Comment by justinmk** [comment]
search existing issues before posting https://github.com/vscode-neovim/vscode-neovim/issues/1196
