### ISSUE TITLE
bug: Ctrl+n and Ctrl+p no longer cycle through history in command line mode

### ISSUE THREAD

**Issue by archilkarchava** [vscode-neovim/vscode-neovim#1298]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.1

### Operating system/version

MacOS 13.4

### Describe the bug

The `ctrl+n` and `ctrl+p` no longer cycle through history in command line mode and when using search.
The issue appeared after this PR https://github.com/vscode-neovim/vscode-neovim/pull/1255 was merged 

### Steps To Reproduce

1. Press `shift+;` to switch to command line mode
2. Press `ctrl+n` or `ctrl+p`
3. Nothing happens

### Expected Behavior

The extension should cycle through previously entered commands.

**Comment by theol0403** [comment]
Thanks for the issue!
