### ISSUE TITLE
"Using '*' activation is usually a bad idea as it impacts performance."

### ISSUE THREAD

**Issue by wenfangdu** [vscode-neovim/vscode-neovim#1309]
https://github.com/vscode-neovim/vscode-neovim/blob/9479c650a3ff79382c6b86e84b16bc317fd3894f/package.json#L34
![image](https://github.com/vscode-neovim/vscode-neovim/assets/28700378/6c177375-4119-432a-a6b5-4b46e333ea9f)
Could it be improved?

**Comment by justinmk** [comment]
As long as startup is super fast this doesn't matter.
