### ISSUE TITLE
bug: unable to connect to Neovim with `init.lua` file

### ISSUE THREAD

**Issue by patternina** [vscode-neovim/vscode-neovim#1311]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.0 

### Operating system/version

MacOS 13.4

### Describe the bug

I am unable to make VSCode pick up the executable file for my Neovim. After several tries, I manage to make it accept a path but now it throws another error:

> 2023-07-11T15:16:42.202Z MainController: Neovim spawn error: spawn /Users/myUser/.config/nvim/init.lua EACCES. Check if the path is correct.

I have the following in my `init.lua` file:
```lua
require('base')
require('highlights')
require('maps')
require('plugins')

if (not vim.g.vscode) then
  require('macos')
end

-- require('vscode')
vim.cmd('source $HOME/.config/nvim/lua/vscode.lua')
```

### Steps To Reproduce

N/A

### Expected Behavior

VSCode's Neovim extension gets connected to my Neovim.

**Comment by theol0403** [comment]
What are your vscode settings? Note that nvim will pick up your init.lua properly without manually setting the config file path.

**Comment by patternina** [comment]
I've set the following in the VSCode's `settings.json` file:

```jsonc
//...
"vscode-neovim.neovimExecutablePaths.darwin": "/Users/<myUsername>/.config/nvim/init.lua",
//...
```

I tried using `$HOME` but, for some reason, it doesn't work (NOENT error). Either path makes Neovim work from the terminal, though.

**Comment by theol0403** [comment]
@patternina you are setting the neovim executable path, not the config path. And you don't actually need to set the latter.
