### ISSUE TITLE
deps: replace msgpack-lite with msgpackr

### ISSUE THREAD

**Issue by justinmk** [vscode-neovim/vscode-neovim#1316]
# Problem

- msgpack-lite is not active since 2016. 
    - It also may be slow: https://github.com/neovim/node-client/issues/78
- msgpackr claims to be fast: https://www.npmjs.com/package/msgpackr

# Solution

If replacing msgpack-lite with msgpackr is low effort, could be worth doing.

**Comment by theol0403** [comment]
I think it's only a dev dependency? We just directly call into node-client for communication. Not sure why it's a dev dep tho.

**Comment by justinmk** [comment]
Oops I missed that. Ok, this is low priority then. Though maybe we could eliminate that dep as you said.
