### ISSUE TITLE
bug:  use space as <leader> is not work in vscode

### ISSUE THREAD

**Issue by Deuscx** [vscode-neovim/vscode-neovim#1317]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.1

### Operating system/version

windows11

### Describe the bug

when set space as a leader. it works in Neovim, but failed in Vscode

### Steps To Reproduce

lua config
```lua
local global = vim.g
global.mapleader = " "
global.maplocalleader = " "
```

### Expected Behavior

leader change should be work

**Comment by justinmk** [comment]
https://github.com/vscode-neovim/vscode-neovim/issues/1137
