### ISSUE TITLE
bug: `neovim.mode == normal` check in vscode when clause is not triggering

### ISSUE THREAD

**Issue by chaoz-dev** [vscode-neovim/vscode-neovim#1318]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

NVIM v0.9.1

### Operating system/version

Ubuntu 22.04 LTS

### Describe the bug

I currently have the following config in my `keybindings.json`
```
    {
        // Switch to next editor in group.
        "key": "tab",
        "command": "workbench.action.nextEditorInGroup",
        "when": "neovim.mode == normal && editorFocus"
    },
    {
        // Switch to previous editor in group.
        "key": "shift+tab",
        "command": "workbench.action.previousEditorInGroup",
        "when": "neovim.mode == normal && editorFocus"
    },
```
As the comments suggest, these keybindings allow me to switch to the next/previous editor in the editor group using `tab` and `shift+tab`. 

These bindings _used_ to work previously (as given); however, on the most recent build of vscode, this binding no longer works. Through testing, it appears that it is the `neovim.mode == normal` check that fails the when clause; the `editorFocus` clause still works. 

The expected behavior is that the I am able to tab/shift+tab to the next/previous editor in the editor group when:
1. The editor has focus
2. The vim mode is `normal`

I have disabled all other extensions except the VSCode Neovim extension to test this issue.

VSCode version:
```
Version: 1.80.1
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:22:25.257Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.19.0-46-generic
```

### Steps To Reproduce

1. Include the following config in `keybindings.json`
```
    {
        // Switch to next editor in group.
        "key": "tab",
        "command": "workbench.action.nextEditorInGroup",
        "when": "neovim.mode == normal && editorFocus"
    },
    {
        // Switch to previous editor in group.
        "key": "shift+tab",
        "command": "workbench.action.previousEditorInGroup",
        "when": "neovim.mode == normal && editorFocus"
    },
```
2. In `normal` mode, hit `tab` or `shift+tab` to move to the next or previous editor in the editor group. 

### Expected Behavior

We should be able to focus on the next or previous editor in the editor group when hitting `tab` or `shift+tab`, respectively.

**Comment by theol0403** [comment]
Probably related to https://github.com/vscode-neovim/vscode-neovim/pull/1255. 

Can you check to see if the issue still happens if you first enter and exit insert mode?

**Comment by bika-c** [comment]
Confirming that reentering normal mode from insert mode fixes the issue.

**Comment by xiyaowong** [comment]
Reproduced
