### ISSUE TITLE
bug: <Shift+Enter> doesn't work well in Find widget

### ISSUE THREAD

**Issue by hustrjh** [vscode-neovim/vscode-neovim#1330]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Win10

### Describe the bug

In **`Find widget`** <shift+enter> will jump to previous match, but with neovim plugin enabled I need to press twice <shift+enter> to jump. It's the same for <shift+F3>.
![image](https://github.com/vscode-neovim/vscode-neovim/assets/69783980/1e809b84-aa9f-4f71-868e-c3d50c96b30b)

Also in **`Replace widget`** \<enter\> doesn't work when it's normal mode.
![image](https://github.com/vscode-neovim/vscode-neovim/assets/69783980/31b82cea-72d1-45f1-b433-57f940858c21)

I bind my own key to trigger find widget like this.
```
vim.keymap.set('v', "<leader>fa", function()
	vim.fn['VSCodeCallVisual']("actions.find", 0) 
	vim.fn['VSCodeCall']("vscode-neovim.escape")
end)
```

### Steps To Reproduce

1. Open a .c file with **`no error`**.
2. Trigger find widget in normal mode.
3. Press <shift+enter> to jump to previous match. And you'll find that you need to press twice.

### Expected Behavior

I wish that I can use vscode find widget like before. Thus I can press <shift+enter> to jump to previous match and press \<enter\> to replace once in replace widget. Thanks.

**Comment by hustrjh** [comment]
<Shift+Enter> is OK in 0.4. Thanks. 😊

However Visual mode is going wrong.
Here's normal mode.
![image](https://github.com/vscode-neovim/vscode-neovim/assets/69783980/f0dbe5ae-51c0-4872-b49f-24281dafa8e3)
Then here's is visual mode.
![image](https://github.com/vscode-neovim/vscode-neovim/assets/69783980/e64315fc-2cf0-4642-ae54-59f25fcb0d41)

I need to swich to another tab to refresh the page correctly.

**Comment by theol0403** [comment]
Can you provide more information? i'm not sure what's the problem.

**Comment by hustrjh** [comment]
It's weird that the background of the code changes when I enter Line Visual mode. Also there're strange words in the end of the line. All strange words disappear after I switch to another tab and back.
In order to reproduce this bug you should put your cursor out of the code and then enter visual mode. This bug hasn't appeared untill latest update of the plugin. I hope this could help you locate the problem.

**Comment by theol0403** [comment]
I still don't know how to recreate the problem, do you have an empty init.vim? Are you setting syntax on by any chance?

**Comment by hustrjh** [comment]
I've found out the cause of the problem. There's nothing to do with int.vim and other vscode plugins. I use empty init.lua and disable most plugins in vscode.
I use Tabs to indent instead of Spaces. It's all right using Spaces but not for Tabs.
![image](https://github.com/vscode-neovim/vscode-neovim/assets/69783980/f6abfd79-76ac-4985-acf6-6317e3250b52)

**Comment by theol0403** [comment]
https://github.com/vscode-neovim/vscode-neovim/issues/1352

**Comment by hustrjh** [comment]
Fine, thanks. 😊
