### ISSUE TITLE
Issue: The behavior of the cursor when selecting content with mouse

### ISSUE THREAD

**Issue by Nashmatphysics** [vscode-neovim/vscode-neovim#1343]
Thank you for providing such a wonderful plugin, I use it everyday. But there is a thing I want to figure out. 

In vim, you can select content with mouse like this: 
https://github.com/vscode-neovim/vscode-neovim/assets/25275896/c34b8fc5-e628-49d6-ad8b-467a4c3cd887
(As you can see, the cursor will change from visual mode to insert mode)

And in visual studio (with plugin: vsvim), where the cursor flashes, it is selected:
https://github.com/vscode-neovim/vscode-neovim/assets/25275896/d5e5182c-c1b9-4922-908f-6e8d39dc7183

but in vscode, it just won't. The location where the cursor flashes will not be selected: 
https://github.com/vscode-neovim/vscode-neovim/assets/25275896/da4e2f6c-7850-4a03-acaa-f5c003f071d9

So, how to make the cursor's behavior be the same as vim (or vsvim in visual studio) in vscode? 

I mean, how to make the cursor from visual mode to insert mod, or make the location where the cursor flashes be selected when you selecting content with mouse?

**Comment by theol0403** [comment]
Please research the issue tracker.
