### ISSUE TITLE
After i installed VSCode Neovim , i find my vscode suggestion cannot show automatically. and i found some error in output , how to resolve this?

### ISSUE THREAD

**Issue by Pomelo1213** [vscode-neovim/vscode-neovim#1344]
![image](https://github.com/vscode-neovim/vscode-neovim/assets/29170164/87da46cb-e0bf-489e-8a89-c0d10c50f3d1)

**Comment by theol0403** [comment]
Please use the issue template, and upgrade your neovim version.

**Comment by Pomelo1213** [comment]
> Please use the issue template, and upgrade your neovim version.

ok, i will try ,thank you
