### ISSUE TITLE
bug: update broke line commenting

### ISSUE THREAD

**Issue by vlrevolution** [vscode-neovim/vscode-neovim#1345]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.4

### Operating system/version

WSL2

### Describe the bug

xmap gc  <Plug>VSCodeCommentary
nmap gc  <Plug>VSCodeCommentary
omap gc  <Plug>VSCodeCommentary
nmap gcc <Plug>VSCodeCommentaryLine

these binds are no longer working, please check

### Steps To Reproduce

put in init.vim and try 

### Expected Behavior

should comment line

**Comment by hustrjh** [comment]
Have you checked the breaking change in this version?
![image](https://github.com/vscode-neovim/vscode-neovim/assets/69783980/f25b2940-94f2-4522-a4a4-774dc4f0bce1)

**Comment by theol0403** [comment]
It is indeed removed.

If you want to replace `VSCodeCommentary`, call `VSCodeCall('editor.action.commentLine')` instead like https://github.com/vscode-neovim/vscode-neovim/blob/214acebf9dc3e748d875b21bf70f3025e86933be/vim/vscode-code-actions.vim#L5.

**Comment by crash5** [comment]
> Have you checked the breaking change in this version? ![image](https://user-images.githubusercontent.com/69783980/256398688-f25b2940-94f2-4522-a4a4-774dc4f0bce1.png)

Sorry, but it does not say anything about breaking the VSCodeCommentary command. Only states that it removes the Visual and Range suffixes. (maybe if you know the internals of the vscode-neovim plugin internals it is clear for you, but for me it was not...)

**Comment by theol0403** [comment]
My bad, forgot to document it.

**Comment by crash5** [comment]
> https://github.com/vscode-neovim/vscode-neovim/blob/214acebf9dc3e748d875b21bf70f3025e86933be/vim/vscode-code-actions.vim#L5

Is it possible to make it work with motions? (Can you put  this snippet into the readme? I think there will be peoples looking for it soon :) )

**Comment by theol0403** [comment]
Humm, no it isn't possible. The reason I removed it is because visual selections are now automatically sent. However, I did not think of operator-pending modes, I didn't know it supported it before.

Would it be a problem if you just used any of the vim/neovim comment plugins?

**Comment by crash5** [comment]
Unfortunately the vim commentary plugins are pretty dumb compared to the vscode comment support but I can live with the select then comment workaround. Thx.

**Comment by shuntaroy** [comment]
I often toggle a comment block using `gcip`, which is more intuitive and efficient than `vipgc` to me (of course, this is just my muscle memory, though).
As @crash5 noted, vim plugins for commenting (e.g. I use [caw.vim](https://github.com/tyru/caw.vim)) don't work correctly via vscode-neovim (e.g. cannot "toggle" comments, but keep nesting comments).
I hope the VSCodeCommentary-like behaviour comes back too.

**Comment by zwyyy456** [comment]
the code as follow in `keymaps.lua` doesn't work now:
```lua
local keymap = vim.keymap
-- local opts = { noremap = true, silent = true }
keymap.set("v", "gc", "<Plug>VSCodeCommentary")
keymap.set("n", "gc", "<Plug>VSCodeCommentary")
keymap.set("o", "gc", "<Plug>VSCodeCommentary")
keymap.set("n", "gcc", "<Plug>VSCodeCommentaryLine")
```
Can someone tell me how to modify the Lua code to adapt to this update, so that I can use `gcc` to comment out a line in normal mode and use something like `6gc` to comment out multiple lines?"

**Comment by tbenthompson** [comment]
I've also been surprised that my commenting keymaps stopped working. 

```
    xmap gc  <Plug>VSCodeCommentary
    nmap gc  <Plug>VSCodeCommentary
    omap gc  <Plug>VSCodeCommentary
    nmap gcc <Plug>VSCodeCommentaryLine
```

I guess I can replace VSCodeCommentaryLine with `call VSCodeCall('editor.action.commentLine')`. But, what about the VSCodeCommentary parts? Or do I have that backwards?

**Comment by theol0403** [comment]
`VSCodeCommentary` also called `'editor.action.commentLine'`

**Comment by tbenthompson** [comment]
Ok, it sounds like I had it backwards:

The correct answer is that:
- `VSCodeCommentary` == `'editor.action.commentLine'`
- but what about `VSCodeCommentaryLine`?

**Comment by theol0403** [comment]
Exact same thing

**Comment by justinmk** [comment]
`gcc`, `gc{motion}`, `gcip`, `{visual}gc`, etc., all work with https://github.com/tpope/vim-commentary installed. Which is a main idea of vscode-neovim : normal-mode vim features and plugins "just work".

**Comment by theol0403** [comment]
I think delegating "language integration" to vscode is a core goal of vscode-neovim, but wanting to apply a command to a motion (and populating dot-repeat) is a valid and common-enough usecase to have special code.

**Comment by justinmk** [comment]
> but wanting to apply a command to a motion (and populating dot-repeat) is a valid and common-enough usecase

Sure, no objection there. But that's different than providing things like `VSCodeCommentary`.

**Comment by theol0403** [comment]
It is needed to achieve that, however.

**Comment by justinmk** [comment]
Motion operations and dot-repeat work fine with https://github.com/tpope/vim-commentary . 

"wanting to apply a command to a motion (and populating dot-repeat)" is a general idea, why are special cases like `VSCodeCommentary` required for that? The `s:vscodeCommentary()` script and related mappings look like something that could be generalized and documented, no?
