### ISSUE TITLE
bug: There is no VSCodeNotifyVisual method after the updated version, WHY?

### ISSUE THREAD

**Issue by tieniu1** [vscode-neovim/vscode-neovim#1346]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

 v0.8.0

### Operating system/version

Mac OS 12.6

### Describe the bug

There is no VSCodeNotifyVisual method after the updated version, WHY?
<img width="1624" alt="image" src="https://github.com/vscode-neovim/vscode-neovim/assets/49060203/2e59799e-b6b4-4276-88eb-8c08579b1be4">

### Steps To Reproduce

Visual Mode Call VSCodeNotifyVisual

### Expected Behavior

no error

**Comment by theol0403** [comment]
Please read the release notes.
