### ISSUE TITLE
bug: Big performance downgrade with flash.nvim since 0.4.0

### ISSUE THREAD

**Issue by tgrelka** [vscode-neovim/vscode-neovim#1349]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [ ] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)
    This is an interaction of a specific plugin, flash.nvim with neovim-vscode, of course everything works fine with an empty init.lua

### Neovim version (nvim -v)

0.9.1 

### Operating system/version

MacOS 13.4.1

### Describe the bug

When using the flash.nvim and triggering a motion (like `f`, for example), there is a massive lag spike, during which my CPU load rises by a great margin. After a few seconds, vscode slowly starts updating the highlighting, first making everything grey before then highlighting relevant letters in a second pass, which also takes a few seconds.

### Steps To Reproduce

1. Install [flash.nvim](https://github.com/folke/flash.nvim) plugin
2. Press any flash motion or use something like remote flash (which btw now works correctly in this version, albeit very slowly due to the performance degradation)
3. Leave to make a coffee and return\* when vscode has finished rendering the highlighted letters

### Expected Behavior

Highlighting for flash motions is rendered within a reasonable timeframe. This worked up until version 0.4.0, and immediately broke after upgrading.

\* this is not meant to be toxic, just as a little joke. My current workaround is using `leap.nvim` until flash is working correctly again, not great, but also not terrible. I‘ve been wanting to contribute to this extension for some time, though it is a little daunting to dive into the code. If I can be of any additional assistance, please let me know.

**Comment by xiyaowong** [comment]
I'm using [hop.nvim](https://github.com/phaazon/hop.nvim), and it has also become very laggy.

**Comment by alcibiadesc** [comment]
+1 with flash.nvim same downgrade of performance

**Comment by theol0403** [comment]
Thanks for reporting. This is probably caused by https://github.com/vscode-neovim/vscode-neovim/pull/1334.

I'll take a look when I get the chance. For now, you can downgrade the extension inside vscode.

**Comment by windwp** [comment]
@theol0403  
https://github.com/vscode-neovim/vscode-neovim/blob/master/src/highlight_provider.ts#L361-L382
I don't understand why you highlight space with \u200D.
on a previous version it skip space character.

**Comment by theol0403** [comment]
@windwp it's possible I made a mistake in the implementation, but the reason was 
- highlighting the empty visual cursor at the end of the line
- highlighting leap.nvim targets that contain space characters

When you send " " to a vscode decoration it doesn't render the background color, which is why I used the invisible space hack.

**Comment by windwp** [comment]
It still create an html node.

https://github.com/vscode-neovim/vscode-neovim/blob/2d5abea1f2b5f2d3337d6e263e1f5a0e3a0487ac/src/highlight_provider.ts#L296


may be If a text on neovim is space and text on vscode is tab then it will create a lot of that invisible node.

**Comment by qizidog** [comment]
ping

**Comment by theol0403** [comment]
Apologies for the bug & delay. Will continue to be busy for a couple weeks. Will fix it by end of month.
