### ISSUE TITLE
Split only seems to work with absolute paths

### ISSUE THREAD

**Issue by maruno** [vscode-neovim/vscode-neovim#135]
Trying out the vsplit I noticed that it doesn't work like normal (neo)vim and relative paths are not supported. I noticed by default the path of the open folder in vscode is not set as the CWD, but I changed this with cd and relative paths still don't work.

**Comment by asvetliakov** [comment]
The path support in commands is very basic now. Mainly is to support `$e MYVIMRC`.

We can set CWD but that to do with vscode multi-root workspaces ? Also paths won't work for vscode remote/WSL
