### ISSUE TITLE
0.4.0:  keep the `VSCodeNotifyRange` function

### ISSUE THREAD

**Issue by xiyaowong** [vscode-neovim/vscode-neovim#1351]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

Some code actions, quickfixes, and refactoring operations enter the snippet mode after execution. These operations can be performed normally from the normal mode of nvim, but they do not enter the snippet mode. Please see the GIFs below.

Can't enter snippet mode
![demo](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/cfa07af1-568c-4834-aceb-bd23f91fcece)

My previous approach was to first save the selected range, then switch to insert mode, and then use that range to call `VSCodeNotifyRange`
```lua

local invoke = function(cmd)
  local mode = api.nvim_get_mode().mode
  local target
  if mode == 'V' then
    local startLine = fn.line('v')
    local endLine = fn.line('.')
    target = function() fn.VSCodeNotifyRange(cmd, startLine, endLine, true) end
  elseif mode == 'v' then
    local startPos, endPos = getpos()
    target = function()
      fn.VSCodeNotifyRangePos(cmd, startPos[2], endPos[2], startPos[3], endPos[3], true)
    end
  else
    target = function() fn.VSCodeNotify(cmd) end
  end
  xy.feedkeys('<esc><esc>')
  vim.defer_fn(function()
    vim.cmd.startinsert()
    target()
  end, 20)
end
```
</details>

![demo](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/531a064e-21fd-43e5-a943-064325e1863a)

 

### Describe the solution you'd like

Provide `VSCodeNotifyRange` function. Alternatively, this use case could be supported from within the extension itself.

### Describe alternatives you've considered

-

**Comment by theol0403** [comment]
From how I understand your snippet, can't you just replace `VSCodeNotifyRange` with `VSCodeNotify`? 

Now, `VSCodeNotify` will automatically send the visual selection to vscode if you are in visual mode, and then you can do the same thing after where you escape and enter insert mode.

**Comment by theol0403** [comment]
Oh I see the problem, I missed where you send the command after you enter insert mode. Maybe this is a useful enough reason to add.

**Comment by doppio** [comment]
@xiyaowong Could you clarify what is responsible for executing your snippet? I'm trying to achieve the same behavior, but I'm still quite new to both Neovim and this extension and I'm a bit lost on how your function gets called.

**Comment by xiyaowong** [comment]
@doppio 
```lua
local api, fn = vim.api, vim.fn

local invoke = function(cmd)
  local mode = api.nvim_get_mode().mode
  local target
  if mode == 'V' then
    local startLine = fn.line('v')
    local endLine = fn.line('.')
    target = function() fn.VSCodeNotifyRange(cmd, startLine, endLine, true) end
  -- TODO: handle <c-v>
  elseif mode == 'v' then
    local startPos, endPos = fn.getpos('v'), fn.getpos('.')
    target = function()
      fn.VSCodeNotifyRangePos(cmd, startPos[2], endPos[2], startPos[3], endPos[3], true)
    end
  else
    target = function() fn.VSCodeNotify(cmd) end
  end
  api.nvim_feedkeys(api.nvim_replace_termcodes('<esc><esc>', true, true, true), 'n', true)
  vim.defer_fn(function()
    vim.cmd.startinsert()
    target()
  end, 20)
end

-- code actions
vim.keymap.set({ 'x', 'n' }, '<leader>a', function() invoke('editor.action.sourceAction') end)
-- quickFix
vim.keymap.set({ 'x', 'n' }, '<leader>q', function() invoke('editor.action.quickFix') end)
-- refactor
vim.keymap.set({ 'x', 'n' }, '<leader>r', function() invoke('editor.action.refactor') end)
```

My suggestion is to wait for the release of vscode-neovim 1.0.0, which has a simpler new API.
