### ISSUE TITLE
bug: EasyMotion: Vim(call):E117: Unknown function: VSCodeSetTextDecorations : function EasyMotion#JK[9]..<SNR>72_EasyMotion[226]..<SNR>72_PromptUser, line 120

### ISSUE THREAD

**Issue by zhaoxuyll** [vscode-neovim/vscode-neovim#1353]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

v0.9.1

### Operating system/version

Windows 11

### Describe the bug

Today When use <Plug>(easymotion-j) in VSCode get error. Before not this error.

Neovim vim-plug:
```
Plug 'asvetliakov/vim-easymotion', Cond(exists('g:vscode'), {'as': 'vsc-easymotion'})
Plug 'easymotion/vim-easymotion', Cond(!exists('g:vscode'))
```

VSCode infomation:
```
版本: 1.80.2 (user setup)
提交: 2ccd690cbff1569e4a83d7c43d45101f817401dc
日期: 2023-07-27T20:40:28.909Z
电子: 22.3.14
ElectronBuildId: 22695494
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```

PS:
When use v0.3.2 version not this problem, but use today upgrade version v0.4.0 this fail.

PS:
I noticed in the v0.4.0 release update notes. `highlight: remove easymotion support`.

### Steps To Reproduce

use <Plug>(easymotion-j) by map

### Expected Behavior

No error.

**Comment by theol0403** [comment]
Easymotion is unsupported. Use hop/sneak/lightspead/flash.

**Comment by zhaoxuyll** [comment]
Please support Easymotion. because alert hop.nvim is buggly.

**Comment by theol0403** [comment]
Not worth the code to support it. Easymotion does not properly use nvim APIs, and uses hacks. Why is hop buggy?

**Comment by zhaoxuyll** [comment]
> Not worth the code to support it. Easymotion does not properly use nvim APIs, and uses hacks. Why is hop buggy?

I always get this error when I create a new file or switch tabs several times normally
![Code_K3PfH2xUtG](https://github.com/vscode-neovim/vscode-neovim/assets/3224165/83a50cfc-cab8-426d-8100-91b92b2addd1)

**Comment by theol0403** [comment]
The slowness is a new bug I'm investigating.

**Comment by theol0403** [comment]
Not sure what the issue with hop is, but you might not have configured it properly.

**Comment by zhaoxuyll** [comment]
> Not sure what the issue with hop is, but you might not have configured it properly.

This is my config is very sample:
```
lua << EOF
require('hop').setup()
EOF
map j <Cmd>HopVerticalAC<CR>
map k <Cmd>HopVerticalBC<CR>
map h <Cmd>HopWordCurrentLineBC<CR>
map l <Cmd>HopWordCurrentLineAC<CR>
map s <Cmd>HopChar1<CR>
```

**Comment by zhaoxuyll** [comment]
I noticed that hop doesn't seem to have an active maintenance and vscode section anymore, see the following question:

https://github.com/phaazon/hop.nvim/issues/357

https://github.com/phaazon/hop.nvim/issues/206

**Comment by theol0403** [comment]
Is easy motion actively developed either? Definitely not our fork of it.

**Comment by zhaoxuyll** [comment]
Thanks to , I'm exploring some possible options, as I do need the usual easymotion features.

**Comment by zhaoxuyll** [comment]
I found this fork version, this is available.

https://github.com/smoka7/hop.nvim

**Comment by theol0403** [comment]
Slowness fixed

**Comment by userrand** [comment]
I also had a problem with that fork. Maybe consider removing https://github.com/vscode-neovim/vscode-neovim/wiki/Plugins#vim-easymotion

**Comment by theol0403** [comment]
@userrand the wiki is open, feel free to delete it.
