### ISSUE TITLE
Consider rename lua vscode module to vscode-neovim

### ISSUE THREAD

**Issue by bika-c** [vscode-neovim/vscode-neovim#1354]
In my config, I have a vscode module for handling all vscode related commands. Since `v0.4.0`, vscode neovim exported a table module named `vscode` causing a conflict with a really unintuitive error message. To have a better compatibility, could we use `vscode-neovim` or `vscode-nvim` as the module name instead? I could open a pull request but I think this should be discussed before action.

**Comment by justinmk** [comment]
> Since `v0.4.0`, vscode neovim exported a table module named `vscode`

Do you mean `_G.vscode` is added to the global namespace? Would it fix things if vscode-neovim did not do that? Or the naming conflict on 'runtimepath' still presents an issue?

**Comment by bika-c** [comment]
Umm, I am referring to this [module](https://github.com/vscode-neovim/vscode-neovim/blob/214acebf9dc3e748d875b21bf70f3025e86933be/runtime/lua/vscode.lua#L15C7-L15C7) here:
```lua

local api = require("vscode.api")
local defaults = require("vscode.defaults")
local cursor = require("vscode.cursor")

local M = {}

M.notify = api.notify
M.call = api.call

-- this guy here
M.setup = function()
    defaults.setup()
    cursor.setup()
end

return M -- exported
```

This is being referenced from [here](https://github.com/vscode-neovim/vscode-neovim/blob/214acebf9dc3e748d875b21bf70f3025e86933be/vim/vscode-neovim.vim#L102):
```lua
lua << EOF
require("vscode").setup()
EOF
```

And neovim is complaining this if I have a module named vscode in my config:
```shell
Error detected while processing pre-vimrc command line..script …/vscode/extensions/asvetliakov.vscode-neovim-0.4.0/vim/vscode-neovim.vim:
line  103:
E5108: Error executing lua [string ":lua"]:1: attempt to index a boolean value
stack traceback:
	[string ":lua"]:1: in main chunk
```

**Comment by henrispriet** [comment]
i am having the same issue

**Comment by theol0403** [comment]
Sure, not a big deal to rename.
