### ISSUE TITLE
How to use VSCodeNotify() instead of VSCodeNotifyRange() after recent breaking changes with 'editor.action.reindentselectedlines' command

### ISSUE THREAD

**Issue by still-dreaming-1** [vscode-neovim/vscode-neovim#1355]
Previously when I called VSCodeNotifyRange had several parameters it accepted. Here is an example of how I used it before from my Lua config:

```
-- change o to also use VS Code to auto indent
normalMap('o', "o<Cmd>call VSCodeNotifyRange('editor.action.reindentselectedlines', line('.'), line('.'), 1)<CR>")
```

The idea with this command is to change the behavior of `o` to both start a new line and get VSCode to indent it.

Currently if I just change it to use `VSCodeNotify()` and only pass the command, it leaves the line unindented. If I then manually run that reindentselectedlines command, it does indent the line.

I also tried using `V` to visually select the entire line before calling `VSCodeNotify('editor.action.reindentselectedlines')`, but it still doesn't work.

On the new, unindented line, I can also manually run (via `:`) `call VSCodeNotify('editor.action.reindentselectedlines')` and it will indent the line.

**Comment by theol0403** [comment]
Thanks for this. I didn't realize there was a usecase for the function without simply forwarding visual mode. I'll re-introduce it shortly.

**Comment by theol0403** [comment]
Actually, this is already possible. I'll still re-add because of https://github.com/vscode-neovim/vscode-neovim/issues/1351.

The problem is that the cursor update from `o` isn't sent to vscode by the time that the command is sent. I think I'll also solve this.

**Comment by theol0403** [comment]
@still-dreaming-1 in the linked PR, using `VSCodeNotify` in your example will now work.

**Comment by still-dreaming-1** [comment]
If updating the cursor after `o` is possible, enabling the use of VSCodeNotify() for this use case, that sounds like the best solution.

**Comment by theol0403** [comment]
That is what the PR does.

**Comment by still-dreaming-1** [comment]
Is this supposed to be fixed in v0.4.1 of this extension? I am currently on that version, and my mapping is running the 'editor.action.reindentselectedlines' command on the line the cursor started on instead of the line it is on at the time the command is run. I am basing this conclusion on the fact that the cursor is at the very start of the new line. Also, if I intentionally mess up the indention of the line the cursor is one before pression `o`, the indentation of that line does get fixed. Here is the mapping I am using from my init.lua:

`vim.keymap.set('n', 'o', "o<Cmd>call VSCodeNotify('editor.action.reindentselectedlines')<CR>")`

**Comment by still-dreaming-1** [comment]
> That is what the PR does.

Is this supposed to be fixed in v0.4.1 of this extension? I am currently on that version, and my mapping is running the 'editor.action.reindentselectedlines' command on the line the cursor started on instead of the line it is on at the time the command is run. I am basing this conclusion on the fact that the cursor is left at the very start of the new line. Also, if I intentionally mess up the indention of the line the cursor is on before pressing `o`, the indentation of that line does get fixed. Here is the mapping I am using from my init.lua:

`vim.keymap.set('n', 'o', "o<Cmd>call VSCodeNotify('editor.action.reindentselectedlines')<CR>")`

**Comment by still-dreaming-1** [comment]
This workaround provided by @xiyaowong works. Actually they suggested using a delay of 20, but I noticed if I change it to 1 it still seems to resolve my issue.
```
vim.keymap.set('n', 'o', function ()
  vim.api.nvim_feedkeys('o', 'n', false)
  vim.defer_fn(function ()
    vim.fn.VSCodeNotify('editor.action.reindentselectedlines')
  end, 1)
end)
```

Based on that example, here is a mapping which I think illustrates the issue well. This will run the reindent on the original line instead of the new line:
```
vim.keymap.set('n', 'o', function ()
  vim.api.nvim_feedkeys('o', 'n', false)
  vim.fn.VSCodeNotify('editor.action.reindentselectedlines')
end)

**Comment by xiyaowong** [comment]
It should be related to the event loop

**Comment by xiyaowong** [comment]
The screenshot should already explain the issues. The defer placed the task on queue, and waits other events proccessed (I'm not familiar with the internal details of NVIM. Correct me if I understand incorrectly)

Without defer
![image](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/5ad410bf-94c7-4c1d-8b51-39f9a43b61bc)

With defer
![image](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/70daffd9-ba44-49e1-baa3-7539bc24bb3a)

**Comment by xiyaowong** [comment]
Now asynchronous actions are automatically scheduled, so using `vscode.action` directly should work fine.

See https://github.com/vscode-neovim/vscode-neovim#lua

```lua
vim.keymap.set('n', 'o', function ()
  vim.api.nvim_feedkeys('o', 'n', false)
  require('vscode-neovim').action('editor.action.reindentselectedlines')
end)
```
