### ISSUE TITLE
bug: unmap mi/ma/mI/mA not working => can't disable multiple cursor

### ISSUE THREAD

**Issue by echaya** [vscode-neovim/vscode-neovim#1359]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.8.1

### Operating system/version

Win 10

### Describe the bug

This is a known issue per https://github.com/vscode-neovim/vscode-neovim/issues/631#issuecomment-852828923.

Re-raising this because since 0.4.0 version of the plug-in, vscode-insert.vim can no longer found under the following path `\.vscode\extensions\asvetliakov.vscode-neovim-0.4.1\vim\`. so that I can't manually disable the shortcuts now

Could you please also let me know where the vscode-insert file has been moved to => so I can still at least disable it manually. Thanks!

### Steps To Reproduce

1. putting the following in the init.vim

``` vim
    xunmap ma 
    xunmap mi 
    xunmap mA 
    xunmap mI 
```
2. Start vscode, all the unmapped shortcuts still work in visual mode

### Expected Behavior

ma/mA/mi/mI no longer working in visual mode per xunmap

**Comment by theol0403** [comment]
It got moved to https://github.com/vscode-neovim/vscode-neovim/blob/master/runtime/lua/vscode-neovim/cursor.lua.

However, I don't understand why it doesn't work to unmap. Can you try?

**Comment by echaya** [comment]
> It got moved to https://github.com/vscode-neovim/vscode-neovim/blob/master/runtime/lua/vscode-neovim/cursor.lua.
> 
> However, I don't understand why it doesn't work to unmap. Can you try?

Thanks. I have tried adding the `xunmap` in my init.vim (after loading the plugins) - it did not do anything.

**Comment by theol0403** [comment]
It works for me, doing `xunmap mi` in init.vim stops mi from doing anything.

**Comment by echaya** [comment]
@theol0403 you used to be able to reproduce this  per https://github.com/vscode-neovim/vscode-neovim/issues/631#issuecomment-852828923 - what change you made to make it work?

I have tried to set the xunmap in the main block or within `if exists('g:vscode')` - both way not working

**Comment by kevintraver** [comment]
They got moved to `runtime/lua/vscode-neovim/cursor.lua`

https://github.com/vscode-neovim/vscode-neovim/blob/a881133d68c675593cee14f5b5ebb1aceaea8ab5/runtime/lua/vscode-neovim/cursor.lua#L43-L46

You should be able to just delete those lines.

Having an option to disable these keymaps would be super helpful.

**Comment by echaya** [comment]
> They got moved to `runtime/lua/vscode-neovim/cursor.lua`
> 
> https://github.com/vscode-neovim/vscode-neovim/blob/a881133d68c675593cee14f5b5ebb1aceaea8ab5/runtime/lua/vscode-neovim/cursor.lua#L43-L46
> 
> You should be able to just delete those lines.
> 
> Having an option to disable these keymaps would be super helpful.

I dug a bit deeper today and managed to disable it permanently  it in `init.lua`. I was not able to do it using `init.vim`. Hope it helps. 

``` lua
if vim.g.vscode then
    vim.keymap.del('x', 'ma')
    vim.keymap.del('x', 'mi')
    vim.keymap.del('x', 'mA')
    vim.keymap.del('x', 'mI')
end
```
