### ISSUE TITLE
bug: shift+space can't bind

### ISSUE THREAD

**Issue by ahmadshiddiq** [vscode-neovim/vscode-neovim#1366]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.1

### Operating system/version

MacOS 13.4.1

### Describe the bug

I want to bind the `shift+space` into find next error. I've try another keybind the command was running, for example I bind to `space+n`.

### Steps To Reproduce

1. add configuration for bind the key in init.vim `nnoremap <s-space> <Cmd>call VSCodeNotify("editor.action.marker.nextInFiles")<CR>`
2. reload window the vscode
3. shift + space not binding

### Expected Behavior

Should be bind to `shift+space`

**Comment by justinmk** [comment]
`:call nvim_input('<s-space>')` triggers the mapping, so this suggests that vscode-neovim is not sending `<s-foo>` chords.

Note: don't need to special case capitalization, i.e. sending `<s-a>` to Nvim will do the right thing even if the user mapped `nnoremap A ...` instead of `nnoremap <s-a> ...`.

**Comment by justinmk** [comment]
I didn't provide a solution, I shared some notes about changes needed in vscode-neovim.

**Comment by theol0403** [comment]
You need to pass `ctrl-space` to neovim from vscode keybindings, please read readme.
