### ISSUE TITLE
bug: highlighting breaks RTL text

### ISSUE THREAD

**Issue by adueck** [vscode-neovim/vscode-neovim#1367]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.8.3

### Operating system/version

MacOS 13.0.1

### Describe the bug

When using NeoVim highlighting over matching RTL text (Arabic etc.), the character ordering is broken. (This happens both while searching and while in visual mode).
 
![Screenshot 2023-08-01 at 6 19 38 PM](https://github.com/vscode-neovim/vscode-neovim/assets/12955501/dfe3c7e5-54b0-4e5c-8f6d-164003686f03)

![Screenshot 2023-08-01 at 6 20 22 PM](https://github.com/vscode-neovim/vscode-neovim/assets/12955501/5a86a9a2-c637-4c4c-8384-75abc51efe6c)

One of the great things about VSCode is how it handles RTL text perfectly (including selecting). I've been delighted to be able to use NeoVim + VSCode and enjoy the RTL support as well, it would be great if this little wrinkle could be ironed out. Perhaps this is a more difficult issue though...

### Steps To Reproduce

 1. Type something in RTL text
 2. Highlight part of or all of the RTL text
 3. The order of the characters is scrambled.

### Expected Behavior

Just as with the VSCode native highlighting/selection, a selection should not break the RTL word order.

**Comment by xiyaowong** [comment]
![image](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/9229cb59-6ba2-4fd7-b4e8-001f64fba72c)

The current highlighting is consistent with nvim. There is nothing we can do.

You can use vscode's search.

```vim
map <silent> / <Cmd>call VSCodeCall('actions.find')<CR>
```
