### ISSUE TITLE
bug: Huge performance downgrade since 0.4.0 when winblend is set

### ISSUE THREAD

**Issue by thomazmoura** [vscode-neovim/vscode-neovim#1369]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

v0.9.1

### Operating system/version

Microsoft Windows 22H2

### Describe the bug

Since 0.4.0 if I have the line `set winblend=15` on my .vimrc and nothing else I get a huge penalty on performance - even just moving the cursor up and down gets sluggish. Downgrading to 0.3.2 solves the issue. Ignoring this line when VS Code is detected solves it too.

### Steps To Reproduce

Start with an empty .vimrc and then add the following line to it: `set winblend=15`.
Open any file with multiple lines on VS Code and try to move freely between the lines with j and k.

### Expected Behavior

I'm fine with this settings having no effect at all on VS Code (this setting adds pseudotransparency to floating windows which is interesting TUI but pointless on any GUI with proper transparency support) and for the time being I will keep it under a check for VS Code on my .vimrc, but it would be nice if it was just ignored like it seems to be on 0.3.2 - specially since it took me quite a while to find out that this line was the culprit.

For anyone interested that's my workaround for the time being (on my .vimrc):

``` vimrc
if ! exists('g:vscode')
  set winblend=15
endif
```

**Comment by thomazmoura** [comment]
I believe this is related to the highlight changes mentioned on #1349 (I know NeoVim makes the pseudotransparency by changing the color of the characters based on the "color of the character behind" so I suppose internally NeoVim might use highlights to make this)

**Comment by theol0403** [comment]
We should force winblend off in the default options
