### ISSUE TITLE
feature: Support IM switch

### ISSUE THREAD

**Issue by haolly** [vscode-neovim/vscode-neovim#1370]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

When you write Chinese in nvim using Input Method, press ESC to enter normal mode, but the command is handled by the input method

### Describe the solution you'd like

like https://github.com/hsanson/vim-im  or  https://github.com/VSCodeVim/Vim#input-method

### Describe alternatives you've considered

imdisable does not work in nvim , see https://github.com/neovim/neovim/issues/1708

**Comment by xiyaowong** [comment]
@haolly Do you tried this plugin https://github.com/keaising/im-select.nvim ?

**Comment by haolly** [comment]
> @haolly Do you tried this plugin https://github.com/keaising/im-select.nvim ?

@xiyaowong  I just tried it, it works in Neovim-QT, but not nvim.exe and vscode-neovim

**Comment by xiyaowong** [comment]
@haolly  IMO, the best way is to use Vim events to call commands provided by other VSCode extensions. This feature is not related to vscode-neovim. VSCodeVim is a Vim emulator, lacks a complete event feature, so this feature is built-in.

**Comment by xiyaowong** [comment]
This works for me. To be honest, this feature is not very useful. There are many issues with input method switching in VSCodeVim.

```vim
autocmd InsertEnter * call jobstart("D:\\bin\\im-select.exe 2052")
autocmd InsertLeave * call jobstart("D:\\bin\\im-select.exe 1033")
```

**Comment by tainzhi** [comment]
> This works for me.
> 
> ```viml
> autocmd InsertEnter * call jobstart("D:\\bin\\im-select.exe 2052")
> autocmd InsertLeave * call jobstart("D:\\bin\\im-select.exe 1033")
> ```
> 
> To be honest, this feature is not very useful. There are many issues with input method switching in VSCodeVim.

Add those two lines into vscode-nvim  entension config > After Init config, then it works to me.

**Comment by ethan-huo** [comment]
For me, I use macism, and I only ever need ABC in non-insert mode.

```json

{
    "vscode-neovim.afterInitConfig": [
        // "autocmd InsertEnter * silent! lua vim.fn.jobstart({'/opt/homebrew/bin/macism', 'com.apple.keylayout.US'})",
        "autocmd InsertLeave * silent! lua vim.fn.jobstart({'/opt/homebrew/bin/macism', 'com.apple.keylayout.ABC'})"
    ]
}
```
