### ISSUE TITLE
bug: VSCode Neovim hangs with big visual mode changes since 0.4.0

### ISSUE THREAD

**Issue by RodrigoDLPontes** [vscode-neovim/vscode-neovim#1371]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Windows 21H2

### Describe the bug

Since version 0.4.0, I have observed severe slowdowns (to the point where it seems to hang) when making big changes with visual mode (for example, deleting all file contents with visual mode). Here is what it looks like for version 0.3.2:

![vscode-neovim-032](https://github.com/vscode-neovim/vscode-neovim/assets/11012066/befca694-ce02-4a2c-8258-272043db49ff)

And for 0.4.1 (had to cut the recording short because 3 minutes in and I still hadn't regained control):

![vscode-neovim-041](https://github.com/vscode-neovim/vscode-neovim/assets/11012066/ff51f817-f6ed-4a76-97aa-68056fdc52c1)

The same occurs for 0.4.0. Note that I was **NOT** able to reproduce with an empty init.vim/lua, however this must be some regression in VSCode Neovim since I haven't updated any Vim plugins in a while.

Please let me know if there are any logs or information I can share to assist in debugging.

### Steps To Reproduce

1. Select a lot of text
2. Edit that text (delete or change)
3. Hangs

### Expected Behavior

For it not to hang.

**Comment by bstncartwright** [comment]
Also experiencing this on macOS 13.4 (Intel). Rolled back to v0.3.2 and it no longer hangs.

**Comment by bstncartwright** [comment]
Looks like this has also been reported here as well: https://github.com/vscode-neovim/vscode-neovim/issues/1349

**Comment by theol0403** [comment]
Please try to identify the setting/plugin that causes this. Dup of https://github.com/vscode-neovim/vscode-neovim/issues/1349
