### ISSUE TITLE
feature: Diff Editor: Switch Sides Add Hot Key Mapping

### ISSUE THREAD

**Issue by parkgang** [vscode-neovim/vscode-neovim#1373]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

I want to explore Windows only with a keyboard.

Among them, I thought it was a shame and inconvenience that I couldn't navigate the screen before and after the comparison on the diff screen with the keyboard.

However, I saw that VSCode Level supports shortcut keys from `VSCode@v1.81` to [diffEditor.switchSide](https://code.visualstudio.com/updates/v1_81#_switch-sides), and I thought it would be nice if the shortcut key was included in Neovim.

### Describe the solution you'd like

Map the shortcut [diffEditor.switchSide](https://code.visualstudio.com/updates/v1_81#_switch-sides) from `VSCode@v1.81` to the command in Vim.

> For example, `diff side` can be moved to `<C-w> + w` on `diff` screen

### Describe alternatives you've considered

The previous case where the shortcut key of `VSCode` was mapped to the shortcut key of `Neovim`

### Additional context

No response

**Comment by xiyaowong** [comment]
Please customize your own keybindings.json. It's difficult to meet everyone's shortcut needs.

**Comment by ghry5** [comment]
As a reference for anyone looking for the same functionality. This is what I came up with:
```json
[
  {
    "key": "ctrl+h",
    "command": "vscode-neovim.send",
    "when": "editorTextFocus && neovim.ctrlKeysNormal.h && neovim.init && neovim.mode != 'insert' && editorLangId not in 'neovim.editorLangIdExclusions' && (!isInDiffEditor || !isInDiffRightEditor)",
    "args": "<c-h>"
  },
  {
    "key": "ctrl+h",
    "command": "-vscode-neovim.send",
    "when": "editorTextFocus && neovim.ctrlKeysNormal.h && neovim.init && neovim.mode != 'insert' && editorLangId not in 'neovim.editorLangIdExclusions'"
  },
  {
    "key": "ctrl+h",
    "command": "diffEditor.switchSide",
    "when": "editorTextFocus && neovim.ctrlKeysNormal.h && neovim.init && neovim.mode != 'insert' && editorLangId not in 'neovim.editorLangIdExclusions' && isInDiffEditor && isInDiffRightEditor"
  },
  {
    "key": "ctrl+l",
    "command": "vscode-neovim.send",
    "when": "editorTextFocus && neovim.ctrlKeysNormal.l && neovim.init && neovim.mode != 'insert' && editorLangId not in 'neovim.editorLangIdExclusions' && (!isInDiffEditor || isInDiffRightEditor)",
    "args": "<c-l>"
  },
  {
    "key": "ctrl+l",
    "command": "-vscode-neovim.send",
    "when": "editorTextFocus && neovim.ctrlKeysNormal.l && neovim.init && neovim.mode != 'insert' && editorLangId not in 'neovim.editorLangIdExclusions'"
  },
  {
    "key": "ctrl+l",
    "command": "diffEditor.switchSide",
    "when": "editorTextFocus && neovim.ctrlKeysNormal.l && neovim.init && neovim.mode != 'insert' && editorLangId not in 'neovim.editorLangIdExclusions' && isInDiffEditor && !isInDiffRightEditor"
  }
]
```
