### ISSUE TITLE
bug: Weird virtual characters

### ISSUE THREAD

**Issue by ahmed-yasser1** [vscode-neovim/vscode-neovim#1374]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

NVIM v0.9.1

### Operating system/version

Pop!_OS 22.04 LTS x86_64

### Describe the bug

when I enter visual mode and select some lines I find some weird characters at the end of some lines.

as you see in the following picture

![bug](https://github.com/vscode-neovim/vscode-neovim/assets/99615534/e8c04dbd-794a-486f-8fd1-dbcf3994b69c)

__NOTE__ I did not face this bug in version `0.3.2`

### Steps To Reproduce

1. go to visual mode
2. just select some lines 
3. sometimes these characters appear and sometimes not, so try step 1 and 2 until you find them

### Expected Behavior

What I expect to find that when I go to visual mode and select some lines, I do not find these weird characters

**Comment by PtravisCS** [comment]
I'm on Ubuntu 22.04.3, nvim v0.9.1 and am getting the same issue. In my case, the extra virtual character is always a repeat of the last character from the line it appears on.

I have noticed that when I do visual line (V) I sometimes see a virtual copy of every character in the line, but shifted 1 space to the right. I don't know if this is an unrelated bug or not, but thought I should mention it.

This bug started around 2 - 3 weeks ago for me after an update to the vscode-neovim plugin.

![image](https://github.com/vscode-neovim/vscode-neovim/assets/21698432/c69c6df4-63b0-4905-8c45-10dd6529d114)

Hopefully this proves helpful.

**Comment by huangzl97** [comment]
Looks like they recently released a major version [v0.4.0](https://github.com/vscode-neovim/vscode-neovim/releases/tag/v0.4.0) which introduce several breaking changes and features related to cursor.

I tried rollback to 0.3.2 and everything works as usual. So i decided to use 0.3.2 until 0.4.x is stable.

**Comment by Tesohh** [comment]
getting this issue too on macOS.
<img width="338" alt="Screenshot 2023-08-10 alle 23 37 16" src="https://github.com/vscode-neovim/vscode-neovim/assets/45905658/369528b8-6a6b-48cf-8898-3df92c7209ec">

**Comment by Tesohh** [comment]
I noticed something more: basically it struggles with Go files specifically with tab size 4 (gofmt default) which I noticed you are using too. for now I'll stick with 0.3.2 so it at least doesn't leave weird artifacts around the place

**Comment by ahmed-yasser1** [comment]
It is really very strange. I tried do reproduce this behavior with rust and python but I can't :(:

1. rust

![image](https://github.com/vscode-neovim/vscode-neovim/assets/99615534/6e3b958d-a67f-4921-b89f-b724f98b7193)

2. python

![image](https://github.com/vscode-neovim/vscode-neovim/assets/99615534/cf096421-d3a5-472c-ab4d-29ca1dfd2e98)


@Tesohh

**Comment by washanhanzi** [comment]
I tried with rust and javascript, it worked fine. It only happens in go.

Especially after I yank something.

<img width="533" alt="CleanShot 2023-08-11 at 11 29 37@2x" src="https://github.com/vscode-neovim/vscode-neovim/assets/56581242/2f76d877-463d-4131-8a5f-d6e4a31f7d1e">

**Comment by Tesohh** [comment]
same issue on windows:
![image](https://github.com/vscode-neovim/vscode-neovim/assets/45905658/6ebd2f75-8a98-40c4-ab94-10baf89d8f7e)

**Comment by PtravisCS** [comment]
I've been able to re-create with PHP, JS, and a txt file.
Was not able to re-create in Rust, Python, Perl, C, or JSON.
I don't have any Go code handy to test on.

The txt file has ANSI terminal escapes in it though (results from `grep --color=always` intended to be played back with `less -R`), so I don't know how much of the issue with this file is due to vscode/nvim trying to parse through those.

I have noticed that I struggle to re-create this in my smaller files ( x < 100 lines), though I'm not sure how much of this is luck.
I also found that restarting vscode can cause this issue to go away for a bit.

**Comment by danielfrg** [comment]
A similar issue but not with characters but with some backgrounds:

![CleanShot 2023-08-11 at 14 17 45@2x](https://github.com/vscode-neovim/vscode-neovim/assets/1580714/ce60f157-d76b-4db4-845d-6b61da993186)

**Comment by cdfmlr** [comment]
> getting this issue too on macOS.
> <img alt="Screenshot 2023-08-10 alle 23 37 16" width="338" src="https://user-images.githubusercontent.com/45905658/259879894-369528b8-6a6b-48cf-8898-3df92c7209ec.png">

Similar to @Tesohh's. On macOS, It looks like there are holes in the screen. And I noticed that these holes are moving with the screen scrolling.


https://github.com/vscode-neovim/vscode-neovim/assets/45259230/daf2efe1-64a9-43e8-bf54-6c6137d815f8



NVIM v0.9.1, VSCode Neovim v0.4.1

**Comment by mhjacks** [comment]
I've seen the same thing on Fedora 38, with neovim 0.9.1 and plugin 0.4.2. In my case, it occurs when I have a YAML file that has additional requirements beyond YAML (specifically: Helm template or ansible playbook). It seems to be an interaction with ALE, and specifically when ALE is installed via OS-level package.

In my case, I work around it by installing ALE in my user directory and skipping it the "normal" way (in init.vm via checking the vscode variable, and not enabling it).

**Comment by searleser97** [comment]
Also facing this issue on Ubuntu 22.04 with latest VSCode version at the moment and latest VScode-Neovim extension version

**Comment by Deuscx** [comment]
still face the problem when there are emojis in the file.


https://github.com/vscode-neovim/vscode-neovim/assets/48537979/36728c88-0d4e-4f69-8efc-ada47a9211a3

**Comment by theol0403** [comment]
Yeah when https://github.com/vscode-neovim/vscode-neovim/pull/1083 was merged I don't think it also fixed the highlight provider.

**Comment by daelmaak** [comment]
Still happening 
![image](https://github.com/user-attachments/assets/aad4a52e-8ed4-4d0e-bcda-42f64b1c23a8)

I'm using:
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
VSCode 1.91.1

**Comment by dnery** [comment]
This is still very much happening in macOS - not sure if extension is to blame or if Cursor is. In any case, the repro is trivial, pretty much every time I do a `/<...>` search and navigate with `n`  I get the ghost characters everywhere.

**Comment by willvousden** [comment]
I can also confirm that this issue still exists, on macOS at least.

<img width="693" alt="Image" src="https://github.com/user-attachments/assets/bb791d94-db6e-42a8-ad83-59cceb672fb5" />

**Comment by dnery** [comment]
Sorry to necrob-ump this, but was this fixed in some off-branch build? Has anyone found a workaround for this at all? Some sort of configuration that prevents this from happening?

Or alternatively, maybe a quick way to redraw the UI and remove the ghost characters? (Preferably that doesn't involve reloading the entire VSCode/Cursor view, which takes several seconds.)

It's starting to become a major point of slowness and confusion in my workflow.

**Comment by janow25** [comment]
I have this problem quite often as well. What I've found to be a quick fix is pressing Ctrl+Shift+P, then searching for "Neovim: Restart Extension". After pressing Enter, the virtual characters disappear.
