### ISSUE TITLE
bug: Not updating cursor position while running keymap

### ISSUE THREAD

**Issue by still-dreaming-1** [vscode-neovim/vscode-neovim#1384]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Ubuntu 20.04.6 LTS (through WSL 2 on Windows 10)

### Describe the bug

This was supposed to be fixed by the [1358](https://github.com/vscode-neovim/vscode-neovim/pull/1358) pull request, but it didn't resolve the issue for me.

The following mapping is running the 'editor.action.reindentselectedlines' command on the line the cursor started on instead of the line it is on at the time the command is run. I am basing this conclusion on the fact that the cursor is left at the very start of the new line. Also, if I intentionally mess up the indention of the line the cursor is on before pressing o, the indentation of that line does get fixed. Here is the mapping I am using from my init.lua:

vim.keymap.set('n', 'o', "o<Cmd>call VSCodeNotify('editor.action.reindentselectedlines')<CR>")

### Steps To Reproduce

1. Add `vim.keymap.set('n', 'o', "o<Cmd>call VSCodeNotify('editor.action.reindentselectedlines')<CR>")` to init.lua
2. Place cursor on a line that is not indented properly (not really necessary, but helps illustrate problem better)
3. Press `o` while in normal mode

### Expected Behavior

The wrongly indented line the cursor started on should not get changed, but it does because the cursor position is not being updated (educated guess). The cursor should be left properly indented on the next line, instead it is at the very beginning of the line because `VSCodeNotify()` is called against the old cursor position (educated guess).

**Comment by still-dreaming-1** [comment]
I really need some way to get `o` working better for indenting the cursor at the new line. It had it working better when I was able to call `VSCodeNotifyRange()` and pass in specific line number.

**Comment by xiyaowong** [comment]
Currently the easist way is add delay to execute command in the mapping. Of course, this is not the perfect solution, but the delay can indeed solve many problems.

```lua
vim.keymap.set('n', 'o', function ()
  vim.api.nvim_feedkeys('o', 'n', false)
  vim.defer_fn(function ()
    vim.fn.VSCodeNotify('editor.action.reindentselectedlines')
  end, 20)
end)
```

**Comment by still-dreaming-1** [comment]
@xiyaowong thanks, I will try it out. I'm going to close this issue as it is a duplicate of my other issue https://github.com/vscode-neovim/vscode-neovim/pull/1358 which recently got re-opened.

**Comment by still-dreaming-1** [comment]
@xiyaowong Actually that worked! Interestingly enough, even if I change the delay from 20 to 1, it still resolves my issue.
