### ISSUE TITLE
bug: Vim command line does not open with : when !notebookEditorFocused

### ISSUE THREAD

**Issue by aaronsgithub** [vscode-neovim/vscode-neovim#1392]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.8.1

### Operating system/version

WSL2 Ubuntu 22.04.2

### Describe the bug

When editing jupyter notebooks in VS Code, there are 3 modes your cursor can be in:

1. Inside a notebook cell in insert mode.
2. Inside a notebook cell in normal mode.
3. Inside a notebook, but not inside a cell. Your cursor is focused on one cell but is not inside it, and you can move between focused cells using `j` and `k` keystrokes.

When in mode 3, `:` does not open the vim command line and so you cannot do `:w`.
It does work as expected in mode 2.

I believe the "when" condition for a key binding should be
```
`editorTextFocus && jupyter.hascodecells && Ijupyter.webExtension ! notebookEditorFocused`
```

but I cannot find the associated command to assign a key binding to open the Vim command line.

Is there a command available to assign a key binding which opens the Vim command line?
Otherwise, are there any alternative work arounds?

### Steps To Reproduce

1. Install the [ms-tools.jupyter](https://github.com/Microsoft/vscode-jupyter) extension pack
2. Open an .ipynb file in Visual studio code.
3. Ensure you are in mode 3 described above (e.g. place your cursor in a cell and press `Esc` twice)
4. Press `:`

### Expected Behavior

Vim command line opens.

**Comment by theol0403** [comment]
Any VSCode commands are specified in package.json. When the text editor is focused, the : is received by the type event. But when it's not focused, we need to add bindings manually. PR is welcome.

**Comment by xiyaowong** [comment]
> Inside a notebook, but not inside a cell. Your cursor is focused on one cell but is not inside it, and you can move between focused cells using j and k keystrokes.

In the model 3 you described, there's no text editor focused. note: "jk" motion in this mode is  provided by the notebook itself.
