### ISSUE TITLE
bug: Selection using mouse is not syncing fast enough

### ISSUE THREAD

**Issue by pvinis** [vscode-neovim/vscode-neovim#1404]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

v0.9.1

### Operating system/version

macos 13.5.1

### Describe the bug

I am with an empty init.lua and a vscode with only neovim plugin.

I noticed that if I have the cursor somewhere, and select using the mouse some other chars, and tapping `x` to delete, the previously selected char will be deleted, which is wrong. If I do the same, wait for a second, and then press `x` then the new selection will be deleted. But doing it right after the mouseup, the wrong thing is deleted.

### Steps To Reproduce

I am with an empty init.lua and a vscode with only neovim plugin.

- I have a regular file with many lines.
- I click once, on say line 2 on any character, and the cursor is on that character.
- Then I click and drag on line 5 up to line 8 to select a bunch of characters/lines
- Immediately tap `x` to delete the selected chars/lines, but the character from line 2 that was previously on the cursor is deleted.

I noticed that if I wait for a second, and then press `x` then the chars/lines will be deleted. But doing it right after the mouseup, the wrong thing is deleted.

### Expected Behavior

The newly selected chars should be the ones being deleted always.

**Comment by xiyaowong** [comment]
This problem is the same as what this PR is trying to solve

**Comment by theol0403** [comment]
@xiyaowong I haven't really tested with faster speeds, it's possible that we can get away with 50-100ms debounce instead?

**Comment by theol0403** [comment]
Otherwise, the other option would be to create a lock, triggered by `onSelectionChanged`, that queues typing events in `TypingManager` until the debounce has resolved.

**Comment by xiyaowong** [comment]
@theol0403 

> Otherwise, the other option would be to create a lock, triggered by `onSelectionChanged`, that queues typing events in `TypingManager` until the debounce has resolved.

I tried this solution, and it works as expected when selecting content with the mouse. However, in my use case, I execute `cursorMove` in nvim to move the cursor, and the execution relies on input triggering. The input needs to wait for synchronization to complete, which causes lag.

I think reducing the debounce time is the best solution at the moment. The cursor synchronization process is very fast, and there haven’t been any issues with using a 20ms debounce time before.

**Comment by theol0403** [comment]
@xiyaowong from my testing, any debouncing less than 50ms results in race conditions where vscode and neovim step on each other. This can be seen when dragging a selection with the mouse, often the selection will not be correct.

**Comment by xiyaowong** [comment]
50ms is ok, it should satisfy most usage scenarios.
