### ISSUE TITLE
bug: Multiple errors after fresh install

### ISSUE THREAD

**Issue by carlitador** [vscode-neovim/vscode-neovim#1408]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- I cannot reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.6.1

### Operating system/version

Linux Mint 21.1 Vera

### Describe the bug

After a fresh install of vscode, neovim, and neovim vscode extension, I get the following error message on the vscode-neovim console:
```
Erreur détectée en traitant /home/charles/.vscode/extensions/asvetliakov.vscode-neovim-0.4.3/vim/vscode-neovim.vim :
ligne  111 :
E216: Aucun événement ou groupe ModeChanged * call VSCodeExtensionNotify('mode-changed', v:event.new_mode)
ligne  119 :
E5108: Error executing lua ...code-neovim-0.4.3/runtime/lua/vscode-neovim/defaults.lua:34: attempt to call field 'nvim_create_autocmd' (a nil value)
stack traceback:
	...code-neovim-0.4.3/runtime/lua/vscode-neovim/defaults.lua:34: in function 'setup'
	...liakov.vscode-neovim-0.4.3/runtime/lua/vscode-neovim.lua:15: in function 'setup'
	[string ":lua"]:1: in main chunk
Erreur détectée en traitant /home/charles/.vscode/extensions/asvetliakov.vscode-neovim-0.4.3/runtime/lua/vscode-neovim/force-options.lua :
E5113: Error while calling lua chunk: vim/_meta.lua:324: Invalid option type 'nil' for 'colorcolumn', should be string or table
stack traceback:
	[C]: in function 'error'
	vim/_meta.lua:324: in function 'assert_valid_value'
	vim/_meta.lua:393: in function 'convert_value_to_vim'
	vim/_meta.lua:681: in function '_set'
	vim/_meta.lua:724: in function '__newindex'
	...neovim-0.4.3/runtime/lua/vscode-neovim/force-options.lua:22: in main chunk
```

No bindings are working. I can only see the cursor

### Steps To Reproduce

1. Install vscode
2. Install neovim
3. Install vscode-neovim extension

### Expected Behavior

Expecting normal behaviour...

**Comment by xiyaowong** [comment]
![image](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/4a440be5-2370-490a-8d7b-b4b4db9b5554)

Please upgrade your neovim, the latest stable version is 0.9.1 for now.
