### ISSUE TITLE
bug: Handling of 'o'/'O' broken going from 0.3.2 to 0.4.X (cursor position synchronization)

### ISSUE THREAD

**Issue by scienceplease** [vscode-neovim/vscode-neovim#1409]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Fedora Linux 37

### Describe the bug

Bug first appeared in 0.4.0 and persists in all 0.4.X versions.

When inserting a new line before/after the current line with 'O'/'o', the displayed cursor position (in VSCode) and actual cursor position (in neovim) become out of sync. For example, when a newline is inserted with 'o', a new line is _always visually_ displayed by VSCode and the cursor _appears_ on the new line, but performing an action like 'dd' (delete current line) _sometimes_ effects the line above the displayed cursor position.

The nondeterministic/timing-based nature of the bug hints towards something asynchronous/event loop related where VSCode is inserting a new line but Neovim still thinks the cursor is on the prior line.

What changed with respect to the implementation of 'O'/'o' from 0.3.2 to 0.4.0? Was something that was previously synchronous made asynchronous? Is there some implicit assumption being made about the completion order of two or more asynchronous actions?

### Steps To Reproduce

After lots of experimenting I found a repro that I can perform with a fairly high success rate on v0.4.3. The faster you can complete the sequence below the higher probability of the bug:

Start with line of text with an empty line above and below it.

1) In NORMAL mode, while on the line of text, insert a new line above 'O' and then immediately insert another new line below 'o' your current position (this effectively inserts two empty lines above your line of text).

2) Quickly move to the empty line below the line of text 'jj' and then delete it with 'dd'. The line with text above your cursor will be deleted instead of the empty line that your cursor was on.

### Expected Behavior

 Neovim's cursor position matches VSCode after 'O'/'o'.

**Comment by theol0403** [comment]
Related: https://github.com/vscode-neovim/vscode-neovim/issues/1355

I don't quite understand the repro steps, if you use o/O, you are in insert mode, so how can you use dd?

**Comment by theol0403** [comment]
And yeah, the cursor sync was refactored to support visual mode, but I tried to be careful about bugs like this.

**Comment by scienceplease** [comment]
> Related: #1355
> 
> I don't quite understand the repro steps, if you use o/O, you are in insert mode, so how can you use dd?

Sorry, I should have been more explicit, but the 'dd' example implies switching to normal mode beforehand.

Here's a repo that I can perform with a fairly high success rate on v0.4.3. The faster you can complete the sequence below the higher probability of the bug:

1) Create a line of text with an empty line above and below it.
2) In NORMAL mode, while on the line of text, insert a new line above 'O' and then immediately insert another new line below 'o' your current position (this effectively inserts two empty lines above your line of text).
3) Quickly move to empty line below the line of text ('jj') and then delete the empty line ('dd'). The line with text above will be deleted instead of the line that your cursor was on.

**Comment by xiyaowong** [comment]
@scienceplease
Based on your latest description, this seems to be the same issue as #1404, not related to #1355(@theol0403). @scienceplease  You can test the latest extension build. https://github.com/vscode-neovim/vscode-neovim/suites/15735910479/artifacts/898493791

**Comment by xiyaowong** [comment]
@scienceplease Is this issue still present in the latest version? This issue cannot be completely eliminated, because debouncing is necessary. Please slow down your hand speed :smile:

**Comment by scienceplease** [comment]
@xiyaowong Just tested v4.4 and your optimizations fixed the line de-synchronization issue, thank you!

**Comment by theol0403** [comment]
I'm glad it's fixed, but I don't fully understand why. In the repro steps, it seems like VSCode is never responsible for an action like modifying text or moving the cursor, thus nvim is in charge the whole time and the debounce of vscode -> neovim shouldn't matter.

**Comment by scienceplease** [comment]
@theol0403 I can only offer pure speculation as I'm not familiar with the plugin's internals. Looking at your cursor management code just now, it looks like I may have gotten it backwards, where you update Neovim's cursor state based on changes in VSCode's state. 

Either way, are updates being made asynchronously? I could imagine a situation where the calls are not executed in the order that they were made, resulting in a state mismatch between VSCode and Neovim.
