### ISSUE TITLE
bug: strange external buffer after startup

### ISSUE THREAD

**Issue by xiyaowong** [vscode-neovim/vscode-neovim#1413]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.1

### Operating system/version

window 11

### Describe the bug

screen gif
![external buffer](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/7e9b1daf-0303-4822-ab68-e18e9db983d4)

log
![YN9YIG15L%W%FY84_E}{J`N](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/e7af7890-7a2b-4f2e-bcab-357e2e9f36a9)

### Steps To Reproduce

No clear reproduce step

### Expected Behavior

No untitled document.

When I close output pannel, and then reload window, It works normal.

![external buffer2](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/99a5eb52-3604-402c-ae87-9cbdca0949d3)

![D@B7DIBZUM0RUN415AI69AK](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/ded14e6b-5079-43e0-a6ed-3eafa654eed0)

**Comment by ian-h-chamberlain** [comment]
Wow, I have been running into this issue for a long time, amazed that it's finally fixed (thank you @xiyaowong)!

Something I just discovered, that may have been making the problem worse is slow startup for Python specifically. Even with `nvim --clean` (not using VSCode) on my system I was sometimes seeing >10s startup times on Python files. This can affect all Neovim users (but there is a workaround: https://github.com/neovim/neovim/issues/2437#issuecomment-522236703).

Hopefully the combination of that neovim workaround and the changes in #1414 will make this a smooth experience for everyone!
