### ISSUE TITLE
feature: make vscode commands dot-repeatable and work in operator-pending mode

### ISSUE THREAD

**Issue by theol0403** [vscode-neovim/vscode-neovim#1422]
It would be nice to make the code used for VSCodeCommentary to be modular for any command.

https://github.com/vscode-neovim/vscode-neovim/issues/1345#issuecomment-1658129459

**Comment by xiyaowong** [comment]
It seems that we can provide a helper function to create an operator. The functions in vscode-neovim are the same as vim.ui, vim.keymap, vim.lsp.... How to make these support dotrepeat? Support operator motion? Pointless

**Comment by theol0403** [comment]
I think we basically want to generalize this: https://github.com/vscode-neovim/vscode-neovim/blob/476502604a5fcfef89c528532de17b391036aed6/vim/vscode-code-actions.vim#L6

**Comment by xiyaowong** [comment]
How about this? https://github.com/vscode-neovim/vscode-neovim/compare/master...xiyaowong:vscode-neovim:tmp/operator-helper
