### ISSUE TITLE
Multiple cursors instructions do not work

### ISSUE THREAD

**Issue by luong-komorebi** [vscode-neovim/vscode-neovim#1423]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.1

### Operating system/version

MacOS 13.5.1

### Describe the bug

As https://github.com/vscode-neovim/vscode-neovim/issues/699 stated, multiple cursors does not work at all with the instructions given on home page https://github.com/vscode-neovim/vscode-neovim#multiple-cursors 

I have tried fresh installed vscode, starting with no extensions installed but vscode neovim, this feature still doesnt work.

Now I am intrigued by why it did not work. Either I am understanding something inaccurately (like `m` in `ma` is actually `Modifier` not character `m`) or there is a problem here (either hidden setting or confusing instructions or deprecated features etc.). The gif in action sadly did not show keypress.

Please help me understand why this feature did not work. Thank you

### Steps To Reproduce

1. Install vscode, fresh, no extension
2. Install neovim, fresh, no plugin
3. Install vscode-neovim extension
4. Try creating some texts

```
abc
abc
abc
abc
abc
```
5. Try the instruction at https://github.com/vscode-neovim/vscode-neovim#multiple-cursors 

### Expected Behavior

It should work like the gif, but it did not

**Comment by xiyaowong** [comment]
Can you provide screen recording? The tests all passed normally, and there should be no bugs.

**Comment by xiyaowong** [comment]
> if this instruction really works, another question is why #97 is still open

Because the current multi-cursor is still relatively simple, it needs to be improved.

**Comment by theol0403** [comment]
From what I can tell, you do *everything* except make a multi-line visual selection and use mi/ma. It just looks like a visual selection because vscode highlights similar words.

**Comment by xiyaowong** [comment]
@luong-komorebi  Try steps in multi-cursor test

https://github.com/vscode-neovim/vscode-neovim/blob/0b3ab8f7d53ba5271dadba54dfa37e90544737b9/src/test/suite/visual-modes.test.ts#L322C1-L375C8
