### ISSUE TITLE
bug: format operator "=" not work

### ISSUE THREAD

**Issue by nokia-git** [vscode-neovim/vscode-neovim#1425]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.1

### Operating system/version

windows10

### Describe the bug

these format operation not work on vscode neovim Version 0.4.4
=ap
=ip
gg=G
...

only visual select then = works ...

### Steps To Reproduce

1. normal mode and cursor at any paragraph, type =ap
2. when type a, it enters into insert mode ...

### Expected Behavior

gg=G should format all text
=ap and =ip should format current paragraph

**Comment by justinmk** [comment]
Works for me. Did you try with "clean" option? This is not a support forum.

**Comment by nokia-git** [comment]
yes, i have tried with empty init.vim and clean vscode.

I found that the key map "=" was changed since vscode neovim 0.4.0
I revert it to 0.3.2, then the operator "=" works well for me.

**Comment by xiyaowong** [comment]
#1422

For now, you can add these to your init.vim
```
function! s:vscodeFormat(...) abort
    if !a:0
        let &operatorfunc = matchstr(expand('<sfile>'), '[^. ]*$')
        return 'g@'
    elseif a:0 > 1
        let [line1, line2] = [a:1, a:2]
    else
        let [line1, line2] = [line("'["), line("']")]
    endif

    call VSCodeCallRange('editor.action.formatSelection', line1, line2, 0)
endfunction

" Bind format to vscode format selection
xnoremap <expr> = <SID>vscodeFormat()
nnoremap <expr> = <SID>vscodeFormat()
nnoremap <expr> == <SID>vscodeFormat() . '_'
```
