### ISSUE TITLE
bug: Buffers were not cleaned up properly

### ISSUE THREAD

**Issue by xiyaowong** [vscode-neovim/vscode-neovim#1427]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.1

### Operating system/version

window 11

### Describe the bug

Buffers were not cleaned up properly.

### Steps To Reproduce

1. Open multiple files.
2. Select one file and close others.
3. Run: `echo nvim_list_bufs()`

You will see the buffers are not cleaned up.

### Expected Behavior

The buffer is properly deleted when the document is closed.

**Comment by fla-t** [comment]
is this the reason i am getting this?

my cursor is not anyone of them, they are phatom cursors appearing on the screen

![image](https://github.com/vscode-neovim/vscode-neovim/assets/61201330/4c0336e4-f5ec-4c5c-a862-f25b8b1e8418)

**Comment by xiyaowong** [comment]
Sometimes I also get this, but I don't pay much attention to it. It May be related to this issue.
