### ISSUE TITLE
feature: Make cursor behaviour <c-e> and <c-y> work like <c-u>

### ISSUE THREAD

**Issue by huibosa** [vscode-neovim/vscode-neovim#1436]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

When using `<c-d>` or `<c-u>`, the cursor will stays in current window view no matter how many lines is move downward or upward, which is not applicable for `<c-e>` and `<c-y>`, the cursor will move out of current window view when you move up/downward too many lines.

I think the behaviour of `<c-e>` or `<c-y>` should work just like it in native neovim, which always stays in current window view.

### Describe the solution you'd like

no solution

### Describe alternatives you've considered

no alternatives

**Comment by xiyaowong** [comment]
For now you can set `vscode-neovim.revealCursorScrollLine` to `true` in `settings.json`

**Comment by huibosa** [comment]
@infinitewhileloop  @xiyaowong Thanks for your generous help, both your advice work good for me. I would try use `vscode-neovim.revealCursorScrollLine` setting cause it seems more consise. And it would be great if the cursor scroll off would check the `scrolloff` in neovim's init.vim or `editor.cursorSurroundingLines` in vscode's settings.json. I've tried both, but none of them works.
