### ISSUE TITLE
bug: flash.nvim search result only show in focused group

### ISSUE THREAD

**Issue by Deuscx** [vscode-neovim/vscode-neovim#1437]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.1

### Operating system/version

windows11 

### Describe the bug

This PR https://github.com/vscode-neovim/vscode-neovim/pull/1417#issuecomment-1705476870, seems to show that the search highlight can show in all groups.  but I tried, it only showed in focused group
I'm using windows11 and Powershell, I don't know what's wrong with the environment
Anyway, Thank you for your time and commitment. I would like to provide more information if needed.

### Steps To Reproduce

1. only use this config 
```lua
vim.g.mapleader = " " -- Make sure to set `mapleader` before lazy so your mappings are correct

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

-- Example using a list of specs with the default options

require("lazy").setup({
  "folke/which-key.nvim",
  { "folke/neoconf.nvim", cmd = "Neoconf" },
  "folke/neodev.nvim",
  {
    "folke/flash.nvim",
    event = "VeryLazy",
    ---@type Flash.Config
    opts = {},
    -- stylua: ignore
    keys = {
      { "s", mode = { "n", "o", "x" }, function() require("flash").jump() end, desc = "Flash" },
      { "S", mode = { "n", "o", "x" }, function() require("flash").treesitter() end, desc = "Flash Treesitter" },
      { "r", mode = "o", function() require("flash").remote() end, desc = "Remote Flash" },
      { "R", mode = { "o", "x" }, function() require("flash").treesitter_search() end, desc = "Treesitter Search" },
      { "<c-s>", mode = { "c" }, function() require("flash").toggle() end, desc = "Toggle Flash Search" },
    },
  },
})
```

2. press `/` to search

https://github.com/vscode-neovim/vscode-neovim/assets/48537979/9cb9b7e8-f11c-4690-8595-d6f18aaad427

### Expected Behavior

search highlight can show in all groups

**Comment by xiyaowong** [comment]
https://github.com/folke/flash.nvim/pull/230
