### ISSUE TITLE
bug: hop.nvim doesn't work correctly when the text contains Korean, Japanese, and Chinese

### ISSUE THREAD

**Issue by 5h5ong** [vscode-neovim/vscode-neovim#1440]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.1

### Operating system/version

MacOS 13.4.1

### Describe the bug

https://github.com/vscode-neovim/vscode-neovim/assets/29355285/bba4071f-9f2d-438a-90db-81545b6a6a67

In alphabets like Korean, Japanese, and Chinese, hop.nvim's jump characters don't display correctly and strangely overlap with existing characters.

I tested this in Neovim with the same text and it worked perfectly. This error only appears in vscode-neovim.

I using this version of hop.nvim: [smoka7/hop.nvim: Neovim motions on speed!](https://github.com/smoka7/hop.nvim)

And I've already tested this things as well: [phaazon/hop.nvim: Neovim motions on speed!](https://github.com/phaazon/hop.nvim)

### Steps To Reproduce

1. type Korean or Japanese or Chinese
2. :HopWord

### Expected Behavior

The jump characters should appear right above the existing text, just like in English.

**Comment by 5h5ong** [comment]
https://github.com/vscode-neovim/vscode-neovim/assets/29355285/5ecf01f2-9291-4a89-ba0c-3bcad4b28c01

After checking to see if the same problem occurs in flash.nvim, it turns out that the result is similar to hop.nvim.

**Comment by xiyaowong** [comment]
This is a long-standing bug that I actually encounter every day, but I haven’t bothered to address it. I will try to fix it during this time.

**Comment by xiyaowong** [comment]
@5h5ong Hello, could you please help test the pr #1449 ? https://github.com/vscode-neovim/vscode-neovim/suites/16175432886/artifacts/923695755

**Comment by 5h5ong** [comment]
@xiyaowong It has been working beautifully so far. Thanks for this great work!
