### ISSUE TITLE
bug: The plugin vim-matchup doesn't work properly

### ISSUE THREAD

**Issue by gaoqiangks** [vscode-neovim/vscode-neovim#1468]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

NVIM v0.10.0-dev-c4f4c7a

### Operating system/version

Windows 11

### Describe the bug

This happens when I edit latex source files.  
  Enter insert mode,  insert `$$`, then exit insert mode. 

Two extra `$$` appeared.  Namely, I get `$$$$`, not `$$`.  

### Steps To Reproduce

1, Open an empty latex file with only 
`\documentclass{amsart}`
`\begin{document}`
`\end{document}`
2,  Between the second and third line, type `$$` and then leave insert mode.
3, This dones't happen every time,  but if you try more than 3  times, it should be reproduced. 

https://github.com/vscode-neovim/vscode-neovim/assets/52161883/dddd11e9-808d-4428-a247-e826ec9ad93f

### Expected Behavior

There shouldn't be extra `$$`.

**Comment by xiyaowong** [comment]
Disable `vim-matchup` in vscode

**Comment by gaoqiangks** [comment]
Sad to see it is closed.  I'll appreciate it if any one knows how to fix it.

**Comment by xiyaowong** [comment]
@gaoqiangks  vim-matchup performs some kind of manipulation or operation on the buffer’s content internally, disrupting the synchronization process of vscode-neovim (Maybe I was wrong. I didn’t thoroughly investigate this plugin). It's difficult to achieve compatibility with such plugins in the case of vscode-neovim synchronization mechanism. By the way, this is not the first issue regarding vim-matchup.
 
You can add this add your vimrc, it should work, but no highlights

```lua
vim.g.loaded_matchit = 1
vim.g.matchup_transmute_enabled = 0
vim.g.matchup_matchparen_enabled = 0
```

**Comment by gaoqiangks** [comment]
> @gaoqiangks vim-matchup performs some kind of operations on the buffer’s content internally, disrupting the synchronization process of vscode-neovim (Maybe I was wrong. I didn’t thoroughly investigate this plugin). It's difficult to achieve compatibility with such plugins in the case of vscode-neovim synchronization mechanism. By the way, this is not the first issue regarding vim-matchup.
> 
> You can add this add your vimrc, it should work, but no highlights
> 
> ```lua
> vim.g.loaded_matchit = 1
> vim.g.matchup_transmute_enabled = 0
> vim.g.matchup_matchparen_enabled = 0
> ```

I see. Thank you very much.

**Comment by xiyaowong** [comment]
@theol0403 I tried again and you’re correct. It’s understandable that these plugins rely on syntax, but I don’t understand why they would change the content.

**Comment by xiyaowong** [comment]
[vscode-neovim/pull/1](https://github.com/xiyaowong/vscode-neovim/pull/1) will rework syntax, so this plugin will be able to run properly.

@gaoqiangks
