### ISSUE TITLE
bug: Inserted text gets doubled when string contains [ or { in files with a filetype

### ISSUE THREAD

**Issue by wqferr** [vscode-neovim/vscode-neovim#1476]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

v0.10.0-dev-1105+g2e9206568 (master a couple weeks ago)

### Operating system/version

Ubuntu 20.04 WSL / Windows 11

### Describe the bug

When inserting a string that contains the characters [, {, ], or }, under the specified conditions, the insert is done again after returning to normal mode, at the current position of the cursor.

### Steps To Reproduce

1. Open a .ts, .lua, .py, or any filetype-set file
2. Enter insert mode
3. Enter any string containing the characters [, {, ], or }
4. Go back to normal mode

### Expected Behavior

String should be inserted only once.

EDITED TO ADD:
I have tested it in raw neovim inside the same WSL system, and the bug does not occur there.

**Comment by xiyaowong** [comment]
@wqferr  Please set neovimClean to true and see if the issue can be reproduced.
https://github.com/vscode-neovim/vscode-neovim/blob/ac7f4e757cced56eff39f10ec5243e47b7c59f0d/package.json#L91C1-L95C19

**Comment by wqferr** [comment]
My apologies, I thought simply removing the path to my init.vim would be enough to make it a clean run. That is not the case, since I cannot reproduce it anymore. I'll have to investigate all my plugins to hope to find the one that causes it... Sorry for the false alarm.

**Comment by wqferr** [comment]
You were correct, it was vim-matchup. Thank you for the suggestion @xiyaowong , and I hope this issue helps someone in the future.

**Comment by wanwiset25** [comment]
I'd just like to add that I was also facing this issue but the inserted string was doubling at all instances.
What solved it was disabling `indent-blankline.nvim` plugin (I am using nvchad) by commenting the lines under plugins/init.lua file.
