### ISSUE TITLE
bug: sometimes there is a leftover VS Code selection in normal / insert modes

### ISSUE THREAD

**Issue by archilkarchava** [vscode-neovim/vscode-neovim#1480]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [ ] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.2

### Operating system/version

MacOS 13.6

### Describe the bug

Sometimes there is a leftover VS Code selection in normal / insert modes.

### Steps To Reproduce

1. Install vim-scripts/ReplaceWithRegister plugin
2. Try to replace with register (gr<text object>)
3. Sometimes there is a leftover VS Code selection in normal / insert modes

https://github.com/vscode-neovim/vscode-neovim/assets/16840190/75313851-cf0e-40ed-b2c1-fbb3d869a56a

The issue is reproducible with keymaps that switch to one of the visual modes to select text and then switch back to normal / insert modes. I was also able to reproduce the problem with `chaoren/vim-wordmotion` and `chrisgrieser/nvim-various-textobjs` plugins.

### Expected Behavior

No leftover selection should be present in normal / insert modes.

I'm using a workaround to resolve the issue:
```lua
vim.api.nvim_create_autocmd({ "ModeChanged" }, {
  desc = "Get rid of leftover VS Code selection",
  pattern = "[vV\x16]:[^vV\x16]",
  callback = function()
    require("vscode-neovim").call("cancelSelection")
  end,
})
```

https://github.com/vscode-neovim/vscode-neovim/assets/16840190/50560437-8ee8-4b60-913f-c79ec2fb6393

**Comment by nokia-git** [comment]
i use this plugin too, but i didn't have this issue.
by the way, what do the key "yii" and "grii" mean ?
i usually use griw, grr... they work very well.

**Comment by xiyaowong** [comment]
From the video, it's not clear what the problem is. The selection always appears after you press the dot. So, what does this dot do? Please make sure the issue can be reproduced when `neovimClean: true`, or pinpoint the specific operation of a plugin.
