### ISSUE TITLE
bug: Double displacement of searched text

### ISSUE THREAD

**Issue by jywu20** [vscode-neovim/vscode-neovim#1487]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.8.2

### Operating system/version

Windows 10

### Describe the bug

When doing selection in visual mode, the selected region somehow appears twice: see the screenshot attached.
<img width="549" alt="1" src="https://github.com/vscode-neovim/vscode-neovim/assets/12218939/7e1ba358-e018-49db-98c1-c060b769bdf1">

This appears in the following cases:
- Entering visual mode by pressing `v`
- Drag-select text using mouse 
- Search mode: see the screenshot:
   <img width="549" alt="1" src="https://github.com/vscode-neovim/vscode-neovim/assets/12218939/1d2494ed-453f-4284-add6-8dc0c18cd700">

The bug appears after VSCode's recent upgrade (1.82.3). Rolling back to older versions however doesn't seem to work. The output of the Neovim extension is the followings each time it's started:
```
E576: Error while reading ShaDa file: last entry specified that it occupies 4 bytes, but file ended earlier
Error detected while processing command line..script c:\\Users\\Thinkpad\\.vscode\\extensions\\asvetliakov.vscode-neovim-0.7.0\runtime\lua\vscode-neovim\force-options.lua:
E5113: Error while calling lua chunk: vim/_meta.lua:36: no such option: 'statuscolumn'
stack traceback:
	[C]: in function 'nvim_get_option_info'
	vim/_meta.lua:36: in function '__index'
	vim/_meta.lua:474: in function 'make_option'
	vim/_meta.lua:536: in function '__newindex'
	...neovim-0.7.0\runtime\lua\vscode-neovim\force-options.lua:42: in function 'forceoptions'
	...neovim-0.7.0\runtime\lua\vscode-neovim\force-options.lua:59: in main chunk
```

### Steps To Reproduce

1. Do any of the operations listed in the bug description

### Expected Behavior

I should just see a highlighted region which is the selected text.

**Comment by jywu20** [comment]
The problem resolves after `nvim` is reinstalled. It seems to be an incompatibility problem between the current version of VSCode extension and an older NVim installation.

**Comment by evantancy** [comment]
which version did you install to fix this? i'm on 0.8.3 and currently getting this error too

**Comment by theol0403** [comment]
Latest nvim should solve the problem.

**Comment by zhuoqun-chen** [comment]
I had the same issue here with `nvim v0.8.0`, gonna try re-install latest nvim release

![image](https://github.com/vscode-neovim/vscode-neovim/assets/73287160/b92e77cc-7576-46ac-8239-4dca1292d2fe)

![image](https://github.com/vscode-neovim/vscode-neovim/assets/73287160/b33737df-26dc-4ff1-9b0d-37704eb50639)

**Comment by jywu20** [comment]
> which version did you install to fix this? i'm on 0.8.3 and currently getting this error too

Hi! I'm on 0.9.2.

**Comment by xiyaowong** [comment]
Always use the latest stable version of neovim. Will compatibility as much as possible in the future.

**Comment by xiyaowong** [comment]
...Including neovim in the extension is absolutely a wrong approach.
