### ISSUE TITLE
auto unfolding during move the cursor up and down

### ISSUE THREAD

**Issue by Hyeong-jin** [vscode-neovim/vscode-neovim#1488]
Type: <b>Bug</b>

1. Folding source code blocks.
2. Move the cursor cross the fold.

Extension version: 0.7.0
VS Code version: Code 1.82.3 (fdb98833154679dbaa7af67a5a29fe19e55c2b73, 2023-10-02T11:09:17.749Z)
OS version: Darwin arm64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|64.00GB (9.01GB free)|
|Process Argv|--crash-reporter-id 94d3b871-1450-4405-9d1c-6e3b8bdcd0d6|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30792226
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
0bi6i642:30841073
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

**Comment by Georift** [comment]
I'm not entirely sure by your report, but I suspect this is a known issue #58

**Comment by Hyeong-jin** [comment]
Thx!! works perfectly!!

After adding the key binding it works fine.

**Comment by Hyeong-jin** [comment]
https://github.com/vscode-neovim/vscode-neovim/issues/58#issuecomment-1316470317

**Comment by xiyaowong** [comment]
recommend my plugin `xiyaowong/fast-cursor-move.nvim`

**Comment by Aneeqasif** [comment]
> recommend my plugin `xiyaowong/fast-cursor-move.nvim`

does it fix the moving over the fold issue in visual mode as well?

**Comment by huypl53** [comment]
You can try method jumping. It avoids opening folds
```text
						*]m*
]m			Go to [count] next start of a method (for Java or
			similar structured language).  When not before the
			start of a method, jump to the start or end of the
			class.  |exclusive| motion.
						*]M*
]M			Go to [count] next end of a method (for Java or
			similar structured language).  When not before the end
			of a method, jump to the start or end of the class.
			|exclusive| motion.
						*[m*
[m			Go to [count] previous start of a method (for Java or
			similar structured language).  When not after the
			start of a method, jump to the start or end of the
			class.  When no '{' is found before the cursor this is
			an error. |exclusive| motion.
						*[M*
[M			Go to [count] previous end of a method (for Java or
			similar structured language).  When not after the
			end of a method, jump to the start or end of the
			class.  When no '}' is found before the cursor this is
			an error. |exclusive| motion.
```

**Comment by nivx18818** [comment]
this would fix the issue while keeping normal behavior when jumping with `10j`
```lua
local map = vim.keymap.set
local vscode = require("vscode")

-- Better up and down
-- Fix folds were automatically opening when navigating with j, k
map("n", "j", function()
  if vim.v.count == 0 then
    vscode.call("cursorDown")
  else
    return "j"
  end
end, { expr = true })

map("n", "k", function()
  if vim.v.count == 0 then
    vscode.call("cursorUp")
  else
    return "k"
  end
end, { expr = true })
```

**Comment by danielnmai** [comment]
> this would fix the issue while keeping normal behavior when jumping with `10j`
> 
> local map = vim.keymap.set
> local vscode = require("vscode")
> 
> -- Better up and down
> -- Fix folds were automatically opening when navigating with j, k
> map("n", "j", function()
>   if vim.v.count == 0 then
>     vscode.call("cursorDown")
>   else
>     return "j"
>   end
> end, { expr = true })
> 
> map("n", "k", function()
>   if vim.v.count == 0 then
>     vscode.call("cursorUp")
>   else
>     return "k"
>   end
> end, { expr = true })

This does not work for me. I had to rely on the VS code keybind settings others put up earlier.

**Comment by nivx18818** [comment]
@danielnmai have you restarted the vscode-neovim extension yet ? the vscode function should work, you can read the README.

**Comment by danielnmai** [comment]
@nivx18818 yes unfortunately it does not work for me, navigating with j/k in normal mode still unfolds code. Here is my[ dotfiles config ](https://github.com/danielnmai/dotfiles/blob/main/.config/nvim/lua/user/vscode_keymaps.lua#L70). The only way it works is modifying the keybindings in VS Code as others mentioned, but that breaks `10j` movement for me.

**Comment by nivx18818** [comment]
@danielnmai that's weird. tried out your config, and everything works just fine. maybe it's conflicting with your vscode keybindings. contact me via [my discord server](https://discord.gg/BmyTQCsq) so i can provide further support.
