### ISSUE TITLE
bug: remapped `i` in visual mode has delay

### ISSUE THREAD

**Issue by llllvvuu** [vscode-neovim/vscode-neovim#1494]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1285+g032ab9d3e

### Operating system/version

macOS 13.4.1

### Describe the bug

When pressing `i` which is remapped in visual mode, there is a delay

### Steps To Reproduce

`vnoremap i :echo("hello world!")<CR>`

### Expected Behavior

No delay

**Comment by theol0403** [comment]
I think this is XY problem. Try using \<CMD> instead of :

**Comment by llllvvuu** [comment]
> I think this is XY problem. Try using <CMD> instead of :

There is delay regardless of whether `:`, `<CMD>`, or Lua function

**Comment by xiyaowong** [comment]
@llllvvuu  Please execute the command `:vmap i` and check for any other mappings.

**Comment by llllvvuu** [comment]
> @llllvvuu Please execute the command `:vmap i` and check for any other mappings.

Looks like this is the issue (text objects), thank you.
