### ISSUE TITLE
bug: Using `gj` and `gk` to do navigate wrapped lines does not preserve horizontal/column position

### ISSUE THREAD

**Issue by InvisibleBacon** [vscode-neovim/vscode-neovim#1498]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.2

### Operating system/version

Windows 10

### Describe the bug

When using the `gj` and `gk` commands to navigate up and down without skipping wrapped lines, the column position is not preserved.

See this gif for an example. NOTE: This example doesn't even involve line wrapping. It still breaks:
![ZdRtHraUIU](https://github.com/vscode-neovim/vscode-neovim/assets/688673/43529007-d77e-4d34-b5af-df9f623e8043)
In this example, the horizontal position remains at the position it was on the second line rather than returning to its original position since the third line is longer.

### Expected Behavior

Here is what happens when I use `gj` in neovim directly:
![s7IPn8GVxP](https://github.com/vscode-neovim/vscode-neovim/assets/688673/e53d4a21-fbec-49b0-bc05-40405b1048fa)

See that the cursor maintains the horizontal position after moving past the shorter line.

### A bit of troubleshooting
I see that these commands are handled using `VSCodeCall('cursorMove')`: 
https://github.com/vscode-neovim/vscode-neovim/blob/68f056b4c9cb6b2559baa917f8c02166abd86f11/vim/vscode-code-actions.vim#L93-L95

I thought this might be a vscode issue with the `cusorMove` command so I added the following test keybinding: 
```json
{
	"key": "ctrl+j",
	"command": "cursorMove",
	"args": {
		"to": "down",
		"by": "wrappedLine"
	}
}
```

With the vscode-neovim extension enabled, this has the same undesirable behavior as hitting `gj`, however, when I disable the extension the desired behavior occurs. So I think this behavior involves the extension.

### Steps To Reproduce

1. Open a file that has varying line lengths.
2. Use the `gj` and `gk` commands to move vertically though the lines.
3. The horizontal position is not preserved.

**Comment by Old-Farmer** [comment]
I am meeting this issue now again. Does Anyone have any idea?

neovim: 0.10.0

vscode: latest stable

vscode neovim: latest release

os: Linux Mint 21.3

**Comment by xiyaowong** [comment]
Try `set ve=onemore`

**Comment by Old-Farmer** [comment]
> Try `set ve=onemore`

Fix the issue, so why?

**Comment by xiyaowong** [comment]
@Old-Farmer I think the answer is in `:h 've'`

The cursor in VSCode is one column to the right of the character instead of on it.

Internal Process:

1. Move the cursor to the position after the last character in VSCode.
2. Sync VSCode cursor position to Nvim.
3. Without `ve=onemore` set, the cursor adjusts to the last character.
4. Sync Nvim cursor position back to VSCode.
5. The state maintained by VSCode cursor commands is disrupted.

**Comment by Old-Farmer** [comment]
> @Old-Farmer I think the answer is in `:h 've'`
> 
> The cursor in VSCode is one column to the right of the character instead of on it.
> 
> Internal Process:
> 
> 1. Move the cursor to the position after the last character in VSCode.
> 2. Sync VSCode cursor position to Nvim.
> 3. Without `ve=onemore` set, the cursor adjusts to the last character.
> 4. Sync Nvim cursor position back to VSCode.
> 5. The state maintained by VSCode cursor commands is disrupted.

Thank you for your explanation！
