### ISSUE TITLE
Dead keys not working (caret, tilde)

### ISSUE THREAD

**Issue by pumpkinlink** [vscode-neovim/vscode-neovim#151]
I type on a Brazillian ABNT 2 layout keyboard, but this can be reproduced on any layout with dead keys, including "US International w/ dead keys" for instance.

On terminal vim, pressing the `^` key twice should take me to start of line, and `~` twice should switch character case. Instead of that, the expected action occurs but after that the corresponding character (~ or ^) is printed on current position and substitutes the character on that position. My guess is that it has something to do with dbus or something

**Comment by asvetliakov** [comment]
Can you try to set in vscode settings `"keyboard.dispatch": "keyCode"` ?

**Comment by pumpkinlink** [comment]
> Can you try to set in vscode settings `"keyboard.dispatch": "keyCode"` ?

switched this setting and restarted VSCode, makes no difference at all

**Comment by jbsilva** [comment]
The same was happening with me on a Arch Linux + KDE clean install.
I then installed Fcitx5 and all started working.

**Comment by leonardopn** [comment]
> O mesmo estava acontecendo comigo em uma instalação limpa do Arch Linux + KDE. Então instalei o Fcitx5 e tudo começou a funcionar.

This solution worked for me on Arch, too.

`sudo pacman -S fcitx5`
