### ISSUE TITLE
bug: MainController: Neovim exited with code: 139

### ISSUE THREAD

**Issue by edicon** [vscode-neovim/vscode-neovim#1518]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

NVIM v0.10.0-dev

### Operating system/version

Windows 10 ( WSL 2 )

### Describe the bug

MainController: Neovim was disconnected -> MainController: Neovim exited with code: 139

![neovim-error](https://github.com/vscode-neovim/vscode-neovim/assets/527522/237a6d1e-5a18-4599-bdc0-ff06cee7837b)

### Steps To Reproduce

 "vscode-neovim.useWSL": true,
  "editor.scrollBeyondLastLine": false,
  "vscode-neovim.neovimExecutablePaths.darwin": "/usr/local/bin/nvim",
  "vscode-neovim.neovimInitVimPaths.darwin": "$HOME/.config/nvim/init.vim",
  "vscode-neovim.neovimExecutablePaths.linux": "/usr/bin/nvim",
  "vscode-neovim.neovimInitVimPaths.linux": "$HOME/.config/nvim/init.vim",
  "vscode-neovim.neovimExecutablePaths.win32": "C:\\Program Files\\Neovim\\bin\\nvim.exe",
  "vscode-neovim.neovimInitVimPaths.win32": "%userprofile%\\AppData\\Local\\nvim\\init.vim",
  "vscode-neovim.logLevel": "debug",
  "vscode-neovim.logOutputToConsole": true,
  "vscode-neovim.logPath": "/tmp/vscode-nvim",

### Expected Behavior

should run extension using WSL 2

**Comment by xiyaowong** [comment]
Simply set useWSL to true, then remove any other redundant binary paths and configure the path.
