### ISSUE TITLE
Text selection breaks the rendering and scrambles the selected text 

### ISSUE THREAD

**Issue by mzdravkov** [vscode-neovim/vscode-neovim#1524]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

NVIM v0.9.0-dev

### Operating system/version

Windows (also in WSL)

### Describe the bug

Hello!

When I select text in visual mode the selected text gets scrambled in a weird way. Here's a video, because I find it a bit hard to explain:

https://github.com/vscode-neovim/vscode-neovim/assets/1406355/48631559-19c5-4edc-addc-91b4a0b18b8e

The problem can still be reproduced after disabling all other extensions and removing my `init.lua` config.
I tried using different versions of the vscode-neovim extension and the issue appears in version `0.7.0`. In version `0.6.1` it works without issues.

I can also see that there are some errors in the vscode-neovim output window. Those appear with the loading of the extension and not when I try to select:

```
Error detected while processing pre-vimrc command line..script /mnt/c/Users/mihai/.vscode/extensions/asvetliakov.vscode-neovim-0.9.0/vim/vscode-neovim.vim:
line  116:
E5108: Error executing lua ...ode-neovim-0.9.0/runtime/lua/vscode-neovim/highlight.lua:73: attempt to call field 'nvim_exec2' (a nil value)
stack traceback:
	...ode-neovim-0.9.0/runtime/lua/vscode-neovim/highlight.lua:73: in function 'setup_syntax_groups'
	...ode-neovim-0.9.0/runtime/lua/vscode-neovim/highlight.lua:122: in main chunk
	[C]: in function 'require'
	...liakov.vscode-neovim-0.9.0/runtime/lua/vscode-neovim.lua:5: in main chunk
	[C]: in function 'require'
	[string ":lua"]:1: in main chunk
Error detected while processing command line..script /mnt/c/Users/mihai/.vscode/extensions/asvetliakov.vscode-neovim-0.9.0/runtime/lua/vscode-neovim/force-options.lua:
E5113: Error while calling lua chunk: vim/_meta.lua:0: no such option: 'statuscolumn'
stack traceback:
	[C]: in function 'nvim_get_option_info'
	vim/_meta.lua: in function '__index'
	vim/_meta.lua: in function ''
	vim/_meta.lua: in function '__newindex'
	...neovim-0.9.0/runtime/lua/vscode-neovim/force-options.lua:39: in function 'forceoptions'
	...neovim-0.9.0/runtime/lua/vscode-neovim/force-options.lua:51: in main chunk
Error executing vim.schedule lua callback: ...ode-neovim-0.9.0/runtime/lua/vscode-neovim/highlight.lua:73: attempt to call field 'nvim_exec2' (a nil value)
stack traceback:
	...ode-neovim-0.9.0/runtime/lua/vscode-neovim/highlight.lua:73: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...ode-neovim-0.9.0/runtime/lua/vscode-neovim/highlight.lua:73: attempt to call field 'nvim_exec2' (a nil value)
stack traceback:
	...ode-neovim-0.9.0/runtime/lua/vscode-neovim/highlight.lua:73: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...ode-neovim-0.9.0/runtime/lua/vscode-neovim/highlight.lua:73: attempt to call field 'nvim_exec2' (a nil value)
stack traceback:
	...ode-neovim-0.9.0/runtime/lua/vscode-neovim/highlight.lua:73: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...ode-neovim-0.9.0/runtime/lua/vscode-neovim/highlight.lua:73: attempt to call field 'nvim_exec2' (a nil value)
stack traceback:
	...ode-neovim-0.9.0/runtime/lua/vscode-neovim/highlight.lua:73: in function ''
	vim/_editor.lua: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

This is information about the VSCode installation (I also tried downgrading the version, but it didn't help).
```
Version: 1.83.0 (user setup)
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:12:16.321Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
```

### Steps To Reproduce

1. Select text by entering visual mode, visual line mode or visual block mode.
2. Move the cursor around to select some text.

### Expected Behavior

Selected text should be rendered in the same way as when it's not selected.

**Comment by xiyaowong** [comment]
Always search existing issues, please.

https://github.com/vscode-neovim/vscode-neovim/issues?q=is%3Aissue++no+such+option%3A+%27statuscolumn%27+

**Comment by th0rgall** [comment]
Also here: **upgrade your nvim**, that fixed it for me and others.

Canonical issue: https://github.com/vscode-neovim/vscode-neovim/issues/1487

**Comment by mzdravkov** [comment]
I did try to search the existing issues, but didn't find those. Sorry for the trouble!
Anyway, updating nvim worked. Thank you!

**Comment by xiyaowong** [comment]
Version checks have been optimized, and future version requirements prompts will be more accurate.
