### ISSUE TITLE
bug: fast typing impossible due to race condition / performance

### ISSUE THREAD

**Issue by ogwhic** [vscode-neovim/vscode-neovim#1534]
Edit: The "race condition"/"poor performance" in the title is just my best guess at what's going on. I really have no idea...

'### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.2

### Operating system/version

Windows 11

### Describe the bug

Unable to determine if this is a vscode-neovim specific issue, code completion or combination of the two.

I have both NeoVim and code completion/intellisense/whatever via the C# extension enabled. I'm not sure exactly what's happening but when typing quickly the autocomplete UI appears and disappears and some combination of NeoVim action and autocomplete action both trigger in response to pressing return or esc or some other key.

The result is often the code I've just typed being inserted twice with some corrupt attempt at autoformatting or just random code from the autocomplete being vomited into the text editor.

I'm spending more time correcting the damaged caused than actual coding.

Because it only happens when I'm typing quickly it's difficult to figure out exactly what's going wrong. Just code vomit everywhere.

It "feels" like some kind of race condition/fight is taking place between neovim and the autocomplete, with both being triggered by the same key press (e.g., return to start a new line being hijacked by autocomplete incorrectly, or an internal buffer of neovim being dumped multiple times into the document).

### Steps To Reproduce

1. Install VSCode
2. Install NeoVim
3. Install vscode-neovim
4. Install C# Dev Kit extension
5. Disable all but the 'C#' extension among those installed by step 4 (optional)
6. Try touch typing code in a C# file
7. Observe a combination of random code and duplicate copies of what you just typed being dumped into the editor as you type

### Expected Behavior

Text I type and intentional autocomplete/snippets/whatever should be inserted into the editor. Random code and duplicate copies of what I type should not.

**Comment by theol0403** [comment]
Not sure what's going on... vscode-neovim should really not be doing anything during insert mode. My only guess is somehow the document change sync is stepping on your typing.

**Comment by c0z0** [comment]
I'm also seeing this. Sometimes changes made in insert mode are duplicated. I couldn't manage to find a way to reliably reproduce it though. It happens about once every five inserts.

**Comment by fpiemontese-dku** [comment]
Similar issue on my end, sometimes when exiting insert mode any added text is duplicated. On my side, it happens very frequently / most of the time.

**Comment by d3chapma** [comment]
I am having a similar issue to what is described here. I have a very repeatable case. Happens every single time I have tried. Here is a screen recording:

https://github.com/vscode-neovim/vscode-neovim/assets/286092/be1628cb-0737-46df-99cc-603a8a76a361

When I entered insert mode I started typing from 4 lines above. When I finish what I am doing, I hit ESC. It does feel like there is a race condition related to how soon I press ESC, though I have a decent window. It is as though if I wait long enough for the LSP to check and highlight everything then I can hit ESC safely. Otherwise, I get duplication.

It is very hard to make this happen if I am just inserting a single line of code then going back to Normal mode.

Hope that helps!

**Comment by theol0403** [comment]
@d3chapma can you reproduce with empty init.vim?

**Comment by d3chapma** [comment]
Hmm... Initial test indicates no. That seems to fix it. I will try running with an empty config and see how I fair. 

I had noticed that suggestion in the docs but had forgotten to do it. Thanks!

**Comment by c0z0** [comment]
I built the app myself from master and that seemed to have fixed the issue. Maybe #1581 fixed it? I'm also using custom init.vim, with plugins

**Comment by xiyaowong** [comment]
Interesting. If someone has this problem, please share your nvim config if possible. This may not be a matter of speed.

**Comment by richyk1** [comment]
I had the same issue. It seems that my `init.lua` config is somehow conflicting with the Neovim extension and VSCode. Not sure how, but I managed to solve this issue by opening and checking the `Neovim Clean` option in VSCode user settings.

<details><summary>Screenshot of the relevant setting that I changed</summary>
<p>

![image](https://github.com/vscode-neovim/vscode-neovim/assets/8665991/204824c7-dd16-47a2-b9fe-a6921a3c2ec4)


</p>
</details>

**Comment by theol0403** [comment]
Issues must be reproduced with empty init.lua.
