### ISSUE TITLE
bug: overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by nokia-git** [vscode-neovim/vscode-neovim#1549]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.4

### Operating system/version

win10

### Describe the bug

V select the text with five lines, and < to de-indent
Then the error window occur
Error applying neovim edits, error: Overlapping ranges are not allowed!

### Steps To Reproduce

V select the text with five lines, and < to de-indent
Then the error window occur
Error applying neovim edits, error: Overlapping ranges are not allowed!

```c
					}
					uart_status = 3;
				}
				break;
			}
```

### Expected Behavior

no error occur, and de-indent the selected text.

**Comment by xiyaowong** [comment]
It seems like you haven't searched for existing issues, but you’ve checked the box.
![image](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/8b425386-db36-47e8-a4f7-6483f5fe4a45)

Dup of #1068

https://github.com/vscode-neovim/vscode-neovim/issues?q=is%3Aissue+is%3Aopen+overlapping+ranges
