### ISSUE TITLE
bug: Default keybinding ctrl+Escape doesn't work on Windows because it's used to open Start menu

### ISSUE THREAD

**Issue by JohnEricson** [vscode-neovim/vscode-neovim#1554]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.2 

### Operating system/version

Windows 10

### Describe the bug

As [default in the extension Ctrl+Escape is bound to workbench.action.focusActiveEditorGroup](https://github.com/vscode-neovim/vscode-neovim/blob/c786074df01bc02d52856620d0da2db60659ae1a/scripts/keybindings/5%20widgets.cjs#L213). This doesn't work on Windows because as [default in Windows this same keybinding is bound to open the Start menu](https://support.microsoft.com/en-us/windows/keyboard-shortcuts-in-windows-dcc61a57-8ff0-cffe-9796-cb9706c75eec).

So when I press Ctrl+Esc in VS Code it opens the Windows start menu instead of changing focus to my active editor in VS Code. I worked around this by changing my keyboard shortcut. But it would be appreciated if we could have a better default for this out-of-the-box.

### Steps To Reproduce

1. Have focus on a terminal.
2. Press keyboard shortcut Ctrl+Esc.
3. Now the Windows  Start menu is opened, instead of changing the focus in VS Code to the active editor.

### Expected Behavior

I expect the default keyboard shortcut shipped in the extension to work out-of-the-box. So the keyboard shortcut should change focus to active editor.

**Comment by xiyaowong** [comment]
> I expect the default keyboard shortcut shipped in the extension to work out-of-the-box

No, what if users from other systems are accustomed to this shortcut key? What if users from other systems encounter similar issues after changing to another shortcut key? Obviously, it is impossible to satisfy everyone out of the box. Customizing shortcuts is not a troublesome thing.

Remove the default:

```json
  {
    "key": "ctrl+escape",
    "command": "-workbench.action.focusActiveEditorGroup",
    "when": "terminalFocus"
  }
```
