### ISSUE TITLE
bug: setting affinity clashes with clangd outputs in status bar

### ISSUE THREAD

**Issue by lakshits11** [vscode-neovim/vscode-neovim#1572]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

NVIM v0.9.4

### Operating system/version

Windows 11

### Describe the bug

i have two extensions installed only:
1. Your
2. `llvm-vs-code-extensions.vscode-clangd`

So if i set affinity of your extension as 1, then in status bar, both clangd and vscode neovim extension fight for showing current status in status bar. for example clangd tries to show this

<img width="171" alt="image" src="https://github.com/vscode-neovim/vscode-neovim/assets/54276661/93b025ce-efb2-44cb-8a31-9fed2b94dbd9">

and vscode neovim wants to show mode status (insert/visual etc)

they both show their status alternatively each getting only 10ms time (i suppose, but its very fast)
also vscode neovim option is not visible in status bar options when above setting is set.

<img width="296" alt="image" src="https://github.com/vscode-neovim/vscode-neovim/assets/54276661/49afede4-c20d-4146-90b6-9ab17c4ba4b8">

if i disable clangd extension option, then vscode neovim mode status is also not shown

but when i set clangd extension affinity also to 1 alongside your extension's, everythings back to normal. i can see both clangd and vscode neovim options in status bar.

### Steps To Reproduce

1. install your extension and clangd extension.
2. set affinity of ur extension to 1 and restart vscode.
3. open a cpp file 
4. type anything in it for example `#inc`
5. in below status bar you will see both clangd and neovim wanting to show their status.

### Expected Behavior

i felt the problem is in your extension and not clangd is because clangd is still shown in status bar and yours is not. 

So please fix it.
Its literally the best extension on neovim in vscode i have used.

**Comment by xiyaowong** [comment]
Need screen recording

**Comment by lakshits11** [comment]
have you set the affinity ? I dont know why I was getting that issue? Below is my settings.json

```jsonc
{
    "files.autoSave": "afterDelay",
    "vscode-neovim.useCtrlKeysForInsertMode": false,
    "extensions.experimental.affinity": {
        "llvm-vs-code-extensions.vscode-clangd":0,
        "asvetliakov.vscode-neovim": 1,
    },
},
```

**Comment by xiyaowong** [comment]
Yes

**Comment by Old-Farmer** [comment]
Same as me
