### ISSUE TITLE
bug: Start of visual selection of previous group becomes start of selection in focused group

### ISSUE THREAD

**Issue by trkoch** [vscode-neovim/vscode-neovim#1577]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.1

### Operating system/version

macOS 13.6

### Describe the bug

When having multiple groups (e.g. left and right split), and while in visual mode in one group (left), switching to the other group (right) by command (`ctrl+w l`) or the mouse _sometimes_ carries over the start of the selection of the first group (left).

Situations where this issue might surface:
* With a previous selection in the left group, when selecting text in right group
* When globally searching for a string (e.g. `function` in `*.js`) and jumping through matches (found occurrences create a selection)

### Steps To Reproduce

1. Open a file (e.g. left group)
2. Open another file in another group (e.g. right group)
3. In left group, place cursor in line `10`
4. In right group, place cursor to line `20` and first non-whitespace column (`y`)
5. In left group, start a visual block-wise selection (`V`) (line 10 is selected)
6. In right group, place cursor to line `20` and column `y`

There are now _two_ visual selections:
* Line 10 in left group
* Line 10 to 20 up to column `y` in right group

<img width="1021" alt="image" src="https://github.com/vscode-neovim/vscode-neovim/assets/73974/a5359854-842e-4641-891e-437e873dc3b0">

### Expected Behavior

The start of the selection of the left group should not carry over to the right group.

I tracked down where the line/column of the previous group is retrieved from vim (see `this.client.callFunction("getpos", ["v"]);` in line `425`):

https://github.com/vscode-neovim/vscode-neovim/blob/21e9da53f073538d838dd97bcb421903f7824a94/src/cursor_manager.ts#L416-L432

(This is after the active buffer/window in vim is changed to match the active editor of Vscode, so I would expect it to equal the current cursor position and not the start of the previous selection).

However, it seems the (Vscode) selection is established before and this is only where the fake selection is updated (or synced) – I verified by placing a 1 second timeout before the code in question. Ultimately, I lost track trying to determine why the selection starts at the position of the previous group.

The easiest solution may be to cancel visual mode on changing groups. In the example given, this would mean no visual selection at all and the cursor in right group being placed at `y` while in normal mode. This appears to match the behavior in `nvim` itself.

```diff
diff --git a/src/buffer_manager.ts b/src/buffer_manager.ts
index 11021b9..715f9cd 100644
--- a/src/buffer_manager.ts
+++ b/src/buffer_manager.ts
@@ -575,6 +575,12 @@ export class BufferManager implements Disposable {
         logger.debug(`Setting active editor - viewColumn: ${activeEditor.viewColumn}, winId: ${winId}`);
         await this.main.cursorManager.updateNeovimCursorPosition(activeEditor, activeEditor.selection.active);
         try {
+            if (this.main.modeManager.isVisualMode) {
+                logger.debug(
+                    `DEBUG: Cancel visual mode to prevent selection from previous editor to carry over active editor`,
+                );
+                await this.client.input("<Esc>");
+            }
             await this.client.request("nvim_set_current_win", [winId]);
         } catch (e) {
             logger.error(`${(e as Error).message}`);
```

**Comment by xiyaowong** [comment]
In fact, this is similar to the behavior of nvim, where ctrl+w and nvim_set_current_win behave differently. In practical terms, exiting visual mode is more intuitive.

**Comment by xiyaowong** [comment]
![test](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/f62fd29a-e6bc-4dc4-a62b-bd0c50bfdc9f)

**Comment by trkoch** [comment]
> ctrl+w and nvim_set_current_win are different.

Interesting!

Note the extension does not invoke `ctrl+w` (vim), but instead overrides the window [mappings](https://github.com/vscode-neovim/vscode-neovim/blob/21e9da53f073538d838dd97bcb421903f7824a94/vim/vscode-window-commands.vim#L90-L98) to delegate to `workbench.action.navigate<Direction>` (Vscode).

**Comment by trkoch** [comment]
Related https://github.com/vscode-neovim/vscode-neovim/pull/1050#issuecomment-1276529909

**Comment by trkoch** [comment]
@theol0403 Do you have a hunch?

> However, it seems the (Vscode) selection is established before and this is only where the fake selection is updated (or synced) – I verified by placing a 1 second timeout before the code in question. Ultimately, I lost track trying to determine why the selection starts at the position of the previous group.

**Comment by theol0403** [comment]
> @theol0403 Do you have a hunch?

Is there an issue remaining that wasn't fixed by your PR?

**Comment by trkoch** [comment]
No. Not that I’m aware of. Merely asking out of curiosity.
