### ISSUE TITLE
bug: The naming prompt for VS Code refactoring tools isn't shown when in visual mode

### ISSUE THREAD

**Issue by doppio** [vscode-neovim/vscode-neovim#1579]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

NVIM v0.9.2

### Operating system/version

macOS Sonoma 14.0

### Describe the bug

When the user makes a selection using neovim's visual mode and then performs a refactoring with VS Code's tools (for example, to extract some code to a new function), the prompt that VS Code normally displays to enter a new name is not shown.

The naming prompt _not_ being displayed while in visual mode:
![screenshot_u7qaCRa0](https://github.com/vscode-neovim/vscode-neovim/assets/1127641/a0b5ac74-035c-4ea0-b492-79ceac3f1b15)

The naming prompt correctly being displayed, when entering insert mode before using the refactor tool:
![screenshot_b0wp2cbi](https://github.com/vscode-neovim/vscode-neovim/assets/1127641/b804dd38-8948-4292-8077-2e9cae7273b4)

### Steps To Reproduce

1. Select some code in visual mode (for example, select the current line with `shift + v`)
2. Activate VS Code quick actions (`cmd + .`)
3. Choose a refactoring option that requires a new name, like extracting the code to a new function
4. Notice that the new entity is created with the placeholder name and must be renamed manually

### Expected Behavior

When performing a refactor that creates a new entity while in visual mode, the naming prompt should appear and allow the user to enter a name, as it currently does when in insert mode.

**Comment by xiyaowong** [comment]
Please refer to the code I gave in #1351

There is no way to detect the current mode of vscode, and all these operations are asynchronous, so the only way is to execute the command in insert mode.

**Comment by doppio** [comment]
Thanks for that context, I'll take a look!
