### ISSUE TITLE
Incremental Search does not jump to show search matches

### ISSUE THREAD

**Issue by GregoryTravis** [vscode-neovim/vscode-neovim#1587]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.2

### Operating system/version

MacOS 12.6.3

### Describe the bug

When searching for something offscreen, incremental search does not jump to the first match, but displays a highlighted copy of the search text in the wrong place. (As if it's highlighting it where it thinks it should be if it jumped, but it didn't jump.)

### Steps To Reproduce

1. :set inccommand=nosplit (from https://github.com/vscode-neovim/vscode-neovim/issues/329)
2. go to the top of the file
3. search for something offscreen

### Expected Behavior

I expect the window to scroll to show the first match, as I type.

**Comment by xiyaowong** [comment]
Please supplement the title.

**Comment by xiyaowong** [comment]
Maybe you need to write a title

**Comment by xiyaowong** [comment]
#1149 
#1555
