### ISSUE TITLE
feature: Remove escape command title to make screencast mode nicer

### ISSUE THREAD

**Issue by awilkins** [vscode-neovim/vscode-neovim#1588]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

When you use `vscodevim`, keys like `Escape` are printed as `Escape` in the VS Code screencast mode.

When you use `vscode-neovim`, `Escape` prints as 

> Neovim send escape key to neovim, or other keys that will exit insert mode <kbd>Escape</kbd>

(cut off because of screen size)

This kinda spoils the screencast.

### Describe the solution you'd like

The easiest way to "fix" this seems to be to set the title property for the `neovim.escape` command defined in `package.json` to an empty string ; while this isn't perfect, I can't see people searching this command out in the palette.

### Describe alternatives you've considered

I don't know if there's any way to change the title at runtime or if this would provide a better outcome (like the command still having it's title in the palette but printing it in screencast mode), or a way to return an empty string just for screencasts.

**Comment by xiyaowong** [comment]
```jsonc
{
  "screencastMode.keyboardOptions": {
    "showKeys": true,
    "showKeybindings": true,
    "showCommands": false,
    "showCommandGroups": false,
    "showSingleEditorCursorMoves": true
  }
}
```
