### ISSUE TITLE
Focus does not shift to the change window

### ISSUE THREAD

**Issue by tresuke** [vscode-neovim/vscode-neovim#1594]
Type: <b>Bug</b>

When I run "Open Changes" under "Source Control", the focus does not shift to the change window.

Extension version: 0.9.1
VS Code version: Code - Insiders 1.85.0-insider (c97d74fba0df6c8da3e0e469a4f37c4ed9612682, 2023-11-07T05:34:56.802Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (8.51GB free)|
|Process Argv|--crash-reporter-id a81ead34-72ea-40d6-9da0-ba2f170baa1c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
py29gd2263:30784851
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
vscrp:30624060
2i9eh265:30646982
showlangstatbar:30737417
pythonfmttext:30716741
fixshowwlkth:30771523
showindicator:30805243
pythongtdpath:30726887
i26e3531:30792625
pythonnosmt12:30779711
pythonidxpt:30768918
pythonnoceb:30776497
dsvsc013:30777762
dsvsc014:30777825
pythonmpswarning:30859870
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30871582
pyreplss1:30879911
pythonmypyd1:30859725
pythoncet0:30859736
pythontbext0:30879054
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
aa_t_chat:30882232

```

</details>

**Comment by xiyaowong** [comment]
Need screen record

**Comment by tresuke** [comment]
If the extension is enabled, the change window opens momentarily and is immediately closed. If the extension is disabled, it works correctly.

https://github.com/vscode-neovim/vscode-neovim/assets/24380877/77a029cb-d214-4336-9b51-3edfee1590a1

**Comment by xiyaowong** [comment]
I have also encountered this problem

**Comment by trkoch** [comment]
Strangely, I cannot reproduce this.

**Comment by tresuke** [comment]
Maybe it's just Windows? It worked fine on Ubuntu (on VirtualBox). Maybe there are other conditions to reproduce this...

**Comment by tresuke** [comment]
Mmmm, the latest insider build of VSCode no longer reproduces it!
On the other hand, the normal version (1.84.2) reproduces it.
Maybe it's a problem on the VSCode side...




```
Version: 1.85.0-insider
Commit: f346494c77e1245505e53a2ddcab3bfb4ee52e08
Date: 2023-11-09T05:35:49.782Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code-Insiders/1.85.0-insider Chrome/114.0.5735.289 Electron/25.9.2 Safari/537.36
```

```
Version: 1.84.2
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:51:52.184Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.84.2 Chrome/114.0.5735.289 Electron/25.9.2 Safari/537.36
```

**Comment by xiyaowong** [comment]
@tresuke  Maybe. I usually encounter this problem and can reproduce it after this issue. But now I can’t reproduce it again. :joy:

**Comment by tresuke** [comment]
I usually use an insider build and so far it seems to have stopped reproducing.
Best if we can find the cause and it doesn't reoccur in the future...

**Comment by xiyaowong** [comment]
The fact is, I can't reproduce the issue in Version 1.84.2 either

**Comment by xiyaowong** [comment]
Okay, just now I reproduced the issue in Version: 1.85.0-insider.
