### ISSUE TITLE
bug: Disable keybind in keybindings.json is not working.

### ISSUE THREAD

**Issue by mttbx** [vscode-neovim/vscode-neovim#1595]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1488+g319803822

### Operating system/version

ubuntu

### Describe the bug

This is the config:  
  ```
{
    "command": "-vscode-neovim.send",
    "key": "ctrl+a"
  },
  {
    "command": "-vscode-neovim.send",
    "key": "ctrl+c"
  },
  {
    "command": "-vscode-neovim.send",
    "key": "ctrl+v"
  },
  {
    "command": "-vscode-neovim.send",
    "key": "ctrl+x"
  },
  {
    "command": "-vscode-neovim.send",
    "key": "ctrl+a"
  },
  {
    "command": "-vscode-neovim.send",
    "key": "ctrl+f"
  },
```

### Steps To Reproduce

1. install vscode neovim v0.2.0 
2. add the config list before in the keybindings.json
3. try it

### Expected Behavior

ctrl-a, ctrl-c... not worked as expected.

**Comment by xiyaowong** [comment]
The when expression is required

**Comment by trkoch** [comment]
See https://github.com/vscode-neovim/vscode-neovim#normal-mode-control-keys

**Comment by mttbx** [comment]
@xiyaowong @trkoch not working.

**Comment by xiyaowong** [comment]
@mttbx  Try ![image](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/7ab7f4e2-0628-4898-a87b-09de4fedd6a5)

**Comment by mttbx** [comment]
nice, problem solved.
