### ISSUE TITLE
bug: 100 % CPU load after VSCode reload

### ISSUE THREAD

**Issue by elagil** [vscode-neovim/vscode-neovim#1598]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

v0.9.4

### Operating system/version

Windows 11 with WSL2 (Ubuntu 22.04)

### Describe the bug

With an empty `init.lua`, and after reloading the VSCode window (`Developer: Reload Window`), I get an `nvim` process that runs at 100 % load. Every time I reload, one process is added. They have to be killed manually. The same thing seems to happen when I just open a different directory in the VSCode window - it might behave similar to a reload.

This happens with or without `affinity` enabled.

The only active extensions are the `WSL` remote connector, and `VSCode Neovim`.

### Steps To Reproduce

1. Start VSCode
2. Reload Window
3. Process with high load exists

### Expected Behavior

No additional load after reloading the window.

**Comment by trkoch** [comment]
Can you verify the issue persist with `vscode-neovim.neovimClean` enabled?

**Comment by elagil** [comment]
It seems like it does not persist with this enabled. What does that mean?

**Comment by elagil** [comment]
I deleted my `nvim` `state` directory, and that seems to fix it. Sorry for the noise.
Closing for now.
