### ISSUE TITLE
feature: Make reading nvim config opt-in

### ISSUE THREAD

**Issue by trkoch** [vscode-neovim/vscode-neovim#1599]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

Here comes a somewhat controversial proposal. As we know, many issues are related to the nvim config not being "compatible" to vscode-neovim.

### Describe the solution you'd like

Starting with version 1.0, switch the default of `vscode-neovim.neovimClean`.  First time users are not put off by a broken installation. Once they wish to use the full power of their nvim installation, they can toggle `neovimClean`. That said, we should probably consider renaming to `neovimConfig` (or similar) with `false` being the default.

### Describe alternatives you've considered

* Log a warning on first startup
  * Can easily be skipped
* Recommend to start with `neovimClean` in `README.md`
   *  Requires users to read from front to back
 * Add a very prominent section in `README.md`
   * It is already prominent in the second section, just a page scroll away

### Additional context

Defaults are powerful. The idea is to nudge users to start with a minimal configuration.

What are your thoughts?

**Comment by xiyaowong** [comment]
>  * Add a very prominent section in `README.md`
>    * It is already prominent in the second section, just a page scroll away
> 

I suggest using this solution. It should also be stated in the **issue template**.

**Comment by justinmk** [comment]
Prominent README + one-time info message is probably the best compromise. 

I agree that this can be a source of issues, otoh reversing it will likely result in confused issues from the opposite side. And the delta of unsupported Nvim plugins is pretty small thanks to the amazing work by @theol0403 and @xiyaowong , I enabled almost all of my plugins with vscode-neovim.

**Comment by justinmk** [comment]
> In addition, it is difficult for us to be compatible with all plugins, but in another way, plugins can use the API provided by vscode-neovim to be compatible with vscode-neovim.

I strongly suggest we don't continue in that direction. Either we support Nvim plugins or we don't. Introducing a quasi-framework,

1. is a maintenance burden
2. distracts both plugin authors and vscode-neovim contributors from the actual goal of support Nvim plugins in vscode

**Comment by xiyaowong** [comment]
This suggestion, at present, does not make much sense. Issue templates and readme have been improved.
