### ISSUE TITLE
bug: jk will make file modified

### ISSUE THREAD

**Issue by mttbx** [vscode-neovim/vscode-neovim#1600]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1488+g319803822

### Operating system/version

ubuntu

### Describe the bug

jk will make file modified

### Steps To Reproduce

1. into insert mode
2. hit jk

### Expected Behavior

observe that the file is modified

**Comment by xiyaowong** [comment]
https://github.com/vscode-neovim/vscode-neovim#composite-escape-keys

**Comment by mttbx** [comment]
I used composite escape keys to set jk as esc, the problem is the same.

**Comment by theol0403** [comment]
Not fixable
