### ISSUE TITLE
forward search `/` incorrectly matches for long line

### ISSUE THREAD

**Issue by kwonoj** [vscode-neovim/vscode-neovim#161]
Repro steps

- create long line text file

i.e single-like package.json like attached in details
<details>
{"name":"@reactivex\/rxjs","version":"7.0.0-alpha.0","description":"Reactive Extensions for modern JavaScript","main":"index.js","sideEffects":false,"config":{"commitizen":{"path":"cz-conventional-changelog"}},"lint-staged":{"*.js":["eslint --fix","git add"],"*.ts":["tslint --fix","git add"]},"scripts":{"precommit":"lint-staged","commitmsg":"validate-commit-msg","build_all":"npm-run-all clean_dist copy_sources build_cjs build_esm5 build_esm2015 build_esm5_for_rollup build_umd build_types generate_packages","build_cjs":"npm-run-all clean_dist_cjs compile_dist_cjs","build_esm5":"npm-run-all clean_dist_esm5 compile_dist_esm5","build_esm5_for_rollup":"npm-run-all clean_dist_esm5_for_rollup compile_dist_esm5_for_rollup && mkdirp dist\/esm5_for_rollup\/node_modules","build_esm2015":"npm-run-all clean_dist_esm2015 compile_dist_esm2015","build_types":"npm-run-all clean_dist_types compile_dist_types","build_closure_core":"node .\/tools\/make-closure-core.js","build_global":"npm-run-all clean_dist_global build_esm5_for_rollup && mkdirp .\/dist\/global && node .\/tools\/make-umd-bundle.js && npm-run-all build_closure_core clean_dist_esm5_for_rollup","build_umd":"npm-run-all clean_dist_global && mkdirp .\/dist\/global && node .\/tools\/make-umd-bundle.js && npm-run-all build_closure_core","build_perf":"webdriver-manager update && npm-run-all build_cjs build_global perf","build_spec":"npm-run-all build_cjs generate_packages","build_spec_full":"npm-run-all build_spec","build:spec:browser":"echo \"Browser test is not working currently\" && exit -1 && webpack --config spec\/support\/webpack.mocha.config.js","clean_dist":"shx rm -rf .\/dist","clean_dist_cjs":"shx rm -rf .\/dist\/cjs","clean_dist_esm5":"shx rm -rf .\/dist\/esm5","clean_dist_esm5_for_rollup":"shx rm -rf .\/dist\/esm5_for_rollup","clean_dist_esm2015":"shx rm -rf .\/dist\/esm2015","clean_dist_global":"shx rm -rf .\/dist\/global","clean_dist_types":"shx rm -rf .\/dist\/typings","commit":"git-cz","compile_dist_cjs":"tsc -p .\/tsconfig\/tsconfig.cjs.json","compile_dist_esm5":"tsc -p .\/tsconfig\/tsconfig.esm5.json","compile_dist_esm2015":"tsc -p .\/tsconfig\/tsconfig.esm2015.json","compile_dist_esm5_for_rollup":"tsc -p .\/tsconfig\/tsconfig.esm5.rollup.json","compile_dist_types":"tsc -p .\/tsconfig\/tsconfig.types.json","copy_sources":"mkdirp dist && shx cp -r .\/src\/ .\/dist\/src","decision_tree_widget":"cd doc\/decision-tree-widget && npm run build && cd ..\/..","generate_packages":"node .make-packages.js","lint_perf":"eslint perf\/","lint_spec":"tslint -c tslint.json \"spec\/**\/*.ts\"","lint_src":"tslint -c tslint.json \"src\/**\/*.ts\"","lint":"npm-run-all --parallel lint_*","dtslint":"npm run build_types && dtslint --localTs .\/node_modules\/typescript\/lib --expectOnly .\/spec-dtslint","perf:micro":"node .\/perf\/micro\/index.js","prepublish":"shx rm -rf .\/typings && npm run build_all","postpublish":".\/docs_app\/scripts\/publish-docs.sh","publish_docs":".\/publish_docs.sh","test":"cross-env TS_NODE_PROJECT=spec\/tsconfig.json mocha --opts spec\/support\/default.opts \"spec\/**\/*-spec.ts\"","test_no_cache":"cross-env TS_NODE_PROJECT=spec\/tsconfig.json TS_NODE_CACHE=false mocha --opts spec\/support\/default.opts \"spec\/**\/*-spec.ts\"","test_transpile_only":"cross-env TS_NODE_PROJECT=spec\/tsconfig.json TS_NODE_TRANSPILE_ONLY=true mocha --opts spec\/support\/default.opts \"spec\/**\/*-spec.ts\"","test:browser":"echo \"Browser test is not working currently\" && exit -1 && npm-run-all build:spec:browser && opn spec\/support\/mocha-browser-runner.html","test:circular":"dependency-cruise --validate .dependency-cruiser.json -x \"^node_modules\" dist\/esm5","test:systemjs":"node integration\/systemjs\/systemjs-compatibility-spec.js","test:side-effects":"check-side-effects --test integration\/side-effects\/side-effects.json","test:side-effects:update":"npm run test:side-effects -- --update","tests2png":"mkdirp docs_app\/content\/img && mocha --opts spec\/support\/tests2png.opts \"spec\/**\/*-spec.ts\""},"repository":{"type":"git","url":"https:\/\/github.com\/reactivex\/rxjs.git"},"keywords":["Rx","RxJS","ReactiveX","ReactiveExtensions","Streams","Observables","Observable","Stream","ES6","ES2015"],"author":"Ben Lesh <ben@benlesh.com>","contributors":[{"name":"Ben Lesh","email":"ben@benlesh.com"},{"name":"Paul Taylor","email":"paul.e.taylor@me.com"},{"name":"Jeff Cross","email":"crossj@google.com"},{"name":"Matthew Podwysocki","email":"matthewp@microsoft.com"},{"name":"OJ Kwon","email":"kwon.ohjoong@gmail.com"},{"name":"Andre Staltz","email":"andre@staltz.com"}],"license":"Apache-2.0","bugs":{"url":"https:\/\/github.com\/ReactiveX\/RxJS\/issues"},"homepage":"https:\/\/github.com\/ReactiveX\/RxJS","dependencies":{"tslib":"^1.9.0"},"devDependencies":{"@angular-devkit\/build-optimizer":"0.4.6","@angular-devkit\/schematics":"^7.3.9","@types\/chai":"4.1.2","@types\/lodash":"4.14.102","@types\/mocha":"2.2.48","@types\/node":"9.4.5","@types\/sinon":"4.1.3","@types\/sinon-chai":"2.7.29","@types\/source-map":"^0.5.2","babel-polyfill":"6.26.0","benchmark":"2.1.0","chai":"4.1.2","check-side-effects":"0.0.20","color":"3.0.0","colors":"1.1.2","commitizen":"^4.0.3","cross-env":"5.1.3","cz-conventional-changelog":"1.2.0","dependency-cruiser":"^4.27.3","dtslint":"^0.7.4","escape-string-regexp":"1.0.5","eslint":"4.17.0","eslint-plugin-jasmine":"^2.10.1","fs-extra":"5.0.0","get-folder-size":"1.0.1","glob":"7.1.2","gm":"1.23.1","google-closure-compiler-js":"20170218.0.0","gzip-size":"4.1.0","klaw-sync":"3.0.2","lint-staged":"^8.1.6","lodash":"^4.17.15","minimist":"1.2.0","mkdirp":"0.5.1","mocha":"5.0.0","npm-run-all":"4.1.2","opn-cli":"3.1.0","platform":"1.3.5","promise":"8.0.1","rollup":"0.66.6","rollup-plugin-alias":"1.4.0","rollup-plugin-inject":"2.0.0","rollup-plugin-node-resolve":"2.0.0","shx":"0.2.2","sinon":"4.3.0","sinon-chai":"2.14.0","source-map-support":"0.5.3","systemjs":"^0.21.0","ts-node":"6.1.0","tsconfig-paths":"3.2.0","tslint":"5.9.1","tslint-etc":"1.5.0","tslint-no-toplevel-property-access":"0.0.2","tslint-no-unused-expression-chai":"0.0.3","typescript":"3.5.3","validate-commit-msg":"2.14.0","webpack":"^4.31.0"},"engines":{"npm":">=2.0.0"},"typings":".\/dist\/package\/Rx.d.ts"}
</details>

- forward search `/` to find text outside of current editor width
- check selected text visual

![repro](https://user-images.githubusercontent.com/1210596/73236844-b5193400-4148-11ea-8f83-18e53fc4a23d.gif)

**Comment by asvetliakov** [comment]
This is not very fixable currently i think. Neovim width is restricted to 500 columns. If search/incsearch goes beyond this, it scrolls. BUT neovim doesn't send horizontal scroll events, so no scroll information here. Alternative solution is word wrap (and forcing it in neovim) here, but this time there is no vscode api to query horizontal editor viewport size to correctly set width in neovim.

**Comment by theol0403** [comment]
It is possible that win-viewport gives horizontal scroll.
