### ISSUE TITLE
bug: random characters being rendered in vscode

### ISSUE THREAD

**Issue by rayzorben** [vscode-neovim/vscode-neovim#1611]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.7.2

### Operating system/version

Ubuntu 23.10

### Describe the bug

Random characters are rendered when using nvim plugin. See https://github.com/vscode-neovim/vscode-neovim/issues/968

This happens in both Windows and Linux for me.

See correct version below with neovim disabled

![image](https://github.com/vscode-neovim/vscode-neovim/assets/7737834/034c4802-1060-4d83-be98-d8f42c04ad9f)

### Steps To Reproduce

Unsure. Seems to be most consistent when using CTRL+SHIFT+F to find text in files, and moving through the list of files with that matching text.

Shows up with both C# and coffeescript

### Expected Behavior

No random characters. See:

![image](https://github.com/vscode-neovim/vscode-neovim/assets/7737834/2228fc46-ab18-4cef-8c80-a9b622930d03)

**Comment by xiyaowong** [comment]
Please try the latest build and attempt to use this autocmd.
```vim
au CmdlineEnter,CmdlineLeave,ModeChanged,CursorHold * silent! mode
```

**Comment by xiyaowong** [comment]
Wait, which version of vscode-neovim are you using? 😨 
![image](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/b1fdaf44-4eb1-4c06-8115-b733013dd423)

**Comment by xiyaowong** [comment]
Upgrade your nvim

**Comment by xiyaowong** [comment]
@rayzorben Please use the latest vscode-neovim (v1.0.0) and the latest stable version of neovim (v0.9.4). If this issue cannot be reproduced, please close this issue.

Use the command `:version` to check the nvim version currently used by vscode-neovim.

**Comment by rayzorben** [comment]
Upgraded but already hitting problems. dd, p is pasting the wrong thing. if I dd a line that says 'onSneak' for example, I will paste it and it will paste onSneak and then a blank line after. Then I go to another line that has a method onEquip and I do dd P and it pastes the next line which is onUnequip. Not sure if it is a rendering issue or a buffer issue.

![image](https://github.com/vscode-neovim/vscode-neovim/assets/7737834/38b2d72a-fe77-42ea-b2cd-899e0b514d46)

**Comment by xiyaowong** [comment]
It should not be a rendering issue. Please open a new issue.
