### ISSUE TITLE
bug: latest dev build is pasting wrong data from buffer.

### ISSUE THREAD

**Issue by rayzorben** [vscode-neovim/vscode-neovim#1612]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

v0.10.0-dev

### Operating system/version

Ubuntu 23.10

### Describe the bug

I try `dd` a line and then `p` it. I repeat it, and it puts an extra line after it.

I then `dd` another line and `P` it. It pastes the wrong line. See video.

[Screencast from 2023-11-14 08-42-55.webm](https://github.com/vscode-neovim/vscode-neovim/assets/7737834/542e1e0d-778b-4da8-b188-3ba6155d8b73)

### Steps To Reproduce

`dd`, `p`. move to the line and repeat.

go to a line a couple down, `dd` and then `P` that.

Wrong line is pasted.

### Expected Behavior

Right line is pasted, see video.

**Comment by xiyaowong** [comment]
Does every file have a problem? Can you upload a file that reproduces the issue?

**Comment by rayzorben** [comment]
https://github.com/rayzorben/mudengine/blob/main/src/engine/user.coffee line 572

other files seem fine but I only tested about 3

**Comment by xiyaowong** [comment]
I can reproduce 👀
