### ISSUE TITLE
bug: action() fails with "Spread syntax requires ...iterable[Symbol.iterator] to be a function"

### ISSUE THREAD

**Issue by justinmk** [vscode-neovim/vscode-neovim#1616]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.10

### Operating system/version

macos

### Describe the bug

Executing this Lua code from the vscode-neovim prompt (or a mapping):

     lua require('vscode-neovim').action('workbench.action.findInFiles', { args = { query = vim.fn.expand('<cword>')} })

fails with error:

    Error on notification: Spread syntax requires ...iterable[Symbol.iterator] to be a function

on this line: https://github.com/vscode-neovim/vscode-neovim/blob/dc075aaf7177a42c287230d79a09f3de292a7f8e/src/main_controller.ts#L221

### Steps To Reproduce

1. call the Lua `action()` with `{args = { ... }` argument

### Expected Behavior

execute vscode command with the specified args.

Edit: this is probably because `args` is expected to be a list, not a dict. We should fail early and show a clear message, in that case.

**Comment by xiyaowong** [comment]
Oops, I linked to the wrong issue 
![image](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/ed80cc24-5aa7-4775-b0ff-6108eb5b498c)

Closed by https://github.com/vscode-neovim/vscode-neovim/commit/536fbf13016e369df09ce029ce6cfc348a313c5e
