### ISSUE TITLE
Update README.md to reflect changes to keybindings in 1.0

### ISSUE THREAD

**Issue by sgarcialaguna-mms** [vscode-neovim/vscode-neovim#1623]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

v0.9.0

### Operating system/version

Windows 10

### Describe the bug

Recently, I noticed that keyboard shortcuts I had disabled for nvim no longer work. For example Ctrl-F for search I re-checked the README.md and it still mentions the old way of defining shortcuts. After digging in to the changelogs, I found that there have been some breaking changes in 1.0, but that should be highlighted much better as it will catch many developers by surprise.

### Steps To Reproduce

.

### Expected Behavior

.

**Comment by justinmk** [comment]
> keyboard shortcuts I had disabled for nvim no longer work. For example Ctrl-F for search

how did you disable them? give exact example code.

> I re-checked the README.md and it still mentions the old way of defining shortcuts. After digging in to the changelogs, I found that there have been some breaking changes in 1.0, 

I assume you're referring to https://github.com/vscode-neovim/vscode-neovim#adding-keybindings ?

what breaking changes specifically?

**Comment by xiyaowong** [comment]
when expression of keybindings is changed. But I think this impact is very small, just delete it yourself. And I'm sure you didn't read the readme carefully
![image](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/ca3e8441-a158-49ff-af3a-cd4d3d7c3d6f)

**Comment by sgarcialaguna-mms** [comment]
From the README:

> To disable an existing shortcut, for example C-a, add to your keybindings.json:
> 
> {
>     "command": "-vscode-neovim.send",
>     "key": "ctrl+a"
> }

This does not work anymore. Your screenshot is from much further down in the README.

**Comment by theol0403** [comment]
Yes the readme must be fixed, removing a default binding is now a settings option instead of keybinding entry.
