### ISSUE TITLE
bug: gq not working for hard wrapping lines since v1.0.0

### ISSUE THREAD

**Issue by reberhardt7** [vscode-neovim/vscode-neovim#1627]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

1.0.0

### Operating system/version

MacOS 13.4

### Describe the bug

Since updating to v1.0.0, when I have a long line in VSCode and type `gql` to hard wrap it, nothing happens. When I revert to version 0.9.1, it successfully hard wraps as expected.

Thank you so much for your hard work on this project! It is a life saver.

### Steps To Reproduce

1. Type a long line
2. In command mode, press `gql` to wrap that line

### Expected Behavior

The line should get hard wrapped

**Comment by xiyaowong** [comment]
gq will use vscode formatting by default

There are two ways.
1. `unmap gq`
2. use `gw`

**Comment by Xiaorui-Huang** [comment]
@xiyaowong First, I'd like to ask how do you remap `gq`? 

And in my opinion, this is a case for inconsistent behavior. `gq` and `gw` should only differ in terms of how the cursor ends up at. but in this extension we get wildly different expected behaviors. I'd suggest changing this back or document it somewhere. 

I don't understand why the decision came about to change `gq` to map to vscode formatting as that has it's own set of shortcuts anyways. In my normal workflow, if I want to format the document by vscode it's just `alt + shift + f`. 

With the new change, we have two ways to vscode format, yet `gq` now have unexpected behaviors.

**Comment by xiyaowong** [comment]
> First, I'd like to ask how do you remap `gq`?

`:map gq`
https://github.com/vscode-neovim/vscode-neovim/blob/6b58cd374eb4f08a0f0ce6bc247a320396ca19b2/runtime/plugin/code_actions.lua#L22-L23

**Comment by jedevc** [comment]
Thanks for all the hard work on this plugin, I genuinely couldn't live without it :smile: (btw @xiyaowong if you ever do get github sponsors/similar sorted out https://github.com/vscode-neovim/vscode-neovim/commit/2c979d1d1fe70eef4c1cef7a792bc3923bcef35c, then let me know, seems like you're doing a lot of the day-to-day on this project and I'd like to support that) :tada:

---

Out of curiosity, I'm kinda confused as to why this behavior was changed from the previous implementation - I typically use `gq`/`gw` to automatically reflow long comments easily into multiple lines. I can't the PR/commit that changed this, but maybe there's been discussion on this before, but I think it would make sense to consider changing it back to how it works before.

It also feels weird that now `gw` and `gq` don't work identically - it feels like either both of them should do the vscode formatting, or they should both follow the vim formatting. 

---

In this example, I think `gw`/`gq` should be the other way round? (assuming the intention is to rebind `gq` to `gw` to get something similar to the old behavior)

```
nnoremap gq gw
nnoremap gqq gww
```

This works as a workaround for me right now, but also, `gq` and `gw` aren't actually the same command.
