### ISSUE TITLE
Rebranding and better docs

### ISSUE THREAD

**Issue by pedroapfilho** [vscode-neovim/vscode-neovim#163]
This package needs better documentation and a rebranding, so it'll be more visible to new users.

We can start a "contest" for brand ideas here! What do you guys think?

**Comment by asvetliakov** [comment]
Agree. The wiki / structured readme won't hurt at least. Also good to compile a list of vim-plugins which are tested and working / need some config param to work / don't work

**Comment by pedroapfilho** [comment]
I would love to see how to implement custom keystrokes, for example, but its very hard to find info here. Maybe we can create a small documentation website with docusaurus?

**Comment by theol0403** [comment]
This has been improved significantly with #513. However, I agree that work can still be done in regard to the wiki, plugin compatibility, more examples, configs, and guides. I hope to work on the wiki sometime 👍
