### ISSUE TITLE
bug: The highlighting is inconsistent between vscode and nvim

### ISSUE THREAD

**Issue by xiyaowong** [vscode-neovim/vscode-neovim#1630]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [x] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.4

### Operating system/version

window 11

### Describe the bug

I have noticed this issue while using flash.nvim.

VSCode vs NeoVim
<img src="https://github.com/vscode-neovim/vscode-neovim/assets/47070852/4f8f6236-31ca-49e8-bcd2-3a93ba796ed4" height="320" /> <img src="https://github.com/vscode-neovim/vscode-neovim/assets/47070852/e5d822d3-f2d3-47e1-8ddf-04a26a140899" height="320" />

Pressing "l" jumps to position "r", while pressing "r" jumps to position "l".

### Steps To Reproduce

Install flash.nvim

1. Open file
	```


	world0
	world1
	world2
	world3
	world3
	world4
	world5
	world6
	world7
	world8
	world9
	worlda
	```
2. type `gg0/world`

### Expected Behavior

Highlighting is consistent with nvim.

**Comment by xiyaowong** [comment]
Debugging found that the grid_line event contained incorrect data. It seems to be a problem with nvim?

![image](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/5b39b4ba-11c6-4045-9abe-e74c0afd33c4)


test patch
```diff
--- a/src/highlight_manager.ts
+++ b/src/highlight_manager.ts
@@ -70,6 +70,13 @@ export class HighlightManager implements Disposable {
                         }
                         const lineText = editor.document.lineAt(highlightLine).text;
                         let vimCol = col + gridOffset.character;
+                        console.log(
+                            highlightLine,
+                            lineText,
+                            cells.reduce((p, n) => {
+                                return p + n[0].repeat(n[2] ?? 1);
+                            }, ""),
+                        );
 
                         // remove cells from statuscolumn
                         if (vimCol < 20) {
```

**Comment by justinmk** [comment]
> seems to be a problem with nvim?

try latest Nvim development version
