### ISSUE TITLE
bug: yank highlighting broke in v1.1.1, but works in v1.1.0

### ISSUE THREAD

**Issue by Edgar-P-yan** [vscode-neovim/vscode-neovim#1631]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

v0.9.4

### Operating system/version

MacOS 14.0

### Describe the bug

Thanks for the awesome integration, i'm new to vim so having an actual nvim instance integrated with the vscode is really helpful!

Yank highlighting broke after updating to v1.1.1, at first i thought that the issue was in the config files as i'm new to neovim and could brake something myself, tried different configs to get highlighting to work:
Vim script:
```vim
augroup highlight_yank
    autocmd!
    autocmd TextYankPost * silent! lua vim.highlight.on_yank { higroup="IncSearch", timeout=1000 }
augroup END
```
And also tried Lua:
```lua
local function augroup(name)
  return vim.api.nvim_create_augroup("lazyvim_" .. name, { clear = true })
end

vim.api.nvim_create_autocmd("TextYankPost", {
  group = augroup("highlight_yank"),
  callback = function()
    vim.highlight.on_yank()
  end,
})
```

Both configs worked just fine inside the nvim terminal, but not with `vscode-extension`, although i had it working in vscode too just today earlier. The configuration file does not contain anything else, I also tried on a fresh installation of VSCode Insiders without any other extensions - still no success. Downgrading to v1.1.0 fixed the problem.

### Steps To Reproduce

Install the v1.1.1 version.
Enable yank highlighting in the config file.

### Expected Behavior

Yank should be highlighted, just as it was in v1.1.0

**Comment by xiyaowong** [comment]
Now, all custom highlight groups in vscode will be automatically cleared. It seems that `nvim_buf_set_extmark` will ignore empty highlight groups.
