### ISSUE TITLE
bug: Multiple cursors keybinding `ma` move the cursor to the wrong position

### ISSUE THREAD

**Issue by mrbeardad** [vscode-neovim/vscode-neovim#1632]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

v0.10.0-dev-9af03bc

### Operating system/version

Microsoft Windows 11 Home 10.0.22621 N/A Build 22621

### Describe the bug

https://github.com/vscode-neovim/vscode-neovim/assets/54128430/4fd2439b-6bcc-4134-9efd-eda645edae09

### Steps To Reproduce

```txt
this is ascii, but this is not 🦄😊😂🤣    |
this is ascii, but this is not 🦄😊😂🤣    |
this is ascii, but this is not 🦄😊😂🤣    |
```
To reproduce: `Vjjma`

### Expected Behavior

After I press `ma`, the cursors should move to the end of line

**Comment by mrbeardad** [comment]
Thanks for the fast fix.👍👍👍BTW, when can I update it from vscode market?

**Comment by xiyaowong** [comment]
Soon. 

However, there are still issues in visual block mode, and currently, there are no plans to fix them :(
