### ISSUE TITLE
bug: keymap 'gc' can not be correcly recgonized

### ISSUE THREAD

**Issue by gzfrozen** [vscode-neovim/vscode-neovim#1639]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Windows 11 / Mac OS

### Describe the bug

I binded a keymap like the following:

```
vim.keymap.set({ "n", "v" }, "gc", function()
    vim.fn.VSCodeNotify("editor.action.commentLine")
end)
```
And recently it cann't work when in normal mode correctly. 
After input 'gc' nothing happend, and the status bar shows that 'g@' had been input.

In visual mode it works totally OK.

If I change to any other key combination it also works totally fine in both normal and visual mode:
```
vim.keymap.set({ "n", "v" }, "<leader>c", function()
    vim.fn.VSCodeNotify("editor.action.commentLine")
end)
```

I also tried the newer method but it doesn't work either.
```
local vscode = require('vscode-neovim')
vim.keymap.set({ "n", "v" }, "gc", function()
    vscode.action("editor.action.commentLine")
end)
```

### Steps To Reproduce

As the description

### Expected Behavior

Can toggle line comment in normal mode after press 'gc'.

**Comment by xiyaowong** [comment]
"gc" and "gcc" are now mapped to comment commands by default. Try `gcc` `gciw` `gcj`...

https://github.com/vscode-neovim/vscode-neovim/blob/ccc83e47e80536b7acd2df66e9a99630d6b4ce5f/runtime/plugin/code_actions.lua#L43-L44
