### ISSUE TITLE
bug: Selecting CJK characters using mouse in normal mode is weird

### ISSUE THREAD

**Issue by cgjosephlee** [vscode-neovim/vscode-neovim#1645]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.4

### Operating system/version

MacOS 12.7.1

### Describe the bug

Selecting CJK characters (Chinese) using mouse in normal mode yields weird results, and following operations (like yank, delete selected) do not work properly.

### Steps To Reproduce

Select any part in test context in normal mode using mouse:
```
English 中文字 English 中文字

English English English English

中文字中文字中文字中文字中文字中文字
```

### Expected Behavior

Selecting CJK and non-CJK characters should yield same behavior.

**Comment by xiyaowong** [comment]
@cgjosephlee Please test https://github.com/vscode-neovim/vscode-neovim/suites/18404771731/artifacts/1066456072

**Comment by cgjosephlee** [comment]
Great thanks to all your efforts! The issue is fixed in this pre-release.
