### ISSUE TITLE
bug: Extmark overlay on dimmed characters becomes blurry

### ISSUE THREAD

**Issue by cgjosephlee** [vscode-neovim/vscode-neovim#1646]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.4

### Operating system/version

MacOS 12.7.1

### Describe the bug

I am using flash.nvim (with LazyVim). The jump labels overlay on dimmed character are blurry (2nd and 3rd columns in screenshot), and others are not. I guess it is an issue about extmark overlay.
![截圖 2023-11-22 下午2 47 41](https://github.com/vscode-neovim/vscode-neovim/assets/12654602/d0145e90-9b84-4544-8a14-222e9a92ea00)
![截圖 2023-11-22 下午2 47 34](https://github.com/vscode-neovim/vscode-neovim/assets/12654602/4d84a81e-825d-4d2c-bd1d-c4c4c2dc7acb)

### Steps To Reproduce

Open a `.py` file with following context:
```
from datetime import date, datetime, timedelta

from datetime import date, datetime, timedelta

from datetime import date, datetime, timedelta
```
Then hit `sda` to trigger flash.nvim with `da` prefix and show jump labels.

### Expected Behavior

The overlayed jump labels should be clear.

**Comment by xiyaowong** [comment]
I noticed this phenomenon very early on :)

Please vote for #170607

**Comment by xiyaowong** [comment]
@cgjosephlee Please test https://github.com/vscode-neovim/vscode-neovim/suites/18404771731/artifacts/1066456072
