### ISSUE TITLE
feature: switch input method automatically 

### ISSUE THREAD

**Issue by crackzj** [vscode-neovim/vscode-neovim#1649]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

I want to switch the input method automatically in normal mode, it works fine in neovim, but not in vscode. I  don't know how to make the 'esc' key trigger from vs code

### Describe the solution you'd like

```
vim.api.nvim_create_autocmd({"InsertLeave"},{
  pattern={"*"},
  callback = function()
        vim.fn.system("im-select com.apple.keylayout.ABC")
  end
})
```
it works in neovim.

### Describe alternatives you've considered

```
vim.api.nvim_create_autocmd({"InsertLeave"},{
  pattern={"*"},
  callback = function()
        vim.fn.system("im-select com.apple.keylayout.ABC")
  end
})
```

**Comment by xiyaowong** [comment]
#1370
