### ISSUE TITLE
remaps don't work when sourcing remaps.vim file

### ISSUE THREAD

**Issue by wis** [vscode-neovim/vscode-neovim#165]
like so:
```
let cfg = fnamemodify($MYVIMRC, ':h')
execute 'source' cfg . '/basic_remaps.vim'
```
when you unmodularize the remaps from the basic_remaps.vim to the init.vim, remaps start working again

**Comment by asvetliakov** [comment]
Your example works for me just fine

Make sure you're not using CRLF line endings for `basic_remaps.vim`

**Comment by wis** [comment]
I think you're right, this is related to a different issue, `fnamemodify($MYVIMRC, ':h')` = `.` in vscode and it's = `/home/x/.config/nvim/` in nvim.
tested with `:echo fnamemodify($MYVIMRC, ':h')`
