### ISSUE TITLE
bug: "Neovim: turn on/off" command no longer exists 

### ISSUE THREAD

**Issue by tom-pollak** [vscode-neovim/vscode-neovim#1650]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.4

### Operating system/version

MacOS 14.1.1

### Describe the bug

Command as described in #794 no longer exists.

Trying to call the command directly leads to: `command 'vscode-neovim.toggle' not found`

I found this stopped working ~4 weeks ago

### Steps To Reproduce

cmd+p

> Neovim: 

does not show the command.

### Expected Behavior

Command should appear

**Comment by xiyaowong** [comment]
use `restart` and `stop`

**Comment by contang0** [comment]
why is there no toggle command? restart/stop means having to create two hotkeys instead of just one.

**Comment by justinmk** [comment]
> means having to create two hotkeys instead of just one.

No. See https://github.com/vscode-neovim/vscode-neovim/pull/1566#issuecomment-1852056253
