### ISSUE TITLE
bug: extension attempts to create a new buffer for the editor when the buffer for the editor already exists

### ISSUE THREAD

**Issue by archilkarchava** [vscode-neovim/vscode-neovim#1651]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.4

### Operating system/version

MacOS 14.1.1

### Describe the bug

"nvim_buf_set_name: Failed to rename buffer" error is shown when selecting an item from the reference search list.
It happens because VS Code creates an editor twice.
First, a new editor is created when the file is opened but the reference hasn't been selected yet. The extension will create a neovim buffer by calling `nvim_buf_set_name` with the following arguments `[bufId, BUFFER_NAME_PREFIX + document.uri.toString()]`
After a reference is selected VS Code will dispose of the existing editor for the file and create a new one. The extension will first create a new buffer and will call the `nvim_buf_set_name` with the same arguments which will result in the "nvim_buf_set_name: Failed to rename buffer" error and only then the buffer for the disposed editor will be removed.

### Steps To Reproduce

1. Open a multi-file code base that has references.
2. Select a function/class that is referenced in multiple files and press "Shift+f12".
3. Focus a reference in a list without pressing enter in a file that was not opened since the extension was initialized to make sure that the new buffer will be created for the editor.
4. Press "Enter" to select a reference.

https://github.com/vscode-neovim/vscode-neovim/assets/16840190/f8188db1-2e18-4eab-9422-21c6a02a7fba

### Expected Behavior

The reference search is closed and a new neovim buffer is created for the editor with the name set to `BUFFER_NAME_PREFIX + document.uri.toString()`

**Comment by stimw** [comment]
get this problem again...

**Comment by uduse** [comment]
I still bump into this problem very often. @stimw did you try something to fix it?

**Comment by stimw** [comment]
> I still bump into this problem very often. @stimw did you try something to fix it?

I found that I changed the name of the nvim configuration file, but did not synchronize the change in vscode.
