### ISSUE TITLE
bug: vscode-neovim now replaces OS clipboard

### ISSUE THREAD

**Issue by dytra** [vscode-neovim/vscode-neovim#1654]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.0

### Operating system/version

MacOs 11.6.5

### Describe the bug

I like to use neovim in vscode because I can be productive by using the clipboard in neovim and the clipboard in the os seperately
so usually If I wanna replace something, I selected part of a text then press CMD+C to copy, then I delete the text I wanna replace using vim motion using the `dw`, `d$`, `dd`, or `x` command. then I paste it using the CMD+V command. I know it's weird but it's been my workflow for a while.
But now using the vim motion delete command, it replaces the clipboard on the OS side also. So I have to copy again the text I wanna copy

recently I've been also playing with the native neovim. I updated to the latest version 0.9.0. Maybe that's the cause of this problem ?

### Steps To Reproduce

- updated to latest neovim
- restarted vscode
- starts to use vim delete motion

### Expected Behavior

the vim motion delete should not replace the OS clipboard

**Comment by xiyaowong** [comment]
`:echo &clipboard` `:h clipboard`

**Comment by dytra** [comment]
it says unnamedplus

**Comment by justinmk** [comment]
> it says `unnamedplus`

which means you have  configured Nvim to do the thing you have reported here.

**Comment by dytra** [comment]
I fix the issue by backuping  my neovim config file on my local machine
is there anyway not to use my local neovim config ? I use lazyvim btw

**Comment by justinmk** [comment]
yes
