### ISSUE TITLE
bug: Move line up ends cursor at wrong line if it is shorter than current horizontal cursor position

### ISSUE THREAD

**Issue by XavierChanth** [vscode-neovim/vscode-neovim#1660]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.4

### Operating system/version

MacOS 14.1.1

### Describe the bug

When in normal mode, if you use the vscode built-in `Move Line Up` command and the following condition is met:

- The current horizontal position of the mouse cursor is further right than the length of the line swapping with. 
  - e.g. My currently selected line is 12 chars long with the cursor in horizontal position 10, and the line I am swapping it with is only 8 chars long.

Then the lines will successfully swap, but then the the cursor will be at the end of the shorter line (8 chars) at position 8, rather than the longer line (12 chars) at position 10.

### Steps To Reproduce

1. Ensure you are in normal mode
2. Write 2 lines of text (shorter line first)
  e.g.`foo` & `Hello World!`
3. Select a spot beyond foo of the longer line
  e.g. select `W`
4. Move Line Up (either by keybind or command palette)
5. Lines will swap, but cursor will be at the end of `foo`

### Expected Behavior

Cursor should be at `W` not end of `foo`

**Comment by distbit0** [comment]
I just did an extension bisection and am having a related issue where "move line up" and "move line up" become unusable with vscode-neovim installed, as it causes the line I am intending to move to randomly be switched with another line above or below it, while it is being moved, causing the line I end up with under my cursor to be different to the line I started with under my cursor.

**Comment by XavierChanth** [comment]
> I just did an extension bisection and am having a related issue where "move line up" and "move line up" become unusable with vscode-neovim installed, as it causes the line I am intending to move to randomly be switched with another line above or below it, while it is being moved, causing the line I end up with under my cursor to be different to the line I started with under my cursor. It has been like this for as long as I remember using vscode neovim (~1/2 year), I just wasn't aware it was due to vscode neovim until now. many thx

I have since moved to full neovim, but this extension was crucial in my learning!

**Comment by ollien** [comment]
@distbit0 Can you open a new issue so we can track this separately? I'm happy to investigate :)
