### ISSUE TITLE
How to call VSCode API with VimScript?

### ISSUE THREAD

**Issue by wenfangdu** [vscode-neovim/vscode-neovim#1662]
Previously, I could use `VSCodeNotifyVisual` to call VSCode API from Neovim, since v1 deprecated VimScript functions, am I forced to convert to Lua? Are there any alternatives?

Since VimScript works across Vim and Neovim, I really don't see any point in the Lua conversion, probably add the VimScript functions back? Or at least provide a guide for calling VSCode API in VimScript.

**Comment by wenfangdu** [comment]
Hmm, looks like `map / <cmd>call VSCodeNotify('editor.action.commentLine')<cr>` works, but wasn't `VSCodeNotify` deprecated?

**Comment by xiyaowong** [comment]
Old VimScript functions can still be used for backward compatibility. You can also call lua functions in VimScript

**Comment by wenfangdu** [comment]
@xiyaowong Then they shouldn't be called deprecated in the doc, I thought they were removed:
![image](https://github.com/vscode-neovim/vscode-neovim/assets/28700378/f34e90fe-c969-4775-b211-5e238eee1a01)
Take `map / <cmd>call VSCodeNotify('editor.action.commentLine')<cr>` for example, how to call the equivalent Lua functions in VimScript? And if I go this route, will they take effect in Vim?

**Comment by xiyaowong** [comment]
There are examples in the README

https://github.com/vscode-neovim/vscode-neovim#examples

**Comment by wenfangdu** [comment]
@xiyaowong Thanks for the pointer, but since the VimScript functions code is there, we should probably change the doc to reflect that? Marking them as deprecated makes me nervous, feels like they'll stop working at any time.

**Comment by xiyaowong** [comment]
Keeping the Vim functions is only for backward compatibility. For new users, they should use the Lua API instead.
