### ISSUE TITLE
Custom Keybindings for Workbench Actions broken since v1.0.0

### ISSUE THREAD

**Issue by pvanb** [vscode-neovim/vscode-neovim#1665]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

NVIM v0.9.4 Build type: Release LuaJIT 2.1.1700008891

### Operating system/version

MacOS 13.6.1

### Describe the bug

I have some custom keybindings of the following form that allow me to move between workbench editor groups:

```json
    {
        "key": "ctrl+h",
        "command": "workbench.action.focusLeftGroup",
        "when": "editorTextFocus && neovim.ctrlKeysNormal && neovim.init && neovim.mode != 'insert'"
    },
    {
        "key": "ctrl+l",
        "command": "workbench.action.focusRightGroup",
        "when": "editorTextFocus && neovim.ctrlKeysNormal && neovim.init && neovim.mode != 'insert'"
    },
    {
        "key": "ctrl+k",
        "command": "workbench.action.focusAboveGroup",
        "when": "editorTextFocus && neovim.ctrlKeysNormal && neovim.init && neovim.mode != 'insert'"
    },
    {
        "key": "ctrl+j",
        "command": "workbench.action.focusBelowGroup",
        "when": "editorTextFocus && neovim.ctrlKeysNormal && neovim.init && neovim.mode != 'insert'"
    },
```
These work with VSCode Neovim `v0.9.1` but starting with `v1.0.0` they no longer work. I've tried every version from `v1.0.0` to `v1.1.4` and these key bindings no longer switch focus as expected.

In terms of precedence nothing appears to have changed between versions (i.e. no other keybindings overriding these)

![Screenshot 2023-11-29 at 11 12 25 AM](https://github.com/vscode-neovim/vscode-neovim/assets/823278/2e37464d-05e7-497e-9789-f9983cbf0bed)

Has something changed to impact the `when` condition that I have defined?

### Steps To Reproduce

1. Install `v1.0.0` or later of VSCode Neovim
2. Enable "Use Ctrl Keys For Normal Mode" option in **Extensions > Neovim** settings
3. Add custom keybindings as described above
4. Open multiple files in either a horizontal or vertical split view
5. Try one of the following operations
     1. With focus on top group, enter `Ctrl+j`
     2. With focus on bottom group, enter `Ctrl+k`
     3. With focus on left group, enter `Ctrl+l`
     4. With focus on right group, enter `Ctrl+h`

Repeating the above steps with `v0.9.1` or earlier installed exhibits the expected behaviour.

### Expected Behavior

5(i) Focus shifts from top group to bottom group
5(ii) Focus shifts from bottom group to top group
5(iii) Focus shifts from left group to right group
5(iv) Focus shifts from right group to left group

**Comment by pvanb** [comment]
I updated my **Steps to Reproduce** to add a step enabling the "Use Ctrl Keys For Normal Mode" user setting in case this isn't the default. I had this enabled in versions `v0.9.1` and older and I have that check any my keybinding `when` condition so it seemed relevant.

However, when I look at the user settings for **Extensions > Neovim** this setting I see the following:

`v1.0.0` or newer
![Screenshot 2023-11-29 at 12 01 33 PM](https://github.com/vscode-neovim/vscode-neovim/assets/823278/7f071a2e-1766-436e-b984-8f8b113b6866)

`v0.9.1` or older
![Screenshot 2023-11-29 at 12 00 44 PM](https://github.com/vscode-neovim/vscode-neovim/assets/823278/58ec4de6-dcc3-4876-a800-75b98ad06fef)

I don't know where the corresponding setting is in `settings.json` but this looks suspicious.

**Comment by theol0403** [comment]
Yes, the when clauses changed. Please look at the release notes.
