### ISSUE TITLE
bug: Cursor position outside buffer when exiting insert mode in a newly created file

### ISSUE THREAD

**Issue by remvn** [vscode-neovim/vscode-neovim#1671]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

v0.9.0

### Operating system/version

Windows 10

### Describe the bug

https://github.com/vscode-neovim/vscode-neovim/assets/34063162/505cf883-abdf-4078-ba98-a3241217d28b

### Steps To Reproduce

1. Create a new file
2. Enter insert mode and type 2 lines 
3. Exit insert mode with `Esc`

### Expected Behavior

Should work correctly

**Comment by xiyaowong** [comment]
Can you provide some logs?

set these options and open vscode's developer tools

```json
{
  "vscode-neovim.neovimClean": true,
  "vscode-neovim.logLevel": "debug",
  "vscode-neovim.logOutputToConsole": true
}
```

**Comment by remvn** [comment]
![image](https://github.com/vscode-neovim/vscode-neovim/assets/34063162/3ce36c04-f333-468e-857f-1b41f436cd7e)

**Comment by remvn** [comment]
By the way, I'm using `S` to enter insert mode. Other than `S`, other ways like `o i a` is fine

**Comment by xiyaowong** [comment]
I only reproduced it twice when immediately started editing after creating a new file. You can try waiting for half a second after creating a new file and then editing to see if the issue persists.

**Comment by remvn** [comment]
I tried wait for 5 seconds, the issue is still there.

**Comment by xiyaowong** [comment]
@remvn Please try this build [vscode-neovim.zip](https://github.com/vscode-neovim/vscode-neovim/files/13538681/vscode-neovim.zip) And provide the latest logs.

**Comment by remvn** [comment]
![image](https://github.com/vscode-neovim/vscode-neovim/assets/34063162/25740bb3-96a4-4d3e-8ddc-42d5ab39a71a)

![image](https://github.com/vscode-neovim/vscode-neovim/assets/34063162/dccec0ad-b5bf-4255-bf7c-1304e342bebc)

![image](https://github.com/vscode-neovim/vscode-neovim/assets/34063162/3b8c9da1-4987-425e-8f39-ddf151229066)

**Comment by xiyaowong** [comment]
Yes, I tried many times

From the logs, the error occurred when you entered the first character. It should be `0,0,0,0,s` here.
![image](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/94196f9e-615a-4295-8703-b2efb33f51f0)
Don't know what happend

**Comment by dbstratta** [comment]
It's happening to me too in new files consistently (entering insert mode with `S` plus the original steps to reproduce it. Waited 30 seconds after creating the file but it didn't make a difference) and the same error has happened to me in existing files but I don't know how to reproduce it there yet.

OS: Windows 11, WSL2 Ubuntu.
Neovim: 0.9.4.

**Comment by gixim** [comment]
Hello,

I also reproduced on both a new file and an existing file.
Not only `S` but `cG` also causes the buffer error.

OS: Windows 11
Neovim: v0.9.5

Here is the steps to reproduce on an existing file.
I'm going to use this plain text to reproduce.

```txt
aaa

bbb
```

1. Go to line 2 (a blank line between `aaa` and `bbb`)
2. Type `cG` to enter insert mode
3. Type at least 2 lines of text
4. Exit insert mode by `<Esc>` and the buffer error will occur

It seems that something goes wrong when the cursor is on a black line.
I could reproduce on VSCode Neovim v1.0.0 but couldn't on v0.9.1.

**Comment by justinmk** [comment]
cannot reproduce this with Nvim v0.10.0  `32b49448b227`
