### ISSUE TITLE
feature: hjkl motion in the hover widget

### ISSUE THREAD

**Issue by ni554n** [vscode-neovim/vscode-neovim#1681]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Update the binding of `K` and keep the `gh` unchanged so that we can use it for quick previews.

We can also add these bindings to enable `hjkl` motion:

```json
{
  "key": "h",
  "command": "editor.action.scrollLeftHover",
  "when": "editorHoverFocused"
},
{
  "key": "j",
  "command": "editor.action.scrollDownHover",
  "when": "editorHoverFocused"
},
{
  "key": "k",
  "command": "editor.action.scrollUpHover",
  "when": "editorHoverFocused"
},
{
  "key": "l",
  "command": "editor.action.scrollRightHover",
  "when": "editorHoverFocused"
},
  ```

### Describe alternatives you've considered

n/a

**Comment by xiyaowong** [comment]
Why not try to create a pr?

https://github.com/vscode-neovim/vscode-neovim/blob/master/scripts/keybindings/5_widgets.cjs#L2

**Comment by justinmk** [comment]
What problem is being solved here? Missing context

**Comment by xiyaowong** [comment]
Not a problem, just some keybindings in the hover widget

**Comment by ni554n** [comment]
> What problem is being solved here? Missing context

> What does this mean?

Generally when you do `gh` or `K` to `editor.action.showHover`, you cannot focus or scroll the popup without a mouse. So, they created an alternative action: `editor.action.showDefinitionPreviewHover` which also focuses the popup that can be interacted with  the keyboard without any mouse involvement.

I'm proposing the keep the `gh` behavior as it is for quick previews so we don't have to `esc` it every time, but change the `K` to that accessible action (and add those `hjkl` keybindings).

**Comment by xiyaowong** [comment]
I think you misunderstood. The difference between these two commands is only the displayed content.

**Comment by ni554n** [comment]
> I think you misunderstood. The difference between these two commands is only the displayed content.

If that's the case then let's start from a clean slate.

Say, I just installed VSCode and vscode-neovim. I move my cursor to a function name and trigger its long documentation preview with `gh` or `K` hover. How do I scroll the preview without mouse?

**Comment by xiyaowong** [comment]
[When hover is not visible, K is sent to nvim for processing normally; when hover is visible, press K again to focus the widget](https://github.com/vscode-neovim/vscode-neovim/issues/1391#issuecomment-1842476307)
```json
  {
    "command": "editor.action.showHover",
    "key": "shift+k",
    "when": "editorTextFocus && editorHoverVisible && neovim.mode == normal"
  }
```
