### ISSUE TITLE
Please vote on vscode "locale-independent keybindings" issue

### ISSUE THREAD

**Issue by martin-braun** [vscode-neovim/vscode-neovim#1683]
#1257 landed a while ago, but it's not feature complete for non-english ISO keyboard layouts, because of some limitations on VSCode. Those limitations have been addressed in https://github.com/microsoft/vscode/issues/186961.

Please [upvote](https://github.com/microsoft/vscode/issues/186961) the issue at VSCode so they will add it to their backlog, so that people with different keyboard layouts can enjoy sane defaults that are on par with Vim keybindings everywhere, not just in the editor view.

I would highly appreciate if we could reach the necessary 20 upvotes on the VSCode issue to get this fixed for everyone using `vscode-neovim` without an English keyboard.

Thank you for your attention.

**Comment by justinmk** [comment]
the issue title is too vague...

**Comment by martin-braun** [comment]
Hurray, we reached the necessary upvotes so the issue was moved to the backlog of the VSCode team. Thank you very much. This issue can be unpinned now.
