### ISSUE TITLE
bug: inconsistent character display with nvim

### ISSUE THREAD

**Issue by wenfangdu** [vscode-neovim/vscode-neovim#1686]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.4

### Operating system/version

macOS 14

### Describe the bug

![image](https://github.com/vscode-neovim/vscode-neovim/assets/28700378/e9e3605f-ae13-45de-a1ce-e7c28cae994c)

### Steps To Reproduce

```
document.title = '‎'
```

### Expected Behavior

The texts are displayed the same.

**Comment by xiyaowong** [comment]
> The texts are displayed the same.

There are inevitably differences between these two editors.

You can try disabling the vscode-neovim extension.

**Comment by wenfangdu** [comment]
@xiyaowong It looks like vscode-neovim renders both, which is incorrect, please reopen this.
vscode-neovim disabled:
![image](https://github.com/vscode-neovim/vscode-neovim/assets/28700378/6d8093ed-c725-4a72-adfc-5dcb52ee1a52)
vscode-neovim enabled:
![image](https://github.com/vscode-neovim/vscode-neovim/assets/28700378/09118b05-babb-4a59-b9ef-63ddcd89634b)

**Comment by xiyaowong** [comment]
It's unfixable. You should ask vscode to provide a way to disable the highlight

**Comment by wenfangdu** [comment]
@xiyaowong  Can vscode-neovim not render the nvim one?

**Comment by xiyaowong** [comment]
No way to distinguish this kind of highlight.

**Comment by wenfangdu** [comment]
@xiyaowong I noticed if it's a text file, reload vscode will remove the nvim highlight:

https://github.com/vscode-neovim/vscode-neovim/assets/28700378/82bf7a16-8aa4-4635-8b20-7bd2bc7e3086

The same doesn't hold for scripts, does this difference provide some hints?:

https://github.com/vscode-neovim/vscode-neovim/assets/28700378/779a8083-3f83-415b-83de-994f972c5632

**Comment by xiyaowong** [comment]
Because plain text lacks syntax, it does not trigger rendering for this part. You can try selecting this text, and you will notice that highlighting occurs.

**Comment by wenfangdu** [comment]
@xiyaowong That's some weird stuff (.
