### ISSUE TITLE
feature: make the dollar sign ($) work by default

### ISSUE THREAD

**Issue by danielo515** [vscode-neovim/vscode-neovim#1704]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

Hello, thank you for this great extension. It seems to have way better performance than the default neovim.
I was surprised that typing `$` in normal mode, inserted a literal dollar sign rather than going to the end of the line. I think this should be the default, since it's default neovim behavior

### Describe the solution you'd like

I wan `$` to be the default go to end of line navigation

### Describe alternatives you've considered

I have added this to my config, and it works:
```
    {
        "command": "vscode-neovim.send",
        // the key sequence to activate the binding
        "key": "$",
        // don't activate during insert mode
        "when": "editorTextFocus && neovim.mode != insert",
        // the input to send to Neovim
        "args": "$"
}
    
```

**Comment by xiyaowong** [comment]
> better performance than the default neovim. 

I guess you just mean lsp stuffs

> I was surprised that typing `$` in normal mode, inserted a literal dollar sign rather than going to the end of the line.

I'm pretty sure $ is being handled correctly, please check your config!

**Comment by danielo515** [comment]
> I guess you just mean lsp stuffs
> 
> >

Sorry, I word it very badly. I meant better performance than the other VSCode vim emulation extension



> I'm pretty sure $ is being handled correctly, please check your config!

How so? What kind of things can be impacting the handling of `$`?

**Comment by danielo515** [comment]
you were rigth. This extension: https://marketplace.visualstudio.com/items?itemName=aliariff.auto-add-brackets
Was hijacking the `$`. This was not a problem with the other emulation layer, so it may be related with the way the insert/normal mode is reported.
