### ISSUE TITLE
bug: searching with / keeps file highlighted

### ISSUE THREAD

**Issue by mezyoucef32** [vscode-neovim/vscode-neovim#1707]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.4

### Operating system/version

ubuntu

### Describe the bug

searching with /   for non existing word or ...  leaves file highlighted even other files when switching files
![Screenshot_2023-12-14_12-32-02](https://github.com/vscode-neovim/vscode-neovim/assets/56481396/b5bf2a6c-cc9b-4d92-b2b4-3ad76d6bc263)

### Steps To Reproduce

press / to search word 
type  ...

### Expected Behavior

it would be expected to remove hightlighting after pressing Esc button

**Comment by xiyaowong** [comment]
`:h nohl`

**Comment by jyc** [comment]
FYI @mezyoucef32, here's what I have in my `keybindings.json` for this:

```
  // Esc: clear vscode-neovim search results
  {
    "key": "escape",
    "command": "vscode-neovim.send",
    "when": "editorTextFocus && neovim.mode != insert",
    "args": ":nohl<cr>"
  }
```
