### ISSUE TITLE
bug: 1.3.0 broke line comment toggle

### ISSUE THREAD

**Issue by ohemelaar** [vscode-neovim/vscode-neovim#1708]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

v0.9.1

### Operating system/version

Ubuntu 22.04.3 LTS

### Describe the bug

Before 1.3.0, I could use `C-/` to toggle line comment like vscode does without neovim. Version 1.3.0 opens the forward search instead, as if I typed `/` without ctrl. This affects the normal, visual and select modes. The insert mode still works.

This also happens on 1.4.0 but I didn't show it in the screencast as I had to install the vsix manually

https://github.com/vscode-neovim/vscode-neovim/assets/19656762/46a7ef1c-2a02-48cb-94b8-48d4415564fc

### Steps To Reproduce

- Use vscode and vscode neovim 1.3.0
- open a source file like markdown, html, js...
- use keyboard shortcut `C-/`
- forward search is opened instead of line getting commented

### Expected Behavior

- Use vscode and vscode neovim 1.2.0
- open a source file like markdown, html, js...
- use keyboard shortcut `C-/`
- line is commented

**Comment by xiyaowong** [comment]
Show me
![image](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/32ff299e-4c34-466d-95c2-e340a1ddf1d2)

**Comment by ohemelaar** [comment]
![Screenshot from 2023-12-18 09-39-22](https://github.com/vscode-neovim/vscode-neovim/assets/19656762/051c44a1-da3b-4394-a9f7-d4dc7062e5df)
![Screenshot from 2023-12-18 09-37-22](https://github.com/vscode-neovim/vscode-neovim/assets/19656762/9bd3143a-cbd4-421d-a2a9-cfd09931f2ba)

**Comment by xiyaowong** [comment]
Please turn on neovimClean or search '<C-/>' in your nvim config

**Comment by ohemelaar** [comment]
I turned on Neovim Clean in the vscode extension options and reloaded and still have this behaviour with extension version 1.3.0 or 1.5.0. My `~/.config/nvim/init.vim` only has this:
```
source ~/.vimrc
```
and `~/.vimrc`
```
syntax on

" Highlights searches
set hls
set is

" Add line numbers
set number
" Relative line numbers
set rnu

" Set up tabs as spaces
set tabstop=4
set shiftwidth=4
set expandtab

" Auto indent on new line
set ai

" Hightlight trailing whitespace
highlight TrailingWhitespace ctermbg=red
:autocmd Syntax * syn match TrailingWhitespace /\s\+$/
```

I'll try replicating it in a completely clean VM to be really sure there's no config involved

**Comment by xiyaowong** [comment]
@ohemelaar try `map gcc`

**Comment by ohemelaar** [comment]
`:map gcc` shows `No mapping found`, both in VSCode or nvim with extension version 1.5.0.

With version `1.2.0` it shows this (sorry for the screenshot I can't select it)
![Screenshot from 2024-01-02 11-25-22](https://github.com/vscode-neovim/vscode-neovim/assets/19656762/a3eda25d-9102-459d-a160-3322f54b0011)

**Comment by xiyaowong** [comment]
@ohemelaar No idea what's happening.

**Comment by ohemelaar** [comment]
Well I tried in a VM and noticed weird stuff with the neovim PPA. I switched to the AppImage install instructions and this works well with any extension version. Sorry for the really weird bug, and thanks for answering those questions :pray:

**Comment by rbits0** [comment]
I have the same bug. I have neovim 0.9.1-1 installed from [Prebuilt MPR](https://docs.makedeb.org/prebuilt-mpr/introduction/)
