### ISSUE TITLE
feature: keybinding context for full mode (i.e. `mode(1)`)

### ISSUE THREAD

**Issue by ian-h-chamberlain** [vscode-neovim/vscode-neovim#1718]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

There might be other ways to solve this or workarounds, but I have a use-case where I'd like to enable a keybinding only if `vscode-neovim` does not have an operator-pending. For example, something like this:
```jsonc
    {
        "key": "shift+5",
        "command": "rust-analyzer.matchingBrace",
        "when": "editorTextFocus && neovim.mode != 'insert' && neovim.mode != 'operator-pending' && editorLangId == 'rust'"
    }
```

Unfortunately, `neovim.mode` doesn't have the concept of operator-pending mode, and I think changing its behavior might break a lot of existing keybinds (since `operator-pending` aka `no[vV^V]` is really a subset of `n`).

### Describe the solution you'd like

I think there are multiple options here, but maybe the simplest one would be a new context key that feeds the result of `mode(1)` into a new context key, instead of trying to cover every case like [the current mapping](https://github.com/vscode-neovim/vscode-neovim/blob/master/src/mode_manager.ts#L18).

My proposal would be a new context key like `neovim.fullMode`, which just returns the same string that `mode(1)` does (e.g. `no`, `noV`, `Vs`, etc.). Since VSCode supports [matching](https://code.visualstudio.com/api/references/when-clause-contexts#match-operator) on these strings, this should be flexible enough to allow lots of different combinations. My example above might look something like this (probably would need to try it out):

```jsonc
    {
        "key": "shift+5",
        "command": "rust-analyzer.matchingBrace",
        "when": "editorTextFocus && !(neovim.fullMode =~ /^(i|no)/) && editorLangId == 'rust'"
    }
```

### Describe alternatives you've considered

It might be feasible to write a custom function that calls back to VSCode, like `require('vscode-neovim').call("rust-analyzer.matchingBrace")`, but would require a remapping and might be tricky to cover all the edge cases. Also, it seems a bit silly to call into neovim just to call back to VSCode, instead of binding keys to a VSCode command directly.

Another option would be to attempt to add a simpler flag like `neovim.operatorPending`, but I could foresee people wanting to add other flags for various "sub-modes", like `niV`, `vs`, etc. (see `:help mode()` for a full list). Passing the full string through seems more flexible and allows for advanced use-cases, while `neovim.mode` can probably be used for most basic keybindings.

### Additional context

If this feature seems like a reasonable request, I'm happy to try implementing it myself. It seems like it would be fairly straightforward to add to the existing mode manager without breaking anything. Thanks!

**Comment by xiyaowong** [comment]
```
au VimEnter,ModeChanged * call VSCodeCall('setContext', 'neovim.fullMode', mode(1))
```

**Comment by ian-h-chamberlain** [comment]
Ah, thanks for that! I had been thinking about trying to invoke the final command (i.e. `rust-analyzer.matchingBrace` in this case) with a command binding, but it didn't occur to me that I could just use the `setContext` function directly. Just in case anyone else comes looking for similar functionality, this is what I ended up writing in my `init.lua`:

```lua
if vim.g.vscode then
    local vscode_neovim = require("vscode-neovim")

    vim.api.nvim_create_autocmd({ "VimEnter", "ModeChanged" }, {
        callback = function(args)
            vscode_neovim.call("setContext", {
                args = { "neovim.fullMode", vim.fn.mode(1) },
            })
        end,
    })
	-- any other vscode-neovim settings ...
end
```

And my vscode `keybindings.json`:
```jsonc
    {
        "key": "shift+5",
        "command": "rust-analyzer.matchingBrace",
        "when": "editorTextFocus && !(neovim.fullMode =~ /^(i|no)/) && editorLangId == 'rust'"
    }
```

**Comment by theol0403** [comment]
Can't you just say neovim.mode != visual?

**Comment by ian-h-chamberlain** [comment]
> Can't you just say neovim.mode != visual?

In this case, I still wanted to use the `rust-analyzer` command in visual mode, for behavior like this:
1. Insert mode: disable keybind, `%` types a literal `%`
2. Normal mode: use `rust-analyzer.matchingBrace`
3. visual / visual block: use `rust-analyzer.matchingBrace` (thanks to cursor synchronization, this works similar to regular neovim and selects the brace contents)
4. operator-pending: send `%` directly to neovim – cursor synchronization does not include nvim operators and the cursor simply moves, without executing the pending `d` or `c` or whatever. The operator _remains_ pending after the cursor move, which also can have weird side effects as well.

`neovim.fullMode =~ /^(i|no)/` covers cases 1 and 4, but as far as I can tell none of the current `neovim.mode` values covers case 4. `nvim_create_autocmd({ "VimEnter", "ModeChanged" }, ...)` does the trick to make the info available in `keybindings.json` though!

**Comment by userrand** [comment]
@ian-h-chamberlain Thank you for providing the lua code.

 I tried both the vimscript and lua for adding the neovim.fullMode context.  Using Developer: Inspect Contex Keys from the command palette, I can see that the neovim.fullMode exists and does what one would expect, for example neovim.fullMode = "no" when using y in normal mode.
 
 However, it seems that vscode still runs a command that should only run when it is 'n' (normal mode as I understand) and 'no' (operating mode as I understand ). 
 
 Here is an example 
 
```
{
        "key": "h",
        "command": "notebook.focusNextEditor",
        "when": "config.notebook.navigation.allowNavigateToSurroundingCells && editorTextFocus && inputFocus && notebookEditorFocused && !accessibilityModeEnabled && !isEmbeddedDiffEditor && notebookEditorCursorAtBoundary != 'none' && notebookEditorCursorAtBoundary != 'top' && editorTextFocus && neovim.init && neovim.fullMode == 'n'"
    }
```

**Comment by tmpm697** [comment]
@ian-h-chamberlain can u help with my use case?, like below:
```
    {
        "key": "n",
        "command": "editor.action.nextMatchFindAction",
        "when": "editorFocus && !findInputFocussed && !(neovim.fullMode =~ /^(i|no)/)"
    },

```
and
```
if vim.g.vscode then
    local vscode_neovim = require("vscode-neovim")

    vim.api.nvim_create_autocmd({ "VimEnter", "ModeChanged" }, {
        callback = function(args)
            vscode_neovim.call("setContext", {
                args = { "neovim.fullMode", vim.fn.mode(1) },
            })
        end,
    })
	-- any other vscode-neovim settings ...
end
```

problem:
```
1. start find and search for something
2. dimiss find
3. press `r` 
4. then press `n`
5. cursor immediately jump to next match which is not what i want --> if user currently in replace mode (in step 3), it should not call nextMatchFindAction action.
```

ty

**Comment by ian-h-chamberlain** [comment]
@tmpm697 unfortunately, I think this is a limitation of vim / neovim? I tried adding a `print(mode(1))` to the callback and it looks like `r` doesn't trigger operator-pending mode, probably because it's not waiting for a motion (like e.g. `c` or `d`). Docs don't seem to mention modes at all here: https://neovim.io/doc/user/change.html#simple-change

`R` (replace mode) from what I can tell is only triggered when you actually type `R` to _stay_ in replace mode as opposed to just the single character replacement.


I think with Lua we can kinda make up a new `nr` mode, meaning "replace-pending". I haven't done extensive testing but this seems like works at first try:

```lua
vim.keymap.set("n", "r", function()
    vscode_neovim.call("setContext", {
        args = { "neovim.fullMode", vim.fn.mode(1) .. "r" },
    })

	-- pass through the original `r` non-recursively as if the user typed it
    vim.api.nvim_feedkeys("r", "n", true)
end)
```

Then something like `"when": "!(neovim.fullMode =~ /^(i|n[or])/)"` should do the trick, I think? Up to you if you wanted to set a separate context like `neovim.replacePending` or something... this might also have a side effect of leaving it set as `nr` for a while until the next mode change but idk

**Comment by nivx18818** [comment]
> [@tmpm697](https://github.com/tmpm697) unfortunately, I think this is a limitation of vim / neovim? I tried adding a `print(mode(1))` to the callback and it looks like `r` doesn't trigger operator-pending mode, probably because it's not waiting for a motion (like e.g. `c` or `d`). Docs don't seem to mention modes at all here: https://neovim.io/doc/user/change.html#simple-change
> 
> `R` (replace mode) from what I can tell is only triggered when you actually type `R` to _stay_ in replace mode as opposed to just the single character replacement.
> 
> I think with Lua we can kinda make up a new `nr` mode, meaning "replace-pending". I haven't done extensive testing but this seems like works at first try:
> 
> vim.keymap.set("n", "r", function()
>     vscode_neovim.call("setContext", {
>         args = { "neovim.fullMode", vim.fn.mode(1) .. "r" },
>     })
> 
> 	-- pass through the original `r` non-recursively as if the user typed it
>     vim.api.nvim_feedkeys("r", "n", true)
> end)
> Then something like `"when": "!(neovim.fullMode =~ /^(i|n[or])/)"` should do the trick, I think? Up to you if you wanted to set a separate context like `neovim.replacePending` or something... this might also have a side effect of leaving it set as `nr` for a while until the next mode change but idk

Using `vim.schedule` to reset the mode on the next event loop tick. This should resolve the issue `nr` remains after being used while maintaining the cursor as operator-pending mode's cursor.

```
-- Tell VSCode Neovim to treat `r` as operator-pending mode
vim.keymap.set({ "n", "x" }, "r", function()
  vscode_neovim.call("setContext", {
    args = { "neovim.fullMode", "no" }
  })

  vim.schedule(function()
    vscode_neovim.call("setContext", {
      args = { "neovim.fullMode", vim.fn.mode(1) }
    })
  end)

  return "r"
end, { expr = true })
```
