### ISSUE TITLE
Question about "operation pending time"

### ISSUE THREAD

**Issue by 2nthony** [vscode-neovim/vscode-neovim#1720]
I am not sure if this is a bug or anything, so I ignored the issue template 🙏.

I searched other issues, and googled, didn't find related-issues 🤔.

---

Here is my question, I had a key binding `<leader>e`, the `leader` key is `space`

```lua
  { "<leader>e", ":call VSCodeNotify('workbench.view.explorer')<cr>" },
```

In vscode, if I pressed `leader(space)`, then about 500ms passed, the behaviour similar to cursor go right, just like this GIF.

![nvim](https://github.com/vscode-neovim/vscode-neovim/assets/19513289/dac4b34b-9c9d-4cbf-9044-95ed412c0526)

so I want to know is, is there any way to increase the "operation pending time"?

**Comment by xiyaowong** [comment]
`:h timeoutlen`
