### ISSUE TITLE
bug: if prettier formats the file, sometimes cursor gets stuck at a certain position in the edited line 

### ISSUE THREAD

**Issue by vlrevolution** [vscode-neovim/vscode-neovim#1726]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [ ] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9

### Operating system/version

Win on WSL2

### Describe the bug

Anybody else having a lot of issues with cursor getting stuck on some lines (cannot be moved further to the right along the line anymore). Seems to happen to me quite often, possibly depending on the speed at which formatting is applied. Every time I have to reload vscode to make the cursor move past the stuck point again.

### Steps To Reproduce

It seems hard to reliably reproduce as it happens randomly at times, but usually after save command (perhaps if I save > formatting is taking place > I move cursor before it finished?). I think it is also sometimes happening when visual selecting lines, just a hunch.

### Expected Behavior

Cursor should always be in sync even if formatting takes time

**Comment by xiyaowong** [comment]
his is caused by dotrepeat, some formatters will replace the entire file, resulting in dotrepeat needing to process a lot of characters for synchronization. It cannot be fixed.

**Comment by xiyaowong** [comment]
Here is a hack you can add to your config.
```lua
local internal = require('vscode-neovim.internal')
local old_sync = internal.dotrepeat_sync

internal.dotrepeat_sync = function(edits, deletes)
  -- Only handle 500 changed characters and 200 deleted characters.
  if #edits > 500 then edits = edits:sub(#edits - 499) end
  deletes = math.max(deletes, 200)
  return old_sync(edits, deletes)
end
```

**Comment by vlrevolution** [comment]
What do you mean ? I never uses dot repeat and this issue keeps coming up at random times

**Comment by xiyaowong** [comment]
Isn't it stuck when you exit insert mode?

**Comment by xiyaowong** [comment]
Please provide a screen recording.
