### ISSUE TITLE
bug: When input non-English by IME on Windows, show some other keys before insert position

### ISSUE THREAD

**Issue by mrbeardad** [vscode-neovim/vscode-neovim#1733]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2026+gbdfea2a89

### Operating system/version

Microsoft Windows 11 Home 10.0.22621 N/A Build 22621

### Describe the bug

When I type a normal command to change into insert mode, the normal command keys will be shown at the start of the insert position.

https://github.com/vscode-neovim/vscode-neovim/assets/54128430/eadc681a-621e-495b-a3fb-d7cccac2a809

### Steps To Reproduce

1. open any non-empty file in vscode
2. press `i` or `C` at non-first column, and input some Chinese
3. the `i` or `C` that you typed before insert will be shown at the start of insert position when the Chinese input are not confirmed

### Expected Behavior

DO not show `i` or `C` in step 3

**Comment by xiyaowong** [comment]
https://github.com/microsoft/vscode/issues/201866
