### ISSUE TITLE
bug: repeating macros skips `jk` movement

### ISSUE THREAD

**Issue by radu781** [vscode-neovim/vscode-neovim#1736]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [x] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.2

### Operating system/version

Windows 10

### Describe the bug

When repeatedly using a macro with the last step `j` or `k`, that step is ignored and applied on the same line.

I am using vscodium 1.85.1 and vscode-neovim 1.5.0

### Steps To Reproduce

1. Create a new file
2. 100i0\<CR\>\<Esc\> (create 100 lines with '0')
3. record macro for r1j
4. play it normally once (see that either `j` is not played or the replace is not)
5. play it repeatedly and the result is more volatile (you might get 1 replace and a lot of `j`)

In vscode with the extension the `j` never happens and all lines will have the same number. Using nvim directly works as intended.

### Expected Behavior

All steps in the macro are repeated and we get 0's replaced by 1's

**Comment by justinmk** [comment]
duplicate https://github.com/vscode-neovim/vscode-neovim/issues/644 https://github.com/vscode-neovim/vscode-neovim/issues/563
