### ISSUE TITLE
feature: Request to add more mode indicators to the status bar

### ISSUE THREAD

**Issue by photkey** [vscode-neovim/vscode-neovim#1737]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

<video src="https://private-user-images.githubusercontent.com/75218616/294788009-0d68ef9c-9df4-4424-9215-9c0aa486e32b.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MjgzNTAsIm5iZiI6MTcwNDgyODA1MCwicGF0aCI6Ii83NTIxODYxNi8yOTQ3ODgwMDktMGQ2OGVmOWMtOWRmNC00NDI0LTkyMTUtOWMwYWE0ODZlMzJiLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDE5MjA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNDkxZmM0NzFiNGYwODFkYzFiMzBjZGUwZGI3Y2E2Yzg4ODE0OTRhNDhjZjE2ZDcyZjhjZDgxYWM3OGNiYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ngTXfFXIqellkGftHDre8LjOvdSyzSnr2R6GV7AOOcc" data-canonical-src="https://private-user-images.githubusercontent.com/75218616/294788009-0d68ef9c-9df4-4424-9215-9c0aa486e32b.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MjgzNTAsIm5iZiI6MTcwNDgyODA1MCwicGF0aCI6Ii83NTIxODYxNi8yOTQ3ODgwMDktMGQ2OGVmOWMtOWRmNC00NDI0LTkyMTUtOWMwYWE0ODZlMzJiLm1wND9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDE5MjA1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNDkxZmM0NzFiNGYwODFkYzFiMzBjZGUwZGI3Y2E2Yzg4ODE0OTRhNDhjZjE2ZDcyZjhjZDgxYWM3OGNiYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ngTXfFXIqellkGftHDre8LjOvdSyzSnr2R6GV7AOOcc" controls="controls" muted="muted" class="d-block rounded-bottom-2 border-top width-fit" style="max-height:640px; min-height: 200px" data-immersive-translate-walked="688b527d-1be2-41fa-ba92-2f337bb18035" __idm_id__="2457605" draggable="true">

  </video> 
Using the `Apc Customize UI++` plugin, you can configure an effect very close to airline, without affecting performance. However, there is currently a lack of a 'Normal' mode.

configure：https://github.com/kensleDev/vscode-nvim-ui/issues/14#issuecomment-1880191058

### Describe the solution you'd like

Add more mode indicators to the status bar

### Describe alternatives you've considered

--

**Comment by xiyaowong** [comment]
https://github.com/vscode-neovim/vscode-neovim#%EF%B8%8F-api

vscode.get_status_item

**Comment by xiyaowong** [comment]
@photkey  :)
```lua
if vim.g.vscode then
  vim.opt.showmode = false
  local status = require('vscode-neovim').get_status_item('my-mode-indicator')
  local mode_names = setmetatable({
    ['n'] = 'NORMAL',
    ['no'] = 'N·OPERATOR PENDING ',
    ['v'] = 'VISUAL',
    ['V'] = 'V·LINE',
    ['\x16'] = 'V·BLOCK',
    ['s'] = 'SELECT',
    ['S'] = 'S·LINE',
    ['^S'] = 'S·BLOCK',
    ['i'] = 'INSERT',
    ['R'] = 'REPLACE',
    ['Rv'] = 'V·REPLACE',
    ['Rx'] = 'C·REPLACE',
    ['Rc'] = 'C·REPLACE',
    ['c'] = 'COMMAND',
    ['cv'] = 'VIM EX',
    ['ce'] = 'EX',
    ['r'] = 'PROMPT',
    ['rm'] = 'MORE',
    ['r?'] = 'CONFIRM',
    ['!'] = 'SHELL',
    ['t'] = 'TERMINAL',
  }, {
    __index = function(t, k)
      t[k] = 'UNKNOWN'
      return t[k]
    end,
  })
  vim.api.nvim_create_autocmd({ 'VimEnter', 'ModeChanged' }, {
    callback = function()
      local mode = vim.api.nvim_get_mode().mode
      status.text = mode_names[mode]
    end,
  })
end
```

**Comment by AchillesG** [comment]
@xiyaowong The require('vscode-neovim').get_status_item API has been removed. What alternative methods are available to achieve the previous functionality?

**Comment by xiyaowong** [comment]
@AchillesG vscode-neovim now supports statusline option.

**Comment by justinmk** [comment]
> vscode-neovim now supports statusline option.

To be clear: the Nvim 'statusline' option. https://neovim.io/doc/user/options.html#'statusline'
