### ISSUE TITLE
bug: jumping to problem from the problems pane activates `VISUAL` mode

### ISSUE THREAD

**Issue by andodet** [vscode-neovim/vscode-neovim#1738]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.2

### Operating system/version

Ubuntu 22.04.3

### Describe the bug

When jumping to a problem from the problems pane, `VISUAL` mode is automatically activated.
![Peek 2024-01-10 18-55](https://github.com/vscode-neovim/vscode-neovim/assets/29178712/51b11792-3d93-4cd7-bfa9-034962cc9a63)

### Steps To Reproduce

1. Click on a problem on the peroblems pane.

### Expected Behavior

Cursor should jump in the editor in `NORMAL` mode.

**Comment by guangxu-li** [comment]
> It's expected. Please disable vscode-neovim and try again.

this also happens to the `go to references` function. After selecting the target references from the references list window, it jumps to the target location and activates the visual mode. Not sure whether it's also the expected behavior. If it is how could I avoid activating the visual mode.

**Comment by xiyaowong** [comment]
I guess this is VSCode's default behavior.

**Comment by guangxu-li** [comment]
> I guess this is VSCode's default behavior.

but the old version vscode-neovim (<= 0.4.3) plugin works ok. And it doesn't only affect the goToReferences function, but also all functions using the peek widget like references-view.showCallHierarchy.

**Comment by xiyaowong** [comment]
@guangxu-li Try disable vscode-neovim

**Comment by guangxu-li** [comment]
> @guangxu-li Try disable vscode-neovim

then what's the purpose of using vscode-neovim. Same vsvode version,there's no issue when use the old version vscode-neovim

**Comment by xiyaowong** [comment]
> then what's the purpose of using vscode-neovim.

My point is to disable vscode-neovim and see what the default behavior of VSCode is like. 

> Same vsvode version,there's no issue when use the old version vscode-neovim

I just tried it myself and there's no such issue when jumping to references or definitions

**Comment by guangxu-li** [comment]
> > then what's the purpose of using vscode-neovim.
> 
> My point is to disable vscode-neovim and see what the default behavior of VSCode is like.
> 
> > Same vsvode version,there's no issue when use the old version vscode-neovim
> 
> I just tried it myself and there's no such issue when jumping to references or definitions

ahhhh, my bad. got ur point now. i guess this behavior change is due to the introduced feature that syncs the selection between the nvim and the vscode. In the old version of vscode-neovim, the selection status isn't synced between them.

The editor.action.referenceSearch.trigger works but it remains the peek widget open after jumping.

Any idea to simulate the old behavior?

**Comment by guangxu-li** [comment]
> > > then what's the purpose of using vscode-neovim.
> > 
> > 
> > My point is to disable vscode-neovim and see what the default behavior of VSCode is like.
> > > Same vsvode version,there's no issue when use the old version vscode-neovim
> > 
> > 
> > I just tried it myself and there's no such issue when jumping to references or definitions
> 
> ahhhh, my bad. got ur point now. i guess this behavior change is due to the introduced feature that syncs the selection between the nvim and the vscode. In the old version of vscode-neovim, the selection status isn't synced between them.
> 
> The editor.action.referenceSearch.trigger works but it remains the peek widget open after jumping.
> 
> Any idea to simulate the old behavior?

use https://github.com/ryuta46/vscode-multi-command as a workaround

```json
    "multiCommand.commands": [
        {
            "command": "enterWithCancelSelection",
            "interval": 75,
            "sequence": [
                {
                    "command": "list.select",
                    "onFail": [
                        "vscode-neovim.escape",
                    ]
                },
                {
                    "command": "vscode-neovim.escape",
                },
            ]
        },
    ],

```
