### ISSUE TITLE
bug: slight delays in neovim init can result in unexpected syntax coloring

### ISSUE THREAD

**Issue by ian-h-chamberlain** [vscode-neovim/vscode-neovim#1739]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

NVIM v0.9.4

### Operating system/version

macOS 13.6.3 (22G436

### Describe the bug

Possibly related to #1625 although I can't be sure. I think I started seeing this behavior around 1.3.0 maybe?

Basically, any kind of delay in `init.lua` or neovim startup seems like it can cause this. My `init.lua` is not trivial, but I was able to reproduce with a simple `:sleep`, so I think this issue probably has a good chance of affecting most users.

What happens is that the extension seems to give out color highlighting that matches `neovim` default colors, instead of letting VSCode decide what theme, etc. to render. Forcing a redraw somehow (moving the cursor, scrolling etc.) reverts back to VSCode colors.

Example with a bare bones config, `neovimClean` turned on and no other extensions:

https://github.com/vscode-neovim/vscode-neovim/assets/11131775/d727ec0c-7435-463a-a13b-de234ce8524c

This seems most noticeable when restarting the extension, but opening new buffers can also trigger it, and I see it periodically as I am moving between files in my normal workflows.

Edit: for reference, these are colors I get when opening in a terminal with `nvim --clean`:

![Screenshot 2024-01-11 at 14 28 53](https://github.com/vscode-neovim/vscode-neovim/assets/11131775/84df682a-3a4f-48aa-bba5-94c59315abd3)

I believe the VSCode colors are lightened due to VSCode's minimum contrast ratio, but I'm not 100% sure.

### Steps To Reproduce

1. Configure an `init.lua` or `afterInitConfig` that takes a non-trivial amount of time, e.g. `:sleep 1`
2. Open a filetype that `neovim` natively supports syntax highlighting for, e.g. `go`, `js`, probably lots of other choices
3. Restart the extension, if necessary

Repeating these steps a few times seems to reproduce pretty reliably for me.

### Expected Behavior

Default VSCode syntax highlighting is used all the time, not just on a redraw. Custom highlights from neovim should still be used, but I think for regular old syntax highlighting most users probably want to let VSCode take priority rather than using `neovim` defaults.

Maybe this is just a timing thing, and whatever is causing the correct coloring after redraw should also be triggered after `init.lua` finishes, or something like that? Of course ideal is to have no color flickering at all, but even just a "manual" redraw at the right time might make this issue mostly go away.

**Comment by justinmk** [comment]
Try `CTRL-L` as a workaround.

**Comment by ian-h-chamberlain** [comment]
Just encountered this on a file by chance, and seems like <kbd>ctrl+L</kbd> doesn't work, but e.g. scrolling with <kbd>ctrl+D</kbd>/<kbd>ctrl+U</kbd> does force a resync of the highlight and I get regular vscode colors back.

I wonder if there is some kind of dummy autocmd that could be used to force a redraw after a short delay...

**Comment by xiyaowong** [comment]
@ian-h-chamberlain Is this issue still present? If it is, please try adding the following code to the setup function
https://github.com/vscode-neovim/vscode-neovim/blob/c5b72fbd4c40900b38295f07c9e5489e7b39b3f9/runtime/lua/vscode-neovim/highlight.lua#L164
```lua
  setup_globals()
  setup_syntax_overrides()
  setup_syntax_groups()
```

**Comment by ian-h-chamberlain** [comment]
@xiyaowong nice find! 

With that change, I am unable to reproduce by introducing delays in my `init.lua`, for example:
```lua
	local vscode_neovim = require("vscode-neovim")
    os.execute('sleep 5')
    vscode_neovim.notify('finished sleeping!')
```

However, I can still reproduce the problem if `vscode-neovim.afterInitConfig` introduces delays, for example:
```json
{
    "vscode-neovim.neovimClean": true,
    "vscode-neovim.afterInitConfig": [
        ":sleep 1",
        ":lua require('vscode-neovim').notify('done afterInitConfig')"
    ],
}
```

I am guessing this has to do with the ordering of the highlight autocmd vs the `VscodeGeneral` one, but maybe you or someone else who knows more about it could figure out the difference.

In the meantime I think the fix you proposed is still an improvement, since I don't personally use `afterInitConfig`. Nice!

**Comment by ian-h-chamberlain** [comment]
Hmm, I think this issue has returned in some form recently, possibly due to some of the changes around highlighting like #1940 

In some cases now, it's actually worse because it seems like the "default" nvim highlighting gets redrawn _after_ whatever else, so issuing a `:redraw` or clicking/moving the cursor (like in the recording on this isssue) no longer restores the VSCode colors...

Should I file a new issue to track this? Meanwhile I'll try to figure out a reliable reproduction, since it seems like the original method I used when filing this issue doesn't reproduce any more.

**Comment by ollien** [comment]
@ian-h-chamberlain Yeah, I've noticed this too (often displayed as a "flash", but I often see it in the preview window when clicking on a definition). I'll admit, I'm not the most familiar with the handling of the syntax coloring, so I'm not sure exactly what to look at. If you can find a reliable repro, please open a new issue.

**Comment by ollien** [comment]
@ian-h-chamberlain I've found what I believe to be a consistent reproducer, though admittedly it's not in the main buffer (but I would imagine there are similar root-causes). Can you tell me if the reproduction in #1963 works for you as well?
