### ISSUE TITLE
feature: add <C-d>/<C-u> to scroll hover widget

### ISSUE THREAD

**Issue by xudyang1** [vscode-neovim/vscode-neovim#1743]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

Currently, only `<C-f>` and `<C-b>` are supported in hover widget, `<C-d>` and `<C-u>` are reasonable alternatives.

### Describe the solution you'd like

In normal mode press `shift + k` twice to focus on hover widget, then press `<C-d>` to scroll pagedown the hover widge, press `<C-u>` to scroll pageup the hover widget.

### Describe alternatives you've considered

In neovim, `<C-f>/<C-b>` and `<C-d>/<C-u>` are good alternatives for page scroll.

**Comment by xiyaowong** [comment]
Please define these bindings in your own keybindings.json. Binding is not a solution to scrolling.
