### ISSUE TITLE
bug: Specific Japanese character could not be yanked/pasted (E353)

### ISSUE THREAD

**Issue by fumiaki05** [vscode-neovim/vscode-neovim#1745]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [x] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

v0.9.4

### Operating system/version

14.2.1(23C71)

### Describe the bug

# Description:

I am experiencing a paste error with Japanese characters in Neovim. When I try to paste a string that contains the Japanese character "フ" followed by a newline and another Japanese character "の", I receive the error message "E353: Nothing in register "".

The string is correctly saved in the register, as shown by the output of the :registers command:

```
Type  Name  Content
  l  ""   フ^J
```
However, when I try to paste the string, I receive the error message.

This behavior is not consistent. If I change the character after "フ" to "て", the paste works correctly.

I have also tried this in Warp (Terminal) and Windows-based Vscode-Neovim, but the problem does not occur in those environments.

# Steps to reproduce:

- Open a new file in Neovim.
- Write "フの"　or "フ"(and create new line)
- Do `yyp`

### Steps To Reproduce

- Open a new file in Neovim.
- Write "フの"　or "フ"(and create new line)
- Do `yyp`

### Expected Behavior

yyp works correctly for the line which contains "フの"　Characters

**Comment by xiyaowong** [comment]
Can't reproduce

![a](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/0e838cfc-d28e-4834-a36c-f9d0c5db090d)

**Comment by fumiaki05** [comment]
Thank you for checking.
Hmm.. it's strange but can be my environment probrem.

https://github.com/vscode-neovim/vscode-neovim/assets/23501475/ee02eabd-1868-4d27-bab6-394e16861994

**Comment by fumiaki05** [comment]
I think I found the cause.
I am using Japanese OS settings on my Mac, but I added the following code to set neovim to English.
$ vim.cmd('language en_US')$

When I deleted the code, the status display in neovim returned to Japanese, but pasting was possible. 
Could you please confirm if this can be reproduced?

**Comment by xiyaowong** [comment]
If this issue still exists, please let me know, and I'll reopen this issue.
