### ISSUE TITLE
feature: add scrolling keybindings to suggestion details

### ISSUE THREAD

**Issue by xudyang1** [vscode-neovim/vscode-neovim#1746]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

Intellisense suggestion details display [quick info](https://code.visualstudio.com/docs/editor/intellisense#_intellisense-features) for autocompletes. Horizontal scroll or vertical scroll may be need when the quick info content is large.

### Describe the solution you'd like

`selectNextPageSuggestion` can be used to scroll pagedown in suggestion detail widget if the focus is on the widget. `toggleSuggestionFocus`  toggles focus between the suggestion and the quick info.

To scroll pagedown the quick info, we can press `ctrl+alt+space` (`toggleSuggestionFocus`), and then press `ctrl+d` (mapped to `selectNextPageSuggestion`)
```json
  {
    "key": "ctrl+d",
    "command":  "selectNextPageSuggestion",
    "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus || suggestWidgetVisible && textInputFocus && !suggestWidgetHasFocusedSuggestion"
  },
  {
    "key": "ctrl+u",
    "command": "selectPrevPageSuggestion",
    "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus || suggestWidgetVisible && textInputFocus && !suggestWidgetHasFocusedSuggestion"
  },
```

## Known Limitations
1. the above keybindings does not work when suggest widget contains only single suggestion ([vscode issue](https://github.com/microsoft/vscode/issues/146787))
2. horizontal scroll does not work with `scrollRight` command ([vscode issue](https://github.com/microsoft/vscode/issues/202466))
  - workaround: `shift` with mouse scroll can be used to horizontally scroll when mouse is on the quick info

### Describe alternatives you've considered

Apply `runCommands` for multiple commands avoids the need to press `ctrl+alt+space`:
```json
  // vertical scrolls in suggestion detail (only work for multiple suggestions)
  {
    "command": "runCommands",
    "key": "ctrl+d",
    "args": {
      "commands": [
        "toggleSuggestionFocus",
        "selectNextPageSuggestion",
        "toggleSuggestionFocus"
      ]
    },
    "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus || suggestWidgetVisible && textInputFocus && !suggestWidgetHasFocusedSuggestion"
  },
  {
    "command": "runCommands",
    "key": "ctrl+u",
    "args": {
      "commands": [
        "toggleSuggestionFocus",
        "selectPrevPageSuggestion",
        "toggleSuggestionFocus"
      ]
    },
    "when": "suggestWidgetMultipleSuggestions && suggestWidgetVisible && textInputFocus || suggestWidgetVisible && textInputFocus && !suggestWidgetHasFocusedSuggestion"
  },
```

**Comment by xiyaowong** [comment]
I think this keybinding is very useless. I suggest defining it in your own configuration.

**Comment by xudyang1** [comment]
> Not everyone needs this. I suggest defining it in your own configuration.

Sure, the scroll functionality is not very common in daily usage, so I did not make a pull request this time. This post is just for people who seek for the minor enhancement in viewing source code from the quick info widget. Closing the issue since `i_ctrl-d` and `i_ctrl-u` behaves differently when suggestion widget is visible.
