### ISSUE TITLE
:number and :relativenu not working

### ISSUE THREAD

**Issue by jamochl** [vscode-neovim/vscode-neovim#175]
Hi! Just coming over from the popular Vim extension and so far things are mostly fantastic. However, there seems to be just a couple of quality of life things that would make the package better.

First is possibly tying :nu and :rnu to the line numbers of vscode. I like to change between relative number and number sometimes in the Vim extension, and giving neovim this ability would be great.

The most pressing issue however, is the inability to view :reg, :ju :ls, and other long line outputs, which does work with the popular vim extension. I've seen that the developer is planning to work on this feature, so i'm just putting this out to again express interest :)

Great work guys!

**Comment by asvetliakov** [comment]
>First is possibly tying :nu and :rnu to the line numbers of vscode. I like to change between relative number and number sometimes in the Vim extension, and giving neovim this ability would be great.

As i know there is no default built-in command to change the line numbering, but you can do the trick by installing something like [settings-toggle](https://marketplace.visualstudio.com/items?itemName=Ho-Wan.setting-toggle), then binding command from neovim to call an extension command to toggle line numbers, e.g.:

```vim
command! Nu call VSCodeNotify('extension.toggle') " This is above extension command, assuming you configured it to toggle relative/non-relative line numbers
AlterCommand nu Nu
AlterCommand rnu Nu
```

>view :reg, :ju :ls, and other long line outputs

Related #78

**Comment by lubaroli** [comment]
Related to this, as a new user coming from the Vim extension as well, it would be awesome if there was an option to automatic toggle the line numbering in normal (relative) and insert (absolute).

And yes, congrats for the extension, truly awesome!

**Comment by asvetliakov** [comment]
@lubaroli Using the method above you can try to use `autocmd InsertEnter` and `autocmd InsertLeave`

**Comment by theol0403** [comment]
Perhaps this functionality can instead be added to the plugin? Example implementation here:
https://github.com/VSCodeVim/Vim/pull/5010/

Advantages:
- does not rely on an external settings toggle plugin
- does not get out of sync, because rather than toggle, it specifies the mode it wants.
- works between editors?
- works without changing settings file?

It would also be doable to use this functionality to implement the commands requested by OP, and leave the auto-switching to the dedicated vim plugin you would use in bare vim.

**Comment by asvetliakov** [comment]
Good points. Good way then is to support separate extension command which you can trigger from neovim's `autocmd` by `VSCodeExtensionNotify()`. Although vscode settings option is viable too

**Comment by theol0403** [comment]
I have drafted a PR in #656. I don't know if there is a way to integrate it with existing vim plugins where `set rnu` would just magically send a command to vscode.

**Comment by floriansto** [comment]
My current solution is the following (tweaked https://github.com/asvetliakov/vscode-neovim/issues/175#issuecomment-584121898 a bit):

I use the **Settings Cycler** extension from here: [https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-settings-cycler](https://marketplace.visualstudio.com/items?itemName=hoovercj.vscode-settings-cycler)

In your `init.vim` add:
```vim
if exists("g:vscode")
    command! Nu call VSCodeCall('settings.cycle.relativeLineNumbers')
    autocmd InsertEnter * :Nu
    autocmd InsertLeave * :Nu
endif
```

Then register the command in the `settings.json`
```json
{
    "editor.lineNumbers":"relative"
    "settings.cycle": [
            {
                "id": "relativeLineNumbers",
                "overrideWorkspaceSettings": false,
                "values": [
                    {
                        "editor.lineNumbers": "on"
                    },
                    {
                        "editor.lineNumbers": "relative"
                    }
                ]
            }
        ],
}
```

Only downside is, that all open windows have the same line number setting. Means if you switch to edit mode in one open editor, all other editors switch to absolute line numbers as well.

**Comment by theol0403** [comment]
@justinmk is there a way to listen to editor line number configuration change? I saw that there is a settings changed event in the UI protocol, but that it doesn't fire for rnu. If so, functionality could be added that lets vim plugins who modify the line numbers to work in vscode out of the box.

**Comment by justinmk** [comment]
> a way to listen to editor line number configuration change?

Can listen to the `OptionSet` autocmd.

**Comment by oiiiiiiii** [comment]
> > a way to listen to editor line number configuration change?
> 
> Can listen to the `OptionSet` autocmd.

How would I do that?

**Comment by justinmk** [comment]
> The most pressing issue however, is the inability to view :reg, :ju :ls, and other long line outputs

Those work since https://github.com/vscode-neovim/vscode-neovim/pull/881
