### ISSUE TITLE
[Bug] `ci'`, cursor jumps to the end of line

### ISSUE THREAD

**Issue by wenfangdu** [vscode-neovim/vscode-neovim#1752]
OS: macOS 14
nvim: 0.9.5
vscode-nvim: 1.5.0

vscode-neovim behavior (cursor jumps to the end of the line):

https://github.com/vscode-neovim/vscode-neovim/assets/28700378/238e82cd-8bfc-4e7b-a25d-1cc9b2758bde

Neovim behavior (cursor stays inside the quotes):

https://github.com/vscode-neovim/vscode-neovim/assets/28700378/b71d0191-ddeb-4c1e-8063-e4bf10b39f83

Code:

```styl
$base = '../rewards'
$bgi = $proxy($base, 'bgi')

@import '../includes/highlight.styl'

.open-task-btn
  $bgi '../static/rewards/open-tasks-btn-double.png'
  $highlight '../static/rewards/open-tasks-btn-double.png'
```

**Comment by xiyaowong** [comment]
#1080 Still can't reproduce

**Comment by wenfangdu** [comment]
@xiyaowong I tried disabling all extensions except vscode-neovim, but the issue still persists.

**Comment by xiyaowong** [comment]
OS: windows 11
All are the latest versions

**Comment by KeqiZeng** [comment]
Facing same issue on MacOS 14.2.1

**Comment by wenfangdu** [comment]
@xiyaowong Confirmed, both #1752 and #1080 are not reproducible on Windows 11 but reproducible on macOS 14, all other related apps are the latest.

**Comment by ollien** [comment]
FWIW, I've tried to replicate this on Linux, and could not. I guess it's macOS specific?

**Comment by wenfangdu** [comment]
@ollien Thanks for the experiment, looks like it is.

**Comment by xiyaowong** [comment]
Please confirm if the issue still exists

**Comment by wenfangdu** [comment]
@xiyaowong Still exists.

**Comment by wenfangdu** [comment]
@xiyaowong I just upgraded  vscode-nvim to 1.14.1, and it's still reproducible with `ci'`, please reopen this issue:

https://github.com/vscode-neovim/vscode-neovim/assets/28700378/251235e3-2b21-4465-b4b7-6d0a11da3577

**Comment by xiyaowong** [comment]
Could you provide more logs and a complete screen recording? When does the issue occur, and when does it function normally? A single screen recording like this is not helpful at all.

**Comment by wenfangdu** [comment]
@xiyaowong I tried, but there's no log, full repro that contains cases that work and don't work:

https://github.com/vscode-neovim/vscode-neovim/assets/28700378/221ec36d-4018-485f-8095-efee0cfffa35

**Comment by wenfangdu** [comment]
@xiyaowong I tried, but there's no log, full repro that contains cases that work and don't work:

https://github.com/vscode-neovim/vscode-neovim/assets/28700378/221ec36d-4018-485f-8095-efee0cfffa35

Could it be a race condition? As you can see in the recording, the cursor jumps to the end of line, then jumps back (work), sometimes it doesn't jump back or _**might jumped back first and then jumped to the end of line**_ (don't work).

Please reopen this.

**Comment by wenfangdu** [comment]
@xiyaowong I tried, but there's no log, full repro that contains cases that work and don't work:

https://github.com/vscode-neovim/vscode-neovim/assets/28700378/221ec36d-4018-485f-8095-efee0cfffa35

Could it be a race condition? As you can see in the recording, the cursor jumps to the end of line, then jumps back (work), sometimes it doesn't jump back or _**might jumped back first and then jumped to the end of line**_ (don't work).

Play this clip in x0.5 speed, you'll see:

https://github.com/vscode-neovim/vscode-neovim/assets/28700378/fd1f77a3-853e-4230-8c61-995d346406ec

Please reopen this.

**Comment by xiyaowong** [comment]
> Could it be a race condition? As you can see in the recording, the cursor jumps to the end of line, then jumps back (work)

Expected

**Comment by xiyaowong** [comment]
I don't understand why only your environment has this issue. I'll fix it when I encounter the problem myself. No need to open it.

**Comment by wenfangdu** [comment]
@xiyaowong Could it because _the cursor jumped back first and then jumped to the end of line_?

![image](https://github.com/vscode-neovim/vscode-neovim/assets/28700378/df5d49e0-47fa-4b1b-8811-f6c40dbcc6e3)

This dev has it too, so not an exception.

**Comment by wenfangdu** [comment]
@xiyaowong Could it because _the cursor jumped back first and then jumped to the end of line_?

![image](https://github.com/vscode-neovim/vscode-neovim/assets/28700378/df5d49e0-47fa-4b1b-8811-f6c40dbcc6e3)

This dev has it too, so not an exception.

Also, check [the full message](https://github.com/vscode-neovim/vscode-neovim/issues/1752#issuecomment-2143278911), I've updated it multiple times.

**Comment by wenfangdu** [comment]
> > Could it be a race condition? As you can see in the recording, the cursor jumps to the end of line, then jumps back (work)
> 
> Expected

@xiyaowong Where's the code controls that? I can add logs there.

**Comment by xiyaowong** [comment]
Try changing option: `vscode-neovim.normalSelectionDebounceTime`

**Comment by wenfangdu** [comment]
@xiyaowong Yeah, setting `"vscode-neovim.normalSelectionDebounceTime": 100` seems to have fixed it, the default is `50`, I thought it would be caused by something like this, race condition indeed. 🎉🎉🎉

**Comment by wenfangdu** [comment]
Side note: slower computers might be less likely to have this issue, my old Windows laptop doesn't have it, but the m1 mac has it.

**Comment by xiyaowong** [comment]
Not accurate. There are many vscode-neovim users, but currently only two have reported this issue.

After so long, from the test, it is indeed unstable on macOS, and the test often fails for no reason.
