### ISSUE TITLE
bug: weird outdent when pressing `esc`

### ISSUE THREAD

**Issue by wenfangdu** [vscode-neovim/vscode-neovim#1753]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.5

### Operating system/version

macOS 14

### Describe the bug

In some cases, when pressing `esc`, `                          foo` becomes `foo`.

### Steps To Reproduce

https://github.com/vscode-neovim/vscode-neovim/assets/28700378/a148ccf4-7702-42a8-a73b-9e5202c19dbe

### Expected Behavior

When pressing `esc`, `                          foo` should be left intact.

**Comment by xiyaowong** [comment]
Can't reproduce. Can you check that the content of the current buffer is consistent with the content in vscode?

**Comment by wenfangdu** [comment]
@xiyaowong How to check what's inside the current buffer?

**Comment by xiyaowong** [comment]
`echo nvim_buf_get_lines(0, 0, -1, v:false)`

**Comment by wenfangdu** [comment]
@xiyaowong When pasting `                          foo`, vscode is in insert mode, nvim commands can't be run, and the leading spaces are removed when entering normal mode.

**Comment by xiyaowong** [comment]
You can create a temporary keybinding and call the vscode-neovim.lua command

**Comment by wenfangdu** [comment]
@xiyaowong I added this keybinding:
```json
  {
    "key": "ctrl+;",
    "command": "vscode-neovim.lua"
  }
```
When pressing it, vscode sends:
![image](https://github.com/vscode-neovim/vscode-neovim/assets/28700378/7e80187c-cb69-47ad-b586-01478db318a4)

**Comment by wenfangdu** [comment]
@xiyaowong Now it prints a table name 😕 
![image](https://github.com/vscode-neovim/vscode-neovim/assets/28700378/267e7811-72bf-4c98-844a-5bec6fcc5bac)

**Comment by xiyaowong** [comment]
Use `vim.print`

**Comment by wenfangdu** [comment]
@xiyaowong With:
```json
  {
    "key": "ctrl+;",
    "command": "vscode-neovim.lua",
    "args": "vim.print(vim.api.nvim_buf_get_lines(0, 0, -1, false))"
  }
```

https://github.com/vscode-neovim/vscode-neovim/assets/28700378/743215fe-86a2-448b-a205-40662e8c54be

Notice after pressing `esc`, the leading spaces are removed from the printing.

**Comment by wenfangdu** [comment]
@xiyaowong Bro, can you reproduce now?
