### ISSUE TITLE
feature: Support browsing previous inputs of command line, forward search, backward search

### ISSUE THREAD

**Issue by taquangtrung** [vscode-neovim/vscode-neovim#1758]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

When using Neovim, I can use `Ctrl-p`, `Ctrl-n` to browse the history (previous/next inputs) of the 3 functionalities: command line (`:`), forward search (`/`), and backward search (`?`).

I investigated and it seems that VSCode Neovim doesn't support this feature yet.

### Describe the solution you'd like

Can a similar feature in Neovim be implemented in VSCode Neovim? That is, to use `Ctrl-p`, `Ctrl-n` to browse the previous/next inputs for the command line (`:`), forward search (`/`), and backward search (`?`

### Describe alternatives you've considered

N/A

**Comment by xiyaowong** [comment]
This feature is already supported

**Comment by taquangtrung** [comment]
Oh, thanks for pointing that out. Turned out, I had these settings that overrode VSCode Neovim's `Ctrl+p`, `Ctrl+n`:

```json
    {
        "key": "ctrl+n",
        "command": "workbench.action.quickOpenSelectNext",
        "when": "inQuickOpen && neovim.mode != 'cmdline_insert' && neovim.mode != 'cmdline_normal' && neovim.mode != 'cmdline_replace'"
    },
    {
        "key": "ctrl+p",
        "command": "workbench.action.quickOpenSelectPrevious",
        "when": "inQuickOpen && neovim.mode != 'cmdline_insert' && neovim.mode != 'cmdline' && neovim.mode != 'cmdline_replace'"
    },

```

I can't remember why I used the condition `neovim.mode != 'cmdline_insert' && neovim.mode != 'cmdline' && neovim.mode != 'cmdline_replace'` previously, as I copied it some where from Neovim default setting.

But after changing to `neovim.mode != 'cmdline'`, then it won't override VSCode Neovim's `Ctrl+p`, `Ctrl+n`:
