### ISSUE TITLE
feature: Inspect vscode state by expanding the lua API

### ISSUE THREAD

**Issue by mbway** [vscode-neovim/vscode-neovim#1760]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

There are several situations where having more access to the vscode state in neovim/lua would be beneficial to configure
the editor in the ways that I want. (I hope I'm not missing something but I don't think this is possible yet)

For example, I would like to create a keybinding to toggle something but vscode only provides a pair of actions to do and undo something instead of also providing an action to toggle. I would like to be able to say:
```lua
-- toggle pinning the current tab
vim.keymap.set('n', '<leader>1', function()
    if tab_is_pinned() then
        vscode.action('workbench.action.unpinEditor')
    else
        vscode.action('workbench.action.pinEditor')
    end
end)

-- toggle between terminal and editor (hypothetical example.
-- I'm not sure if vscode neovim can handle keys when inside the terminal)
vim.keymap.set('n', '<C-t>', function()
    if terminal_is_active() then
        vscode.action('workbench.action.focusActiveEditorGroup')
    else
        vscode.action('workbench.action.terminal.focus')
    end
end)

```
where `terminal_is_active()` and `tab_is_pinned()` is what I am having difficulty with.

This is achieved in native vscode using the `editorTextFocus/terminalFocus` and `activeEditorIsPinned` context values respectively in the `when` part of a keybinding in `keybindings.json`.

It seems like the decision was made where extensions aren't able to access this context information: https://github.com/microsoft/vscode/issues/117980 but it looks like it would be possible to get some of the same information from the [vscode-api](https://code.visualstudio.com/api/references/vscode-api) eg `vscode.window.tabGroups.activeTabGroup.activeTab.isPinned` for `activeEditorIsPinned` and `vscode.window.activeTerminal != null` for `terminalFocus`

Another example is that I wanted to get the path of the document to be able to have a keybinding for running an autoformatting program. I wrote the following to parse the path from the neovim side:
```lua
function decode_percent_encoding(input)
    local converted = string.gsub(input, "%%(%x%x)", function(hex) return string.char(tonumber(hex, 16)) end)
    return converted
end

function current_path()
    local expected_prefix = '__vscode_neovim__-file://'
    local scratch_buffer_path = vim.fn.expand('%')
    local n = string.len(expected_prefix)
    if string.sub(scratch_buffer_path, 0, n) ~= expected_prefix then
        return nil
    end
    local url_encoded_path = string.sub(scratch_buffer_path, n + 1)
    return decode_percent_encoding(url_encoded_path)
end
```
but accessing it via `window.activeTextEditor.document.fileName` would be easier.

Would it be possible to query these vscode objects from lua? I assume this is possible in theory as the extension on the vscode side has access.

### Describe the solution you'd like

Ideally, I would like to interact with objects available to vscode extensions from neovim using the lua API that this extension provides.

I'm not sure of the details, but perhaps a proxy object could be created on the lua side that when a property is accessed it does an rpc call to fetch the value from vscode. Kind of like how [multiprocessing proxies](https://docs.python.org/3/library/multiprocessing.html#proxy-objects) allow for somewhat transparent access to objects from another process.

```lua
-- hypothetical example of what could be possible
local active_editor = vscode.get('window.activeTextEditor')
if active_editor ~= nil then
    -- corresponding to window.activeTextEditor.document.fileName
    vscode.notify('current file: ' .. active_editor:document():fileName())
end
```
but even a more limited hard coded API giving access to the most useful parts of the state would be much better than nothing.

### Describe alternatives you've considered

I tried adding keybinding entries in `keybindings.json` like
```json
    {
        "key": ", 1",
        "command": "workbench.action.unpinEditor",
        "when": "activeEditorIsPinned"
    },
    {
        "key": ", 1",
        "command": "workbench.action.pinEditor",
        "when": "!activeEditorIsPinned"
    },
```
but after doing this it seems that vscode wants to handle all key combinations starting with `,` (my leader key) so all my neovim leader bindings stop working. Even if this solution did work it would mean splitting the configuration across
multiple files and is less flexible than having access from lua.

**Comment by theol0403** [comment]
Yes, the infrastructure is there to easily add this. Look at `vscode.get_config()`. Just need a handler on the extension side to expose the vscode API.

**Comment by mbway** [comment]
Ok. I may put together a PR when I have the time

**Comment by mbway** [comment]
for anyone interested, with `vscode.eval` I can now write the following and it works great :slightly_smiling_face: 
```lua
vim.keymap.set('n', '<leader>1', function()
    vscode.eval_async([[
        if (vscode.window.tabGroups.activeTabGroup.activeTab.isPinned) {
            await vscode.commands.executeCommand('workbench.action.unpinEditor');
        } else {
            await vscode.commands.executeCommand('workbench.action.pinEditor');
        }
    ]])
end)

```

**Comment by justinmk** [comment]
Is there anything we can remove/delete now that we have "eval"?

**Comment by mbway** [comment]
I think the answer is 'yes' but it depends on what you are looking for. I have already replaced some of the simple hard-coded actions with eval. Replacing the remaining ones would require more significant changes. For example the `*_config` actions could be replaced with eval if the logic in those actions were put into a class accessible from eval. Taken all the way, all the actions other than eval could be removed which might simplify the `ActionManager`.

I haven't looked through the whole codebase so I don't know if there are places other than `actions.ts` where eval is useful.

**Comment by justinmk** [comment]
> all the actions other than eval could be removed which might simplify the `ActionManager`.

If "eval" ends up being reliable, then we should be able to implement the `_config` interface in Lua (by calling "eval"). And then, AFAICT, `ActionManager` serves no real purpose (and isn't clearly documented as to what its purpose is).
