### ISSUE TITLE
bug: Scramble when highlighted

### ISSUE THREAD

**Issue by Cheney-Xu** [vscode-neovim/vscode-neovim#1766]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9.2

### Operating system/version

win 11

### Describe the bug

In the C language environment,When I search for a word using *,It will have garbled characters


![bug](https://github.com/vscode-neovim/vscode-neovim/assets/11714643/e2b6011b-2e6a-4043-8c06-85d83d8fc794)

### Steps To Reproduce

nomal mode

### Expected Behavior

fix this bug

**Comment by girving** [comment]
Another example screenshot.  Typically I search for something, it starts with lovely highlighting, and then the highlighting gets blurrier and blurrier as I edit until I clear the search.

![Weird highlight screenshot](https://github.com/vscode-neovim/vscode-neovim/assets/70511/2db82052-45d0-4b6b-b581-1d922592f2f1)

The neovim vscode plugin is otherwise terrific, by the way: significant improvement over the standard one.

**Comment by justinmk** [comment]
Workaround is to hit CTRL-L to force a redraw.

**Comment by justinmk** [comment]
> The neovim vscode plugin is otherwise terrific, by the way: significant improvement over the standard one. ❤️

The "standard" one doesn't have all your Nvim plugins. This issue could likely be avoided if you disable the plugin(s) that cause the highlighting. 

Did you try with the `neovimClean` vscode option?

**Comment by mbway** [comment]
this issue occurs even with an empty init script or when using `neovimClean` 
![image](https://github.com/vscode-neovim/vscode-neovim/assets/4923501/cbe34145-4b99-4648-9e5b-3b8e655ef64e)
also tested with a brand new user account with empty settings.json and empty neovim configuration
![Screenshot_20240131_200508](https://github.com/vscode-neovim/vscode-neovim/assets/4923501/e42b56ad-e04b-4cc5-acc0-f32490ffbb3c)

OS: Arch linux
Desktop: KDE Plasma 5
vscodium: 1.85.2
neovim: 0.9.5

**Comment by woodchuck** [comment]
I had some form of this issue. I was using neovim 0.6 and upgrading to 0.10(pre-release) resolved it. 0.9 is the minimum required per the docs.

**Comment by loxcel** [comment]
Workaround: Revert to "VSCode Neovim" version 0.7.0
How: right click on "VSCode Neovim" under VSCode's EXTENSIONS pane and select "Install another version..."

I experience this annoying bug with plugin version 1.8.1 and VSCode 1.88.0 under Fedora 39.

The bug might be related to fix #1449 released as version 0.8.0:
https://github.com/vscode-neovim/vscode-neovim/pull/1449

**Comment by ollien** [comment]
This may have been addressed by version 1.8.3. Can you give that a whirl and let me know if you still experience issues (even better if it's in a reproducible way)?

**Comment by loxcel** [comment]
> Can you give that a whirl

I'm running these versions, but the letter corruption remains:
- VSCode Neovim v1.8.3
- Visual Studio Code 1.88.1
- Fedora Core 39

These screenshots show how it should look and how it does look when I search for "uint32":
![Screenshot from 2024-04-19 14-29-29](https://github.com/vscode-neovim/vscode-neovim/assets/40441828/db298c7c-820f-4cd3-a955-bd31ef290e8a)
![Screenshot from 2024-04-19 14-29-29](https://github.com/vscode-neovim/vscode-neovim/assets/40441828/baf50fb4-43f9-4e1f-84d3-7d07fba16b1f)

**Comment by ollien** [comment]
That's very strange. I definitely don't experience that locally if I type `/uint32<enter>` in a buffer containing the text in that screenshot. Is this with a clean `init.vim`/`neovimClean` enabled? 

What's interesting to me is your decorations on the highlights look a bit different than mine (they're "outlined" rather than highlighted), which makes me wonder if some customization is exacerbating this effect.

**Comment by loxcel** [comment]
> if some customization is exacerbating this effect.

Possibly.

> Is this with a clean init.vim/neovimClean enabled?

I believe so. See below.

A section from settings.json:

```
{
    "editor.formatOnPaste": false,
	"editor.autoClosingComments": "never",
	"editor.autoClosingQuotes": "never",
	"editor.autoIndent": "none",
	"editor.autoSurround": "never",
	"C_Cpp.commentContinuationPatterns": [ "" ],
    "editor.formatOnSave": false,
	"editor.formatOnType": false,
    "editor.useTabStops": true,
    "editor.tabSize": 4,
    "editor.insertSpaces": false,
	"java.debug.settings.numericPrecision": 18,
	"java.debug.settings.showHex": false,
	"java.debug.settings.showStaticVariables": true,
	"files.exclude": {
		"**/*.o": true
	},
	"workbench.colorCustomizations": {
		"editor.findMatchBackground": "#80000000",
		"editor.findMatchBorder": "#707000",
		"editor.findMatchHighlightBackground":"#80000000",
		"editor.findMatchHighlightBorder": "#707000",
		"editor.background" :"#000000",
		"sideBar.background": "#000000",
		"activityBar.background":"#000000",
		"commandCenter.background": "#000000",
		"statusBar.background": "#000000",
		"terminal.background": "#000000"
	},
	"terminal.integrated.scrollback": 10000000,
	"vscode-neovim.neovimExecutablePaths.linux": "/usr/bin/nvim",
	"vscode-neovim.neovimClean":true,
	"vscode-neovim.normalSelectionDebounceTime":20,
	"C_Cpp.default.cppStandard": "c++20",


```

**Comment by Cheney-Xu** [comment]
This problem still exists on 1.8.3
![图片](https://github.com/vscode-neovim/vscode-neovim/assets/11714643/8db02743-9d19-408a-9c83-68e7a0668fcc)

My C language code is as follows

#include "miio_define.h"
#include "miio_api.h"
#include "miio_uart.h"
#include "arch_dbg.h"
#include "iid.h"
#include "user_app_func.h"
#include "user_app_main.h"
#include <applet.h>

#include <GT_AppLight.h>

static uint8_t 		UP_Light_OnOff=10;
static uint8_t 		UP_Light_Mode=10;
static uint8_t 		UP_Light_Brightness=101;
static uint32_t 	UP_Light_ColorTemp=0;
static uint8_t 		UP_FlexSwitch_EN=10;
static uint8_t     	UP_light_pattern=10;

static uint8_t 		UP_Fan_OnOff=10;
static uint8_t 		UP_Fan_Speed=0;
static uint8_t 		UP_Fan_Direction=10;
static uint8_t 		UP_Fan_Wind_Mode=10;
static uint8_t 		UP_Fan_Shake_IfRun=10;

static uint8_t     	UP_Pre_OnOff=10;
static uint8_t     	UP_Pre_FanSpeed=0;
static uint8_t     	UP_Pre_LightBri=0;
static uint32_t    	UP_Pre_LightColorTemp=0;
static uint8_t     	UP_Pre_BellOnOff=10

**Comment by ollien** [comment]
@Cheney-Xu Does this happen every time you hit `*` on a variable on that file, or is there something else you're doing to reproduce it? I've not had the same luck reproducing it with Neovim 0.9.5 on Fedora 39+Extension 1.8.3

**Comment by Cheney-Xu** [comment]
Yes, it happens every time，You can try it with the following file
[user_app_main - 副本.txt](https://github.com/vscode-neovim/vscode-neovim/files/15048880/user_app_main.-.txt)

**Comment by Cheney-Xu** [comment]
My environment is win11,neovim0.10.0-dev++Extension 1.8.3.

**Comment by Cheney-Xu** [comment]
Change the tab indentation in front of the variable to a space and it will not appear.

**Comment by ollien** [comment]
Aha! I am able to reproduce this, thank you, I will take a look.

One interesting note is that if you don't have your highlight style set to one with borders, it doesn't really look "scrambled", as much as offset.

![image](https://github.com/vscode-neovim/vscode-neovim/assets/977151/77a62094-7f05-45fa-9a6f-6927f8b6017f)

**Comment by loxcel** [comment]
I upgraded to VSCode Neovim v1.9.0 and spent a minute searching for a few words, and "n"-nning to next matches.

Everything rendered as it should.

Thank you for identifying, applying and releasing the fix so quickly.
