### ISSUE TITLE
bug: JSX tags are highlighted incorrectly in .tsx files

### ISSUE THREAD

**Issue by OctarineSourcerer** [vscode-neovim/vscode-neovim#1767]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

NVIM v0.9.5

### Operating system/version

Arch Linux 6.7.0-arch3-1

### Describe the bug

In .tsx files - a mix between JSX and Typescript - the whole of a tag (and its contents) are displayed a uniform colour and underlined with squiggles.
![image](https://github.com/vscode-neovim/vscode-neovim/assets/6842867/0e5244b7-42a4-45e4-bd08-0df777418815)

Here's a more complex example that shows the issue more strongly:
![image](https://github.com/vscode-neovim/vscode-neovim/assets/6842867/6c20ec7b-dd75-43a4-801d-a3f02e11b37c)

Now, I *know* that it's surprising that it's this extension causing it, but I disabled all extensions and enabled one at a time until the culprit was reached. Enabling and disabling VSCode Neovim toggles the rendering issue. Here's the first file when VSCode Neovim (and only VSCode Neovim) is disabled. It renders correctly:
![image](https://github.com/vscode-neovim/vscode-neovim/assets/6842867/e4efeb55-bcf6-448c-aefa-3c24918d6346)

Interestingly, a completely commented-out `init.vim` still shows the same bug, but it appears a little differently.
![image](https://github.com/vscode-neovim/vscode-neovim/assets/6842867/4b424187-efd8-48d2-b6a7-62bcf4406213)

Let me know if you need anything more :)

### Steps To Reproduce

1. Create a .tsx file with the contents `<h1>I am a rendering bug</h1>`.
    * This can be any valid HTML tag I think, or any text inside the above h1, but there's an MVE
2. Open said file in VSCode. Tadaaa, rendering bug.

### Expected Behavior

I expect the different elements of a tag (angle brackets, closing slashes, name, properties) to all have their own individual colours, a la 
![image](https://github.com/vscode-neovim/vscode-neovim/assets/6842867/315e3e18-cae0-4d13-a79b-4b9f05d23050)

**Comment by justinmk** [comment]
Does this change anything?

```
:syntax off
:lua vim.treesitter.stop()
```

vscode-neovim tries to resolve highlights from Nvim, but that is very much best-effort. Is your issue different than the other existing highlighting issues: https://github.com/vscode-neovim/vscode-neovim/issues?q=is%3Aissue+is%3Aopen+highlight

**Comment by xiyaowong** [comment]
Related to [Why are my headings magenta?](https://github.com/vscode-neovim/vscode-neovim/discussions/1730)

**Comment by OctarineSourcerer** [comment]
> Does this change anything?
> 
> ```
> :syntax off
> :lua vim.treesitter.stop()
> ```
> 
> vscode-neovim tries to resolve highlights from Nvim, but that is very much best-effort. Is your issue different than the other existing highlighting issues: https://github.com/vscode-neovim/vscode-neovim/issues?q=is%3Aissue+is%3Aopen+highlight

Apologies for the slow response! I'm afraid nothing seems to change when running those commands.

I've tried restarting the extension as described in #1739 - the colours return to the _correct_ colours VSCode highlights with usually, and then back to the incorrect highlighting. I don't think it's this issue anyway - this one has the colours change to the nvim colours briefly, then back to VSCode ones, which is the other way around.

Running `:hi clear Title` as described in #1730 does nothing, though I don't know if I'm clearing the correct highlight group there. Running `:echo w:_vscode_hl_ns`  from within the incorrect highlight also gives me `2`.

So as far as I can tell, it's not the same as other highlighting issues.
