### ISSUE TITLE
"Failed to rename buffer" after relaunch with juptyer panel open

### ISSUE THREAD

**Issue by pinkfrog9** [vscode-neovim/vscode-neovim#1773]
### Did you check docs and existing issues?

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

1.5.0

### Operating system/version

MacOs 14.2.1

### Describe the bug

When relaunch vscode with juptyer interactive panel open, neovim will err.

### Steps To Reproduce

First, we have to make sure the juptyer interactive panel is open,
![image](https://github.com/vscode-neovim/vscode-neovim/assets/107285219/45ea0f87-f884-41f4-a07a-591659b4e64c)

And then, perform a relaunch of vscode,
you will see the error message:
![image](https://github.com/vscode-neovim/vscode-neovim/assets/107285219/cd37d839-f6b9-41cb-b131-7dd86aeccde9)

### Expected Behavior

There shall be no error

**Comment by justinmk** [comment]
> Neovim version (nvim -v)
> 1.5.0

?? That is not a valid nvim version.

**Comment by pinkfrog9** [comment]
Right. `NVIM v0.9.5`.
1.5.0 was the vscode-neovim version.
