### ISSUE TITLE
bug: different behavior with different delay when pressing g key in normal mode

### ISSUE THREAD

**Issue by shelper** [vscode-neovim/vscode-neovim#1775]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.9.1

### Operating system/version

ubuntu 22.04

### Describe the bug

i found any command in normal mode starts with g cause different behavior with different delay, 
for instance, if i want to comment a line, if i press 'gcc' fast enough, everything works, 
but if i press gcc very slow, e.g., 2 second between each char, then it does not comment the code

### Steps To Reproduce

normal mode, press 'g c c' with 2 second delay in-between each char, no line commented, rather it enters the operation mode

### Expected Behavior

normal mode, press 'g c c' with 2 second delay inbtween each char, shoudl also comment the line

**Comment by xiyaowong** [comment]
`:h timeoutlen`

[timeoutlen](https://neovim.io/doc/user/options.html#'timeoutlen')


Please learn the basic knowledge of Vim.
