### ISSUE TITLE
Init file loading?

### ISSUE THREAD

**Issue by benlieb** [vscode-neovim/vscode-neovim#1776]
### Check the following:

- [X] I have read all the vscode-neovim docs
- [X] I have searched the existing issues of vscode-neovim
- [X] I can reproduce the issue with an empty init.vim/init.lua and no other vscode extensions (when applicable)

### Neovim version (nvim -v)

0.9

### Operating system/version

Macos 13.2.1

I'm not sure that the extension is loading my init file at all. I've tried with just  `~/.config/nvim/init.lua` file, and I tried also with a near empty `~/.config/nvim/init.vim` file. Still seems to not be loading... I made sure they were not both present at the same time.

I'm at a loss for finding out how to debug this. When I put errors in my init files, I don't see any debug errors in vscode, but straight nvim complains...

I also tried to use the specific setting to no avail:

![image](https://github.com/vscode-neovim/vscode-neovim/assets/634562/276c0d96-a2c7-47ef-ac29-3e6b09e504a3)

Not sure what I'm missing...

![image](https://github.com/vscode-neovim/vscode-neovim/assets/634562/e80da2c6-fc82-4ad9-ac99-3199c3fa19af)
 
Files are in ~/.config/nvim:

<img width="564" alt="image" src="https://github.com/vscode-neovim/vscode-neovim/assets/634562/f7c0e988-7755-43cf-b65a-c1f2c356d3a7">

**Comment by justinmk** [comment]
what does `:echo $MYVIMRC` report using the `:` vscode-neovim prompt from vscode?

<img width="544" alt="image" src="https://github.com/vscode-neovim/vscode-neovim/assets/1359421/ab3e979d-aaaf-4f53-8c89-53e02fc84d67">

**Comment by justinmk** [comment]
Also try `:messages` (again, from the vscode-neovim `:` prompt in vscode)

**Comment by benlieb** [comment]
@justinmk 

:messages is empty

Logfile only shows one message in 2024:

![image](https://github.com/vscode-neovim/vscode-neovim/assets/634562/cb46b4b5-6fb4-45a0-8d05-8bddf59a306c)

**Comment by benlieb** [comment]
@justinmk In regular nvim:

<img width="718" alt="image" src="https://github.com/vscode-neovim/vscode-neovim/assets/634562/fa809e1f-6967-4104-af8c-5983cfc7b5b0">

**Comment by benlieb** [comment]
Technically `~/.config` is a symlink on my system into an icloud directory. This was working fine a month ago. But something has changed since then. Now nothing loads.

**Comment by benlieb** [comment]
I have tried to load directly `/Users/me/.vimrc` and it still doesn't seem to do anything

**Comment by benlieb** [comment]
I think I may have traced this back to the version of the extension. Anything after .8 seems to not work

**Comment by justinmk** [comment]
Try updating to Nvim 0.9.5 , no reason to use 0.9.0.

Is it possible you have set the `vscode-neovim.neovimClean` setting? Can you share your `vscode-neovim.*` settings from your vscode settings.json.

**Comment by benlieb** [comment]
Not sure how to get that file exactly.  Neovim Clean was checked

**Comment by xiyaowong** [comment]
@benlieb Please provide vscode-neovim's log

![image](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/802524fc-77f4-4a11-a751-db00f8c79328)

**Comment by justinmk** [comment]
> Not sure how to get that file exactly.

use google. if you don't know how to find the vscode settings.json I assume this is a user error and not going to spend more time on it.

**Comment by justinmk** [comment]
> * `:echo $NVIM_LOG_FILE` to get the Nvim log file path. Then see if it has any recent clues.
> * `:echo stdpath('config')`

After https://github.com/vscode-neovim/vscode-neovim/pull/1786 it will be easy to log info like that on startup.
