### ISSUE TITLE
bug: quickscope highlighting not working

### ISSUE THREAD

**Issue by TheDataSeneschal** [vscode-neovim/vscode-neovim#1778]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

NVIM v0.9.4

### Operating system/version

Windows 11

### Describe the bug

Quickscope highlighting is not showing up in the vs code. This has previously been mentioned here, but I couldn't understand the solution, so I would like some personalized help.

### Steps To Reproduce

I put this Plug 'unblevable/quick-scope' in my vscodeneovim.vim
:PlugInstall

### Expected Behavior

Quickscope highlighting should show up.

**Comment by xiyaowong** [comment]
https://github.com/unblevable/quick-scope/blob/master/doc/quick-scope.txt

**Comment by TheDataSeneschal** [comment]
Thanks :)
