### ISSUE TITLE
Cursor's position is wrong when press 'o' in normal mode

### ISSUE THREAD

**Issue by cy-by-side** [vscode-neovim/vscode-neovim#1780]
### Check the following:

- [ ] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [ ] I have read the vscode-neovim docs.
- [ ] I have searched existing issues.

### Neovim version (nvim -v)

NVIM v0.9.5

### Operating system/version

Arch Linux 6.7.2

### Describe the bug

Cursor's position is wrong when press 'o' in normal mode,
In NeoVim/Vim,
it should create a new line and then move to the new line

### Steps To Reproduce

when I press 'o', the cursor's position isn't change

### Expected Behavior

happen like NeoVim

**Comment by justinmk** [comment]
search existing, closed issues.
