### ISSUE TITLE
bug: Infinitely logging to BufferManager whenever specific actions occur

### ISSUE THREAD

**Issue by amin-hrp** [vscode-neovim/vscode-neovim#1788]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.9.5

### Operating system/version

MacOS 14.3

### Describe the bug

With `vscode-neovim.logLevel` set to `debug`, if I perform specific actions I see `2024-02-08 17:23:54.620 [info] BufferManager: received buffer event for vscode-neovim://2/<FILEPATH>%3Aasvetliakov.vscode-neovim.vscode-neovim` logged infinitely. It's much more easily reproduced if I use my current `init.vim` but it also seems to happen when I use `vscode-neovim.neovimClean` although I'm not entirely sure how to reproduce 100% when clean is on

This infinite looping causes my buffers to desync. My cursor will suddenly jump to somewhere else in the file, or `leap.vim` will stop working, or suddenly lines will change.

### Steps To Reproduce

I can reproduce pretty easily with my current `init.vim`:

1. Use `init.vim` below
2. Go to any file with groupings and change them using `surround.vim`. If you don't see the log outputs, try again a few times and they'll start up

```
call plug#begin()

Plug 'tpope/vim-surround'
Plug 'ggandor/leap.nvim'
Plug 'tpope/vim-repeat'

" Initialize plugin system
call plug#end()

runtime autoload/repeat.vim

set nu
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set clipboard+=unnamedplus

" Add default maps for leap
lua require('leap').add_default_mappings()

if exists ('g:vscode')
  xmap gc  <Plug>VSCodeCommentary
  nmap gc  <Plug>VSCodeCommentary
  omap gc  <Plug>VSCodeCommentary
  nmap gcc <Plug>VSCodeCommentaryLine
  " Use ctrl-[hjkl] to select the active split!
  nnoremap <silent> <c-k> :<C-u>lua require('vscode-neovim').call('workbench.action.focusAboveGroup')<CR>
  xnoremap <silent> <c-k> :<C-u>lua require('vscode-neovim').call('workbench.action.focusAboveGroup')<CR>
  nnoremap <silent> <c-j> :<C-u>lua require('vscode-neovim').call('workbench.action.focusBelowGroup')<CR>
  xnoremap <silent> <c-j> :<C-u>lua require('vscode-neovim').call('workbench.action.focusBelowGroup')<CR>
  nnoremap <silent> <c-h> :<C-u>lua require('vscode-neovim').call('workbench.action.focusLeftGroup')<CR>
  xnoremap <silent> <c-h> :<C-u>lua require('vscode-neovim').call('workbench.action.focusLeftGroup')<CR>
  nnoremap <silent> <c-l> :<C-u>lua require('vscode-neovim').call('workbench.action.focusRightGroup')<CR>
  xnoremap <silent> <c-l> :<C-u>lua require('vscode-neovim').call('workbench.action.focusRightGroup')<CR>
endif
```

OR 

With `vscode-neovim.neovimClean: true`:

I created a new file:
```typescript
const hello = ""

function thing(){
  return {
    howdy: {
      wow: ['a','b','c']
    }
  }
}
```
- Open another new file in another tab
- Go back to first file
- Go to line starting with func and shift-v. Hit % so that entire function is highlighted in visual
- Hit y to yank
- Hit gt to try to switch tabs (this will occasionally not work and you'll just be stuck on your tab, sorta related I think)
- If gt doesn't work, click within the file and you'll see the file/buffer flash. You can now gt
- Hit p in the other file (the new one)
- You'll see the infinite list of logs

### Expected Behavior

Expect buffers to not desync

**Comment by amin-hrp** [comment]
Found something else as well

I created a new file:

```typescript
const hello = ""

function thing(){
  return {
    howdy: {
      wow: ['a','b','c']
    }
  }
}```

- Open another new file in another tab
- Go back to first file
- Go to line starting with `func` and `shift-v`. Hit `%` so that entire function is highlighted in visual
- Hit `y` to yank
- Hit `gt` to try to switch tabs (this will occasionally not work and you'll just be stuck on your tab, sorta related I think)
- If `gt` doesn't work, click within the file and you'll see the file/buffer flash. You can now `gt`
- Hit `p` in the other file (the new one)
- You'll see the infinite list of logs

**Comment by justinmk** [comment]
> With `vscode-neovim.logLevel` set to `debug` ... I see `2024-02-08 17:23:54.620 [info] BufferManager: received buffer event for vscode-neovim://2/<FILEPATH>%3Aasvetliakov.vscode-neovim.vscode-neovim` logged infinitely.

That is a regression from https://github.com/vscode-neovim/vscode-neovim/pull/1786 . I'll take a look.

Workaround is to set logLevel to "info" or lower.

**Comment by justinmk** [comment]
Fixed in https://github.com/vscode-neovim/vscode-neovim/pull/1790
