### ISSUE TITLE
feature: support for statusline plugins

### ISSUE THREAD

**Issue by steveshi7** [vscode-neovim/vscode-neovim#1809]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

Currently, there does not seem to be support for statusline plugins such as [lualine](https://github.com/nvim-lualine/lualine.nvim).

It would be awesome to either have these available, or to have greater integration with the existing VSCode status bar. For example, [the plugin](https://github.com/kensleDev/vscode-nvim-ui) mentioned in this issue https://github.com/vscode-neovim/vscode-neovim/issues/1224 appears to no longer be supported. This appears to be something that is offered in VsCodeVim.

### Describe the solution you'd like

Support for statusline plugins, or greater integration with status bar.

### Describe alternatives you've considered

Use existing status bar.

**Comment by justinmk** [comment]
> This appears to be something that is offered in VsCodeVim.

Huh? VsCodeVim does not support any vim/nvim plugins.

You are expecting too much. If you're going to use vscode, use vscode. It makes no sense to expect Nvim UI plugins to map to the vscode UI.

**Comment by xiyaowong** [comment]
Use https://github.com/vscode-neovim/vscode-neovim#vscodeget_status_itemid

**Comment by justinmk** [comment]
@xiyaowong should we mention how to use [nvim_eval_statusline](https://neovim.io/doc/user/api.html#nvim_eval_statusline()) with that feature? Though I assume the request here was to automatically show the statusline rendered from Nvim UI events.
