### ISSUE TITLE
bug: mappings of `gj` and `gk` do not work

### ISSUE THREAD

**Issue by rennsax** [vscode-neovim/vscode-neovim#1813]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.9.5

### Operating system/version

MacOS 14.3.1

### Describe the bug

I put these key mappings in my `init.vim`:

```
nnoremap <Up> gk
nnoremap <Down> gj
```

But when I press Up and Down arrow key, they behave like `k` and `j` rather than `gk` and `gj` (do not handle the line wrap).

Other mappings for `gj` or `gk`, for example, `nnoremap x gk`, do not work either. However, `gj` and `gk` themselves behave normally.

### Steps To Reproduce

1. Use the command `nnoremap <Up> gk` or put the command into your vimrc/init.vim.
2. Type <Up> or <Down> when the cursor is on a wrapped line. You'll see the cursor goes to the real previous/next line, rather than the display previou/next line.

### Expected Behavior

`gj` and `gk` are supposed to navigate in the **display line**, as the neovim doc has highlighten.

**Comment by justinmk** [comment]
is this different than the other "composite" issues https://github.com/vscode-neovim/vscode-neovim/issues?q=is%3Aissue+is%3Aopen+composite

see also https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#composite-escape-keys though it is about insert mode , not normal mode.

**Comment by rennsax** [comment]
@justinmk Thanks for your response! I think they're different, because the problem only happens for `gj` and `gk` key mappings. And `gj` and `gk` themselves work normally (the same behavior as neovim). I think after key mapping, `gj` and `gk` lose their functionalities.

**Comment by justinmk** [comment]
https://github.com/vscode-neovim/vscode-neovim/issues?q=is%3Aissue+gj+gk+is%3Aclosed

**Comment by rennsax** [comment]
Thanks again! I finally know what should I do:

```
nmap <Up> gk
nmap <Down> gj
```

**Comment by gaoqiangks** [comment]
`vmap <Down> gj`  still doesn't work.

**Comment by YouSame2** [comment]
seems like an issue i ran into and ended up getting so frustrated i just made a plugin to fix it. heres the link for anyone who runs into this:
https://github.com/YouSame2/vscode-neovim-fix-word-wrap/
