### ISSUE TITLE
feature: Movement between cells (`` command)

### ISSUE THREAD

**Issue by Jeffresh** [vscode-neovim/vscode-neovim#1814]
### Did you check the docs?

- [x] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

In juypter notebooks, right now, you can move between the cells using commands like GG or G. But you cannot jumping back with: 

> `` 

### Describe the solution you'd like

Move back to the position before the jump using:

> ``

Just like in the cells.

### Describe alternatives you've considered

No alternatives have been considered.

**Comment by xiyaowong** [comment]
Not possible. You can customize the keybindings to execute the commands provided by the notebook.
