### ISSUE TITLE
[Question] Any thoughts on supporting azure data studio?

### ISSUE THREAD

**Issue by JoeHFB** [vscode-neovim/vscode-neovim#182]
Hi guys - 

Not a big deal if you can't, do you guys have any thoughts on supporting [azure data studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/what-is?view=sql-server-ver15)?

I use it quite a bit for my work with MSSQL, and apparently it's built on top of vscode - and having the power of vim would be _really_ nice :).  

Looks like adamskt was able to get vscodevim to install and run on azure data studio before.  https://github.com/VSCodeVim/Vim/issues/2677
Unfortunately if I try to install from VSIX the way he describes in that issue, I get this:
![image](https://user-images.githubusercontent.com/60893676/74349537-61caf680-4d82-11ea-8f27-abc295a67abc.png)
:(

**Comment by asvetliakov** [comment]
If the API is compatible then why not? I'll investigate

**Comment by jonpdw** [comment]
@asvetliakov What did your investigation find? :)

**Comment by blalande** [comment]
I’d be very interested in this too.

**Comment by theol0403** [comment]
It's likely it works now because https://github.com/vscode-neovim/vscode-neovim/pull/668
