### ISSUE TITLE
bug: I can't use neovim in Vscode

### ISSUE THREAD

**Issue by Dssssds** [vscode-neovim/vscode-neovim#1825]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.9.5

### Operating system/version

14.3.1 (23D60)

### Describe the bug

1. I installed [VScode-neovim] in the vscode editor.
2. Environment variables are configured, but they cannot be used.
3. Can not start, and always pop-up the following error.

### Steps To Reproduce

![image](https://github.com/vscode-neovim/vscode-neovim/assets/17268259/2447d887-494a-429c-bcf2-f783c4f9fa65)
this my setting.json 
![image](https://github.com/vscode-neovim/vscode-neovim/assets/17268259/ca17951d-b6d7-43d2-9620-761f665d29a7)

### Expected Behavior

![image](https://github.com/vscode-neovim/vscode-neovim/assets/17268259/61a3370e-0184-409c-8067-68d2bd4f22df)

**Comment by xiyaowong** [comment]
For macOS, you should use the option "darwin"
```json
{
  "vscode-neovim.neovimExecutablePaths.darwin": "/opt/homebrew/bin/nvim"
}
```

**Comment by Dssssds** [comment]
This problem still exists.
![image](https://github.com/vscode-neovim/vscode-neovim/assets/17268259/67765b48-caf1-4783-bbee-dec351305ff4)

**Comment by justinmk** [comment]
I'm working on a PR that will improve the ENOENT case.

Not sure about the "command already exists" case.

**Comment by Dssssds** [comment]
@xiyaowong  这位伙伴的办法是正确的办法.非常感谢. (。This partner's approach is the right one. Thank you very much  🌹🌹🌹 )
