### ISSUE TITLE
bug: VS Code Highlighting Problem

### ISSUE THREAD

**Issue by shanepat** [vscode-neovim/vscode-neovim#1833]
### Check the following:

- [X] #1834
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

1.6.1

### Operating system/version

MacOS 14.3.1

### Describe the bug

Code highlighting is inconsistent when mouse scrolling.
<img width="780" alt="Screenshot 2024-02-29 at 13 28 25" src="https://github.com/vscode-neovim/vscode-neovim/assets/11996311/ebba34ac-b070-4501-8684-9abda718d6a9">

### Steps To Reproduce

1. Be on the code with extension
2. Scroll down and the inconsistent highlighting should occur

### Expected Behavior

Code highlighting should not be effect by the extension.

**Comment by justinmk** [comment]
search existing issues

**Comment by justinmk** [comment]
> Neovim version (nvim -v)
> 1.6.1

That is not a valid Nvim version.
