### ISSUE TITLE
Errors installing nvim in vscode Ubuntu 22.04.4

### ISSUE THREAD

**Issue by justmedanel** [vscode-neovim/vscode-neovim#1843]
So i clean installed vscode from (sudo snap install code) also installed the nvim sudo apt ,and then in my vscode i installed the neovim extension in vscode and when i installed nvim a log was written with 251 lines of error. Maybe somebody got the same errors and can help me with this problem 
[vscode-neovim.log](https://github.com/vscode-neovim/vscode-neovim/files/14516746/vscode-neovim.log)

**Comment by xiyaowong** [comment]
Please use the issue template. I guess your nvim is too old.

**Comment by justmedanel** [comment]
> Please use the issue template. I guess your nvim is too old.

what do you mean by issue template ?

this is the sudo version of nvim
![image](https://github.com/vscode-neovim/vscode-neovim/assets/161379046/99f991e8-a678-4805-add5-2791f0d07d68)

and this is the apt version of nvim
![image](https://github.com/vscode-neovim/vscode-neovim/assets/161379046/238e8745-d705-44cc-9eb9-6e968699d5d6)

**Comment by xiyaowong** [comment]
Remove or upgrade Neovim installed with apt.
