### ISSUE TITLE
Checking $VIMRUNTIME read permissions will always fail on wsl

### ISSUE THREAD

**Issue by xiyaowong** [vscode-neovim/vscode-neovim#1848]
`Cannot read $VIMRUNTIME directory "/opt/nvim-linux64/share/nvim/runtime". Ensure that VSCode has access to that directory. Also try :checkhealth.`
I'm getting that error but I do not fully understand what am I suppose to do, running on WSL, nvim installed from pre-built release

_Originally posted by @Yusuf007R in https://github.com/vscode-neovim/vscode-neovim/issues/1816#issuecomment-1992304302_

**Comment by liu2g** [comment]
I have the same problem using flatpak neovim

**Comment by keifererikson** [comment]
Confirming I am running into the same issue.

**Comment by justinmk** [comment]
That means that `fs.readdirSync()` failed on that directory. What is vscode-neovim or Nvim supposed to do if it can't read that directory? What are the permissions on the directory?

**Comment by mignatoski** [comment]
First time building the plugin from source and installing, so I may have done something wrong... I had to add wsl.localhost to my "Allowed UNCHosts" settings in VSCode to get past a new error, but after that I'm still seeing the `Cannot read $VIMRUNTIME directory` error logged in the terminal.
