### ISSUE TITLE
bug: ctrl+p ctrl+p goes to last file in the list, instead of most-recent file

### ISSUE THREAD

**Issue by tbo47** [vscode-neovim/vscode-neovim#1857]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.9.5

### Operating system/version

debian 12 (stable)

### Describe the bug

`Ctrl+p` and then `p` again should go to the last edited file. Instead it goes the end of the list with no apparent logic.

### Steps To Reproduce

1. edit multiple files
2. type `Ctrl+p` and then `p` again on the keyboard

### Expected Behavior

It should go to the previously edited file.

**Comment by justinmk** [comment]
> `Ctrl+p` and then `p` again

Do you mean "`p` again" _while holding ctrl_ ? This is because vscode-neovim defines ctrl+n / ctrl+p keybindings which act like Nvim, for the vscode quickfix menus.

Read https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#disable-keybindings

**Comment by tbo47** [comment]
Thanks. I added this to `~/.config/Code/User/keybindings.json`. And it works fine now.
```json
 {
    "key": "ctrl+p",
    "command": "-workbench.action.quickOpenSelectPrevious",
    "when": "inQuickOpen && neovim.wildMenuVisible || inQuickOpen && neovim.mode != 'cmdline'"
  }
```
