### ISSUE TITLE
bug: clipboard throws error ("vscode" not defined during eval())

### ISSUE THREAD

**Issue by brendonscript** [vscode-neovim/vscode-neovim#1864]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2698+g00e71d3da

### Operating system/version

WSL Arch Linux

### Describe the bug

Using the VSCode Neovim extension v1.8.0 with the latest LazyVim version any command that writes or reads from clipboard will return an error. Using any version prior does not return an error. Using the option `vscode-neovim.neovimClean = true` this issue does not occur. I figured this could be a LazyVim issue but was directed here when I posted the bug at LazyVim/LazyVim#2832

Using `yy`:
```
t read properties of null (reading 'env')
2024-03-26 12:11:57.404 [info] 
^I...liakov.vscode-neovim-1.8.0/runtime/modules/clipboard.lua:23: in function <...liakov.vscode-neovim-1.8.0/runtime/modules/clipboard.lua:20>
2024-03-26 12:15:11.527 [info] 
table: 0x7f222808cb78
2024-03-26 12:17:27.559 [info] 
nil
2024-03-26 12:20:06.372 [info] 
Already at oldest change
2024-03-26 12:20:07.082 [info] 
Already at oldest change
2024-03-26 12:20:12.083 [error] MainController: Request error:  Cannot read properties of null (reading 'env')
2024-03-26 12:20:12.085 [info] 
^I...liakov.vscode-neovim-1.8.0/runtime/modules/clipboard.lua:23: in function <...liakov.vscode-neovim-1.8.0/runtime/modules/clipboard.lua:20>
2024-03-26 12:20:13.029 [error] MainController: Request error:  Cannot read properties of null (reading 'env')
2024-03-26 12:20:13.030 [info] 
^I...liakov.vscode-neovim-1.8.0/runtime/modules/clipboard.lua:23: in function <...liakov.vscode-neovim-1.8.0/runtime/modules/clipboard.lua:20>
2024-03-26 12:20:32.746 [info] 
E518: Unknown option: g:clipboard
2024-03-26 12:20:55.939 [error] MainController: Request error:  Cannot read properties of null (reading 'env')
2024-03-26 12:20:55.940 [info] 
^I...liakov.vscode-neovim-1.8.0/runtime/modules/clipboard.lua:23: in function <...liakov.vscode-neovim-1.8.0/runtime/modules/clipboard.lua:20>
2024-03-26 12:23:04.269 [info] 
1 line less; before #2  1 second ago
2024-03-26 12:24:24.968 [error] MainController: Request error:  Cannot read properties of null (reading 'env')
2024-03-26 12:24:24.969 [info] 
^I...liakov.vscode-neovim-1.8.0/runtime/modules/clipboard.lua:23: in function <...liakov.vscode-neovim-1.8.0/runtime/modules/clipboard.lua:20>
2024-03-26 12:27:13.123 [error] MainController: Request error:  Cannot read properties of null (reading 'env')
2024-03-26 12:27:13.127 [info] 
^I...liakov.vscode-neovim-1.8.0/runtime/modules/clipboard.lua:23: in function <...liakov.vscode-neovim-1.8.0/runtime/modules/clipboard.lua:20>
2024-03-26 12:27:14.648 [error] MainController: Request error:  Cannot read properties of null (reading 'env')
2024-03-26 12:27:14.649 [info] 
^I...liakov.vscode-neovim-1.8.0/runtime/modules/clipboard.lua:6: in function <...liakov.vscode-neovim-1.8.0/runtime/modules/clipboard.lua:5>

Error detected while processing function provider#clipboard#Call[9]..function provider#clipboard#Call[6]..2:
line    2:
E15: Invalid expression: "s:paste[a:reg]()"
2024-03-26 12:27:14.651 [info] 
clipboard: provider returned invalid data
2024-03-26 12:27:16.891 [info] 
1 line less; before #3  2 seconds ago
2024-03-26 12:29:13.468 [error] MainController: Request error:  Cannot read properties of null (reading 'env')
2024-03-26 12:29:13.469 [info] 
^I...liakov.vscode-neovim-1.8.0/runtime/modules/clipboard.lua:23: in function <...liakov.vscode-neovim-1.8.0/runtime/modules/clipboard.lua:20>
2024-03-26 12:29:14.914 [info] 
1 more line; before #4  1 second ago
2024-03-26 12:29:28.485 [error] MainController: Request error:  Cannot read properties of null (reading 'env')
2024-03-26 12:29:28.487 [info] 
^I...liakov.vscode-neovim-1.8.0/runtime/modules/clipboard.lua:23: in function <...liakov.vscode-neovim-1.8.0/runtime/modules/clipboard.lua:20>
``` 

### Steps To Reproduce

Using the VSCode Neovim extension v1.8.0 trigger any command writes or reads the clipboard

### Expected Behavior

Anything that writes or reads to clipboard should not throw an error.

**Comment by Adnios** [comment]
Same issue (without lazyvim config) after latest update.

**Comment by Adnios** [comment]
Same issue when `set clipboard& clipboard+=unnamedplus` after latest update

**Comment by justinmk** [comment]
> ^I...liakov.vscode-neovim-1.8.0/runtime/modules/clipboard.lua:23: in function <...liakov.vscode-neovim-1.8.0/runtime/modules/clipboard.lua:20>
> 2024-03-26 12:20:13.029 [error] MainController: Request error:  Cannot read properties of null (reading 'env')

Seems that `vscode` isn't defined here (yet?): https://github.com/vscode-neovim/vscode-neovim/blob/f75a199fa06615875654c65ac1782861b076b07b/runtime/modules/clipboard.lua#L6

@mbway

**Comment by theol0403** [comment]
Yeah not to do with Lazyvim. Issue with eval. Not sure why vscode isn't defined @mbway .

**Comment by mbway** [comment]
I'm not able to reproduce the exact clipboard issue, but I can reproduce the root cause which is that the 'vscode' object is `null` from the eval context when using the new vscode-neovim release.
So far I've only been testing eval with the 'development build' so maybe this is some kind of protection mechanism when running extensions normally?

Running the following:
```
:lua print(require'vscode-neovim'.eval('return vscode'))
```
`vscode` is `null` but `logger` (another global that should be visible from eval) is not null

I can think of several ways it might be possible to work around this. It would be nice to figure out if the value is intentionally null for protection or if we're doing something incorrectly.

**Comment by mbway** [comment]
I may not get a chance to look at this properly until Friday. To limit disruption maybe it makes sense to go back to using fixed actions like `set_keyboard` until the issue is resolved?

**Comment by theol0403** [comment]
> I may not get a chance to look at this properly until Friday. To limit disruption maybe it makes sense to go back to using fixed actions like `set_keyboard` until the issue is resolved?

Friday is fine. People can easily downgrade their extension version until then.

**Comment by justinmk** [comment]
> I wonder if webpack or something is stripping out the unused include.

Yeah. There are ways to tell webpack not to mangle names, e.g. [`keepNames` with `ESBuildMinifyPlugin`](https://www.neolisk.blog/posts/2021-10-08-webpack-minification-preserve-class-names/).

**Comment by still-dreaming-1** [comment]
Yeah I started getting "Cannot read properties of null (reading 'env')" errors constantly after the last update, related to using the clipboard. Downgraded to previous version and the it works well again.

**Comment by theol0403** [comment]
Strangely, `:lua print(require'vscode-neovim'.eval('return vscode'))` gives "null" while `:lua print(require'vscode-neovim'.eval('return anything_else'))` gives "not defined". The problem then isn't because of name mangling.

**Comment by mbway** [comment]
It doesn't look like a runtime protection at least which is a good thing. I downloaded the `.vsix` file, unpacked it and searched through the minified javascript:
![image](https://github.com/vscode-neovim/vscode-neovim/assets/4923501/29bb1fd5-e80a-43d8-a36f-6d0fe1a61468)
