### ISSUE TITLE
bug: gitsigns does not work

### ISSUE THREAD

**Issue by searleser97** [vscode-neovim/vscode-neovim#1873]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

v0.10.0-dev-2407+g9bb046d1b

### Operating system/version

Windows

### Describe the bug

The following config does not work in vscode-neovim, I would like to be able to jump to next/prev changes in vscode like I do in neovim with gitsigns, but for some reason it just does not work

```lua

  local gs = package.loaded.gitsigns

  -- Navigation
  vim.keymap.set('n', 'Gn', function()
    if vim.wo.diff then return ']c' end

    vim.schedule(function() gs.next_hunk() end)
    return '<Ignore>'
  end, {expr=true, desc = "Next Change"})

  vim.keymap.set('n', 'Gp', function()
    if vim.wo.diff then return '[c' end
    vim.schedule(function() gs.prev_hunk() end)
    return '<Ignore>'
  end, {expr=true, desc = "Previous Change"})
```
lazy.nvim config
```lua
  {
    "lewis6991/gitsigns.nvim",
    lazy = false,
    config = function ()
      require('gitsigns').setup()
    end
  },
```

### Steps To Reproduce

See description

### Expected Behavior

be able to jump through changes with gitsigns

**Comment by justinmk** [comment]
not going to debug Nvim plugins.

if you have a specific, reproducible (without plugins) issue, report that (after searching existing issues).

check your mappings.

it could be related to how the buffers are named.
