### ISSUE TITLE
bug: line wrap formatting with 'gq' does not work

### ISSUE THREAD

**Issue by MarelliF** [vscode-neovim/vscode-neovim#1874]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

GNU/Linux openSUSE Tumbleweed

### Describe the bug

In normal mode, trying to format a line or a paragraph for line wrapping using `gqq` (or `gq` with a selected area) does not produce the expected result. The cursor jumps at the start of the line when hitting `gqq`, but the text stays unchanged, with no line wraps.
Doing the exact same directly in neovim on the same documents works as expected.
If my memory is correct, this used to work in vscode-neovim quite some time ago.

### Steps To Reproduce

1. Open any document with some very long lines (longer than your textwidth, should be 80 by default)
2. In normal mode, position your cursor on a line much longer than your textwidth, and hit `gqq` 

### Expected Behavior

The selected line should be formatted with hard line wraps so that it fits the desired textwidth.

**Comment by justinmk** [comment]
gqq is mapped by default to invoke a vscode feature:

https://github.com/vscode-neovim/vscode-neovim/blob/0d6de9aa37f3ee5d3d5ac1015b1da27afdc3d9ac/runtime/modules/code_actions.lua#L23

<img width="247" alt="image" src="https://github.com/vscode-neovim/vscode-neovim/assets/1359421/26f51b91-bd55-4e5e-8e4a-f52a1a8c2ed6">

**Comment by justinmk** [comment]
https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#disable-keybindings

**Comment by bew** [comment]
> [vscode-neovim/vscode-neovim#disable-keybindings](https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#disable-keybindings)

`gqq` is not mentioned in the keybindings at this link, and searching for `gq` in VSCode's keybindings gives no results.
Since you linked to:
https://github.com/vscode-neovim/vscode-neovim/blob/0d6de9aa37f3ee5d3d5ac1015b1da27afdc3d9ac/runtime/modules/code_actions.lua#L23
I believe we need to disable the keybinding on neovimi's side instead?

**Comment by MarelliF** [comment]
Thanks, that did the trick.
