### ISSUE TITLE
bug: using composite escape keys breaks macros behavior

### ISSUE THREAD

**Issue by iampeternguyen** [vscode-neovim/vscode-neovim#1882]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.9.4

### Operating system/version

MacOs 14.4.1

### Describe the bug

If you use composite escape keys (ex: j,j), this inserts a `j` while using macros

### Steps To Reproduce

1. Set composite escapes key
2. Record a macro using `j,j` to escape
3. Use macro

### Expected Behavior

Using `j,j` to escape shouldn't insert letters

**Comment by justinmk** [comment]
https://github.com/vscode-neovim/vscode-neovim/issues?q=is%3Aissue+is%3Aopen+composite
