### ISSUE TITLE
bug: Additional thin cursor appears in visual mode

### ISSUE THREAD

**Issue by ycy3723** [vscode-neovim/vscode-neovim#1883]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.9.1

### Operating system/version

MacOS 13.2.1

### Describe the bug

When entering visual mode in Neovim, an additional thin cursor appears alongside the default cursor provided by the editor. Is there a way to resolve this?

https://github.com/vscode-neovim/vscode-neovim/assets/38966985/93933cb7-fee5-4b9b-adf1-0a858407ae2c

### Steps To Reproduce

1. enter visual mode
2. select lines

### Expected Behavior

Only one cursor in visual mode

**Comment by justinmk** [comment]
> 0.9.1

first step is always to use the latest Nvim

**Comment by ycy3723** [comment]
> > 0.9.1
> 
> first step is always to use the latest Nvim

I updated to version 0.9.5, but the issue still persists.

**Comment by xiyaowong** [comment]
Expected. The thin cursor is used to synchronize the selection in nvim. The reason why it is a thin cursor is because vscode cannot hide the cursor, and the square cursor you see is just a highlight (fake cursor), indicating the current cursor position of nvim.
