### ISSUE TITLE
feature: when condition in vscode call

### ISSUE THREAD

**Issue by Guray00** [vscode-neovim/vscode-neovim#1885]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

I would like to specify the VS Code "when" condition in order to separate different behaviours.

### Describe the solution you'd like

It could be the second parameter of the VsCodeNotify function.

### Describe alternatives you've considered

Nothing.

**Comment by xiyaowong** [comment]
Not possible #986
