### ISSUE TITLE
bug: unable to listFocusUp programmatically

### ISSUE THREAD

**Issue by davibe** [vscode-neovim/vscode-neovim#1889]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

NVIM v0.9.5 Build type: Release LuaJIT 2.1.1710088188     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.5/share/nvim"  Run :checkhealth for more info

### Operating system/version

Sonoma 14.4.1 (23E224)

### Describe the bug

I am not able to trigger the action "list.focusPageUp" (or down) from my init.lua

### Steps To Reproduce

in my `init.lua` I have created a mapping for `+` in normal mode which does `vscode.call("list.focusPageUp")` but this does result in nothing happening in vscode.

### Expected Behavior

 I would expect it to move as if I typed `C-u`. I debugged with some print statemens but I could not find any issues with my code. I also tried with `action()` (async).

How can i trigger that action ?

Note: I CAN trigger a map "+" to "<C-u>" in neovim, but that is not the same action as the one performd by vscode. My intention is to trigger the same action the vscode-neovim plugin does

**Comment by theol0403** [comment]
What is `list.focusPageUp` supposed to do in the context of an editor? It's only for vscode lists like navigation menu or quickfix.
