### ISSUE TITLE
bug:  expand("%p") returns empty on first file restored after vscode restart

### ISSUE THREAD

**Issue by gaoqiangks** [vscode-neovim/vscode-neovim#1892]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

NVIM v0.9.4

### Operating system/version

Windows 11

### Describe the bug

`expand("%p")` doesn't work properly, which makes some plugins failed.

### Steps To Reproduce

1. Create an empty folder, for example, called `test`
2. Create two files `a.txt`, `b.txt` in the directory `test`
3. Right click on `test`, choose open with `vscode`
4. Open the two files `a.txt` and `b.txt`, and make `a.txt` as the current tab.
5. Close vscode.
6. Reopen vscode, then the last session is restored, and `a.txt` is the current tab.
7. Type `: echo expand("%p")`, and we get nothing.
8. Change to `b.txt`, and type `: echo expand("%p")`, and we get the wsl path of `b.txt`

### Expected Behavior

`echo expand("%p")` should print path of the current file, however, nothing printed. See the following link.

[https://www.youtube.com/watch?v=IyQTBKg8Im4](url)

**Comment by justinmk** [comment]
> 6\. Reopen vscode, then the last session is restored, and `a.txt` is the current tab

Seems much narrower than the more general problem of "expand doesn't work"? Does `expand("%p")` work otherwise (i.e. without close-and-restart vscode)?

**Comment by xiyaowong** [comment]
Can't reproduce

**Comment by gaoqiangks** [comment]
> Can't reproduce

One more thing: I use wsl version(ubuntu 24.04) nvim, and I can always reproduce this issue.

**Comment by xiyaowong** [comment]
It seems to be a local environment issue. I'll close this issue for now.

There are several methods for reference: 
1. Use variables `b:vscode_uri` and `b:vscode_uri_data`
3. Use `vscode.eval` to obtain document information.
