### ISSUE TITLE
build: lint tasks should not depend on pre-commit

### ISSUE THREAD

**Issue by justinmk** [vscode-neovim/vscode-neovim#1905]
# Problem

our "lint" and "format" tasks depend on pre-commit: https://github.com/vscode-neovim/vscode-neovim/blob/5868ad1c950599a8ae121c4947f3c9b03a5cd0e3/package.json#L2089-L2090

this makes no sense. pre-commit was introduced for CI. devs shouldn't have to install pre-commit to lint the codebase.

**Comment by theol0403** [comment]
This was the price of removing all those dependencies from package.json... now `npm run lint` automatically bootstraps all linting dependencies.

**Comment by justinmk** [comment]
what dependencies? I must admit I didn't scrutinize the package-lock.json 7000 lines in that PR. Do we now have a 2nd, hidden dependency list somewhere that is pulled in by pre-commit?

**Comment by xiyaowong** [comment]
Agree.

**Comment by ollien** [comment]
> what dependencies? I must admit I didn't scrutinize the package-lock.json 7000 lines in that PR. Do we now have a 2nd, hidden dependency list somewhere that is pulled in by pre-commit?

I don't know if it's hidden per-se, but yes, the dependency comes from `pre-commit`

https://github.com/vscode-neovim/vscode-neovim/blob/3c82cc01e69e0817eb92f7093844136a3038bcff/.pre-commit-config.yaml#L26-L32

Fundamentally, you either have to have these deps managed by NPM, or something else :) Though, that said, it does look like this pre-commit plugin was deprecated just a couple weeks ago

https://github.com/pre-commit/mirrors-prettier

**Comment by justinmk** [comment]
> I don't know if it's hidden per-se

yeah. but now it's not reflected in a committed lockfile, and it's using a different package tool. so it's "hidden" in the sense that it's indirect.

somehow my comment at https://github.com/vscode-neovim/vscode-neovim/pull/1853#pullrequestreview-1943386418 got interpreted as "remove all of our existing lint dependencies", or something.

**Comment by xiyaowong** [comment]
Any conclusions? Recently I discovered that pre-commit is ok except that it requires additional installation.🌚

**Comment by justinmk** [comment]
The conclusion is what I said above, which is that our dependencies should be reflected in package-lock.json, and using an alternative package manager makes no sense.

**Comment by xiyaowong** [comment]
Sure

**Comment by ollien** [comment]
I was looking to do some maintenance on the linters and came back to this issue. I'm reading through the previous issue for context and I want to make sure I understand the concerns correctly.

There seems to have been concerns about blowing up the dependency tree with tools that do too much. `litn-staged` was called out, which I guess we could live without. Husky was also called out, but looking at npm it has zero dependencies and isn't that big at all. We could write scripts to set up pre-commit hooks for us but why not use something already written? 

Anyway: would there be pushback on me replacing the pre-commit lint tools with some npm managed tools, and then use husky to install hooks? The only thing I'm concerned about is stylelua, as that's not in NPM.

**Comment by justinmk** [comment]
> There seems to have been concerns about blowing up the dependency tree with tools that do too much. `litn-staged` was called out, which I guess we could live without

That was mainly it. The initial form of that PR added what looked like a lot of dependencies and "nice to have" things without a strong purpose. Then it turned into something else (which appeared to remove lots of dependencies but actually just hid them).

I don't have any strong objection to husky, but it's irrelevant for CI, and if adding pre-commit hooks adds lots of dependencies, it's just not worth it. CI is 99% of the story. Running the linter (locally), manually, is low-cost for this project, while adding pre-commit hooks can cause some problems if husky misbehaves or is slow.
