### ISSUE TITLE
feature: Multi-cursors operation in normal mode

### ISSUE THREAD

**Issue by musjj** [vscode-neovim/vscode-neovim#1906]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

I want to perform multi-cursor operation within normal mode, but it looks like that multi-cursors are always reset when you exit insert mode. Is this a fundamental limitation of the plugin?

### Describe the solution you'd like

Multi-cursor operation in normal mode.

### Describe alternatives you've considered

I've been using this: https://github.com/VSCodeVim/Vim. But it feels kind of slow, so I want to try the neovim version out.

**Comment by theol0403** [comment]
https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#multiple-cursors

Use vim-visual-multi or https://github.com/vscode-neovim/vscode-multi-cursor.nvim

**Comment by musjj** [comment]
Sorry if I wasn't clear, but `vscode-multi-cursor.nvim` still does not quite do what I wanted. I want to perform *synchronized* normal mode operations (e.g. `dw`) across all cursors. `vscode-multi-cursor.nvim` allows you to place individual cursors in normal mode and operate them in insert mode. But it will clear all the cursors once you enter normal mode.

To be clear, I'm not asking for this to be implemented on the plugin level, but I just wanted to know if this is just an inherent limitation of the plugin or if something can be done about it.

**Comment by theol0403** [comment]
https://github.com/brenton-leighton/multiple-cursors.nvim comes close, but needs some patching to make insert mode work
