### ISSUE TITLE
feature/bug?: when in visual line mode dont use vscode cursor

### ISSUE THREAD

**Issue by fazulk** [vscode-neovim/vscode-neovim#1910]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [x] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

I'm not sure if this is a feature, or even a bug, or just a limitation. I have seen this addressed indirectly in other issues, but can't find a solution. 

When in visual line mode, I see the "ghost" cursor aka the neovim "fake" cursor, and the end of the line cursor, which i presume is the real vscode cursor. 

Problem is I can have very long lines in my code, and if the line is longer than the window, the focus jumps to the VScode cursor at the end of the line. This makes for a maddening experience when i'm trying to select lines of text because the focus is jumping all over the place. Just to be clear i have word wrap turned off in vscode, and in neovim. Turning it on is not a option. 

### Describe the solution you'd like

Ideally, the focus wouldn't jump to the vscode cursor. I have seen this implemented in the other vim extension, but i'm aware this extension works differently.

### Describe alternatives you've considered

Ive tried looking into setting widths in neovim and vscode with no luck. 

### Additional context

If i'm not using visual line mode, but just visual mode- all works fine. presumably because in visual mode only, the vscode cursor is at the start of the line when my selection area expands vertically.

**Comment by ni554n** [comment]
Just updated to 1.10.1, but the cursor is still showing up.

![image](https://github.com/vscode-neovim/vscode-neovim/assets/2310552/b98ad4e4-60a6-443f-b74f-42ecb84b02ef)

**Comment by xiyaowong** [comment]
@ni554n  Not a same thing.

It's cannot be solved. Because it's not a problem. vscode-vim is the same.

**Comment by fazulk** [comment]
thank you!!
