### ISSUE TITLE
Help wanted: Remove H, L in default scroll config

### ISSUE THREAD

**Issue by tinoquang** [vscode-neovim/vscode-neovim#1916]
How can I remove the mapping to `H` and `L` in the scrolling default config? https://github.com/vscode-neovim/vscode-neovim/blob/3c82cc01e69e0817eb92f7093844136a3038bcff/vim/vscode-scrolling.vim#L25

- I'm using lazyvim as package manager and those mappings conflict with `<S-h>` and `<S-l>` which is used for switching buffer in lazyvim. 
- I already checked the keyboard shortcuts in vscode but can't find those mapping to remove.

**Comment by xiyaowong** [comment]
Add `unmap H` at the top of your init.vim
