### ISSUE TITLE
[REGRESSION BUG] IME text twitches in v1.11.0

### ISSUE THREAD

**Issue by wenfangdu** [vscode-neovim/vscode-neovim#1921]
This is exactly the reason that I don't use https://github.com/VSCodeVim/Vim, now vscode-neovim also has it...........

OS: macOS 14
VSCode: v1.88.1
IME: https://shurufa.sogou.com/

v1.11.0

https://github.com/vscode-neovim/vscode-neovim/assets/28700378/a727e408-3027-40d6-9117-93ba58ba9f8a

v1.10.1

https://github.com/vscode-neovim/vscode-neovim/assets/28700378/2fab8ce7-1abd-437a-ae65-b517eee2b143

Might be caused by https://github.com/vscode-neovim/vscode-neovim/pull/1917.
@xiyaowong Bro, take a look.

**Comment by xiyaowong** [comment]
能不能别老用这种命令的语气？这个按理说是vscode的问题，vscode提供default:type命令就是为了vim这种插件的

**Comment by xiyaowong** [comment]
我明天抽空修复下

**Comment by wenfangdu** [comment]
@xiyaowong 兄弟，有空看看就行，我锁版本了，抱歉语气不好，俺没在意………………

**Comment by theol0403** [comment]
@xiyaowong I don't think we should have merged such a major change so soon. Registering the type event during insert mode is something the extension has explicitly avoided for years. 

Currently, the new approach will break Russian layouts/dead keys/IME for regular typing in insert mode, something we can't do.

https://github.com/vscode-neovim/vscode-neovim/issues/653
https://github.com/vscode-neovim/vscode-neovim/issues/1466

**Comment by xiyaowong** [comment]
@theol0403 These should not be the same problem. First of all, this issue is actually a problem with vscode. Now vscode-neovim uses default:type correctly. I will optimize this problem when I am free today.

**Comment by xiyaowong** [comment]
According to this issue phenomenon, it's not lag, it's just that the characters are jumping.

**Comment by xiyaowong** [comment]
> Currently, the new approach will break Russian layouts/dead keys/IME for regular typing in insert mode, something we can't do.

In ime composition, we didn't do anything superfluous.

**Comment by theol0403** [comment]
I might be wrong here actually. I forgot that we are now using type instead of forwarding using vscode key bindings.

**Comment by vlwkaos** [comment]
Can confirm this with Korean as well, it not only visually twitches, but actually hinders typing.

**Comment by xiyaowong** [comment]
@vlwkaos Is it the same phenomenon? I can't test the Korean input method. The input shake of the Chinese input method here is very slight, and the degree of the phenomenon may also vary with different input methods.

**Comment by xiyaowong** [comment]
See https://github.com/microsoft/vscode/issues/211856

**Comment by xiyaowong** [comment]
Currently, only users who need to use composite keys and input CJK characters may encounter this issue. (And just found out that similar issues existed before.)

**Comment by wenfangdu** [comment]
@xiyaowong What are composite keys?

**Comment by xiyaowong** [comment]
I'm not sure either, but I've seen this term used 😂. Essentially, it refers to the mappings in insert mode, typically 'jj' or 'jk', to return to normal mode.

**Comment by xiyaowong** [comment]
@wenfangdu Not a same thing

**Comment by xiyaowong** [comment]
The original way is not friendly to CJK users too, so I don't think this problem will have a great impact at present. Besides, it's a problem with vscode, so I'll close this issue.
