### ISSUE TITLE
bug: can't use non-default escape key

### ISSUE THREAD

**Issue by pypp** [vscode-neovim/vscode-neovim#1926]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

v0.9.2

### Operating system/version

Ubuntu 22.04.4 LTS x86_64 

### Describe the bug

when clicking the non-default escape key (jk in my case), instaed of going to normal mode I have a warning popup that says the following:
```
command 'vscode-neovim.compositeEscape2' not found
```

lines that change the default keymap for escape key.
```lua
vim.keymap.set("i", "jk", "<Esc>", { silent = true })
```
This bug never happend before, it only now that I've discovered it.

### Steps To Reproduce

1. change neovim config to change the escape key to some other key
2. click that key when in insert mode

### Expected Behavior

to leave insert mode when clicking over the non-default escape key.

**Comment by pypp** [comment]
> I experienced the same issue, but as it turns out, it's not a bug. It's a breaking change: [Release notes v1.11.0](https://github.com/vscode-neovim/vscode-neovim/releases/tag/v1.11.0)
> 
> [Composite escape keys](https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#composite-escape-keys)

oh, I missed this from the changlog. thank you.

**Comment by ValdamireGido** [comment]
I had to roll back a couple of version to be able to type 'j'. Have not mappings for specific (composite) escape. Tried adding mention in Release notes mappings  - didn't help. Seams to me that bug is still valid.

**Comment by pypp** [comment]
> I had to roll back a couple of version to be able to type 'j'. Have not mappings for specific (composite) escape. Tried adding mentioned in Release notes mappings - didn't help. Seams to me that bug is still valid.

Did you remove the old bindings from keybindings.jaon and added the new ones ?

**Comment by ValdamireGido** [comment]
> > I had to roll back a couple of version to be able to type 'j'. Have not mappings for specific (composite) escape. Tried adding mentioned in Release notes mappings - didn't help. Seams to me that bug is still valid.
> 
> Did you remove the old bindings from keybindings.jaon and added the new ones ?

Removing old mappings helped. Thank you! 

Maybe a good idea to mention this in the Release notes you shared.

**Comment by zph** [comment]
For me, this is broken in v1.11.1 (maybe earlier) due to custom declarations in my `keybindings.json` file.

Resolution:
1. Cmd-P > Preferences: Open Keyboard Shortcuts JSON
2. Remove the object with a command referencing `compositeEscape2`, in my case a custom binding for `k`.

Looks like I've had this config in place since Mar 2021 https://github.com/zph/dotfiles/commit/eab16ba47675131892f8946dd64a0af71f86e084

With that declaration removed the plugin works again for my setup.
