### ISSUE TITLE
allow to use `alt-key` as `escape key` for keys used by neovim?

### ISSUE THREAD

**Issue by goyalyashpal** [vscode-neovim/vscode-neovim#1927]
hi! would it allow to use `alt-key` as `escape key` for all the keys used by neovim?

i.e. say, i press `alt-j` in insert mode, then it would become equivalent to pressing `escape` then `j` thus bringing me in normal mode and then navigate down.

but rather than me configuring for each combination hard-codingly, it is performed automatically for at least good enough range of the most significant combos 

like `alt-` `:`, `h, j, k, l`, `i, a, o`, `y, p`, `x, d, r, c`, `u`, `(, ), {, }`, etc
what more, if either of these options feel overkill, then it could be exposed in such a way that specifying only these single keys in an `array of strings` (for quick configuration of single character chords) or `array of arrays of strings` (for multi charcater chords if any) would work.

e.g.

```jsonc
"...altkeychords": [
  ":",          # activating command mode
  "0123456789",  # for count motion
  "hjkl",  # songle char navigation
  "wbeWBE",  # word-by navigation
  "ftFT",  # navigation by fond
  "ia",  # fine tuning cursor position
  "IAoOR", # changing cursor positoon
  "xdcr",  # deletions
  "yp",  # yanks puts
  "u",  # undo
  "(){}",  # para wise navogation
  "/?",  # searches
  "\"",  # specifying registers
  "@",  # running macros
]
```

this would help me immensly.

* https://github.com/helix-editor/helix/issues/3162

_Originally posted by @goyalyashpal in https://github.com/vscode-neovim/vscode-neovim/issues/1917#issuecomment-2088782327_

**Comment by justinmk** [comment]
> i.e. say, i press `alt-j` in insert mode, then it would become equivalent to pressing `escape` then `j` thus bringing me in normal mode and then navigate down.

Nvim already supports that by default. https://neovim.io/doc/user/insert.html#i_ALT

However vscode-neovim mostly lets vscode own insert-mode, so vscode-neovim would not capture `<m-j>` and send it to Nvim. 

I guess since `ctrlKeysForInsertMode` exists, we could consider adding another setting... but if this adds a lot of code I'm not in favor of it.

**Comment by ollien** [comment]
Hm, I can't put my finger on why, but I almost consider this a hair different from `ctrlKeysForInsertMode`, because it's executing an arbitrary action - it's not an alt-specific action (you move down with just `j`, `alt-j` isn't a requirement), like some of the ctrl keys (`ctrl-[` is different from `alt-[`). Regardless, at minimum I can investigate to see if it's feasible. :)

**Comment by ollien** [comment]
Ok, yeah! There's not a ton that needs to be done to make this work; it works almost exactly the same as how we map `<C-x>`. The only "downside", if you can call it that, is that we have to produce a key mapping for each "alt key". I guess this is fine... I think if we map all chars on a standard ANSI QWERTY layout (letters, numbers, plus combinations with shift) we'll get 80% of the way there. And if it's desirable, we can of course add an allowlist just like we do for `ctrl` (maybe we should, just so we don't get on too many people's nerves with extensions that choose to map something similar)

**Comment by xiyaowong** [comment]
Simply configure your keybindings.json.

It is intentional not to provide altKeysForInsertMode.

**Comment by xiyaowong** [comment]
https://github.com/vscode-neovim/vscode-neovim/pull/1558#issuecomment-1775469775

**Comment by ollien** [comment]
Why not provide it? It seems completely reasonable; is there a problem with doing so? 

I actually kinda wish I knew about it sooner as a vim user.

**Comment by xiyaowong** [comment]
Do we need to provide it, fKeysInNormal  fKeysInInsert   ctrlFKeysInNormal  altFKeysInNormal?

**Comment by ollien** [comment]
I guess I can understand the argument of configuration bloat. I don't necessarily agree, but I also don't feel very strongly.
