### ISSUE TITLE
feature: Improve Instructions for configuring the new Composite Key

### ISSUE THREAD

**Issue by KenzKD** [vscode-neovim/vscode-neovim#1929]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

The new Composite Key Code Snippets are meant to be placed in the settings.json file but the previous implementation was meant to be placed in the keyboardshortcuts.json file. This has led to confusion on how to reconfigure the Composite keys.

I and others had put the code snippet in the keyboardshortcuts.json file only to be greeted with an error and no clarification on to resolve this issue.

### Describe the solution you'd like

I would like for the Composite Key section in the Details Panel/ Readme to mention that it has to be placed in the settings.json file.

### Describe alternatives you've considered

There could also be an error message that redirects the user in case the place it in the keyboardshortcuts.json file

**Comment by xiyaowong** [comment]
will do
