### ISSUE TITLE
feature: extension's command to "disable"

### ISSUE THREAD

**Issue by goyalyashpal** [vscode-neovim/vscode-neovim#1932]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

* i am not very comfortable in using nvim in multifile editing i.e. switching vscode-tabs/groups, toggling sidebars etc
(basically i don't know how to do _any_ of that yet)
* so, when doing kinda slapdash work, i prefer not to use nvim in vscode

but current option to achieve that are just: 
* `F1` > `Neovim: Stop Extension` or 
* `<C-S-x>` > `@installed neovim` `<TAB><TAB>` `rt click` disable

and both have their own problems:
* "neovim: stop" doesn't persist in next window reload/launch, and
* "vscodium extension: disable" requires "reload windows" (umh wait no, "restart extensions" now in vscodium v1.88.1?) which breaks stuff, say doing some interactive work in vscode-notebooks etc... and is jarring nonetheless

### Describe the solution you'd like

having an option of "neovim: disable" will help a lot.

### Describe alternatives you've considered

i have never noticed the "restart extensions" button before ('have only updated vscodium a few days ago), so, it might be that it alleviates from the jarriness of "reload window" and an extension based handling of disable is not needed...

but i ain't sure.

### Additional context

versions:

```console
$ codium --list-extensions --show-versions | grep -i neovim
asvetliakov.vscode-neovim@1.11.0

$ codium --version
1.88.1
0d01a72525276e5e3771fe5851b9c83de0de1e2b
x64

$ nvim --version
NVIM v0.10.0-dev-2961+g4d52b0cf6
Build type: RelWithDebInfo
LuaJIT 2.1.1713484068

$ systeminfo | grep -Ei "^os name|^system type"
OS Name:                   Microsoft Windows 10 Home Single Language
System Type:               x64-based PC
```

**Comment by justinmk** [comment]
> i have never noticed the "restart extensions" button before ('have only updated vscodium a few days ago), so, it might be that it alleviates from the jarriness of "reload window" and an extension based handling of disable is not needed...

yes, that is a recent vscode enhancement.

> "neovim: stop" doesn't persist in next window reload/launch

that would be redundant with vscode's "disable" feature.

**Comment by goyalyashpal** [comment]
> would be redundant with vscode's "disable" feature.

i already said that too lol
