### ISSUE TITLE
bug:  MainController: nvim_execute_lua: Wrong type for argument 1, when using example from docs

### ISSUE THREAD

**Issue by Nikola-Milovic** [vscode-neovim/vscode-neovim#1938]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

`NVIM v0.9.4`

### Operating system/version

Windows 11 + Ubuntu 22.04 WSL

### Describe the bug

When using the example for jk from the docs

```json
 "vscode-neovim.compositeKeys": {
        "jk": {
            // Use lua to execute any logic
            "command": "vscode-neovim.lua",
            "args": [
                [
                    "local code = require('vscode-neovim')",
                    "code.action('vscode-neovim.escape')",
                    "code.action('workbench.action.files.save')"
                ]
            ]
        }
    },
```

I am getting this error when i `jk`

`nvim_execute_lua: Wrong type for argument 1 when calling nvim_execute_lua, expecting String`

### Steps To Reproduce

Copy the code from the docs into `settings.json` and try using `jk`, clean neovim installation with empty `lua.init`

### Expected Behavior

Would work as intended

**Comment by xiyaowong** [comment]
Wait for the new version. Please check the README on the vscode extension detail page.

**Comment by Nikola-Milovic** [comment]
Any eta on the new release?
