### ISSUE TITLE
bug: compositeKeys is Identified as Unknown Configuration Setting

### ISSUE THREAD

**Issue by themuuln** [vscode-neovim/vscode-neovim#1945]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Windows 11

### Describe the bug

![Screenshot 2024-05-06 153448](https://github.com/vscode-neovim/vscode-neovim/assets/75017829/5da600b4-67eb-4c52-b41e-d0b6c7349dab)

### Steps To Reproduce

1. Set jj as Escape

### Expected Behavior

Identify CompositeKeys

**Comment by justinmk** [comment]
what version of vscode-neovim is installed? maybe you need to restart vscode? 
![image](https://github.com/vscode-neovim/vscode-neovim/assets/1359421/a490bd89-0a28-42e3-87ed-1e3e5ea4c1c9)
