### ISSUE TITLE
bug: <C-o> jump back and stuck at visual mode

### ISSUE THREAD

**Issue by albert-ying** [vscode-neovim/vscode-neovim#1946]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.9.4

### Operating system/version

MacOS 14.4.1

### Describe the bug

When your jump list includes operations in visual mode, the `<C-o>` will lead you back to visual mode and get stuck there unless you do `o` followed by escape. Then press `<C-o>` again with let me go back to the previous jump list

### Steps To Reproduce

1. Jump to somewhere in the file
2. VG
3. call command-shift P in visual mode
4. esc esc (quit command palette and visual mode)
5. gg
6. Then keep pressing `<C-o>`, you will find yourself back to the visual mode in step 2. Keep pressing `<C-o>` will not do anything.

### Expected Behavior

Keep pressing `<C-o>` will let me navigate to the jump list prior to the visual mode operation.

**Comment by albert-ying** [comment]
https://github.com/vscode-neovim/vscode-neovim/assets/59846322/53507bfb-c6e3-4360-9aec-7dfad9ddbdb0

It persists when I try using empty init.vim

**Comment by xiyaowong** [comment]
This is because `<C-o>` is actually `workbench.action.navigateBack`
https://github.com/vscode-neovim/vscode-neovim/blob/12e0d8b53708c28adc31a5c4083bfb40b44d0e33/vim/vscode-jumplist.vim#L10

Here is a workaround

```lua
local code = require('vscode-neovim')
vim.keymap.set('n', '<C-o>', function()
  code.action('workbench.action.navigateBack', {
    callback = function()
      vim.defer_fn(function()
        code.action('cancelSelection', {
          callback = function() vim.api.nvim_input('<ESC><ESC>') end,
        })
      end, 100)
    end,
  })
end)
```
