### ISSUE TITLE
bug: scrolling quickly can interfere with highlights

### ISSUE THREAD

**Issue by ollien** [vscode-neovim/vscode-neovim#1948]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

Fedora 39

### Describe the bug

I admit, this one is a bit tough to reproduce, but I have managed to reproduce it. I originally thought this might be a bug with #1940, but I can reproduce it with `master`.

When you scroll quickly in a file, sometimes highlights are removed from the screen. I suspect there is somehow a race between our tracking of the viewport and the tracking of the highlights.

I found this bug, which was marked as a duplicate, but I could not find what it was marked as a duplicate of?  https://github.com/vscode-neovim/vscode-neovim/issues/1833

### Steps To Reproduce

1. Open a file that you are able to scroll significantly in
2. Search for text with `/`, and move your cursor to another line.
3. Scroll up and down quickly with your mouse, and notice highlights disappear

Here's a recording of me searching for `/jest` in https://github.com/jestjs/jest/blob/726ca20752e38c18e20aa21740cec7aba7891946/package.json. Keep your eye on line 1, and notice the highlight disappears.

https://github.com/vscode-neovim/vscode-neovim/assets/977151/21f69d28-5878-4470-8d96-0329e08745df

### Expected Behavior

The existence of the highlight should not depend on how quickly one scrolls

**Comment by xiyaowong** [comment]
https://github.com/vscode-neovim/vscode-neovim/blob/12e0d8b53708c28adc31a5c4083bfb40b44d0e33/src/viewport_manager.ts#L147

**Comment by xiyaowong** [comment]
If it's just that the highlighting takes a while to appear, that's expected. Scrolling must be debounced, so it's an unavoidable phenomenon.
