### ISSUE TITLE
Feature request: New install experience

### ISSUE THREAD

**Issue by hholst80** [vscode-neovim/vscode-neovim#195]
I would like to improve on the first-install experience.

1. Have vscode-neovim.neovimPath be 'nvim' and search $PATH for it by default.
2. If nvim is found but have the wrong version. ERROR OUT and show an error on start.

This plugin requires me to always open up the config to use the tool when I install vscode with the neovim ext. on a new computer. Which I do.. often! And equally often I will screw up on the configuration and wonder why all keyboard input is being dropped. After several restarts and WTFs I realize that "oh its called nvim not neovim" or "oh neovim was old on this system I need to install it out of tree" or something else.

**Comment by hholst80** [comment]
The resolve-path semantics requires that 1) check if program is an absolute path 2) check if it is available in $PATH

```
➜  PATH=/bin type /bin/ls 
/bin/ls is /bin/ls
➜  PATH=/bin type ls
ls is /bin/ls
➜  PATH=/bin type nvim
nvim is /bin/nvim
➜  PATH=/bin type /usr/bin/nvim
/usr/bin/nvim not found
```

**Comment by 3nuc** [comment]
Checking for absolute paths should be a one line thing with node's `path` module

As for checking in $PATH I'm not sure, but there's [this](https://stackoverflow.com/questions/20643470/execute-a-command-line-binary-with-node-js#20643568)

You have a good idea here though. The install experience could be improved as the user can be in the dark from time to time about what's happening. I'm currently working on a feature related to paths (splitting neovimPath into neovimPath.windows, neovimPath.linux etc) so if you'd like to see the code that's related to the paths check out #157

**Comment by justinmk** [comment]
I've been thinking it would be nice for Nvim clients like https://github.com/neovim/node-client and https://github.com/neovim/pynvim to have a "find `nvim`" function, since this is a very common need.

**Comment by justinmk** [comment]
> Have vscode-neovim.neovimPath be 'nvim' and search $PATH for it by default.

https://github.com/neovim/node-client now provides `getNvimFromEnv()` which tries to find `nvim` on the user's system and returns a list of all found Nvims, their filepaths, and any errors encountered (which can shown to the user). https://github.com/neovim/node-client/blob/06b4c185848a4c1e041d8cba267d8b9abac892f7/packages/neovim/src/utils/getNvimFromEnv.test.ts#L96
