### ISSUE TITLE
bug: "references" preview pane shows tree-sitter highlights after scrolling

### ISSUE THREAD

**Issue by ollien** [vscode-neovim/vscode-neovim#1963]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

Fedora 39

### Describe the bug

When opening the "references" pane, highlighting will (usually) show up correctly. However, once I click on an item to scroll to, the tree-sitter highlights return. A video is worth a thousand words:

https://github.com/vscode-neovim/vscode-neovim/assets/977151/63d35917-6dfb-420d-b374-eb1975e24d56

This seems related to #1739 (and perhaps #1940?). 

### Steps To Reproduce

1. Go to a file where you will have multiple references for a single variable
2. Run "go to references"
3. Click on one of the jump-points, and notice that the highlight colors change.

### Expected Behavior

The tree-sitter highlights should not bleed through.

**Comment by ollien** [comment]
Hm, I've been experimenting a little bit, and I wonder... do we have any reason to store highlight groups for of kind `syntax`? We always just disable `treesitter` when a buffer opens. I worry this would have knock-on effects, but it sure feels like a "simple" solution.

https://neovim.io/doc/user/ui.html

> kind: always present. One of the following values: "ui": Builtin UI highlight. [highlight-groups](https://neovim.io/doc/user/syntax.html#highlight-groups) "syntax": Highlight applied to a buffer by a syntax declaration or other runtime/plugin functionality such as [nvim_buf_add_highlight()](https://neovim.io/doc/user/api.html#nvim_buf_add_highlight()) "terminal": highlight from a process running in a [terminal-emulator](https://neovim.io/doc/user/nvim_terminal_emulator.html#terminal-emulator). Contains no further semantic information. ui_name: Highlight name from [highlight-groups](https://neovim.io/doc/user/syntax.html#highlight-groups). Only for "ui" kind. hi_name: Name of the final [:highlight](https://neovim.io/doc/user/syntax.html#%3Ahighlight) group where the used attributes are defined. id: Unique numeric id representing this item.

**Comment by ollien** [comment]
I did a `git-bisect` from v1.11.1 to `master`, and came up with #1944 being the culprit, which is interest because it seems to try and fix this same problem. I'll dig into this when I get a spare cycle (but of course wouldn't mind a hand)

**Comment by ian-h-chamberlain** [comment]
Nice, this seems to reproduce pretty reliably for me as well (like 75% of the time), but only when I'm running v1.11.3, so I think it helped! I'll keep an eye out for any other highlight issues (seems like there was some discussion on that PR) but this definitely seems like it's helping for now, thanks! 🎉
