### ISSUE TITLE
When the log level is error, normal messages cannot be output

### ISSUE THREAD

**Issue by xiyaowong** [vscode-neovim/vscode-neovim#1965]
![image](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/18ffd355-18e9-40cf-ba86-d39bf8d68544)

1. Set output channel level to error
2. Run `lua print('a\nb')`

**This is not a log, so log levels should not affect it.**

Messages should use an independent output channel
https://github.com/vscode-neovim/vscode-neovim/blob/b9ad120efac084de7e66207a385ac66af97132d9/src/messages_manager.ts#L9

And it should be `OutputChannel`, not `LogOutputChannel`

**Comment by xiyaowong** [comment]
Messages should use an independent output channel

**Comment by justinmk** [comment]
I think we can handle this without an extra channel.

> And it should be `OutputChannel`, not `LogOutputChannel`

Why? The timestamps and highlighting can be useful.

**Comment by xiyaowong** [comment]
The output is closer to neovim and is not a log in nature. In addition, there are problems with the current message output. Particularly long content is sometimes missing.

**Comment by ollien** [comment]
For normal `msg_show` events (e.g. pressing "u" and getting "Already at oldest change"), we already have those in the status bar, so it not being in the log makes sense to me. The only one that's different is `show_msg_history`, which needs somewhere to go. IMO, that is justification to have a separate output channel for logs.

My proposal is we create two output channels, one titled "vscode-neovim logs" and another titled "vscode-neovim", the latter of which is a plain output channel (that we could perhaps adorn with a timestamp).


P.S, heh, so this is amusing. You can actually create two output channels with the same name, and they'll both display in the list.
