### ISSUE TITLE
`incsearch` not works in NVIM v0.10.0

### ISSUE THREAD

**Issue by xiyaowong** [vscode-neovim/vscode-neovim#1969]
See https://github.com/neovim/neovim/issues/28800

**Comment by justinmk** [comment]
incsearch works for me in vscode-neovim with Nvim 0.10. I type something, it highlights as I type, and navigates to the first match.

what symptoms are you seeing? https://github.com/neovim/neovim/issues/28800 mentions low-level details.

**Comment by xiyaowong** [comment]
Sometimes it works normally. You can try this in the JSON file (settings.json).
