### ISSUE TITLE
feature: Implement cmdline in statusbar

### ISSUE THREAD

**Issue by xiyaowong** [vscode-neovim/vscode-neovim#1977]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Describe the solution you'd like

1. Implement it.
2. Provide option for users to choose between quickpick or statusbar

### Additional context

Previous request: https://github.com/vscode-neovim/vscode-neovim/issues/288#issuecomment-872203603

This is very easy to achieve with vscode-neovim. Compared with quickpick, it is difficult to implement the wildmenu. Everything else is an advantage

**Comment by ollien** [comment]
Personally, I really don't like having the commandline in the status bar. Too many extensions already take up that space, and it can be frustrating to try and read longer text. That said, I do recognize it has some advantages, so I understand the preference. I would hope there would be an option to keep the quickpick.

**Comment by xiyaowong** [comment]
Off course we should keep quickpick

**Comment by theol0403** [comment]
VSCodeVim uses the status bar. It has some advantages, but there are no completions which is a major issue. With more bindings now supported in the quickpick menu, I think we should just try to improve the ergonomics.

**Comment by xiyaowong** [comment]
Cmdline is very good at present.

**Comment by theol0403** [comment]
Why reopen? Edge-case bugs in quickpick can and will be fixed.

**Comment by xiyaowong** [comment]
Anyway, this is a feature worth considering. Edge cases always exist. If the implementation isn't straightforward, I'll close this.
