### ISSUE TITLE
bug: searching for text with the substitute command jumps to the first match

### ISSUE THREAD

**Issue by ollien** [vscode-neovim/vscode-neovim#1978]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Fedora 39

### Describe the bug

Originally part of #329 

In Neovim, if you type `%s/query` and there is a match on your screen, the match will highlight. However, in vscode-neovim, the editor scrolls up to the first match, even if a relevant match is currently in the viewport.

https://github.com/vscode-neovim/vscode-neovim/issues/329#issuecomment-2115855371

This comment contains some details that may be worth exploring

### Steps To Reproduce

1. Load [this file](https://gist.githubusercontent.com/nikcub/3833406/raw/97891e880b4ed6bd29d514b983669f611a2523a7/index.php)
2. Put your cursor on line 87
3. Type `%s/p` (do not hit enter) and notice your cursor jumps to the first line (the first location of `p`)

### Expected Behavior

The window should not scroll when highlighting the matches, just as nvim does not.

**Comment by xiyaowong** [comment]
Expected since we set &inccommand to ""
