### ISSUE TITLE
feature: expose `vscode.action_into_insert` and `neovim.action_into_insert`

### ISSUE THREAD

**Issue by theol0403** [vscode-neovim/vscode-neovim#1999]
There are some vscode bindings which create behaviors which are incompatible with nvim. However, we would like to intelligently ease the transition and allow clever behavior from normal mode.

The best example is vscode multi cursor like C-S-L for `editor.action.selectHighlights` or C-d for `editor.action.addSelectionToNextFindMatch`.

It would be nice to be able to do the following (equivalent, though I prefer the latter):

```lua
vim.keymap.set({ "n", "x", "i" }, "<C-S-L>", function() require("vscode-neovim").action_into_insert("editor.action.selectHighlights") end)
```

or

```json
{
  "key": "ctrl+shift+l",
  "command": "neovim.action_into_insert",
  "args": "editor.action.selectHighlights",
  "when": "editorFocus && neovim.init && neovim.mode != 'insert'"
}
```

This would remove the need for https://github.com/vscode-neovim/vscode-multi-cursor.nvim/blob/main/lua/vscode-multi-cursor/wrappers.lua, because we can make these bindings default for core (and generically handle any other binding which should move to insert mode before executing). 

https://github.com/vscode-neovim/vscode-neovim/assets/16546293/8952f29c-66f4-4e16-aec4-a677e654da90

**Comment by xiyaowong** [comment]
This is not worthy to be an API

**Comment by theol0403** [comment]
Fair enough, but I think this is universal enough to be builtin bindings (vscode multi cursor commands work in normal mode out of the box). How can we support this in a good way? That's what I wanted to make a generic API in case anyone else wants to transition from insert mode along with a command.

**Comment by theol0403** [comment]
What about an extra arg in `vscode.action` that lets you specify to enter insert mode before running the action?

**Comment by xiyaowong** [comment]
Perhaps we can place it in the `vscode.util` module.

**Comment by xiyaowong** [comment]
> What about an extra arg in `vscode.action` that lets you specify to enter insert mode before running the action?

The main consideration is that there are many aspects to consider if we want to make this method generic. Perhaps offering some helper functions would be better.
