### ISSUE TITLE
bug: Neovim disconnected frequently in jupyter notebook file.

### ISSUE THREAD

**Issue by neuromaancer** [vscode-neovim/vscode-neovim#2004]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MacOS 14.5

### Describe the bug

Neovim disconnected frequently in jupyter notebook file.

### Steps To Reproduce

1. open a Jupyter notebook file and wait. (might need a medium size file)

### Expected Behavior

Not disconnected.

**Comment by ollien** [comment]
Probably related to #2000. Does it persist if you downgrade to `0.95`?

**Comment by xiyaowong** [comment]
Duplicate of #2000
