### ISSUE TITLE
bug: navigateBack and navigateForward doesn't work

### ISSUE THREAD

**Issue by Xlight97** [vscode-neovim/vscode-neovim#2013]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Windows 11

### Describe the bug

navigateBack and navigateForward / Ctrl-o and Ctrl-i not work in some files, I play with .js and .ts, jump to specific line and then Ctrl-o nothing happen except if I open another file it will bring back to the file. Play with .py and .json it work as expected.

I've disabled this extension, just normal vscode navigateBack and navigateForward work as expected.

### Steps To Reproduce

1. Open VSCode with the Neovim extension.
2. Open .js or .ts file
3. Go to specific line
4. navigateBack and navigateForward

### Expected Behavior

when jump to specific line and then Ctrl-o it will bring back to previous line.

**Comment by ollien** [comment]
I've tested this with .ts files and nvim 0.9.5 and can't reproduce it.

**Comment by Xlight97** [comment]
Now it's work as expected, thanks @ollien
