### ISSUE TITLE
feature(api): vscode.altercmd

### ISSUE THREAD

**Issue by xiyaowong** [vscode-neovim/vscode-neovim#2019]
Or `vscode.util.altercmd`

This idea originates from #2009. While our goal is to remove altercmd, frankly, it seems challenging to achieve at the moment. Since there's still a demand for it, how about providing an auxiliary function for altercmd?

For example:
```lua
vscode.altercmd("w[rite]", function()
  vscode.action("workbench.action.files.saveWithoutFormatting")
end)
```

**Comment by justinmk** [comment]
I don't understand why we keep discussing adding more and more features, when we've previously aligned to find ways to simplify this codebase.

AlterCmd is a hack that should be removed. It's a workaround for a missing vim/nvim feature. It's not something we should elevant by exposing as an API.
