### ISSUE TITLE
bug: insertions after `S` become immutable

### ISSUE THREAD

**Issue by xzhang8102** [vscode-neovim/vscode-neovim#2023]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MacOS 13.6.7

### Describe the bug

Some key sequences could lead to unexpected behavior when editing.

https://github.com/vscode-neovim/vscode-neovim/assets/43830077/b38a1d66-0727-4e54-a9c6-679b9f175f22

### Steps To Reproduce

1. random text
2. normal mode press O (capital o)
3. esc back to normal mode
4. press S (capital s) to insert
5. type `{`
6. esc back to normal mode

Now, the `{}` cannot handle any operations (editing and cursor moving).

### Expected Behavior

The inserted characters should be operatable.

**Comment by ollien** [comment]
I can't reproduce this. Are you rebinding any of these commands in your `init.vim`, perhaps?

**Comment by xzhang8102** [comment]
> I can't reproduce this. Are you rebinding any of these commands in your `init.vim`, perhaps?

I tried `nvimClean` and the issue is still there.
I was trying to copy some lines from `settings.json` to a opened lua buffer as a comment before this issue showed up the first time.

**Comment by xzhang8102** [comment]
> I can't reproduce this. Are you rebinding any of these commands in your `init.vim`, perhaps?

I just find out that the key sequences are not necessary, pressing `S` in an empty line and the inserted characters will be immutable.

**Comment by xiyaowong** [comment]
Possible related to #1624. When encountering this issue, please try the following commands:

1. `echo win_getid()`
2. `echo nvim_buf_get_lines(0, 0, -1, v:false)`

Check the output of these commands.

**Comment by ollien** [comment]
@xiyaowong From a repro of this (empty file, hit `S`, type `asdf`), this is the output of those commands

```
:echo win_getid()
1002
:echo nvim_buf_get_lines(0, 0, -1, v:false) 
['']
```

**Comment by xiyaowong** [comment]
Confirmed
