### ISSUE TITLE
bug: cmdline flickering in 1.13.1 on development container

### ISSUE THREAD

**Issue by nicolaibonde** [vscode-neovim/vscode-neovim#2025]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

1.13.1

### Operating system/version

Windows 10 + WSL ubuntu 23

### Describe the bug

When working with on a file after a little while, the cmdline will start flickering, when this happens no input can be made.
but if you press escape it inserts hlsearch into the document. 

### Steps To Reproduce

1. Open a development container
2. Edit a document
3. press :w to save
4. the flickering happens

### Expected Behavior

No flickering and insertion of random vim commands into file

**Comment by uraza** [comment]
I have a similar issue on my side, and I root caused it to that particular keymap in my init.lua:

`vim.keymap.set("n", "<Esc>", ":nohlsearch<CR>")`

With this line (alone) in init.lua, typing <Esc> will cause the commandline input to flicker and insert "nohlsearch" into the open editor.
Without this line in init.lua, no issue.

**Comment by xiyaowong** [comment]
Use `<Cmd>`

`vim.keymap.set("n", "<Esc>", "<Cmd>nohlsearch<CR>")`

**Comment by uraza** [comment]
> Use `<Cmd>`
Works for me, thanks for the info.
It is not clear whether @nicolaibonde issue is the same or not, I will let him confirm.

**Comment by nicolaibonde** [comment]
This seems to have fixed the issue! Thanks.
I had the same keymap.
