### ISSUE TITLE
bug: Extension doesn't work correctly after updating to 1.14.*

### ISSUE THREAD

**Issue by RobinLanderloos** [vscode-neovim/vscode-neovim#2040]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

NVIM v0.9.5

### Operating system/version

Windows 11

### Describe the bug

After updating the extension to the latest version I get the following output from "vscode-neovim messages"
```
Error detected while processing VimEnter Autocommands for "*":
E116: Invalid arguments for function nvim_exec2
```

Also, when scrolling in any code, everything gets fumbled.
![image](https://github.com/vscode-neovim/vscode-neovim/assets/50279108/447fe412-6056-4fcc-85e9-74aa8c9d31bd)

### Steps To Reproduce

1. Update to version 1.14.* (tested with both 1.14.0 and 1.14.1) of the extension
2. It's messed up

### Expected Behavior

That the extension works after updating.

**Comment by xiyaowong** [comment]
Need output of `echo nvim_get_runtime_file("lua/vscode*", v:true)`

**Comment by xiyaowong** [comment]
> After updating the extension to the latest version I get the following output from "vscode-neovim messages"
> ```
> Error detected while processing VimEnter Autocommands for "*":
> E116: Invalid arguments for function nvim_exec2
> ```

Isn't this error message incomplete?

**Comment by ollien** [comment]
Are you doing anything in particular to trigger this? I can't say I'm having this experience with either 0.10 or 0.9.5

**Comment by xiyaowong** [comment]
I guess you have `lua/vscode` or `lua/vscode.lua` in your config directory.

**Comment by ollien** [comment]
Nice catch. Doing `mkdir ~/.config/nvim/lua && touch ~/.config/nvim/lua/vscode.lua` allows me to repro. In that state I get

```
:echo nvim_get_runtime_file("lua/vscode*", v:true)
['/home/nick/.config/nvim/lua/vscode.lua', '/home/nick/.vscode/extensions/asvetliakov.vscode-neovim-1.14.1/runtime/lua/vscode', '/home/nick/.vscode/extensions/asvetliakov.vscode-neovim-1.14.1/runtime/lua/vscode.lua'
```

Seems like expected breakage from https://github.com/vscode-neovim/vscode-neovim/pull/1997, but maybe we can detect this somehow and make the failure more obvious...?

**Comment by xiyaowong** [comment]
For personal configurations, it is recommended to place them in an individual module, such as lua/self, lua/username, etc.

**Comment by xiyaowong** [comment]
I'm not sure if it's a module conflict issue. If it is, then you definitely haven't enabled the "neovimClean" option 😅 
![image](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/d6dd7d7e-2d8b-4e4b-96fb-d7580e9960f7)

**Comment by MikePresman** [comment]
I have the same issue after update

**Comment by Jinghao-Tu** [comment]
Renaming the file `lua/vscode.lua` to other name can solve the problem.

**Comment by RobinLanderloos** [comment]
> Renaming the file `lua/vscode.lua` to other name can solve the problem.

Thank you, that seems to have indeed fixed the issue.

Renamed to 'rlanderloos-vscode' from 'vscode'
![image](https://github.com/vscode-neovim/vscode-neovim/assets/50279108/fb6d40f3-3023-40b5-85d2-13279a096da6)

**Comment by MikePresman** [comment]
> Renaming the file `lua/vscode.lua` to other name can solve the problem.

I dont understand what is `the` file? You mean rename init.lua to vscode.lua?

**Comment by RobinLanderloos** [comment]
For me I have two separate configurations, one for regular neovim and one for vscode-neovim.
These were separated into two folders -> `rlanderloos` and `vscode`.

So I had both `rlanderloos/init.lua` and `vscode/init.lua`.
I'm guessing that after the extension updated some naming from `vscode-neovim` to just `vscode` it broke my install because of conflicting files/namespaces?

So now I insted have `rlanderloos/init.lua` and `rlanderloos-vscode/init.lua`
Which then fixed my issue at least.

**Comment by MikePresman** [comment]
> For me I have two separate configurations, one for regular neovim and one for vscode-neovim. These were separated into two folders -> `rlanderloos` and `vscode`.
> 
> So I had both `rlanderloos/init.lua` and `vscode/init.lua`. I'm guessing that after the extension updated some naming from `vscode-neovim` to just `vscode` it broke my install because of conflicting files/namespaces?
> 
> So now I instead have `rlanderloos/init.lua` and `rlanderloos-vscode/init.lua` Which then fixed my issue at least.

I dont believe that.
I also have two configs but the structure is

`~/.config/init.lua` which either runs `init.lua` if we're in VSCODE or if im using regular neovim it calls
`./lua/init2.lua`

**Comment by Jinghao-Tu** [comment]
> > Renaming the file `lua/vscode.lua` to other name can solve the problem.将文件 `lua/vscode.lua` 重命名为其他名称可以解决该问题。
> 
> I dont understand what is `the` file? You mean rename init.lua to vscode.lua?我不明白 `the` 文件是什么？您的意思是重命名 init.lua 为 vscode.lua 吗？

My config file tree is this.
```
.config/nvim/
├── init.lua
├── lazy-lock.json
└── lua
    ├── basic.lua
    ├── code.lua
    ├── numbertoggle.lua
    ├── ordinary-plugins.lua
    ├── plugins.lua
    └── theme.lua
```
`code.lua` was named as `vscode.vim` originally, which is my config for vscode-neovim.

After #1997, the module `vscode-neovim` has been reflactorred to `vscode`. My original config file was conflicted with the new module name, so I said the config file needed to rename.

By the way, if you use some API in the vscode-neovim like

```
local vscode = require('vscode-neovim')
vscode.action()
```

You need to retype the use of API like

```
local vscode = require('vscode')
vscode.action()
```

**Comment by MikePresman** [comment]
I had `  use 'https://github.com/Mofiqul/vscode.nvim'` in my plugins install file for packer. Removing it fixed it for me.

**Comment by niun** [comment]
> I dont believe that it was namespace conflict.

maybe its two different problems but renaming my `vscode` module to `niun-vscode` fixed this for me and I think it is obvious that there was a naming conflict because in `vscode/init.lua` I had some imports like `require("vscode.remap")` which I guess would import the main extension module now but after renaming the `vscode/` directory to `niun-vscode/` I had to change this to `require("niun-vscode.remap")` of course, so now the conflict is gone.

**Comment by MikePresman** [comment]
> > I dont believe that it was namespace conflict.
> 
> maybe its two different problems but renaming my `vscode` module to `niun-vscode` fixed this for me and I think it is obvious that there was a naming conflict because in `vscode/init.lua` I had some imports like `require("vscode.remap")` which I guess would import the main extension module now but after renaming the `vscode/` directory to `niun-vscode/` I had to change this to `require("niun-vscode.remap")` of course, so now the conflict is gone.

> > I dont believe that it was namespace conflict.
It is, I was wrong. Simply put in your case you had made the namespace conflict by naming the files explicitly that resulted in collision, in my case a plugin I had installed created a namespace conflict.

**Comment by xiyaowong** [comment]
Version 1.14.2 will tell you where the issue lies.

**Comment by Ivanes1** [comment]
I'm having the same issue with a completely empty config (running on wsl ubuntu-22.04, neovim v0.7.2)

**Comment by xiyaowong** [comment]
@Ivanes1 Update neovim

**Comment by Ivanes1** [comment]
> Update neovim

I think it's the latest one for this ubuntu version. If it's the version problem then I guess I need to install another wsl distro. Will try that, thanks

**Comment by xiyaowong** [comment]
@Ivanes1 https://github.com/neovim/neovim/blob/master/INSTALL.md#ubuntu

**Comment by Ivanes1** [comment]
works without any issues on wsl ubuntu-24.04, neovim v0.9.5

**Comment by chardskarth** [comment]
I experienced this issue as well. I think this is a namespace conflict as chaging `lua/vscode.lua` to `lua/custom-vscode.lua` fixed it for me.
