### ISSUE TITLE
bug: Cannot escape by composite key when my type 'jk' from input method like fctix

### ISSUE THREAD

**Issue by cycode0527** [vscode-neovim/vscode-neovim#2047]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.10

### Operating system/version

Fedora 40

### Describe the bug

When my typing my composite key to escape directly , it works. But when my type the keys from fcitx5 and press "Enter", it not work.
![image](https://github.com/vscode-neovim/vscode-neovim/assets/76815699/8141d6f3-88e2-41ed-b522-1fa5aba32fdd)
![image](https://github.com/vscode-neovim/vscode-neovim/assets/76815699/a92b6e2e-a2b2-4945-b194-8d4441f5b9ee)
I have used the plug im-select.nvim, it work perfectly in my neovim terminal. But it not work in vscode because of this bug

### Steps To Reproduce

1. install fcitx or other input method
2. set composite key like jj or jk or kj
3. into insert mod, type `'jk'` can escape.
4. then switch on fcitx, type `jk` and `Enter`.
5. It seemed that the string `'jk' `was showed on screen directly

### Expected Behavior

when I type `jk` on fcitx and then type `Enter`, it can escape successfully

**Comment by xiyaowong** [comment]
not supported
