### ISSUE TITLE
bug: Copilot chat make neovim disconnect

### ISSUE THREAD

**Issue by Urriel** [vscode-neovim/vscode-neovim#2057]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MACOS 14.2.1

### Describe the bug

When triggering copilot chat to open I get the message: "Neovim was disconnected"
I tried to bisect it and it happens every time I open copilot chat.

### Steps To Reproduce

1. Open a file
2. Go over a typecript error.
3. Trigger copilot chat to open

### Expected Behavior

Neovim should still be running.

Here is a demo : [video](https://app.claap.io/edko-education/neovim-issue-c-Ak5aXS47Nj-pj7PRsBv6Bon)

**Comment by xiyaowong** [comment]
#2000
