### ISSUE TITLE
In insert mode, also synchronize the cursor position from VSCode to Neovim

### ISSUE THREAD

**Issue by xiyaowong** [vscode-neovim/vscode-neovim#2069]
First: changing the selections of textEditor will break the cursor-related functions of vscode, such as placeholder jumps in snippet mode, multi-cursor selection, etc.

In insert mode, when sending keys to neovim, it is necessary to allow synchronization of cursor changes in neovim (for example, the user may bind `<C-a>` to `<Home>`), and the cursor position in neovim needs to be updated so that the cursor is in the latest position when exiting insert mode.
https://github.com/vscode-neovim/vscode-neovim/blob/62bab0597590ba4445b57b98653b2f0dd60ee002/src/typing_manager.ts#L294-L303
The problem is: sending all keystrokes will execute this logic. If the function corresponding to a key in neovim happens to call the cursor function of vscode, there will be a problem:

![select](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/e74af566-61d2-4198-ad59-974cb7703708)
<sub> Ctrl+i calls editor.action.addSelectionToNextFindMatch </sub>

Because the cursor position is inconsistent, synchronizing the cursor changes in neovim causes vscode to lose the selected range.

Solution:

In insert mode, also update the cursor position of neovim. Also, in insert mode, after the cursor in vscode is synchronized to neovim, the cursor changes from neovim should no longer be synchronized to avoid the selection in vscode being destroyed.

**Comment by ollien** [comment]
I think this would also solve the repro mentioned in the original issue here: https://github.com/vscode-neovim/vscode-neovim/issues/1624#issue-1996656923

**Comment by xiyaowong** [comment]
Probably not. That's a content synchronization issue.

**Comment by xiyaowong** [comment]
### Solution

This can be considered an edge case. Directly calling the script is sufficient.

`keybindings.json`

```jsonc
{
  "key": "ctrl+d",
  "command": "vscode-neovim.lua",
  "args": [
    "local vscode = require('vscode')",
    "vscode.with_insert(function()",
    "  vscode.action('editor.action.addSelectionToNextFindMatch')",
    "end)"
  ],
  "when": "neovim.init && editorTextFocus"
}
```
