### ISSUE TITLE
bug: "Neovim was disconnected" when copilot chat is opened

### ISSUE THREAD

**Issue by badcodecat** [vscode-neovim/vscode-neovim#2076]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.0-beta3

### Operating system/version

Gentoo Base System release 2.15

### Describe the bug

When copilot chat is opened, I receive an error "Neovim was disconnected" with an option to restart and I am unable to continue using the extension. Using the restart button is ineffective as the message just appears again shortly.
I'm not sure if these apply to my issue or not, if it does feel free to close:
> - Plugins that provide their own UI, or work during insert-mode, are not supported.
> - Nvim can only interact with one window at a time.

### Steps To Reproduce

1. Use the VSCode Neovim extension and the Github Copilot Chat extension
2. Click on the Copilot Chat icon in the Activity Bar

### Expected Behavior

I expected the extension (VSCode Neovim) to function as normal, or the "restart" button to return the extension to a working state.

**Comment by xiyaowong** [comment]
You checked `I have searched existing issues.`, but #2000, #2057

**Comment by badcodecat** [comment]
Sorry I thought that only applied to open issues, thanks!
