### ISSUE TITLE
bug: vim-sandwich stops working since 1.14

### ISSUE THREAD

**Issue by echaya** [vscode-neovim/vscode-neovim#2079]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.9.1

### Operating system/version

Windows 7

### Describe the bug

I have been using https://github.com/machakann/vim-sandwich in neovim and vscode-neovim since day 1. It has been working perfectly. But it stops working since v1.14 (the last version it is still working is 1.13.1).

When try to delete / replace pair of parentheses, it just alter the texts outside of the selected scope.   

### Steps To Reproduce

1. Install vim-sandwich => `Plug 'machakann/vim-sandwich'`
2. Create a *.md file with 

```
"test_1"
"test_2"
"test_3"
```
3. Run `sr"'` in normal mode. It should replace `"` pair into `'` pair. 
4. Run `sd"` in normal mode. It should delete `"` pair

![vim-sandwich](https://github.com/vscode-neovim/vscode-neovim/assets/34254408/7c6894c5-06fc-4012-b102-16dd92ab41d4)

### Expected Behavior

Run `sr"'` in normal mode. It should replace `"` pair into `'` pair. 
Run `sd"` in normal mode. It should delete `"` pair

**Comment by ollien** [comment]
Thanks for the report. I can repro this

Also, I've wanted a plugin like this for a while, so thanks for the rec :D

**Comment by xiyaowong** [comment]
broken by #2035

**Comment by ollien** [comment]
Yep. Specifically f73eac673e72d0c3c62eeaadbbfc266486e7c2e5. Trying to track down why this would even affect it.

**Comment by theol0403** [comment]
> Also, I've wanted a plugin like this for a while, so thanks for the rec :D

Modern nvim replacements :): https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-surround.md https://github.com/kylechui/nvim-surround

**Comment by echaya** [comment]
> > Also, I've wanted a plugin like this for a while, so thanks for the rec :D
> 
> Modern nvim replacements :): https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-surround.md https://github.com/kylechui/nvim-surround

Most of the modules within mini.nvim look really cool (although it does not go along with my philosophy about one plugin should just do one thing XD

Do you know if vscode-neovim supports most if not all of the modules?

**Comment by xiyaowong** [comment]
> Do you know if vscode-neovim supports most if not all of the modules?

The simplest way to determine whether a plugin works correctly is to try it out.

**Comment by theol0403** [comment]
> although it does not go along with my philosophy about one plugin should just do one thing

You can install each plugin individually.

> Do you know if vscode-neovim supports most if not all of the modules?

Yes, other than modules which provide extra UI elements.

**Comment by xiyaowong** [comment]
@echaya Submit feature requests to these plugins.

**Comment by ollien** [comment]
If someone else wants to take this on, please feel free. I don't know when I'll have a free moment in the next couple of weeks

**Comment by albert-ying** [comment]
I saw it is fixed at v1.18.2. Will it be pushed to VScode soon (as now there is still v1.18.0), as it is a bug fix? Thank you!

**Comment by ollien** [comment]
@albert-ying I intend to do it as soon as I can, but it may be a bit. You can build the extension from source in the interim, if this is breaking your workflow.
