### ISSUE TITLE
bug: Enter visual mode unexpectedly

### ISSUE THREAD

**Issue by Songggggr** [vscode-neovim/vscode-neovim#2095]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.10

### Operating system/version

MacOS 14.5

### Describe the bug

When I'm searching, I use the "l" key to jump to the editor, and then the search content is automatically selected. I don't want to enter the visual mode.
![image](https://github.com/vscode-neovim/vscode-neovim/assets/131334123/57ef8733-bc57-4ee8-845d-5530518470f2)

### Steps To Reproduce

1. search
2. "l" select
3. now editor is visual mode

### Expected Behavior

I've also found that using "gd" to jump and the "workbench.action.quickTextSearch" command will both automatically take me into the visual mode as well. I've tested this in a clean mode to rule out any interference from my Vim configuration.

**Comment by ollien** [comment]
I'm not sure I understand the report. If you search for "test" in the "Find" panel, and you press "l", it's just going to type `l` in the editor box. Could you either explain in more detail and/or give a screen capture?

**Comment by theol0403** [comment]
This is unavoidable. When VSCode selects text for any reason, it is converted to a nvim selection. See if there is a VSCode setting to prevent the preselection of the find result.

**Comment by Songggggr** [comment]
@ollien Any vscode search command to enter the visual mode
![Kapture 2024-06-10 at 11 29 22](https://github.com/vscode-neovim/vscode-neovim/assets/131334123/a56ef150-ee1d-4daf-91ad-26588d5df21b)

**Comment by xiyaowong** [comment]
@Songggggr 
- #1738
- #1828
