### ISSUE TITLE
VSCode Launch Error: "vscode.get_status_item" Missing

### ISSUE THREAD

**Issue by photkey** [vscode-neovim/vscode-neovim#2098]
Whenever I start VSCode, I get the following prompt: The "vscode.get_status_item" is missing. If you have a Lua module named "vscode", please rename it.

Can someone explain the specific cause of this issue? How can I configure my settings to prevent this prompt from appearing?

**Comment by xiyaowong** [comment]
Upgrade 'vscode-multi-cursor.nvim'
