### ISSUE TITLE
bug: vs code now constantly auto switching to the output panel on multiline messages

### ISSUE THREAD

**Issue by nikvdp** [vscode-neovim/vscode-neovim#2099]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MacOS 14.4

### Describe the bug

In recent versions of this extension (> `v1.13.1`) the output panel gets focused whenever neovim outputs multiline messages. This behavior does not happen in v1.13.1, and is probably related to the "revamp messages output channel" PR (https://github.com/vscode-neovim/vscode-neovim/pull/2024) introduced in v1.14. 

I use a neovim plugin ([pounce](https://github.com/rlane/pounce.nvim)) with this extension, and that plugin outputs multiline messages in the course of normal use, which has made this extension near unusable because it's now constantly covering up the terminal window or otherwise refocusing things against my will.

VS code's focusing behavior is quite aggressive and is not configurable (there are lot of [longstanding issues](https://github.com/microsoft/vscode/issues/105270) about this in the vs code repo) so it would be nice to have a setting to disable this behavior in vscode-neovim

Related to: https://github.com/vscode-neovim/vscode-neovim/issues/2046 and https://github.com/vscode-neovim/vscode-neovim/issues/1812

### Steps To Reproduce

1. emit a multi-line message in neovim (`:echom "test\n"`). 
2. The ouput panel pops up, taking over focus from whatever was visible previously

### Expected Behavior

The extension behaves the same as it did in v1.13.1 and shows multiline output in the status bar area rather than the output channel

**Comment by justinmk** [comment]
> I use a neovim plugin ([pounce](https://github.com/rlane/pounce.nvim)) with this extension, and that plugin outputs multiline messages in the course of normal use,

So... why not configure that plugin to disable that behavior? If Nvim displays a multiline message, then vscode-neovim displays it. It makes no sense to expect anything different.

**Comment by bew** [comment]
Related but without any plugins, I'm getting very annoyed when doing a search that don't exist like `/foobar` and getting the vscode panel open with the messages:
```
search hit BOTTOM, continuing at TOP
E486: Pattern not found foobar
```
This is builtin and I would expect this to work without disrupting the UI and my current focus.

Could you please reopen and change back this behavior?

**Comment by nikvdp** [comment]
Yes, as @bew explained, this issue is larger than just the issue I have with the pounce plugin, as shown by the related issues I linked (https://github.com/vscode-neovim/vscode-neovim/issues/1812 and https://github.com/vscode-neovim/vscode-neovim/issues/2046).

While I may be able to configure pounce to not output multiline messages, that does not solve the larger issue: there should be a less intrusive way to display multiline messages. While you are correct that neovim does display multi-line output, neovim does not take up half the available screen real estate to display two line messages.

Additionally, this is a regression in this repo, versions of nscode-neovim before 14 do not have this usability breaking behavior.

> I can't reproduce that issue (with my personal config as well as with vscode-neovim.neovimClean), messages are not focused when a search fails

this issue is easily reproducible with `vscode-neovim.neovimClean` by doing `:echom "test\n"` as I wrote in the original report

**Comment by justinmk** [comment]
> by doing `:echom "test\n"` as I wrote in the original report

By echoing a multiline message you are literally asking Nvim (and vscode-neovim) to show a message. The messages Output channel is how multiline messages are displayed.

**Comment by nikvdp** [comment]
In version 13.1 they were displayed in the status bar without focusing the Output panel.

**Comment by justinmk** [comment]
The statusbar can only show one line. 

It might be the case that we need to adjust a threshold so that the Output channel is only shown if there are >=2 EOL chars.

Thus this does not focus the Output channel:

    :echom "test\n"

but this does:

    :echom "test\ntest\n"

**Comment by nikvdp** [comment]
That would help, thank you for reopening the issue, much appreciated. Would making the threshold configurable via a user setting increase the complexity significantly? I'd be interested in contributing to make that happen if helpful

**Comment by justinmk** [comment]
This behavior has existing for at least 1 year. Most likely just the threshold needs to be adjusted.

We don't need a setting. I have yet to see any explanation about why you think it makes sense for an Nvim plugin to display a long message but you expect vscode-neovim not to show it. 

So far, the only cases mentioned here are about 2-line messages. That shouldn't exceed the threshold. But if a 3-line message is displayed by Nvim, it makes no sense to insist that vscode-neovim should not display it. Fix your plugins, in that case.

**Comment by squigglybob** [comment]
I was also looking just now to see how to stop the output panel from keeping on opening.
Is there a way to prevent it from opening if I don't want to see any multi line messages that may be being outputted?

Similar to @bew the panel is distracting and taking up space. I would like to choose for it not to open by itself.

Any help would be greatly appreciated :) thanks

**Comment by fiddler** [comment]
I'm having the same experience here. When the search does not find anything the output panel pops out to show the message. This did not happen previously, so it looks like some recent change to vscode-neovim is causing it.

Adjusting the threshold up would work to fix the immediate annoyance.

**Comment by squigglybob** [comment]
> This behavior has existing for at least 1 year. Most likely, a recent PR may have regressed the threshold.

Does that mean there is a plan to fix that threshold?

> 
> We don't need a setting. I have yet to see any explanation about why you think it makes sense for an Nvim plugin to display a long message but you expect vscode-neovim not to show it.

Personally I don't mind it showing it once (similar to debug opening the panel when started), but then I would like it to respect my decision to close the panel and stay closed for future messages if I choose not to read the messages, rather than continuing to open after being closed.

> So far, the only cases mentioned here are about 2-line messages. That shouldn't exceed the threshold. But if a 3-line message is displayed by Nvim, it makes no sense to insist that vscode-neovim should not display it. Fix your plugins, in that case.

Messages should be displayed, but it should be the user's choice to read them and not to have a panel automatically open.
Many messages go into the output or sql console or debug console, but they don't automatically open up the panel. I can choose to open the panel and read them if I desire.

**Comment by ollien** [comment]
@justinmk 

> This behavior has existing for at least 1 year. Most likely, a recent PR may have regressed the threshold.

Yes, I decreased the threshold from 3 to 2 because it seemed like an accident. Before, it would show the logs panel, which is way more than any user would really need to show a message. I suppose I could have filtered out empty lines in that count...

**Comment by zirho** [comment]
![image](https://github.com/vscode-neovim/vscode-neovim/assets/1251296/4746f500-7671-43bf-a949-4cdcee41a5a8)
rolled it back and 1.13.0 seems quite to me :) 
thanks

**Comment by xiyaowong** [comment]
# Set `cmdheight` to a higher value

**Comment by mike-rambil** [comment]
I am getting something similar in current version(1.18.12) where when i yank multiple lines in visual studio mode.

@xiyaowong

**Comment by mizagog** [comment]
@mike-rambil, I've test now, and adding ':set cmdheight=10' to my init file solved it for me. Did you try that?

**Comment by nikolovlazar** [comment]
@mizagog this worked! thank you so much!

**Comment by justinmk** [comment]
> This is so fiercely annoying. The panel should not open of its own accord, it should respect the users' placement of the panel.

The panel only opens if you invoke a Nvim command that prints multiple lines of output. It makes no sense at all to invoke a command that shows a message and then say "I don't want to see the message".

If you have a plugin or mapping that is showing a message you don't want to see, that has nothing to do with this issue. That is a problem with your config.
