### ISSUE TITLE
bug: <Esc> in ":" mapping does not work

### ISSUE THREAD

**Issue by pgsandstrom** [vscode-neovim/vscode-neovim#2100]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

MacOS 13.6.7

### Describe the bug

I have the following line in my config:

    nnoremap O :set paste<CR>O<Esc>:set nopaste<CR>a

This line fixes so when I press `O` in normal mode on a commented line, the comment isnt copied. It used to work before v1.13.0 of this extension. Now instead it replaces the line above and prints out "set nopaste". If I revert to v1.12.0 it works again.

### Steps To Reproduce

1. Add to config: `nnoremap O :set paste<CR>O<Esc>:set nopaste<CR>a`
2. Stand on commented line in any file
3. Press `O`
4. New line wont appear above, instead current line above will be replaced with the text "set nopaste"

### Expected Behavior

It should work like it does in nvim.

**Comment by justinmk** [comment]
As a workaround, `<cmd>` instead of `:` seems to work:

    nnoremap O <cmd>set paste<CR>O<Esc><cmd>set nopaste<CR>a

**Comment by xiyaowong** [comment]
Similar to #2079

**Comment by ollien** [comment]
This is very likely the same bug, given you spawn a command line twice. One (silly) workaround would be to add a sleep between the two commands.

**Comment by xiyaowong** [comment]
@ollien Can we also close this issue?

**Comment by ollien** [comment]
Yep! Just gave this a test and it works :)
