### ISSUE TITLE
Bug: Give arg <space> to the F motion will to waiting and fail, If the map reader is <space>

### ISSUE THREAD

**Issue by ShortArrow** [vscode-neovim/vscode-neovim#2106]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

Win10 Pro 22H2

### Describe the bug

To be precise, this is not because `vim.g.mapleader` is `<space>`.
Maybe, this is wrong approach, sorry.

If you set a vscode key binding to mimic the case where "mapleader of vim is the letter x", when you want to move to the x position using F motion, it will wait for a command and you will not be able to move.

If this isn't a bug, but an issue with how `keybindings.json` is written, or if it can be solved by some ingenuity in `init.lua`, please tell me and close issue. thank you.

### Steps To Reproduce

init.lua
```lua
vim.g.mapleader = " "
```

keybindings.json
```json
[
  {
    "key": "tab",
    "command": "-tab",
    "when": "editorTextFocus && !editorReadonly && !editorTabMovesFocus"
  },
  {
    "key": "space d",
    "command": "editor.action.goToDeclaration",
    "when": "neovim.mode == normal && editorTextFocus"
  },
  {
    "key": "space b",
    "command": "workbench.action.navigateBack",
    "when": "neovim.mode == normal && editorTextFocus"
  },
  {
    "key": "space h",
    "command": "editor.action.showHover",
    "when": "neovim.mode == normal && editorTextFocus"
  },
  {
    "key": "space l f",
    "command": "editor.action.formatDocument",
    "when": "neovim.mode == normal && editorTextFocus"
  },
  {
    "key": "space s",
    "command": "workbench.action.files.save",
    "when": "neovim.mode == normal && editorTextFocus"
  }
]
```

### Expected Behavior

I want to ensure that setting the key binding in VSCode to mimic the case where the mapleader in Vim is the letter x does not affect the f motion.

**Comment by xiyaowong** [comment]
init.lua
```lua
vim.g.mapleader = " "

local action = function(cmd)
	return function()
		require("vscode").action(cmd)
	end
end

vim.keymap.set("n", "<space>d", action("editor.action.goToDeclaration"))
vim.keymap.set("n", "<space>b", action("workbench.action.navigateBack"))
vim.keymap.set("n", "<space>h", action("editor.action.showHover"))
vim.keymap.set("n", "<space>d", action("editor.action.goToDeclaration"))
vim.keymap.set("n", "<space>lf", action("editor.action.formatDocument"))
vim.keymap.set("n", "<space>s", action("workbench.action.files.save"))

```

keybindings.json
```json
[
  
]
```
