### ISSUE TITLE
bug: vim.tbl_islist is deprecated

### ISSUE THREAD

**Issue by Adnios** [vscode-neovim/vscode-neovim#2107]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Windows 11

### Describe the bug

After neovim 0.10, vim.tbl_islist is deprecated. With neovim 0.10, everytime open vscode with vscode-neovim, the warning message show up.
![image](https://github.com/vscode-neovim/vscode-neovim/assets/41060790/1e3318e9-5051-4b16-9d69-f35462f0a3db)
Maybe update below `vim.tbl_islist` to `utils.islist` refer: https://github.com/nvim-telescope/telescope.nvim/pull/3109
![image](https://github.com/vscode-neovim/vscode-neovim/assets/41060790/5eb71340-1100-4b71-927f-dd3bd0da2f7d)

### Steps To Reproduce

- With neovim 0.10, open vscode with vscode-neovim
- waring message shows up `vim.tbl_islist is deprecated...`

### Expected Behavior

No waring message

**Comment by xiyaowong** [comment]
You're using nvim 0.11.0
