### ISSUE TITLE
bug: Undo pops up Output window

### ISSUE THREAD

**Issue by jaydev947** [vscode-neovim/vscode-neovim#2109]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.9.4

### Operating system/version

Ubuntu 22.04

### Describe the bug

In the latest release v1.71.1 clicking on `u` in normal mode brings the output window of vs code into focus. When i downgraded to v1.71.0 the problem is not seen.

### Steps To Reproduce

Upgrade to v1.71.1 and make changes. and the click on `u` in normal mode. If the output is out of focus , it comes into focus

### Expected Behavior

The output window does should not come to focus like previous version.

**Comment by xiyaowong** [comment]
What's the value of "cmdheight"? Try ":echo &cmdheight"

**Comment by xiyaowong** [comment]
Solution https://github.com/vscode-neovim/vscode-neovim/issues/2099#issuecomment-2169085647

**Comment by zirho** [comment]
I use 0.9.4 and my `:echo &cmdheight` output is 3

**Comment by xiyaowong** [comment]
@zirho  How do you change the value of `cmdheight` in nvim 0.9? ❓

**Comment by xiyaowong** [comment]
Since `cmdheight` is always 0 in Nvim 0.9, 1 is used as the threshold for popping up the output. If the output pops up frequently, please use Nvim 0.10 and set `cmdheight` to a higher value.

**Comment by sumanth-lingappa** [comment]
I am using neovim 0.10 version and setting the below in my init.lua helped me to resolve this

```lua
if vim.g.vscode then
  cmdheight = 1 -- This is the extra config I added
  return
end

-- rest of the lua config
```

**Comment by xiyaowong** [comment]
@sumanth-lingappa Not needed. 1 is the default value

**Comment by sumanth-lingappa** [comment]
No @xiyaowong, it didn't work for me by default. I had to explicitly add.

**Comment by zirho** [comment]
> cmdheight

I didn't do anything specifically. Not sure how I can check what (or which) plugin is setting it. 
I could not find it in my `init.vim`

**Comment by phortonssf** [comment]
I cannot change the value of **cmdheight** with neovim ext **1.18.10** and NEOVIM -v **10.1**. I am using an empty init.lua
```
vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.opt.cmdheight = 1 -- This is the extra config I added
if vim.g.vscode then
  cmdheight = 1 -- this is the new line I added
  return
end
```
In my terminal neovim will load with the expected cmdheight of 1 but in vscode it will be 0. I am using ***echo &cmdheight** to check the value of cmdheight. 
Even when i use the **:set cmdheight=2** in neovim it works but does nothing in vsode neovim extension.

**Comment by xiyaowong** [comment]
@phortonssf 
1. Turn on `vscode-neovim.neovimClean`
2. Provide outputs of:
	- `:version`
	- `:echo &ch`

**Comment by phortonssf** [comment]
@xiyaowong So setting my default version to a different wsl instance fixed it. Works in the same wsl distro as well and other linux distros it wasn't previously.

**Comment by hyperfocus1337** [comment]
> > cmdheight
> 
> I just have it in my `init.vim`
> 
> ```
> set cmdheight=3
> ```
> 
> I left a comment there saying it's related to [spf13/spf13-vim#540](https://github.com/spf13/spf13-vim/issues/540)

This fixed it for me

**Comment by daelmaak** [comment]
In my case, even `cmdheight=3` wasn't enough when using [VimSneak](https://github.com/justinmk/vim-sneak). This would happen when I searched through VimSneak for a non-present string (eg. `no`), in which case the [message manager would encounter](https://github.com/vscode-neovim/vscode-neovim/blob/master/src/messages_manager.ts#L127) output from VimSneak like this `['>', '>n', '>no', 'not found']`. This output has length 4 which exceeded `cmdheight=3` and would therefore display the output.

So at least for me, the quick fix was (Lua)
```vimscript
vim.o.cmdheight=4
```

Though I can't tell all the implications right now as this number already feels quite high and arbitrary. Also still don't understand the message manager's reasoning on when to display output since `:h cmdheight` mentions that this setting only sets the height of the command line, not whether output gets shown at all 🤷 .

**Comment by Ansis100** [comment]
I'm using [pounce.nvim](https://github.com/rlane/pounce.nvim) and no matter what I set `cmdheight` to, the output window still appears. Is this because pounce can add output in new lines indefinitely? Can I somehow suppress the output of a specific plugin?

**Comment by victororlyk** [comment]
same issue for hop

**Comment by vdawg-git** [comment]
I have the same thing now. If I yank something the messages output window pops up.
Its very annoying. Setting cmdheight doesnt change anything :/

**Comment by sinkr** [comment]
Same annoyance here.

**Comment by metetolga** [comment]
```
    "workbench.view.showQuietly": {
        "workbench.panel.output": true
    }
```


Basically disabling output window completely. problems, terminal tabs can be still accessible. this is not `neovim`, `vscode-neovim` related solution tho. Paste the below config to `settings.json`
