### ISSUE TITLE
Feature request: !command support

### ISSUE THREAD

**Issue by Shadowsith** [vscode-neovim/vscode-neovim#211]
It is often useful to call console commands directly in vim.
In Vim/Neovim this can be done by !command.

I know this already works but unfortunately you can not see the output of the command.

Can you pipe the command output into the output tab of an open vscode terminal (or create a new terminal if no one exists)? That would be great.

**Comment by justinmk** [comment]
Fixed by https://github.com/vscode-neovim/vscode-neovim/pull/881
