### ISSUE TITLE
bug:  Render issue when deleting line

### ISSUE THREAD

**Issue by jruebsam** [vscode-neovim/vscode-neovim#2111]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.10.0

### Operating system/version

EndeavourOS 

### Describe the bug

When using dd to delete a line , the line  below is not rendered correctly.

This is a rendering issues and using `CTRL + L` seems to fix it. 
Is there some way how to fix this in general?

### Steps To Reproduce

For example see:
![image](https://github.com/vscode-neovim/vscode-neovim/assets/5864799/070aa38d-31fd-4c2b-95c5-86b02b9730c1)

Deleteting the empty line with dd gives something like:
![image](https://github.com/vscode-neovim/vscode-neovim/assets/5864799/bcd41dab-1906-47f6-9b66-b33267539425)

### Expected Behavior

The line should render correclty

**Comment by xiyaowong** [comment]
It's a highlighting issue. But I'm curious how such a strange misalignment occurred. Did you use any other plugins?

**Comment by jruebsam** [comment]
Currently in neovim i don't have any plugins enabled, I use some VsCode plugins for C++ / Cmake however I'm not sure if this is relevant. This occurs 100% when I do this. 
Probably not relevant but  I'm on KDE using X11 and the Nvidia 550.90.07 driver.

**Comment by xiyaowong** [comment]
[vscode-neovim.zip](https://github.com/user-attachments/files/15847118/vscode-neovim.zip)

Please test this build
