### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by theswit** [vscode-neovim/vscode-neovim#2114]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

NVIM v0.8.0

### Operating system/version

macos / rocky8 linux

### Describe the bug

I get cryptic error messages, and inconsistent ones at that between the neovim debug log and the pop-up error message.

note: I was, through binary search, able to figure out that v1.7 at least loads without error, though it's quite broken functionally.
There should be a compatibility table if the tool is going to hard-drop support for versions of nvim that are the latest available for mainstream enterprise linux distros.

### Steps To Reproduce

install extension on rocky8 linux/EL8. latest nvim available is 0.8.0
try to start vscode with the extension enabled

### Expected Behavior

a) work with nvim 0.8
b) give a useful error message if an incompatible version is installed.

**Comment by xiyaowong** [comment]
Upgrade your Nvim https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#installation

**Comment by theswit** [comment]
I can't. the tool should at least give a useful error message if it finds an incompatible version of nvim. but 0.8.0 is the latest available compatible release on EL8, so not supporting a mainstream release essentially means there's a huge population that cannot use this tool (after getting cryptic error messages)

**Comment by ruby3141** [comment]
On [Readme](https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#-getting-started) the author clearly said that this extensions requires neovim >=v0.9.0.
So if you want neovim <=v0.8.0 to be supported, you should have open this issue as feature request, not bug.

BTW there's [Unsupported Nvim Releases](https://github.com/neovim/neovim-releases?tab=readme-ov-file) for older glibc.
I heard that Rocky 8 uses glibc 2.28, so why don't you give it a try?
