### ISSUE TITLE
bug: `@` will deselect visually selected area since 1.1.3

### ISSUE THREAD

**Issue by echaya** [vscode-neovim/vscode-neovim#2115]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.9.5

### Operating system/version

win 10

### Describe the bug

I have been using the following function to execute macro in selected lines

```vim
" execute macro at visual range, does not stop when no match
xnoremap @ :<C-u>call ExecuteMacroOverVisualRange()<CR>
function! ExecuteMacroOverVisualRange()
  echo "@".getcmdline()
  execute ":'<,'>normal @".nr2char(getchar())
endfunction
```

Function-wise it has been working but lately I noted the visual block is not displaying properly after pressing `@`. When the code blocks are selected from visual mode >> press `@` will de-select everything.  I spent some time today and identify that it stops working from 1.1.3. 

### Steps To Reproduce

1. add the following function in an empty init.vim
```vim
" execute macro at visual range, does not stop when no match
xnoremap @ :<C-u>call ExecuteMacroOverVisualRange()<CR>
function! ExecuteMacroOverVisualRange()
  echo "@".getcmdline()
  execute ":'<,'>normal @".nr2char(getchar())
endfunction
```
2. Run `CODE`
3. Record some macro to any letter-x; *it can also be repro even without macro
4. Select multiple lines in visual mode
5. Press `@`

![visual not working](https://github.com/vscode-neovim/vscode-neovim/assets/34254408/a9df7a10-e262-4f73-be47-b88adadf84d3)

### Expected Behavior

The selected lines will keep selected after pressing `@`

![visual working properly](https://github.com/vscode-neovim/vscode-neovim/assets/34254408/e15def2b-bc06-4e19-82e0-c3579bbe94d7)

**Comment by theol0403** [comment]
Probably https://github.com/vscode-neovim/vscode-neovim/issues/2079

**Comment by xiyaowong** [comment]
Since 1.1.3 ?

**Comment by echaya** [comment]
> Since 1.1.3 ?

1.1.3 not 1.13 if thats your question.

**Comment by xiyaowong** [comment]
Actually, it's the same. It's just that v1.1.3 doesn't display the Visual highlight in nvim.

The issue is that the selection in nvim is not synchronized with VSCode.

**Comment by xiyaowong** [comment]
Use `:h <Cmd>`
```vim
xnoremap @ <Cmd>call ExecuteMacroOverVisualRange()<CR>
```

The `:<C-u>` changes the mode to command mode (c), which causes VSCode to lose the selection.

**Comment by echaya** [comment]
> Use `:h <Cmd>`. There's almost no reason to use `:<C-u>` anymore.
> 
> ```viml
> xnoremap @ <Cmd>call ExecuteMacroOverVisualRange()<CR>
> ```
> 
> The `:<C-u>` changes the mode to command mode (c), which causes VSCode to lose the selection.

It makes sense on the paper but may I check if you have tested it? It does not work unfortunately

**Comment by echaya** [comment]
If this is a bug you don't bother to fix, please leave it without closing

**Comment by xiyaowong** [comment]
I tested it

**Comment by xiyaowong** [comment]
Add
```jsonc
    "Visual": {
      "backgroundColor": "theme.editor.selectionBackground"
    }
```
to option `vscode-neovim.highlightGroups.highlights`

**Comment by echaya** [comment]
> I tested it

Do you use `<Cmd>` or `<C-u>`?

**Comment by xiyaowong** [comment]
- `<Cmd>` ok
- `:<C-u>` ng

**Comment by xiyaowong** [comment]
Please try the following steps.

1. `test.vim`
	```vim
	set stl=%{mode()}

	" execute macro at visual range, does not stop when no match
	xnoremap @ :<C-u>call ExecuteMacroOverVisualRange()<CR>
	function! ExecuteMacroOverVisualRange()
	  echo "@".getcmdline()
	  execute ":'<,'>normal @".nr2char(getchar())
	endfunction
	```
2. `nvim --clean -u test.vim`
3. Press `V`
4. Press `@`

The mode switches to `c`.


After changing `:<C-u>` to `<Cmd>`, the mode remains `V` throughout the same steps.

**Comment by xiyaowong** [comment]
In your function, add `redraw!`, test it with terminal nvim

**Comment by echaya** [comment]
> In your function, add `redraw!`, test it with terminal nvim
> 
> In fact, as long as you enter cmdline, the selected area will be lost. You can select some content in nvim, then press `:`. getchar just pauses drawing.

This is not true:

* Using 1.1.2 or earlier version of the plugin it was working (plz refer to the gif)
* The function and behavior is still working as expected on vim or nvim
* Macro is not working properly when replacing <c-u> to <cmd> => that's why I asked if you have tested it.

**Comment by xiyaowong** [comment]
https://github.com/vscode-neovim/vscode-neovim/issues/2115#issuecomment-2177424967

**Comment by xiyaowong** [comment]
> Macro is not working properly when replacing <c-u> to <Cmd> => that's why I asked if you have tested it.

I understand what you mean now, but this is unrelated to the issue.

**Comment by echaya** [comment]
> > Macro is not working properly when replacing  to  => that's why I asked if you have tested it.
> 
> I understand what you mean now, but this is unrelated to the issue.

IMHO, it is evident that utilizing `<Cmd>` as a workaround in this particular use-case is simly ineffective. I kindly request that you reopen this issue.

**Comment by xiyaowong** [comment]
@theol0403 Again, https://github.com/vscode-neovim/vscode-neovim/issues/2115#issuecomment-2177424967

**Comment by xiyaowong** [comment]
Again, https://github.com/vscode-neovim/vscode-neovim/issues/2115#issuecomment-2177424967
