### ISSUE TITLE
bug: Fast repitition of VSCode's "Move Line Up/Down" command messes up selected lines

### ISSUE THREAD

**Issue by ruby3141** [vscode-neovim/vscode-neovim#2118]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

Windows 11 Pro 23H2 22631.3593

### Describe the bug

[recording.webm](https://github.com/vscode-neovim/vscode-neovim/assets/3256382/d8dd4b59-31a9-4486-a242-da95428749d0)

When you try to move selected lines up/down by hard pressing shortcut of VSCode's "Move Line Up/Down" commands (Default shortcut assigened on `<A-up>` and `<A-down>`), selected lines can be appended, dropped or mixed.

### Steps To Reproduce

1. Select multiple lines using <S-v> Visual line mode, or just with your mouse.
2. Press down `<A-up>` to do `editor.action.moveLinesUpAction` or `<A-down>` to do `editor.action.moveLinesDownAction`.
  Higher chance of happening when you do it over the edge of visible area.

### Expected Behavior

Selected lines should move up/down without undeterministic behavior.

**Comment by ruby3141** [comment]
I tried increasing `vscode-neovim.neovimViewportHeightExtend`, but it didn't help.

A workaround can be done by assigning this shortcuts on VSCode
```json
    {
        "key": "alt+up",
        "command": "vscode-neovim.send",
        "when": "neovim.init && neovim.recording || editorTextFocus && neovim.init && neovim.mode != 'insert' && editorLangId not in 'neovim.editorLangIdExclusions'",
        "args": "<A-up>"
    },
    {
        "key": "alt+down",
        "command": "vscode-neovim.send",
        "when": "neovim.init && neovim.recording || editorTextFocus && neovim.init && neovim.mode != 'insert' && editorLangId not in 'neovim.editorLangIdExclusions'",
        "args": "<A-down>"
    },
```
and add this remap on `init.vim`.
```vim
  nnoremap <silent><A-up> :silent! move -2<CR>
  nnoremap <silent><A-down> :silent! move +1<CR>
  inoremap <silent><A-up> <Esc>:silent! move -2<CR>a
  inoremap <silent><A-down> <Esc>:silent! move +1<CR>a
  vnoremap <silent><A-up> :<C-u>silent! '<,'>move '<--<CR>gv
  vnoremap <silent><A-down> :<C-u>silent! '<,'>move '>+<CR>gv
```
It works, but has a problem as well.
I will open another issue about that.

**Comment by xiyaowong** [comment]
Recommend using commands like those in VSCode, and avoid rapid operations. Due to the bidirectional synchronization of vscode-neovim, simultaneous modifications to content, selected areas, and cursor positions are challenging to support during fast operations.
