### ISSUE TITLE
bug: editor flickers(by showing intermediate state for short time) while using `:move`

### ISSUE THREAD

**Issue by ruby3141** [vscode-neovim/vscode-neovim#2119]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

Windows 11 Pro 23H2 22631.3593

### Describe the bug

If you move selected lines using `:move` command, intermediate state is displayed for short period of time, make lines below to flicker.

[r1.webm](https://github.com/vscode-neovim/vscode-neovim/assets/3256382/f9934bd1-6efd-4989-bac8-3dd25be2d20b)

The frame before flicker.
![139](https://github.com/vscode-neovim/vscode-neovim/assets/3256382/f3facdee-4c7f-4675-aa46-dd7a220079a1)

The frame when intermediate state has displayed.
![140](https://github.com/vscode-neovim/vscode-neovim/assets/3256382/75fb73b9-c5e9-4d76-854b-03fc02f48a3d)

The frame after flicker.
![141](https://github.com/vscode-neovim/vscode-neovim/assets/3256382/a813338a-e788-4376-82e6-ac0cc66c305d)

On nvim with Windows Terminal there's no visible artifact like this. 

[r2.webm](https://github.com/vscode-neovim/vscode-neovim/assets/3256382/cd677c11-fa2a-4706-8d08-635114e2bc5b)

On per-command perspective it's not a big deal, but if you use "Move Lines Up/Down" keymaps like https://github.com/vscode-neovim/vscode-neovim/issues/2118#issuecomment-2171995318 it makes users hard to land their moving lines on desired position, especially moving downward.

### Steps To Reproduce

1. Select line(s) you want to move. It happens regardless of selection size, but with larger selection it will be more visible.
2. use `:move` command to move selections up or down.

### Expected Behavior

Not showing intermediate state while using `:move` command.

**Comment by theol0403** [comment]
This is likely out of our control, and is related to nvim internals. I would guess instead of sending one ui update it sends one for the inserted text and one for the deleted text. Due to lag in vscode this is perceived.
