### ISSUE TITLE
feature: Integrating plugin Status to right corner notification area

### ISSUE THREAD

**Issue by xchray** [vscode-neovim/vscode-neovim#2120]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

Hello,
first of all, thank you so much for this awesome plugin. 

I am using it with many plugins. And my vscode has also some plugins.  All these make the loading of VScode very long, which is fine. However, the problem is I don't know when the plugin is ready at all. 

Today, I am using vscode.notify to popup a message for myself. The problem of this one is that it disappeared after sometime or sometime after a click it is gone. 

I am wondering if it is possible to do the same like Ruff using the right corner for status. 

Thanks so much. 
![image](https://github.com/vscode-neovim/vscode-neovim/assets/81406963/e67df6d9-714a-4d8d-8bb5-7787a35cba2f)

### Describe the solution you'd like

Using right lower corner to show the status of plugin. 

![image](https://github.com/vscode-neovim/vscode-neovim/assets/81406963/e60cd0e4-6359-43e2-8a85-a6b160868151)
 

### Describe alternatives you've considered

Otherwise I will stay with vscode.notify

**Comment by xiyaowong** [comment]
You can add some content to the statusline. e.g. `set stl=Nvim`

**Comment by theol0403** [comment]
Might be a nice QOL improvement to add an item here which shows "loading/active/disabled" status and "enable/disable/restart" buttons. This is separate from nvim statusline.
