### ISSUE TITLE
bug: Neovim immediately disconnects even on clean run - extension not working 

### ISSUE THREAD

**Issue by DominikMendel** [vscode-neovim/vscode-neovim#2121]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Ubuntu 22

### Describe the bug

I just installed the extension, and after setting everything I cannot get the neovim service working. It immediately disconnects. 
See debugging logs. 
![image](https://github.com/vscode-neovim/vscode-neovim/assets/11708209/2314eab4-c6ee-42e9-b0bb-1f534ec04576)

And output from log: 
2024-06-20T19:11:01.882Z MainController: Starting nvim: /snap/bin/nvim -N --embed --cmd source /home/dominik/.vscode/extensions/asvetliakov.vscode-neovim-1.17.2/runtime/vscode-neovim.vim --clean

### Steps To Reproduce

1. Install extension 
2. Setup configuration 
3. Run clean
4. Get immediate failures 

### Expected Behavior

Something to work

**Comment by justinmk** [comment]
your screenshot shows a EACCES (permissions) error. that's probably related to snap.

try installing nvim without snap.

**Comment by DominikMendel** [comment]
> your screenshot shows a EACCES (permissions) error. that's probably related to snap.
> 
> try installing nvim without snap.

Yes this fixed it. Thanks!
