### ISSUE TITLE
bug: Can't run vscode-neovim in react-native project

### ISSUE THREAD

**Issue by 1wolfalone1** [vscode-neovim/vscode-neovim#2123]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.10.0

### Operating system/version

ubuntu 24

### Describe the bug

I'm not sure why I can't run vscode-neovim in my React Native project. 

### Steps To Reproduce

The issue is strange because "Neovim was disconnected", or sometimes I can't use hjkl or switch modes (i, a, v). However, it works perfectly fine in Java or Golang projects.

### Expected Behavior

Run vscode-neovim plugins in react native project.

**Comment by xiyaowong** [comment]
Please search the existing issues first.
