### ISSUE TITLE
~bug: documentation should warn user about `<leader>` bindings in vs code

### ISSUE THREAD

**Issue by bigH** [vscode-neovim/vscode-neovim#2124]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

NA

### Operating system/version

NA

### Describe the bug

I ran into an issue where my `<leader>` bindings in neovim didn't work in vs code. After removing any bindings that use `<leader>` in vs code, the bindings in neovim started to work in vs code. This is a surprising issue and should be called out better in the docs.

### Steps To Reproduce

NA

### Expected Behavior

Warning in docs.

**Comment by xiyaowong** [comment]
So what's the problem? How did you set the `<leader>`?

**Comment by theol0403** [comment]
Yeah, what is the problem? No reason why leader isn't supported by this ext.

**Comment by bigH** [comment]
I had chorded bindings that used the same key as leader to get similar
behavior in vs code. e.g in nvim I use `<leader>e` so I mapped `\ e` (key
chord) in vs code. This resulted in other chorded leader bindings that are
set in nvim to not work.

**Comment by theol0403** [comment]
This is not a vscode-neovim or documentation issue... this is the nature of how conflicting bindings work in nvim no?
