### ISSUE TITLE
bug: Newer Versions not available on some devices

### ISSUE THREAD

**Issue by themuuln** [vscode-neovim/vscode-neovim#2125]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

Windows 11

### Describe the bug

![image](https://github.com/vscode-neovim/vscode-neovim/assets/75017829/633cf650-425b-4881-a684-b1c0b6c3750b)

can't install newer version

### Steps To Reproduce

1. Install Another version

### Expected Behavior

Show Newer Versions

**Comment by xiyaowong** [comment]
It could be an issue with your environment. You can try manually downloading it from the [marketplace](https://marketplace.visualstudio.com/items?itemName=asvetliakov.vscode-neovim).

**Comment by justinmk** [comment]
What version of vscode are you using? That is one thing that decides this.

**Comment by theol0403** [comment]
Yes, this extension specifies a minimum vscode version.
