### ISSUE TITLE
feature: default key maps for neovim builtin functionality

### ISSUE THREAD

**Issue by antonk52** [vscode-neovim/vscode-neovim#2130]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

When starting to work with vscode-neovim people commonly need to explore existing vscode commands to repro some of the builtin functionality into neovim. For example folds, to get basic functionality it is required to add the following to your init.lua

```lua
if vim.g.vscode then
    vim.keymap.set('n', 'za', ':call VSCodeNotify("editor.toggleFold")<cr>', { desc = 'toggle fold' })
    vim.keymap.set('n', 'zM', ':call VSCodeNotify("editor.foldAll")<cr>', { desc = 'fold all' })
    vim.keymap.set('n', 'zR', ':call VSCodeNotify("editor.unfoldAll")<cr>', { desc = 'unfold all' })
    -- other
end
```

It would be a bit qol improvement if such things would be built in.

I understand that this can be tricky due to the maintenance burden of a list of not exactly 1:1 matching vscode commands. 

### Describe the solution you'd like

Have such keymaps enabled by default.

### Describe alternatives you've considered

Provide an opt in `require('vscode.keymaps')` module which sets the key maps. This way users have to explicitly call it to enable the builtin vscode commands mappings.

### Additional context

Happy to send a PR once it is confirmed that this is a welcome change.

Since this plugin already has `shift+K` keymap enabled by default. I thought this might be a welcomed change too

https://github.com/vscode-neovim/vscode-neovim/blob/08e973d20e93835416c3c5a7bd3a81239c02d213/package.json#L1675-L1679

**Comment by theol0403** [comment]
What other bindings do you want included other than these three fold bindings? Generally we already have nearly-full coverage of most common native vim bindings.

These fold bindings are specifically not included because moving across a fold currently triggers its expansion (folds are not synced to vim, so it doesn't know to skip them).

**Comment by antonk52** [comment]
Good point about auto opening vim folds. I have not considered it when opening the issue.

A couple of other things that would be nice to have out of the box are lsp functionality and below are other vscode related keymaps that I do not an opinion if they should be included or not.

## LSP

For lsp there can be a different approach to setting a keymap as most functionality is not mapped by default and is typically done by the user. However, we can use `vim.lsp.with()` to wrap builtin functions. This way a user won't need to change anything in their configuration and the same keybindings will work in vscode. See example

```lua
vim.lsp.handlers['textDocument/definition'] = vim.lsp.with(function()
    require('vscode-neovim').call('editor.action.revealDefinition')
end, {})
```

The same can be done for other lsp handlers.

## Other key maps

```lua
-- these are default mappings in neovim since 0.10
vim.keymap.set('n', ']d', ':call VSCodeNotify("editor.action.marker.next")<cr>')
vim.keymap.set('n', '[d', ':call VSCodeNotify("editor.action.marker.prev")<cr>')

-- default mapping with netrw and some other directory management plugins
vim.keymap.set('n', '-', ':call VSCodeNotify("workbench.files.action.showActiveFileInExplorer")<cr>')
```

**Comment by theol0403** [comment]
Are the lsp commands not already handled by https://github.com/vscode-neovim/vscode-neovim/pull/2045?

And the ]d bindings are on the roadmap, but there isn't a 1-to-1 correlation to vscode (can't specify severity) so we would need custom code (check the vim.diagnostic issue in this repo).

**Comment by antonk52** [comment]
Thanks for the code pointer. I have tested it and it works flawlessly. I guess this issue can be closed now.

At my job we use a fork of VS Code and it looks like files inside `runtime/vscode` are not being sourced. Thus vim.lsp.buf and vim.ui are not overwritten. An idea or a code pointer on how can this debugged would be highly appreciated.
