### ISSUE TITLE
bug: Ctrl hjkl navigation key bindings not working

### ISSUE THREAD

**Issue by duffney** [vscode-neovim/vscode-neovim#2133]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

Windows 11

### Describe the bug

No matter what way I define the remap it doesn't take effect. I've tired adding to init.lua, keyboard shortucts in vscode and keybindings.json

### Steps To Reproduce

1. Open keybindings.json
2.  Add the following:

```json
    {
        "command": "vscode-neovim.send",
        "key": "ctrl+j",
        "when": "editortextfocus && neovim.mode != insert",
        "args": {
            "command": "<C-w>j"
        }
    },
```

### Expected Behavior

With the change I am expecting to be able to navigate with ctrl j down the next n windows.

**Comment by xiyaowong** [comment]
In most cases, for UI-related operations, you need to call VSCode commands.

Two ways:

1. Set a shortcut in VSCode to call a VSCode command directly.

```json
  {
    "key": "ctrl+j",
    "command": "workbench.action.navigateDown",
    "when": "editorTextFocus && neovim.mode == normal"
  }

```

2. Set up a mapping in Nvim to call a VSCode command.

```lua
vim.keymap.set('n', '<C-j>', function ()
  require('vscode').action("workbench.action.navigateDown")
end)
```

**Please read README carefully. Your usage is completely incorrect.**
