### ISSUE TITLE
Output channel: `ui-messages` handling, `MessagesManager` logging 

### ISSUE THREAD

**Issue by ian-h-chamberlain** [vscode-neovim/vscode-neovim#2134]
Hi, I know this has been an area that's changed a lot recently, so hopefully this isn't stirring up too much trouble, but I noticed that the `ui-messages` handling seems to be slightly inconsistent at times, and I think I know why. I can probably open a PR to address it, but I wanted to check that the approach seems agreeable first.

## The issue

A simple example that shows the kind of thing I'm talking about. With `neovimClean` set, I source this file:
```lua
local i = 0

function do_echo()
    vim.api.nvim_command('echom "' .. vim.inspect(i) .. ' line 1\nline 2\nline 3"')
    i = i + 1

    if i < 5 then
        vim.defer_fn(do_echo, 1500)
    end
end

do_echo()
```

The `vscode-neovim messages` channel only appears to show one update, which (maybe comes from modeline?) is displayed as `1 line 1^@line 2^@line 3`. It's possible to see the messages with `:messages`, but I would expect the output panel to be updated as well (as in `nvim`).

The `vscode-neovim logs` panel is interesting here. The messages don't appear to be logged, except for the visible one:
```
2024-06-30 17:30:57.363 [info] MessagesManager: 1 line 1^@line 2^@line 3
2024-06-30 17:31:07.665 [debug] BufferManager: Editor viewColumn: undefined, winId: 1005, closing
2024-06-30 17:31:07.665 [debug] BufferManager: Document: output:asvetliakov.vscode-neovim.vscode-neovim%20logs, bufId: 5, deleting
2024-06-30 17:31:07.666 [debug] BufferManager: Visible editor, viewColumn: 1, doc: file:///Users/ianchamberlain/Downloads/repro.lua
2024-06-30 17:31:07.666 [debug] BufferManager: Visible editor, viewColumn: 2, doc: file:///Users/ianchamberlain/Documents/Development/vscode-neovim/src/messages_manager.ts
2024-06-30 17:31:07.669 [warning] ViewportManager: Unable to update scrolled view. No grid for winId: 1006
2024-06-30 17:31:11.963 [debug] BufferManager: Editor viewColumn: undefined, winId: 1006, closing
2024-06-30 17:31:11.964 [debug] BufferManager: Visible editor, viewColumn: 1, doc: file:///Users/ianchamberlain/Downloads/repro.lua
2024-06-30 17:31:11.964 [debug] BufferManager: Visible editor, viewColumn: 2, doc: file:///Users/ianchamberlain/Documents/Development/vscode-neovim/src/messages_manager.ts
2024-06-30 17:31:12.035 [warning] ViewportManager: Unable to update scrolled view. No grid for winId: 1007
````

However I can see them after running `:messages`, all concatenated together:

```
2024-06-30 17:33:59.180 [debug] ModeManager: Setting mode context to normal
2024-06-30 17:33:59.180 [info] MessagesManager: echomsg: 0 line 1
line 2
line 3
echomsg: 1 line 1
line 2
line 3
echomsg: 2 line 1
line 2
line 3
echomsg: 3 line 1
line 2
line 3
2024-06-30 17:33:59.182 [debug] StatusLineManager: Skipping statusline clear as a message is currently pending
```

## Why I think it happens

Reading `:help ui`, I think there are a couple potential problems here working together:
1. Messages are written immediately when `msg_show` is received, instead of being collected until a neovim `flush` event.
2. `msg_show` events have a boolean `replace_last`, which if set means:
  	> Replace the message in the most-recent `msg_show` call, but any other visible message should still remain.

  	Looking at the implementation `messages_manager.ts`, it seems like all previous messages in the notification would be cleared, instead of just the last one. 
3. From what I can tell, `msg_clear` is unimplemented except for statusline

For one example, looking at a `/` search that doesn't match, `nvim` normally shows two lines and then a prompt:
```
/asdfklj
E486: Pattern not found: asdfklj
Press ENTER or type command to continue
```

`vscode-neovim` only shows the second line, (third one omitted, related to https://github.com/vscode-neovim/vscode-neovim/issues/2046#issuecomment-2144175058 I think):

<img width="698" alt="Screenshot 2024-06-30 at 17 52 44" src="https://github.com/vscode-neovim/vscode-neovim/assets/11131775/b74fd915-5f2d-4a4d-8022-bf3d75b9f45d">

## Proposed change

I believe it's possible to behave closer to vanilla `nvim`, if the message manager worked closer to how `ui-events` are describe. Effectively:
* Maintain a new internal message buffer
* `redraw`:
	* `msg_show`: append message string to a `string[]` buffer
		* if `replace_last`: replace last message in the buffer with the current one
		* Maybe do something different with `return_prompt` here too?
	* `msg_history_show`: replace internal buffer with incoming history messages. Maybe this should use a separate buffer even?
	* `msg_clear`: clear internal buffer
* `flush-redraw`:
	* append internal buffer to output channel (and logs)
	* clear internal buffer

If all that sounds reasonable, I am happy to work on a PR for it! I think it's possible without too much refactoring outside of `messages_manager.ts`, and maybe will also help make the experience more consistent with `nvim`. Since this has been troublesome lately, it would need a lot of testing around things like `cmdheight` and the changes between 0.9 and 0.10.

Thanks! Let me know what y'all think.

**Comment by xiyaowong** [comment]
It's worth trying. The current message implementation is rough, and Neovim ui-messages also have flaws. 

Additionally, I've mentioned this issue before but haven't addressed it. https://github.com/vscode-neovim/vscode-neovim/issues/1965#issuecomment-2114839321

**Comment by ollien** [comment]
Thanks for the report @ian-h-chamberlain; I think your analysis and proposed solution is sound. I will caution you, however, about `return_prompt`, as I lost a few hours and some component of my sanity tracking this down. You linked to this comment, https://github.com/vscode-neovim/vscode-neovim/issues/2046#issuecomment-2144175058, but I did want to call attention to point #2 there. There are significantly more cases where nvim sends us `return_prompt` than you would experience in a tui session of `nvim`.

If you wanna take a stab at this in a PR, by all means!

**Comment by ollien** [comment]
@ian-h-chamberlain Do you plan to submit a PR for this? If you want to and just haven't gotten the time (a problem I am greatly sympathetic to...), do let me know; I don't mind letting this sit :). Otherwise, I may take a stab at it when I get a free cycle.

**Comment by ian-h-chamberlain** [comment]
@ollien yes, I am still planning on submitting something! As you guessed I have not had the time to sit down and finish it recently; I have a WIP that does most of what I proposed, but I think it still had some issues last time I was working on it, so I just need to clean it up and work out some corner cases (including the `return_prompt` issue you mentioned).

I hope to get some time maybe this week or next to revisit it — will let you know if anything changes on that front.
