### ISSUE TITLE
feature: compositeKeys supports `when`

### ISSUE THREAD

**Issue by echaya** [vscode-neovim/vscode-neovim#2142]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

vscode-neovim.compositeKeys provide a neat way that triggers neovim command during `Insert` mode. It would be cool if it supports `when` param used in keybindings so the neovim command is fired when propriate (e.g., when matching certain editor type).  

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

**Comment by xiyaowong** [comment]
This is difficult to achieve because 'compositeKeys' and keybinding have no relation to each other. Moreover, 'when' in VSCode is not accessible.

**Comment by xiyaowong** [comment]
For example, `jj` only exits insert mode in Python files.
```jsonc
  "vscode-neovim.compositeKeys": {
    "jj": {
      "command": "vscode-neovim.lua",
      "args": [[
        "local code = require('vscode')",
        "if vim.bo.ft == 'python' then",
        "  code.action('vscode-neovim.escape')",
        "else",
        "  code.action('default:type', { args = { text = 'jj' } })",
        "end"
      ]]
    }
  }
```
