### ISSUE TITLE
bug: Bracket Pairs Horizontal line is disapear

### ISSUE THREAD

**Issue by an1ndra** [vscode-neovim/vscode-neovim#2144]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

v0.11.0-dev

### Operating system/version

Pop OS! 22.04

### Describe the bug

When updated this plugin to current latest version (1.18.1). It disapear the bracket pairs horizontal line (Some times brackets also). But lower version like `vscode-neovim-v1.15.1.vsix` works fine without any issue.
[Screencast from 07-06-2024 10:46:44 PM.webm](https://github.com/vscode-neovim/vscode-neovim/assets/36324543/21a9f152-1098-48ce-bf34-0385d8fde470)

### Steps To Reproduce

1. Update VScodium neovim version to latest version.
2. Reload plugin and VScodium.
3. Bracket pairs horizontal line disapears.

### Expected Behavior

Should work find as expected and like other old version.

**Comment by ollien** [comment]
Are you referring to the rulers introduced by `editor.guides.bracketPairs`? If so, I can't reproduce this (see screenshot below where I have the blue underline on the selected parenthesis pair, line 107). If it's something else, please let me know.

![image](https://github.com/vscode-neovim/vscode-neovim/assets/977151/94bf65f7-5ba3-4518-ae8c-a8bdae8ef25c)

**Comment by an1ndra** [comment]
Can you try this settings https://gist.github.com/an1ndra/48b901ec60a5ba3374c4c44a58318e9d

**Comment by xiyaowong** [comment]
@an1ndra  Please enable `vscode-neovim.neovimClean` and check if the issue still persists.

**Comment by xiyaowong** [comment]
@an1ndra 

Please enable the `vscode-neovim.neovimClean` option and follow these steps to provide the information:

1. Open Developer Tools: Help -> Toggle Developer Tools
2. Select the element where the indent line disappears
3. Check if the element has a class like TextEditorDecorationType.

![image](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/ea9c023a-96ad-41bb-8c3b-9849f143bdea)

**Comment by an1ndra** [comment]
When `vscode-neovim.neovimClean` enable

![Screenshot from 2024-07-09 19-34-29](https://github.com/vscode-neovim/vscode-neovim/assets/36324543/d9f03e93-2b1a-4a70-ac7c-088f1ea9f518)


When `vscode-neovim.neovimClean` disable

![Screenshot from 2024-07-09 19-35-20](https://github.com/vscode-neovim/vscode-neovim/assets/36324543/01472768-34f5-4946-b90d-f9283ae52522)

**Comment by xiyaowong** [comment]
@an1ndra It seems to be caused by a plugin. Could you share the list of Nvim plugins you are using?

**Comment by an1ndra** [comment]
@xiyaowong https://docs.astronvim.com/reference/default_plugins/ this all plugins I am using.

**Comment by xiyaowong** [comment]
@an1ndra 

Disable indent-blankline.nvim

Please avoid using such "large" configurations in vscode-neovim. In most cases, you only need plugins related to cursor movement, text objects, and quick editing.

Recommendations:
1. Disable all existing plugins.
2. Enable only the plugins you feel are essential in vscode, one by one.
3. If a plugin doesn't work, you can open an issue.
