### ISSUE TITLE
bug: Cursor position doesn't sync (sometimes)

### ISSUE THREAD

**Issue by OldStarchy** [vscode-neovim/vscode-neovim#2146]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

v0.9.4

### Operating system/version

5.15.153.1-microsoft-standard-WSL2

### Describe the bug

Sometimes (maybe once a week or less) moving the cursor with the mouse will stop working. The cursor in VSCode will move, but any subsequent typing action will jump back to the "original" location and execute there.

Closing and reopening the tab doesn't help, restarting the neovim extension fixes it.

It may be related to having returned to my computer after lunch and some timeout occurs.

eg.
```
foo bar|
baz quz

something else
```

click to move cursor after "else"

```
foo bar
baz quz

something else|
```

type "a"

```
foo bara|
baz quz

something else
```

Note that I have not tried the `vscode-neovim.neovimClean` setting as it requires a restart to neovim which will fix (mostly) the issue already.

### Steps To Reproduce

I don't know how to repro.

### Expected Behavior

The VSCode cursor position and neovim cursor position stay in sync.

**Comment by xiyaowong** [comment]
https://github.com/vscode-neovim/vscode-neovim/blob/806e241f28025eb7d542eb309e40c661efae5677/package.json#L326

**Comment by xiyaowong** [comment]
TODO: In the README, inform users to check all configuration options and commands under Extension Details -> Features.
![image](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/14c2f917-8449-40aa-a51d-187630f943e2)

**Comment by OldStarchy** [comment]
I will try configuring this setting next time the bug occurs, though I would not have thought such a setting would have any effect.

**Comment by OldStarchy** [comment]
Setting this to `200` did not fix the problem, it just made it slower.
Setting it to `0` had weird results, it worked on some clicks but not others.
Setting it back to `200` it was now working properly again.
Setting it back to `100` it was still working.

I'll test more next time it happens.

**Comment by OldStarchy** [comment]
It seems to be affected by scrolling, though that may because I'm currently in a merge view.

**Comment by xiyaowong** [comment]
It should be set to a smaller value. However, I forgot that this option only provides a few fixed choices. Moreover, this is a difficult problem to avoid. What this plugin does is always synchronizing the states of VSCode and NVim bidirectionally. Debouncing is necessary. Therefore, it's highly likely that when changing the state in VSCode and quickly performing an operation in NVim, the synchronization might not be completed yet.
