### ISSUE TITLE
bug: `leap.nvim`'s beacons no longer show with the recent `leap.nvim` updates

### ISSUE THREAD

**Issue by echaya** [vscode-neovim/vscode-neovim#2147]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Win 10

### Describe the bug

First of all, this is an reopen of https://github.com/vscode-neovim/vscode-neovim/issues/2145 which was irresponsibly closed. Please KEEP IT OPEN if you couldn't care less about this issue. 

In the past 2 years, this community has made great efforts (I counted at least 8 pull requests merged) from @theol0403 @windwp @trkoch @ollien  among other great contributors to support `extmark`/ `highlights` for plugins include but not limit to `vim-sneak`, `leap-nvim`, `hop.nvim` among other similar motion plugins. 

The issue: `leap.nvim`'s beacons (those highlighted labels) are no longer showing since its related update on their repo on beacon refactoring / highlight logic update from last week.  

### Steps To Reproduce

pressing `swh` should highlight all `wh` from "when" with those beacons/labels, but nothing is highlighted at the moment

```JSON
    {
        "key": "ctrl+alt+k",
        "command": "-bookmarks.toggle",
        "when": "editorTextFocus"
    },
    {
        "key": "alt+a",
        "command": "jupyter.insertCellAbove",
        "when": "editorTextFocus && jupyter.hascodecells && !notebookEditorFocused"
    },
    {
        "key": "ctrl+; a",
        "command": "-jupyter.insertCellAbove",
        "when": "editorTextFocus && jupyter.hascodecells && !notebookEditorFocused"
    },



### Expected Behavior

beacons are highlighted

**Comment by xiyaowong** [comment]
Try 
```lua
vim.api.nvim_set_hl(0, 'LeapLabel', { fg = '#282c34', bg = '#98c379' })
```

**Comment by echaya** [comment]
Indeed this fixes the issue. For anyone else has this issue, `LeapLabelPrimary` also needs to be set for highlight. 

@xiyaowong I'm thankful for your prompt response and solution this time but would appreciate even more if you could close anything with more detailed explanation.

**Comment by xiyaowong** [comment]
See https://github.com/ggandor/leap.nvim/issues/239

**Comment by trkoch** [comment]
@xiyaowong Thanks for the provided snippet. Is choosing colors via `highlightGroups.highlights` in `settings.json` a viable alternative? I'd be interested to hear about drawbacks of this approach. The advantage I see is that colors of (VSCode) themes can be referenced.

```json
"vscode-neovim.highlightGroups.highlights": {
  "LeapLabel": {
    "backgroundColor": "theme.terminal.ansiBrightCyan",
    "color": "#eeeeee"
  },
}
```

**Comment by xiyaowong** [comment]
@trkoch 

> I'd be interested to hear about drawbacks of this approach.

No disadvantages
