### ISSUE TITLE
edit command doesn't autocomplete files

### ISSUE THREAD

**Issue by pavkum** [vscode-neovim/vscode-neovim#215]
Hello,

First of all, thanks for the awesome extension.

I'm trying to edit file in my home directory (my workspace points do different directory, I wanted to quickly edit a dot file in my home directory) using **edit** command. From vscode-neovim command palette I typed **e ~/**  and pressed tab. I didn't see any autocomplete results. Is it as expected? How do I use **edit** like use it in vim?

Thank you

**Comment by asvetliakov** [comment]
It works but autocompletion replaces whole path with latest completion result
