### ISSUE TITLE
Option to start disabled by default

### ISSUE THREAD

**Issue by kazmath** [vscode-neovim/vscode-neovim#2157]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

My workflow with the VscodeVim extension involved it not being enabled most of the time and when I want to use macros and other vim features I toggle it with `alt+v` and maybe disable when I want to use normal vscode keybindings. That is not currently possible afaik with this extension.

I solved the toggle problem with https://github.com/vscode-neovim/vscode-neovim/pull/1566#issuecomment-1852111050, but I can't find a way to have it disabled by default.

### Describe the solution you'd like

I can think of a few solutions:

1. An option like VscodeVim's `vim.disableExtension` (maybe `vscode-neovim.enabled`) that defaults to the extension being enabled and needing a `neovim.restart` command to work.

2. Have the `vscode-neovim.afterInitConfig` setting only run once instead of call to `neovim.restart` to allow for something like `lua require('vscode').call("vscode-neovim.stop")` to work

3. Same as above but in a separate setting like `vscode-neovim.onExtensionLoad`

4. Vim event in the API that only runs on restarts to allow for something like
```lua
local has_restarted = false
vim.api.nvim_create_autocmd("VscodeNeovimRestart", {
  callback = function(_)
    has_restarted = true
  end
})

if not has_restarted then
  require('vscode').call("vscode-neovim.stop")
end
```

### Describe alternatives you've considered

I have tried putting something like
```lua
local vscode = require('vscode')
if vscode.get_config("vscode-neovim.enabled") ~= nil and not vscode.get_config("vscode-neovim.enabled")
    vscode.call("vscode-neovim.stop")
end
```
in my neovim init files with a custom `vscode-neovim.enabled` in my settings.json, but all that does is permanently disable the extension.

If there is a way to make this work somehow and I am not seeing please tell me.

**Comment by xiyaowong** [comment]
Disable Extension (Workspace)

**Comment by xiyaowong** [comment]
> 1. An option like VscodeVim's `vim.disableExtension` (maybe `vscode-neovim.enabled`) that defaults to the extension being enabled and needing a `neovim.restart` command to work.

This option is counterintuitive. Why disable the extension but still need to use the commands provided by the extension?

> 2. Have the `vscode-neovim.afterInitConfig` setting only run once instead of call to `neovim.restart` to allow for something like `lua require('vscode').call("vscode-neovim.stop")` to work

Introducing a new mechanism isn't worth it.

> 3. Same as above but in a separate setting like `vscode-neovim.onExtensionLoad`

This is acceptable but still doesn't seem worth providing a separate setting for.

> 4. Vim event in the API that only runs on restarts to allow for something like

Introducing a new mechanism isn't worth it.

---

Overall, this is a rare use case. I recommend using the following approach for now:

```lua
local vscode = require 'vscode'

---Check if it's the first time starting up
---@return boolean
local is_first_startup = function()
  local activated = vscode.eval 'return vscode.vscode_neovim_activated'
  if activated and activated ~= vim.NIL then
    return false
  end
  vscode.eval 'vscode.vscode_neovim_activated = true'
  return true
end

if vim.g.vscode then
  if is_first_startup() then
    vscode.action 'vscode-neovim.stop'
  end
end
```

**Comment by kazmath** [comment]
So what this means is that the `vscode` package and its variables persist neovim embedded instances but not between vscode launches? That could be documented somewhere imo, but I will try that, thanks!

**Comment by kazmath** [comment]
I tried including that in multiple places, but, although it works, this keeps loading non-stop. Even after a `neovim.restart` action to start it up.
![image](https://github.com/user-attachments/assets/f9a65883-0ba1-4572-889a-ce4addfc25be)

**Comment by kazmath** [comment]
Well, while that is still an issue I'll at least respond to the responses you first gave me:

> > 1. An option like VscodeVim's `vim.disableExtension` (maybe `vscode-neovim.enabled`) that defaults to the extension being enabled and needing a `neovim.restart` command to work.
> 
> This option is counterintuitive. Why disable the extension but still need to use the commands provided by the extension?

The way the VscodeVim does it is exactly how I described, if you set `vim.disableExtension` to `true`, the extension will load, but will not work in vim mode, you need the `toggleVim` action for that. Their naming is indeed counterintuitive, since disableExtension doesn't actually disable the extension.

> > 2. Have the `vscode-neovim.afterInitConfig` setting only run once instead of call to `neovim.restart` to allow for something like `lua require('vscode').call("vscode-neovim.stop")` to work
> 
> Introducing a new mechanism isn't worth it.

Fair enough.

> > 3. Same as above but in a separate setting like `vscode-neovim.onExtensionLoad`
> 
> This is acceptable but still doesn't seem worth providing a separate setting for.

I do think this is worth it though, it allows for more configuration apart from my exact issue, but I'm not gonna assume the efforts needed to do that, since the fact that this even works is like magic to me.

> > 4. Vim event in the API that only runs on restarts to allow for something like
> 
> Introducing a new mechanism isn't worth it.

Fair enough.

> Overall, this is a rare use case.

I don't think it is that much of an edge-case to want functionality to be disabled by default.

> Disable Extension (Workspace)

Sadly it is not possible to enable/disable extensions with keybindings in vscode as of right now. Yes, I looked into it. I did however find a way to toggle settings in the settings.json file with keybindings, which would still require my `1.` suggested solution in some capacity.

**Comment by xiyaowong** [comment]
> I tried including that in multiple places, but, although it works, this keeps loading non-stop. Even after a `neovim.restart` action to start it up. ![image](https://private-user-images.githubusercontent.com/66137568/348509543-f9a65883-0ba1-4572-889a-ce4addfc25be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5MjEzMjAsIm5iZiI6MTcyMDkyMTAyMCwicGF0aCI6Ii82NjEzNzU2OC8zNDg1MDk1NDMtZjlhNjU4ODMtMGJhMS00NTcyLTg4OWEtY2U0YWRkZmMyNWJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDAxMzcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NTIwZGRjNTU0MDE2M2FiZTJhZDVhN2ViNGRhNmY3NGYzOWQwODY2NDQwYmMwZDhkZmM3NjFlZGM5YjgxMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rt6MwK-Qej3AqKAPIQoa9TKB89a3S5eL1EsH1TI6Vww)

This should be another bug

**Comment by xiyaowong** [comment]
> So what this means is that the `vscode` package and its variables persist neovim embedded instances but not between vscode launches? That could be documented somewhere imo, but I will try that, thanks!

VSCode is a global object in the extension host. This method is a hack and won't be documented.

**Comment by xiyaowong** [comment]
> The way the VscodeVim does it is exactly how I described, if you set `vim.disableExtension` to `true`, the extension will load, but will not work in vim mode, you need the `toggleVim` action for that. Their naming is indeed counterintuitive, since disableExtension doesn't actually disable the extension.

I know, but that doesn't mean anything. Take the built-in functions of vscode as an example. Switching all functions will modify the corresponding configuration.

**Comment by kazmath** [comment]
> > I tried including that in multiple places, but, although it works, this keeps loading non-stop. Even after a `neovim.restart` action to start it up. ![image](https://private-user-images.githubusercontent.com/66137568/348509543-f9a65883-0ba1-4572-889a-ce4addfc25be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5MjEzMjAsIm5iZiI6MTcyMDkyMTAyMCwicGF0aCI6Ii82NjEzNzU2OC8zNDg1MDk1NDMtZjlhNjU4ODMtMGJhMS00NTcyLTg4OWEtY2U0YWRkZmMyNWJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDAxMzcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NTIwZGRjNTU0MDE2M2FiZTJhZDVhN2ViNGRhNmY3NGYzOWQwODY2NDQwYmMwZDhkZmM3NjFlZGM5YjgxMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rt6MwK-Qej3AqKAPIQoa9TKB89a3S5eL1EsH1TI6Vww)
> 
> This should be another bug

Alright, I'll open an issue for that.

> > So what this means is that the `vscode` package and its variables persist neovim embedded instances but not between vscode launches? That could be documented somewhere imo, but I will try that, thanks!
> 
> VSCode is a global object in the extension host. This method is a hack and won't be documented.

I don't mean to say you should document this hack, I meant to at least say that somewhere.

**Comment by xiyaowong** [comment]
In my opinion, providing a disable option but enabling it through a command is counterintuitive. For example, VS Code's built-in features like autoSave and minimap all modify the corresponding configuration items.

**Comment by kazmath** [comment]
I do agree that it is counterintuitive as I said before, but just that their naming is bad. Essentially what that does is disabling it by default, so a better option name would be something close to `vim.startOnLaunch` or even `vim.defaultState` that can be either `"vim"` or `"vscode"` (or in the case of this extension `vscode-neovim.startOnLaunch` and `vscode-neovim.defaultState`)

**Comment by goyalyashpal** [comment]
yesterday when i read this issue proposal, i thought whatever and moved on....

but after enabling "toggle neovim" (https://github.com/vscode-neovim/vscode-neovim/pull/1566#issuecomment-1852111050) command, i have started using `neovim` in vscodium ever more.  earlier, i used to keep this extension _moooost always_ to be disabled permanently.

and yeah, truly... now i also too feel that this should be option to start this extension in "Stopped mode" essentially.
