### ISSUE TITLE
feature: Will there be tree-sitter support?

### ISSUE THREAD

**Issue by MrOxMasTer** [vscode-neovim/vscode-neovim#2158]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

There is no support for tree-sitter in vscode

### Describe the solution you'd like

Support for tree-sitter in vscode and management of this tree (using plugins)

### Describe alternatives you've considered

I don't know any alternatives

### Additional context

As far as I understand, vs code is planning to add support for tree-sitter in July/August and I would like to see how this extension will be combined with it

https://github.com/microsoft/vscode/issues/220925
https://github.com/microsoft/vscode/issues/210475

**Comment by xiyaowong** [comment]
1. nvim-treesitter can work normally, you can use plugins such as nvim-treesitter and nvim-treesitter-textobjects
2. The work of vscode's treesitter has nothing to do with us

**Comment by MrOxMasTer** [comment]
> 1. nvim-treesitter can work normally, you can use plugins such as nvim-treesitter and nvim-treesitter-textobjects

I understand that you can use a conditional nvim-treesitter and it will work fine. The question is different. If they add a tree-sitter to vs-code itself, wouldn't it be strange that 2 parsings would be performed. 1 on the vs code side, and the other on the neovim side

**Comment by xiyaowong** [comment]
They are completely unrelated. vscode-neovim works by maintaining an instance of nvim and synchronizing various states between nvim and vscode in both directions. So, the situation you are worried about is actually how vscode-neovim operates. :joy:

Additionally, it will take a long time for vscode to support treesitter. Even when it does, it will still require a significant amount of time to provide an API similar to nvim-treesitter, and it might never offer one at all.

**Comment by MrOxMasTer** [comment]
> They are completely unrelated. 

I know that vscode-novim synchronizes various states and I understand that in vscode-neovim it opens a separate instance of neovim.

And that's the question. If they add a tree-sitter to vs code, will the tree-sitter from vs code synchronize with the tree-sitter from neovim. 

Well, as I understand it, it will be difficult, because as you said, they have different APIs (nvim-tree-sitter)

**Comment by xiyaowong** [comment]
99% unlikely, and the remaining 1% is because it doesn't exist yet. Assuming VSCode provides an API related to Tree-sitter for plugins, it would at most implement functionality similar to the nvim-treesitter-objects plugin for Neovim, but it cannot achieve "synchronization."
