### ISSUE TITLE
bug: cursor jumps when inserting a newline in a braced-block

### ISSUE THREAD

**Issue by tomjakubowski** [vscode-neovim/vscode-neovim#2164]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

NVIM v0.9.4

### Operating system/version

macOS 13.3.1 (a)

### Describe the bug

When I insert a newline between braces, the cursor is jumping to outside the braces. I'd expect it to remain in place somewhere between the braces (depending on the auto-indent settings I might have).

To my recollection, this only started happening after the most recent VSCode update. The video shows it happening with "Neovim Clean" set to `true`.

https://github.com/user-attachments/assets/60574640-049d-4ca0-a5d0-691d62c76b62

### Steps To Reproduce

1. Create a .rs file and type in a block, like `mod foo {}`
2. In normal mode, move the cursor to between the `{}`
3. hit "i" to enter insert mode
4. Hit <ret> to insert a newline

### Expected Behavior

I'd expect the cursor to remain between the `{}`. Instead, it is jumping to outside the closing brace.

**Comment by tomjakubowski** [comment]
Wouldn't you know it, restarting vscode resolved this issue for me. I am curious though, if it happens again, what good next debugging steps might be.

**Comment by sidneyfrancois** [comment]
It started to happen to me, the same issue, when I paste something it's the same problem.
