### ISSUE TITLE
bug: Cannot scroll wit HJKL on MacOS 14.1

### ISSUE THREAD

**Issue by mpm896** [vscode-neovim/vscode-neovim#2170]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.10.0

### Operating system/version

MacOS 14.1

### Describe the bug

Despite the docs clearly specifying `On a Mac, the h, j, k and l movement keys may not repeat when held, to fix this open Terminal and execute the following command: defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false`, press and hold is still enabled.

I followed [this issue](https://github.com/VSCodeVim/Vim/issues/345) and [this issue](https://github.com/VSCodeVim/Vim/issues/422) from VSCode Vim, which also suggested setting the global `defaults write -g ApplePressAndHoldEnabled -bool false`. Disabling this allows me to scroll in Neovim opened from the terminal, but not vscode-neovim.

Any suggestions on how else to disable this feature so I can scroll? Thanks!

### Steps To Reproduce

1. Open file through VSCode (in vscode-neovim) - extension version 1.7.1
2. type a bunch of text
3. Try scrolling by holding h, j, k, or l

### Expected Behavior

Expecting the cursor to scroll. Instead, it does not scroll and instead displays alternate characters.

**Comment by mpm896** [comment]
Despite having closed and reopening everything after every change, this now works after submitting this issue. I'm not even sure what to say- but I'm closing this as it now works.

**Comment by ncronquist** [comment]
Adding a comment here just in case anyone else runs into a similar issue and finds this issue again. 

The value you update depends on which version or fork of the VS Code editor you're using; Here are the instructions and other editor values I found in the Vim plugin:

Mac

To enable key-repeating, execute the following in your Terminal, log out and back in, and then restart your editor:

```
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false              # For VS Code
defaults write com.microsoft.VSCodeInsiders ApplePressAndHoldEnabled -bool false      # For VS Code Insider
defaults write com.vscodium ApplePressAndHoldEnabled -bool false                      # For VS Codium
defaults write com.microsoft.VSCodeExploration ApplePressAndHoldEnabled -bool false   # For VS Codium Exploration users
defaults write com.todesktop.230313mzl4w4u92 ApplePressAndHoldEnabled -bool false     # For Cursor
defaults delete -g ApplePressAndHoldEnabled                                           # If necessary, reset global default
```

A note about Cursor and the `com.todesktop.230313mzl4w4u92` reference. I don't know if that value will be the same for everyone, but the way to find it is:

```
osascript -e 'id of app "Cursor"'
```
