### ISSUE TITLE
bug: jumplist incorrectly includes window commands

### ISSUE THREAD

**Issue by aavogt** [vscode-neovim/vscode-neovim#2173]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

NVIM v0.11.0-dev

### Operating system/version

Ubuntu 22.04.4 LTS

### Describe the bug

:help jumplist says each window has it's own jumplist. The vscode-neovim jumplist includes cursor motion between different windows into the same buffer.

### Steps To Reproduce

1. C-w s
2. C-w C-w
3. C-] on an identifier
4. C-w C-w
5. C-o

### Expected Behavior

The C-o undoes C-w C-w. In neovim proper it undoes the cursor movement to get to the identifier and leaves the other window alone.

**Comment by theol0403** [comment]
Yes, VSCode jumplist is used for best compatibility instead of the nvim jumplist (for navigation between vscode commands), which unfortunately is global. 

https://github.com/vscode-neovim/vscode-neovim/blob/master/runtime/vscode/overrides/vscode-jumplist.vim
