### ISSUE TITLE
bug:  Keybindings not working in vscode-neovim on Windows 11

### ISSUE THREAD

**Issue by tieniu1** [vscode-neovim/vscode-neovim#2181]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

v0.9.1

### Operating system/version

windows 11 23H2

### Describe the bug

I'm using vscode-neovim on Windows 11, and I'm having trouble with my keybindings. I want VSCode to handle ctrl+f, ctrl+b, and ctrl+j in Normal mode, and ctrl+a in Insert mode. I configured it as follows, but it's not working. Could someone help me figure out what might be wrong?

Here is my configuration:

```
"vscode-neovim.highlightGroups.highlights": {
  "Directory": "vim",
  "IncSearch": {
    "backgroundColor": "theme.editor.findMatchBackground",
    "borderColor": "theme.editor.findMatchBorder"
  },
  "Search": {
    "backgroundColor": "theme.editor.findMatchHighlightBackground",
    "borderColor": "theme.editor.findMatchHighlightBorder"
  },
  "Visual": {
    "backgroundColor": "theme.editor.selectionBackground"
  },
  "Conceal": "vim",
  "Substitute": "vim"
},
"vscode-neovim.neovimExecutablePaths.darwin": "/usr/local/bin/nvim",
"vscode-neovim.neovimInitVimPathos.darwin": "Users/renee2022/.config/nvim/init.vim",
"vscode-neovim.ctrlKeysForNormalMode": [],
"vscode-neovim.ctrlKeysForInsertMode": [
  "c",
  "d",
  "h",
  "j",
  "m",
  "o",
  "r",
  "t",
  "u",
  "w"
],
"vscode-neovim.neovimClean": true,
```

### Steps To Reproduce

1. open  vscode
2. `ctrl + f`

### Expected Behavior

"Open the search box in VSCode"

**Comment by theol0403** [comment]
```
"vscode-neovim.ctrlKeysForInsertMode": [
  "c",
  "d",
  "h",
  "j",
  "m",
  "o",
  "r",
  "t",
  "u",
  "w"
],
```

I don't see `a` here...

**Comment by tieniu1** [comment]
> ```
> "vscode-neovim.ctrlKeysForInsertMode": [
>   "c",
>   "d",
>   "h",
>   "j",
>   "m",
>   "o",
>   "r",
>   "t",
>   "u",
>   "w"
> ],
> ```
> 
> 我在这里没有看到 `a` ...

Because I want ctrl+a to be handled by VSCode, I removed a from ctrlKeysForInsertMode. However, I also tried adding a to ctrlKeysForInsertMode, but neither configuration allows ctrl+a to be handled by VSCode. 😢

**Comment by theol0403** [comment]
My bad, I misunderstood. Yeah, that should be fine... check the keybindings UI to see other conflicting bindings.

**Comment by tieniu1** [comment]
> 我的错，我误会了。是的，那应该没问题...检查键绑定 UI 以查看其他冲突的绑定。

I added the following code to **keybindings.json** , and it solved my problem. Thank you!

``` 
  {
    "key": "ctrl+a",
    "command": "-vscode-neovim.send",
    "when": "editorTextFocus && neovim.ctrlKeysInsert.a && neovim.init && neovim.mode == 'insert' && editorLangId not in 'neovim.editorLangIdExclusions'"
  },
  {
    "key": "ctrl+f",
    "command": "-vscode-neovim.ctrl-f",
    "when": "editorTextFocus && neovim.ctrlKeysNormal.f && neovim.init && neovim.mode != 'insert' && editorLangId not in 'neovim.editorLangIdExclusions'"
  },
  {
    "key": "ctrl+j",
    "command": "-vscode-neovim.send",
    "when": "editorTextFocus && neovim.ctrlKeysNormal.j && neovim.init && neovim.mode != 'insert' && editorLangId not in 'neovim.editorLangIdExclusions'"
  },
  {
    "key": "ctrl+b",
    "command": "-vscode-neovim.ctrl-b",
    "when": "editorTextFocus && neovim.ctrlKeysNormal.b && neovim.init && neovim.mode != 'insert' && editorLangId not in 'neovim.editorLangIdExclusions'"
  },

```

**Comment by tieniu1** [comment]
> @tieniu1 使用按键绑定 (UI) 检查是否有任何其他绑定。


Thank you for your suggestion, it solved my problem.

**Comment by xiyaowong** [comment]
These keybindings should be controlled by the `ctrlKeysInNormal` configuration. Therefore, the issue has not been resolved.

**Comment by xiyaowong** [comment]
After testing, ctrlKeysForNormalMode is effective.

**Comment by tieniu1** [comment]
> ctrlKeysForInsertMode

On macOS 12.6, vscode-neovim.ctrlKeysForNormalMode works for me, but the same configuration doesn't work on my Windows 11 setup. I plan to try it again tonight with a clean VSCode configuration on Windows 11.
