### ISSUE TITLE
bug: It seems that using this extension causes some display errors in the .sh files.

### ISSUE THREAD

**Issue by BetterHurryUp** [vscode-neovim/vscode-neovim#2185]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [x] I have searched existing issues.

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

windows 11 23H2 with WSL 2.2.0.4

### Describe the bug

When extension is activated, there are some strange things in .sh files.
I have a simple .sh file
```sh
pyinstaller -F ../saveyourbug.py    \
--add-data "../config.yml;."        \
--distpath "../build/"              \
--specpath "../temp/"               \
--workpath "../temp/"               \
--optimize 2                        \
--icon="../resource/logo.icns"      \
--log-level="ERROR"                 \
--clean                             \
```
but if I open it with vscode neovim extension, it will be like this
![image](https://github.com/user-attachments/assets/b7203389-7386-44c8-a317-dc0a2cfd6c1c)
But if I try to copy those things and paste, it will come back to the origin content

### Steps To Reproduce

1. enable VSCode Neovim extension
2. reload window
3. open a .sh file in windows

### Expected Behavior

plain text

**Comment by BetterHurryUp** [comment]
poor english sry😭

**Comment by xiyaowong** [comment]
Confirmed

**Comment by xiyaowong** [comment]
Debugged for 2 hours.  Nvim combined the dashes at the beginning of these lines with the status column, causing them to be mistakenly removed
