### ISSUE TITLE
bug: "Search and replace" command preview does not match actual change it will make

### ISSUE THREAD

**Issue by urdenster** [vscode-neovim/vscode-neovim#2188]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Microsoft Windows 11 Pro/10.0.22631 Build 22631

### Describe the bug

When you start typing the replace part of search and replace command preview does not match actual change it will make, it seems for all changed lines it does not adjust part that goes after replaced segment.
![image](https://github.com/user-attachments/assets/ce785011-eaaa-41cc-97e8-ac9e5245e76f) - Text before change
![image](https://github.com/user-attachments/assets/edde80bb-037f-4bfd-b807-23de1c958fa5) - Preview
![image](https://github.com/user-attachments/assets/462d597e-b366-409a-b96a-341ed8d2444a) - Actual change

### Steps To Reproduce

1. Open any text file.
2. Type :%s/{any text that would match}/{text you want to replace it with} 
3. While enter is still not pressed preview shows changed lines incorrectly
4. After you press enter it actually changes text like neovim would change it

### Expected Behavior

Expecting preview to show actual result of the change.

**Comment by xiyaowong** [comment]
We have ignored all default highlights, so the text on the right is hidden. You can `set icm=split` to preview.

**Comment by xiyaowong** [comment]
Yes, this is a flaw.
