### ISSUE TITLE
VSCode Neovim causes VSCode to freeze

### ISSUE THREAD

**Issue by plasmadice** [vscode-neovim/vscode-neovim#2192]
Type: <b>Bug</b>

Certain operations cause VSCode to freeze. Especially reloading windows or closing the entire application.

Further testing led me to find that this only happens when the vim-plug autoload function runs before a window opens.

Either removing or commenting this out from my nvim config fixes the issue for me.
```
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif
```

Extension version: 1.18.6
VS Code version: Code 1.91.1 (Universal) (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:07:54.982Z)
OS version: Darwin arm64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|12, 9, 7|
|Memory (System)|32.00GB (1.53GB free)|
|Process Argv|--crash-reporter-id 2644ea1a-772b-4beb-9af6-08cf46f7de10|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
refactort:31108082
ccplc:31103425
pythonrstrctxt:31103193
1iic9185:31097392
wkspc-onlycs-t:31106322

```

</details>

**Comment by theol0403** [comment]
It's likely to do with Plug opening a new buffer to display the plugin install process -- and currently, vscode-neovim doesn't support neovim-spawned external buffers. Use lazy.nvim, or don't autoinstall plugins inside vscode.

**Comment by plasmadice** [comment]
> It's likely to do with Plug opening a new buffer to display the plugin install process -- and currently, vscode-neovim doesn't support neovim-spawned external buffers. Use lazy.nvim, or don't autoinstall plugins inside vscode.

Disabling autoinstall fixed most of the issues. Crashes still happening, but it now happens much less often.

I will give lazy.nvim another try soon!
