### ISSUE TITLE
bug: Ghost highlighted text appears when scrolling with relative line numbers enabled

### ISSUE THREAD

**Issue by tma-xtia** [vscode-neovim/vscode-neovim#2194]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

Windows 11 Pro 23H2

### Describe the bug

The issue is demonstrated in the video linked below:

https://github.com/user-attachments/assets/c99f5407-2179-4253-b8f5-7053d4ee825f

Additional details:
- This bug occurs with `vscode-neovim.neovimClean` enabled (although this setting is not shown in the video).
- The issue persists regardless of the affinity setting.
- This behavior is believed to be recent, as it was not observed months ago.

### Steps To Reproduce

1. Set `"editor.lineNumbers": "relative"` in `settings.json`
2. Open a file in the editor
3. Search for text using the `/` key
4. Press Enter to close the search popup
5. Scroll the document using the mouse
6. Observe ghost highlighted text appearing

### Expected Behavior

No ghosts appear when scrolling.

**Comment by erik-megarad** [comment]
I also have this issue. I have to do ctrl+l pretty regularly to force it to redraw.

**Comment by shivamchandra75** [comment]
I also have the same issue, when search for something either use *,/ then scroll and the highlighted/searched text tries to stay on the same position when scrolling which make
<img width="1440" alt="Screenshot 2024-08-09 at 9 58 58 PM" src="https://github.com/user-attachments/assets/740560ec-74a0-4b5d-b364-1b53e18580f4">
s the text overlap on other text.

**Comment by pumpkinlink** [comment]
still happening with me when I use the undo feature
