### ISSUE TITLE
bug: BufAdd error when opening python file on startup (with ghost_text_view.lua plugin)

### ISSUE THREAD

**Issue by lvyuemeng** [vscode-neovim/vscode-neovim#2207]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

NVIM v0.10.1 Build type: Release LuaJIT 2.1.1713484068

### Operating system/version

windows 11

### Describe the bug

When in the editor window:

```
> [info] MessagesManager: Error detected while processing BufAdd Autocommands for "*"..BufReadPost Autocommands for "*":
    Error executing lua callback: C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:35:
    Error executing lua: C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:36:
    BufAdd Autocommands for "*"..BufReadPost Autocommands for "*"..FileType Autocommands for "*"..function <SNR>21_LoadFTPlugin[20]..script C:\Program Files\Neovim\share\nvim\runtime\ftplugin\python.vim, line 41:
    Vim(if):provider: python3: missing required variable g:loaded_python3_provider
> stack traceback:
> 	[C]: in function 'nvim_cmd'
> 	C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:36: in function <C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:35>
> 	[C]: in function 'nvim_buf_call'
> 	C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:35: in function <C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:10>
> 	[C]: in function 'nvim_buf_set_option'
> 	...kov.vscode-neovim-1.18.7\runtime/lua/vscode/internal.lua:354: in function <...kov.vscode-neovim-1.18.7\runtime/lua/vscode/internal.lua:327>
> stack traceback:
> 	[C]: in function 'nvim_buf_call'
> 	C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:35: in function <C:\Program Files\Neovim\share\nvim\runtime\filetype.lua:10>
> 	[C]: in function 'nvim_buf_set_option'
> 	...kov.vscode-neovim-1.18.7\runtime/lua/vscode/internal.lua:354: in function <...kov.vscode-neovim-1.18.7\runtime/lua/vscode/internal.lua:327
```

### Steps To Reproduce

1.Add extension
2.Open VScode and in the editor window
3.Log Error

### Expected Behavior

No output of log error.

**Comment by justinmk** [comment]
are you opening a python (.py) file? Based on the stacktrace, it looks like this code: https://github.com/vscode-neovim/vscode-neovim/blob/400d5d51cc7bfac65b7cdc0178d92d772f29b106/runtime/lua/vscode/internal.lua#L327 
is triggering `ftplugin\python.vim`.

And this apparently happens before Nvim has invoked `runtime/autoload/provider/python3.vim` which is what defines the `g:loaded_python3_provider` variable.

Can you double-check that this happens with `vscode-neovim.neovimClean` ?

**Comment by lvyuemeng** [comment]
> Are you opening a python (.py) file? Does it happen _only_ on startup, or also when you open another (python) file?
> 
> Based on the stacktrace, it looks like this code:
> 
> https://github.com/vscode-neovim/vscode-neovim/blob/400d5d51cc7bfac65b7cdc0178d92d772f29b106/runtime/lua/vscode/internal.lua#L327
> 
> 
> is triggering `ftplugin\python.vim`.
> And this apparently happens before Nvim has invoked `runtime/autoload/provider/python3.vim` which is what defines the `g:loaded_python3_provider` variable.
> 
> Can you double-check that this happens with `vscode-neovim.neovimClean` ?

This only happen when I open python file. I ensure this still happen when I use the extension as `--clean`, and won't happen in neovim itself (sorry if I don't notice something, I'm not good at nvim. I already reinstall like `TSInstall vimdoc` or `TSUpdate`).

But there's other problem like 
![屏幕截图 2024-08-20 220933](https://github.com/user-attachments/assets/9952ecce-60ab-4bcf-bced-85ffdece0a8d)
and sometimes neovim will crash and terminal continously prompts the error log and I have to restart.
I can't ensure these other problems are related to this. If I'm wrong and misidentify, I'm sorry.

**Comment by justinmk** [comment]
> continously prompts the error log

can you paste the errors here, if they are different than the original report

**Comment by lvyuemeng** [comment]
> > continously prompts the error log
> 
> can you paste the errors here, if they are different than the original report

Error in decoration provider cmp:GHOST_TEXT.win:
Error executing lua: ...nvim-data/lazy/nvim-cmp/lua/cmp/view/ghost_text_view.lua:35: Invalid buffer id: 46
stack traceback:
	[C]: in function 'nvim_buf_del_extmark'
	...nvim-data/lazy/nvim-cmp/lua/cmp/view/ghost_text_view.lua:35: in function <...nvim-data/lazy/nvim-cmp/lua/cmp/view/ghost_text_view.lua:33>

**Comment by justinmk** [comment]
This error comes from the `ghost_text_view.lua` plugin.

**Comment by lvyuemeng** [comment]
> This error comes from the `nvim-cmp .. ghost_text_view.lua` plugin.

I'm sorry for my dumb question, you are patient!
