### ISSUE TITLE
bug: where do I need to set the init.lua or the init.vim file in a windows environment?

### ISSUE THREAD

**Issue by mike-rambil** [vscode-neovim/vscode-neovim#2208]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

v1.18.7

### Operating system/version

Windows 11

### Describe the bug

Not sure where the location of the init.lua file needs to be for the extension to find it in windows.

### Steps To Reproduce

Need a location as mentioned above for the init.lua

### Expected Behavior

Need a location as mentioned above for the init.lua so vscode nvim extension can use it

**Comment by justinmk** [comment]
> Not sure where the location of the init.lua file needs to be for the extension to find it in windows.

Nvim finds the init.lua, not vscode-neovim. `:help init.lua`
