### ISSUE TITLE
bug: "E5108: Error executing lua [string ":lua"]:1: module 'cfg' not found"

### ISSUE THREAD

**Issue by Zxiiiprt** [vscode-neovim/vscode-neovim#2212]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.10.1

### Operating system/version

MacOS 14.6

### Describe the bug

```shell
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1724512491
```

Following error encountered when launching neovim 0.10.1 (fresh install via brew) on MacOS Sonoma 14.6

```shell
Error detected while processing ~/.config/nvim/init.vim:
line  386:
E5108: Error executing lua [string ":lua"]:1: module 'cfg' not found:
        no field package.preload['cfg']
        no file './cfg.lua'
        no file '/opt/homebrew/share/luajit-2.1/cfg.lua'
        no file '/usr/local/share/lua/5.1/cfg.lua'
        no file '/usr/local/share/lua/5.1/cfg/init.lua'
        no file '/opt/homebrew/share/lua/5.1/cfg.lua'
        no file '/opt/homebrew/share/lua/5.1/cfg/init.lua'
        no file './cfg.so'
        no file '/usr/local/lib/lua/5.1/cfg.so'
        no file '/opt/homebrew/lib/lua/5.1/cfg.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
```

Here's what the end of my `init.vim` file looks like (line 386):
```vim
lua require('cfg')
```

My directory structure under `~/.config/nvim` is as follows:
```shell
init.vim
cfg/
-- cfg.lua
```

My `cfg.lua` contains half of my configurations for certain plugins, `init.vim` has other configurations (at the end of which I call my lua config file).

### Steps To Reproduce

1. Have configurations in your `init.vim` file
2. Create another `cfg.lua` file that has further configurations in lua
3. Call the `cfg.lua` file from your `init.vim` by placing `lua require('cfg')` at the end of the `init.vim` file
4. Ensure you're on MacOS Sonoma and using `brew` to install latest neovim 0.10.1

### Expected Behavior

This works on other MacOS/Linux systems (running versions < neovim 0.10.1) and successfully loads the `cfg.lua` file properly with no errors

**Comment by xiyaowong** [comment]
You should place lua modules in `~/.config/nvim/lua/`

Read https://neovim.io/doc/user/lua.html#lua-module-load
