### ISSUE TITLE
bug: multi byte emoji's render improperly, unless in visual modes

### ISSUE THREAD

**Issue by snacksncode** [vscode-neovim/vscode-neovim#2214]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

MacOS 14.4.1 (23E224)

### Describe the bug

When emojis (multi-byte ones) are present in the text, visual artifacts are visible (<200d>). They go away if text is selected. Stopping the extension fixes the issue too.

https://github.com/user-attachments/assets/f3fdc596-3ad3-4b15-a135-5a87c1f496dc

### Steps To Reproduce

Reproduction input used in the video:
```html
<span>
  👀 = {size('👀')}, length: {'👀'.length}
</span>
<span>
  👨‍👩‍👧‍👦👀 = {size('👨‍👩‍👧‍👦👀')}, length: {'👨‍👩‍👧‍👦👀'.length}
</span>
<span>
  🇺🇸👨‍👩‍👧‍👦👀 = {size('🇺🇸👨‍👩‍👧‍👦👀')}, length: {'🇺🇸👨‍👩‍👧‍👦👀'.length}
</span>
<span>
  🕺🏻👯‍♀️💃🏻 = {size('🕺🏻👯‍♀️💃🏻')}, length: {'🕺🏻👯‍♀️💃🏻'.length}
</span>
```

### Expected Behavior

Emojis are rendered properly (like when being selected), no <200d> artifacts are visible

**Comment by xiyaowong** [comment]
These emojis cannot be displayed correctly in nvim.
![image](https://github.com/user-attachments/assets/4d2a6bd9-6692-4cf8-a205-6d0442216eae)

If you need to frequently handle emojis, you can temporarily disable vscode-neovim.
