### ISSUE TITLE
How do I get the logs after a disconnect?

### ISSUE THREAD

**Issue by mdonato-fn** [vscode-neovim/vscode-neovim#2216]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

I am experiencing random disconnects when working on dev containers and jupyter notebooks. My issue is that when that happens, the output logs disappear. Is there a way to recover them?

For reference, I look at the logs like this:
> View the logs via Output: Focus on Output View and select vscode-neovim
But (obviously) the vscode-neovim section does not exist anymore post disconnect

### Describe the solution you'd like

A link to a log file in the disconnect pop up

### Describe alternatives you've considered

None

**Comment by justinmk** [comment]
You can see where the files are stored by clicking "..." in the output window:

![image](https://github.com/user-attachments/assets/e96fcf0a-1f78-4e07-96c0-9ccecffadf26)

That should give you an idea of where logs are stored. 


> A link to a log file in the disconnect pop up

vscode extensions have no control or visibility into the "disconnect" event, AFAIK.
