### ISSUE TITLE
bug: unicode characters (zero-width joiners U+200B, U+200D) behave weirdly

### ISSUE THREAD

**Issue by sadan4** [vscode-neovim/vscode-neovim#2220]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

NVIM v0.10.1 Build type: Release LuaJIT 2.1.1713773202

### Operating system/version

NixOS

### Describe the bug

Characters such as zero-width spaces, and zero-width joiners(U+200B, U+200D) render weirdly and are weird to interact with.
I'm not sure what other characters this occurs with.
It seems neovim and vs-code both have their ways of rendering them, and they collide
the text `this is a zwsp >>​<<` in a plain text file in vs code.
![image](https://github.com/user-attachments/assets/96c2692a-2f30-4f5d-9c73-961b7d0d7430)

### Steps To Reproduce

1. paste `this is a zwsp >>​<<` into a text file in vs code
2. observe weird rendering

### Expected Behavior

Either use neovim's way of rendering these characters or vs code's, but not both

**Comment by xiyaowong** [comment]
Similar to #2214. In Neovim, `<200b>` is displayed, and there's no way to know how Nvim will render this character.

![image](https://github.com/user-attachments/assets/fb7836cc-6079-43e1-b207-442e393ee515)

**Comment by justinmk** [comment]
> In Neovim, `<200b>` is displayed, and there's no way to know how Nvim will render this character.

What do you mean? There are functions like `:help strdisplaywidth()` and related.

**Comment by xiyaowong** [comment]
The current logic works fine, rendering the highlights in nvim, but ignoring the default highlights. The `strdisplaywidth` related functions can't distinguish between what is expected to be displayed and what needs to be ignored.
