### ISSUE TITLE
bug: After the latest update (v1.18.10), getting error starting nvim 0.10.0-dev (prerelease)

### ISSUE THREAD

**Issue by fargly** [vscode-neovim/vscode-neovim#2227]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1713484068

### Operating system/version

VSCode Front End -> Windows 10, Remote Server-> Ubuntu 22.04

### Describe the bug

After the latest update (v1.18.10) the extension stopped working, after vscode reboot, getting:

 > '[Failed to start nvim] Unable to find a suitable neovim executable. Please check your neovim installation.'

I've been happily enjoying this extension until it stopped working this morning. I verified that the extension settings still pointed at my installed instance of nvim.

It would be nice to have provisions to regress the extension version so I could keep working.

### Steps To Reproduce

1. Reboot VScode error pops
2. Verified newest version of nvim, copied to "known" locations in case settings are working correctly
3.  Even with nvim installed into both /usr/bin and /usr/local/bin, the extension is still erroring out
4. Uninstalled/Reinstalled Extension

### Expected Behavior

vscode-neovim is an awesome extension, I expected it to keep working as it has for the last 6 months. nvim works fine in the vscode terminal.

**Comment by justinmk** [comment]
Sounds similar to https://github.com/vscode-neovim/vscode-neovim/issues/2225


> It would be nice to have provisions to regress the extension version so I could keep working.

vscode allows you to revert to a previous version:

https://code.visualstudio.com/updates/v1_30#_install-previous-versions

**Comment by emiljt** [comment]
I can confirm that version 1.18.10 causes a failure to start nvim error after reload. Installing the previous version (1.18.9) solves the issue after a reload.

This is on VS Code 1.92.2

**Comment by fargly** [comment]
Just after submitting the issue, I was able to track down the process for installing a specific extension version so I'm back in business. I made the effort after 5 minutes of using the Vim extension which works but its performance pales in comparison to vscode-neovim.  :)

**Comment by justinmk** [comment]
See https://github.com/vscode-neovim/vscode-neovim/issues/2225#issuecomment-2334832907 .

In `nvim`, check the output of `:version` or `:lua =tostring(vim.version())`. If you are using a *prerelease* build (e.g. `0.10.0-dev`), then you do not have the 0.10.0 release.

**Comment by fargly** [comment]
@justinmk You must be psychic or just encountered this exact problem.  I ran the lua directive and, yes, I'm on 0.10.0-dev which doesn't show in what I would consider the "normal" way of getting the version. I have updated to 0.10.1 so I'll update the extension tomorrow and verify. Thanks for the comment.

**Comment by fargly** [comment]
After upgrading nvim to 0.10.1, I updated the extension to 1.18.10. I am getting the same error as I originally posted. I completely restarted VSCode and I am seeing the same issue. I have regressed back to 1.18.9 as a work around.

Just to clarify, I'm running VSCode on a Windows 10 host and am accessing a remote vscode server on an Ubuntu 22.04 host. nvim is installed on the Linux host which I am assuming that is what's being accessed by the neovim extension.

**Comment by xiyaowong** [comment]
@fargly  Where is the extension running? On a local or remote environment? https://github.com/vscode-neovim/vscode-neovim#remote-development

**Comment by SaintWacko** [comment]
Upgrading my neovim version worked for me, however there is a slight issue with the required version. Once I did a `brew reinstall neovim` I had version 0.10.0, but vscode-neovim was still giving me an error that it required version 0.10.0 or higher. Once I got it to update to version 0.10.1 that error went away.

**Comment by justinmk** [comment]
> Once I did a `brew reinstall neovim` I had version 0.10.0

Because `brew reinstall` only reinstalls, it doesn't upgrade. https://stackoverflow.com/a/7898617/152142

**Comment by SaintWacko** [comment]
> Because `brew reinstall` only reinstalls, it doesn't upgrade. https://stackoverflow.com/a/7898617/152142

Well, that certainly explains a lot. I guess the first google result for "how to update neovim mac" was wrong lol

Doesn't that mean, though, that I originally had 0.10.10 installed? Odd that the error message changed after the reinstall
