### ISSUE TITLE
bug: Lots of Neovim was disconnected pop-ups

### ISSUE THREAD

**Issue by schmidtw** [vscode-neovim/vscode-neovim#2228]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

v0.10.1

### Operating system/version

Fedora 40

### Describe the bug

`Neovim was disconnected` happens about every 30-60s when I am using the plugin now.  I just noticed it happening today.  I tried going back to older versions than `v1.18.10`, but it doesn't seem to help too much.

### Steps To Reproduce

1. Open a file and use VSCode Neovim for a while, just navigating around the file will cause the problem.
2. Observe the popup saying `Neovim was disconnected`.
3. Reconnect & go back to step one.  I can get about 30s of work done before something goes badly & I have to restart Neovim.

### Expected Behavior

There should be no reeconnection issue.

**Comment by justinmk** [comment]
View the logs via `Output: Focus on Output View` and select vscode-neovim.

**Comment by schmidtw** [comment]
I don't see anything printed out in that view.

**Comment by schmidtw** [comment]
There are 5 different `vscode-neovim messages` that are:
- `/\<fetch\>      [11/13]`
- empty
- empty
- `Already at oldest change`
- empty

**Comment by schmidtw** [comment]
Is there some way to enable more debugging or look somewhere else?

**Comment by justinmk** [comment]
click the gear icon, choose "Debug", then click it again and choose "Set as default"
<img width="330" alt="image" src="https://github.com/user-attachments/assets/fc573882-0825-4817-a52a-d6f96dbf1842">

**Comment by xiyaowong** [comment]
Duplicate of #2165
