### ISSUE TITLE
bug: Failed to start nvim

### ISSUE THREAD

**Issue by sumanth-lingappa** [vscode-neovim/vscode-neovim#2231]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

Ubuntu22

### Describe the bug

My VSCode Installation is on Windows. I am trying to REMOTE-SSH to ubuntu VM. 
NVIM is installed in the ubuntu VM

However I am getting the below error when the vscode connects to REMOTE-SSH

```
[Failed to start nvim] Unable to find a suitable neovim executable. Please check your neovim installation.
```

However, the same (remote-ssh to the same ubuntu vm) works when I connect via VSCode installed on my MacOS

### Steps To Reproduce

1. install vscode in windows
2. install vscode-neovim extension
3. install the latest nvim in ubuntu vm
4. try to remote-ssh to a ubuntu vm

### Expected Behavior

vscode-neovim should work on ubuntu vm from windows

**Comment by justinmk** [comment]
>  I have searched existing issues.

There are two open issues

**Comment by xiyaowong** [comment]
https://github.com/vscode-neovim/vscode-neovim#remote-development

**Comment by sumanth-lingappa** [comment]
Please help. I didnt understand the solution. 
Below is my settings.json in vscode installed on windows (I am trying to REMOTE-SSH to linux from windows)

```json
{
    "vscode-neovim.neovimInitVimPaths.darwin": "/Users/sumanth/.config/nvim/init.lua",
    "vscode-neovim.neovimExecutablePaths.linux": "/usr/local/bin/nvim",
    "vscode-neovim.neovimClean": true,
    {
        "remote.extensionKind": {
            "asvetliakov.vscode-neovim": ["workspace"]
        }
    }
}
```

below is the command run from my ubuntu VM

```bash
❯ which nvim
/usr/local/bin/nvim
```

**Comment by qlibp** [comment]
> Please help. I didnt understand the solution. Below is my settings.json in vscode installed on windows (I am trying to REMOTE-SSH to linux from windows)
> 
> ```json
> {
>     "vscode-neovim.neovimInitVimPaths.darwin": "/Users/sumanth/.config/nvim/init.lua",
>     "vscode-neovim.neovimExecutablePaths.linux": "/usr/local/bin/nvim",
>     "vscode-neovim.neovimClean": true,
>     {
>         "remote.extensionKind": {
>             "asvetliakov.vscode-neovim": ["workspace"]
>         }
>     }
> }
> ```
> 
> below is the command run from my ubuntu VM
> 
> ```shell
> ❯ which nvim
> /usr/local/bin/nvim
> ```

set the vscode configuration first, and then reinstall the extension, then the extension will be installed into remote server. After that, all works fine.
