### ISSUE TITLE
bug: Composite Escape Keys no longer work since v1.18.10 (multiple vscode profiles)

### ISSUE THREAD

**Issue by MrDwarf7** [vscode-neovim/vscode-neovim#2232]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

Windows 11 & ArchWSL (Containered)

### Describe the bug

Using the extension for a while I'm aware that we've had to change the way these are handled before.
So it broke - I checked the docs "Okay, cool there's been a change", update the binds and double check any thing I'm handing out of Neovim itself back to vscode etc.
That's all good - After some fiddling around I can no longer get any variation of composite keys functioning at all.

### Steps To Reproduce

1. Install VSCode Neovim
2. Set composite keys as per docs & readme
3. Go into insert mode
4. Attempt to use any variation from the json table to exit insert mode ("jj", "jk", "kj")
5. Hit Esc to actually return to normal mode

### Expected Behavior

Hitting a composite key defined in either my VsCode settings.json as per the docs OR registering the same command via a .lua file inside the neovim config should allow the usage of composite keys as per normal.

These worked prior to the interface/implementation change that's now in the current version.

**Comment by justinmk** [comment]
what is the exact, most recent version, that worked?

**Comment by MrDwarf7** [comment]
Would be the version prior to the change-over to how composite keys were being handled - I leave auto-update on for the majority of my extensions.
If you need a version specifically I can try and do a rollback per version and see if I can find one prior to the composite keys overhaul.

**Comment by justinmk** [comment]
> I can try and do a rollback per version and see if I can find one prior to the composite keys overhaul.

would be helpful. and is pretty easy to do from the vscode extensions page.

**Comment by spro** [comment]
1.18.9 is the last version that works for me. Newer ones don't accept my Caps Lock key (remapped) or the regular Esc key

**Comment by xiyaowong** [comment]
This is quite strange; we have test cases.
https://github.com/vscode-neovim/vscode-neovim/blob/master/src/test/integ/composite-escape.test.ts

**Comment by xiyaowong** [comment]
I tested it, and it works fine.

**Comment by MrDwarf7** [comment]
Here is a section of my settings.json from VsCode

```json
    // VIM/NEOVIM RELATED
    "extensions.experimental.affinity": {
        "asvetliakov.vscode-neovim": 1
    },
    "vscode-neovim.compositeTimeout": 200,
    "vscode-neovim.compositeKeys": {
        "jj": {
            "command": "vscode-neovim.lua",
            "args": [
                [
                    "local code = require('vscode')",
                    "code.action('vscode-neovim.escape')",
                    "code.action('workbench.action.files.save')",
                ],
            ],
        },
        //   "kj": {
        //       "command": "vscode-neovim.lua",
        //       "args": [
        //           "local code = require('vscode')",
        //           "code.action('vscode-neovim.escape')",
        //           // "code.action('workbench.action.files.save')"
        //       ]
        //   },
        //   "jk": {
        //       "command": "vscode-neovim.lua",
        //       "args": [
        //           "local code = require('vscode')",
        //           "code.action('vscode-neovim.escape')",
        //           // "code.action('workbench.action.files.save')"
        //       ]
        //   },
    },
    "extensions.ignoreRecommendations": true,
    "vscode-neovim.revealCursorScrollLine": true,
    "vscode-neovim.logLevel": "debug",
    // "vscode-neovim.NVIM_APPNAME": "nvim",
    //"vscode-neovim.wslDistribution": "Arch",
```

Note: None of the above work, nor does `gcc` for commenting (though this could be a config issue on my side unless it's handle by same interface as well).

I've tried fiddling around with multiple things in the settings.json & vscode plugin side of things.
I can also link to a portion of my nvim config that would handle anything on that side as well
[Link here](https://github.com/MrDwarf7/dotfiles/blob/acdfad7b10090be9a08f9e204b6ecfde96eed1b3/.config/nvim/lua/vscode_conf/init.lua#L45C1-L45C6)
for a section of my nvim config that has anything to do with vscode.
I've been changing a couple of things and cannot seem to get it to play nicely.

**Comment by kjiang95** [comment]
Same issue here. It's working on my Mac but not on my Windows machine. Both are set up with the same vscode and neovim configs

**Comment by xiyaowong** [comment]
It's hard to find the issue. Please send a screen recording.

**Comment by justinmk** [comment]
> I'm willing to try just about anything to resolve this issue.

please open a new issue and share your logs and full details

**Comment by MrDwarf7** [comment]
I was ended up cleaning up the extensions and managed to resolve this.
I would speculate due to multiple profiles something may have been out-of-sync/partially updated at some point.

Believe it may be worth checking other profiles if there's such an API available to call for vscode - Happy to close the issue, less someone wants to keep it open for any reason.

**Comment by justinmk** [comment]
Thanks for following up! Doesn't seem like there's anything actionable here, but if you find more hints then we can always revisit.

**Comment by nikko87** [comment]
im experiencing the same problem. Now I cant even type 'jk' in my editor. Any fix for that issue?

**Comment by georg-ch** [comment]
For me, this still works:

`"extensions.experimental.affinity": {
        "asvetliakov.vscode-neovim": 1
    },
    "vscode-neovim.compositeKeys": {
        "kj": {
            "command": "vscode-neovim.escape"
        }
    },
    "vscode-neovim.compositeTimeout": 50,`

Ignore the notification that min timeout is 100, set it however you want.
