### ISSUE TITLE
bug: "neovim 0.10 required" error, with neovim 0.10 prerelease

### ISSUE THREAD

**Issue by rv-nath** [vscode-neovim/vscode-neovim#2238]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

Windows11 > WSL > Ubuntu 24.04 LTS

### Describe the bug

I have the vsscode-neovim plugin installed, and everything was fine.  But of late, whenever I launch vscode, I get this alert message indicating 

> vscode-neovim requires nvim version 0.10.0 or higher. 0.10.0 Install the [latest stable version](https://github.com/neovim/neovim/releases/latest).

![image](https://github.com/user-attachments/assets/8e189b67-59fa-469c-99bb-8cf914d6b0e3)

I could have ignored this warning.  But if I continue using vscode editor, randomly the vscode gets disconnected and another notification comes up saying "neovim disconnected".  After this, I have to close the vscode editor and reopen it to get the plugin working.   I can;'t predict when this disconnect happens.  It is erratic and happens randomly, like twice or thrice in a day.

![image](https://github.com/user-attachments/assets/e3ac011e-2508-441f-93ae-63d68c47645f)

I have also checked a similar issue https://github.com/vscode-neovim/vscode-neovim/issues/1684 that talks about nvim being disconnected and tried that option of changing the extensionKind.  This doesn't solve the issue of "neovim 0.10 required".  I am observing whether it solves the disconnection issue or not, because it takes time to observe this random behavior.

### Steps To Reproduce

This behavior is observed in WSL / Ubuntu and also in native Ubuntu OS.  
1. Upgrade the existing neovim 0.9 to   0.10.1 on WSL/Ubuntu.
2. Have the vscode neovim plugin installed.
3. Launch the vscode editor with any project. Example:  goto a sourcecode root directory and type "code ." from the terminal.
4. vscode launches and initializes itself and shows this notice.

### Expected Behavior

The two alerts should not be appearing.
the exteion should not keep disconnecting.

**Comment by rv-nath** [comment]
neovim disconnection happens, even after chanigng the extensionKind

**Comment by justinmk** [comment]
view the [vscode-neovim logs](https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#troubleshooting) to see the exact path (and its version info) to Nvim being used by vscode-neovim

**Comment by rv-nath** [comment]
You mean this view..  These logs and messages are empty.

![image](https://github.com/user-attachments/assets/a1119baf-4c95-4626-bf43-adf176c17b4a)
and this...

![image](https://github.com/user-attachments/assets/540d79c5-15a6-44d3-a2f4-5ecc1de004c2)

**Comment by justinmk** [comment]
in the `vscode-neovim logs` view (not "messages"), click the gear icon and select "debug". then click it again and select "set as default". 

then restart and try again. if no logs appear, the extension isn't running.

**Comment by rv-nath** [comment]
Here is the output.  
- I still get the alert saying nvim version .10 or higher required.
- the neovim editing works, in spite of the above msg.
- The erratic behaviour might surface anytime.

```shell
2024-09-11 11:37:21.762 [info] MainController: Starting nvim: /usr/bin/nvim.appimage -N --embed --cmd source /home/rvnath/.vscode-server/extensions/asvetliakov.vscode-neovim-1.18.11/runtime/vscode-neovim.vim --clean
2024-09-11 11:37:22.341 [info] MainController: Nvim info: {
  nvimVersion: {
    minor: 10,
    build: 'g27fb62988',
    api_prerelease: null,
    prerelease: true,
    api_level: 12,
    major: 0,
    api_compatible: 0,
    patch: 0
  },
  logFile: '/home/rvnath/.local/state/nvim/log',
  configDir: '/home/rvnath/.config/nvim'
}
2024-09-11 11:39:29.234 [debug] BufferManager: Visible editor, viewColumn: 1, doc: vscode-userdata:/c%3A/Users/ravindranath.m/AppData/Roaming/Code/User/settings.json
2024-09-11 11:39:29.235 [debug] BufferManager: Setting active editor - viewColumn: 1, winId: 1002
2024-09-11 11:39:29.236 [debug] BufferManager: Cancel visual mode to prevent selection from previous editor to carry over to active editor
2024-09-11 11:39:29.237 [debug] ModeManager: Changing mode to n
2024-09-11 11:39:29.237 [debug] ModeManager: Setting mode context to normal
2024-09-11 11:39:29.347 [debug] BufferManager: window changed, target window id: 1002
2024-09-11 11:39:36.314 [debug] TypingManager: Send for: <C-a>
```

**Comment by justinmk** [comment]
Your logs show `prerelease: true`. As mentioned in https://github.com/vscode-neovim/vscode-neovim/issues/2227#issuecomment-2334836590 and https://github.com/vscode-neovim/vscode-neovim/issues/2225#issuecomment-2334832907 , you need to update to an actual v0.10.0 release, not a prerelease (which could be any commit before the final release).

Your logs also show the exact Nvim path that was used (perhaps you configured it in vscode settings): `/usr/bin/nvim.appimage`.

Either update your settings, or clear the setting so that vscode-neovim will search `$PATH` for a valid Nvim.
