### ISSUE TITLE
support IME setting `editor.experimentalEditContextEnabled`

### ISSUE THREAD

**Issue by wenfangdu** [vscode-neovim/vscode-neovim#2239]
Currently, `vscode-neovim` doesn't work well with the new IME setting `editor.experimentalEditContextEnabled`, please support it.

Refs: https://github.com/microsoft/vscode/issues/183814#issuecomment-2337849263, https://github.com/microsoft/vscode/issues/154935#issuecomment-2337893514.

**Comment by justinmk** [comment]
What did you try and what are the results?

Pasting a comment from your linked issues, to provide context:

> The new "editor.experimentalEditContextEnabled" fixes this issue, because a div containing the text is no longer being made visible during composition.

**Comment by xiyaowong** [comment]
Fix what? First, this is an experimental feature in VSCode that has just been added. Secondly, this option has issues because VSCodeVim is also not working properly, which means the registration of the type command has been broken.

**Comment by wenfangdu** [comment]
What I meant is that if `editor.experimentalEditContextEnabled` gets finalized, vscode & vscodevim/vscode-neovim need to work together like before. For that to happen, both sides might have works to do, therefore I opened issues regarding to `editor.experimentalEditContextEnabled` on both repos.

**Comment by xiyaowong** [comment]
Vscode should ensure that this option will not destroy the existing input method, rather than we are compatible with this option.
