### ISSUE TITLE
bug: Unable to find a suitable neovim executable. Please check your neovim installation

### ISSUE THREAD

**Issue by michens** [vscode-neovim/vscode-neovim#2240]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Windows 11

### Describe the bug

Starting from v1.18.10, vscode-neovim can no longer find neovim. Reverting to v1.18.9 or earlier fixes the problem.

### Steps To Reproduce

1. Launch VSCode. 
2. Get error message

### Expected Behavior

Extension works

**Comment by polaritus9801** [comment]
how did you solve that?
