### ISSUE TITLE
bug: The output window shows messages from Neovim constantly

### ISSUE THREAD

**Issue by dotai2012** [vscode-neovim/vscode-neovim#2248]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.10.1

### Operating system/version

Ubuntu 22.04

### Describe the bug

I am not sure why it behaves this way after upgrading vscode-neovim to 1.18.10, probably because of https://github.com/vscode-neovim/vscode-neovim/pull/2177, 

This problem is the same as https://github.com/vscode-neovim/vscode-neovim/issues/2099, https://github.com/vscode-neovim/vscode-neovim/issues/2109. And I have tried all possible solutions (setting cmdheight, changed the log to developer console), but it didn't work

There is also a weird thing: If I use `echo &cmdheight` to check the current cmdheight in Vscode, it sometimes shows 0 sometimes shows 1. When it shows 1, then I don't have this problem

I think there is a race condition and the cmdheight is replaced by other Lua scripts 

### Steps To Reproduce

1. Upgrade vscode-neovim to 1.18.10
2. Try to yank/copy something
3. The message is shown in the output window

![image](https://github.com/user-attachments/assets/ce1d88a2-004f-4a62-ac16-1d0eb020c149)

### Expected Behavior

If

- Log Output To developer console = true
- Or cmdheight = 1 in the init.lua file

Then the output window should not pop up

**Comment by justinmk** [comment]
> If I use `echo &cmdheight` to check the current cmdheight in Vscode, it sometimes shows 0 sometimes shows 1. When it shows 1, then I don't have this problem

Use `:verbose set cmdheight?` to see what set it to 0. If it's from a Lua script, start nvim with `-V1` to enable tracing of Lua calls, then try again.

**Comment by dotai2012** [comment]
Thank you @justinmk , looks like the culprit was Astrovim's plugin

![image](https://github.com/user-attachments/assets/4cfb1066-5ee4-4639-b443-d7f45b4d5906)

However, I have set "Log Output To developer console = true", so it shouldn't print to the Output window in the first place, right?

![image](https://github.com/user-attachments/assets/125e509c-563b-433a-a7f6-f87745133a80)

**Comment by justinmk** [comment]
> I have set "Log Output To developer console = true", so it shouldn't print to the Output window in the first place, right?

I think that's only for logs. Why not fix the actual problem?

Why use astro when embedded in vscode? Makes no sense.
