### ISSUE TITLE
bug: pressing `o` will create a new line, but the indent seems have a mistake

### ISSUE THREAD

**Issue by baizeyv** [vscode-neovim/vscode-neovim#2250]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Windows 11 PRO

### Describe the bug

```c#
    public class AssetManager : MonoBehaviour, ISingleton(cursor here)
```
press `o`
```c#
    public class AssetManager : MonoBehaviour, ISingleton
                                               |(curso here)
```
press `O`
```c#
                                               |(curso here)
    public class AssetManager : MonoBehaviour, ISingleton
```

### Steps To Reproduce

in insert mode press `<C-j>` or 
in normal mode press  `o` or `O`

### Expected Behavior

```c#
    public class AssetManager : MonoBehaviour, ISingleton(cursor here)
```
press `o`
```c#
    public class AssetManager : MonoBehaviour, ISingleton
    |(curso here)
```
press `O`
```c#
    |(curso here)
    public class AssetManager : MonoBehaviour, ISingleton
```

**Comment by justinmk** [comment]
> I have searched existing issues.

Did you search closed issues? I think there are open ones that cover this. 

Or, explain how this issue is different than the existing ones.

**Comment by baizeyv** [comment]
old issue will create a  new extra empty line, but this is only a indent mistake

**Comment by justinmk** [comment]
searching for `"o" indent` gives several relevant-looking results.

https://github.com/vscode-neovim/vscode-neovim/issues/1172

https://github.com/vscode-neovim/vscode-neovim/issues/799

**Comment by baizeyv** [comment]
我刚刚设置filetype indent off，它解决了我的问题。我没有从已关闭的问题中找到此解决方案，这是我的错误。我应该查一下吗？谢谢，你是我的英雄，我会关闭这个问题。
