### ISSUE TITLE
"unable to find suitable neovim" (vscode remote)

### ISSUE THREAD

**Issue by orangejuicetin** [vscode-neovim/vscode-neovim#2251]
### Check the following:

- [X] I have tried setting `vscode-neovim.neovimClean` in VSCode settings and **restarting VSCode.**
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing (closed!) issues.

### Neovim version (nvim -v)

0.10.1 Release

### Operating system/version

Ubuntu 20.04.6 LTS

### Problem (including [log messages](https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#troubleshooting))

Logs are still showing the same uninformative message of "Unable to find a suitable neovim executable. Please check your neovim installation". Sufficient release with `nvim -v` yielding `0.10.1`, and the path settings have changed as below (this is using the Remote SSH vscode extension to work on an Ubuntu Focal machine): 
![image](https://github.com/user-attachments/assets/bf818ad7-cb43-4223-a55b-dda4f3637728)

### Steps To Reproduce

Just opening the vscode-neovim extension on my machine causes this message to repeatedly show up with no logs showing up at times even.

### Expected Behavior

A working neovim extension! You guys have done great work and it's a wonderful extension, it's just a shame the last two releases seem to not be working. The version I had to rollback to was v1.18.9 in order for it to start working again on my machine.

**Comment by justinmk** [comment]
> The version I had to rollback to was v1.18.9

Post the logs from that version

**Comment by orangejuicetin** [comment]
```
2024-09-16 15:00:18.653 [info] MainController: Starting nvim: /opt/homebrew/bin/nvim -N --embed --cmd source /Users/justinchoi/.vscode/extensions/asvetliakov.vscode-neovim-1.18.7/runtime/vscode-neovim.vim --clean
2024-09-16 15:00:18.711 [info] MainController: Nvim info: {
  nvimVersion: {
    minor: 9,
    major: 0,
    api_level: 11,
    api_prerelease: false,
    api_compatible: 0,
    patch: 5,
    prerelease: false
  },
  logFile: '/Users/justinchoi/.local/state/nvim/log',
  configDir: '/Users/justinchoi/.config/nvim'
}
2024-09-16 15:01:20.481 [info] MainController: Starting nvim: /opt/homebrew/bin/nvim -N --embed --cmd source /Users/justinchoi/.vscode/extensions/asvetliakov.vscode-neovim-1.18.9/runtime/vscode-neovim.vim --clean
2024-09-16 15:01:20.548 [info] MainController: Nvim info: {
  nvimVersion: {
    api_compatible: 0,
    prerelease: false,
    api_level: 11,
    api_prerelease: false,
    major: 0,
    minor: 9,
    patch: 5
  },
  logFile: '/Users/justinchoi/.local/state/nvim/log',
  configDir: '/Users/justinchoi/.config/nvim'
}
```

**Comment by justinmk** [comment]
The logs in the old version are showing `/opt/homebrew/bin/nvim` as the path to nvim. That's probably because vscode-neovim is running as a "ui" extension. 

So you should update your local nvim (`/opt/homebrew/bin/nvim`), the remote environment is irrelevant.

When you connect via "vscode remote", vscode "ui" extensions run locally. The local `nvim` is used as a logic host, it doesn't access the remote filesystem. 

Alternativel you could try setting `remote.extensionKind` to "workspace":
https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#remote-development

**Comment by orangejuicetin** [comment]
It works! Thanks for helping diagnose, that was a great spot @justinmk
