### ISSUE TITLE
bug: WARNING: vim.treesitter.get_parser will return nil instead of raising an error in Neovim 0.12

### ISSUE THREAD

**Issue by GrzegorzKozub** [vscode-neovim/vscode-neovim#2255]
### Check the following:

- [X] I have tried setting `vscode-neovim.neovimClean` in VSCode settings and **restarting VSCode.**
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing (closed!) issues.

### Neovim version (nvim -v)

v0.11.0-dev-798+ge268fcbda

### Operating system/version

Arch Linux

### Problem (including [log messages](https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#troubleshooting))

The following warning appears in `vscode-neovim messages and the status bar`:

```
WARNING: vim.treesitter.get_parser will return nil instead of raising an error in Neovim 0.12
```

Not blocking anything but may be worth fixing for future

### Steps To Reproduce

1. Just launch vscode

### Expected Behavior

No warning

**Comment by justinmk** [comment]
apparently we are calling that here: https://github.com/vscode-neovim/vscode-neovim/blob/ccd89d3e457ee968c09eb13d711bde0e0097a3f9/runtime/vscode/treesitter.lua#L6-L10

but we disable ts here: https://github.com/vscode-neovim/vscode-neovim/blob/ccd89d3e457ee968c09eb13d711bde0e0097a3f9/runtime/lua/vscode/highlight.lua#L142-L147

so I'm not sure why we are calling get_parser?

**Comment by GrzegorzKozub** [comment]
Parsing the file on each change may impact the performance for users who do not suffer from https://github.com/vscode-neovim/vscode-neovim/pull/1713. Maybe we could make creating this autocommand optional via a setting?

**Comment by xiyaowong** [comment]
It's not a big issue; it's just a temporary warning in the Neovim nightly version that can't be avoided for now.

**Comment by xiyaowong** [comment]
>  autocommand 

We're already using autocmd, and there's also debounce implemented, so there's no need to worry about performance issues. #2154

**Comment by GrzegorzKozub** [comment]
This is fine then. Thanks!
