### ISSUE TITLE
bug: Unacceptable delay on 'o' key since 1.17.0

### ISSUE THREAD

**Issue by gaoqiangks** [vscode-neovim/vscode-neovim#2256]
### Check the following:

- [X] I have tried setting `vscode-neovim.neovimClean` in VSCode settings and **restarting VSCode.**
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing (closed!) issues.

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

Ubuntu24.04 on wsl2.

### Problem (including [log messages](https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#troubleshooting))

There's an unacceptable delay when pressing the key 'o' to enter editing mode.

[diffgeom.zip](https://github.com/user-attachments/files/17088624/diffgeom.zip)

### Steps To Reproduce

1. Open the folder diffgeom with vscode.
2. Open the file surfaceI.tex
3. Press 'o' to enter editing mode and type anything. 

See this video.  

https://github.com/user-attachments/assets/53e226d7-a08b-4d8b-a971-077e000984ab

### Expected Behavior

Any text typed after pressing 'o' should be on the next line.

**Comment by justinmk** [comment]
Are you certain this happens when `vscode-neovim.neovimClean` is set? It sounds like a plugin or mappings issue.

**Comment by gaoqiangks** [comment]
> Are you certain this happens when `vscode-neovim.neovimClean` is set? It sounds like a plugin or mappings issue.
> 
> Related: #31

Yes, I'm sure ```neovimClean``` is set, and I disabled all extensions of vscode. The video I uploaded shows it.   This happens after I updated this extension days ago.  ( I havn't updated  ```vscode-neovim```  for months)

**Comment by justinmk** [comment]
Ok, can you bisect the exact vscoden-neovim regression where the issue appeared? Vscode makes this easy to do:

![image](https://github.com/user-attachments/assets/c07fea17-3b1e-4856-b969-b010a8a9b6e0)

**Comment by gaoqiangks** [comment]
> Ok, can you bisect the exact vscoden-neovim version where the issue appeared? Vscode makes this easy to do:
> 
> ![image](https://private-user-images.githubusercontent.com/1359421/369678201-c07fea17-3b1e-4856-b969-b010a8a9b6e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwMDA0MzMsIm5iZiI6MTcyNzAwMDEzMywicGF0aCI6Ii8xMzU5NDIxLzM2OTY3ODIwMS1jMDdmZWExNy0zYjFlLTQ4NTYtYjk2OS1iMDEwYThhOWI2ZTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjJUMTAxNTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDY3ZGE2NjUwMWNiNDQ1NjkwZGZkYzg1OWIyMjUzNmEyZGUzODE4ZjQ4NjU2Y2MzNGQwNTkyZDNhODMwNDUxZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.d1Bp5g9MiFijD_eG41O4pCdD3LpGA6FSIsWNkXckwEU)

There's a non-negligible delay since v1.7.0.   

Uploading delay2.mp4…

**Comment by justinmk** [comment]
> There's a non-negligible delay since [v1.7.0](https://github.com/vscode-neovim/vscode-neovim/releases/tag/v1.7.0).

But _not_ in 1.6.1? 1.7.0 didn't [change anything](https://github.com/vscode-neovim/vscode-neovim/compare/v1.6.1...v1.7.0) related to input 🤔

**Comment by gaoqiangks** [comment]
> > There's a non-negligible delay since [v1.7.0](https://github.com/vscode-neovim/vscode-neovim/releases/tag/v1.7.0).
> 
> But _not_ in 1.6.1? 1.7.0 didn't [change anything](https://github.com/vscode-neovim/vscode-neovim/compare/v1.6.1...v1.7.0) related to input 🤔

Sorry, it's since version 1.17.0, not 1.7.0. Things work well in version 1.16.0.

**Comment by justinmk** [comment]
> There's a non-negligible delay since v1.7.0.

oh, based on your screen recording, you mean 1.17

**Comment by justinmk** [comment]
bisected to: https://github.com/vscode-neovim/vscode-neovim/releases/tag/v1.17.0

**Comment by gaoqiangks** [comment]
> Thanks for reporting this. This is a tricky bug to fix, especially since it is difficult for us to reproduce ourselves (I also use vscode-neovim in wsl at work, and it works fine). Hopefully someone will have the time eventually to look into this. For now, please revert to an older version of the extension.

I know what's happening now. I'm writing a math book and there are some long lines, so I set ```neovimWidth = 20000```, which is too large.  Now I set it to 5000 and it works well.

**Comment by gaoqiangks** [comment]
> Thanks for reporting this. This is a tricky bug to fix, especially since it is difficult for us to reproduce ourselves (I also use vscode-neovim in wsl at work, and it works fine). Hopefully someone will have the time eventually to look into this. For now, please revert to an older version of the extension.

I know what's happening now. I'm writing a math book and there are some long lines, so I set neovimWidth = 20000, which is too large. Now I set it to 5000 and it works well.
