### ISSUE TITLE
Endless 'Syncing layout: Syncing visible editors'

### ISSUE THREAD

**Issue by imoyy** [vscode-neovim/vscode-neovim#2273]
Type: <b>Bug</b>

It suddenly appears without any warning, and the only way to recover is to restart vscode.

Extension version: 1.18.12
VS Code version: Code - Insiders 1.95.0-insider (af6645a661a5402af586154207ee2ea3742f3bea, 2024-10-04T12:46:44.894Z)
OS version: Darwin x64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400F (12 x 2500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|12, 6, 5|
|Memory (System)|32.00GB (2.47GB free)|
|Process Argv|--crash-reporter-id b81652b2-f252-46f7-b39d-72713ae3cd4c|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vscod805:30301674
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
945dj816:31013170
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
nb_pkg_only:31057982
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31151552
cf971741:31144450
e80f6927:31120813
defaultse:31146405
12bdf347:31141542
iacca1:31150324
notype1:31143044
f8igb616:31140137

```

</details>

**Comment by micdonato** [comment]
Ha, I have the same issue on the release version of VSCode. Reloading the window solves the issue. Why was it closed?

**Comment by Kossak-esky** [comment]
I have the exact same error.
@justinmk any update on it? It happens too often, for now I need to go back to vim extension...

**Comment by tkossak** [comment]
I have the exact same error.
@justinmk any update on it? It happens too often, for now I need to go back to vim extension...

**Comment by justinmk** [comment]
There are multiple other issues open tracking this.

**Comment by tkossak** [comment]
I found only 2 open: this one and https://github.com/vscode-neovim/vscode-neovim/issues/2184
In the other one you asked if `CTRL+L` helps in recovering, but I couldn't even write an answer because the thread is locked to collaborators. I can check, but it would be safer to write which command to run, because people may have `Ctrl+L` bound to something else (I have it bound to next editor in group)

**Comment by tkossak** [comment]
It has a bit different error message ("active" instead of "visible") that's why github doesn't show it for people searching for specific message. Maybe the cause is the same for both errors...
