### ISSUE TITLE
bug: Commands inside init.lua do not work

### ISSUE THREAD

**Issue by SFX123456** [vscode-neovim/vscode-neovim#2277]
### Check the following:

- [X] I have tried setting `vscode-neovim.neovimClean` in VSCode settings and **restarting VSCode.**
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing (closed!) issues.

### Neovim version (nvim -v)

0.11

### Operating system/version

WIndows 10

### Problem (including [log messages](https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#troubleshooting))

I dont think the extension is using my init.lua.
With this content vim.keymap.set({'i'}, 'j','k')
it does work like as expected inside nvim but not inside vscode. 
With this content 
vim.keymap.set({'i'}, 'j','k')

print("hello world")
it should print hello world somewhere. 
It works with nvim again.
I have tried to set the init.lua path but it does not change anything. It does seem to pick it up as i get errors if the init.lua file is incorrect.
ehler beim Ausführen von "C:\\Users\\Nico\\AppData\\Local\\nvim\\init.lua":\n' +
  "E5113: Error while calling lua chunk: C:\\Users\\Nico\\AppData\\Local\\nvim\\init.lua:1: attempt to index field 'keymgggap' (a nil value)\n" +
  'stack traceback:\n' +
  '\tC:\\Users\\Nico\\AppData\\Local\\nvim\\init.lua:1: in main chunk\n'

Its really frustrating as i really dont see anything that could be wrong. Its just not working.
The command that works is from a tutorial on mac and for him its working. 

2024-10-09 18:20:43.145 [info] MainController: Nvim info: {
  configDir: 'C:\\Users\\Nico\\AppData\\Local\\nvim',
  nvimVersion: {
    build: 'gf449a38f6',
    patch: 0,
    minor: 11,
    prerelease: true,
    api_compatible: 0,
    api_level: 13,
    api_prerelease: true,
    major: 0
  },
  logFile: 'C:\\Users\\Nico\\AppData\\Local\\nvim-data\\log'
}
2024-10-09 18:31:28.772 [info] MessagesManager: 'C:\\Users\\Nico\\AppData\\Local\\nvim\\init.lua\n'
2024-10-09 18:31:56.715 [info] MessagesManager: ''
2024-10-09 18:32:17.345 [info] MessagesManager: 'C:\\Users\\Nico\\AppData\\Local\\nvim-data\\log\n'
2024-10-09 18:33:00.694 [info] MessagesManager: 'C:\\Users\\Nico\\AppData\\Local\\nvim\n'
2024-10-09 18:39:33.315 [info] MainController: Starting nvim: C:\Users\Nico\Downloads\nvim-win64\nvim-win64\bin\nvim.exe -N --embed --cmd source c:\\Users\\Nico\\.vscode\\extensions\\asvetliakov.vscode-neovim-1.18.12/runtime/vscode-neovim.vim
2024-10-09 18:39:33.446 [info] MainController: Nvim info: {
  configFile: 'C:\\Users\\Nico\\AppData\\Local\\nvim\\init.lua',
  nvimVersion: {
    api_level: 13,
    api_prerelease: true,
    api_compatible: 0,
    prerelease: true,
    minor: 11,
    major: 0,
    build: 'gf449a38f6',
    patch: 0
  },
  logFile: 'C:\\Users\\Nico\\AppData\\Local\\nvim-data\\log',
  configDir: 'C:\\Users\\Nico\\AppData\\Local\\nvim'
}

### Steps To Reproduce

On Windows, clone kickstarter.nvim in C:\Users\YOURUSER\AppData\Local\nvim\ 
i got a bunch of errors.
Then i made a clean init.lua and i get the weird behaviour reported.

### Expected Behavior

I expected it that if i type j in insert mode it prints k.

**Comment by justinmk** [comment]
very hard to read this, please use markdown formatting to format codeblocks.

> print("hello world")
> it should print hello world somewhere.

No, it shouldn't. If you put that print() call in your init.lua, then Nvim will print it possibly before vscode-neovim connects. 

It sounds like you are assuming things "don't work" based on a print() statement, but you also indicated that your init.lua is correctly getting found.
