### ISSUE TITLE
feature: An option to execute `vscode-neovim.send` synchronously in normal mode

### ISSUE THREAD

**Issue by gaoqiangks** [vscode-neovim/vscode-neovim#2296]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

For details, see this discussion https://github.com/vscode-neovim/vscode-neovim/discussions/2289.

The doc says   "command": "vscode-neovim.send"  "title": "Neovim: send key to neovim, syncing if in insert mode". Therefore, I think in normal mode, this command is executed asynchronously, and I tested, it is.

### Describe the solution you'd like

Could you give an option to execute `vscode-neovim.send` synchronously?

### Describe alternatives you've considered

Placing a `sleep` before executing the next command is an inelegant solution.

**Comment by justinmk** [comment]
This currently isn't possible (in a 100% reliable way), see https://github.com/neovim/neovim/issues/10826 https://github.com/neovim/neovim/issues/30760

**Comment by gaoqiangks** [comment]
> This currently isn't possible (in a 100% reliable way), see [neovim/neovim#10826](https://github.com/neovim/neovim/issues/10826) / [neovim/neovim#30760](https://github.com/neovim/neovim/issues/30760)
> 
> > For details, see this discussion #2289.
> 
> Provide a small (3 lines of code), concrete example here, don't link to a long discussion.
> 
> What keys do you need to send, why can't you use `:normal` or other commands?

For example, I want to map `<a-p>` to paste yanked lines and autoindent them.  I tried 

```
keyset("n", "<A-p>", function() 
    --  paste yanked text below the current line
    vim.api.nvim_exec2(vim.api.nvim_replace_termcodes("normal o<Esc>p", true, false, true), {output=false})
    -- select pasted text
    vim.cmd.normal("`[v`]")
   -- reindent select lines. This command doesn't work
    vscode.call('editor.action.reindentselectedlines')
    vim.cmd.normal(vim.api.nvim_replace_termcodes('<Esc>', true, true, true))
end, {silent=true, desc= "粘贴到下一行"})

```

It doesn't work. It seems that buffer state of nvim isn't synchronized to vscode before all commands in this map are executed, therefore,  duiring the line `vscode.call('editor.action.reindentselectedlines')`, vscode is unaware of the section.  I searched the doc and find no solution.  Therefore, I turned to the vscode side to solve this problem.  In `keybindings.json`, I map `<alt-p>` to two commands:  `vscode-neovim.send '<a-p>'`,  which paste text and select them, and `editor.action.reindentselectedlines`. However, `vscode-neovim.send` is executed asynchronously, and I have to put a sleep before executing reindenting. 


Could me give me some hits?

**Comment by theol0403** [comment]
>  during the line vscode.call('editor.action.reindentselectedlines'), vscode is unaware of the section

It should be. You can try adding a small delay to give the visual selection time to sync to nvim (by default, debounced by 50ms). Alternatively, you can passing `range` to the `call` function to explicitly tell vscode which range to indent, without needing a visual selection. This is the canonical approach. 

> I turned to the vscode side to solve this problem

Hacks like `multiCommand` is a terrible approach and will never be supported by this extension. `vscode-neovim.send` is intended simply to passthrough keybindings, and should not be used in automations. Besides, making it "synchronous" makes no sense, as that implies having some functionality, through the nvim api, to synchronously block `nvim_input` until whatever binding gets triggered by the keystrokes is finished processing. `nvim_input` simply adds the keystrokes to the event buffer.

**Comment by justinmk** [comment]
> that implies having some functionality, through the nvim api, to synchronously block `nvim_input` until whatever binding gets triggered by the keystrokes is finished processing. `nvim_input` simply adds the keystrokes to the event buffer.

Nvim support for that is planned: 

- https://github.com/neovim/neovim/issues/10826
- https://github.com/neovim/neovim/issues/30760
