### ISSUE TITLE
bug: Triple left-click selects the first character on the next line

### ISSUE THREAD

**Issue by monyxie** [vscode-neovim/vscode-neovim#2305]
### Check the following:

- [X] I have tried setting `vscode-neovim.neovimClean` in VSCode settings and **restarting VSCode.**
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing (closed!) issues.

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

Linux 6.11.5-arch1-1

### Problem (including [log messages](https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#troubleshooting))

Under normal mode, triple left-click (line-wise selection) also selects the first character on the next line. It should only select the current line.
Insert mode doesn't seem to have this issue.

### Steps To Reproduce

1. Switch to normal mode
2. Triple left-click on any line
3. The first character on the next line is selected along the current line

### Expected Behavior

Only the current line should be selected

**Comment by xiyaowong** [comment]
This is the behavior of VS Code, which includes the line break at the end of the triple-clicked line. You can set `:set selection=exclusive`, but I recommend switching to insert mode before selecting with the mouse.
