### ISSUE TITLE
feature: show vim command line at the bottom of vscode

### ISSUE THREAD

**Issue by CCLDArjun** [vscode-neovim/vscode-neovim#2312]
### Did you check the docs?

- [X] I have read all the vscode-neovim docs
- [X] I understand the fundamental limitations of the plugin and believe this request to be reasonable

### Is your feature request related to a problem? Please describe.

<img width="607" alt="Screenshot 2024-11-10 at 10 20 24 PM" src="https://github.com/user-attachments/assets/9c804935-1cab-40f7-914d-f17ac1370c2e">

I find this window kinda obnoxious 

### Describe the solution you'd like

<img width="240" alt="Screenshot 2024-11-10 at 10 20 44 PM" src="https://github.com/user-attachments/assets/e776d4b4-d882-4d6d-b759-32af30cb56c2">

I would like for the vim command line contents to be displayed here, similar to regular neovim

### Describe alternatives you've considered

I looked through the settings and readme but couldn't find anything to do this

**Comment by theol0403** [comment]
Duplicates:

- https://github.com/vscode-neovim/vscode-neovim/issues/2312
- https://github.com/vscode-neovim/vscode-neovim/issues/1130
- https://github.com/vscode-neovim/vscode-neovim/issues/781
- https://github.com/vscode-neovim/vscode-neovim/issues/297

VSCode now supports dragging/moving the command line. 

- https://github.com/microsoft/vscode/issues/17268
- https://github.com/microsoft/vscode/pull/237847

Move it to where you want by dragging or using configure menu.

![Image](https://github.com/user-attachments/assets/66b14e59-1a85-4328-8292-05da1ce03e40)

Move to middle by using `workbench.action.alignQuickInputCenter`
