### ISSUE TITLE
bug: Crash (Core Dump) during vscodium shutdown with "experimental.affinity" enabled

### ISSUE THREAD

**Issue by castarray** [vscode-neovim/vscode-neovim#2315]
### Check the following:

- [X] I have tried setting `vscode-neovim.neovimClean` in VSCode settings and **restarting VSCode.**
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing (closed!) issues.

### Neovim version (nvim -v)

0.10.2

### Operating system/version

Arch Linux (fully updated)

### Problem (including [log messages](https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#troubleshooting))

The issue does not occur when the Neovim plugin is disabled or the experimental.affinity option is commented out.
Even when all Neovim configuration files (written in Lua) are fully commented out, the same issue persists.

My additional environments: VSCodium: v1.95.3.24321-1 (AUR package), vscode-neovim plugin: v1.18.14

Here is a stacktrace: [gdb.txt](https://github.com/user-attachments/files/17883056/gdb.txt)

### Steps To Reproduce

1. Enable the vscode-neovim plugin.
2. Add the following to `settings.json`:
   ```json
   "extensions.experimental.affinity": {
      "asvetliakov.vscode-neovim": 1
   }
 3. Exit vscodium (e.g., via awesome wm keybinding or pkill -15 codium)
 4. Observe core dump and crash.


### Expected Behavior

vscodium should exit cleanly without generating a core dump.

**Comment by justinmk** [comment]
A core dump is always a vscode bug. Report it to vscode(ium).
