### ISSUE TITLE
bug: attempt to index global 'Snacks' (a nil value)

### ISSUE THREAD

**Issue by dgokcin** [vscode-neovim/vscode-neovim#2321]
### Check the following:

- [X] I have tried setting `vscode-neovim.neovimClean` in VSCode settings and **restarting VSCode.**
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing (closed!) issues.

### Neovim version (nvim -v)

v0.10.2

### Operating system/version

MacOS 15.1.1 (24B91)

### Problem (including [log messages](https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#troubleshooting))

There seems to be an issue with loading the keymaps in my neovim configuration, after a clean install of neovim and lazyvim. I only see this issue on VsCode Neovim(no error messages when I run nvim on my local machine).

Any help is muchly appreciated

```console
Failed loading lazyvim.config.keymaps




...ocal/share/nvim/lazy/LazyVim/lua/lazyvim/util/format.lua:182: attempt to index global 'Snacks' (a nil value)




# stacktrace:


  - /LazyVim/lua/lazyvim/util/format.lua:182 _in_ **snacks_toggle**


  - /LazyVim/lua/lazyvim/config/keymaps.lua:123


  - /LazyVim/lua/lazyvim/config/init.lua:252


  - /LazyVim/lua/lazyvim/config/init.lua:251 _in_ **_load**


  - /LazyVim/lua/lazyvim/config/init.lua:259 _in_ **load**


  - /LazyVim/lua/lazyvim/config/init.lua:185
```

### Steps To Reproduce

1. Clone `https://github.com/dgokcin/dotfiles`
2. Run `make nvim`
3. Open VsCode to see the mentioned error.

### Expected Behavior

No error messages to pop.

**Comment by justinmk** [comment]
The  [log messages](https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#troubleshooting)) show the exact command used to start `nvim`. That doesn't exactly match the usual `nvim` case. Could be an assumption by lazy, or your config. You need to bisect that yourself (`:help bisect`)
