### ISSUE TITLE
bug: Cursor may be misplaced when working with LSPs with inline prompts such as clangd

### ISSUE THREAD

**Issue by CodingOIer** [vscode-neovim/vscode-neovim#2325]
### Check the following:

- [X] I have tried setting `vscode-neovim.neovimClean` in VSCode settings and **restarting VSCode.**
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing (closed!) issues.

### Neovim version (nvim -v)

NVIM v0.10.2

### Operating system/version

VSCode on Windows11 but SSH to Ubuntu

### Problem (including [log messages](https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#troubleshooting))

![image](https://github.com/user-attachments/assets/ce73a2ba-c068-4a08-9d66-9598579d57df)
As shown in the figure, the cursor should be on the s of still - 1 on the right side.

### Steps To Reproduce

1. Working with clangd
2. Writing code with inline hints
3. Move to the left of the inline prompt, then use l to move right
4. The cursor appears on the first character of the inline hint, and moves right again to appear on the second character of the actual text.

### Expected Behavior

The cursor should pass over the inline hint and appear directly on the first character of the actual text

**Comment by CodingOIer** [comment]
https://github.com/user-attachments/assets/0b86a224-cb5d-4d87-a648-f5a9f64ab034

**Comment by theol0403** [comment]
https://github.com/vscode-neovim/vscode-neovim/issues/946
https://github.com/VSCodeVim/Vim/issues/8141
https://github.com/microsoft/vscode/issues/127703

If this isn't fixed in vscodevim, there is nothing we can do about it until it is fixed on the vscode side.
