### ISSUE TITLE
bug: ctrl+w related shortcut bug

### ISSUE THREAD

**Issue by liinyun** [vscode-neovim/vscode-neovim#2334]
### Check the following:

- [X] I have tried setting `vscode-neovim.neovimClean` in VSCode settings and **restarting VSCode.**
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing (closed!) issues.

### Neovim version (nvim -v)

0.10.2

### Operating system/version

fedora 41

### Problem (including [log messages](https://github.com/vscode-neovim/vscode-neovim?tab=readme-ov-file#troubleshooting))

    {
        "key": "ctrl+w e",
        "command": "workbench.action.toggleSidebarVisibility"
    },
    {
        "key": "ctrl+b",
        "command": "-workbench.action.toggleSidebarVisibility"
    },
    I have configed a shortcut like this. Now all vscode neovim shortcut related with ctrl+w don't work. Only the shortcut like ctrl+w ? will disable the vscode neovim shortcuts. If I change it to simply "ctrl+w" or "ctr+e", it will work properly

### Steps To Reproduce

you just need to add 
    {
        "key": "ctrl+e",
        "command": "workbench.action.toggleSidebarVisibility"
    },
    {
        "key": "ctrl+b",
        "command": "-workbench.action.toggleSidebarVisibility"
    },

these code to you keybindings.json 

### Expected Behavior

I have explained it in Problem column

**Comment by theol0403** [comment]
You need to bind this from inside your init.lua. If vscode is trying to wait to resolve a chord, it won't know to send it to neovim. Use vscode.call inside neovim.
