### ISSUE TITLE
Dirty ("modified") file status

### ISSUE THREAD

**Issue by jdahm** [vscode-neovim/vscode-neovim#247]
Great extension! I think this is a really nice use of neovim. I'd like to adopt this in my workflow, but I'm having a hard time getting over the fact that vscode tells me files have unsaved changes after backing out all changes with 'u' in normal mode. Is there a way around this?

**Comment by mvalero** [comment]
+1 I came into same problem when evaluating the extension to see if I can switch from vscodevim to neovim.

It makes the daily work a bit annoying as you see a lot of "changed" files that actually have no changes.

Even getting into insert mode and exiting using `jj` marks the file as dirty in my case.

**Comment by phphong** [comment]
Try putting this into your `init.vim`. It means using VSCode undo stack instead of neovim's undo stack. They may cause some problems for example you have to undo multiple times instead of 1 time.

```vim
if exists('g:vscode')
    nnoremap <silent> u :<C-u>call VSCodeNotify('undo')<CR>
    nnoremap <silent> <C-r> :<C-u>call VSCodeNotify('redo')<CR>
endif
```

**Comment by jdahm** [comment]
Thanks! That seems to work. I'll use it for a few days and report back if there are any issues that come up.

**Comment by asvetliakov** [comment]
There is no way to set/reset dirty file status in vscode, except using vscode undo stack which is problematic

**Comment by jdahm** [comment]
@phphong - This works well for me. Thanks again!

**Comment by Shatur95** [comment]
@asvetliakov, what if just call `workbench.action.files.revert` in the last Neovim undo?

**Comment by asvetliakov** [comment]
@Shatur95 that will lead to the incorrect behaviour because `files.revert` will revert a file to the last saved content which can be different than the undo stack (e.g. you've changed something (1), saved (2), changed again (3), calling `files.revert` will revert you back to (2), although in this case you must have the dirty status). 

We can revert (or alternatively call `save`) only when `save_last` from vim's `undotree()` is equal to `seq_cur`, but the problem all buffers from neovim are scratch ones and never saved

**Comment by Shatur95** [comment]
@asvetliakov, yes, you are right :(

**Comment by Jun-JZ** [comment]
> There is no way to set/reset dirty file status in vscode, except using vscode undo stack which is problematic

Could you please elaborate on what's the problem with vscode's undo?

**Comment by theol0403** [comment]
I think the biggest reason is inconsistency with vim's undo behaviour. It won't undo things in the same chunks as nvim, won't work with plugins, and nvim will consider redoes as edits. Its a compromise both ways unless there is a new vscode dirty file flag api.

**Comment by philippmossier** [comment]
Here is a workaround to get rid of the **Dirty ("modified") file status** inside vscode, after your last undo is "already the oldest change":

Just put this into your `init.vim`

```
function! s:undoWrapper()
    let l:before = undotree().seq_cur
    silent! undo
    let l:after = undotree().seq_cur
    if l:before == l:after
        call VSCodeNotify('workbench.action.files.save')
    endif
endfunction

nnoremap u :call <SID>undoWrapper()<CR>
```

Here I created a function which programmatically triggers a save operation when you reach the last undo state. 
The function checks if the undo operation changes the undo sequence number. If the undo sequence number hasn't changed, it means we are already at the oldest change, so we can trigger a file save by vscode, to get rid of the dirty file status.

**Comment by xiyaowong** [comment]
I think this issue has a solution now. Especially after completing PR #2075, the buffer's `&modified` is effective. @ollien I think you might be interested in this :)

**Comment by theol0403** [comment]
@xiyaowong isn't the issue that there is no way to clear the modified flag in the vscode api? The dirty flag is set because undoing changes in neovim is just providing buffer updates but vscode doesn't know that it is undoed.
