### ISSUE TITLE
"Restart" feature?

### ISSUE THREAD

**Issue by muratg** [vscode-neovim/vscode-neovim#250]
I think it would be nice to have a way to "restart" things (nvim instance, reset buffers etc.). 

The issue is when things sometimes go crazy (cursor stuck, or doing each move twice, or movements not mapping to the keys pressed, etc.)  Understandable as this is new, so bugs like these will happen for a while.

"Reloading" VS window doesn't seem to work once it goes into this state. Disabling/enabling/reloading doesn't work either. I have to restart VSCode.

So a simple command I can execute to "re-jiggle" things so that things are in working order would be nice. Until the issues are ironed out.

(Thank you for this amazing plugin! Other one is simply too slow and doesn't look like it'll get fixed)

**Comment by David-Else** [comment]
I find pressing `esc` a few times seems to strangely fix things when input seems frozen here. 

Have you tried `f1 > developer:reload window` to restart without quitting?

**Comment by muratg** [comment]
Reload window doesn't work for me. First thing I tried. Disabling the extension/reloading/enabling it/reloading doesn't work either. 

I'll try the `esc` trick, thanks!

**Comment by sisrfeng** [comment]
every time I modify my init.vim,  I need to reload vscode.  
I bind alt+L to reload.  
Not so cool still

**Comment by X9VoiD** [comment]
I'm still having this problems with default neovim config, and only the c#'s omnisharp as lsp server.

**Comment by zhuoqun-chen** [comment]
> every time I modify my init.vim, I need to reload vscode. I bind alt+L to reload. Not so cool still

Hi, may I ask which action you bind to `alt+L` to reload? I have the same question here that I need to quit vscode and then relaunch it again once my `init.lua` has changed. I'm quite a newbie in `lua` config.

**Comment by sisrfeng** [comment]
> > every time I modify my init.vim, I need to reload vscode. I bind alt+L to reload. Not so cool still
> 
> Hi, may I ask which action you bind to `alt+L` to reload? I have the same question here that I need to quit vscode and then relaunch it again once my `init.lua` has changed. I'm quite a newbie in `lua` config.

{
  "key": "alt+L",
  "command": "workbench.action.reloadWindow"
}

**Comment by xiyaowong** [comment]
Restarting is the last resort to resolve problems. If a problem occurs frequently, please report it
