### ISSUE TITLE
Disable mouse in normal mode

### ISSUE THREAD

**Issue by Adolf-L** [vscode-neovim/vscode-neovim#251]
if I can block the cursor moving, when I am using mouse in vscode.  I use vscode-neovim with local init.vim configuration file. Even I have add the command `:set mouse=` but it doesn't works in vscode. 

if I did wrong somewhere? please help thx :)

**Comment by Adolf-L** [comment]
VSCodeVim/Vim#4405

**Comment by theol0403** [comment]
VSCode is inherently a mouse-based GUI. Adding special code to ignore mouse selection events is going in the wrong direction. 

I don't think there are benefits anyway, because there is no such thing as using the mouse to select text to copy while not changing the cursor.
