### ISSUE TITLE
Select multiple lines in visual mode highlighting incomplete

### ISSUE THREAD

**Issue by rightaway** [vscode-neovim/vscode-neovim#253]
If I select one line in visual mode the whole line highlights as expected. But expanding the selection to include multiple lines makes the highlighting of every line incomplete, not highlighting the first few characters of each line.

**Comment by asvetliakov** [comment]
Are you using tab indents? If so can you try latest version?

**Comment by Dominionized** [comment]
It seems the extension doesn't highlight the first character in empty lines like in Neovim. Also, the cursor position is not highlighted as part of the selection.

![visualmode](https://user-images.githubusercontent.com/5436916/93038620-7bcc0080-f613-11ea-9c24-5f783b843bd0.gif)

![nvim](https://user-images.githubusercontent.com/5436916/93038774-e1b88800-f613-11ea-875c-d5ac3b89a1e3.gif)

**Comment by asvetliakov** [comment]
@Dominionized Not fixable unfortunately
