### ISSUE TITLE
Allow cursor movement commands (e.g., <left>, <right>) in VIM Command Line

### ISSUE THREAD

**Issue by gaylonalfano** [vscode-neovim/vscode-neovim#268]
Hello - Thank you for this great extension! 

I understand that the **VIM Command Line** window has a built-in 1.5 second delay you've added. I have a VIM mapping to help me quickly perform a **search and replace all occurrences** for the word under cursor:  `nnoremap <leader>r yiw:%s/\<<C-r><C-w>\>//g<left><left>`

However, when adjusting/tweaking for this extension, I cannot seem to get any cursor movement commands (i.e., `<left><left>`) to run. I have tried to run subsequent commands using `|`, Vim's `:sleep` command, and even your custom `VSCodeNotify('cursorMove')` functions, etc. No matter my configuration (see below), the best I can achieve is having the command text entered into your Vim Command Line window, `%s/\<foo\>//g`, with my cursor position at the **_very end of the string_**.

Below are my various failed attempts for reference. Any suggestions are greatly appreciated and thanks again for your work!

```# init.vim
" Replace all occurrences of word under cursor with new string using
" ERROR: Can't get VS Code to perform the cursor move <left>...
" <leader>rNewString<CR>
"nnoremap <leader>r yiw:%s/\<<C-r><C-w>\>//g<left><left>
"nnoremap <leader>r yiw:%s/\<<C-r><C-w>\>//g<C-b><C-b>
"nnoremap <leader>r *:%s///g<C-b><C-b>
"nnoremap <leader>r yiw:%s/\<<C-r><C-w>\>//g|<C-u>call VSCodeNotify('cursorMove', { 'to': 'left', 'by': 'character', 'value': 2 })<CR>

" The wildmenu has a builtin 1.5 second timeout delay. 
" Vim has built-in sleep: nnoremap <Leader>ss :set columns=95<CR>:sleep 5m<CR><C-l>
" nnoremap <leader>r yiw:%s/\<<C-r><C-w>\>//g|:sleep 1600m<CR><left><left>  " Doesn't move
"nnoremap <leader>r yiw:%s/\<<C-r><C-w>\>//g|:sleep 2000m<C-b><C-b>
"nnoremap <leader>r yiw:%s/\<<C-r><C-w>\>//g|:sleep 4<C-b><C-b>
"nnoremap <leader>r yiw:%s/\<<C-r><C-w>\>//g|:sleep 2000m<CR><C-u>call VSCodeNotify('cursorMove', { 'to': 'left', 'by': 'character', 'value': 2 })<CR>
"nnoremap <leader>r yiw:%s/\<<C-r><C-w>\>//g|:sleep 2000m|<C-u>call VSCodeNotify('cursorMove', { 'to': 'left', 'by': 'character', 'value': 2 })<CR>
"nnoremap <leader>r *:|:sleep 2000m|%s///g<left><left>
"nnoremap <leader>r *::sleep 2000m|%s///g<left><left>
"nnoremap <leader>r yiw:%s///g|:sleep 4<CR><left><left>
"nnoremap <leader>r yiw:%s///g|:sleep 4<CR><C-b><C-b>
"nnoremap <leader>r yiw:%s//|<left><left>
nnoremap <leader>r yiw:%s/\<<C-r><C-w>\>/|:sleep 2<C-b><C-b>
```

**Comment by vlwkaos** [comment]
https://github.com/asvetliakov/vscode-neovim/blob/28c908ecc11719617050db37ee94f92070715335/src/command_line.ts#L52-L80

Is it possible to manipulate cursor position of vscode popup textfield? (I don't know what it's called), even if it is possible I don't think it is the right solution because then it would be emulating that behavior on vscode front...

**Comment by asvetliakov** [comment]
Why not use `<cword>` here ?

**Comment by vlwkaos** [comment]
<cword> is not the main issue here.  For example, mapping `:s/<cword>//g<left><left>` to a key and using it in vim/nvim will let you type replace right away by filling in the command with `:s/<cword>/<cursor>/g` with cursor position in between second and third slashes. Whereas in vscode neovim, <left> command is ignored when transferred so you are left with `:s/<cword>//g<cursor>`.

**Comment by asvetliakov** [comment]
@vlwkaos thanks, got it. vscode doesn't allow to programatically move the cursor in the current implementation of commandline window. As possible solution you can request a user input from a function, then execute your `s` command through `normal! ` with provided input
