### ISSUE TITLE
Publish to open-vsx / add CI deployments

### ISSUE THREAD

**Issue by james-ingold** [vscode-neovim/vscode-neovim#274]
Hello, 

I was looking to get this extension published to the open-source visual studio code extension repository for use with VSCodium (community-driven, freely-licensed binary distribution of Microsoft’s editor VSCode)
https://open-vsx.org/

https://github.com/eclipse/openvsx/wiki/Publishing-Extensions#how-to-publish-an-extension

I was looking for a CI spot where I could pull request and set up the code where you would just need to add an access token but it doesn't look there is something such as Github Actions or Travis CI to use. I'd be happy to help set up some CI, or I might have missed it but didn't want to step on toes if there is already a process. 

Thanks,
James

**Comment by crash5** [comment]
You can start with github actions like this [create-new-release.yml](https://raw.githubusercontent.com/crash5/vscode-neovim/master/.github/workflows/create-new-release.yml)

**Comment by newzubakhin** [comment]
I would really happy to see **vscode-neovim** in open-vsx repository.

**Comment by justinmk** [comment]
Looks like open-vsx has vscode-neovim now: https://open-vsx.org/extension/asvetliakov/vscode-neovim
