### ISSUE TITLE
bug: arrows don't work for cmdline history navigation 

### ISSUE THREAD

**Issue by kpeters-cbsi** [vscode-neovim/vscode-neovim#288]
I use regexen extensively in vim / neovim. Often I will mess up a regex somehow and need to correct it, and I do that by editing it from my search history (i.e. in vim, hitting "/" then pressing up arrow until I reach the regex I want to edit). How do I do this in vscode-vim? I've been having to spawn vim in a terminal, do the regex stuff, and then exit.

**Comment by chrisjaquet** [comment]
I have the same question and would extend it to command history too.

**Comment by theol0403** [comment]
Yeah, for some reason the arrows don't work in command mode anymore. I tried installing some very old versions of this plugin and still could not get it to work, so I assume an update to VSCode broke it, not this plugin. Trying to manually map the arrow keys don't work either, however, putting this in your keybindings is a mediocre fix:
```
    {
        "command": "vscode-neovim.history-up-cmdline",
        "key": "ctrl-p",
        "when": "neovim.mode == cmdline_normal"
    },
    {
        "command": "vscode-neovim.history-down-cmdline",
        "key": "ctrl-n",
        "when": "neovim.mode == cmdline_normal"
    },
```

**Comment by chasingmaxwell** [comment]
I remember this working for me and I don't think it was too long ago. It no longer does, but that workaround did the trick for now. Thanks @theol0403!

**Comment by kpeters-cbsi** [comment]
That worked for me too. Thanks, @theol0403!

**Comment by genso** [comment]
It works also for me!. Thanks to @theol0403

**Comment by Shatur95** [comment]
@theol0403, thanks!
 @asvetliakov, maybe made this shortcuts be default? In Neovim `<C-p>` and `<C-n`> works for search too.

**Comment by bisho** [comment]
If you could get arrows to work will be ideal. Muscle memory is hard to change. I have seen other vim integrations that even include a drop-down with the history, so moving up/down is easier.

**Comment by asvetliakov** [comment]
VSCode started to disallow to remap `<up>`/`<down>` in quick pick. Blame vscode devs ! 👿  👿  👿

**Comment by uladkasach** [comment]
@asvetliakov  Any thoughts on moving the command line to the VSCode status bar (the bottom bar in the ide)? 

The `VSCodeVim` extension exposes the vim commandline in that bar - it shows what you're typing and allows you to navigate through history with arrow keys due to it. Could resolve this problem

**Comment by theol0403** [comment]
@uladkasach It would be worth considering, and also solve a few other problems regarding quickpick's limitations (and support more bindings). However, the largest drawback is showing completions - any idea how that could be done?

**Comment by micimize** [comment]
@theol0403 VSCodeVim implemented this in https://github.com/VSCodeVim/Vim/pull/2758/files. Some asked for the ability to move it back (https://github.com/VSCodeVim/Vim/issues/2773,  https://github.com/VSCodeVim/Vim/issues/3602) but I'd say `:` opening in quick open is one of the biggest cons transitioning from VSCodeVim to vscode-neovim so far.

Though, I think a really good approach to multiple buffers (#505) might lead to the most optimal, fully-featured command buffer. Maybe something leveraging horizontal splits. `View: Toggle Split Editor In Group` and `View: Toggle Layout of Split Editor in Group` can be used to make "borderless" splits of the same file, and https://github.com/microsoft/vscode/issues/36700#issuecomment-953737831 implies there might be a way to do that using some custom view.

**Comment by theol0403** [comment]
Still not fixed, waiting for 

https://github.com/microsoft/vscode/pull/196899

**Comment by theol0403** [comment]
Fixed by https://github.com/vscode-neovim/vscode-neovim/pull/2001

**Comment by ollien** [comment]
FYI, now that VSCode 1.90 is released, this now works :tada:
