### ISSUE TITLE
Page movements don't affect cursor

### ISSUE THREAD

**Issue by pnotequalnp** [vscode-neovim/vscode-neovim#293]
`<C-d>`, `<C-u>`, `<C-f>`, and `<C-b>` all move the view but not the cursor, which is inconsistent with native Neovim behavior, which is to move the cursor a half/full screen and only adjust the view if necessary.

**Comment by wcauchois** [comment]
Just trying out vscode-neovim since I found VSCodeVim too laggy. I use C-d and C-u all the time, so after playing around a bit this started driving me crazy.

Is there any known workaround until the developers fix this? (And also thank you developers for working on this!)

**Comment by asvetliakov** [comment]
No workarounds. `<C-u>/etc` need to be properly re-implemented at plugin side. PRs welcome! 😄  Personally i think the difference is minor and kind of acceptable, so it's not at top of my priorities.

**Comment by wcauchois** [comment]
Thanks for the response @asvetliakov. I was taking a look at the docs, I wonder if the solution is to change `editorScroll` to `cursorMove` ([vscode docs - built in commands](https://code.visualstudio.com/api/references/commands) - also I stalked the [motion.ts file](https://github.com/VSCodeVim/Vim/blob/d9517680785b926b69d8d65bb1b334ec71cc1f3c/src/actions/motion.ts#L131) in the VSCodeVim repo).

**Comment by asvetliakov** [comment]
yep, `cursorMove` possibly can work here too

**Comment by wcauchois** [comment]
You've gotten a new contributor :) - I think #528 will do the trick but happy to respond to any comments.

This is my first time dev'ing an extension, VS Code makes it pretty slick actually!

**Comment by AleksueiR** [comment]
As a workaround, I tried remap <C-u/d> to simple movements, but that doesn't work in VSCode (works in nvim though). Any ideas why?

```vim
nnoremap <C-d> 20j
nnoremap <C-u> 20k
```

**Comment by AleksueiR** [comment]
> As a workaround, I tried remap <C-u/d> to simple movements, but that doesn't work in VSCode (works in nvim though). Any ideas why?
> 
> ```viml
> nnoremap <C-d> 20j
> nnoremap <C-u> 20k
> ```

Ah, my bad, `<C-d>` and `<C-u>` are default VSCode shortcuts and they take precedence. Adding the following to `keybindings.json` helped:
```json
    { "key": "ctrl+d", "command": "vscode-neovim.send", "args": "<c-d>", "when": "editorTextFocus && neovim.init" },
    { "key": "ctrl+u", "command": "vscode-neovim.send", "args": "<c-u>", "when": "editorTextFocus && neovim.init" },
```

**Comment by kuzy000** [comment]
> Ah, my bad, `<C-d>` and `<C-u>` are default VSCode shortcuts and they take precedence. Adding the following to `keybindings.json` helped:
> 
> ```json
>     { "key": "ctrl+d", "command": "vscode-neovim.send", "args": "<c-d>", "when": "editorTextFocus && neovim.init" },
>     { "key": "ctrl+u", "command": "vscode-neovim.send", "args": "<c-u>", "when": "editorTextFocus && neovim.init" },
> ```

Wow! It actually just works even without adding nnoremaps. I think it should be the default behavior.
