### ISSUE TITLE
q: behaves strangely

### ISSUE THREAD

**Issue by hidjgr** [vscode-neovim/vscode-neovim#294]
I'm not sure what happens but `q:` seems to actually put you in command editing mode but doesn't open a new window or dialog, and can't be exited with `:q` (it can however be exited with \<CR\>)

**Comment by asvetliakov** [comment]
Ex command-line is not supported yet. I'm not sure it will be ever

**Comment by prwang** [comment]
![image](https://user-images.githubusercontent.com/7418905/125222336-62134c80-e2fc-11eb-8711-848166505bfe.png)
Fortunately you can use context menu and paste from system clipboard, which is my 99% use cases of q: in Vim.

**Comment by theol0403** [comment]
Duplicate of #505
