### ISSUE TITLE
Is it possible to configure the command line at the bottom of the window, like vim or Neovim? 

### ISSUE THREAD

**Issue by genso** [vscode-neovim/vscode-neovim#297]
Thank you very much for the plugin! I

Is it possible to configure the command line display using the usual Neovim form, at the bottom instead of the current configuration?. If used on large screens it may be more convenient to display the command and information line in the traditional way of vim or Neovim.

I have another issue, for example, if I want to print in the screen the information of the registers, using the command registers, I don't see any information ... Is it possible to see this information?  Any help?

Thank you very much!

**Comment by hackel** [comment]
I would love to see this work similarly to [Tridactyl](https://github.com/tridactyl/tridactyl), which actually looks quite similar to actual vim in Firefox.  Integrating it in the VSCode status bar is another option, though I prefer a separate pop-up command line at the bottom.

**Comment by theol0403** [comment]
For now, the plugin uses the quickpick for the command line, and there are no plans to move to the statusbar.

**Comment by theol0403** [comment]
Duplicates:

- https://github.com/vscode-neovim/vscode-neovim/issues/2312
- https://github.com/vscode-neovim/vscode-neovim/issues/1130
- https://github.com/vscode-neovim/vscode-neovim/issues/781
- https://github.com/vscode-neovim/vscode-neovim/issues/297

VSCode now supports dragging/moving the command line. 

- https://github.com/microsoft/vscode/issues/17268
- https://github.com/microsoft/vscode/pull/237847

Move it to where you want by dragging or using configure menu.

![Image](https://github.com/user-attachments/assets/66b14e59-1a85-4328-8292-05da1ce03e40)

Move to middle by using `workbench.action.alignQuickInputCenter`
