### ISSUE TITLE
Insert mode: dot command works only for backspace key but not delete key

### ISSUE THREAD

**Issue by horst5000** [vscode-neovim/vscode-neovim#336]
In insert mode the dot repeating only seems to work for deleting characters with the Backspace key, not with the Delete key.

Example, given two lines:
```
  12345 // That’s amazing, I’ve got the same combination on my luggage!
  12345
```
Delete `123` with `back` key starting at character 4 then type `xxx` in first line, apply to second line
```
  xxx45
  xxx45  // result as intended
```
Delete `123` with `del` starting at character 1 then type `xxx`in first line, apply to second line
```
  xxx45
xxx12345  // 123 not deleted
```

**Comment by asvetliakov** [comment]
It's possible to workaround this by using same method as we did with composite escape - bind a custom handler to vscode `<Del>` and hint dot-repeat with delete mode though. But `<Del>` can be slow in this case. I don't see much value here, but reopening - if you really want this put 👍  or leave comment

**Comment by horst5000** [comment]
Thanks for the quick response. Would the performance really be that bad? I think it would be great for the sake of compatibility, and since the number of `<Del>` keystrokes would be rather limited either way I wouldn't expect to much of a performance hit (but that's just and assumption, correct me if I'm wrong).

**Comment by asvetliakov** [comment]
Depends on the project size/installed extensions/etc. That's the old known problem of blocking extension host in vscode by other extensions and producing typing lag.
Also another thing here - storing deletion mode hint will make much worse the dot-repeat handler which is already is a big hack. If neovim will have few more api methods to set characters in a buffer and control of undo points the whole story can be much much better.

**Comment by horst5000** [comment]
So this means that the input lag will also occur when typing normally (but only if typing `<Del>`, right?) and not just when applying dot-repeat? This is of course bad..

**Comment by asvetliakov** [comment]
correct
