### ISSUE TITLE
asvetliakov/vim-easymotion: not moving cursor until after subsequent motion cmd

### ISSUE THREAD

**Issue by thelazydogsback** [vscode-neovim/vscode-neovim#352]
I'm using the latest VsCode and and vscode-neovim and for the moment an init.vim file that's currently empty other than Plug-ing the forked easymotion plugin.

Easymotion is activating, but the cursor does not move (or appears be at an unrelated position) after I select the appropriate labeled letter(s) -- however, something seems to think the position has been reset, because if I then issue any move cmd (h or ;, for example), the cursor will jump to where it was expected to be after the easymotion cmd (plus the relative motion of the subsequent cmd, of course.)

**Comment by asvetliakov** [comment]
Make sure you're not binding easymotion overwin motions

**Comment by thelazydogsback** [comment]
Thanks for the quick reply!
The explicitly mapped cmds didn't seem to have an effect -- same behavior.

**Comment by asvetliakov** [comment]
Hm, very curious, i remember similar problem at development time - the culprit was return prompt which was sent each time for easymotion move, thus blocking the cursor movement. But the extension is looking for it and accepting automatically.

Can you paste your `init.vim` just in case ?

**Comment by thelazydogsback** [comment]
Pretty bare-bones:
```

if exists('g:vscode')
	call plug#begin('~/AppData/Local/nvim/plugged')
		Plug 'asvetliakov/vim-easymotion'
	call plug#end()

	"let mapleader="\"
	"map <Leader> <Plug>(easymotion-prefix)

	let g:EasyMotion_do_mapping = 0 " Disable default mappings
	let g:EasyMotion_smartcase = 1

	nmap <Leader>s <Plug>(easymotion-s)
	map <Leader>j <Plug>(easymotion-j)
	map <Leader>k <Plug>(easymotion-k)
	map <Leader>w <Plug>(easymotion-w)

endif
```

**Comment by asvetliakov** [comment]
hmm, does it work if you set space as leader?
```vim
let mapleader = "\<Space>"
```

**Comment by thelazydogsback** [comment]
It has the same behavior. (Other than being initiated with <Space> of course)

**Comment by asvetliakov** [comment]
After motion, do you have this line in statusbar?
![image](https://user-images.githubusercontent.com/8881674/92423268-d92e0080-f180-11ea-9b0a-1bb7d3f4a06c.png)

**Comment by thelazydogsback** [comment]
Okay -- it's working now. (For the time-being at least.)
On a whim, I disabled the Calva vscode extension, then easymotion started working.
After re-enabling Calva -- now it still seems to work with both enabled!
I'm not sure it's some kind or order-dependent extension setup or what -- but I can't reproduce the problem now even if I enable and disable each extension in different orders.

I'm having other issues w/Calva at random: editor gets really confused on what line I'm on so cursor doesn't nav right, editor cmd lock-ups, and REPL output going (infinitely appending, needing restart) to my code window instead of the REPL editor window, etc -- but that's a whole other story.

**Comment by asvetliakov** [comment]
may be dumb question but have you sourced your init.vim after changes? btw please create separate issue for calva issues

**Comment by thelazydogsback** [comment]
I did a full restart between all changes.

Well, some possible interference is a known issue -- see https://calva.io/vim/. 

> "The VIM Extension and Calva has some friction between them. The alternative VSCode Neovim extension may fare a bit better as it unbinds keystrokes from VS Code while not in insert mode and uses Neovim as a backend"

So "may fare a bit better" is good, but not exactly a promise :)

**Comment by thelazydogsback** [comment]
Also, there was a major change to Calva recently -- the REPL used to me like a regular terminal window -- append-only with history recall, etc.  They changed it so now it's a watched file that is a full editor window -- supposedly the advantage is consistency as in a regular code file of colorizing, formatting, completion, etc., as well as being able to go back and edit something and re-submit it.  But for me this change (which I don't really care about) has caused lots of headaches.

**Comment by asvetliakov** [comment]
If it's seen as neovim editor and causing troubles perhaps i can ignore it

**Comment by thelazydogsback** [comment]
Well, AFAIK, yours in the only vscode extension that uses NeoVim, right?
But you can probably ignore it anyway.  After pounding away for a bit, I always run into issues -- but it's really hard to get a simple repro case, so I'm not sure how you'd approach it anyway. 
If I find a simple repro (or at least one you have a chance at reproducing) I will open a separate item.

**Comment by tlc** [comment]
I don't know what easymotion refers to, but often I see the following:  I'll try to change lines via :<linenumber>, and the cursor/view doesn't move until I do a motion command, j or k.

This condition seems to come and go.  Sometimes it behaves like this for a while.  Other times it doesn't.

**Comment by theol0403** [comment]
The easymotion patch will soon be removed in favor of #868.
