### ISSUE TITLE
C-e and C-y modifications not working

### ISSUE THREAD

**Issue by nwaywood** [vscode-neovim/vscode-neovim#361]
Firstly, thank you so much for this plugin! I just switched from vscode vim plugin and I am already in love!

I have the following lines in my `init.vim` to scroll the viewport faster:

```
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>
```

However I can't get this to work with this plugin.

I have tried with and without the following snippet in `keybindings.json` and neither works:

```
  {
    "key": "ctrl+e",
    "command": "vscode-neovim.send",
    "when": "editorTextFocus && neovim.mode != insert",
    "args": "<C-e>"
  },
  {
    "key": "ctrl+y",
    "command": "vscode-neovim.send",
    "when": "editorTextFocus && neovim.mode != insert",
    "args": "<C-y>"
  },
```

**Comment by theol0403** [comment]
~~This is because when you do `nnoremap <C-e> 3<C-e>` with `nnoremap`, you are bypassing the mapping of `<C-e>` that sends the command to vscode.~~ This would be the case if https://github.com/asvetliakov/vscode-neovim/blob/00d594e0ca7d3c15fe7ca84e52b878d38f735f2c/vim/vscode-scrolling.vim#L28 lines were not commented. 

Here is where it is actually defined:
https://github.com/asvetliakov/vscode-neovim/blob/00d594e0ca7d3c15fe7ca84e52b878d38f735f2c/src/commands_controller.ts#L34

Your best bet is to define your ctrl-e keymap inside vscode keybindings.json to a command that scrolls how much you want.

**Comment by asvetliakov** [comment]
Yep, unfortunately sending scroll commands from neovim produces jitter (at least it did last time when i've checked)

**Comment by nwaywood** [comment]
> It's possible to restore behaviour by disabling default ctrl+e/ctrl+y bindings and using `vscode-neovim.send` command instead and notifying back the extension from neovim. But the extension doesn't support count argument anyway in the handler.

I'm a little confused. Are you saying that it should be possible to do atm or not?

Because I also did try setting

`"vscode-neovim.useCtrlKeysForNormalMode": false,`

while these keybindings were active

```
 {
    "key": "ctrl+e",
    "command": "vscode-neovim.send",
    "when": "editorTextFocus && neovim.mode != insert",
    "args": "<C-e>"
  },
  {
    "key": "ctrl+y",
    "command": "vscode-neovim.send",
    "when": "editorTextFocus && neovim.mode != insert",
    "args": "<C-y>"
  },
```

and that didn't work either

**Comment by asvetliakov** [comment]
@nwaywood Sorry, but it's not possible now 😄 . Scrolling commands are bound in the extension directly that's why neovim `nnoremap` doesn't work here. I'll look if we can change that

**Comment by wenfangdu** [comment]
> I don't think it's possible to define object arguments for a command in vscode keybindings.

@asvetliakov @nwaywood 

It is possible, I'm using these keybindings to scroll up/down multiple lines:

```json
  {
    "key": "alt+p",
    "command": "editorScroll",
    "when": "textInputFocus",
    "args": {
      "to": "up",
      "value": 5,
      "by": "line",
      "revealCursor": true
    }
  },
  {
    "key": "alt+n",
    "command": "editorScroll",
    "when": "textInputFocus",
    "args": {
      "to": "down",
      "value": 5,
      "by": "line",
      "revealCursor": true
    }
  },
```
