### ISSUE TITLE
Hook vscode FocusLost/Gained

### ISSUE THREAD

**Issue by ianzhuo** [vscode-neovim/vscode-neovim#370]
Hi ,
I use setting as below to control IME behavior in nvim-qt.

but only `VimEnter` and `InserLeave` autocmd work in vscode-neovim. 
Is there any solution to solve`VimLeave` , `FocusLost` , `FocusGained` not working issues, thx.
```
function! SetKeyboardEn()
	echom system(stdpath('config')."/im-select.exe 1033")
endfunction
function! SetKeyboardTw()
	echom system(stdpath('config')."/im-select.exe 1028")
endfunction

au VimEnter * call SetKeyboardEn()
au VimLeave * call SetKeyboardTw()
au InsertLeave * call SetKeyboardEn()
au FocusLost * call SetKeyboardTw()
au FocusGained * call SetKeyboardEn()
```

**Comment by asvetliakov** [comment]
>FocusLost , FocusGained not working issues, thx.

Neovim is non GUI backend here so obviously can't receive and lost focus

Although we can hook vscode and call `doautocmd`. Probably should work

>`VimLeave`

Possibly but that's a use case for `VimLeave` with vscode?

**Comment by theol0403** [comment]
With #1532, you will be able to do:

```lua
vscode.on("window_state_changed", function(focused)
  vim.cmd.doautocmd(focused and "FocusGained" or "FocusLost")
end)
```
