### ISSUE TITLE
Ex command auto complete lost '$' sign

### ISSUE THREAD

**Issue by DrakeXiang** [vscode-neovim/vscode-neovim#391]
I was trying to edit vimrc from vscode by using ex command: `:e $MYVIMRC`, if I type this command manually it works, but If I use `tab` or `enter` to autocomplete on `$MYVIMRC`, the actual command entered is `MYVIMRC` and file will not open.

vscode: 1.49.2
os: mac 10.14.6
neovim: 0.5.0 nightly

**Comment by theol0403** [comment]
Will be fixed by #860
