### ISSUE TITLE
[Question] What is the best way to use VS Code's built in refactoring in vscode-neovim ?

### ISSUE THREAD

**Issue by David-Else** [vscode-neovim/vscode-neovim#394]
In normal VS Code you need to select some code to get the lightbulb to appear that tells you what refactoring is available for that code.

In this extension:

- If I enter visual mode and select code then the lightbulb does not appear until I `ctrl+shift p` to transfer the Neovim selection into VS Code
- I can then select 'refactor' in the menu
- If I select more lines of code in visual mode then the selection as far as VS Code is concerned is lost, and I need to `ctrl+shift p` again to get to select refactor

Am I missing some obvious shortcut or easier way to do things? Could visual mode communicate with VS Code and show the lightbulb and allow `ctrl+shift r` as insert mode does for refactoring?

**Comment by Shatur95** [comment]
Just map a shortcut inside your vim that converts Vim selection into VSCode selection and then call the command you need. [Here](https://github.com/asvetliakov/vscode-neovim/blob/f7aad4c3205f9b59762c725243b56bfc2b6d129b/vim/vscode-code-actions.vim#L102) is the example.
You can check out my configuration also if you prefer lua solution ([1](https://github.com/Shatur95/neovim-config/blob/032449ebfad809dfafe8998237aa976afe785c8e/plugin/vscode.vim#L56), [2](https://github.com/Shatur95/neovim-config/blob/master/lua/vscode.lua)).

**Comment by David-Else** [comment]
Thanks for quick reply! With regard to the first example, do I need to copy paste:
```
function! s:openVSCodeCommandsInVisualMode()
    let mode = mode()
    if mode ==# 'V'
        let startLine = line('v')
        let endLine = line('.')
        call VSCodeNotifyRange('workbench.action.showCommands', startLine, endLine, 1)
    else
        let startPos = getpos('v')
        let endPos = getpos('.')
        call VSCodeNotifyRangePos('workbench.action.showCommands', startPos[1], endPos[1], startPos[2], endPos[2] + 1, 1)
    endif
endfunction
```
into my `init.vim` and tell it to run `editor.action.codeAction` instead of `'workbench.action.showCommands'? I am a bit confused. I found https://code.visualstudio.com/updates/v1_20#_keybindings-for-quick-fixes-and-code-actions but not sure how to directly tell it to show the refactoring dialog based on the selection. Is there a list of `workbench.action.xxxx` commands somewhere to reference? Thanks!!

**Comment by Shatur95** [comment]
> into my init.vim and tell it to run editor.action.codeAction instead of 'workbench.action.showCommands?

Yes.

> Is there a list of workbench.action.xxxx commands somewhere to reference? Thanks!!

Yes, just open shortcuts menu in VScode, search for the hotkey and use right-click to copy command identifier.

**Comment by David-Else** [comment]
Cheers!

It works but is clunky. It seems to forget when in visual block mode that other lines are selected after the first run. While many are selected on screen it is only acting on one.

Maybe I am just muddling up what VS Code can offer refactoring for with and without selecting code. It is acting funny somewhere, not sure if it is this plugin or Code itself.

I will forget it for now, many refactors are selectble in normal mode. Maybe someone might find it useful or improve it:

```
function! s:refactorInVisualMode()
    let mode = mode()
    if mode ==# 'V'
        let startLine = line('v')
        let endLine = line('.')
        call VSCodeNotifyRange('editor.action.refactor', startLine, endLine, 1)
    else
        let startPos = getpos('v')
        let endPos = getpos('.')
        call VSCodeNotifyRangePos('editor.action.refactor', startPos[1], endPos[1], startPos[2], endPos[2] + 1, 1)
    endif
endfunction

xnoremap <C-R> <Cmd>call <SID>refactorInVisualMode()<CR>
```

**Comment by theol0403** [comment]
Can use `xnoremap <C-R> <Cmd>call VSCodeNotifyVisual('editor.action.refactor', 1)<CR>`
