### ISSUE TITLE
Extension throws error on case-matched regex comparison, while CL Neovim does not.

### ISSUE THREAD

**Issue by jrpear** [vscode-neovim/vscode-neovim#403]
Basically, vscode-neovim throws an error on the regex `\m\\\@<!\%(\\(\|\\\@<!\\\[\|\$\$\|\$\)` when used in a cased regex comparison (`=~#`), while the CL version of Neovim does not.

## Steps to reproduce:

**Neovim:**

1. Launch your Neovim 0.5+ CLI (`bash -c nvim`)
2. Press `:` to enter command line mode
3. Paste `if '$' =~# '\m\\\@<!\%(\\(\|\\\@<!\\\[\|\$\$\|\$\)' | echo 'true' | else | echo 'false' | endif`
4. Press enter to run
5. Observe output "true"

**VSCode:**

1. Launch a VSCode instance with vscode-neovim installed
2. Open any file (you just need a buffer open)
3. Press `:` to enter command line mode
4. Paste `if '$' =~# '\m\\\@<!\%(\\(\|\\\@<!\\\[\|\$\$\|\$\)' | echo 'true' | else | echo 'false' | endif`
5. Observe error `E54: Unmatched \(`
6. Press enter to run
7. Observe: no printed output

## Expected behavior:
Extension prints the same thing as CL Neovim.

## Actual behavior:
Extension throws error when CL Neovim does not

## Some context for decoding the regex:

This is a regex used by `vimtex` to locate math mode delimiters `$`, `\(`, and `\[`. `pattern.txt` has all the info you need for figuring out what items like `\@<!` (negative lookbehind) do. I tried to simplify the regex, but the error always seems to disappear! Also note that this only happens when doing a cased comparison. Non-cased comparisons and normal searches work fine.

## My setup

My Neovim version is v0.5.0-728-gf6ac37560. I've checked that I'm using the same version for both VSCode and bash. I'm using a WSL Neovim installation and hooked up vscode-neovim to use that installation.

**Comment by theol0403** [comment]
I can no longer reproduce this
