### ISSUE TITLE
Problems with emojis

### ISSUE THREAD

**Issue by Knaackee** [vscode-neovim/vscode-neovim#405]
I stumbled upon a file containing comments with emojis like

    // 💰 Thats a comment

I cant jump to the end of the line.
Pressing `$` brings me to the the second m in com**m**ent.

Any idea on how to fix that?

**Comment by lucasvianav** [comment]
I've also been having that problem. It seems the emoji takes up multiple cursor "positions".

**Comment by eoriont** [comment]
I also had this problem. Trying to skip ahead or back a word with `w` or `b` instead skips to the middle for some reason.

**Comment by kbtz** [comment]
The extension becomes unusable past any multibyte character. Maybe a similar fix to [this one](https://github.com/asvetliakov/vscode-neovim/commit/01992682c526f07597f11bcb5ae1c9d68d98c860) applies.
