### ISSUE TITLE
cmd + z yield weird error

### ISSUE THREAD

**Issue by muhajirdev** [vscode-neovim/vscode-neovim#417]
<img width="607" alt="image" src="https://user-images.githubusercontent.com/12745166/97418399-5c770180-193b-11eb-9a22-f579b85cc156.png">

It says something like `2020-10-28T09:33:02.116Z undefined`

**Comment by dschuessler** [comment]
I get those on a regular basis without any clear path for reproduction. It once even resulted in n endless loop of these popups being generated.

https://user-images.githubusercontent.com/5774545/103438424-4d5e4980-4c33-11eb-995d-2774086db3f1.mov

**Comment by asvetliakov** [comment]
Please enable debug logging and reproduce with it

**Comment by dschuessler** [comment]
![Bildschirmfoto 2021-04-06 um 8 47 15 PM](https://user-images.githubusercontent.com/5774545/113763939-9504dd80-971a-11eb-89b4-450af8c90c49.png)

The endless loop of toasts happened again. I had debug logging enabled to catch some messages but no output was written. Are the debug logs somewhere else?
