### ISSUE TITLE
Use meta keys in normal mode setting

### ISSUE THREAD

**Issue by smackesey** [vscode-neovim/vscode-neovim#421]
Some Vim users make heavy use of `<M-`(alt/meta) mappings. Currently `vscode-neovim` has a setting (`vscode-neovim.useCtrlKeysForNormalMode`) to automatically pass `ctrl-` modified chords through to NeoVim, but not `alt/meta`  modified chords. You have to manually add a key binding for each specific `<M-` chord you want to pass through. It seems to me there should be an analogous setting for passing through alt: `vscode-neovim.useAltKeysForNormalMode`.

**Comment by alefpereira** [comment]
Hello, @smackesey, beyond using some Alt-key maps, I'm used to exit Insert Mode by pressing Alt/Meta Key + Move Key (i.e Alt-j, Alt-k, Alt-f, and so one) and this is not working on VSCode Neovin. I think those problems are related.

**Comment by Shatur95** [comment]
> beyond using some Alt-key maps, I'm used to exit Insert Mode by pressing Alt/Meta Key + Move Key (i.e Alt-j, Alt-k, Alt-f, and so one) and this is not working on VSCode Neovin. I think those problems are related.

This is not an issue, read #463.

**Comment by theol0403** [comment]
Since there are no nvim bindings that use Alt, they are not included by default. You can add them yourself using `vscode-neovim.send` as shown in readme.
