### ISSUE TITLE
[feature request] leave insert mode onFocusChange event

### ISSUE THREAD

**Issue by vdegenne** [vscode-neovim/vscode-neovim#434]
It would be very useful to have a way to leave insert mode on `onFocusChange` (specifically `onWindowChange`).
When I code a web application I often quickly switch from window to window using alt+shift or similar shortcut to check the result and go back to visual studio code for fine tuning the page. Sometimes (a lot of time) I forget that I didn't press escape to leave insert mode before switching the window so I start to press `j` or any other navigation key but because I am still in insertion mode I have `jjjjjjjjjj` that is written.. and because I can't escape the mode and press `u` to undo because the last modification will also get lost, I have to manually remove the unwanted `jjjjjjj` character on the line which is double time a pain in the... hands.

Please if you could implement this option as soon as you can, I am sure many people will also like that.
Or maybe just telling me if you think of a quick adjustment in VSC to allow this effect.

Thanks

**Comment by martin-braun** [comment]
I made the same suggestion over at VsVim when I first started learning Vim. Now returning from Neovim for some benefits of VSCode by using `vscode-neovim` I noticed this issue doesn't bother me anymore and here is why:

I got used to keyboard movements and thus I got used to ctrl+c before attempting the navigation to a different window/buffer. This is pretty doable if you take the time to remap VSCode bindings as well as add custom bindings to pass-through vim keymaps to VSCode via `VSCodeCall` or `VSCodeNotify`.

Still I want to say that this convenience would be useful for those that are still tied to work-flows with a mouse. Even in the optimal keymaps ... VSCode is sometimes more convenient using a mouse.

**Comment by theol0403** [comment]
@martin-braun if you have any keybindings that you think are general enough to include in the extension (including vscode-specific bindings), feel free to PR!

**Comment by martin-braun** [comment]
@theol0403 Well, my nvim-tree mappings are slightly customized (so are my VSCode equivalents) as are my terminal navigations as well, since I use tmux outside of VSCode for that with a different prefix as well. So my bindings are slightly off the norm, but it works the best for me.

What is probably useful in this project are my general window movements `^w ...` as those are original, but still missing by vscode-neovim, but sorely implementing those will be half-baked. You will have the ability to leave the file explorer, but you will not have the ability to enter it.

**Comment by theol0403** [comment]
@martin-braun what about entering the file explorer by modifying the existing c-w bindings to move between ui panes (including explorer) instead of just editor windows? I believe there is a command that does that.

**Comment by martin-braun** [comment]
@theol0403 I was able to move between windows for sure, but I wasn't able to figure out when I'm next to the file explorer and head into it's direction using the `When` field. The file explorer can be on both sides, I think there is no way to have this complexity within VSCode keybindings without custom code.

The major problem is that VSCode treats the file explorer as its own thing, while nvim-tree just uses a buffer, obviously.

**Comment by theol0403** [comment]
@martin-braun thanks for the info. I totally understand if you don't feel like the bindings are cohesive enough. 

I was talking about `workbench.action.navigateDown`, which should let you navigate everywhere, not just editors. See what you think. That might be a good PR to make!

Bindings are https://github.com/vscode-neovim/vscode-neovim/blob/3b70aef9fae9401a88a5a0fec4f68f800c634ab1/package.json#L353

**Comment by martin-braun** [comment]
@theol0403 This is definitely a solution for `navigateLeft` and `navigateRight`. I wouldn't want to enter the terminal windows below the editors this way though, because it would interfere with the tmux-way out of VSCode. I think the user should come up with their own bindings to enter or leave the terminal, what do you think?

To make things work, we also have to edit https://github.com/vscode-neovim/vscode-neovim/blob/3b70aef9fae9401a88a5a0fec4f68f800c634ab1/vim/vscode-window-commands.vim

VSCode bindings also need to feature `<C-Arrow>` and `<C-Letter>` movements for consistency.

**Comment by theol0403** [comment]
Agreed on all those points. Yep, you will need to editor the vim bindings for when the editor is focused, and the vscode bindings for when the editor is not, and arrow/letter movements are both important.

In my experience, when "the user should come up with their own bindings", it creates a lot of reinventing the wheel and ultimately somewhat incoherent bindings. In retrospect, it is better to have an excellent default that covers all usecases.

I don't entirely see the problem with binding `navigateDown` and it leading you to the terminal... is that not a sane and general default? Essentially, it treats the terminal kind of like another buffer.

**Comment by martin-braun** [comment]
@theol0403 

> I don't entirely see the problem with binding `navigateDown` and it leading you to the terminal... is that not a sane and general default? Essentially, it treats the terminal kind of like another buffer.

It depends on the user I guess. I think there are vim plugins that allow to have a terminal like a buffer, but I think a lot of people just use `tmux` for that. In that case, you cannot enter the terminal with window movements, you have to use `tmux` bindings to switch to the terminal.

Personally, I wouldn't want to enter the terminal for this reason, but I can't speak for the general public in that regard.

**Comment by martin-braun** [comment]
@theol0403 By all respect to @vdegenne and it totally different issue, let's continue discussion at #1248. :)

**Comment by theol0403** [comment]
With #1532, you will be able to do:

```lua
vscode.on("window_state_changed", function(focused)
  if not focused then
    vim.api.nvim_input("<ESC>")
  end
end)
```

**Comment by xiyaowong** [comment]
With https://github.com/vscode-neovim/vscode-neovim/pull/1532, `FocusGained/FocusLost` will be triggered normally
```vim
au FocusLost * call nvim_input('<esc>')
```
