### ISSUE TITLE
Can't launch extension from source on WSL

### ISSUE THREAD

**Issue by guyguy2001** [vscode-neovim/vscode-neovim#438]
**Setup:**
Vscode 1.51.1 (Or insiders 1.52)
remote wsl 0.51.4
vscode-neovim: Cloned from master at dc35432
yarn: 1.22.5
npm: 6.14.9

**What Happens:**
When running with either F5 or by clicking on the "launch extension" button, a new VSCode window opens, but the extension isn't loaded (meaning that I don't have the `Neovim` commands in the Ctrl-Shift-P command palette).
This only occurs on wsl - using the same codebase and vscode in windows, the extension runs just fine on the remote development host.
I tried it both when the source code was in windows (accessing it through /mnt/c), and when it was natively in wsl.

I have no idea which logs to attach; ~~I couldn't find errors in any of them.~~ I couldn't find any errors relating to loading the extension in any of them.
Here is my Remote Extension Host log: https://pastebin.pl/view/24146ce4
And here is the Terminal I get when pressing the `Building...` button in the status bar: https://pastebin.com/RKU40Vdv

The Tasks and Extensions logs are empty.

When pausing the debugger, I always get to timers.ts:461 (the first line of processTimers) and async_hooks.js:160 (the first line of emitHook), both in \<node_internals>\internal\timers.js

Replacing the package.json and .vscode folder with those of an extension created with `yo code`, `Typescript Extension`, `yarn`, `webpack` works just fine (I can see the `Hello World` command, which of course doesn't work).

**Comment by flagoon** [comment]
I think this is an issue: https://github.com/asvetliakov/vscode-neovim/issues/147. It's fixed now, but we need to wait for version 0.64 that will include it.

**Comment by asvetliakov** [comment]
That's vscode issue. I don't know if there is such possibility. If someone would be able to figure it out - please drop a note here.

**Comment by guyguy2001** [comment]
@asvetliakov could you elaborate on why? I was able to launch other extensions just fine
