### ISSUE TITLE
Turn off for specific filetypes (draw.io)

### ISSUE THREAD

**Issue by incoggnito** [vscode-neovim/vscode-neovim#439]
Is it possible to turn of neovim on specific filetypes?

**Comment by Shatur95** [comment]
Currently, not.

**Comment by theol0403** [comment]
Should this issue remain open to be addressed in the future? I know it was phrased as a question, but it may as well be a feature request.

Also, implementation may be somewhat related to #250, as they both require some higher-level control of the plugin.
