### ISSUE TITLE
Integrate keyboard-quickfix with vscode-neovim

### ISSUE THREAD

**Issue by David-Else** [vscode-neovim/vscode-neovim#469]
It seems the quick-fix menu uses the standard context menu that has no ability to use anything other than the arrow keys to navigate up and down:

https://github.com/microsoft/vscode/issues/88076

I think it is the same thing with the `ctrl-shift-r` refactor menu too? Anyone have any luck getting `j/k` or `alt-j / alt-k` working in these?

**Comment by asvetliakov** [comment]
As far as i know - no. There was a feature request in vscode repo, but i can't seem to find it.
It's real pain on Win, since even `<C-n>/<C-p>` doesn't work here.

**Comment by David-Else** [comment]
@asvetliakov There is a solution in the https://github.com/PascalSenn/keyboard-quickfix extension:

https://github.com/PascalSenn/keyboard-quickfix/blob/master/src/extension.ts

Thanks to @theol0403 for this info https://github.com/asvetliakov/vscode-neovim/issues/457#issuecomment-752831430
Could you use a modified version of this code to add the capability to vscode-neovim?

**Comment by asvetliakov** [comment]
Why duplicate functionality when you can just install that extension?

**Comment by David-Else** [comment]
@asvetliakov You have a very valid point, but here are a few counter-arguments to consider:

- Integrating the code removes another extension dependency that could become unmaintained or break functionality with other extensions. Every extension installed is a liability to long-term productivity.
- It adds a very important feature that the user will want out of the box, they don't want to install another extension for basic functionality
- The code could be streamlined and the generic extension boilerplate removed eradicating bloat from the universe
- The extra functionality of  `keyboard-quickfix` is ONLY needed for VS Code Vim extensions, so why not have it built right in? You could also add the shortcuts as default, standardizing the use

I don't think VS Code is getting this functionality any time soon based on https://github.com/microsoft/vscode/issues/55111 and similar requests I have read.

I don't know what the best thing to do is really, @theol0403 what do you think?

**Comment by alanmrochadeveloper** [comment]
A workaround for whose can't find a solution > https://github.com/microsoft/vscode/issues/55111#issuecomment-808639067
Remember to set it as you like, as it fits to you, for me alt+f/e/s/d for arrow keys, but vim user can simulate vim shortcuts.

**Comment by theol0403** [comment]
> I don't know what the best thing to do is really, @theol0403 what do you think?

Sorry for the very late reply. I do agree with all your points. I don't have the typescript knowledge to merge the plugins together, but I think if vscode-neovim provides this fuctionality it would be nice. That way, `z=` and `ctrl-.` can be enabled to open the keyboard quicklist by default.

**Comment by jgirardet** [comment]
https://github.com/microsoft/vscode/issues/55111#issuecomment-1237491199
should be marked as resolved ?
