### ISSUE TITLE
Is there a way to map jj to Escape and Save

### ISSUE THREAD

**Issue by fredysan** [vscode-neovim/vscode-neovim#493]
I'd like to replicate this map `inoremap jj <ESC>:w<CR>`

**Comment by asvetliakov** [comment]
Currently not. But i think it would be possible to easily implement this. For all escaping keys though.

I imagine there should be vscode conf option like: `additionalEscapeSequence`, which in you case should be set to `:w<CR>`.
Then need to pass it here, before `${keys}`:
https://github.com/asvetliakov/vscode-neovim/blob/20cba2206f1fd04db4eaccc716b1028f96411194/src/typing_manager.ts#L133

**Comment by bew** [comment]
Why close @xiyaowong, is it possible now?

**Comment by xiyaowong** [comment]
🫠
