### ISSUE TITLE
My cursor is on speed, often leaves VS Code behind.

### ISSUE THREAD

**Issue by trusktr** [vscode-neovim/vscode-neovim#495]
As you may have noticed in some of my recordings, my cursor is :horse_racing: :horse_racing: :horse_racing: :horse_racing: :horse_racing: :shopping_cart:.

I some times move too fast, and VS Code rendering will not be up to date. Or sometimes, VS Code's cursor will have moved further than mine. Maybe this happens once it has been slammed with all the previous movement, and then VS Code handles the input instead of neovim? I think that may be the case, because sometimes in insert mode I'll type some stuff, then ctrl+c and start moving with `j`, but instead I'll see `jjjjjj` inputted into the text.

I think this is also more likely to happen when other things are taking up CPU, so that it slows both VS Code and Neovim down.

I noticed the `Vim` plugin also has the same issue.

**Comment by asvetliakov** [comment]
@trusktr can you try with 0.0.74?

**Comment by jvbianchi** [comment]
I have a similar issue but it happens with `llll` and `hhhhhhhh`, the cursor jump around multiple lines.


https://user-images.githubusercontent.com/13983663/103457554-17769f00-4cdf-11eb-929c-cfc17027f362.mp4

**Comment by asvetliakov** [comment]
@jvbianchi 

Does this fix it for you?
```vim
nnoremap l <Cmd>call VSCodeNotify('cursorMove', { 'to': 'right', 'by': 'character', 'value': v:count ? v:count : 1 })<CR>
nnoremap h <Cmd>call VSCodeNotify('cursorMove', { 'to': 'left', 'by': 'character', 'value': v:count ? v:count : 1 })<CR>
```

**Comment by asvetliakov** [comment]
@jvbianchi
Can you try also build from #500 but without mapping above? Thanks!

@trusktr Same

**Comment by jvbianchi** [comment]
With the mapping it works, but it does not respect the end of the line anymore (goes to the next line when it reaches the end of the line).

**Comment by asvetliakov** [comment]
@jvbianchi @trusktr 
Another attempt - #501 . This is based on above mapping (make sure to remove if you put one), but with the fix for EOL

**Comment by trusktr** [comment]
Haven't had time to try those yet, but today I pressed something like `kkoif` starting in NORMAL, which went up two lines, opened a new line, but instead of placing the `if` characters in the right spot, it did this:

![Screenshot from 2021-01-05 16-28-21](https://user-images.githubusercontent.com/297678/103714403-6f2d3880-4f73-11eb-9463-f9d91d648236.png)

**Comment by asvetliakov** [comment]
Nope, doesn't seem related. Not sure what broke your `if` even

**Comment by trusktr** [comment]
What I experience happens most often when there's lots of system load and VS Code is operating slowly (I only have 8GB RAM, so working at full mem usage and swap space swapping is usually when it happens). The slowness seems to cause races or something, and then text editing gets out of sync, but it always catches up. When VS Code is slow and I'm trying to edit fast, then sometimes the edits don't happen where I expected they would (like I would expect with vim on a slow network). Similar to the movement, the edits happen at the erroneous cursor positions before the cursor lands at the correct spots and I've already inputted the vim commands before things settle.

**Comment by vlwkaos** [comment]
I experienced similar issue. on 0.7x versions. Most noticeable for me is when I type 'o' to open line in normal mode, it enters insert mode further down the next line. Also I have seen what @trustkr is experiencing too sometimes.
