### ISSUE TITLE
[Feature Request] Fix spell checking

### ISSUE THREAD

**Issue by David-Else** [vscode-neovim/vscode-neovim#506]
It would be great to use Neovim spellcheck. You can turn it on with `set spell` and use `[s` `]s` to jump around, but the highlighting is not shown. You can use `z=` to select a word to replace, and it opens in the `vscode-neovim Message` terminal and then doesn't work when prompted to select a number. If it could be made to use a drop-down menu in Code it would be amazing, or even allow input on the terminal when prompted?

If you turn on spelling and use `ggVG` to select all, you get really weird highlighting and if you then `y` yank it doesn't work.

I don't know if this feature is possible, but it would be great.

 In my init I toggle highlighting on and off with:
```
  " toggle spell checking in normal and insert mode
  nnoremap <silent> <F9> :set invspell<cr>
  inoremap <silent> <F9> <C-O>:set invspell<cr>
```

**Comment by asvetliakov** [comment]
For HL i think you can override default `vscode-neovim.highlightGroups.ignoreHighlights` setting. I don't know which group name is being used for spell checking HL though, but you can try to mess around.

Why not use vscode extension for that? i think vim ones would be restricted by internal viewport height (200 rows) for spell checking/displaying error HL while any vscode extension doesn't have such limitation.

**Comment by David-Else** [comment]
Thanks for the highlight tip, but it won't be of use unless the selection menu for replacement spelling works.

I think it would be a waste to use another extension when Neovim has such a great spellcheck built-in. 

Ideally, the suggestions would appear in a code actions list and have a little lightbulb appear, a bit like how spellright works:

![screenshot-context-menu](https://user-images.githubusercontent.com/12832280/103491183-7fc99b80-4e19-11eb-9d4d-a9b7d7ad26f2.png)

At the moment we have:
```
Change "plugin" to:
 1 "plug in"
 2 "plugging"
 3 "puling"
 ... etc ...
199 "gin"
Type number and <Enter> or click with mouse (empty cancels):
```
I have no idea how this would be done, but I am just throwing the idea out there :) Maybe it is impossible or would take far too much work.

**Comment by infinitewhileloop** [comment]
I agree that it would be convenient to use the built-in Vim spell checker.
As a workaround, I use the “Code Spell Checker” extension and these key bindings:

```vim
nnoremap <silent> yos <Cmd>call VSCodeCall('cSpell.toggleEnableSpellChecker')<CR>
nnoremap <silent> [os <Cmd>call VSCodeCall('cSpell.enableForWorkspace')<CR>
nnoremap <silent> ]os <Cmd>call VSCodeCall('cSpell.disableForWorkspace')<CR>
nnoremap <silent> [s <Cmd>call VSCodeCall('cSpell.goToPreviousSpellingIssue')<CR>
nnoremap <silent> ]s <Cmd>call VSCodeCall('cSpell.goToNextSpellingIssue')<CR>
nnoremap <silent> [S <Cmd>call VSCodeCall('cSpell.goToPreviousSpellingIssueAndSuggest')<CR>
nnoremap <silent> ]S <Cmd>call VSCodeCall('cSpell.goToNextSpellingIssueAndSuggest')<CR>
nnoremap <silent> z= <Cmd>call VSCodeCall('cSpell.suggestSpellingCorrections')<CR>
nnoremap <silent> zg <Cmd>call VSCodeCall('cSpell.addWordToUserDictionary')<CR>
nnoremap <silent> zug <Cmd>call VSCodeCall('cSpell.removeWordFromUserDictionary')<CR>
nnoremap <silent> zG <Cmd>call VSCodeCall('cSpell.addIgnoreWordsToWorkspace')<CR>
```
