### ISSUE TITLE
Allow write to send buffer to external program

### ISSUE THREAD

**Issue by jrpear** [vscode-neovim/vscode-neovim#521]
In CL Neovim you can use `:w !command` to send the contents of the current buffer to the stdin of any external program `command`. I'd like to be able to do this in VSCode Neovim.

I'm not sure exactly how this is done, but it could be as easy as checking whether a `:w` command has arguments before modifying it to `:Write`

**Comment by asvetliakov** [comment]
The right path would be add handling here:

https://github.com/asvetliakov/vscode-neovim/blob/532d4b8809f68fd90b9f4c18484a66ec158441d3/vim/vscode-file-commands.vim#L34

**Comment by ollien** [comment]
Should be fixed by #2027

**Comment by justinmk** [comment]
Related: https://github.com/vscode-neovim/vscode-neovim/issues/1260#issuecomment-1637179297

**Comment by theol0403** [comment]
Fixed by https://github.com/vscode-neovim/vscode-neovim/issues/2116
