### ISSUE TITLE
'jk' not working correctly

### ISSUE THREAD

**Issue by HwangTaehyun** [vscode-neovim/vscode-neovim#523]
Thank you for a great extension. l love vim so much.

Using this extension in vscode, I found a bug when I type 'jk' in insert mode, and next, I type 'j' very fast. Then j is typed before going normal mode. And when some text is deleted when typing 'jk' and next typing j fast.

Why does this happen? Thank you for your effort.

https://user-images.githubusercontent.com/42465090/104157031-a7c68980-542d-11eb-8c71-1562f723ec1f.mp4

**Comment by pojntfx** [comment]
Can confirm this (code-server)

**Comment by asvetliakov** [comment]
Related #330

**Comment by mdanics** [comment]
I'm also facing this. On Mac 11.4

**Comment by theol0403** [comment]
Duplicate of #330
