### ISSUE TITLE
Slow insert operations on large files

### ISSUE THREAD

**Issue by Gelio** [vscode-neovim/vscode-neovim#538]
Hey :slightly_smiling_face: I'm loving the extension so far, thanks for maintaining it!

I've noticed some sluggishness when working with large files (11k lines long). Looks like communicating with the underlying neovim instance takes some time.

This can be easily observed when doing the `o` command. First, just after pressing it I can see a new line appear, but my cursor is still in the same place, and only after half a second, or so, does my cursor move into the new line.

https://user-images.githubusercontent.com/889383/105676622-135b2d00-5eeb-11eb-9d4c-f89e65305539.mp4

File I have been using as reference: https://github.com/evanw/esbuild/blob/master/internal/js_parser/js_parser.go

It would be great if the communication was a bit faster, if possible :slightly_smiling_face: I don't notice such problems using the real neovim in the terminal

**Comment by theol0403** [comment]
Hopefully performance will be improved in the future, but closing the issue as we don't need an issue for performance.
