### ISSUE TITLE
Trailing whitespace added when new lines are created is never removed

### ISSUE THREAD

**Issue by n7st** [vscode-neovim/vscode-neovim#539]
Trailing whitespace removal appears to be broken with VSCode 1.52.1 and Neovim 0.5.0. I've tested plugin versions 0.0.77, 0.0.76 and 0.0.73. I'm using Arch Linux and `code-oss`, and could replicate the issue on a fresh install of VSCode on a spare laptop.

For my examples I have the "highlight all whitespace" setting enabled.

Creating a new block, pressing `ESC`, then opening a new line (inside the block) with `o` and pressing `ENTER` multiple (2 or more) times leaves trailing whitespace:

![trailing](https://user-images.githubusercontent.com/2040110/105781118-daae6880-5f69-11eb-9683-d4614cdde3cd.png)

The issue can also be replicated by going to an existing block, pressing `o` and then `ENTER` multiple times.

I would expect the block to look like this:

![notrailing](https://user-images.githubusercontent.com/2040110/105781460-8c4d9980-5f6a-11eb-8520-a8be72ac448c.png)

This issue does not occur when using NeoVim by itself.

Enabling the VSCode "trim trailing whitespace on save" removes the spaces as expected, but trimming existing trailing whitespace automatically makes for messy pull requests.

Please let me know if any more information is required.

**Comment by NelsonAPenn** [comment]
I'm running into the same issue. Could this be caused by the following behavior mentioned in the README?

> When entering the insert mode, the extensions stops listen for keystroke events and delegates typing mode to vscode (no neovim communication is being performed here)
> After pressing escape key from the insert mode, extension sends changes obtained from the insert mode to neovim

The trailing spaces are left in when enter is pressed in insert mode. If the insert is done in VSCode and then communicated to nvim, it could bypass the added functionality nvim provides of clearing the annoying trailing spaces.

**Comment by theol0403** [comment]
Yeah, this is because vscode adds the whitespace and then sends the whole thing to nvim - nvim doesn't see that you just pressed enter twice.

**Comment by schoblaska** [comment]
```lua
vim.api.nvim_create_autocmd({ "InsertLeave" }, {
	pattern = "*",
	command = [[lua require('vscode-neovim').call('editor.action.trimTrailingWhitespace')]],
})
```

I added this autocmd to my Neovim config to get around this issue... unsure if it's a good idea yet or not.
