### ISSUE TITLE
binding "jk" breaks typing Russian 

### ISSUE THREAD

**Issue by slavugan** [vscode-neovim/vscode-neovim#545]
I have binded "gj" for switching to command mode 
` {
        "command": "vscode-neovim.compositeEscape1",
        "key": "g",
        "when": "neovim.mode == insert && editorTextFocus",
        "args": "g"
    },
    {
        "command": "vscode-neovim.compositeEscape2",
        "key": "j",
        "when": "neovim.mode == insert && editorTextFocus",
        "args": "j"
    }
`
and when I'm typing in Russian, instead of "п" or "р" editor types "g" or "j" accordingly.

**Comment by Lopol2010** [comment]
yes please fix this is annoying bug:(

**Comment by eyehol3** [comment]
did you find a solution?

**Comment by slavugan** [comment]
yes, switched back to **vscodevim** :)

**Comment by theol0403** [comment]
Duplicate of #653
