### ISSUE TITLE
Allow EasyMotion to view and jump to text in all visible editors

### ISSUE THREAD

**Issue by andrewschreiber** [vscode-neovim/vscode-neovim#546]
![image](https://user-images.githubusercontent.com/1892071/106554567-827ae780-64d0-11eb-9cd2-f68ba6ba4af4.png)
The EasyMotion integration is fast and enjoyable. Great work! 

### Both editors
Would it be possible for **both editors** in the above photo to be enabled for jumping? This would be really helpful for moving around VSCode.

**Comment by theol0403** [comment]
Unfortunately, this is not possible because nvim only manages one buffer at a time. You could maybe use a vscode plugin like MetaGo for this purpose.
