### ISSUE TITLE
Convert VSCode selection to visual mode selection

### ISSUE THREAD

**Issue by pokey** [vscode-neovim/vscode-neovim#553]
I know there's a way to go from visual mode selection to VSCode selection, but I was wondering if there's any command to go the other direction. I spend most of my time in insert mode, but would like to be able to use things like vim-abolish on my VSCode selection. Having a command to convert a VSCode selection to a visual mode selection would make such a task straightforward

**Comment by robclancy** [comment]
The fact it doesn't do this automatically basically makes this extension unusable for me.

**Comment by yogeshdhamija** [comment]
This may be a duplicate of https://github.com/asvetliakov/vscode-neovim/issues/395 (though I grant that your title is better). 

There is a PR open to (ostensibly) fix it, though it hasn't been merged yet.

**Comment by theol0403** [comment]
Duplicate of #395

**Comment by theol0403** [comment]
Since that issue is closed, no longer a duplicate.
