### ISSUE TITLE
In normal mode, Chinese input methon will cause strange behavior 

### ISSUE THREAD

**Issue by adewalike** [vscode-neovim/vscode-neovim#560]
In normal mode, normal behavior should not impact original text, while in `vscode-neovim` will impact original text. In below image, original text is `We need to “break window for emergency” here.`  cursor is at `f` word. And when type `j` it impact original text. In vim or neovim or vim in vscode don't have impact on original text.
![image](https://user-images.githubusercontent.com/26520465/108826404-34ed2880-75ff-11eb-9767-66453169d70b.png)

**Comment by albert-ying** [comment]
+1... It is basically a disaster each time I forgot to change the input method.

**Comment by evolify** [comment]
+1... any solution ?

**Comment by nbfhscl** [comment]
+1. Seems related to #751 . The indicator shows still in insert mode.

**Comment by nbfhscl** [comment]
This works for me with miscrosoft pinyin input. Need to download im-select.exe manually [here](https://github.com/daipeihust/im-select/raw/master/im-select-win/out/x86/im-select.exe).
`
if exists('g:vscode')
    autocmd InsertLeave * :silent :!C:\\tools\\neovim\\im-select.exe 1033
    autocmd InsertEnter * :silent :!C:\\tools\\neovim\\im-select.exe 2052
else
endif
`

**Comment by theol0403** [comment]
Fixed by #1009
