### ISSUE TITLE
nvim loses keyboard input

### ISSUE THREAD

**Issue by kpeters-cbsi** [vscode-neovim/vscode-neovim#561]
Environment:

VSCode:
* Version: 1.53.2 (user setup)
* Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
* Date: 2021-02-11T11:48:04.245Z
* Electron: 11.2.1
* Chrome: 87.0.4280.141
* Node.js: 12.18.3
* V8: 8.7.220.31-electron.0
* OS: Windows_NT x64 10.0.21318

vscode-neovim: 0.0.78

NVIM v0.5.0-nightly

Behavior:

I was working on a piece of code. I think I entered `:!` when I meant to hit `:1` or something. When I did that, I suddenly lost all keyboard input to the editor window in VSCode. It came back after a few minutes, though. Sorry that this is so vague. Is there a log file somewhere that I can get more information from?

**Comment by gobuki** [comment]
I don't know how to find logs, but I ran into something similar recently. All the sudden Normal mode would be mostly unresponsive; I'd only have access to Input mode and a few other sequences like `u` and `^r`. I isolated unneeded configs in my .vimrc and haven't encountered the issue since. Is this something you've already ruled out?

```
if exists('g:vscode')
    ....
    finish
endif 
```

**Comment by kpeters-cbsi** [comment]
Yes, my `.vimrc` is protected by a `if !exists('g:vscode')` block. In fact, looking at it, there's nothing in there that applies to vim *inside* a vscode context :)

**Comment by RekiDunois** [comment]
Same issue here, but I found that only when a node server was opened, normal mode will loses input.

when input lose, sometimes shows `Applying neovim edits` in the right bottom, like this:

![image](https://user-images.githubusercontent.com/23435534/147401796-ceee7e0b-bd70-4a6b-adff-7a0c1a5f7db8.png)

**Comment by RekiDunois** [comment]
I found that this issue only happen when I open a nextjs program and start `yarn dev`

other react or vue project was fine.

how strange.
