### ISSUE TITLE
EasyMotion display wrong letters

### ISSUE THREAD

**Issue by maxtremblay** [vscode-neovim/vscode-neovim#571]
Hello,

When I try to use EasyMotion in VS Code, it highlights the first character of each word instead of the target characters.

I guess an image is worth a thousand words in this case.

![Screenshot from 2021-03-09 08-10-19](https://user-images.githubusercontent.com/52462375/110475465-ed5ea600-80ae-11eb-82e6-29e46c6c1ccd.png)

In this example, if I type 'h' with the hope to go at the word 'Hello', the cursor move to 'main' instead. I guess 'h' is the character associate to the motion to 'main'.

I also have similar problems with line motion.

The extension works fine in regular neovim. 

![Screenshot from 2021-03-09 08-18-12](https://user-images.githubusercontent.com/52462375/110476494-087de580-80b0-11eb-9dec-f960c148cdec.png)

I am using VS Code 1.53.2 and neovim 0.5.0 and my init.vim is only these few lines

```vim
call plug#begin('$HOME/.config/nvim/plugged')
    Plug 'asvetliakov/vim-easymotion'
call plug#end()

map ml <Plug>(easymotion-bd-jk)
nmap ml <Plug>(easymotion-overwin-line)

map mw <Plug>(easymotion-bd-w)
nmap mw <Plug>(easymotion-overwin-w)
```

**Comment by davelosert** [comment]
I am having this exact issue with the hop plugin.

**Comment by aserowy** [comment]
@davelosert how did you get it even functioning (i teared out my hear, trying to get even a response)

**Comment by davelosert** [comment]
Don't ask me. It sometimes works, someimtes don't. :D 

Installed it with packer like this (lua based config):

```lua
 use {
          'phaazon/hop.nvim',
          as = 'hop',
          config = function()
            -- you can configure Hop the way you like here; see :h hop-config
            require'hop'.setup { keys = 'etovxqpdygfblzhckisuran' }
          end
        }
```

And then used this config:

```lua
vim.api.nvim_set_keymap('n', '<Leader>w', "<cmd>lua require'hop'.hint_words()<cr>", {})
```

But yeah, the result looks like this – so it clearly only highlights already existing letters, but not the actual jump markers:
![Bildschirmfoto 2021-05-06 um 17 39 03](https://user-images.githubusercontent.com/4287128/117326480-f93dcd00-ae91-11eb-9520-6bccb904a891.png)

**Comment by echaya** [comment]
i guess you guys may want to check out https://github.com/ChristianChiarulli/vscode-easymotion. I've been using it for weeks now and seems it is working fine on my end.

**Comment by aserowy** [comment]
Heho,

just a word, the fork is a fork of

![image](https://user-images.githubusercontent.com/8199164/117424731-6305b780-af22-11eb-8684-80d84d018c28.png)

:D

**Comment by echaya** [comment]
right...my bad :)

i rmb i use this fork just to keep vscode-easymotion in a separate folder from the og easymotion folder so i can use the latter in nvim.

**Comment by aserowy** [comment]
yaeh, cool, i didnt even noticed the difference 😃 . I started using hop because of this.

Kind regards,

Alexander

**Comment by killer4639** [comment]
> Hello,
> 
> When I try to use EasyMotion in VS Code, it highlights the first character of each word instead of the target characters.
> 
> I guess an image is worth a thousand words in this case.
> 
> ![Screenshot from 2021-03-09 08-10-19](https://user-images.githubusercontent.com/52462375/110475465-ed5ea600-80ae-11eb-82e6-29e46c6c1ccd.png)
> 
> In this example, if I type 'h' with the hope to go at the word 'Hello', the cursor move to 'main' instead. I guess 'h' is the character associate to the motion to 'main'.
> 
> I also have similar problems with line motion.
> 
> The extension works fine in regular neovim.
> 
> ![Screenshot from 2021-03-09 08-18-12](https://user-images.githubusercontent.com/52462375/110476494-087de580-80b0-11eb-9dec-f960c148cdec.png)
> 
> I am using VS Code 1.53.2 and neovim 0.5.0 and my init.vim is only these few lines
> 
> ```viml
> call plug#begin('$HOME/.config/nvim/plugged')
>     Plug 'asvetliakov/vim-easymotion'
> call plug#end()
> 
> map ml <Plug>(easymotion-bd-jk)
> nmap ml <Plug>(easymotion-overwin-line)
> 
> map mw <Plug>(easymotion-bd-w)
> nmap mw <Plug>(easymotion-overwin-w)
> ```

Change "easymotion-bd-w" to "easymotion-bd-W", it worked for me. In the plugin, some functions are working properly and some are not. 
Some of the functions which are working fine for me are "easymotion-bd-f", "easymotion-bd-fl", "easymotion-s2", "easymotion-bd-W".

**Comment by jeffersonchen-tw** [comment]
Same issue. I had tried using hop, and still get same result.

**Comment by xarthurx** [comment]
Same issue here.

**Comment by theol0403** [comment]
The easymotion patch will soon be removed in favor of #868.
