### ISSUE TITLE
visual mode: gj/gk not working in wrapped lines

### ISSUE THREAD

**Issue by Perry3D** [vscode-neovim/vscode-neovim#576]
This is based on issue #90 but for visual mode instead of normal mode. 
Currently it is not possible to jump over wrapped lines with gj/gk when visual mode is on.

I tried to copy these lines: 
https://github.com/asvetliakov/vscode-neovim/blob/6469c216f30c4bf29d5718f6d3fe99d517a33db0/vim/vscode-motion.vim#L15-L16

and changed them to vnoremap:
```vim
vnoremap gk <Cmd>call VSCodeNotify('cursorMove', { 'to': 'up', 'by': 'wrappedLine', 'value': v:count ? v:count : 1 })<CR> 
vnoremap gj <Cmd>call VSCodeNotify('cursorMove', { 'to': 'down', 'by': 'wrappedLine', 'value': v:count ? v:count : 1 })<CR> 
```

Afterwards the movement works but it doesn't update the selection. Here the cursor is in line 17 but the selection is still stuck in line 18.
![image](https://user-images.githubusercontent.com/986287/111029965-02656d00-8400-11eb-854a-15260ac129d5.png)

I checked the [API](https://code.visualstudio.com/api/references/commands) and there is the `select` argument for cursorMove.
```vim
vnoremap gk <Cmd>call VSCodeNotify('cursorMove', { 'to': 'up', 'by': 'wrappedLine', 'value': v:count ? v:count : 1, 'select': true})<CR>
vnoremap gj <Cmd>call VSCodeNotify('cursorMove', { 'to': 'down', 'by': 'wrappedLine', 'value': v:count ? v:count : 1, 'select': true})<CR
```
But i get an error that the variable `true` is undefined: `emsg: E121: Undefined variable: true`

Any ideas how i can use the `select` argument?

**Comment by guyguy2001** [comment]
From https://devhints.io/vimscript:
> "No booleans. 0 is false, 1 is true."
![image](https://user-images.githubusercontent.com/6932278/111707895-92b31000-884d-11eb-8bb2-bea85d3cbe61.png)
I tried to google around to see if the neovim package for node.js (which is the thing vscode-neovim uses) supports some magic for sending booleans, but I couldn't find anything yet. I'll look further if sending 0 and 1 don't work for you.

**Comment by theol0403** [comment]
Related: #580

**Comment by albert-ying** [comment]
Any update on this? Thank you!

**Comment by theol0403** [comment]
Not a priority, but the problem is that vscode moves the cursor but then does not tell nvim about the new cursor position to extend the visual selection. Either the gj/gk hack could be removed, or there needs to be some code that extends the visual selection.

**Comment by jweickm** [comment]
That's too bad. Would love to see this functionality added into VSCode Neovim.

**Comment by xiyaowong** [comment]
The following code will work, but only in charwise visual mode. There is no plan to add it to the internal default mapping. It is recommended to use vim's native gj/gk

```lua
local function move(d)
  return function()
    -- Only works in charwise visual mode
    if vim.api.nvim_get_mode().mode ~= 'v' then return 'g' .. d end
    require('vscode-neovim').action('cursorMove', {
      args = {
        {
          to = d == 'j' and 'down' or 'up',
          by = 'wrappedLine',
          value = vim.v.count1,
          select = true,
        },
      },
    })
    return '<Ignore>'
  end
end

vim.keymap.set({ 'v' }, 'gj', move('j'), { expr = true })
vim.keymap.set({ 'v' }, 'gk', move('k'), { expr = true })
```

**Comment by januswel** [comment]
The following configurations work in my env.

```vim
vnoremap gk <Cmd>call VSCodeNotify('cursorMove', { 'to': 'up', 'by': 'wrappedLine', 'value': v:count ? v:count : 1})<CR>
vnoremap gj <Cmd>call VSCodeNotify('cursorMove', { 'to': 'down', 'by': 'wrappedLine', 'value': v:count ? v:count : 1})<CR>
```

VSCode: v1.88.0
vscode-neovim: v1.8.1
neovim: v0.9.5

**Comment by januswel** [comment]
Sorry, `VSCodeNotify` is deprecated now
The lua codes from xiyaowong work fine for me

https://github.com/vscode-neovim/vscode-neovim/issues/576#issuecomment-1835799743

This works without charwise visual mode, thanks!!
