### ISSUE TITLE
motion does not work properly in visual mode

### ISSUE THREAD

**Issue by champignoom** [vscode-neovim/vscode-neovim#580]
Steps to reproduce:
1. Open a new file with neovim plugin enabled
2. type `iabc<Esc>yy99p` to insert 100 lines of `abc`
3. type `V`
4. type `M`, or `L`, or `<ctrl-f>`, or `<ctrl-d>`

Expected behavior:
Lines from line 2 to the middle or last line of the screen should be selected.

Actual behavior:
Only line 2 is selected, while the cursor is at the middle or the last line of the screen.

**Comment by ssipos90** [comment]
+1, I use `shift+V` (visual line) with `ctrl+d` or `ctrl+u` for half page selection most of the times.

Only the viewport is moving, not the cursor.

**Comment by theol0403** [comment]
It looks like this is because vscode intercepts these commands and does not update neovim after scrolling. The reason vscode intercepts these commands instead of delegating to neovim is, according to @asvetliakov, "cursor jitter" and other problems.

However, when I disable the interceptions, it actually seems to work alright.

Here is how you can do this:

```json
    {
        "key": "ctrl+d",
        "command": "-vscode-neovim.ctrl-d",
        "when": "editorTextFocus && neovim.ctrlKeysNormal && neovim.init && neovim.mode != 'insert'"
    },
    {
        "key": "ctrl+u",
        "command": "-vscode-neovim.ctrl-u",
        "when": "editorTextFocus && neovim.ctrlKeysNormal && neovim.init && neovim.mode != 'insert'"
    },
    {
        "key": "ctrl+f",
        "command": "-vscode-neovim.ctrl-f",
        "when": "editorTextFocus && neovim.ctrlKeysNormal && neovim.init && neovim.mode != 'insert'"
    },
    {
        "key": "ctrl+b",
        "command": "-vscode-neovim.ctrl-b",
        "when": "editorTextFocus && neovim.ctrlKeysNormal && neovim.init && neovim.mode != 'insert'"
    },
    {
        "command": "vscode-neovim.send",
        "key": "ctrl+d",
        "when": "editorTextFocus && neovim.init && neovim.mode != insert || neovim.recording",
        "args": "<C-D>"
    },
    {
        "command": "vscode-neovim.send",
        "key": "ctrl+u",
        "when": "editorTextFocus && neovim.init && neovim.mode != insert || neovim.recording",
        "args": "<C-U>"
    },
    {
        "command": "vscode-neovim.send",
        "key": "ctrl+f",
        "when": "editorTextFocus && neovim.init && neovim.mode != insert || neovim.recording",
        "args": "<C-F>"
    },
    {
        "command": "vscode-neovim.send",
        "key": "ctrl+b",
        "when": "editorTextFocus && neovim.init && neovim.mode != insert || neovim.recording",
        "args": "<C-B>"
    },
```

Disabling H/M/L is a bit trickier, because it is defined here: https://github.com/asvetliakov/vscode-neovim/blob/ba50a353ee5b188d963be7561803f96a587b733f/vim/vscode-scrolling.vim#L25-L30
 
Adding this to the bottom of my init.vim seems to have solved it:
```vim
  unmap H
  unmap M
  unmap L
```

However, I'm not sure if that works 100% of the time, because it seems like in some cases unmapping does not seem to have an effect (#631). Let me know if it works for you.

**Comment by lars-berger** [comment]
@theol0403 Added the unmappings to H, M, and L like in the snippet above, but encountering some strange behavior.

It's causing the cursor to move to the top/bottom/middle of the _file_ and not the viewport.

**Comment by theol0403** [comment]
Ah, right. It's because with this plugin, the neovim viewport width is set to a really huge number. I'm not sure what side effects syncing the viewport width with vscode would have.

**Comment by theol0403** [comment]
Fixed by #885

**Comment by lifei** [comment]
Is this issue fixed? I can not increase selection by press `<c-fbud>`. latest version `v1.18.19`

**Comment by grimwm** [comment]
> Is this issue fixed? I can not increase selection by press `<c-fbud>`. latest version `v1.18.19`

I concur that this is still broken.

**Comment by ni554n** [comment]
This issue still persists as of `v1.18.22` @theol0403
