### ISSUE TITLE
u does not undo command with count prefix

### ISSUE THREAD

**Issue by champignoom** [vscode-neovim/vscode-neovim#581]
Steps to reproduce:
1. Open a new file with neovim plugin enabled
2. type `9iabc<Enter><Esc>`
3. type `u`

Expected behavior:
The file should be empty.

Actual behavior:
8 lines of `abc` remain.

**Comment by echaya** [comment]
i can repro

**Comment by champignoom** [comment]
Looks like it's fixed.
