### ISSUE TITLE
<C-L> + [ for <Esc>

### ISSUE THREAD

**Issue by MPW1412** [vscode-neovim/vscode-neovim#582]
Hello,

awesome project!

I'm very used to escaping by Control + [ (which is actually Control + Alt Gr + [ on German keyboards).

That doesn't seem to work, is that an issue with the German keyboard settings or could the binding be added manually? I saw in the readme, that you seem to prefer jj. I'm just more used to the default shortcut.

Best,
Matthias

**Comment by Shatur95** [comment]
You should [enable normal mode](https://github.com/asvetliakov/vscode-neovim#normal-mode-control-keys) control keys.

**Comment by MPW1412** [comment]
@Shatur95, they are enabled and they don't work. As I pointed out, this might be a problem with a German keyboard setup.

**Comment by Shatur95** [comment]
You can bind it yourself:

```
            {
                "command": "vscode-neovim.escape",
                "key": "ctrl+[",
                "when": "editorTextFocus && neovim.init"
            },
```

Maybe do you have any conflicts with other shortcuts?

**Comment by MPW1412** [comment]
Doesn't work. VSC seems to have a general issue with the Alt GR key for keybindings. It detects it as normal alt, which is only the left key on German keyboards.

**Comment by jorhett** [comment]
it works for me as an escape sequence, yes @MPW1412
