### ISSUE TITLE
The YankRing plugin/script doesn't work normally

### ISSUE THREAD

**Issue by x-ji** [vscode-neovim/vscode-neovim#583]
Sorry if anybody reported something similar before or if the solution already exists somewhere among the issues. I haven't used raw Vim for a while (been using evil in Emacs) so I might have missed something obvious.

The YankRing (https://github.com/vim-scripts/YankRing.vim) plugin works normally in vim/nvim on my system. I managed to pass through `<C-n>` and `<C-p>` (keys to cycle through yank history) to neovim following the README. However,  in VSCode something weird happens after I press `<C-n>` or `<C-p>` once: The pasted content is indeed changed, but sometimes the cursor jumps to the next line or the previous line, so that subsequent pressings of `<C-n>` or `<C-p>` results in a prompt from YankRing saying that I didn't start from a paste operation. I have to then manually move my cursor up or down by one line in order to be able to resume the cycling. This behavior never happens in nvim.

I don't think it's caused by the original functionalities of `<C-n>` and `<C-p>` since they are unbound first. I also tried to change the bindings to some other key e.g. `<C-g>` but got similar results.

To reproduce:
- Install YankRing.vim and verify that it works in normal nvim by first yanking multiple times and then `p` -> `<C-p>`
- Pass through `<C-n>` and `<C-p>` to neovim with

```
  {
    "key": "ctrl+n",
    "command": "-cursorDown",
    "when": "textInputFocus"
  },
  {
    "key": "ctrl+p",
    "command": "-cursorUp",
    "when": "textInputFocus"
  },
  {
    "command": "vscode-neovim.send",
    "key": "ctrl+p",
    "when": "editorTextFocus && neovim.mode != insert",
    "args": "<C-p>"
  },
  {
    "command": "vscode-neovim.send",
    "key": "ctrl+n",
    "when": "editorTextFocus && neovim.mode != insert",
    "args": "<C-n>"
  }
```

- Try to use YankRing.vim the same way as in neovim. The aforementioned behavior occurs.

Any help would be appreciated. Thanks!

**Comment by samvv** [comment]
Thanks for reporting the issue and another thanks for providing so much clear information. This could be an issue with `vscode-neovim`. I have yet to get a bit more acquainted with the sources, but I can imagine the cursor not being properly synchronized due to the paste operation. I'll look into it.

**Comment by samvv** [comment]
I can confirm this is an issue. The problem is with the 'sometimes'. I'm not able to pinpoint exactly what kind of text is causing this jump.

**Comment by xiyaowong** [comment]
Possible outdated issue.
