### ISSUE TITLE
Filetype detection for notebook cells

### ISSUE THREAD

**Issue by smackesey** [vscode-neovim/vscode-neovim#595]
I can't get filetype detection to work in notebook cells. Notebook cells have a `bufname` that looks like:

    __vscode_neovim__-vscode-notebook-cell:/path/to/notebook.ipynb#ch0000001

But this autocommand isn't getting the job done:

    autocmd BufCreate,BufReadPost,BufNew,BufAdd,BufFilePre,BufFilePost,BufNewFile,BufRead *-vscode-notebook-cell:* set filetype=python

I gather from #115 that this has something to do with the filetype being `nofile`, but that issue claims it's been fixed.

In any case, the reason this matters even with VSCode handling syntax etc is that some plugins in Vim that are still useful in VSCode (like commenting plugins) rely on a correct filetype.

**Comment by xiyaowong** [comment]
```lua
vim.filetype.add({
  pattern = {
    ['.*'] = {
      priority = -math.huge,
      function(_, bufnr)
        local name = vim.api.nvim_buf_get_name(bufnr)
        if name:match('vscode%-notebook%-cell') then return 'python' end
      end,
    },
  },
})
```

NOTE: `['vscode%-notebook%-cell'] = 'python'` works in nvim, but not in vscode
