### ISSUE TITLE
[End of line] - mouse selection skip last character (edge case)

### ISSUE THREAD

**Issue by tbm98** [vscode-neovim/vscode-neovim#602]
I have the same bug with both neovim and vim: [issue from vscodevim](https://github.com/VSCodeVim/Vim/issues/4039)

**Describe the bug**
When in vim 'Normal' mode, if the cursor is on the last character of a line, selecting with with a mouse omits the last character (the one before the newline).

**To Reproduce**

1. Enter 'Normal' mode
2. Navigate to last character of a line of text
3. Select that line with the mouse
4. Last character (before the newline) will not be in the selection

**Screenshots**
![](https://user-images.githubusercontent.com/12128540/64211805-34396300-ce5c-11e9-8c9e-3fe1017c5237.gif)

**Comment by trkoch** [comment]
I have stumbled across this a few times too. A workaround (very cumbersome though) is to double click next to the line.

**Comment by NotSimone** [comment]
> I have stumbled across this a few times too. A workaround (very cumbersome though) is to double click next to the line.

For me I need to triple click next to the line and even then it doesn't select the first character.

**Comment by theol0403** [comment]
Seems to be fixed now.

**Comment by erik-megarad** [comment]
This is still an issue for me

**Comment by markur4** [comment]
I have the same issue (it's driving me insane)

**Comment by xiyaowong** [comment]
Two ways:
1. Click twice on the end position.
![key](https://github.com/vscode-neovim/vscode-neovim/assets/47070852/5c072651-b8c5-44ff-990a-94a28590daac)
2. `:set ve=onemore`
Highly recommended. This option will also resolve other cursor issues, such as "[cursorMove with wrappedLines](https://code.visualstudio.com/api/references/commands#:~:text=cursorMove%20%2D%20Move%20cursor%20to%20a%20logical%20position%20in%20the%20view)".

**Comment by markur4** [comment]
@xiyaowong thanks, but I found the actual bug: Disabling [frame-indent-rainbow](https://marketplace.visualstudio.com/items?itemName=firejump.frame-indent-rainbow).  fixed it. This is a [known issue](https://github.com/firejump/vscode-frame-rainbow/issues/1). 

I'm now using [indent-rainbow](https://marketplace.visualstudio.com/items?itemName=oderwat.indent-rainbow) and it works fine.

**Comment by xiyaowong** [comment]
These two issues are not related

**Comment by twpayne** [comment]
I'm still seeing this issue in May 2024 with VSCode 1.89.1, VSCode Neovim released 2024-05-21, 04:51:37, and NVIM v0.9.5.
