### ISSUE TITLE
Option to stop :%s from jumping around highlighting matches

### ISSUE THREAD

**Issue by wonrax** [vscode-neovim/vscode-neovim#607]
The current behavior with the `:%s` (update: the `global` command too) command is whenever you add/remove character to the search pattern, vscode-neovim tries jumping around to highlight the first match. It makes it really hard when I try to look at the current line I'm on and write search pattern based on it. It'd be useful if there's an option to stay on the current line while doing `:%s`.

**Comment by theol0403** [comment]
https://github.com/vscode-neovim/vscode-neovim/issues/329#issuecomment-694862304:
> Incremental search with / works well for me, but %s/ is really jumpy - it seems to re-search for the first hit every time you type a char.

**Comment by theol0403** [comment]
https://github.com/vscode-neovim/vscode-neovim/issues/329
