### ISSUE TITLE
Invisible visual mode selections

### ISSUE THREAD

**Issue by seflue** [vscode-neovim/vscode-neovim#609]
I run vscode-neovim in combination with WSL2. When I use visual mode, the selection is completely invisible. The text seems to be selected correctly (when I delete or change the - not shown - selection, the expected parts of text gets removed), but I see nothing.
This happens for all kinds of visual mode (character, line, block).

**Comment by sinetoami** [comment]
I'm having a similar issue. When I select a block code or just a line, the selection seems like this:
![2021-05-05-113916_912x429_scrot](https://user-images.githubusercontent.com/16659014/117160620-a4b62700-ad97-11eb-846b-cdddf5c8d2a2.png)

My `init.vim` is empty, without any custom configuration for VSCode. Any solution?

**Comment by davelosert** [comment]
I just had this problem when I was using a theme with base16 in my nvim-configs.
Disabling this for VSCode fixed the issue for me.

**Comment by sinetoami** [comment]
> I just had this problem when I was using a theme with base16 in my nvim-configs.
> Disabling this for VSCode fixed the issue for me.

@davelosert 
I don't have any theme with base16, I think. Could you share the diff in your config with us? I would be glad.

**Comment by davelosert** [comment]
Well its a plugin I installed with Packer.
In my settings, i just dont enable it for VSCode like this:

```lua
if(not vim.g.vscode)
  then
    local base16 = require "base16"
    base16(base16.themes["solarized-dark"], true)
end
```
(it's lua config)

**Comment by sinetoami** [comment]
Interesting. I've test without any configuration and the issue persists. :(

**Comment by chinux23** [comment]
I didn't had this problem before. But somehow when reinstalled remote server and started all over again, I somehow come across this issue. Just upgraded to the latest 0.5.0 nightly and the issue persists.

**Comment by chinux23** [comment]
@adzierzanowski, what version of neovim did you install?

**Comment by chinux23** [comment]
I managed to resolve my issue.

In my local neovim, I had a tree-sitter plugging, which conflicts with vscode when in visual mode. Disabling tree-sttier resolves the visual mode issue for me.

**Comment by milanglacier** [comment]
> I managed to resolve my issue.
> 
> In my local neovim, I had a tree-sitter plugging, which conflicts with vscode when in visual mode. Disabling tree-sttier resolves the visual mode issue for me.

What a sad story! I used tree-sitter not just for highlighting, I used it for text objects and incremental selection, yet another unparalleled features you can only see in neovim.

I found that you can disable the syntax highlight function when `g.vscode` exists to solve the problem. We don't use treesitter's highlight in vscode for sure. I found that the visual selection conflict is resolved while good things retained.

But there simply very obscure that why the default regex highlighting doesn't conflict with vscode but treesitter's highlighting does.

my treesitter config:

```
    highlight = {
        -- `false` will disable the whole extension
        enable = (not vim.g.vscode) and true or false, -- 'pseudo' ternary operator in lua
        additional_vim_regex_highlighting = false,
    },



```

**Comment by theol0403** [comment]
All highlighting stuff should be disabled in nvim
