### ISSUE TITLE
Neovim plugins not working in VSCode

### ISSUE THREAD

**Issue by otterlover24** [vscode-neovim/vscode-neovim#610]
Hi,

Many thanks for the awesome plugin! I am using the Neo Vim plugin on VSCode on Ubuntu 20.04, with Neovim 0.5 installed via AppImage (Neovim Executable Paths: Linux is set to /usr/bin/nvim which symlinks to /home/t/nvim.appimage). Everything appears to be working fine except for which key plugin. When I press space  (which calls up which key in my Neovim instance) in VSCode, I get the message 'whichkey.show failed, args:[] error: command 'whichkey.show' not found'. Any idea what I can do to resolve this issue?

**Comment by otterlover24** [comment]
I realized that the Commentary plugin isn't working either. Here are some of my settings:

VSCode settings.json:
    "vscode-neovim.neovimExecutablePaths.linux": "/usr/bin/nvim",
    "vscode-neovim.neovimInitVimPaths.linux": "$HOME/.config/nvim/init.vim"

Neovim location and version:
 2021-04-20 13:36:32 [t@t-VirtualBox ~/.config/nvim] (main)
$ which nvim
/usr/bin/nvim
 2021-04-20 13:39:02 [t@t-VirtualBox ~/.config/nvim] (main)
$ ls -alh /usr/bin | grep nvim
lrwxrwxrwx  1 root root       21 Mar 19 19:17 nvim -> /home/t/nvim.appimage
 2021-04-20 13:39:34 [t@t-VirtualBox ~/.config/nvim] (main)
$ nvim --version
NVIM v0.5.0-dev+1160-g0f7b6b2ef
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az166-971

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

init.vim:
 2021-04-20 13:39:54 [t@t-VirtualBox ~/.config/nvim] (main)
$ cat init.vim
" Path to python interpreter with pynvim installed
let g:python3_host_prog=expand("/usr/bin/python")

" Disable Coc at startup, manually enable via :CocEnable
let g:coc_start_at_startup=v:false

" Source plugin configurations
source $HOME/.config/nvim/plug-config/coc.vim
source $HOME/.config/nvim/general/settings.vim
source $HOME/.config/nvim/vim-plug/plugins.vim
source $HOME/.config/nvim/keys/mappings.vim
source $HOME/.config/nvim/themes/airline.vim
source $HOME/.config/nvim/keys/which-key.vim
source $HOME/.config/nvim/plug-config/vim-commentary.vim
source $HOME/.config/nvim/plug-config/rnvimr.vim

" VSCode extension
if exists('g:vscode')
        source $HOME/.config/nvim/vscode/settings.vim
        source $HOME/.config/nvim/plug-config/easymotion.vim
        source $HOME/.config/nvim/plug-config/highlightyank.vim

" If started by firenvim, load firenvim.vim.
" Choose different themes depending on whether started by firenvim
elseif exists('g:started_by_firenvim')
        source $HOME/.config/nvim/general/firenvim.vim
        " Prevent leaving buffer
        augroup test | au!
                autocmd BufLeave * throw 'BufLeave not allowed!'
        augroup end
        " Disable modelines
        set nomodeline
        " Prevent secure option on.
        " When on, ":autocmd", shell and write commands are not allowed in
        ".vimrc" and ".exrc" in the current directory and map commands are
        " displayed.
        set secure
        " Don't show tabline
        set showtabline=0
        " Use one colorscheme for browser in firenvim
        colorscheme one
        set bg=light
        " Make tilde for non-existent lines white so that it is less visible on white bg
        highlight EndOfBuffer ctermfg=White ctermbg=NONE
else
        " Use desert colorscheme on terminal
        colorscheme desert
        " Make tilde for non-existent lines black so that it is less visible on dark
        " themes
        highlight EndOfBuffer ctermfg=Black ctermbg=NONE

        " Get rid of ugly gray signcolumn to the left
        set signcolumn=no

        " Make vertical split less visible
        highlight VertSplit cterm=NONE
endif

Any help would be greatly appreciated.

**Comment by theol0403** [comment]
I don't think which-key is a plugin that can be supported by vscode. However, you can try to use https://github.com/VSpaceCode/vscode-which-key, which is quite nice, and can be triggered by neovim:

```vim
nnoremap <space> <Cmd>call VSCodeNotify('whichkey.show')<CR>
```

However, I'm not sure if this is what your problem is. 
Can you see if running the appimage from the terminal has the same problem? It could be that the plugin cannot find your vim files.
