### ISSUE TITLE
Small suggestion for readme.md: How to do EX commands via VSCode hotkey

### ISSUE THREAD

**Issue by SHanded** [vscode-neovim/vscode-neovim#611]
Hello, I got a small suggestion to add to the readme.md - in the same vein as "Enabling jj or jk as escape keys from the insert mode", add a tip on how to remove search highlights with Esc in normal mode until the next search:

> **Removing search highlighing temporarily (until next search)**
>Add the following to your keybindings.json:
    {
        "key": "escape",
        "command": "vscode-neovim.send",
        "when": "neovim.init && editorTextFocus && neovim.mode == 'normal'",
        "args": ":nohls\<Enter\>"
    },

Or maybe even a paragraph about how you can bind EX commands to a VSCode hotkey. I had to spend some time searching how to execute these commands via VSCode bindings - in the end I guessed that sending ":" followed by the command and Enter was the only way to make it work.

**Comment by echaya** [comment]
I had the exact question before and ended up add the following line in init.vim
``` vim
nnoremap <CR> :noh<CR><CR>
```

**Comment by theol0403** [comment]
Yes, this should all be done in init.vim
