### ISSUE TITLE
Setting to open editors in insert mode by default

### ISSUE THREAD

**Issue by pokey** [vscode-neovim/vscode-neovim#613]
Would you be interested in a PR that would add a setting for opening editors in insert mode by default, instead of normal mode? I would think I could just add a check to [this if statement](https://github.com/asvetliakov/vscode-neovim/blob/a4735e901cb154a91bd36643970abf4d953622a3/src/mode_manager.ts#L84-L87).

**Comment by asvetliakov** [comment]
`autocmd WinEnter startinsert` or something like it. Try to search, there were similar questions/requests

**Comment by pokey** [comment]
I'm guessing you're referring to #579.  Unfortunately, that doesn't work for me, because the call to `commands.executeCommand("vscode-neovim.escape")` causes VSCode to lose the current cursor position, which the autocmd doesn't restore.  Is there a solution that allows me to preserve the cursor position?

**Comment by asvetliakov** [comment]
Right. Then an option to disable mode changing on editor change would be appreaciated

**Comment by pokey** [comment]
Great; I'll take a swing!

**Comment by pokey** [comment]
And to confirm, am I on the right track with 

> I would think I could just add a check to [this if statement](https://github.com/asvetliakov/vscode-neovim/blob/a4735e901cb154a91bd36643970abf4d953622a3/src/mode_manager.ts#L84-L87).

Would it be alright if I added a command to toggle the behaviour on and off?  I switch between keyboard and voice coding, and when I'm coding by voice I am mostly in insert mode, and by keyboard mostly normal mode

**Comment by QAston** [comment]
I'm using something linke this in init.vim:

**Comment by trkoch** [comment]
I think there are a number of features which could be useful related to this issue. Happy to create new issues, but first wanted to discuss it here.

1. I noticed the editor stays in insert mode while switching to another application (e.g. <Cmd+Tab>). However, the editor enters normal mode when changing tabs or splits. This seems inconsistent to me. Not sure, but I think I'd prefer it if the editor stayed in insert mode in both scenarios.

2. Sometimes I'd like to disable the bindings completely (including <Esc>), for instance when pairing with a non Vim user, or when in an editing scenario where using the mouse extensively makes sense. VsCodeVim has a setting disableExtension and a command for this. I used to bind the command to a toolbar item I could toggle quickly.

**Comment by trkoch** [comment]
> I'm using something linke this in init.vim:
> 
> ```
> if exists('g:vscode')
>  " start in insert mode
>    au BufEnter * start
> endif
> ```

Thanks. This forces the editor to start in insert mode. However, there is a delay when switching tabs and cursor position is off by one character (if it was on the last column before leaving the tab).

**Comment by QAston** [comment]
Turns out my config workaround causes 642, this needs a better solution
