### ISSUE TITLE
Vim commands mentioned in init.vim has no impact

### ISSUE THREAD

**Issue by mmohdnowfal** [vscode-neovim/vscode-neovim#615]
Vim commands specified in init.vim has no impact in vscode Neo vim editor. 
I am providing the below settings in the init.vim

set colorcolumn=60
set tabstop=8
set softtabstop=4
set shiftwidth=4
set noexpandtab

As shown in the below image, even though the values are visible to the extension, but it doesn't work. 
Here at the bottom you see that colorcolumn is set to 60, but no impact. 
Same applies to other tabs related settings  

<img width="1023" alt="Screenshot 2021-05-06 at 3 38 52 PM" src="https://user-images.githubusercontent.com/15832093/117281393-39488400-ae81-11eb-81d0-7755a138ed52.png">

P.S Opening nvim directly renders the settings as expected

**Comment by BrianZhang1** [comment]
The extension doesn't seem to convert those settings properly, but remaps usually work. In the meantime, maybe changing it directly from vscode will help:

https://stackoverflow.com/questions/29972396/how-can-i-customize-the-tab-to-space-conversion-factor
