### ISSUE TITLE
Support for BSD?

### ISSUE THREAD

**Issue by gregf** [vscode-neovim/vscode-neovim#616]
On BSD there is no way to set the path to the nvim binary. I tried using the Linux box, hoping that might work, but it's still complaining that it doesn't know where the nvim binary is.

On FreeBSD the path is /usr/local/bin/nvim

uname -a

FreeBSD beastie 13.0-RELEASE FreeBSD 13.0-RELEASE #0 releng/13.0-n244733-ea31abc261f: Fri Apr  9 04:24:09 UTC 2021     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64

**Comment by avysk** [comment]
It seems that setting `vscode-neovim.neovimExecutablePaths.freebsd` in `settings.json` helps.
