### ISSUE TITLE
undo corrupts files

### ISSUE THREAD

**Issue by champignoom** [vscode-neovim/vscode-neovim#619]
Open a file, insert/delete some text multiple times, undo multiple times. Then the file gets completely messed up.

Can't reproduce it exactly since I uninstalled the extension immediately when it appeared.
I'm reporting it anyway just in case anyone's still patient enough with it and wants to have it fixed.

**Comment by guyguy2001** [comment]
I believe it's a known issue, that sometimes vscode and neovim can get out of sync, which leads to freezes and corruptions.
A temporary fix is to use Ctrl-Z in insert mode - it uses vscode's own undo stack, which never gets corrupted (I think that this is an incredibly useful technique either way, as it allows you to revert changes you made in edit mode).
