### ISSUE TITLE
mapping enter key <CR> is not working

### ISSUE THREAD

**Issue by BIKA-C** [vscode-neovim/vscode-neovim#621]
The wildfire extension uses enter key `<CR>`  in normal mode and I think it is very convenient. 
Unfortunately, `<CR>`  does not seem to be working in this extension. I tried this to test:
```
map <CR> x
```
It still does the default nvim `<CR>` action, which is jumping to the next line.

**Comment by echaya** [comment]
we may need to block the behavior of CR to move the curve from jumping down from VSCode end, following works on my end:
```vim
nnoremap <silent><CR> :noh<CR><CR>
```

**Comment by echaya** [comment]
actually 
```vim
map <Cr> x
```
works fine on my end when i saved it in .vimrc. but not when i set on-the-fly.

**Comment by theol0403** [comment]
`map <CR> x` works fine for me, both in vimrc and on-the-fly. @BIKA-C are you still experiencing this issue?

**Comment by fecet** [comment]
I have the same issue. `map <CR> x`  really make enter to delete a charater but `map <CR> <Plug>(wildfire-fuel)` did nothing
