### ISSUE TITLE
Insert-mode always stores 0 as column in the changelist

### ISSUE THREAD

**Issue by gertqin** [vscode-neovim/vscode-neovim#625]
After leaving insert-mode the change position is always stored with column set to 0 in the changelist. For example (cursor at ```|```)
```
Hello Worl|d
```
typing ```a!<esc>g;``` will result in
```
|Hello World!
```

It works as expected when text is put at the cursor using ```p```.

**Comment by shellwhale** [comment]
Facing the same issue

**Comment by theol0403** [comment]
Probably from dot-repeat hack.

**Comment by xiyaowong** [comment]
See https://github.com/neovim/neovim/issues/28618

**Comment by xiyaowong** [comment]
Nothing can be done about this issue

**Comment by shellwhale** [comment]
> Nothing can be done about this issue

Why is that?

**Comment by xiyaowong** [comment]
https://github.com/vscode-neovim/vscode-neovim/issues/625?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDE4ODE2ODk0MjA6NDcwNzA4NTI%3D&notifications_query=is%3Aunread#issuecomment-2092521993

**Comment by xiyaowong** [comment]
@shellwhale https://github.com/vscode-neovim/vscode-neovim/issues/625#issuecomment-2092521993

**Comment by shellwhale** [comment]
> @shellwhale [#625 (comment)](https://github.com/vscode-neovim/vscode-neovim/issues/625#issuecomment-2092521993)

Yes, I saw that but can't it be fixed once a fix comes for neovim?

**Comment by xiyaowong** [comment]
What is the problem? You can subscribe to changes in that issue
