### ISSUE TITLE
easymotion-sn search jumping to incorrect location in vscode

### ISSUE THREAD

**Issue by jkevinruiz** [vscode-neovim/vscode-neovim#629]
I have `map / <Plug>(easymotion-sn)` on my init.vim setup, which I use for search instead of the default vim forward search.

Using the search in neovim, it works as expected, but with vscode, its jumping to incorrect locations.

In the gif below, I'm trying to search for a word and move to the first result, but it would always jump the cursor to the beginning of the line below it. Instead of the expected action of moving the cursor to the beginning of the word.

![2021-05-08 00-25-26](https://user-images.githubusercontent.com/26445418/117529517-35a62180-af95-11eb-8174-04da41b6da9f.gif)

**Comment by echaya** [comment]
i can repo. also note that Tab and Shift-Tab are not working properly in easymotion-sn search mode.

**Comment by DominickVale** [comment]
I'm having the same issues as well

**Comment by qinxiao1990** [comment]
I'm having the same issue and searching twice does fix it... Any idea why? Thanks!

**Comment by theol0403** [comment]
The easymotion patch will soon be removed in favor of #868.
