### ISSUE TITLE
adding an option to suppress ma, mi, mA, mI in visual mode

### ISSUE THREAD

**Issue by echaya** [vscode-neovim/vscode-neovim#631]
Hi, I'd switch-off ma, mi, mA, mI in visual mode so when i press m in visual mode there will produce no delay. Any suggestion is appreciated.

In the readme, it says both are `optional` so i trust there is way to turn it off. thanks!

(Optional) Visual line mode
(Optional) Visual block mode

**Comment by echaya** [comment]
now i have to manually comment out the following from vscode-insert.vim

``` vim
xnoremap ma <Cmd>call <SID>vscodePrepareMultipleCursors(1, 1)<CR>
xnoremap mi <Cmd>call <SID>vscodePrepareMultipleCursors(0, 1)<CR>
xnoremap mA <Cmd>call <SID>vscodePrepareMultipleCursors(1, 0)<CR>
xnoremap mI <Cmd>call <SID>vscodePrepareMultipleCursors(0, 0)<CR>
```

**Comment by theol0403** [comment]
Humm, the "optional" is a little misleading. However, can you use something like `xunmap ma` etc in your `init.vim` to achieve the desired result?

**Comment by theol0403** [comment]
Humm, I don't see how unmapping or commenting have any difference, are you sure there is a delay, or that the bindings are actually disabled? Strange

**Comment by echaya** [comment]
let me test again :)

**Comment by echaya** [comment]
thanks for looking into this. Im suing vim-cutlass, and mapped m to d per below:

```vim
xnoremap m d

if exists('g:vscode')

    call plug#begin('~/AppData/Local/nvim/plugged')

        Plug 'svermeulen/vim-cutlass'   "this plug-in is the reason why i want to use m key alone in visual mode

    call plug#end()

    xunmap ma 
    xunmap mi 
    xunmap mA 
    xunmap mI 
   "... more config here

else
```

**Comment by theol0403** [comment]
Alright, so I was able to reproduce, but that was because the cursor bindings were still enabled, even with the unmap in init.vim. However, running the unmaps manually in the commandline solved the problem. 

My theory is that the vscode mappings are loaded after init.vim, so the unmaps do nothing. I'm not sure how to solve this. One option would be to unmap in some autocommand hook. But I feel like there should be a better way.

**Comment by echaya** [comment]
easiest option imo is to have something like  `vscode_multi_cursor_on ` variable and can be switched off by defining it in init.vim so to make it 'optional'.

but i'll keep commenting those lines out for now.
