### ISSUE TITLE
[InsertMode] ctrl+g does not work as expected (undo word by word)

### ISSUE THREAD

**Issue by searleser97** [vscode-neovim/vscode-neovim#636]
The following mapping adds the ability to undo word by word:

`inoremap <Space> <Space><C-g>u`

when using it with this extension it just doesn't work (it does nothing)

The expected behavior is that when I press "u" in normal mode it should undo word by word instead of the whole line.

**Comment by echaya** [comment]
per the README.md:

***First-class VSCode insert mode. The plugin unbinds self from the type event in the insert mode, so no typing lag and freezing anymore when long completion popup appears.***

Most of `imap` wont work. So this is WAD.

**Comment by theol0403** [comment]
Yeah, you cannot use vim bindings in insert mode, unfortunately.

Related: #84, #585
