### ISSUE TITLE
Focus jumps to latest position when 2 tabs are open side by side

### ISSUE THREAD

**Issue by QAston** [vscode-neovim/vscode-neovim#642]
Same issue and behaviour as #427 but for editors opened in side-by-side tabs

**Comment by QAston** [comment]
Turns out this is caused by my config workaround for #613

**Comment by QAston** [comment]
Actually, the issue is due to the fact that the plugin updates the cursor position from neovim in insert mode, which it shouldn't do.

**Comment by justinmk** [comment]
> the plugin updates the cursor position from neovim in insert mode, which it shouldn't do.

Sounds like something that should be fixed. Adding new options (https://github.com/vscode-neovim/vscode-neovim/pull/716) doesn't fix that root cause.

**Comment by QAston** [comment]
There are reason why the plugin doesn't post updates for insert mode - mainly performance and having a consistent method of keeping things in sync. Lack of consistency gives you stuff like this.

**Comment by theol0403** [comment]
Duplicate of https://github.com/vscode-neovim/vscode-neovim/issues/776
