### ISSUE TITLE
Composite Escape breaks macro recording

### ISSUE THREAD

**Issue by mikatpt** [vscode-neovim/vscode-neovim#644]
Not sure if I'm doing something wrong, or misinterpreting. Hope somebody has some insight!

init.vim settings:
```
xmap gc <Plug>VSCodeCommentary
nmap gc <Plug>VSCodeCommentary
omap gc <Plug>VSCodeCommentary
nmap gcc <Plug>VSCodeCommentary
set clipboard=unnamedplus
:nnoremap <Space> :noh<CR>  
```
In VS Code, I'm using the suggested composite escape keybindings for `jj` and `jk`.

System: MacBook Pro, Big Sur 11.3

Steps to reproduce:
1. Open an editor and in normal mode, type `qdi`
2. Type any sequence including j or k
3. As soon as any letter besides j or k is typed, all j's and k's are erased.

**Comment by theol0403** [comment]
Can reproduce

**Comment by theol0403** [comment]
Related: #563

**Comment by BlueDrink9** [comment]
After switching to the composite in  #886, I can no longer reproduce this issue. IMO #886 should be considered an official workaround and this can be closed. No reason to be using the old composite behaviour that I can see nowe

**Comment by BlueDrink9** [comment]
After switching to the composite in  #886, I can no longer reproduce this issue. IMO #886 should be considered an official workaround and this can be closed. No reason to be using the old composite behaviour that I can see now
