### ISSUE TITLE
Expression Register

### ISSUE THREAD

**Issue by yonchicy** [vscode-neovim/vscode-neovim#652]
Many thanks for this awesome extension .

When I wanted to use a variable's value by expression register, it reported a problem.

Given to that expression register is not fully supported, I used the way below, which still didn't work. But it works in NeoVim.
```shell
:let a=1
"=a
i
<^R>=
```
I don't know why

**Comment by theol0403** [comment]
For what it's worth, `"=` in normal mode works. I'm not sure why ctrl-r = does not work.

**Comment by theol0403** [comment]
I think this is a neovim implementation: https://neovim.io/doc/user/eval.html#getreg()
> getreg('=') returns the last evaluated value of the expression register.
I'm not sure how you would change it so that it prompts you for an expression entry.

**Comment by theol0403** [comment]
Another meh workaround:

Make `ctrl-o` in insert mode work, either by doing https://github.com/asvetliakov/vscode-neovim/issues/181#issuecomment-585264621 or merging https://github.com/asvetliakov/vscode-neovim/pull/585. Then you can do `<C-o>"=<expression>p`, if staying in insert mode is favorable.

**Comment by theol0403** [comment]
Related lines:

https://github.com/asvetliakov/vscode-neovim/blob/8ee0c96a0e42525b898f85c29c38639a44ecdfa5/src/commands_controller.ts#L20
https://github.com/asvetliakov/vscode-neovim/blob/8ee0c96a0e42525b898f85c29c38639a44ecdfa5/src/commands_controller.ts#L95-L106
https://github.com/asvetliakov/vscode-neovim/blob/8ee0c96a0e42525b898f85c29c38639a44ecdfa5/vim/vscode-neovim.vim#L97-L100
