### ISSUE TITLE
JK keybinding breaks russian keyboard layout

### ISSUE THREAD

**Issue by letzabelin** [vscode-neovim/vscode-neovim#653]
**Describe the bug**
If keybinding for `escape` on `jj` or `jk` exist, russian keyboard layout breaks. 

**Keybindings**
```
{
    "command": "vscode-neovim.compositeEscape1",
    "key": "j",
    "when": "neovim.mode == insert && editorTextFocus",
    "args": "j"
},
{
    "command": "vscode-neovim.compositeEscape2",
    "key": "k",
    "when": "neovim.mode == insert && editorTextFocus",
    "args": "k"
}
```

**To Reproduce**
1. Create file
2. Change language to russian or any other
3. Type any characters and then type `jk`. You will see next (for example): фываjk

![admin-1622811614753](https://user-images.githubusercontent.com/40225759/120805488-8ab26480-c54e-11eb-80f9-7d554d9670b9.gif)

English characters remain active, when russian language is on. Only `j` and `k` shows.
If I disable `jk` keybinding everything is ok

**Environment:**

- Extension version: v0.0.81
- VSCode version: 1.56.2
- OS: ubuntu 20.04.2

**Comment by asvetliakov** [comment]
It inserts whatever you've declared as ` "args": `.Try
```json
{
    "command": "vscode-neovim.compositeEscape1",
    "key": "j",
    "when": "neovim.mode == insert && editorTextFocus",
    "args": "о"
},
{
    "command": "vscode-neovim.compositeEscape2",
    "key": "k",
    "when": "neovim.mode == insert && editorTextFocus",
    "args": "л"
}
```

I'd also try to create 2 set of bindings (key/args)  - one for english `j/j` and another for russian `о/о`. If neither works unfortunately it can't be supported and i suggest to get used to normal escape key instead.

**Comment by theol0403** [comment]
Related: #389

**Comment by olejech** [comment]
Any solutions?

**Comment by theol0403** [comment]
Is the solution mentioned above not enough?

**Comment by olejech** [comment]
> Is the solution mentioned above not enough?

Okay, I use '[['. It's work perfect

**Comment by IlyaGarazha** [comment]
> 
Not an elegant solution, but maybe someone will appreciate it.
`    {
    "command": "vscode-neovim.compositeEscape1",
    "key": "j",
    "when": "neovim.mode == insert && editorTextFocus",
    "args": "j"
    },
    {
    "command": "type",
    "key": "ctrl+j",
    "when": "neovim.mode == insert && editorTextFocus",
    "args": { "text": "о" },
    },`
