### ISSUE TITLE
Can't repeat vim-sneak commands with vim-repeat

### ISSUE THREAD

**Issue by PatrickWulfe** [vscode-neovim/vscode-neovim#665]
When using vim-sneak and vim-repeat in VSCode Neovim, vim-sneak works as expected, but when I try to repeat a command like "cz.d", it will let me change up to the ".d", but when I try to repeat the command elsewhere, vim-repeat ends up not deleting any characters and will either paste in a space or a new line.

I tried disabling everything but these two plugins in both nvim and vscode, including all vscode extensions, and it works as expected in nvim, but works as listed above in VSCode.

I'm on Windows, VSCode v. 1.57.0 and neovim 0.5.0=dev+1381-gb3e3ab056.

**Comment by trkoch** [comment]
Strange. vim-sneak works fine for me with vim-repeat.

**Comment by seriiserii825** [comment]
> When using vim-sneak and vim-repeat in VSCode Neovim, vim-sneak works as expected, but when I try to repeat a command like "cz.d", it will let me change up to the ".d", but when I try to repeat the command elsewhere, vim-repeat ends up not deleting any characters and will either paste in a space or a new line.
> 
> I tried disabling everything but these two plugins in both nvim and vscode, including all vscode extensions, and it works as expected in nvim, but works as listed above in VSCode.
> 
> I'm on Windows, VSCode v. 1.57.0 and neovim 0.5.0=dev+1381-gb3e3ab056.

Hi, how you install vim-sneak in vscode?
