### ISSUE TITLE
{count}gt command not jumping to correct tab

### ISSUE THREAD

**Issue by ZackPlauche** [vscode-neovim/vscode-neovim#670]
When you use "5gt" for example and you have 5 tabs open, the last tab should open.

If you use 1gt, it should go to the first tab. If you say 3gt, it should go to the third.

Currently, if I press any count and gt, it acts as if I'm pressing gt 5 (next tab) times instead of jumping to the correct tab, it also wraps to the first tab. 

vscode version: 1.57.0
vscode neovim version: v0.0.82

**Comment by Jeremalloch** [comment]
I also have this issue.

**Comment by yanshay** [comment]
Same here
