### ISSUE TITLE
EasyMotion is slow "Applying neovim edits"

### ISSUE THREAD

**Issue by csp-stu** [vscode-neovim/vscode-neovim#674]
When using [easymotion](https://github.com/easymotion/vim-easymotion) plugin, the editor is slow to respond (up to 30seconds) to overlay the target characters and move the cursor. During this time, an 'Applying neovim edits' popup sometimes shows. When running neovim as normal outside of vscode, easymotion is super quick. 

Is there anything I can do to try and diagnose the issue further?

**Comment by spectrius** [comment]
Use this https://github.com/ChristianChiarulli/vscode-easymotion, much smoother

**Comment by csp-stu** [comment]
Thanks, looks promising. For anyone else finding this, you need to install both easymotion plugins in Vim and conditionally load one if you're in neovim or vscode: 
https://github.com/asvetliakov/vscode-neovim/issues/415#issuecomment-715533865 

```
function! Cond(Cond, ...)
  let opts = get(a:000, 0, {})
  return a:Cond ? opts : extend(opts, { 'on': [], 'for': [] })
endfunction

" inside plug#begin:
Plug 'easymotion/vim-easymotion', Cond(!exists('g:vscode'))
Plug 'asvetliakov/vim-easymotion', Cond(exists('g:vscode'), { 'as': 'vsc-easymotion' })
```

**Comment by xarthurx** [comment]
> Use this https://github.com/ChristianChiarulli/vscode-easymotion, much smoother

The two are even, what is the difference?

**Comment by theol0403** [comment]
The easymotion patch will soon be removed in favor of #868.
