### ISSUE TITLE
Pressing enter in insert mode while recording a macro does not insert a carriage return, but moves the cursor instead.

### ISSUE THREAD

**Issue by luiz00martins** [vscode-neovim/vscode-neovim#686]
Steps to reproduce
----
 - Press `qa` to start recording a macro
 - Press `i` to enter insert mode
 - Press enter

The expected behaviour is for a carriage return to be inserted, however what happens is that the cursor moves.

Details
---
The cursor seems to jump 2 lines down and 1 column behind on every odd press, and 1 column ahead (in the same line, it doesn't jump to the next line if the current is empty) on every even press.

Oddly, it seems to "remember" where to jump. That is, being on line 28 and pressing `<cr>` jumps to line 30 (behaviour on odd press), and even if you *manually click* in another line, say 10, it'll will go back to line 30 when pressing `<cr>` again, and only then it'll move one column ahead (behaviour on even press).

If you type after a jump, it always starts after the last column you typed on. AKA, it always "continues" column-wise. So, typing 4 "a"s, pressing `<cr>`, then typing "a" again will always put it in the 5th column in the line (see examples below). This also "remembers" where it was, so clicking on another line to move the cursor and typing "a" would still put it (and the cursor) on the 5th column of the last line you were.

If that wasn't weird enough, typing something after an odd jump places the text one line behind, while typing after an even jump places it in the same line.

Debugging Examples
----
These will hopefully help with debugging. The cursor starts behind first character in insert mode (with a macro recording). 

This is the original text:
```
bbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
```

Pressing `<cr>` results in a jump 2 lines down and 1 column behind, then pressing `-` results in an "-" being placed 1 line behind, in the column following the last one. Repeatedly pressing `<cr>-` results in:
```
bbbbbbbbbbbbbbbbbb
b-bbbbbbbbbbbbbbbb
bb-bbbbbbbbbbbbbbb
bbb-bbbbbbbbbbbbbb
bbbb-bbbbbbbbbbbbb
bbbbb-bbbbbbbbbbbb
bbbbbb-bbbbbbbbbbb
bbbbbbb-bbbbbbbbbb
bbbbbbbb-bbbbbbbbb
bbbbbbbbb-bbbbbbbb
bbbbbbbbbb-bbbbbbb
bbbbbbbbbbb-bbbbbb
bbbbbbbbbbbb-bbbbb
bbbbbbbbbbbbb-bbbb
bbbbbbbbbbbbbb-bbb
bbbbbbbbbbbbbbb-bb
bbbbbbbbbbbbbbbb-b
```

Pressing `<cr>` results in a jump 2 lines down and 1 column behind, pressing `<cr>` again jumps 1 column ahead, then pressing `-` results in an "-" being placed on the same line, in the column following the last one. Repeatedly pressing `<cr><cr>-` results in:

```
bbbbbbbbbbbbbbbbbb
b-bbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bb-bbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbb-bbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbb-bbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbb-bbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbb-bbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbbb-bbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbbbb-bbbbbbbbbb
```

This example shows the "column-wise continuing" behaviour. This is the result of pressing `<cr>` followed by `-`, but increasing the number of times each are pressed on every step:
```
bbbbbbbbbbbbbbbbbb
b-bbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bb--bbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbb---bbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbbb----bbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbbbb
bbbbbbbbbbb-----bbbbbbb
```

As you can see, it "continues" from the last line. 

It's important to note that even if you click on a different line with the mouse to move the cursor, in any step of the way, it still jumps and types in the exact same lines in the text. Even spam-clicking different lines results in the exact same texts shown above.

----

I have disabled all of my VsCode extensions and NeoVim plugins, and the problem still persists. If any debugging info is needed, feel free to ask for it.

**Comment by theol0403** [comment]
Thanks for the detailed report! I cannot reproduce this issue. Can you make sure that you have nothing in your keybindings.json? Do you have latest neovim version?

**Comment by luiz00martins** [comment]
I'm currently using the nightly version of neovim `v0.6.0-dev+43-g02bf251bb`. This is my `keybindings.json`:

```
// Place your key bindings in this file to override the defaultsauto[]
[
	{
		"key": "f1",
		"command": "-workbench.action.showCommands"
	},
	{
		"key": "ctrl+s",
		"command": "-workbench.action.files.save"
	}
]
```

I've also just changed my distro and the problem remains despite the OS, VsCode, and neovim being fresh installs. On the other hand, my VsCode configs were synced, and my `init.vim` came with me, so the problem might be in one of those. However, I have no clue what that problem could be.
