### ISSUE TITLE
shift + [ to skip blocks of code doesnt work as intended 

### ISSUE THREAD

**Issue by default-303** [vscode-neovim/vscode-neovim#687]
Hey, I recently started using the nevim extension instead of the vim extension. I noticed that when i press `shift` + `[`or `shift` + `]` to skip block of code seperated by a new line, the extension ignores the new line and goes to some other newline in the same direction.
Like for instance - 
```
                                   //3 . cursor ends up here when i press shift + [
print('neovim')
                                    //2 .target line to reach when i press shift + [
print('vscode')
                                    // 1. cursor here
```
I dont see any pattern on how many blocks it skips for now. 

Initially i thought, something in my neovim config is screwing stuff up, and removed my neovim config path from the settings.json but that doesnt seem to fix the issue.

**Comment by theol0403** [comment]
It's probably still an issue in your config, I think that if there is nothing in your neovim config path, it defaults to init.vim.

**Comment by default-303** [comment]
hey, I tried it with an empty vim config and can confirm i still face the same issue.

**Comment by vlwkaos** [comment]
Is the line in between actually empty?

**Comment by default-303** [comment]
ooh god. I added `"editor.renderWhitespace":"all" `in settings.json and voila!! We have are culprit. Some 'empty' lies are filled with `tab` whitespace which i assume is becuz of the auto indent in the editor. I did some more testing and turns out `enter` works fine (i.e doesnt leave any whitespace) but when i do `o` from normal mode and press `enter` again, the indenting seems to persist. 
Like so , 
```
1. <code>                          //pressing o from normal mode
2.------------------------          //whitespace
3.                                       //cursor here after pressing enter again
```

How do i fix this ?? Any ideas ?

**Comment by vlwkaos** [comment]
Probably should use a formatter or linter to automatically remove indent(or any other white-spaces) on an empty line.

**Comment by default-303** [comment]
hmm, i've installed prettier and tried other inbuild options, but they all format on save(unless stated otherwise). I'm i the only one facing this ? How come there are is not proper guide ?

**Comment by cursoras** [comment]
@default-303 did you manage to fix it?

**Comment by default-303** [comment]
@cursoras hmmm no, I've just gotten used to it but a fix would be welcome tho . You facing the same issue?

**Comment by cursoras** [comment]
@default-303 Yes. #539 is relative to this issue, but there are not any fixes.

**Comment by theol0403** [comment]
Unfortunately nvim does not know to delete the whitespace inserted by vscode
