### ISSUE TITLE
VIM Command Line ctrl+p only returns last command and ctrl+n doesn't work at all

### ISSUE THREAD

**Issue by vlrevolution** [vscode-neovim/vscode-neovim#689]
What could be causing this?

**Comment by theol0403** [comment]
Humm, I am also experiencing this with the latest neovim. I feel like the problem is relatively recent?

**Comment by vlrevolution** [comment]
Yes, I tried with empty neovim config and still get the same, also with most VSCode plugins disabled. I am thinking recent VSCode updates have broken something about cmdline. Anyone else experience this?

**Comment by mizagog** [comment]
i've had it for a while (even before NVIM 5), but i didn't have a go with an empty config, also i'm on Windows.

**Comment by vlrevolution** [comment]
Yeah, I am also on windows.

**Comment by sisrfeng** [comment]
+1

**Comment by theol0403** [comment]
Fixed by #908
