### ISSUE TITLE
Unable to indent lines starting with #

### ISSUE THREAD

**Issue by smackesey** [vscode-neovim/vscode-neovim#695]
The `>` indentation functionality appears to be subtly broken in very specific circumstances.

In a Python file, `>` works normally for me unless I am attempting to indent a commented line starting in the first column:

```
'this indents ok'
    # this indents ok
# trying to indent this does nothing
```

I'm sure this situation manifests in other scenarios/filetypes as well, but I've really only used this plugin for Python.

**Comment by wilkystyle** [comment]
I am encountering this one, too. FWIW if I open the same file in _native_ NeoVim (i.e. same `~/.config/nvim/init.vim` and all) the indentation command works.

**Comment by theol0403** [comment]
I believe this is caused by `synax off`.

**Comment by filyp** [comment]
@theol0403 I tried `syntax on` and the bug persists.

**Comment by xiyaowong** [comment]
Maybe it's an upstream issue, either with Neovim or the node-client.

**Comment by xiyaowong** [comment]
Okay, the reason is quite simple.

https://github.com/neovim/neovim/blob/add1b10b79011d1af61419a63cc8ef4645f45bbf/runtime/doc/options.txt#L5656
