### ISSUE TITLE
Using Cmd+D (add to selection, multiple cursors) in visual mode

### ISSUE THREAD

**Issue by smackesey** [vscode-neovim/vscode-neovim#698]
I'm attempting to bind <D-d> (macOS Cmd-d) in visual mode so that it behaves as it does with a real VSCode selection. Pressing <D-d> in visual mode should:

- convert the visual selection to a VSCode selection
- search for the visually selected string
- add the next match to the selection
- leave me in insert mode with multiple selections

Is this possible? I'm having a lot of difficulty. I've tried following the instructions in the README and this is what I have:

```
# keybindings.json
 {
    "key": "cmd+d",
    "command": "vscode-neovim.send",
    "when": "editorFocus && neovim.mode == 'visual'",
    "args": "<D-d>"
  },
```

```
# vimrc
vnoremap <D-d>  <Cmd>call VSCodeNotifyVisual('editor.action.addSelectionToNextFindMatch', 1)<CR>
```

I also pasted the `VSCodeNotifyVisual` definition in the README into my vimrc, because it was otherwise undefined (this is not clear from the README, which suggests the function is defined by the extension).

However, this mapping doesn't have the desired effect. It does about half of what I want, but it seems to leave me with multiple selections in normal mode, and subsequent presses of Cmd+D don't work.

I would also settle for a binding that just converted my visual selection to a VSCode selection and left me in insert mode, but I can't figure out how to do that from the README.

**Comment by theol0403** [comment]
> clear from the README, which suggests the function is defined by the extension

It is, but that function is new and has not been released to the vscode marketplace.

I would try to enter insert mode, then add to next match. I don't have the time to figure it out, though I'll try to take a look at it sometime.

**Comment by introom** [comment]
@asvetliakov Can we release a new version on Marketplace to cover the VSCodeNotifyVisual functionality?
