### ISSUE TITLE
Multiple cursors does not work

### ISSUE THREAD

**Issue by haolly** [vscode-neovim/vscode-neovim#699]
All mi/mI ma/mA does not work in normal mode

**Comment by madupuis90** [comment]
I'm having the same problem.

vscodium V1.58.2
vscode neovim v 0.0.82

**Comment by vlwkaos** [comment]
Maybe related to https://github.com/asvetliakov/vscode-neovim/issues/97 ?

**Comment by theol0403** [comment]
Works for me
