### ISSUE TITLE
Visual mode selection has an offset

### ISSUE THREAD

**Issue by buiducanh** [vscode-neovim/vscode-neovim#702]
# Problem
I enter visual mode with `v` and start selecting, but the selection has an offset from where my cursor is

# Expectations
Selecting text in visual mode should match my cursor

# Versions
1. Neovim 0.5
2. vscode-neovim v0.82

[Video Example](https://youtu.be/MX_Wt5NXCJc)

**Comment by mehalter** [comment]
I can confirm that this is also affecting me (same versions: neovim v0.5, vscode-neovim v0.82) and is making visual mode nearly unusable. There is an offset when using `v` visual mode but it gets worse if I try to use visual line or visual block mode.

**Comment by theol0403** [comment]
Make sure you test with empty init.vim

**Comment by oleynikandrey** [comment]
Hello, I've the same problem but only with `*.go` files, selection in other files works as expected.
My `init.vim` is empty. How could I find a root cause?
