### ISSUE TITLE
How to exclude capturing singular ctrl key (ctrl-k)

### ISSUE THREAD

**Issue by UncleGoogle** [vscode-neovim/vscode-neovim#703]
I would like to open zen-mode by default `ctrl-k z` vscode shortcut, but in normal mode it is captured by the nvim.

I know I can `useCtrlKeysForNormalMode` to disable all of them but how to exclude only ctrl-k ?

For ctrl-c and ctrl-f I have those that works

```json
    {
        "key": "ctrl+c",
        "command": "-vscode-neovim.escape"
    },
    {
        "key": "ctrl+f",
        "command": "-vscode-neovim.ctrl-f",
        "when": "editorTextFocus && neovim.ctrlKeysNormal && neovim.init && neovim.mode != 'insert'"
    }
```

but 

```json
    {
        "key": "ctrl+k",
        "command": "-vscode-neovim.ctrl-k",
    }
``` 

does not work

**Comment by theol0403** [comment]
Are you sure you are not sending ctrl-k to neovim yourself?? This plugin does nothing to bind ctrl-k.

**Comment by UncleGoogle** [comment]
@theol0403 in the Keyboard Shortcuts view I found this:

![image](https://user-images.githubusercontent.com/12197825/126879216-23ca5e74-058a-4aaa-b4b0-30bdd3ced2ba.png)

And when I chose right-click-> `Remove Keybinding` then this appears in my `%appdata%\Code\User\keybindings.json`:

```json
    {
        "key": "ctrl+k",
        "command": "-vscode-neovim.send",
        "when": "editorTextFocus && neovim.ctrlKeysNormal && neovim.init && neovim.mode != 'insert'"
    } 
```

and then it works.

In the `Default Keybindings` I can see


```json
{ "key": "ctrl+k",                "command": "vscode-neovim.send",
                                     "when": "editorTextFocus && neovim.ctrlKeysNormal && neovim.init && neovim.mode != 'insert'",
                                     "args": "<C-k>" },

```

so I thought it is a default extension setting?

**Comment by YgtOz** [comment]
I would also like to know this, precisely for this use case. I am quite new to Vim and VSCodium both, and as such I would also really appreciate help on this matter.

**Comment by ElSamhaa** [comment]
`ctrl+c` is not working with me as well, even though I made sure it's bound to the default action i.e. `copy`.

**Comment by nic11** [comment]
In case anyone struggling with `ctrl+f` too, here's the solution. Add this to `~/.config/Code/User/keybindings.json` (or its' equivalent):
```json5
[
  // ...
  {
    "command": "actions.find",
    "key": "ctrl+f",
    "when": "editorFocus || editorIsOpen"
  },
]
```

For other shortcuts, you can find out which command id you want from 'Preferences: Open Default Keyboard Shortcuts' menu (or just copy the corresponding keybinding from it's `(JSON)` version)
