### ISSUE TITLE
ctrl-R overrided by vscode default keybinding

### ISSUE THREAD

**Issue by UncleGoogle** [vscode-neovim/vscode-neovim#704]
ctrl-R does not work in normal mode as redo.

Looks like the deafult keybinding is covering the extension setting.

![image](https://user-images.githubusercontent.com/12197825/126879414-a0497844-1b94-4874-8315-f25f9fd128b0.png)

I have enabled `useCtrlKeysForNormalMode`.

Forgive me if I messed up something in vscode on my side, I do no understand its settings well yet.

**Comment by theol0403** [comment]
Works for me.
