### ISSUE TITLE
:%s/foo/baaaaar/gc does not prompt for confirmation and produces incorrect selection

### ISSUE THREAD

**Issue by pepijndevos** [vscode-neovim/vscode-neovim#707]
gc means it'll match multiple times on the same line, and c means it'll ask for confirmation.

This extension does not visibly prompt for confirmation, and shows an incorrect selection for subsequent matches on each line.
Basically it does not account for the length of the line to change, and only updates after going to the next line.

**Comment by vlwkaos** [comment]
It works for me. The prompt is shown at the bottom of the editor.
