### ISSUE TITLE
VIM command menu gets stuck open

### ISSUE THREAD

**Issue by collang** [vscode-neovim/vscode-neovim#709]
Intermittently (about 0.8 times per week) I find the VIM command line pop-up at the top of the screen becomes stuck open. Esc does not close it, neither does running a command such as closing the current file. To remove it I just restart VSCode, which is a minor inconvenience.

I am using: VSCode version 1.57.1, VSCode Neovim 0.0.82 and running RHEL 8

**Comment by oliver6653** [comment]
me too

**Comment by oliver6653** [comment]
@AngusCollett   ***Did U sole this ??? ***

May Someone  solve this? To remove it I just restart VSCode, which is a huge inconvenience.

**Comment by AngusCollett** [comment]
Try running `visual` in the command menu. I think this might be a vim quirk that happens when you accidentally type `q:` instead of `:q` (see: https://vi.stackexchange.com/questions/14090/im-stuck-in-vim-i-see-command-line-at-the-bottom-and-nothing-makes-vim-respo).
