### ISSUE TITLE
Edamagit support

### ISSUE THREAD

**Issue by jtpavlock** [vscode-neovim/vscode-neovim#714]
Hello, and thank you for the great extension!

[Edamagit ](https://marketplace.visualstudio.com/items?itemName=kahole.magit)is an extension to mimic the functionality of magit in emacs. Currently, they have [some tips for working with the Vim extension](https://github.com/kahole/edamagit#vim-support-vscodevim), and I was wondering if similar settings were possible with neovim?

**Comment by Fraznist** [comment]
I think I found a (very tedious) solution:
`vscode-neovim` introduces a lot of `Neovim: send key` keybindings, which aren't deactivated when the user is in the `edamagit` window. Neovim bindings end up taking precedence, as a result edamagit bindings do not activate. Adding `editorLangId != 'magit'` to the `when` expressions of `Neovim: send key` keybinds lets me use the edamagit keybindings.

For instance, `<Tab>` wasn't folding or unfolding any of my changes in the magit status page. Adding the following to `keybindings.json` restores the `<Tab>` functionality to edamagit:
```json
{
  "key": "tab",
  "command": "extension.vim_tab",
  "when": "editorFocus && vim.active && !inDebugRepl && vim.mode != 'Insert' && editorLangId != 'magit'"
}
```
Downside to this approach is we would probably need to add all `vscode-neovim` keybinds that `edamagit` uses manually.

**Comment by giulioungaretti** [comment]
Maybe it's me doing something wrong :D but the above from @Fraznist  do not seem to work. 
For now I went:
 {
      "command": "-vscode-neovim.send",
      "key": "tab"
  }
But it's a rather aggressive solution :D

**Comment by robertfw** [comment]
I also couldn't get the solution from @Fraznist to work,the solution from  @giulioungaretti  did do the job, though I haven't used it enough to see if anything else has broken.

Has anyone come up with an ideal solution for this?

**Comment by xiyaowong** [comment]
@robertfw We can provide a configuration like `vscode-neovim.keybinds.editorLangIdBlacklist` and then add `editorLangId not in neovim.editorIdBlacklist` to the when expressions of all keybinds.
https://code.visualstudio.com/api/references/when-clause-contexts#in-and-not-in-conditional-operators

**Comment by trkoch** [comment]
Please try to add `magit` to `editorLangIdExclusions`. See https://github.com/vscode-neovim/vscode-neovim#disable-keybindings.

> To disable keybindings defined by this extension in certain filetypes, you can use the `editorLangIdExclusions`
configuration. Please note that this will not affect all keybindings. If you find that this option is not working, you
can manually modify the keybindings in VSCode.

If this does not work for you, a workaround is to disable the extension with the command `Neovim: Stop extension`.

**Comment by sylvester-roos** [comment]
That explains why I couldn't find the configuration option haha
