### ISSUE TITLE
Question: can this extension be used to get tree-sitter highlighting in VS Code?

### ISSUE THREAD

**Issue by ahelwer** [vscode-neovim/vscode-neovim#715]
VS Code has a [well-known tree-sitter deficiency](https://github.com/Microsoft/vscode/issues/50140). Can this extension be used with the [nvim-treesitter plugin](https://github.com/nvim-treesitter/nvim-treesitter) as a sort of backdoor method of getting tree-sitter-based syntax highlighting into VS Code? If so, how? It doesn't seem to just work by default.

[Also asked](https://github.com/nvim-treesitter/nvim-treesitter/discussions/1637) over on the nvim-treesitter discussion board.

**Comment by IBS27** [comment]
I think you can enable semantic highlighting in VSCode to get the same highlighting.

**Comment by still-dreaming-1** [comment]
Which settings exactly are involved in getting this to work? Or does it work without changing any settings? It's not working for me. I'm trying to use my colorscheme from Neovim, but it's not working at all. It is just using the VS Code theme instead.

**Comment by ahelwer** [comment]
I recall you can't have an extension installed that sets syntax highlighting because that will take precedence over it, but it's been a few years since I tried. Perhaps it works differently now. There's also the vscode-anycode extension now.

**Comment by dotai2012** [comment]
For anyone searching thing issue: It works, but you need to enable `Semantic highlight` and add `TSEnable highlight` to your init.lua

![image](https://github.com/vscode-neovim/vscode-neovim/assets/12532557/0d5dba38-814a-4259-87e1-dd9fb0bb4a18)
![Uploading image.png…]()

```
return {
  -- This function is run last and is a good place to configuring
  -- augroups/autocommands and custom filetypes also this just pure lua so
  -- anything that doesn't fit in the normal config locations above can go here
  polish = function()
    vim.api.nvim_create_autocmd({ "VimEnter" }, {
      command = "TSEnable highlight",
    })
  end,
}
```

After that, you can use all textobjects keymaps: https://github.com/nvim-treesitter/nvim-treesitter-textobjects

**Comment by dotai2012** [comment]
For anyone searching thing issue: It works, but you need to enable `Semantic highlight` and add `TSEnable highlight` to your init.lua

![image](https://github.com/vscode-neovim/vscode-neovim/assets/12532557/0d5dba38-814a-4259-87e1-dd9fb0bb4a18)
![Uploading image.png…]()

```
return {
  -- This function is run last and is a good place to configuring
  -- augroups/autocommands and custom filetypes also this just pure lua so
  -- anything that doesn't fit in the normal config locations above can go here
  polish = function()
    vim.api.nvim_create_autocmd({ "VimEnter" }, {
      command = "TSEnable highlight",
    })
  end,
}
```

After that, you can use all textobjects keymaps: https://github.com/nvim-treesitter/nvim-treesitter-textobjects

**Comment by justinmk** [comment]
> but you need to enable `Semantic highlight`

That is a vscode LSP setting, it has nothing to do with treesitter.
