### ISSUE TITLE
Neovim extension startup/config problem for VSCode installed from a FLATPAK on linux

### ISSUE THREAD

**Issue by VProfirov** [vscode-neovim/vscode-neovim#719]
Referencing issue: [Neovim disconnects and exits with error code 1 #685](url:https://github.com/asvetliakov/vscode-neovim/issues/685)

Errot : MainController: spawn /usr/bin/nvim ENOENT

Granting all needed permissions using Flatseal doesn't fix it either.

It will be greatly appreciated if an example of settings.json configuration for the neovim extension is added with the mention of what minimal permissions are needed for the work of the extension with a custom init.vim in the /home/$USER/.config/nvim directory.

**Comment by ianchanning** [comment]
I have always found that sandboxed installations such as flatpak cause problems with IDEs which need constant access outside the sandbox. I'd just use the standard linux package.

**Comment by qlibp** [comment]
> I downloaded the official neovim appimage and unpacked it following neovim's release instructions (`--appimage-extract`) and placed the resulting dir in the `/usr` directory on my host, which the vscode plugin can see, by setting the plugin's neovim path to `/run/host/usr/REST_OF_PATH`. After that I symlinked my host nvim's `init.vim` to the vscode flatpak's `config/nvim` directory (having to first `mkdir` the `nvim` directory). Most things seem to work now in VSCode.

How to set plugin's neovim path? `/run/host/usr/bin/nvim` ?

**Comment by userrand** [comment]
@qlibp I am not sure if I understand your question but you can tell the neovim plugin to look for neovim using the settings UI (not json although there is probably a way to do it with the json file). If you are using Linux or wsl you can search for vscode-neovim.neovimExecutablePaths.linux in the search input. I guess if you are using windows you can search for (but I did not try on windows) vscode-neovim.neovimExecutablePaths.win32. In general you can type vim in the settings UI and see other options that you can configure.

"vscode-neovim.neovimExecutablePaths.linux": "/home/claude/code_development/nvim-linux64/bin/nvim"
