### ISSUE TITLE
Syntax not highlighted until exiting insert mode

### ISSUE THREAD

**Issue by with-heart** [vscode-neovim/vscode-neovim#721]
I've recently run into an issue where anything I type in insert mode doesn't receive syntax highlighting until I return to normal mode.

![Kapture 2021-08-11 at 09 11 15](https://user-images.githubusercontent.com/1954752/129034704-46439b7a-dc63-4a02-a924-a23aa6cde80f.gif)

Syntax highlighting works fine if I disable the extension. I also validated that it isn't caused by conflict with another extension by disabling all extensions except for `vscode-neovim`.

## Versions

VSCode: 1.59.0
neovim: 0.5.0
vscode-neovim: 0.0.82

**Comment by theol0403** [comment]
Try with empty init.vim. Maybe you turned on syntax in nvim.

**Comment by sitiom** [comment]
@with-heart Treesitter was causing the issue for me, and following the config in https://github.com/vscode-neovim/vscode-neovim/issues/609#issuecomment-1042796958 worked:
```lua
    highlight = {
        enable = (not vim.g.vscode),
    },
```
