### ISSUE TITLE
ctrl+e and ctrl+y does not work with numbers to repeat

### ISSUE THREAD

**Issue by russoue** [vscode-neovim/vscode-neovim#729]
Not sure if I am describing it clearly but when I try to do `5 ctrl+y` instead of moving 5 lines I see only 1 line moving.  The behavior is the same for `ctrl+e`.  Basically the number I specify to repeat the command is ignored.  I am running version `v0.0.82` in Mac OS.  Please take a look.

**Comment by theol0403** [comment]
Duplicate of #361
