### ISSUE TITLE
:qa completely shuts down Neovim in the background

### ISSUE THREAD

**Issue by comiluv** [vscode-neovim/vscode-neovim#733]
1. Brief description:
Entering command qa results in messages "MainController: Neovim was disconnected" and "MainController: Neovim exited with code: 0", shutting itself down and vscode not responding any further.
2. Reproduce steps:
(1) :qa
3. Expected
It would be preferred if the editor closes all open tabs without completely shutting down Neovim
4. Happens
See 1.
5. Other info
Microsoft Windows [Version 10.0.19043.1165]
VSCode 1.59.0
Neovim NVIM v0.6.0-dev+142-g5a111c1b0

**Comment by theol0403** [comment]
Works for me

**Comment by micimize** [comment]
I had this issue when closing any tab due to the following:
```vimrc
" Close window when quitting last buffer
autocmd BufDelete * if len(filter(range(1, bufnr('$')), 'empty(bufname(v:val)) && buflisted(v:val)')) == 1 | quit | endif
```
