### ISSUE TITLE
[BUG]:  :w fails with E494: Not an editor command: Write with NVIM v0.6.0

### ISSUE THREAD

**Issue by danielb2** [vscode-neovim/vscode-neovim#736]
Seems `:w` isn't working for me. I don't remember ever having this issue before, but I'm new to vscode and I just went to vacation for a month. 

`NVIM v0.6.0-dev+1639-g50b30de20`

I've confirmed that it's the 0.6 version of nvim that's not compatible.

**Comment by justinmk** [comment]
did you try disabling your vim config / plugins?

**Comment by danielb2** [comment]
no, what's the easiest way? But even `:e!` works fine. So I'm not sure why `:w` is giving issues now

**Comment by justinmk** [comment]
easiest way is to just delete/rename ~/.config/nvim

**Comment by danielb2** [comment]
the problem persists even after renaming the nvim config

**Comment by danielb2** [comment]
getting this error too when stating

```
VSCode-Neovim:

line   34:
E1208: -complete used without -nargs
line   10:
E1208: -complete used without -nargs
```

**Comment by justinmk** [comment]
that is a signal that vscode-neovim has a malformed `:commad` definition, see https://github.com/tpope/vim-fugitive/commit/4cdeff8c33ec2fe0686324bf1846ce158c452754

**Comment by danielb2** [comment]
oh, I did update my plugins recently. But i see it even after moving the ~/.config/nvim. how can that be if it's in the tpope plugin? (which I do have)

**Comment by justinmk** [comment]
> how can that be if it's in the tpope plugin?

Has nothing to do with tpope, I only linked to that to show an example of how to fix the error. Newer versions of Vim/Nvim now throw an error when that type of `:command` exists.

**Comment by danielb2** [comment]
Given that `:w` still doesn't work even after disabling the plugins, any idea what could be causing it? I did recently upgrade all my packages, and it could be due to a new nvim version

**Comment by pcuttriss** [comment]
@danielb2 I hit exactly the same issue this morning. After 3 hours of moving stuff around and testing I have got to a stable situation again....on Ubuntu 18.04 but the error was identical.

On 18.04 I was using the unstable ppa for neovim and that got updated to a version post 0.5.0....and it broke everything. I have pulled down the 0.5.0 stable appimage of neovim from here https://github.com/neovim/neovim/releases and dropped it into my /home/username/bin directory and used that path in the vscode-neovim config and all is well with the world again.

Hope that helps you.

**Comment by danielb2** [comment]
> @danielb2 I hit exactly the same issue this morning. After 3 hours of moving stuff around and testing I have got to a stable situation again....on Ubuntu 18.04 but the error was identical.
> [...SNIP...]
> Hope that helps you.

Yes, that helps as it confirms my suspicion. Hopefully it will be fixed soon

**Comment by danielb2** [comment]
I did downgrade to 0.5 as well, and now it works fine

**Comment by rtmor** [comment]
A fix has already been proposed, just waiting for review/approval.

See PR #725.

**Comment by danielb2** [comment]
> A fix has already been proposed, just waiting for review/approval.
> 
> See PR #725.

does it address the `:w` issue? It seems to address the ticket talking about `E1208: -complete used without -nargs` but I don't know if that's even related

**Comment by joshniec** [comment]
When I remove `-complete=file` from https://github.com/asvetliakov/vscode-neovim/blob/bd375c6462ba7f065e6c7c86b53444269b9a23cd/vim/vscode-file-commands.vim#L34 the problem goes away and I am able to use `:w` using the latest version of Neovim 0.6.0. 

On Windows this is in `%USERPROFILE%/.vscode/extensions/asvetliakov.vscode-neovim-0.0.82` (even if using WSL2). I believe Linux/mac are in `~/.vscode/extensions/asvetliakov.vscode-neovim-0.0.82`.

**Comment by gerroon** [comment]
When is the release that has this fix?

**Comment by sisrfeng** [comment]
> A fix has already been proposed, just waiting for review/approval.
> 
> See PR #725.

I Updated to neovim 0.6, and find that I have to update vscode-neovim too.
Done.
