### ISSUE TITLE
Sometimes move/jump to matching brace does not work

### ISSUE THREAD

**Issue by Sebas-h** [vscode-neovim/vscode-neovim#740]
[Vim feature in question](https://vim.fandom.com/wiki/Moving_to_matching_braces)

## Software env

VSCode: 1.59.1
vscode-neovim: v0.0.82 [using an empty `init.vim`]
neovim: v0.5.0
OS: macOS Big Sur 11.1

## The bug

In some instances moving/jumping to matching brace using `%` does not work.

### Video

(Key cast bottom left)

![bug](https://user-images.githubusercontent.com/12663408/131257868-22f24a40-3bcc-46de-98cc-d968ce10c12f.gif)

#### Summary:
* Cursor on opening brace L98 -> press `%` -> cursor now on closing brace on L99.
* Cursor on opening brace L101 -> press `%` -> [nothing happens, **bug**] -> press `j` -> cursor now on L103 (one line below closing brace)

#### Test file used
[test.txt](https://github.com/asvetliakov/vscode-neovim/files/7072835/test.txt)
NOTE that there are 102 empty lines after the second close brace, with less the bug does not occur

#### Logs
[log.txt](https://github.com/asvetliakov/vscode-neovim/files/7072842/log.txt)
I don't see a difference between the first and second matching jump logs.

### Quirks

Several ways to make moving to matching brace on the second pair of braces in the test file work

* Put brace on same line
    * Indicating it only happens when the braces or on separate lines
* Put one or more characters in front of the open and/or closing brace, but not the same amount for each
    * Indicating it only happens when both braces are on the same column
* Remove a single line after L102
    * Indicating it only happens when there are at least 99 lines after the closing brace
* Remove L100 (it works in this state even if adding more lines after the second closing brace)
    * Indicating it only happens if the open brace is on L101 or after.

## Related issues

* https://github.com/asvetliakov/vscode-neovim/issues/488
* https://github.com/asvetliakov/vscode-neovim/issues/605

These seem to indicate this issue should already have been solved, but at least for me this is not the case.

**Comment by xiyaowong** [comment]
Unable to reproduce, it may have been fixed.
