### ISSUE TITLE
Find in project from highlighted text

### ISSUE THREAD

**Issue by lougreenwood** [vscode-neovim/vscode-neovim#741]
In vanilla VSCode I can highlight test, press the `cmd-shift-F` shortcut to open the project search and the highlighted text from my file will be used for the search.

Is this possible in `vscode-neovim`?

**Comment by vlwkaos** [comment]
Put these under vscode environment settings.
```vim
    " find in files, query: word under caret
    command! FindInFile call VSCodeNotify('workbench.action.findInFiles', {'query': expand('<cword>'), 'replace': ''})
    command! FindInFileS call VSCodeNotify('workbench.action.findInFiles', {'query': @p, 'replace': ''})
    nnoremap <silent> <Leader>f :FindInFile<CR>
    xnoremap <silent> <Leader>f "py<Esc>:FindInFileS<CR>
```

press <Leader>f or map it your way.

**Comment by luong-komorebi** [comment]
Can confirm that the commands that @vlwkaos is working really well. Also what I am using right now :)
