### ISSUE TITLE
autocmd BufWritePost  

### ISSUE THREAD

**Issue by diogogmt** [vscode-neovim/vscode-neovim#743]
I'm not sure if it's a supported feature, but some of the `autocmd BufWritePost` directives I have configured to run whenever a file is saved are not working if I save the file on **vscode**. Saving the files on **nvim** works as expected.

Eg;
```
autocmd BufWritePost ~/.local/src/my-repo/{*.c,*.h} !cd ~/.local/src/my-repo/; sudo make install
```

**Comment by justinmk** [comment]
This extension currently uses a wrapper called `AlterCommand` for some commands, so there are quirks. See https://github.com/asvetliakov/vscode-neovim/issues/136#issuecomment-581085268 for details and future ideas.
