### ISSUE TITLE
[Feature Request] pass `--clean` to neovim

### ISSUE THREAD

**Issue by goolord** [vscode-neovim/vscode-neovim#746]
motivation: i want to keep 2 separate configs for vscode-neovim and standalone nvim, including full control over the rtp. this way, i can forgo loading plugins that are broken or otherwise made unnecessary by vscode

**Comment by goolord** [comment]
worth noting that this plugin basically broken for me unless i run with `-u NONE` since i can't pass `--clean`

**Comment by trkoch** [comment]
You can distinguish Plugin/Standalone with `if exists('g:vscode')` in case you didn't know.

**Comment by goolord** [comment]
my 2 configs are very different, I would basically be wrapping entire files like this and i would still need to manually manage my rubtime path which is a sisyphean task i don't want to do

**Comment by theol0403** [comment]
Also you can specify a different init.vim location

**Comment by goolord** [comment]
it doesn't matter if you can pass a different init.vim, the runtime path is global state. if your two init.vims use different runtime paths, this doesn't work

**Comment by goolord** [comment]
> worth noting that this plugin basically broken for me unless i run with -u NONE since i can't pass --clean

**Comment by jim-chien** [comment]
@goolord you can add this to your `init.vim` file:
```vim
if(exists('g:vscode')
  set noloadplugins
endif
```
The answer is at the section 9 here: https://neovim.io/doc/user/starting.html

**Comment by theol0403** [comment]
I think it is more useful to have a shared config than two separate configs. If you want to separate them, add the logic yourself. Unless you want to make a PR for a config option.

**Comment by goolord** [comment]
> Unless you want to make a PR for a config option.

so, is it worth having or is it not? 😞

I only opened the issue instead of making a PR myself because it's not at all obvious from 30 minutes of hacking or so how I would even add this feature, but I was hoping it's trivial for someone with a little more familiarity with the codebase / writing vs code plugins

**Comment by goolord** [comment]
> I think it is more useful to have a shared config than two separate configs 

(´。＿。｀)
![image](https://user-images.githubusercontent.com/24906808/177023012-69386f06-a291-4516-baef-67b1a47eb6cb.png)
