### ISSUE TITLE
[Question] How to use `VSCodeSetTextDecorations` ?

### ISSUE THREAD

**Issue by searleser97** [vscode-neovim/vscode-neovim#748]
Is there any place where I can find documentation on how to use `VSCodeSetTextDecorations(...)` ?
like What parameters should I send to it ?

**Comment by sisrfeng** [comment]
+1
I come here because the vscode specific easymotion plugin has problems:
If these lines are in init.vim, calling easymotion will make the screen flashing:
```
" nmap f <Plug>(easymotion-f) "f{char}
" map  <Leader>f <Plug>(easymotion-bd-f) " <Leader>f{char} to move to {char}

" these two lines make the cursor go to next line, instead of jumping to where you want
" nmap s <Plug>(easymotion-f2)
" map  <Leader>w <Plug>(easymotion-w) 
``


![image](https://user-images.githubusercontent.com/53520949/136188942-de279b8c-4352-4db0-be84-a0124d14ed92.png)

**Comment by theol0403** [comment]
Soon the plugin will support extmarks using #868.
