### ISSUE TITLE
mode indicator error when using input method switcher

### ISSUE THREAD

**Issue by Wongboo** [vscode-neovim/vscode-neovim#751]
I'm a Chinese user of plugin, my init.vim looks like
```vim
autocmd InsertLeave * :silent :!C:\\Users\\90834\\Documents\\im-select.exe 1033
autocmd InsertEnter * :silent :!C:\\Users\\90834\\Documents\\im-select.exe 2052
```
When I use vscode-neovim and try to type Chinese in insert mode, which means using Chinese mode in Chinese keyboard, corresponding to inputmethod 2052, and press 'Enter', I'm in fact in normal mode, but the mode indicator show I'm in insert mode, in fact, other functionality works well, except mode indicator.
I have to mention use nvim in terminal won't cause this problem, besides, using English mode in Chinese keyboard (which is differenct from English keyboard, which inputmethod is 1034) which inputmethod is still 2052, won't cause problem

**Comment by theol0403** [comment]
I think this was fixed in #772
