### ISSUE TITLE
vim-xkbswitch not workin

### ISSUE THREAD

**Issue by albert-ying** [vscode-neovim/vscode-neovim#754]
This plugin is very useful for multi-lingual users. It seems not working in vscode. (I believe it worked before, but at some point, it breaks.)

Vim plugin XkbSwitch can be used to easily switch current keyboard layout back and forth when entering and leaving Insert mode. Say you are typing some document in Russian and have to leave Insert mode: when you press <Esc> your keyboard layout switches to US/English automatically.

https://github.com/lyokha/vim-xkbswitch

Also related to #560

**Comment by albert-ying** [comment]
The VScodeVim also supports automatic input method switch between normal and insert mode 
https://github.com/daipeihust/im-select

**Comment by karambaq** [comment]
@albert-ying how did you make it work? it doesn't work for me in vscode-neovim.
