### ISSUE TITLE
Switch tab + quick paste messes up undo in first tab

### ISSUE THREAD

**Issue by wtfsck** [vscode-neovim/vscode-neovim#759]
version: v0.0.82 (latest version at this point in time)

Create two text files:

a.txt (copied from README):
```txt
Neovim is a fork of VIM to allow greater extensibility and integration. This extension uses a full embedded Neovim instance, no more half-complete VIM emulation! VSCode's native functionality is used for insert mode and editor commands, making the best use of both editors.

    tada Almost fully feature-complete VIM integration by utilizing neovim as a backend.
    wrench Supports custom init.vim and many vim plugins.
    1st_place_medal First-class and lag-free insert mode, letting VSCode do what it does best.
    handshake Complete integration with VSCode features (lsp/autocompletion/snippets/multi-cursor/etc).
```

b.txt (it's empty):
```
```

Repro:
- Open both files in VS Code
- Switch to `a.txt` and go to line 3
- Yank 2 lines (eg. `2Y` or `VjY`)
- Ctrl+tab to `b.txt` tab or `gt` to it
- Immediately hit `P` to paste (don't try to wait)
- Nothing is pasted in `b.txt` tab (could be https://github.com/asvetliakov/vscode-neovim/issues/643)
- Switch back to `a.txt` tab
- Undo `u` and it will undo the 2 lines we yanked. You can also enter visual mode and select all lines and you'll see that some lines aren't completely selected.

Instead of `P`, you can also try `p` since it messes up the file in a slightly different way.

**Comment by theol0403** [comment]
Can confirm

**Comment by xiyaowong** [comment]
When switching editors, it takes time to set nvim's window and buffer. This process takes about 0.2s. it's unavoidable
