### ISSUE TITLE
How to map workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup in neovim?

### ISSUE THREAD

**Issue by introom** [vscode-neovim/vscode-neovim#762]
Mapping
```
nnoremap <Space>s <Cmd>call VSCodeNotify('workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup')<CR>
```
Leaves the quickwindow open instead of switching to the previous file.

Compare the effect with the vscode land correspondent <ctrl-tab>, which opens the quickwindow and the automatically goes to the previous file.

**Comment by theol0403** [comment]
I think vscode did something special that closes quickpick when ctrl let go. Not possible with a command.
