### ISSUE TITLE
visual mode bug

### ISSUE THREAD

**Issue by askfiy** [vscode-neovim/vscode-neovim#766]
Visual mode cannot select multiple lines, although I have used cmd+shift+p to try to make it a normal vscode selection.

A simple example, I often use the Comment Translate plug-in to translate comments in the source code.
If I use the visual mode of the vscode-vim plugin to select multiple lines, it is correct:

![image-20211105185340447](https://images-1302522496.cos.ap-nanjing.myqcloud.com/img/image-20211105185340447.png)

But if I use the visual mode of the vscode nvim plug-in to select multiple lines vscode multi-line mode, it still won’t take effect, but the last line is selected（i use cmd+shift+p command）:

![image-20211105185255586](https://images-1302522496.cos.ap-nanjing.myqcloud.com/img/image-20211105185255586.png)

what should I do??? @asvetliakov

**Comment by theol0403** [comment]
Works on latest version
