### ISSUE TITLE
Cursor jumps when switching split-screen tabs 

### ISSUE THREAD

**Issue by hffmnn** [vscode-neovim/vscode-neovim#776]
When editing in one tab and switching to another tab (e.g. via the mouse) the cursor position is somehow reset: 
- It always jumps to the highlighted line. This only happens, when one of the files is edited before switching. 
- It also happens when switching tabs via the native OS tab switch mechanism (in this case macOS: `Cmd-Shift-[`
- This does not happen when using the window shortcuts provided by the plugin e.g. `<C-W>l`
---

https://user-images.githubusercontent.com/352753/143090454-f43436c8-4c0c-4267-bf04-bf61d1d32675.mov

---
- As you can see I don't have any other plugins enabled
- VS Code Settings are completely empty besides this line: `"vscode-neovim.neovimExecutablePaths.darwin": "/usr/local/bin/nvim"`
- No custom `nvim` configuration  at all:
```bash
open ~/.config/nvim
The file ~/.config/nvim does not exist.
```
- `nvim` is installed via `brew`:

```bash
nvim --version
NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20211103-3501-1gz0ofb/neovim-0.5.1/build/config -I/tmp/neovim-20211103-3501-1gz0ofb/neovim-0.5.1/src -I/usr/local/include -I/tmp/neovim-20211103-3501-1gz0ofb/neovim-0.5.1/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20211103-3501-1gz0ofb/neovim-0.5.1/build/src/nvim/auto -I/tmp/neovim-20211103-3501-1gz0ofb/neovim-0.5.1/build/include
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.5.1_1/share/nvim"

Run :checkhealth for more info
```

Any idea what might cause this issue?

**Comment by sa1148260** [comment]
I have a similar problem. This won't happen if you go back to normal mode manually before switching TAB. But I don't know how to automatically go back to normal mode when I switch tabs.

**Comment by hffmnn** [comment]
Nice. Did a quick test and it works as expected. Thanks a lot for taking the time to fix it. 👍
