### ISSUE TITLE
How to use ctrl+[ to escape from vim command line

### ISSUE THREAD

**Issue by stimw** [vscode-neovim/vscode-neovim#780]
Esc works, but ctrl+[ doesn't work for escaping from command line...

![image](https://user-images.githubusercontent.com/30977647/145202653-944f170e-0a3d-4bac-8448-fff276b6b645.png)

I have this setting:

```
{
  "key": "ctrl+[",
  "command": "vscode-neovim.escape",
  "when": "editorTextFocus && neovim.init"
}
```

**Comment by theol0403** [comment]
If the quickpick window is focused, the editor is not focused. You need to fix your when clause.
