### ISSUE TITLE
Visual mode and CursorLine conflicts

### ISSUE THREAD

**Issue by stimw** [vscode-neovim/vscode-neovim#786]
When I use visual mode, the cursorline won't disappear...
Then it's difficult to distinguish **whether the code is selected** in some color schemes.

Like:
![nvim](https://user-images.githubusercontent.com/30977647/145701274-bd9560e4-9c04-4e56-81e5-c0883676f1be.gif)

But the vscode-vim extension works well:
![vim](https://user-images.githubusercontent.com/30977647/145701296-cb7d3236-9fcc-4b9c-8eba-30ad7126012c.gif)

**Comment by theol0403** [comment]
This can only be fixed if the plugin produces real vscode selections from visual mode instead of fake ones. Might be possible however.

https://github.com/vscode-neovim/vscode-neovim/commit/1e1e8ce74f11c9b3b6d02cab05ef103a37aa36ca

**Comment by stimw** [comment]
> This can only be fixed if the plugin produces real vscode selections from visual mode instead of fake ones. Might be possible however.
> 
> [1e1e8ce](https://github.com/vscode-neovim/vscode-neovim/commit/1e1e8ce74f11c9b3b6d02cab05ef103a37aa36ca)

Thanks, now I modified this to fix it: 
```json
"workbench.colorCustomizations": {
    "editor.selectionBackground": "#B0C4DE"
  },
```

Should the issue be able to close?

**Comment by theol0403** [comment]
That's a good fix. Maybe we don't need this issue to track sending vscode selections.
