### ISSUE TITLE
Extension breaks renaming files via the Explorer window

### ISSUE THREAD

**Issue by ksweetie** [vscode-neovim/vscode-neovim#790]
When the files explorer window has focus, and a file selected, you should be able to press enter to edit the filename in place. With this extension enabled, instead, the editor window becomes focused, and there's no opportunity to rename the file.

If I disable this extension, it works as expected.

**Comment by VanillaBase1lb** [comment]
```
    {
        "key": "enter",
        "command": "renameFile",
        "when": "explorerViewletVisible && filesExplorerFocus && !explorerResourceIsRoot && !explorerResourceReadonly && !inputFocus"
    },

```

Try adding this to your `keybindings.json`

**Comment by cupcakearmy** [comment]
Solved it for me, thanks!

**Comment by theol0403** [comment]
A better solution would be to open the keybindings editor and delete the offending binding.

**Comment by zhiyuanzmj** [comment]
> A better solution would be to open the keybindings editor and delete the offending binding.

```json
{
    "key": "r",
    "command": "-renameFile",
    "when": "explorerViewletVisible && filesExplorerFocus && !explorerResourceIsRoot && !explorerResourceReadonly && !inputFocus"
},
{
    "key": "enter",
    "command": "-list.select",
    "when": "listFocus && !inputFocus && !notebookCellListFocused"
},
```
