### ISSUE TITLE
`set keymap=…` and ctrl-^ binding

### ISSUE THREAD

**Issue by timka** [vscode-neovim/vscode-neovim#791]
When I `set keymap=russian-jcukenwin` in regular nvim I can switch the layout in use with ctrl-^. This doesn't seem to work in vscode.

I'm on OS X 10.15.2
VSCodium 1.62.3

**Comment by teu5us** [comment]
I'm also interested in this

**Comment by justinmk** [comment]
'keymap' is an insert-mode feature. For insert mode you need to use VSCode or OS features.

The key tradeoff that vscode-neovim makes is to let vscode handle insert-mode. That avoids a lot of complexity / disappointments and enables all kinds of vscode features such as snippets and autocompletion.

**Comment by teu5us** [comment]
Keymap isn't strictly for insert mode. It also works in normal mode to allow f/F and t/T find characters from keymap. It also works when you search text and in command mode without breaking keybindings

**Comment by justinmk** [comment]
Does 'keymap' not work with f/F and t/T? 

This issue has almost zero details. Be specific about what you tried, what precise steps you tested, and what exactly "doesn't work" means.

**Comment by zenVentzi** [comment]
@timka did you find any workaround?

@justinmk it does work while in normal mode and using f/F. You seem vim-knowledgeable(looking at your profile), could you think of some solution, even a hacky one, but one that would allow us to use keymaps for different languages? It'd be greatly appreciated

**Comment by timka** [comment]
@zenVentzi I didn't, unfortunately. This requires deeper understanding of how bot NeoVim and the extension work and after reading the comments I'm totally lost.
