### ISSUE TITLE
Cursor not moving even if I hold down the key

### ISSUE THREAD

**Issue by atEaE** [vscode-neovim/vscode-neovim#792]
MacOS Monterey ver 12.0.1
VSCode Version: 1.63.2
Extension Version: 0.0.83
Nvim Version: 0.5.1

Hi Thank you for this great extension!

As the title says, I'm in trouble because cursor not moving.  
Other features are available.

https://user-images.githubusercontent.com/30979044/147377198-dfd06713-0ed3-43c2-8462-e3da199bbb7f.mp4

Do I need to configure vscode or nvim?

**Comment by vlwkaos** [comment]
Please read Readme of the repository.
AFAIK, you have to enable it for macOS.
