### ISSUE TITLE
Pressing <space> twice misbehaves in normal mode

### ISSUE THREAD

**Issue by adaitche** [vscode-neovim/vscode-neovim#793]
When I press \<space> twice (in normal mode), the letter before the cursor is replaced by `. ` (note the space at the end). Weirdly this happens only if I am inside a word, it doesn't happen if the cursor is at the beginning of a word. I have tried adding `nnoremap <Space> <NOP>` to my config, but to no avail.

I discovered this because I use \<space> as my leader key. However this weird behavior also appears if I set my leader key to something different than \<space>.

**Comment by fibbo** [comment]
I have the same observations, pressing space twice in normal mode completely looks nvim up. Other VSCode shortcuts still work but I can only get nvim to work again by completely restarting VSCode.

**Comment by theol0403** [comment]
Try with empty init.vim

**Comment by Alainx277** [comment]
This has nothing to do with this extension. It is a MacOS feature which is enabled by default.

[Related comment](https://github.com/VSCodeVim/Vim/issues/2108#issuecomment-347977957)
