### ISSUE TITLE
Installing vscode-neovim sends a jibberish print job to network connected printer

### ISSUE THREAD

**Issue by bysameng** [vscode-neovim/vscode-neovim#797]
Hello, happy new year all!

I was configuring vscode-neovim yesterday, until I was interrupted by my office printer that started printing page after page. What the heck was going on? I scrambled to the printer and found a huge stack of hard copies of some random jibberish. Weird.

Today, imagine my surprise when I was configuring vscode-neovim, my printer sprang to life again! Luckily it was out of paper!

I couldn't believe it, so I entirely reset my vscode. I uninstalled every plugin and reset all my settings.
Then I reinstalled the vscode-neovim plugin by itself. And there! Across the room, I hear my printer's mechanisms starting up.
I open the macOS print queue and see the 157 page pdf of jibberish. What wondrous magic of the holidays!

Visual Studio Code Version: 1.63.2
neovim 0.6.0 installed via brew
macOS Monterey 12.1
HP OfficeJet Pro 9010 connected via AirPrint (native macOS drivers)

https://user-images.githubusercontent.com/5396947/147835185-fb8f39e1-ab46-48fc-a767-d4bf4f17b791.mov

.

**Comment by kairyu** [comment]
Same here.

**Comment by davemo88** [comment]
Unfortunately I witnessed it happen to @bysameng firsthand

**Comment by theol0403** [comment]
If this somehow happens again... please reopen :)
