### ISSUE TITLE
Current file name in % register is invalid

### ISSUE THREAD

**Issue by DiogoDoreto** [vscode-neovim/vscode-neovim#798]
The percent register `%` has an invalid file name which makes it unusable.

For example, I wanted to quickly run my current file through node, so I ran the following command:

```
:! node %
```

which got expanded as:

```
VSCode-Neovim:

:! node __vscode_neovim__-file:///Users/path/to/my/file.js
```

That prefix obviously made the command fail. Is that a hard requirement to have to make this extension work?

**Comment by trkoch** [comment]
`%` is referring to the scratch buffer, see https://github.com/vscode-neovim/vscode-neovim#-how-it-works. I have my doubts this can be fixed.

**Comment by niklaswallerstedt** [comment]
Thanks for the link @trkoch, I understand the difficulty around this. The plugin makes vscode 10x better IMO 😄 but I ran into the same issue wanting to run updates on a csproj-file in `.Net`.

**Comment by trkoch** [comment]
Perhaps a Neovim plugin inlined in this extension could override `%` and remove the prefix? @asvetliakov Perhaps you can give us some hints as to why this prefix is required in the first place?

**Comment by filchristou** [comment]
is there a way to get the file path in nvim by any means? 

In vscode one can use the [predefined variables](https://code.visualstudio.com/docs/editor/variables-reference)
Is there a way to use these variables in nvim ?

**Comment by ambiguous48** [comment]
This is my current workaround for this issue. I named the script `vnr` (say 'vscode neovim replace'). If you prefix your command with `vnr`, it'll strip out `__vscode_neovim__-file://` then run your command.

https://gist.github.com/ambiguous48/234df06b9b915feead215152b78f92e4

```sh
# instead of this
:! node %

# do this
:! vnr node %
```

Note: you probably want to place this in your PATH so you can reference it directly.

**Comment by infinitewhileloop** [comment]
@thenbe Your solution is working great, thanks! It just seems like your link is broken, this one should work: https://gist.github.com/thenbe/234df06b9b915feead215152b78f92e4

An example of a mapping I created: `nnoremap <buffer> <Leader>r :exec '!vnr python3' shellescape(@%, 1)<CR>`
