### ISSUE TITLE
bug: Incorrect indentation after `o`

### ISSUE THREAD

**Issue by secretnonempty** [vscode-neovim/vscode-neovim#799]
Plugin version: v0.0.83

* Issue description
If the current line of a py file contains the char sequence :#, then when a user presses 'o' to insert a line below, the plugin would indent incorrectly.

To reproduce the issue, please follow the steps below:
1. Open a py file with vs code, for example, test.py, please note that it must be a file on the disk, otherwise you might not be able to reproduce the issue.
2.  type the following line in test.py:
```code
print( f'add {var:#x}' )
```
3. Then press <esc> to return to the normal mode, after which press 'o' to insert a new line below.
Expected effect: 
```code
print( f'add {var:#x}' )
|
```
the '|' sign represents the cursor.

The actual effect:
```code
print( f'add {var:#x}' )
          |
```

If we remove either ':' or '#' from the line, the issue would not occur.

**Comment by theol0403** [comment]
This is either caused by a bug in the cursor manager, or the lack of #519

**Comment by oberblastmeister** [comment]
Setting `filetype indent off` fixes this for me. I don't know why.

**Comment by xiyaowong** [comment]
Share my solution.
```lua
---@param key "o" | "O"
local function start_newline(key)
  return function()
    local check_line = ''
    if key == 'o' then
      check_line = vim.api.nvim_get_current_line()
    else
      check_line = vim.fn.getline(vim.fn.line('.') - 1)
    end
    vim.api.nvim_feedkeys(key, 'n', false)
    if check_line ~= '' and check_line:match('^[%s\t]*$') == nil then
      vim.defer_fn(function() vim.fn.VSCodeNotify('editor.action.reindentselectedlines') end, 100)
    end
  end
end
vim.keymap.set('n', 'o', start_newline('o'))
vim.keymap.set('n', 'O', start_newline('O'))
```

**Comment by xiyaowong** [comment]
Can't reproduce when enabling syntax

**Comment by baizeyv** [comment]
I just set `filetype indent off` and it solved my problem. It was  my mistake not to find this solution from the closed issue. I should have looked it up? Thanks, YOU ARE MY HERO , I will close this issue.
