### ISSUE TITLE
nmap J to PageDown behaves wired 

### ISSUE THREAD

**Issue by guopenghui** [vscode-neovim/vscode-neovim#800]
I want to use `J/K` to `PageDown/PageUp`，so set following commands in `init.vim`: 
```shell
nmap J <C-f>
nmap K <C-b>
```
It works well in neovim itself and other software with vim-mode. But in vscode, it jumps more than one page (nearly 100 lines, but one page is only 35 lines on my editor).
However, the original commands `Ctrl f / Ctrl b` and `PageUp / PageDown` works well. 
I don't know what happened : (

**Comment by theol0403** [comment]
#885

https://github.com/vscode-neovim/vscode-neovim/blob/253757630a75effe1566722ab01a50a673f9c108/vim/vscode-scrolling.vim#L38
https://github.com/vscode-neovim/vscode-neovim/blob/253757630a75effe1566722ab01a50a673f9c108/src/commands_controller.ts#L26

Basically the 100 lines thing is a product of the viewport and the scrolloff, and those links show you how you could fix it to be defined yourself.
