### ISSUE TITLE
Text is dark while typing in insert mode

### ISSUE THREAD

**Issue by qwerty-300** [vscode-neovim/vscode-neovim#801]
Hello, i'm using the neovim extension on vscode. When i'm typing out code in insert mode, the text is dark, and only becomes visible once i exit insert mode. Here's a short video demonstrating what i mean:

https://user-images.githubusercontent.com/75761281/149023714-9dc0c207-26d7-42c4-9380-cba20d80606c.mp4

You can see how this can be frustrating, and makes it difficult to code with the neovim extension

Operating system: Fedora Linux
Neovim version: NVIM v0.6.1

**Comment by plundration** [comment]
Hello, having the same issue.

OS: Garuda Linux
Neovim version: NVIM v0.6.1

**Comment by plundration** [comment]
@querty-300 are you using an init.vim file? When I removed some stuff from it, the issue disappeared... I think it was somethign with Coc...

**Comment by theol0403** [comment]
Yes, try with empty init.vim
