### ISSUE TITLE
Neovim Main controller cant connect

### ISSUE THREAD

**Issue by phortonssf** [vscode-neovim/vscode-neovim#802]
I have WSL2 with neovim, the extension used to work, but now I get the following error.
`2022-01-18T00:29:58.319Z MainController: Neovim exited with code: 0`

My vscode settings.json
`  "vscode-neovim.logPath": "/home/digitaldive/.dotfiles/vscode.txt",
  "vscode-neovim.useWSL": true,
  "vscode-neovim.mouseSelectionStartVisualMode": true,
  "vim.enableNeovim": true,
  "vim.neovimPath": "/usr/local/bin/nvim",
  "vscode-neovim.neovimExecutablePaths.linux": "/usr/local/bin/nvim",
  "vscode-neovim.neovimInitVimPaths.linux": "/home/digitaldive/.dotfiles/init.vim",
`
In wsl **which nvim** = /usr/local/bin/nvim
My real lua.init is wrapped in if(not vim.g.vscode) and my **init.vim** that I point the neovim vscode extension too is empty.

**Comment by DNLHC** [comment]
Make sure the distro you're running from is set as the default in WSL

`wsl -s <Your Distro>`

**Comment by snaka** [comment]
I had a similar problem, but it was due to the fact that the distribution that NeoVim was installed on was different from the default distribution in wsl.

I had NeoVim installed on `Ubuntu-20.04`.

So I used the following command to change the distribution used by default in WSL, which solved my problem.

```
wsl -s Ubuntu-20.04
```

**Comment by milanglacier** [comment]
I'm in macOS and I have the same issue.
It does not always occur, but it occurs more frequently than before, especially when I am using jupyter notebook within vscode. The problem appears someday I update the vscode version.
