### ISSUE TITLE
Mapping jj or jk disables use of colon.

### ISSUE THREAD

**Issue by JakeDevs** [vscode-neovim/vscode-neovim#809]
Steps to reproduce: Copy the binding for jj or jk for normal mode and paste it in your keybind.json.  You can no longer type colons.

**Comment by theol0403** [comment]
Cannot reproduce. Please add more information and try with empty init.vim.

**Comment by JakeDevs** [comment]
> 

hi, i found out the bug only happens if you also map jj or jk in your neovim confing and your vscode config. you cant use both.

**Comment by theol0403** [comment]
Still can't reproduce
