### ISSUE TITLE
Unable to send <C-y> to vim

### ISSUE THREAD

**Issue by nerdo** [vscode-neovim/vscode-neovim#811]
I'm trying to use https://github.com/mattn/emmet-vim from vscode-neovim and it seems like the `<C-y>` or maybe the combination of the chord of `<C-y>,` isn't getting picked up by vim in insert mode.

Is there a way to get this working?

**Comment by theol0403** [comment]
This plugin is not active during insert mode, see the readme. Just use vscode emmet.
