### ISSUE TITLE
Some key mappings do not work in VSCode

### ISSUE THREAD

**Issue by yayiji** [vscode-neovim/vscode-neovim#812]
The following key mappings do not work in VSCode (I have removed duplicate keys from VSCode) but work fine in native Neovim.

```
nnoremap <C-f11> 5j
nnoremap <C-f12> 5k
nnoremap <A-f11> 5j
nnoremap <A-f12> 5k
```

**Comment by theol0403** [comment]
You need to send the keys from vscode to neovim as shown in https://github.com/vscode-neovim/vscode-neovim#custom-keybindings
