### ISSUE TITLE
editor.action.blockComment doesn't receive visual mode selection

### ISSUE THREAD

**Issue by hackel** [vscode-neovim/vscode-neovim#813]
If I select something in visual block mode and try to use <C-S-/> for VSCode's built-in editor.action.blockComment action, I just get `/*   */` inserted wherever my cursor was (at the start or end of my selection), and the selection remains highlighted and uncommented.  I would love to see this implemented over having to use a third-party extension like vim-commentary.

**Comment by jdix531** [comment]
I also run into this issue. If I select multiple lines in visual (or visual block) and hit the comment hotkey it only comments the line where the cursor currently is. Can provide more details if requested.

**Comment by yayiji** [comment]
+1

**Comment by 1-800-jono** [comment]
I'm having the same issue.

**Comment by bhuynhdev** [comment]
Fixes in these links have worked for me: https://github.com/vscode-neovim/vscode-neovim/issues/199#issuecomment-1006685895 and https://github.com/vscode-neovim/vscode-neovim#vim-commentary

**Comment by BTBMan** [comment]
+1

**Comment by BTBMan** [comment]
It works for me!

```vim
" do something in visual mode
function! s:VSCodeNotifyInVisual(cmd, leaveSelection, ...)
    normal! gv

    let mode = mode()

    if mode ==# 'V'
        let startLine = line('v')
        let endLine = line('.')
        call VSCodeNotifyRange(a:cmd, startLine, endLine, a:leaveSelection, a:000)
    elseif mode ==# 'v' || mode ==# "\<C-v>"
        let startPos = getpos('v')
        let endPos = getpos('.')
        call VSCodeNotifyRangePos(a:cmd, startPos[1], endPos[1], startPos[2], endPos[2] + 1, a:leaveSelection, a:000)
    else
        call VSCodeNotify(a:cmd, a:000)
    endif
endfunction

 map <silent> gC <ESC><Cmd>call <SID>VSCodeNotifyInVisual('editor.action.blockComment', 1)<CR><ESC> " block comment
```

**Comment by cupcakearmy** [comment]
A (maybe) interesting side note:

If I select some lines (`Shift + V` then `j/k`) and press `command + /` it only comments the current line where the cursor is.
However if i select some lines and the search `Toogle Line Comment` in the command palette (which is the same command used by the `command + /` shortcut it works.

**Comment by theol0403** [comment]
Visual selection is only send to vscode in specific situations, like the C-S-P for commands. 

`VSCodeNotifyInVisual` actually exists in the plugin, called `VSCodeNotifyVisual`. 

Maybe you just have to send this as well:

```json
{
  "command": "vscode-neovim.send",
  "key": "cmd+/",
  "when": "editorTextFocus && neovim.init && neovim.mode != insert && neovim.ctrlKeysNormal",
  "args": "<C-/>"
},
```
