### ISSUE TITLE
Use I-Beam cursor in insert mode

### ISSUE THREAD

**Issue by cirelli94** [vscode-neovim/vscode-neovim#814]
Is it possible to use the I-Beam cursor in insert mode instead of the block?

**Comment by justinmk** [comment]
that already works, and is controlled by vscode. If it doesn't work, it's your config.

**Comment by mathstylish** [comment]
When i press "i" for insert, the cursor is I-Beam, however if i press "a, o, A.." the cursor is block. How can i  get rid of this??
