### ISSUE TITLE
Question: How to use temporary Visual mode when selecting with mouse/trackpad?

### ISSUE THREAD

**Issue by tobealive** [vscode-neovim/vscode-neovim#817]
Hello dear community, having trouble enabling the feature myself I'm hoping to find a little help or a  hint here.

The desired functionality is when using normal- / insert mode and click selecting text, to temporarily enable visual mode for the selection.  In vim / nvim outside of _Code_, it is possible to achieve this when using _mouse support_ (e.g. `set mouse=nv`). The regular vscodevim extension has this enabled by default even though `set mouse` is not available when trying to use the command. I'm probably a bit blind-sighted currently that I can't quite understand the functionality behind it.

Wishing all the best 🙌.

**Comment by theol0403** [comment]
This was recently fixed in https://github.com/vscode-neovim/vscode-neovim/pull/723, but it has not been released yet.

**Comment by tobealive** [comment]
thank you my friend
