### ISSUE TITLE
[coc.nvim]: Error on "codeAction": current buffer 4 not attached

### ISSUE THREAD

**Issue by psilospore** [vscode-neovim/vscode-neovim#822]
When I try to use any plugin that shows a pop up such as coc.nvim or fzf.vim I won't see the an error about a current buffer that is not attached. Would those plugins not be compatible with this extension?

**Comment by throwaway69420-69420** [comment]
they aren't compatible with the extension afaik

**Comment by justinmk** [comment]
dear god, people. vscode already has LSP support.

if you want to use insert-mode plugins, use terminal `nvim` instead of a vscode embedded Nvim.

**Comment by psilospore** [comment]
Wish I could have the features of liveshare in nvim so I can pair with my coworkers. Otherwise I wouldn't need to use vscode.

Thanks for working on the project but no reason to be such a jerk.

**Comment by justinmk** [comment]
So then use vscode LSP. There is zero reason for vscode-neovim to deal with the complexity of supporting Vim insert-mode plugins. Letting vscode handle insert-mode is a fantastic tradeoff.
