### ISSUE TITLE
Use ctrl-T to go back after go to definition

### ISSUE THREAD

**Issue by kflu** [vscode-neovim/vscode-neovim#823]
In vim, neovim, vscode vim, etc, Ctrl-T is used to navigate back from where a go to definition (or go to tag) was initiated:

```
g<RightMouse>						*g<RightMouse>*
<C-RightMouse>					*<C-RightMouse>* *CTRL-T*
CTRL-T			Jump to [count] older entry in the tag stack
			(default 1).
```

However this doesn't seem to work in vscode neovim. Is there a way to customize/configure this?

**Comment by kflu** [comment]
I was able to work around this by defining the following in the `keybindings.json`:

```
     {
        "command": "workbench.action.navigateBack",
        "key": "ctrl+t",
        "when": "editorTextFocus && neovim.mode == normal"
    }
```

**Comment by kflu** [comment]
I tried to add it as a builtin keybinding (in vscode-neovim/pull/827), but wasn't successful. I documented the failed reason in the PR - can someone help take a look?

**Comment by xiyaowong** [comment]
working fine
