### ISSUE TITLE
[Bug?] Moving Multiple Lines? 

### ISSUE THREAD

**Issue by tobealive** [vscode-neovim/vscode-neovim#825]
I tried to get it working, unfortunately to no avail, so I'm writing in hope that maybe some can help to figure it out. 
The goal is to move multiple lines when selected in visual mode. When mapping the standard vscode command  ` "command": "editor.action.moveLinesDownAction"` to e.g. `<A-j>` it's only the line the cursor is currently on that moves, even when multiple lines are selected in visual mode.

What's funny though is that entering the `:` vim command  used in my init.vim for moving multiple lines it works flawlessly. I couldn't figure out where it gets stuck when trying to use keyboard shortcuts to move lines. 
The commands I'm using:
```
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
inoremap <A-j> <Esc>:m .+1<CR>==gi
inoremap <A-k> <Esc>:m .-2<CR>==gi
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv
```
Works with standard neovim/neovide and in vscode-neovim when entered like `:m '<-2<CR>gv=gv`. Also tried to make it work with the vim-move plugin. 

So, if it is somehow possible to map a command execution like this to a shortcut directly inside vscode when using vsvode-neovim it would probably be one solution to solve this. Is that possible? 

Best regards

**Comment by tobealive** [comment]
checked again, it's working using another key then the alt key (tried with ctrl). Already did before and checked agin for conflicting vscode mappings with the alt key but didn't find none. Could you think of a solution to make work using the alt modifier?

**Comment by orbitoo** [comment]
Oh, I'v got a problem much alike recently.
```vim
xnoremap <leader>s <Cmd>call VSCodeCallVisual('latex-workshop.surround',1)<CR>
```
I added this line to my init.vim and it surrounds not actually what I've selected in v mode but with a little offset.
If I just use v mode to select and use ctrl+shift+p to call it, it will work flawlessly as well...
I tried to remap it to other keys but doesn't get solved.

**Comment by theol0403** [comment]
@tobealive 

- nvim-only solution (like vim-move, your bindings, etc) should work
- to map something with `<A-j>`, you need to send the key to nvim though vscode keybindings
- to use vscode solution, use

```vim
xnoremap <A-j> <Cmd>call VSCodeCallVisual('editor.action.moveLinesDownAction',1)<CR>
```

it seems pretty buggy though. 


@orbitoo what direction is this offset?

It might be related to https://github.com/vscode-neovim/vscode-neovim/pull/310/.

**Comment by orbitoo** [comment]
> 
Hello, here's my init.vim...
```vim
xnoremap <leader>s <Cmd>call VSCodeCallVisual('latex-workshop.surround',1)<CR>
```
I'll show you.
I guess it was due to Chinese characters...
I use v mode to select the word "函数" and it results in wrapping ", 如果"
![bandicam 2022-04-30 14-05-29-170_7](https://user-images.githubusercontent.com/86230731/166094456-2f6eb792-13b4-473d-a54f-2aff5e0f04d5.gif)

**Comment by theol0403** [comment]
Ah, yeah currently Chinese characters breaks the extension in a couple ways.

**Comment by orbitoo** [comment]
> Ah, yeah currently Chinese characters breaks the extension in a couple ways.

So, might there be a way to fix this?
This function is quiet convenient and I don't feel like to use my mouse to select, because it just breaks my workflow...

**Comment by JuanAKAJuan** [comment]
Adding these lines to my init.lua file makes it so I can move blocks of lines while they are selected in insert mode. It is a little choppy graphically, but it does what I need it to do.
`vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")`

**Comment by tobealive** [comment]
Hey thanks for the message @JuanAKAJuan. The <rhs> of the command is exactly the same as the one in the issue opening isn't it? You should still run into issue with afaik.
