### ISSUE TITLE
Scroll offset in .vimrc / init.lua doesn't work 

### ISSUE THREAD

**Issue by diningPhilosopher64** [vscode-neovim/vscode-neovim#828]
The `scrolloff` command ie. scroll offset doesn't seem to work. 

It works as expected in neovim but not in VSCode with neovim extension.

**Comment by trkoch** [comment]
Use native `editor.cursorSurroundingLines` instead.

**Comment by diningPhilosopher64** [comment]
Thank you. Works as expected!
