### ISSUE TITLE
Erroneously selects the last character of the line when clicking in edit mode

### ISSUE THREAD

**Issue by metasprite** [vscode-neovim/vscode-neovim#832]
Let's say you're in edit mode and you move to the end of line 5 with your mouse, you do this by moving your mouse past the last character of the line and clicking. If your mouse stays perfectly still when clicking, all goes well.

But if your mouse moves even a single pixel(!) while clicking, it will select the last character of the line. This seems to be because `vscode-neovim` want the cursor on last character of the line, but the mouse moving even a single pixel while clicking _pulls the cursor forward past the last character_.

```
int a;   <- clicking at the end of the line can cause ; to be selected if you accidentally move your mouse 1 pixel while clicking

vscode-neovim wants cursor here:
int a|;

but moving the mouse a pixel makes it go here, causing an accidental selection of the semicolon:
int a;|
```

And when entering insert mode, this selection is not erased. This leads to situations where I click somewhere, enter insert mode, press enter to add a new line, and suddenly realize that a semicolon on the previous line is missing - because I accidentally selected it earlier due to this bug.

Here's a video: https://streamable.com/bnuos7

**Comment by theol0403** [comment]
I can't reproduce anymore - does this still happen?

**Comment by tedbyron** [comment]
> I can't reproduce anymore - does this still happen?

yes

**Comment by theol0403** [comment]
Don't think this is something we can avoid. However, this should be improved by the pending visual selection PR.
