### ISSUE TITLE
API call: Invalid buffer id: 2 on mac

### ISSUE THREAD

**Issue by dumitrandrei** [vscode-neovim/vscode-neovim#833]
On windows, vscode-neovim works like a charm although, on mac I always get the following error when launching VSCode: 
`Unable to init vscode-neovim: nvim_call_function: Vim(call):E5555: API call: Invalid buffer id: 2`
Same init.vim on both windows and mac..
I have reinstalled nvim, the extension, and vscode.
I have tried with empty init.vim file - same error.

![image](https://user-images.githubusercontent.com/92296221/155873134-0f9a07e3-9fb5-48c2-82be-26977c005ed5.png)

**Comment by Damaged-Code** [comment]
I have a almost same  error,same on mac, I think maybe is buffer manager have some problem

**Comment by tobealive** [comment]
Same here on linux. Extensions seems still totally unusable

**Comment by justinmk** [comment]
> Is there a way or workaround to define a separate data dir for one of the nvim instances, either vscodes or regular nvims? To be able keep an instance for both nvim configurations?

https://github.com/vscode-neovim/vscode-neovim#conditional-initvim

**Comment by tobealive** [comment]
> > Is there a way or workaround to define a separate data dir for one of the nvim instances, either vscodes or regular nvims? To be able keep an instance for both nvim configurations?
> 
> https://github.com/vscode-neovim/vscode-neovim#conditional-initvim

Yes that's what I'm doing and tried to apply in different variations to make it work. This is changig the config file but the data dir remains the same.  But this doesn't change the data dir check `h: *$XDG_CONFIG_HOME*` `:h *$XDG_DATA_HOME*.

**Comment by tobealive** [comment]
A workaround, at least on linux, and pretty dirty though, is using a flatpak nvim installation for a regular nvim setup. Then having a nvim binary, .deb, .rpm or whatever installation free to use with vscode-nvim.

A side effect is the configuration of the flatpak instance. Some plugins don't want to use the flatpaks data dir by default instead they try to force the $XDG_DATA_HOME. Furthermore,it is  some workload getting your path variables properly working with flatpaks.
