### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by sumandroid12** [vscode-neovim/vscode-neovim#834]
Okay I am big noob and know nothing about javascript/electron/vscode ecosystems. How do I install the master branch? There have been some important fixes which have not been released..

**Comment by justinmk** [comment]
Unfortunately you will need to build the project and then `Install from VSIX` in vscode.

Would be great if CI were setup so that VSIX files were produced automatically, but that isn't the case yet.

**Comment by justinmk** [comment]
https://github.com/vscode-neovim/vscode-neovim/pull/874 updates the readme, here's the steps meanwhile:

(you will need to manually install `yarn` and `vsce` until that PR is merged)

> How to build (and install) from source:
> 
> 1. Clone the repo locally.
>    ```
>    git clone https://github.com/vscode-neovim/vscode-neovim
>    ```
> 2. Install the dependencies.
>    ```
>    npm install
>    ```
> 3. Build the VSIX package:
>    ```
>    ./node_modules/.bin/yarn run vsce package -o vscode-neovim.vsix
>    ```
> 4. From vscode, use the `Extensions: Install from VSIX...` command to install the package.

**Comment by justinmk** [comment]
CI is uploading artifacts. It's kinda non-obvious, but there is an Artifacts section at the bottom of each CI run. Example: https://github.com/vscode-neovim/vscode-neovim/actions/runs/2217166790

<img width="663" alt="image" src="https://user-images.githubusercontent.com/1359421/165013276-4e5607dd-b2a6-42d5-b693-0418e4a2411d.png">
