### ISSUE TITLE
how to yank from VSCode neovim to system clipboard? 

### ISSUE THREAD

**Issue by ChaoXu1997** [vscode-neovim/vscode-neovim#835]
## how to yank from VSCode neovim to system clipboard? 
How can I select using the `V mode` and `y` to yank  in the text and then `ctrl + v` paste in the terminal

**Comment by echaya** [comment]
https://stackoverflow.com/questions/3961859/how-to-copy-to-clipboard-in-vim

Essentially, you need to share the nvim's clipboard with the OS one.

**Comment by throwaway69420-69420** [comment]
I use this in my init.vim

``` 
let mapleader = ";"

" system clipboard
vmap <leader>y "+y
vmap <leader>d "+d
nmap <leader>y "+yy
nmap <leader>p "+p
nmap <leader>P "+P
vmap <leader>p "+p
vmap <leader>P "+P
```

**Comment by echaya** [comment]
does the settings above give you access of clipboard in nvim?

**Comment by throwaway69420-69420** [comment]
no, it does not

**Comment by echaya** [comment]
> no, it does not

It means it is not properly set up and thus it is not plug-in related. My suggestion is to revisit the following posts:
https://stackoverflow.com/questions/3961859/how-to-copy-to-clipboard-in-vim
and
https://vim.fandom.com/wiki/Accessing_the_system_clipboard

below is what i have on my .vimrc and it works fine for me. But what I want is different (using ctrl+v to trigger paste in `insert mode`)

```vim
set clipboard=unnamed
inoremap <silent> <c-v> <Esc>:set paste<Cr>a<c-r>+<Esc>:set nopaste<Cr>a
```

Also as a best practice, try to map your `<leader>` to  `<Nop>` first.

**Comment by justinmk** [comment]
don't ask usage questions on the issue tracker.

**Comment by throwaway69420-69420** [comment]
@justinmk where to ask it?

**Comment by theol0403** [comment]
If it works in terminal nvim, it should work in vscode-nvim. Try to get the former working first.

**Comment by hrai** [comment]
I am on Windows and was using WSL nvim. After I switched to local windows install of nvim, the clipboard started working with the suggested changes above.

**Comment by 0x4richard** [comment]
I'm using MacOS and this one works for me. 

```vimrc
"clipboard
  if has("clipboard")
    if has("unnamedplus")
      " When possible use + register for copy-paste
      set clipboard=unnamed,unnamedplus
    else
      " On mac and Windows, use * register for copy-paste
      set clipboard=unnamed
    endif
  endif
```

**Comment by iosifzota** [comment]
If someone wants to use init.lua this is what worked for me:
vim.o.clipboard = 'unnamedplus'

(note: for me pressing "+yy does copy line into system clipboard)
