### ISSUE TITLE
No undo points when moving cursor in insert mode

### ISSUE THREAD

**Issue by NeoRaider** [vscode-neovim/vscode-neovim#84]
When moving the cursor in insert mode using the arrow keys (or the mouse, when mouse support is enabled), (n)vim creates an undo point for each move. This does not work in vscode-neovim.

**Comment by asvetliakov** [comment]
>When moving the cursor in insert mode using the arrow keys (n)vim creates an undo point for each move.

wow, I didn't know !! Anyway, this won't be fixed probably until there will be character range insert support/sending updates as edits API in neovim, see [this comment](https://github.com/asvetliakov/vscode-neovim/issues/76#issuecomment-562903490)

**Comment by NeoRaider** [comment]
Wouldn't it be possible to do whatever happens when the insert mode is left each time the cursor moves while in insert mode (if something was edited)? Or would it just not make sense to implement it based on current APIs, as it would be replaced soon anyways?

**Comment by asvetliakov** [comment]
yes, it's possible. I'd wait a little though - sending insert mode changes as edits immediately will solve many problems with cleaner way
