### ISSUE TITLE
Cursor movement is not recorded in complex macros.

### ISSUE THREAD

**Issue by PMuril** [vscode-neovim/vscode-neovim#841]
Here by _complex_ I mean a macro that itself invokes a macro.
Whenever I try to record a macro that chains the effect of multiple macros the in-between movement of the cursor is not recorded.
The same macro when executed in a plain Neovim instance runs smoothly.

**Comment by theol0403** [comment]
This is too complicated of an edge case to fix

**Comment by theol0403** [comment]
The double recording issue might be caused by https://github.com/vscode-neovim/vscode-neovim/blob/f6cae671085cf61f33634f1efea4682b3325148d/vim/vscode-neovim.vim#L157
