### ISSUE TITLE
Snippet plugins seem not to work

### ISSUE THREAD

**Issue by PMuril** [vscode-neovim/vscode-neovim#842]
The integration of the extension with all of my other Neovim plugins is seamless, however I cannot trigger the insertion of any code snippet.
I have currently tried both Ultisnips and Snipmate with no results.
Is the behavior expected?
I read the documentation and searched through the other issues here on Github but I've got no clues.

**Comment by DeadlySquad13** [comment]
I think default vscode snippet engine was supposed to be used.

**Comment by justinmk** [comment]
The key tradeoff made by this plugin, and mentioned in the readme, is that insert-mode is controlled by vscode. Using a vscode snippet plugin.
