### ISSUE TITLE
Why there is a ‘呐’ in vscode status bar shows as a vscode neovim item?

### ISSUE THREAD

**Issue by RekiDunois** [vscode-neovim/vscode-neovim#843]
<img width="331" alt="image" src="https://user-images.githubusercontent.com/23435534/160082413-3f22ecb0-593a-4105-997d-2a105edfd085.png">
when I enter insert mode, and then back to normal mode, it just gone.

what does '呐' means?

**Comment by theol0403** [comment]
Can't reproduce. Might be something in your init.vim
