### ISSUE TITLE
unable to use tpope/vim-surround plug

### ISSUE THREAD

**Issue by waltiam** [vscode-neovim/vscode-neovim#844]
I have been using this plug in previous versions.

I have the init.vim correctly configured (the plugin works with nvim) from the console.

I'm using the dein plugin manager.

I know the init.vim is being loaded from vscode.

I'm just not getting the surround functionality in vscode.

**Comment by waltiam** [comment]
Seems if you leave the path to the init.vim file black - it loads fine.

**Comment by ianchanning** [comment]
> Seems if you leave the path to the init.vim file black - it loads fine.

Indeed I did the same and it worked nicely.

It is really really hard to tell if a plugin is loading though. There's practically no output from `vim-plug`.

Running `PlugInstall` hangs and does appear to have installed all the plugins I have.

I'll add here quickly my plugins setup as I'm using vim-surround, and a bunch of Tim Pope plugins.

I'm on Linux / Ubuntu 22.04, with nvim installed via `apt` with [`ppa-neovim/unstable`](https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable).

I moved from Vim to Neovim and I still use my `.vimrc` and amazingly this kind of setup seems to work with vscode-neovim too.

I have the following `~/.config/nvim/init.vim`:

```vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
if exists('g:vscode')
    " VSCode extension
    source ~/.vimrc.vscode
else
    " ordinary Neovim
    source ~/.vimrc
endif
```

This happily loads my `~/.vimrc` file for terminal `nvim` and then loads `~/.vimrc.vscode` for vscode-neovim - which also appears to load:

1. It sets my leader to `<space>` 
2. It loads Plug
3. It loads my custom key mappings 
4. It loads `vim-surround` and and `vim-repeat`
    1. I know it loads these because I have a command `map <leader>' ysiw'` 
    2. This puts single quotes around the current word
    3. This works (so `vim-surround` works)
    5. I can then 'repeat' my adding quotes with `.` which means `vim-repeat` is working in combination with it.

I have massively stripped my `.vimrc` file down:

```vim
let data_dir=has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

set nocompatible
call plug#begin('~/.vim/bundle')

Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-commentary'
call plug#end()

nnoremap <space> <nop>
let mapleader="\<space>"
let g:mapleader="\<space>"

set encoding=utf8 " Set utf8 as standard encoding and en_US as the standard language
set fileformats=unix,dos,mac " Use Unix as the standard file type
set hlsearch " Highlight search results
set incsearch " Makes search act like search in modern browsers
set nobackup
set nowritebackup
set noswapfile

try
    autocmd FileType php setlocal commentstring=\/\/\ %s
    autocmd FileType javascript setlocal commentstring=\/\/\ %s
    autocmd FileType reason setlocal commentstring=\/\/\ %s
    autocmd FileType dosbatch setlocal commentstring=rem\ %s
    autocmd FileType rust setlocal commentstring=//\ %s
catch
endtry

map <leader>' ysiw'
map <leader>" ysiw"

map <leader>; A;<esc>
map <silent> <leader><cr> :nohlsearch<cr>
nnoremap <leader>bb :buffers<cr>:b<space>
map <leader>s :w<cr>
```
