### ISSUE TITLE
Mouse selection not working despite setting `vscode-neovim.mouseSelectionStartVisualMode` enabled

### ISSUE THREAD

**Issue by bhuynhdev** [vscode-neovim/vscode-neovim#848]
I have turned on my "Mouse selection start Visual Mode" setting. However, In Normal mode, when I select text with mouse and press <kbd>x</kbd>, only the first character of the Visual selection gets deleted.

I have recorded a Loom Video: https://www.loom.com/share/bcccd2bbfdbc4eb2b1afd8d9a77ba430

This is my `init.vm`
```
set clipboard=unnamedplus

xmap gc  <Plug>VSCodeCommentary
nmap gc  <Plug>VSCodeCommentary
omap gc  <Plug>VSCodeCommentary
nmap gcc <Plug>VSCodeCommentaryLine
```

My VsCode's `settings.json`
```
"vscode-neovim.mouseSelectionStartVisualMode": true,
"vscode-neovim.useCtrlKeysForInsertMode": false
```

**Comment by trkoch** [comment]
It's a known issue (look around the issue tracker) and currently not well supported.

**Comment by theol0403** [comment]
Should be fixed in latest release

**Comment by trkoch** [comment]
For clarification to the casual reader, this is "fixed" in the sense that this setting now has *any* effect. It is not "fixed" in the sense that it is working properly.
