### ISSUE TITLE
Enter/Esc keys to edit/leave Jupyter cell don't work

### ISSUE THREAD

**Issue by maciejzj** [vscode-neovim/vscode-neovim#849]
The Jupyter Notebooks built into vscode come with enter binding to start editing the current code cell and esc to leave it. The enter keybing is also hinted by the editor when clicking a markdown cell and hovering over "pencil" "edit" glyph on the right saying "Edit Cell (Enter)". Unfortunately the vscode-neovim breaks these shortcuts making it more necessary to use mouse.

**Comment by jnzd** [comment]
I'm facing this same issue. The workaround I'm currently using is remapping the keyboard shortcuts for these actions of the notebooks extension.

"Notebook: Stop Editing Cell" is mapped to Escape by default. You can map this to any shortcut not used by NeoVim and it should work. I'm using "Shift + CapsLock".
"Notebook: Edit Cell" is mapped to Enter by default and I've mapped it to "Ctrl + Shift + Enter".

I'm less sure why the NeoVim extension overwrites the Enter shortcut to edit a cell. Escape not working makes sense, given that Escape is used to enter normal mode. Though I believe the desired behavior should be that pressing escape once in insert mode should bring you to normal mode and pressing it again should leave the cell editor.

**Comment by maciejzj** [comment]
This must have been resolved by some update (dunno which one), but I noticed now Enter/Esc keys work marvelously without any custom remaps.
