### ISSUE TITLE
Some questions regarding this extension

### ISSUE THREAD

**Issue by Raj2032** [vscode-neovim/vscode-neovim#851]
Hey guys I have some questions regarding this extension:
1. If I installed this extension as well as `neovim` on Windows, then I am able to use all the shortcuts `vim` has to offer as well as I would get the usual `visual`, `normal` and `edit` mode?
2. If `1` is true, then if I am in `insert` mode, am I able to still use `ctrl`+`c` and `ctrl`+`v`, you know like use `vscode` like a normal text editor?

**Comment by nokia-git** [comment]
yes

**Comment by Raj2032** [comment]
Ok thanks mate

**Comment by justinmk** [comment]
It takes like 5 minutes to just try it and find out.
