### ISSUE TITLE
How to reload `init.vim` without restarting VSCode?

### ISSUE THREAD

**Issue by wenfangdu** [vscode-neovim/vscode-neovim#854]
Every time I modified `init.vim`, had to restart VSCode for the change to take effect, is there a built-in way to do so?

If not, please consider this a feature request for such a function 🙏.

**Comment by bva99** [comment]
I have found two options, though they both aren't ideal:

1- Disable and reenable the VSCode Neovim extension
Go to the extensions window (or hit Ctrl+Shift+x) then right click VSCode Neovim extension and Disable it. This requires a Reload. Then right click and enable it.

2- Reload the VSCode window, which reloads all extensions automatically
Go to View -> Command Pallete... (or hit Ctrl+Shift+p). Then type "reload" and select "Reload Window".

But these reloads are almost the same as restarting, so yeah, being able to modify `init.vim` without any reloads would be great.

**Comment by wenfangdu** [comment]
I use `map <silent> <leader>r :source $MYVIMRC<cr>` to reload `init.vim` without restarting VSCode, my leader key is space, in this case, space + r.
