### ISSUE TITLE
Highlight yank

### ISSUE THREAD

**Issue by bva99** [vscode-neovim/vscode-neovim#856]
I cannot get highlighted yank to work.

The general way to do so in Neovim (mine is version 0.5) is by adding the following to init.vim:
```vim
augroup highlight_yank
    autocmd!
    autocmd TextYankPost * silent! lua require'vim.highlight'.on_yank("IncSearch", 1000)
augroup END
```
But that doesn't work.

**Comment by jonz94** [comment]
I have same issue today when I trying to do the same thing.

After some googling I found [this comment on reddit](https://www.reddit.com/r/neovim/comments/gofplz/comment/g5sgtjp/?utm_source=share&utm_medium=web2x&context=3) and it mentions that the syntax has change a little bit.

So I change the settting to the following:
```nvim
augroup highlight_yank
    autocmd!
    au TextYankPost * silent! lua vim.highlight.on_yank { higroup="IncSearch", timeout=1000 }
augroup END
```

and the highlight yank works as expected!

**Comment by bva99** [comment]
That solves the issue! Thanks!

**Comment by karmaral** [comment]
I'm not sure if that fixed it (can't reproduce it right now) but this solution wasn't working for me until I changed `lua` for `:lua`.
