### ISSUE TITLE
How to set Visual mode selection (and other) colors?

### ISSUE THREAD

**Issue by yanshay** [vscode-neovim/vscode-neovim#861]
Visual mode selection uses white background (unlike standard VSCode selection) and when the text is white I can't see the selected text which makes it unusable. Also, when the file have Syntax Highlighting (su multiple colors) I do see the text but not very good, depending on the colors.

How can I customize the colors? I tried the highlight commands (Visual and others) but they don't seem to work and I couldn't find any VSCode settings either. I tried looking at the source code and it seems there is some code that deals with color codes conversion of various highlights but the commands just don't seem to have any effect on VSCode (while the same commands do affect a standard Neovim).

So how can I set colors for the selection as well as potentially other VSCode/Neovim colors?

**Comment by justinmk** [comment]
this isn't a support channel

**Comment by yanshay** [comment]
Actually, I believe this is a bug. Instead of doing reverse of colors like VSCode selection does vscode-neovime just change the background to white, so when the text is white it can't be seen.

Just before filing a bug I wanted to verify I'm not missing any setting (my guess I don't miss and it is a bug).

So should I file this as a bug instead?

**Comment by theol0403** [comment]
On my system, the nvim visual selection uses the same highlight as vscode's selection. You might have weird syntax highlighting coming from your init.vim.

**Comment by yanshay** [comment]
@theol0403 Does it use both the same background and foreground? So the Visual mode selection alters the foreground color of the text like VSCode selection does?

**Comment by theol0403** [comment]
This shows nvim's visual selection and then vscode's selection.


https://user-images.githubusercontent.com/16546293/165633449-b7dbe32f-be33-4a35-8d0c-bae381ea9f03.mp4
