### ISSUE TITLE
Scroll offset ignored when scrolling by pages

### ISSUE THREAD

**Issue by eEQK** [vscode-neovim/vscode-neovim#867]
I've changed scroll offset in vsc as well as in nvim to 15.

It works correctly when scrolling with `hjkl`, but when I press C-d or C-u -- the cursor behaves as if the offset was 0. When I press either of `jk`, the cursor jumps to the correct offset.

Executing `:set so=15` does not help.

I'd expect the cursor to keep the offset at all times.

```
vscode-neovim: v0.0.83
vscode: 1.66.2
neovim: v0.6.1
```

**Comment by theol0403** [comment]
Scrolloff is forced by the plugin. C-d and C-u are currently implemented in vscode and ignore scrolloff. This issue can either not be fixed, or will inadvertently be fixed by #867
