### ISSUE TITLE
Doesn't work with Chinese characters

### ISSUE THREAD

**Issue by wenfangdu** [vscode-neovim/vscode-neovim#871]
`f` works with Chinese characters in native Neovim:

![STG 2022-04-24 12_40_31](https://user-images.githubusercontent.com/28700378/164956959-f6c59f6d-a5b9-42fb-bea7-b3803f00a50a.gif)

But doesn't work in vscode-neovim:

![STG 2022-04-24 12_43_21](https://user-images.githubusercontent.com/28700378/164957029-2f81d645-5c35-44d6-b874-0bb75b5c99af.gif)

The same applies to `r`, `F` etc.

**Comment by orbitoo** [comment]
Sorry to bother but, I wanna ask how to use f to find a Chinese character in neovim? I'm a neovim user, and recently I turned to VSCode and I've never known neovim has this function at all...

**Comment by wenfangdu** [comment]
@orbitoo Neovim natively supports it, give it a try.

**Comment by chase** [comment]
This would require using something like [`beforeinput`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/beforeinput_event) to capture the [IME](https://www.google.com/inputtools/services/features/input-method.html) events.

Basically input would require not being sent to neovim until the IME event is finished.

**Comment by doongjohn** [comment]
korean input is also not working properly

**Comment by theol0403** [comment]
@chase @doongjohn would you be able to try https://github.com/vscode-neovim/vscode-neovim/pull/1009

**Comment by wenfangdu** [comment]
Seems like #1009 fixed this issue.
