### ISSUE TITLE
`noremap <silent> <leader>e :edit $MYVIMRC<cr>` opens new file not the existing `init.vim`

### ISSUE THREAD

**Issue by wenfangdu** [vscode-neovim/vscode-neovim#872]
With `noremap <silent> <leader>e :edit $MYVIMRC<cr>`, use leader + e to open `init.vim`, `init.vim` is not opened, a new file with `init.vim`'s content is opened instead:

![image](https://user-images.githubusercontent.com/28700378/164967163-3d905c24-f263-45ed-bf2f-c17c80d2dc1a.png)

**Comment by wenfangdu** [comment]
Fixed with `map <silent> <leader>e :edit $MYVIMRC<cr>`, not sure why.

**Comment by theol0403** [comment]
The plugin remaps `:edit` to intercept the command and sends it to vscode.
