### ISSUE TITLE
`-- INSERT --` stays after pressing escape

### ISSUE THREAD

**Issue by wenfangdu** [vscode-neovim/vscode-neovim#877]
![STG 2022-04-25 10_38_01](https://user-images.githubusercontent.com/28700378/165011694-364e05bc-8ea1-422e-b070-8a289515b4ed.gif)

**Comment by justinmk** [comment]
works for me. did you try without your nvim & vscode config

**Comment by wenfangdu** [comment]
@justinmk Sometimes it works, sometimes it doesn't, pretty unstable.

**Comment by theol0403** [comment]
Fixed in latest release.
