### ISSUE TITLE
show Nvim messages in Output channel

### ISSUE THREAD

**Issue by chrisands** [vscode-neovim/vscode-neovim#880]
When something logs in neovim it shows in statusbar and that's all. I think they should be duplicated in Messages output in vscode.

**Comment by justinmk** [comment]
You didn't give a concrete example so I assume you mean things like `:echo "hi"`. Agreed that it would make sense for that to

1. focus the `vscode-neovim` Output view
2. write the output there

<img width="395" alt="image" src="https://user-images.githubusercontent.com/1359421/165408455-6f26e1c5-96d8-4905-b0df-5912b61ebef9.png">

**Comment by justinmk** [comment]
You can see messages by using the `:messages` command. That will populate the above-mentioned Output channel. This only shows persisted messages (`:echomsg "foo"`), so it won't show "ephemeral" messages (':echo "foo"`).

Showing the Output channel on every ephemeral message would get annoying.

You can always set a mapping or something that runs `:messages`.

So there's not much to do here, except, imo: _if_ the Output channel is visible, append all messages there (including ephemeral?).
