### ISSUE TITLE
What's the point to escape while in normal mode?

### ISSUE THREAD

**Issue by wenfangdu** [vscode-neovim/vscode-neovim#882]
https://github.com/vscode-neovim/vscode-neovim/blob/08af1e378ba818186d6c8706d5a4c659225b31ac/package.json#L374-L378

https://github.com/vscode-neovim/vscode-neovim/blob/08af1e378ba818186d6c8706d5a4c659225b31ac/package.json#L384-L388

**Comment by justinmk** [comment]
That defines when vscode-neovim handles ESC and ctrl-c. Which means it will forward it to Nvim. If the `when` clause is false then vscode handles the keys, not vscode-neovim.

**Comment by wenfangdu** [comment]
@justinmk Please forgive me, but the use of escape is to enter normal mode, right? What're the other uses of escape when in normal mode?

**Comment by wenfangdu** [comment]
@justinmk Please forgive me, but the use of escape is to enter normal mode, right? What're the other uses of escape when in normal mode?

And if there're other uses, it's missing some "when" conditions, such as `!suggestWidgetVisible`, etc.

**Comment by justinmk** [comment]
ESC and ctrl-c can be mapped (in Nvim).

**Comment by wenfangdu** [comment]
@justinmk Thanks, that makes sense.

**Comment by wenfangdu** [comment]
Also, Esc can be used to exit easymotion while in normal mode.
