### ISSUE TITLE
neovide support ?

### ISSUE THREAD

**Issue by tourkit** [vscode-neovim/vscode-neovim#883]
Hello, excuse me to polute the Issues list for this, but I don't know how to ask elsewhere ? 

So It's not an issue but a question, all is in the title.

I tryed to set the neovim executable path Win32 in the settings to neovide.exe wich is in the same folder as nvim.exe, but it didn't work. Using nvim.exe on the other hand does work. So should I do an other way ? can I do it ? 

thank you for your help

**Comment by justinmk** [comment]
Your question makes no sense. Neovide itself requires `nvim`: 

https://github.com/neovide/neovide#install

> Note: Neovide requires neovim version 0.6 or greater

**Comment by tourkit** [comment]
hm ... ur making no sense to me
