### ISSUE TITLE
`workbench.action.toggleSidebarVisibility` not working

### ISSUE THREAD

**Issue by mvpopuk** [vscode-neovim/vscode-neovim#888]
First of all thanks for this amazing plugin.

I am trying to map `<C-n>` to open the sidebar in vscode because I have the same key binding for opening `NvimTree` in neovim. This is how I'm trying to achieve that:

`nnoremap <silent> <C-n> <Cmd>call VSCodeNotify('workbench.action.toggleSidebarVisibility')<CR>`

But, this has no effect. Am I doing something wrong ?

Thanks.

**Comment by theol0403** [comment]
You need to send C-n to nvim from vscode keybindings
