### ISSUE TITLE
Allow multiple executable paths

### ISSUE THREAD

**Issue by DerYeger** [vscode-neovim/vscode-neovim#893]
I'm sharing my VSCode config between Intel and M1 Macs.
However, since Homebrew uses different directories for both architectures,  I always have to update my executable path when changing machines.

Would it be possible to allow multiple paths and fallback to the next available path if the previous one does not exist?

**Comment by justinmk** [comment]
What are the paths? 

I think https://github.com/neovim/node-client should gain the ability to search for Nvim on the system, so that clients don't need to reinvent this stuff.

**Comment by DerYeger** [comment]
> What are the paths?


`/opt/homebrew/bin/nvim` (M1) and `/usr/local/bin/nvim` (Intel).

> I think https://github.com/neovim/node-client should gain the ability to search for Nvim on the system, so that clients don't need to reinvent this stuff.

That sounds like a much better solution!

**Comment by echaya** [comment]
wouldn't it be easier if you choose to turn off syncing `executable path` ? At least that works for me for my home pc and work pc.

**Comment by DerYeger** [comment]
> wouldn't it be easier if you choose to turn off syncing `executable path` ? At least that works for me for my home pc and work pc.

I did not know that this was an option. Thank you very much for the hint, it solves my issue!
