### ISSUE TITLE
Feasibility of implementing Telescope

### ISSUE THREAD

**Issue by raj-magesh** [vscode-neovim/vscode-neovim#897]
I'd really love to use Telescope and its extensions in my neovim-vscode instance, but I don't think it's supported.

Is this in principle impossible or are there VS Code APIs that might allow such integration?

**Comment by justinmk** [comment]
Re-implementing plugins makes no sense for this project and is totally out of scope. The entire purpose is for Nvim and its plugins to work. Not to mention, vscode has a command palette.

If telescope doesn't work, then Nvim API and/or RPC UI might need new features, or maybe vscode-neovim needs new support like https://github.com/vscode-neovim/vscode-neovim/pull/868

**Comment by raj-magesh** [comment]
^Gotcha, I didn't mean re-implementing Telescope, just getting it to work using `vscode-neovim` (which it doesn't currently). The necessary APIs probably don't exist (yet, at least). Could you expand RPC for me?

**Comment by albert-ying** [comment]
I used the FindItFaster plugin for this in VScode https://github.com/tomrijndorp/vscode-finditfaster

**Comment by popadicbranislav** [comment]
> I used the FindItFaster plugin for this in VScode https://github.com/tomrijndorp/vscode-finditfaster

This is exactly what I was looking for. Now I can continue to look for things faster. Thanks

**Comment by darianmorat** [comment]
> I used the FindItFaster plugin for this in VScode https://github.com/tomrijndorp/vscode-finditfaster
> 
> I think it does the same thing as the telescope, with a similar interface. I'm pretty happy with it so far

This is absolutely fantastic, you can set up a shortcut that goes full screen terminal & activates this extension and can toogle with the editor !!

**Comment by mloskot** [comment]
> I used the FindItFaster (...) I think it does the same thing as the telescope

I use FindItFaster too, but a while ago I also discovered https://github.com/jpcrs/binocular (and its counter-part https://github.com/jpcrs/binocular-cli) which has a great potential.
What i like about the Binocular take is it opens in a floating view much like the telescope, while the FindItFaster opens in the VSCode terminal view. This may be annoying at times: if I have the terminal view narrowly resized, then the FindItFaster is tiny, what is an obvious disadvantage. The Binocular does not suffer form this. I wish Binocular received more attention increasing chance for contributions with enhancements.

**Comment by albert-ying** [comment]
> > I used the FindItFaster (...) I think it does the same thing as the telescope
> 
> I use FindItFaster too, but a while ago I also discovered https://github.com/jpcrs/binocular (and its counter-part https://github.com/jpcrs/binocular-cli) which has a great potential. What i like about the Binocular take is it opens in a floating view much like the telescope, while the FindItFaster opens in the VSCode terminal view. This may be annoying at times: if I have the terminal view narrowly resized, then the FindItFaster is tiny, what is an obvious disadvantage. The Binocular does not suffer form this. I wish Binocular received more attention increasing chance for contributions with enhancements.

This is gold. Thank you for sharing
