### ISSUE TITLE
Cursor stutters when moving

### ISSUE THREAD

**Issue by iver0** [vscode-neovim/vscode-neovim#898]
When moving the cursor, a slight stutter is noticeable. It persists with all extensions disabled except vscode-neovim; in both WSL2 and native environment; with a completely empty neovim config.
vscode-vim extension on the other hand doesn't have this stutter despite it having worse performance, so probably not a performance issue? What could this be?

**Comment by Sejdens** [comment]
Can you send a video of it happening? Can you describe more in detail what do you mean by stutter?

**Comment by iver0** [comment]
https://user-images.githubusercontent.com/81345597/168514310-fdf6fee4-5e32-449f-8434-2b7b06c0ccbc.mp4

This is on Arch WSL2 with native windows vscode attached to it, same thing in non WSL. Although I've found out that this issue is not present on Linux, so this is a Windows exclusive problem.

**Comment by theol0403** [comment]
Closing as this is a minor performance issue. Might be resolved by updating to newer nvim cursor APIs.
