### ISSUE TITLE
Cursor not placed on newly inserted line with `O`

### ISSUE THREAD

**Issue by joelostblom** [vscode-neovim/vscode-neovim#899]
The expected behavior of hitting `O` is that a line is inserted above the current line and the cursor is placed on this new line. Sometimes I have noted that the cursor remain on the current line (ie, it appears to be "moved down" a line together with the text). In this video you can see an example of this. Every time I enter insert mode in the video it is by pressing `O`. The first couple of times work as expected, but then the cursor is repeatadly positioned at the line below the newly inserted line:

https://user-images.githubusercontent.com/4560057/167729963-5f4846ca-17ef-4cf1-a3e8-22c9d6331180.mp4

This particular clip is from a Jupyter Notebook, but I have seen the same behavior in regular text files. This is on vscode 1.67 with nvim 0.5.0 on PopOS 21.10.

**Comment by theol0403** [comment]
Related: #864

**Comment by theol0403** [comment]
This might be fixed by https://github.com/vscode-neovim/vscode-neovim/pull/992, can you give it a try?

**Comment by andmis** [comment]
Just tried this, can't reproduce.

**Comment by joelostblom** [comment]
I think you are correct @theol0403 (and sorry for the late reply). I just tried this again and I can't reproduce anymore so closing.
