### ISSUE TITLE
Selecting multiple rows of data for operation in visual mode is invalid

### ISSUE THREAD

**Issue by AmelloAster** [vscode-neovim/vscode-neovim#907]
<img width="552" alt="image" src="https://user-images.githubusercontent.com/26178326/168834143-fc5a3d62-bd39-490c-9d6a-b43691df89ee.png">

**Comment by Damaged-Code** [comment]
When I select multiple lines and hold down the comment shortcut
the comment symbol will only appear at the end

**Comment by theol0403** [comment]
Are you selecting with the mouse? Do you have the mouse select option enabled?

**Comment by Damaged-Code** [comment]
> Are you selecting with the mouse? Do you have the mouse select option enabled?

no,I selected by keyboard

**Comment by theol0403** [comment]
Which comment shortcut are you using? You might need to use `VSCodeNotifyVisual` to trigger the command instead.

**Comment by btctrl** [comment]
this same thing is happening to me
When selecting multiple rows in visual mode and running `CMD+/` (comment shortcut) I expect to see all highlighted rows be single commented each line but only see the last line that the cursor is one becomes commented

**Comment by theol0403** [comment]
You may need to pass CMD+/ to nvim.

```json
{
  "key": "cmd+/",
  "command": "vscode-neovim.send",
  "when": "editorTextFocus && neovim.ctrlKeysNormal && neovim.init && neovim.mode != insert',
  "args": "<C-/>"
}
```

**Comment by pix0r** [comment]
This fix worked for me as well; thanks!

FWIW, I was able to fix a similar issue with `cmd+c` not copying a multi-line visual selection using the same approach -  setting `args` to `"\"*y"`
