### ISSUE TITLE
Command line tab completion doesn't handle nested paths

### ISSUE THREAD

**Issue by awilkins** [vscode-neovim/vscode-neovim#911]
Reproduce : 

```
❯ tree
.
├── database
│   └── tables
└── schema.sql
```

- Open `schema.sql`
   -  (which has a DDL schema in it for sake of argument, pretend we're selecting individual table statements and want to write them into separate files in `tables/`)
- Select some lines of text
- Open the command line <kbd>:</kbd>
- Start a command that uses a path e.g. <kbd>w</kbd>
- Start to type a path that exists inside the directory of the current buffer `schema.sql`

   - e.g. `datab`
   - Note that completion list highlights `database/`
- Hit <kdb>Tab</kbd>

At this point, I was trying to reproduce this in a temp folder, and it was behaving differently to the tree where I noticed it... 

At this point the command line contains

```
'<,'>w database/
```

- Start to type the second component of your path, e.g. `tabl`
- What should happen :
   - Drop list under command line offers `tables/` as a completion (and `schema.sql`)
   - You hit <kbd>Tab</kbd>
   - Command line appends `tables/` to the existing path
   - Command line now contains the following
      - And the completion list should show things from inside `tables/`
```
'<,'>w database/tables/
```
- What actually happens, in my real workspace
   - Drop list under command line offers `tables/` as a completion (alongside other items in the folder)
   - You hit <kbd>Tab</kbd>
   - Command line replaces `database/` with `tables/`
 ```
 '<,'>w tables/
 ```
 - What happened in the temp folder I tried reproduction of bug in
    - Drop list under command line .. continues to only offer `tables/` and `schema.sql` as completions
    - Hitting <kbd>Tab</kbd> changes nothing

**Comment by theol0403** [comment]
This should be fixed by #860 - can you give it a try? Otherwise, I can look into adding a more general fix to #908.

**Comment by awilkins** [comment]
This is great - my only tiny complaint now is that it doesn't offer file names as completions after the second nest (ie, files inside `database/` are offered, but not inside `database/functions/`), but as this stands it's a large improvement.

**Comment by awilkins** [comment]
Merged #908 into #860 and still only goes into the second nest and doesn't offer files as completions.

Will try #908 on it's own.

**Comment by xiyaowong** [comment]
To be aware, Vim's default wildmenu isn't very efficient. There are numerous wildmenu plugins available. We can emulate such plugins to implement our cmdline. Early [attempt](https://github.com/xiyaowong/vscode-neovim/tree/fix/refactor-cmdline-tmp)

**Comment by theol0403** [comment]
Fixed by https://github.com/vscode-neovim/vscode-neovim/pull/2001
