### ISSUE TITLE
vscode lose focus and refocus Mouse cannot move in Normal mode

### ISSUE THREAD

**Issue by AmelloAster** [vscode-neovim/vscode-neovim#912]
After I clicked on other software with my mouse
I found that the mouse can be moved in insert mode
all other modes cannot be moved

https://user-images.githubusercontent.com/26178326/169540998-edecf8f0-e7c9-411e-9e25-9dda3eed7598.mov

**Comment by theol0403** [comment]
Sometimes this extension freezes. Are you able to consistently reproduce this, or did it just happen once? If so, can you provide steps?

**Comment by AmelloAster** [comment]
> 

There have been several occurrences
But the specific reasons for the appearance of the current I am not very clear
I only know that I switch to a different software for a period of time and then switch back to vscode will appear the cursor can not move the situation
If it occurs again I will pay close attention to the details

**Comment by AmelloAster** [comment]
> Sometimes this extension freezes. Are you able to consistently reproduce this, or did it just happen once? If so, can you provide steps?

I tried, even if I do not switch files by mouse, as long as I switch files switch more often, the cursor will easily die and can not move, except in insert mode can move, other modes are not responsive

**Comment by JUNGHUNKIM-7** [comment]
same issue here.
