### ISSUE TITLE
Strange tab/indent rendering in vscode

### ISSUE THREAD

**Issue by GiuseppeMP** [vscode-neovim/vscode-neovim#913]
After updating vscode to Version: 1.67.2, these tabs rendering appears. Any ideia? bug? config? 

![image](https://user-images.githubusercontent.com/4944009/169668142-d7c0773b-8107-4d7a-a411-88e8a7f826ac.png)

NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by GiuseppeMP** [comment]
This procedure resolves for me:

1. Removed these dirs: ~/.local/share/nvim and ~/.config/nvim
2. Clean reinstall of NVIM v0.7.0 with brew install neovim --force.
3. Restored all configs and plugins with the backup of init.vim.

Everything backs to normal.

**Comment by Dandarprox** [comment]
Hey kind of followed these same instructions, I went from 0.7.0dev to 0.8.0dev but I am still seeing those weird lines. Is your current solution still working?

**Comment by GiuseppeMP** [comment]
@Dandarprox Try to use the NVIM v0.7.0 Release and remove all files before, like ~/.local/share/nvim.

I noted some weird relations with the configs below in vscode, try to change them:

```
"workbench.tree.renderIndentGuides": "onHover"
"editor.renderWhitespace": "selection"
```

**Comment by theol0403** [comment]
https://github.com/vscode-neovim/vscode-neovim/issues/915
