### ISSUE TITLE
[Bug] Error detected while processing command line after upgrading to v0.0.85

### ISSUE THREAD

**Issue by wenfangdu** [vscode-neovim/vscode-neovim#917]
After upgrading to v0.0.85, the following error is thrown for every VSCode restart:

![](https://user-images.githubusercontent.com/28700378/169736324-8d012c06-c4d2-4bd3-b8ba-f186713cf690.png)

v0.0.84 has no such issue.

OS: Windows 10 + WSL Ubuntu
VSCode: v1.67.2

**Comment by jackblackevo** [comment]
Seems like the same as #520

**Comment by wenfangdu** [comment]
@theol0403 Is this closed as a dup for #520? But the error didn't pop up before v0.0.85 though.
