### ISSUE TITLE
Ghost vertical line on end end of every line

### ISSUE THREAD

**Issue by AnishDe12020** [vscode-neovim/vscode-neovim#918]
There is this irritating vertical line at the end of every line when using this extension - 
![image](https://user-images.githubusercontent.com/63192115/169809924-ccad00f8-2870-438c-9cc4-948aaa22c9f0.png)

I have confirmed that this extension is the culprit by disabling it while keeping all other VSCode extensions enabled.

**Comment by asvetliakov** [comment]
#915 #913
