### ISSUE TITLE
Incorrect `o` behavior for PHP files

### ISSUE THREAD

**Issue by lynear24** [vscode-neovim/vscode-neovim#920]
Using `o` in normal mode with php files does not indent properly, but creating a newline after that correctly indents. I have all my php-related vim plugins deactivated, and here is what happens in both vscode and base neovim. I'm using VSCodium, but the behavior is exactly the same with VSCode.

https://user-images.githubusercontent.com/15196698/169848764-5d409ede-3e6b-4fdb-8185-ea9800cd2932.mp4

https://user-images.githubusercontent.com/15196698/169848773-50d64aa5-2448-44aa-af9d-1b396f9bbcd2.mp4

I'm using VSCodium 1.67.2, Neovim 0.7.0, and vscode-neovim 0.0.85.

**Comment by xgrei** [comment]
Related: https://github.com/vscode-neovim/vscode-neovim/issues/864
