### ISSUE TITLE
With Remote - WSL I get E344: Can't find directory "\home\..."

### ISSUE THREAD

**Issue by KennedDoll** [vscode-neovim/vscode-neovim#924]
Using windows vscode from WSL (as vscode suggests)  using Remote - WSL, there is an error message in which the directory separators are backslashes instead of forward slashes.

I don't know if this affects anything.

**Comment by anthonyma94** [comment]
This happens with SSH too.

**Comment by edgartaor** [comment]
Related or the same issue: #520

**Comment by erees1** [comment]
Possibly related: have just opened a pr to fix a similar message when opening a folder over ssh-remote https://github.com/vscode-neovim/vscode-neovim/pull/925

**Comment by nauynix** [comment]
Can confirm that downgrading to 0.0.84 fixes it (for now)

**Comment by ppwwyyxx** [comment]
Why is this issue closed? It is apparently not fixed.

**Comment by theol0403** [comment]
Duplicate

**Comment by ppwwyyxx** [comment]
For duplicates, you can comment `Duplicate of #123`. Github can recognize this and mark it correctly, and it will ensure people can follow the right issue to find a solution.

**Comment by theol0403** [comment]
Error should be fixed in latest version.

**Comment by KennedDoll** [comment]
Duplicate of?
