### ISSUE TITLE
is there any way to set composite key to single charactor in insert mode?

### ISSUE THREAD

**Issue by JUNGHUNKIM-7** [vscode-neovim/vscode-neovim#926]
inoremap jk (
imap jk (

thank for your extension. i'm new from ideavim but dont know about original vim too much. 
i usually bind j+k as single bracket key in ideavim, and i wannna apply too in my environment.
unfortunately, i haven't still have solution for that. could you tell me what i did wrong?
thanks!

**Comment by theol0403** [comment]
This plugin does not support insert-mode maps. Your best option is to try and use vscode snippets or some vscode plugin.
