### ISSUE TITLE
`set ambiwidth=double` in vimrc will cause error

### ISSUE THREAD

**Issue by Alaskra** [vscode-neovim/vscode-neovim#928]
https://github.com/vscode-neovim/vscode-neovim/blob/ac5403a280d6dff18e5cd8f564c70bf9ab9c57b3/vim/vscode-options.vim#L34-L35
I don't know the meaning of this line, but it will cause error if there is `set ambiwidth=double` in vimrc :
```
Error detected while processing /home/alaskra/.vscode/extensions/asvetliakov.vscode-neovim-0.0.85/vim/vscode-options.vim:
line   35:
E474: Invalid argument: listchars=tab:❥♥
```

**Comment by Alaskra** [comment]
The nvim document says:
![image](https://user-images.githubusercontent.com/49367127/172534870-681dc7ab-85e9-4614-9b5c-3f0e6744e7d3.png)

**Comment by justinmk** [comment]
If `set listchars=tab:❥♥` is really needed, we should guard it w/ `if &ambiwidth !=# 'double'`.

**Comment by theol0403** [comment]
Not sure if `ambiwidth` is supported by this plugin, as rendering is handled by vscode. I don't think anything needs to change because `ambiwidth` isn't a valid option.

**Comment by Alaskra** [comment]
But I usually use my vimrc(there is `set ambiwidth=double`) in this plugin setting, so this error arise every time when launch this plugin.

**Comment by justinmk** [comment]
> But I usually use my vimrc(there is `set ambiwidth=double`) in this plugin setting

guard it with `if exists('g:vscode')`.

An error is the correct behavior as @theol0403 pointed out.
