### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by JoepKneefel** [vscode-neovim/vscode-neovim#930]
The extension crashes immediately after start up. I get these errors:

```
2022-06-08T12:39:44.506Z MainController: Neovim exited with code: -13

2022-06-08T12:39:44.505Z MainController: Neovim was disconnected

MainController: Neovim spawn error: spawn /opt/homebrew/Cellar/neovim/HEAD-af2899a/bin EACCES
```

I tried changing the permissions, but that didn't work.
When I run neovim in the terminal, it works just fine.

**Comment by justinmk** [comment]
> When I run neovim in the terminal, it works just fine.

What is the exact command? Seems like vscode-neovim is trying to run `/opt/homebrew/Cellar/neovim/HEAD-af2899a/bin`

**Comment by JoepKneefel** [comment]
nvim

**Comment by JoepKneefel** [comment]
What is wrong with `/opt/homebrew/Cellar/neovim/HEAD-af2899a/bin`?
This is where the neovim I use is located.

**Comment by justinmk** [comment]
> When I run neovim in the terminal, it works just fine.

Did you try `/opt/homebrew/Cellar/neovim/HEAD-af2899a/bin` from the terminal?

**Comment by JoepKneefel** [comment]
Yes, that did work

**Comment by JoepKneefel** [comment]
So dumb. I had to specify the full path (including the filename: `".../bin/nvim"`). Now it works.
