### ISSUE TITLE
How select and copy in OUTPUT? 

### ISSUE THREAD

**Issue by Adnios** [vscode-neovim/vscode-neovim#931]
Sometimes, there is some message in OUTPUT. And I want to copy it. But the mouse selection is very strange. It always miss a few characters.

https://user-images.githubusercontent.com/41060790/172747768-8a5dfb80-abe2-4c56-88fa-c040bf4e8d31.mp4

**Comment by justinmk** [comment]
related:

- https://github.com/vscode-neovim/vscode-neovim/issues/912
- https://github.com/vscode-neovim/vscode-neovim/issues/705

**Comment by theol0403** [comment]
Mouse selection is indeed strange. I'm not sure if this is caused by the plugin or not though. If it is, looks like it tries to enable vim mode on the output buffer, which should probably be disabled.
