### ISSUE TITLE
nnoremap { {zz seem not work

### ISSUE THREAD

**Issue by ShiChenCong** [vscode-neovim/vscode-neovim#933]
`nnoremap { {zz` seem not work

**Comment by justinmk** [comment]
look at `:nn {` : 

```
x  zz          * <Cmd>call <SNR>4_reveal('center', 0)<CR>
n  zz          * <Cmd>call <SNR>4_reveal('center', 0)<CR>
```

it is currently mapped to a workaround, though I think it might not be necessary these days, since `win_viewport` ? https://github.com/vscode-neovim/vscode-neovim/pull/649

related?: https://github.com/vscode-neovim/vscode-neovim/pull/919

**Comment by ShiChenCong** [comment]
@justinmk  i see, thank you for the reply
