### ISSUE TITLE
Upper marks create new file

### ISSUE THREAD

**Issue by take-study** [vscode-neovim/vscode-neovim#935]
when jump to an upper mark taht set in other file ,it will create a new file in vscode.

**Comment by take-study** [comment]
it seems neovim has jump to the mark and send the buffer to vscode ,but vscode handle this buffer as new file.

**Comment by theol0403** [comment]
Check your init.vim. For me, jumping to upper mark works properly.

**Comment by ACupofAir** [comment]
> when jump to an upper mark taht set in other file ,it will create a new file in vscode.

I have the same problem. Do you solve it?

**Comment by ACupofAir** [comment]
> > > when jump to an upper mark taht set in other file ,it will create a new file in vscode.
> > 
> > 
> > I have the same problem. Do you solve it?
> 
> Have you tried with empty config?

I use the empty `init.vim`, it still not work and make new buffer in vscode.

**Comment by take-study** [comment]
> > when jump to an upper mark taht set in other file ,it will create a new file in vscode.
> 
> I have the same problem. Do you solve it?

I found this problem only happens with windows and remote dev,if i use a local linux nvim and vscode it never happen

**Comment by theol0403** [comment]
I am able to reproduce on windows.

**Comment by guhetier** [comment]
I have a similar issue happening in multiple scenarios (not only jumping to marks), but most basic commands.
It seems to mostly happen when in a Windows remote session or when the system is under a heavy workload (compiling...), so I suspect a timing problem.

**Comment by QuadrupleA** [comment]
Getting this too - on Windows 10. Tried empty init.vim, no luck.

**Comment by morew4rd** [comment]
Same here. I think it may be related to the path separator character `/` vs `\`.  

See the output of `:marks` (folder names)
```
 A      4    9 __vscode_neovim__-file:\\\c%3A\work\play\snek\1\app.fnl
 C   2052   10 __vscode_neovim__-file:///c%3A/work/play/morelib/lyte2d/src/api.c
```

**Comment by justinmk** [comment]
Closing in favor of https://github.com/vscode-neovim/vscode-neovim/issues/1223
