### ISSUE TITLE
Fix behavior of `<NL>` in insert mode and command-line mode

### ISSUE THREAD

**Issue by pedrominicz** [vscode-neovim/vscode-neovim#936]
The default behavior of `<NL>` (`ctrl+j`) in insert mode or command-line mode in Neovim (or Vim, or Vi) is the same as `<CR>` (`enter`). The insert mode behavior can be verified by running `nvim --clean` and entering this exact key sequence: `ihello<Esc>0i<NL>`, where `<Esc>` is the escape key and `<NL>` is `ctrl+j`. The command-line mode behavior can be verified by running `nvim --clean` and entering `:echo 'hello'<NL>` instead. However, VSCode Neovim maps `ctrl+j` to `editor.action.insertLineAfter` in insert mode and doesn't map it in command-line mode. `<NL>` works as expected in normal mode.

VSCode Neovim also doesn't map `ctrl+m` anywhere. In a terminal, `ctrl+m` sends a carriage return, meaning it behaves as `<CR>` (that is, the exact same as if `enter` was pressed). In Neovim (or Vim, or Vi), `ctrl+m` in any mode behaves exactly the same way as `enter`. However, since VSCode Neovim doesn't bind `ctrl+m`, it has the wrong behavior in every mode (namely the default `ctrl+m` binding to `editor.action.toggleTabFocusMode`). While I never use `ctrl+m`, I know some Neovim/Vim/Vi users do.

Here is a similar issue in VSCodeVim: https://github.com/VSCodeVim/Vim/issues/1505

### Workaround
The following keybindings can be added to make `ctrl+j` and `ctrl+m` behave as expected:
```json
{
    "key": "ctrl+j",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus && neovim.mode == 'insert'",
    "args": {
        "snippet": "\n"
    }
},
{
    "key": "ctrl+m",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus && neovim.mode == 'insert'",
    "args": {
        "snippet": "\n"
    }
},
{
    "key": "ctrl+j",
    "command": "vscode-neovim.send",
    "when": "neovim.mode != 'insert' && neovim.mode != 'normal'",
    "args": "<NL>"
},
{
    "key": "ctrl+m",
    "command": "vscode-neovim.send",
    "when": "neovim.mode != 'insert'",
    "args": "<CR>"
}
```
However, this is just a workaround and probably has some issues.

I hope the behavior of `ctrl+j` and `ctrl+m` gets fixed because I believe this extension should behave exactly as Neovim does when possible.

**Comment by theol0403** [comment]
The proper solution would be sending vscode-neovim.send like the other insert-mode and visual-mode bindings in package.json.
