### ISSUE TITLE
Ctrl C in Insert mode.

### ISSUE THREAD

**Issue by M-Mabrouk1** [vscode-neovim/vscode-neovim#939]
I used to be able to use the default vs code keybindings Ctrl-C to copy and Ctrl-V to paste in Insert mode.
now whenever I press Ctrl-c in Insert mode it gets me out of it and doesn't copy anything.
I even remapped <C-C> in my nvim configs to do nothing still not working.

**Comment by HiDe-Techno-Tips** [comment]
* In VSCode, go to `File`>`Preferences`>`Keyboard Shortcuts`.
* In the menu search for `Escape Key`.
* Change to your preferred keybinding or Right click and `Remove Keybinding` for all those `Escape Key` entries that are set to `Ctrl-C`.

These keybinding escapes from neovim insert mode to normal mode.

**Comment by M-Mabrouk1** [comment]
Thank you so much.
