### ISSUE TITLE
How to change the highlight color of indent area with tab ?

### ISSUE THREAD

**Issue by nokia-git** [vscode-neovim/vscode-neovim#940]
When select a section of code, the color is strange in the indent area with tab
![screenshot_20220621_084129](https://user-images.githubusercontent.com/80832836/174694805-e71a47e4-0fee-452a-8656-edd7891c1c61.png)
If replace tab by space, the highlight color is better.
![screenshot_20220621_084242](https://user-images.githubusercontent.com/80832836/174694954-4a643647-b675-41bc-8215-caa691c2e2ff.png)
My question is how to change the highlight color of indent area with tab ? Just as the color with space. Thanks.

**Comment by justinmk** [comment]
Try stackoverflow for usage questions.

**Comment by b1mind** [comment]
So recently converted to tabs and this happen to me too. I do use vsCode theme highlightGroup overrides from the extension to tell it to use my theme not "vim".

Fix that worked for me:

edit vsc settings.json

change `"vscode-neovim.highlightGroups.unknownHighlight": "vim",` to 👇

(or add)

```json
	"vscode-neovim.highlightGroups.unknownHighlight": {
		"Visual": {
			"backgroundColor": "theme.editor.selectionBackground"
		}
	},
```
