### ISSUE TITLE
`vscode-neovim.mouseSelectionStartVisualMode` malfunction, aka VSCode selection to Neovim visual mode problem

### ISSUE THREAD

**Issue by SichangHe** [vscode-neovim/vscode-neovim#944]
# `mouseSelectionStartVisualMode` — WIP
a.k.a Selecting with a mouse in VSCode does not properly transfer to Neovim visual mode selection
## what is this option
As my understanding goes, `vscode-neovim.mouseSelectionStartVisualMode` is supported from #723, and it aims to transfer *mouse selection in normal mode in VSCode* to *visual mode selection in Neovim*.

To enable it, you need to set:
```json
"vscode-neovim.mouseSelectionStartVisualMode": true
```
in your `settings.json` and `Reload Window`

Unfortunately, this setting does not work properly yet, and probably therefore does not get an option in `Settings`.
## objective of this issue
This issue aims to concentrate some discussions on this functionality, and add my experience.

As I understand, `vscode-neovim.mouseSelectionStartVisualMode` as an option is in an "alpha" stage.
Several issues have reported that this option is missing (older issues) or does not work as intended, with some duplications. For example:
- [VS Code mouse selection is not transfered to Neovim](https://github.com/vscode-neovim/vscode-neovim/issues/395)
- [Selecting text with the mouse has strange behavior](https://github.com/vscode-neovim/vscode-neovim/issues/891)
- [Mouse selection not working despite setting `vscode-neovim.mouseSelectionStartVisualMode` enabled](https://github.com/vscode-neovim/vscode-neovim/issues/848)

- [VSCode visual to nvim visual](https://github.com/vscode-neovim/vscode-neovim/issues/921)

Unfortunately, these issues use different wording to refer to this same problem, thus searching and finding the problem in existing issues is somewhat difficult.
I hope it might help if I make an issue and try to include common wording to direct people to the same place and therefore help with the problem.

### selecting from the left to the right
After setting this option and reloading, I do enter visual mode after selecting text using a mouse in normal mode, and the highlighted selected text seems to be the correct text, i.e. the text I just selected.
![image](https://user-images.githubusercontent.com/84777573/175359839-f8fe170b-eb86-414d-a5cf-8654de1fff3b.png)
But, if I use a command like `c`, or if I click somewhere else, or if I change the selection using something like `l`, I notice that I did not select the correct text. I always lose some characters in the front.
![image](https://user-images.githubusercontent.com/84777573/175360376-d3561fea-7712-4575-83d0-bb0eda253eb2.png)
Sometimes I loose one character
![image](https://user-images.githubusercontent.com/84777573/175360084-a962fe08-2da0-4374-9ca9-69bdea579953.png)
Sometimes two
![image](https://user-images.githubusercontent.com/84777573/175360280-ecc7e0e1-0306-460f-ab6e-eaf923bdead8.png)
Sometimes three
![image](https://user-images.githubusercontent.com/84777573/175359974-9f5620f6-678e-449b-ae26-54ca090b2c46.png)
Sometimes four
![image](https://user-images.githubusercontent.com/84777573/175360191-7d267cf9-848e-4a90-93ed-d58a8f9c9542.png)
Sometimes five

In my trials, the most common scenarios is that I loose two or three characters. The scenarios where one or five characters are lost is rare.
And, the lost characters are always in the front, not back.
### selecting from the right to the left
By selecting from the right to the left, the actual selected part sometimes got rendered properly, but not always. I still usually lose characters in the front (in this case the right) by one to five characters, but seldom the selection is correct (maybe I just got luckier selecting from the right to the left).
### other experience
Another minor issue is that visual mode is not exited if I click somewhere and it just changes the endpoint to where I clicked. But, that is rather a feature request to single click to exit visual mode.
## My versions
```shell
$ uname -a
Darwin <domain> 21.1.0 Darwin Kernel Version 21.1.0: <time>; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101 arm64

$ nvim --version 
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.0/share/nvim"

Run :checkhealth for more info

$ co --version
1.69.0-insider
4c72dedb4ad283a569f83a7389468c3ae2c642c3
arm64
```
vscode-neovim version is latest
## for updates
If anyone has different experience, please point out. If I have different experience, I would try to update as well.

**Comment by SichangHe** [comment]
## one way to use this functionality properly
1. place the cursor at the start of the selection
2. press <kbd>v</kbd> to enter visual mode
3. move mouse cursor to click the end of the selection

This way, the selection is always (at least when I tried) correct. And, you get to use your mouse (trackpad) cursor as an option.

As a note, this would not work if
```json
"vscode-neovim.mouseSelectionStartVisualMode": false
```
because the click in 3. does not create a selection

**Comment by ollien** [comment]
This was mentioned in #723, but this is a major annoyance that makes this feature troublesome

> It is working partially for me; The selection does translate to the neovim selection, but on some files the selection always starts from the end of the file, or instead of starting a new selection it uses the current cursor position as starting point.
