### ISSUE TITLE
lua plugin not working in vscode but works in native nvim env.

### ISSUE THREAD

**Issue by echaya** [vscode-neovim/vscode-neovim#945]
I see the following error msg when try to use a lua plugin (this is the only lua plugin I have in init.vim.)

>E5108: Error executing lua C:\Users\xxx\AppData\Local\nvim/lua/leap/leap.lua:1: module 'leap' not found:
	no field package.preload['leap']
	no file '.\leap.lua'
	no file 'c:\tools\neovim\nvim-win64\bin\lua\leap.lua'
	no file 'c:\tools\neovim\nvim-win64\bin\lua\leap\init.lua'
	no file '.\leap.dll'
	no file 'c:\tools\neovim\nvim-win64\bin\leap.dll'
	no file 'c:\tools\neovim\nvim-win64\bin\loadall.dll'
stack traceback:
	[C]: in function 'require'
	C:\Users\xxx\AppData\Local\nvim/lua/leap/leap.lua:1: in main chunk
	[C]: in function 'require'
	[string ":lua"]:1: in main chunk

I'm currently using https://github.com/junegunn/vim-plug to install & manage the plug-ins. And it is working fine in the nvim env by calling `lua require("leap.leap")` 

PS1: leap is installed in the following path. `c:\tools\neovim\nvim-win64\share\nvim\vimfiles\plugged\leap.nvim\`
PS2: leap configuration is stored in the following path `c:\Users\xxx\AppData\Local\nvim\lua\leap\leap.lua`

Any advice is appreacited!

**Comment by echaya** [comment]
found the problem on init.vim. closing

**Comment by shelper** [comment]
> found the problem on init.vim. closing

i am facing the same problem as yours, just curious how you fixed it?

**Comment by shelper** [comment]
> found the problem on init.vim. closing

@echaya could you share what is the problem? i got a similar issue. thanks!

**Comment by echaya** [comment]
> > found the problem on init.vim. closing
> 
> @echaya could you share what is the problem? i got a similar issue. thanks!

I can't rmb exactly what was the issue because it was so long ago but if I rmb correct it has things to do with the activation of plugins. Below is my init.vim now - hope it helps!


```vim
source d:\Dropbox\neovim\config\.vimrc
lua require('leap.leap')
···

within the vimrc file, I have the follow:

```vim
if exists('g:vscode')

    call plug#begin(WorkDir.'Neovim\\nvim-win64\\share\\nvim\\vimfiles\\plugged')
        Plug 'unblevable/quick-scope'
        Plug 'machakann/vim-sandwich'


        if has('nvim')
            Plug 'ggandor/leap.nvim'
            " Plug 'ggandor/lightspeed.nvim'
        endif

    call plug#end()
```
