### ISSUE TITLE
Unable to enter uppercase J and K when use jj and jk keybindings

### ISSUE THREAD

**Issue by ilexwg** [vscode-neovim/vscode-neovim#949]
My platform：
MacOS：12.4

My VSCode version: 1.68.1
My neovim version: v0.7.0
VSCode Neovim version: v0.0.87

Problem:
I enable the jj and jk hotkey in the keybindings.json
```json
[
  {
    "command": "vscode-neovim.compositeEscape1",
    "key": "j",
    "when": "neovim.mode == insert && editorTextFocus",
    "args": "j"
  },
  {
    "command": "vscode-neovim.compositeEscape2",
    "key": "k",
    "when": "neovim.mode == insert && editorTextFocus",
    "args": "k"
  }
]
```

But when I type J or K at insert mode, I can't get "J" and "K", I get 'j' and 'k' instead.
I tried to empty keybindings.json file, I can type "J" and "K" again.
I don't know why I can't type uppsercase "J" and "K" when enable the keybindings.
Could you tell me why, or could I do other setting to make it work?

**Comment by theol0403** [comment]
Please try with empty settings.json, init.vim, and all extensions disabled. I am unable to reproduce this.

**Comment by ilexwg** [comment]
I tried the empty settings.json, init.vim and disabled all extensions, only use VSCode Neovim, but it still doesn't work.
