### ISSUE TITLE
Question on setting "vscode-neovim.textDecorationsAtTop"

### ISSUE THREAD

**Issue by wenfangdu** [vscode-neovim/vscode-neovim#951]
Setting "vscode-neovim.textDecorationsAtTop" takes a restart to take effect, this should be reflected in the doc.

Or is it a bug, i.e. restart is not required?

**Comment by theol0403** [comment]
This is just an implementation detail I believe. Actually, I will remove the configuration option, as the default of "true" is the correct implementation and the code bloat for the config is unnecessary.
