### ISSUE TITLE
[Bug] Unexpected output panel popping up

### ISSUE THREAD

**Issue by wenfangdu** [vscode-neovim/vscode-neovim#954]
When using vim-easymotion with `map f <plug>(easymotion-s2)`, the output panel shows up every time the user presses `f`:

![image](https://user-images.githubusercontent.com/28700378/177037734-87073dd4-c490-4163-b0d3-0b874d0ee5ef.png)

VSCode Neovim: v0.0.87

**Comment by theol0403** [comment]
Duplicate of https://github.com/vscode-neovim/vscode-neovim/issues/910

**Comment by justinmk** [comment]
Is there not an EasyMotion option that tells it to shutup?

**Comment by wenfangdu** [comment]
@justinmk `let g:EasyMotion_prompt = ""`
