### ISSUE TITLE
[FR] Convert Neovim selections to VSCode selections for every keystroke in visual mode

### ISSUE THREAD

**Issue by wenfangdu** [vscode-neovim/vscode-neovim#958]
I tried `map q <cmd>call VSCodeNotifyVisual('noop', 1)<cr>` in `init.vim`, then every time I press `q` in visual mode, the nvim selections will be converted to vscode selections, I think this definitely could be automated. If it's implemented, [the selection sync issue](https://github.com/vscode-neovim/vscode-neovim/issues/778) will be resolved.

**Comment by wenfangdu** [comment]
@theol0403 Theo, what do you think?

**Comment by theol0403** [comment]
I'm not sure if this is the best solution, but it is worth a try. The automation would come from some visual selection updated autocommand/event, if it exists.

I wonder if there is a new nvim api that can do this for us.
