### ISSUE TITLE
[Bug] `Ctrl+D` doesn't add selection to next find match when in normal mode

### ISSUE THREAD

**Issue by wenfangdu** [vscode-neovim/vscode-neovim#962]
Repro Steps:

1. Add `"vscode-neovim.useCtrlKeysForInsertMode": false, "vscode-neovim.useCtrlKeysForNormalMode": false` to `settings.json`.
2. Put the cursor at the start of a word in normal mode.
3. Use `Ctrl+D`(editor.action.addSelectionToNextFindMatch) to select that word.
4. Cursor blinks, nothing is selected.

vscode-neovim: v0.0.87
Possible relevant issue: #390 

![STG 2022-07-07 18_31_35](https://user-images.githubusercontent.com/28700378/177753709-bb061b91-c71d-4ad9-ade0-a4171185fae7.gif)

**Comment by theol0403** [comment]
This is because multi cursor is not currently supported in normal mode. If you want to use vscode multi cursor, switch to insert mode first (or add a mapping in nvim that enters insert mode then triggers the vscode command).

**Comment by chennnnnnnnsy** [comment]
it works when use `Ctrl+n` in normal mode. @wenfangdu 
```json
{
    "command": "editor.action.addSelectionToNextFindMatch",
    "key": "ctrl+n",
    "when": "neovim.mode == normal && editorFocus",
    "args": "i+ctrl+n"
 }
```
