### ISSUE TITLE
[Bug] Lightspeed.vim jumps incorrectly on wrapped lines

### ISSUE THREAD

**Issue by aleksey-rowan** [vscode-neovim/vscode-neovim#964]
I've noticed that Lightspeed sometimes would make weird jumps and not land on target. It seems to happen on long, wrapped lines.

Here are two paragraphs with the first being broken into five separate lines and the second one is a single wrapped line. I'm trying to jump to the word "refined" on the third line.

It works correctly on the split-line paragraph, but lands on "work-in-progress" on the second line in the wrapped-line paragraph:

![vscode-lightspeed](https://user-images.githubusercontent.com/79934725/178038610-9c8e7d98-df18-46ef-8770-b18b6eb4015e.gif)

I tried the same in neovim itself and it works correctly in both cases (although I noticed it labels targets a bit differently, but I'm not sure if it matters):

![nvim-lightspeed](https://user-images.githubusercontent.com/79934725/178038611-1f11baef-d0f5-4f15-9218-810153a97562.gif)

I tired disabling all other VSCode extension, but that didn't change anything.

VSCode version: 1.69.0
neovim version: v0.7.0
VSCode Neovim version: v0.0.87

**Comment by aleksey-rowan** [comment]
Yesterday's update: 

- this issue also affects Leap and Sneak
- the incorrect jump described above only happens if the cursor is located on the line **immediately above** the line you are targeting

Today's update:

- I can't reproduce it anymore 🎉🎉🎉
- I see that both VSCode and VSCode Neovim versions got bumped up

**Comment by theol0403** [comment]
Hurray!
