### ISSUE TITLE
Automatically quit visual mode after execute `VSCodeNotifyVisual`

### ISSUE THREAD

**Issue by albert-ying** [vscode-neovim/vscode-neovim#967]
Hi, usually whenever you execute an command in visual mode (e.g., y or d), the editor automatically goes back to normal mode -- which is intuitive. However, this is not the case if the command includes `VSCodeNotifyVisual`.

For example, I have `xnoremap <silent> <D-CR> <Cmd>call VSCodeNotifyVisual('workbench.action.xxx', 1)<CR>` in my init.vim. After I execute the command, I will still be in visual mode.

I tried to modifiy it to something like:

`xnoremap <silent> <D-CR> <Cmd>call VSCodeNotifyVisual('workbench.action.xxx', 1)<CR><Esc>`

But still doesn't work.

Is it possible for me to configure it that automatically quit visual mode after execution (and it would be an intuitive default IMHO)?

**Comment by theol0403** [comment]
Mapping with Esc should work, are you sure it doesn't? Providing `1` to the command means that the VSCode selection will remain after the command is executed, so maybe it appears as though you are still in visual mode but you arent?

**Comment by albert-ying** [comment]
> Mapping with Esc should work, are you sure it doesn't? Providing `1` to the command means that the VSCode selection will remain after the command is executed, so maybe it appears as though you are still in visual mode but you arent?

Yeah... you are right, seems that what I see is the VSCode selection. Is there way to also clean the VSCode selection after command?

**Comment by theol0403** [comment]
> > Mapping with Esc should work, are you sure it doesn't? Providing `1` to the command means that the VSCode selection will remain after the command is executed, so maybe it appears as though you are still in visual mode but you arent?
> 
> Yeah... you are right, seems that what I see is the VSCode selection. Is there way to also clean the VSCode selection after command?

It's mentioned in the docs, just pass 0 to the parameter.
