### ISSUE TITLE
About easymotion-sn: 3 problems

### ISSUE THREAD

**Issue by ZXYFrank** [vscode-neovim/vscode-neovim#973]
First, a lot of thanks to this awesome extension and @asvetliakov 's great job.
I've set up neovim in VSCode and try to use easymotion.

```
set number relativenumber
set autoindent

let mapleader=";"

function! Cond(Cond, ...)
  let opts = get(a:000, 0, {})
  return a:Cond ? opts : extend(opts, { 'on': [], 'for': [] })
endfunction

call plug#begin('D:/ProgramFiles/Neovim/plugged')
" inside；plug#begin:
Plug 'easymotion/vim-easymotion', Cond(!exists('g:vscode'))
Plug 'asvetliakov/vim-easymotion', Cond(exists('g:vscode'), { 'as': 'vsc-easymotion' })
call plug#end()

let g:EasyMotion_smartcase = 1

map <Leader> <Plug>(easymotion-prefix)
nmap <Leader>z <Plug>(easymotion-jumptoanywhere)
nmap <Leader>x <Plug>(easymotion-s2)
nmap <Leader>f <Plug>(easymotion-sn)
```

I've set my init.vim as above.

There are **3** problems 

# Problem

https://user-images.githubusercontent.com/49837632/179131581-6e5663fc-ff24-4101-9180-fe324ab64d43.mp4

1. When I'm using `nmap <Leader>f <Plug>(easymotion-sn)`, the panel always pops up
2. The cursor jumps to the start of the next line, instead of where the indicator is.
3. The highlights of `ta` remains after jumping.

😄 thanks for your help!

**Comment by theol0403** [comment]
https://github.com/vscode-neovim/vscode-neovim/issues/910

If you have other issues, switch to hop or lightspeed.

**Comment by StaticESC** [comment]
@ZXYFrank I have the same problem. Instead of using easymotion, you may consider using hop and hop's `:HopPattern` Function.
