### ISSUE TITLE
 ViewportManager: No viewport for gridId: 1

### ISSUE THREAD

**Issue by AmelloAster** [vscode-neovim/vscode-neovim#976]
vscode os:
Version: 1.70.0-insider
Commit: 3da2d669a4dcf93938a262ba92f50b128ca7262a
Date: 2022-07-20T05:31:50.008Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.5.0

<img width="446" alt="image" src="https://user-images.githubusercontent.com/26178326/179916977-e3d2f0af-1d08-40bc-b1d5-ef91c7cf8e26.png">

**Comment by zbw8388** [comment]
Hi!
Were you able to reproduce it with an empty `init.vim`? Does the extension work correctly after seeing this message (especially cursor and highlight)?

**Comment by AmelloAster** [comment]
> I did some troubleshooting and it seems that there is a problem with the lightspeed plugin

**Comment by AmelloAster** [comment]
> 
<img width="795" alt="image" src="https://user-images.githubusercontent.com/26178326/180344013-b8199851-d462-4c1f-9dcb-f52c17d6bf11.png">

<img width="460" alt="image" src="https://user-images.githubusercontent.com/26178326/180344023-01162c7e-b151-49cb-9b38-3f1dba7cda3c.png">
I used a blank neovim init configuration, but the plugin still reports this error

**Comment by zbw8388** [comment]
What is your neovim version?

**Comment by AmelloAster** [comment]
> What is your neovim version?

<img width="347" alt="image" src="https://user-images.githubusercontent.com/26178326/180588797-7c7c907a-1a8d-478b-9102-511bf28745b0.png">

**Comment by zbw8388** [comment]
I am unable to reproduce this. Other things you might try would be to disable all other extensions, use an empty settings.json, or use a different nvim version. Lightspeed is broken likely due to your neovim build. I got errors when using that specific release but not with the stable release (0.7.2).

**Comment by Dashift** [comment]
I have same issue, and not fixed after I upgrade to 0.7.2

```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.2_1/share/nvim"

Run :checkhealth for more info
```

**Comment by yamatsum** [comment]
I'm in trouble with the same phenomenon
```
❯ v --version
NVIM v0.8.0-dev-nightly-238-g1a655b71a
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by yamatsum@R-MBP-14UBL-0023.local
```

**Comment by theol0403** [comment]
Fix not released yet.
