### ISSUE TITLE
ctrl + p shortcut not working as expected.

### ISSUE THREAD

**Issue by mansoorkhan96** [vscode-neovim/vscode-neovim#981]
Normally `ctrl + p` opens up Quick Open menu to search for files and `ctrl + p + p` opens up last opened file.

After installing this extension it behaves differently. Instead of opening the last opened file and starts navigating the list hence running the vscode command: `workbench.action.quickOpenSelectPrevious`

**Comment by zbw8388** [comment]
Try removing this keybinding and see if it works for you. To keep stuff consistent, you might also want to remove `Select Next in Quick Open`
![image](https://user-images.githubusercontent.com/60573138/181777708-234c87ca-2976-4793-8f71-f2b0885a702a.png)

**Comment by theol0403** [comment]
Not sure if there is a solution for this. C-p is used to navigate quick-pick for cmdline history, commands, etc. You can disable the binding if you want, but I think your usecase is too niche. 

Another solution might be to directly map `ctrl-p p` in vscode.
