### ISSUE TITLE
Duplicated insertion while typing korean

### ISSUE THREAD

**Issue by zuhanit** [vscode-neovim/vscode-neovim#984]
It seems something wrong in typing korean after update 0.0.89.

![녹화_2022_08_02_05_18_23_575](https://user-images.githubusercontent.com/36349353/182239184-4a1ac8c1-46f4-4800-aea2-3d869030955d.gif)

But when I downgraded vscode-neovim 0.0.88, it doesn't happen and everything works fine.

![녹화_2022_08_02_05_21_53_807](https://user-images.githubusercontent.com/36349353/182241120-1877ac68-d694-4696-9ad6-6f68dad3a082.gif)

Version: 1.69.2 (user setup)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:52.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by theol0403** [comment]
This might be caused by #900. @BTBMan could you look into this? Thanks!

**Comment by BTBMan** [comment]
@zuhanit Could you tell me what input method that you are using to reproduce? And It's that happend after type space key? I'm sorry I'm not a korean user and I tried to reproduce with my only Mac, but It didn't happend, But I will try my best to fix that.

**Comment by zuhanit** [comment]
I'm using default IME of Windows 11, from Microsoft. It happens after type space key, but can happen like below:

- Exit inserting mode

![녹화_2022_08_02_16_07_16_73](https://user-images.githubusercontent.com/36349353/182313361-53a120f2-7b50-4053-a3da-a7fa7b073b76.gif)

I pressed `ㄷ+ㅐ+ㅎ+ㅏ+ㄴ+ㅁ+ㅣ+ㄴ` and type ESC for exit.

- Just type little long word

![녹화_2022_08_02_16_08_10_449](https://user-images.githubusercontent.com/36349353/182313556-e4ab5487-0f7c-4722-a767-641e472d4cd7.gif)

I pressed `ㄷ+ㅐ+ㅎ+ㅏ+ㄴ+ㅁ+ㅣ+ㄴ+ㄱ+ㅜ+ㄱ` and type `ㅇ`(not `o`, `0`).

Type space key always produce characters before cursor.

![녹화_2022_08_02_16_12_41_170](https://user-images.githubusercontent.com/36349353/182314353-50ce2d5c-7cff-4ef3-adb9-3063c8736c6a.gif)

Please tell me if you need any information for solve this 👀

**Comment by 74th** [comment]
This also occurs in Japanese.


Version: 1.70.0
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:48.541Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.15.0-43-generic

Ubuntu 22.04
NeoVim v0.5.0-dev+1041-g1607dd071

![Screencast from 2022年08月07日 13時02分41秒](https://user-images.githubusercontent.com/1060011/183274881-f92d0813-c41c-4286-85f0-c3fc55359b0e.gif)

I typed the following

```
i[ENABLE JAPANESE INPUT]aiueo[SPACE]aiueo[ENTER]
```

It seems to occur when the Japanese conversion is started with the space key and then the next input is started without being confirmed with the enter key.

**Comment by snaka** [comment]
I'm facing same problem too (in Japanese).

Version: 1.70.0 (user setup)
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:16.462Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19043

Using with NeoVim on WSL2 (Ubuntu 20.04)

**Comment by vlwkaos** [comment]
0.0.89 has this bug. Use 0.0.88 until new release containing the revert
