### ISSUE TITLE
Ctrl-p and Ctrl-n not working as expected in visual mode

### ISSUE THREAD

**Issue by rradonic** [vscode-neovim/vscode-neovim#985]
In normal mode, Ctrl-p and Ctrl-n work as expected, moving the cursor one line up and one line down respectively.

In visual mode though, they move the cursor but they don't update the selection. "j" and "k" work as expected, moving the cursor up / down as well as updating the selection.

Expected behavior: In neovim and regular vim, Ctrl-p and Ctrl-n behave the same as "j" and "k" in visual mode, moving the cursor up / down as well as updating the selection.

**Comment by theol0403** [comment]
By default, C-p and C-n are not sent to neovim, and open vscode's command picker and opens a new file, respectively. Did you map this yourself? If so, how? The issue could be the way you did that - sending C-p and C-n to neovim should work. 

Second, neovim selections aren't synced with vscode, except when you open command picker and some other actions. Could this be what you are noticing? A "fake" visual highlight should still show though.

**Comment by rradonic** [comment]
Sorry, I forgot to mention, I'm on a Mac, which maps Command + p to the file picker and Command + n to opening a new file, while the Ctrl + p and Ctrl + n shortcuts move the cursor up and down. I did not remap these shortcuts, they work like this out of the box. I realize on Windows and Linux it's different.

**Comment by theol0403** [comment]
Try this:

```
  {
    "key": "ctrl+n",
    "command": "vscode-neovim.send",
    "args": "<C-n>",
    "when": "editorTextFocus && neovim.init && neovim.mode != insert || neovim.recording"
  },
  {
    "key": "ctrl+p",
    "command": "vscode-neovim.send",
    "args": "<C-p>",
    "when": "editorTextFocus && neovim.init && neovim.mode != insert || neovim.recording"
  }
```
