### ISSUE TITLE
CTRL-^ not working as expected

### ISSUE THREAD

**Issue by janzhen** [vscode-neovim/vscode-neovim#987]
`CTRL-^` do nothing in vscode-neovim, but in native neovim will swich to alternate file. Refers to `:h CTRL-^`. Can we have this feature in vscode-neovim?

```
							*CTRL-^* *CTRL-6*
CTRL-^			Edit the alternate file.  Mostly the alternate file is
			the previously edited file.  This is a quick way to
			toggle between two files.  It is equivalent to ":e #",
			except that it also works when there is no file name.
```

**Comment by zbw8388** [comment]
Try adding the following lines to your `keybindings.json` for a temporary solution:

```
    {
        "key": "ctrl+6",
        "command": "-workbench.action.focusSixthEditorGroup"
    },
    {
        "key": "ctrl+6",
        "command": "workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup",
        "when": "!activeEditorGroupEmpty"
    },
    {
        "key": "ctrl+6",
        "command": "workbench.action.quickOpenNavigateNextInEditorPicker",
        "when": "inEditorsPicker && inQuickOpen"
    }
```
Note that this is a bit different than the neovim default as it supports navigating to multiple files upon pressing ctrl-6 multiple times. I personally found it more powerful than neovim.

**Comment by janzhen** [comment]
> Try adding the following lines to your `keybindings.json` for a temporary solution:
> 
> ```
>     {
>         "key": "ctrl+6",
>         "command": "-workbench.action.focusSixthEditorGroup"
>     },
>     {
>         "key": "ctrl+6",
>         "command": "workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup",
>         "when": "!activeEditorGroupEmpty"
>     },
>     {
>         "key": "ctrl+6",
>         "command": "workbench.action.quickOpenNavigateNextInEditorPicker",
>         "when": "inEditorsPicker && inQuickOpen"
>     }
> ```
> 
> Note that this is a bit different than the neovim default as it supports navigating to multiple files upon pressing ctrl-6 multiple times. I personally found it more powerful than neovim. If you dislike this behavior, remove the last keybinding.

@zbw8388 Thank you so much. It works for me.

**Comment by theol0403** [comment]
Would you also be able to try

```
    {
        "key": "ctrl+6",
        "command": "vscode-neovim.send",
        "args": "<C-^>" 
    },
```

Perhaps the when clause should be fine tuned

**Comment by zbw8388** [comment]
I think it causes some bugs when the file we need to edit belongs to vscode (for example, `keybindings.json`, or any of the ipynb as vscode would go to a buffer with text in them). We might be able to fix them by creating associations. However, I think this vscode functionality is a superset of what neovim can offer. Maybe we should let vscode handle all file navigations (which includes `gd` and all that) as intellisense is one thing that we would like to preserve with this extension? 

BTW, I did see your comment but I need to find time to work on it.

**Comment by theol0403** [comment]
Youre right, it does have some bugs. I am a bit surprised however, because neovim jumplist and jumping to upper case marks *used* to be able to switch back to old files with no issues. Now it seems broken.

**Comment by jamestrew** [comment]
> If you want to make it the same as in neovim (without picker) you can also use something like this:
> 
>     {
>         "key": "ctrl+6",
>         "command": "runCommands",
>         "args":{
>             "commands": [
>                 "workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup",
>                 "list.select"
>             ]
>         },
>         "when": "editorTextFocus && neovim.init && neovim.mode == 'normal' && editorLangId not in 'neovim.editorLangIdExclusions'"
>     },

It's `"key": "ctrl+shift+6"` for anyone that wants to bind to `<c-^>`
