### ISSUE TITLE
Can you just use the path?

### ISSUE THREAD

**Issue by dyercode** [vscode-neovim/vscode-neovim#988]
By default if nvim is on the path can't you just use it? It's cool there's an override, but getting an error until I go in and type `nvim` into a box felt a bit :facepalm: 

edit: platform = linux

**Comment by justinmk** [comment]
Should definitely try that as a fallback. Often, however, users set $PATH in their shell config and expect it to work for GUI programs, which often don't inherit the same $PATH as an interactive terminal.

**Comment by dyercode** [comment]
Good thing this setting already exists for when it fails then 😉

**Comment by theol0403** [comment]
Good idea. Would you be able to make a PR for this? It should just involve changing the default configuration for the linux path setting from "" to "nvim".
