### ISSUE TITLE
[BUG] v0.0.89 causes flickering IME input

### ISSUE THREAD

**Issue by wenfangdu** [vscode-neovim/vscode-neovim#989]
This is the type of problem that causes me to migrate from VSCodeVim to vscode-neovim, but now vscode-neovim has it too, please fix this, I will stick with v0.0.88 for now.

v0.0.88

![STG 2022-08-02 15_31_02](https://user-images.githubusercontent.com/28700378/182317831-c9666e10-6ec1-4846-89b2-2730332b5c24.gif)

v0.0.89

![STG 2022-08-02 15_33_42](https://user-images.githubusercontent.com/28700378/182318310-59695a19-7bc3-4c48-8d48-2831b2e5c3a4.gif)

Notice in v0.0.89 the background IME text flickers all the time.

Seems to be caused by https://github.com/vscode-neovim/vscode-neovim/pull/900.

**Comment by theol0403** [comment]
Change reverted
