### ISSUE TITLE
Have `<C-n>` and `<C-p>` in cmdline work as <Down> and <Up> if completion candidates exist

### ISSUE THREAD

**Issue by Matts966** [vscode-neovim/vscode-neovim#991]
Currently, `<C-n>` and `<C-p>` works only as history next/prev.
It is great to have `<C-n>` and `<C-p>` in cmdline work as `<Down>` and `<Up>` if completion candidates exist.

**Comment by theol0403** [comment]
You can disable the history nav with 
![image](https://user-images.githubusercontent.com/16546293/182909745-5a23b57c-33f1-4ca5-9743-a783eeaaa188.png)

**Comment by theol0403** [comment]
If you are looking for smarter behaviour, please reopen.

**Comment by Matts966** [comment]
Could you reopen this issue? @theol0403 
The behavior below is the default in neovim, and it is great to have it in vscode-neovim too.

- If no completion candidates exist, `<C-p>` and `<C-n>` work as history navigators.
- If completion candidates exist, `<C-p>` and `<C-n>` work as completion candidate navigators.

Disabled history nav can not realize the behavior.
