### ISSUE TITLE
[Bug] In VSCode v1.70.0, `workbench.list.automaticKeyboardNavigation` is gone

### ISSUE THREAD

**Issue by wenfangdu** [vscode-neovim/vscode-neovim#995]
![image](https://user-images.githubusercontent.com/28700378/183329948-ed32f416-cec9-4ca6-84b2-a594b5f23905.png)

![image](https://user-images.githubusercontent.com/28700378/183330013-0ce7a1f1-c170-401f-a053-8b07517082bc.png)

This causes explorer list navigation not functional.

**Comment by theol0403** [comment]
Please make an issue in vscode.

**Comment by theol0403** [comment]
It seems like this is caused by https://code.visualstudio.com/updates/v1_70#_tree-find-control.
Are you sure explorer navigation is not functional? It still works for me - I think vscode decided to totally remove search-on-type. 
We should update the `/` binding to `list.find`.

**Comment by wenfangdu** [comment]
@theol0403 Oh, that would be why, the new UX is more visual.
