### ISSUE TITLE
Search match border is not rendered

### ISSUE THREAD

**Issue by shiro** [vscode-neovim/vscode-neovim#996]
By using the following colors in `settings.json`:
```
"workbench.colorCustomizations": {
    "editor.findMatchBorder": "#ff0000",
    "editor.findMatchBackground": "#0000ff30",
    "editor.findMatchHighlightBorder": "#ff0000",
    "editor.findMatchHighlightBackground": "#0000ff30",
}
```
The search result background should be a very transparent blue color and have a full opacity red outline, however the border setting seems not to work at all.

**Expected**:

![Screenshot_20220808_172050](https://user-images.githubusercontent.com/13651492/183373036-fd5730d4-8a5b-400d-a646-5c41a912eb21.png)

Works fine when using the global search function of VSCode.

**Actual**:

![Screenshot_20220808_172243](https://user-images.githubusercontent.com/13651492/183373389-95198884-a043-47d3-b2b9-a58ae1b25707.png)

The border is not rendered when using vim's search (`/`) function.

This is the case without modifying the extensions' `Vscode-neovim › Highlight Groups: Highlights` settings as well as with some changes I tried such as directly providing a color value or removing the `theme.` prefix from the defaults. I guess this is a bug since it looks like it was intended to work with the default settings.

**Comment by theol0403** [comment]
Looks like you need to use 
```
  "vscode-neovim.highlightGroups.highlights": {
    "Directory": "vim",
    "IncSearch": {
      "backgroundColor": "theme.editor.findMatchBackground",
      "borderColor": "theme.editor.findMatchBorder",
      "borderStyle": "solid",
      "borderWidth": "1px"
    },
    "Search": {
      "backgroundColor": "theme.editor.findMatchHighlightBackground",
      "borderColor": "theme.editor.findMatchHighlightBorder",
      "borderStyle": "solid",
      "borderWidth": "1px"
    },
    "Visual": {
      "backgroundColor": "theme.editor.selectionBackground"
    },
    "Conceal": "vim",
    "Substitute": "vim"
  },
```
Not sure if there is a way to make it work out of the box.

**Comment by shiro** [comment]
Thanks a lot!
Might want to put that somewhere in the readme if it's not in the defaults, or make it the default.

**Comment by theol0403** [comment]
You can add it to the wiki if you want. I don't know how to make it default, as adding a border shape with no color will still add a border.
