### ISSUE TITLE
Search replace with confirmation :%s/foo/bar/gc does not scroll automatically

### ISSUE THREAD

**Issue by arthurspa** [vscode-neovim/vscode-neovim#999]
When try a search/replace with confirmation in a long file vscode-nvim plugin won't scroll to the next instance to be replaced. It stays in the first viewport. It becomes cumbersome to search/replace since you have to scroll manually to know what are you about to replace.

---------------------------------------------------
vscode-neovim v0.0.89
NVIM v0.7.2
VS Code: 1.70.0 da76f93349a72022ca4670c1b84860304616aaa2 arm64
Model Name: MacBook Air
Chip: Apple M1
Mac OS Monterey v12.3.1

**Comment by theol0403** [comment]
It scrolls for me. Can you try with empty init.vim and settings.json?

**Comment by arthurspa** [comment]
Hi, 

It turns out I had a vim-go plugin in my init.vim. When I commented out it worked.

`Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }`

Thanks for the quick reply. I will close this issue since I don't see the point of using the `fatih/vim-go` plugin while in vscode + visconde-neovim.
